### PR TITLE
[Pal/Linux-SGX] Remove `stream_fd` from `pal_sec`

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Yeah, I'm still trying to refactor PAL globals :) This is quite a tiny PR, but it was easy to split this part out from the harder changes which will come next.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/272)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/272)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/272)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1145 at r1](https://reviewable.io/reviews/gramineproject/gramine/272#-MqP9qei7u0F1HiZybAq:-MqP9qej5ffIKGOEZiv2:b-xb58kd) ([raw file](https://github.com/gramineproject/gramine/blob/38c9f8d132a4b6bedf69d0e6906ed5efb10b7bb4/Pal/src/host/Linux-SGX/sgx_main.c#L1145)):*
> ```C
>     }
> 
>     int parent_pipe_fd = -1;
> ```

Not blocking, but why you didn't call it `parent_stream_fd`?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/272)* status: 9 of 15 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1145 at r1](https://reviewable.io/reviews/gramineproject/gramine/272#-MqP9qei7u0F1HiZybAq:-MqPIcEcDz9Td0OgO5FP:b-y8teq9) ([raw file](https://github.com/gramineproject/gramine/blob/38c9f8d132a4b6bedf69d0e6906ed5efb10b7bb4/Pal/src/host/Linux-SGX/sgx_main.c#L1145)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not blocking, but why you didn't call it `parent_stream_fd`?
</blockquote></details>

It's just inconsistent naming, fixed.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/272)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/272)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1145 at r1](https://reviewable.io/reviews/gramineproject/gramine/272#-MqP9qei7u0F1HiZybAq:-MqPWHfGDNeZg5jrNjRZ:b32wtd) ([raw file](https://github.com/gramineproject/gramine/blob/38c9f8d132a4b6bedf69d0e6906ed5efb10b7bb4/Pal/src/host/Linux-SGX/sgx_main.c#L1145)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's just inconsistent naming, fixed.
</blockquote></details>

ok

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/272)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/272)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
