### PR TITLE
[python] Compile aesm_pb2.py during build

### LINKED ISSUE #155: Compile protobuf from source
## Description of the problem

Currently we have compiled AESMD protobuf committed into sources (see `python/graminelibos/_aesm_pb2.py`). We should generate it from sources during build instead.

### PR DESCRIPTION
**Pull request by NieDzejkob**
## Description of the changes 

Fixes #155, and therefore also fixes gramineproject/gsc#65.

## How to test this PR? 

CI should suffice.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/701#-N5kVDgM29pH93wjHIDw):*
We don't do these in commit messages (to remove at rebase)
___
*[`python/graminelibos/meson.build` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/701#-N5kY5S32v-1fLRWwlXZ:-N5kY5S32v-1fLRWwlX_:b-4cqizc) ([raw file](https://github.com/gramineproject/gramine/blob/d07500a77f5a19bcd2caf696fef62b545a8ee9d3/python/graminelibos/meson.build#L32)):*
> ```Meson
>         input: 'aesm.proto',
>         output: 'aesm_pb2.py',
>         # we pass BUILD_ROOT because OUTDIR makes protoc output to python/graminelibos/python/graminelibos.
> ```

From what I've tested `protoc python/graminelibos/aesm.proto --python_out=A/ --proto_path=python/graminelibos/` outputs the file directly under `A`, so this should rather be `OUTDIR`? How does the current version work?
Update: I see how it works, `install_dir`. Still the above should be better, right?

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N5lcW4j1yijUq2KlUIv:-N5lcW4k2qZFFqXEeULT:bdmhgfl) (no related file):*
@dimakuv: I think this makes https://github.com/gramineproject/gsc/pull/71 partially obsolete?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N5lc_2v1oBg7YJcMoQp:-N5lc_2w2m6qH3Lry6qX:b-t34wjf) (no related file):*
> Fixes #155, and therefore gramineproject/gsc#65.

@niedzejkob: you need to also add "fixes" before the latter, otherwise it won't auto-close.

___

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

___
*[`python/graminelibos/meson.build` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/701#-N5kY5S32v-1fLRWwlXZ:-N5oSZnJ8u87pmECmoye:bciwt68) ([raw file](https://github.com/gramineproject/gramine/blob/d07500a77f5a19bcd2caf696fef62b545a8ee9d3/python/graminelibos/meson.build#L32)):*
> I don't think install_dir is really involved.

What you said applies to build (generation) time, not installing, so it might be involved.

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N5lcW4j1yijUq2KlUIv:-N5opMXwDp1JnvLwN3eD:b-xsyk0m) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Only the first commit from there (https://github.com/gramineproject/gsc/pull/71/commits/d6ab97a25463dee750b840520febdbf5ad5fe31b). But also, GSC is typically used with the stable release of Gramine (currently v1.2), so I think those workaround should still be kept, at least until v1.3 is released.
</blockquote></details>

The default is to use `master`? So, I wouldn't bother with the temporary workarounds for just a tiny part of the userbase (1.3 will be released soon, and this happens only to users with super new distros which also manually switched GSC to use 1.2 instead of `master`).

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N5lcW4j1yijUq2KlUIv:-N5p5DUb3h9cXV9z5-_G:b-nh12cj) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The default is to use `master`? So, I wouldn't bother with the temporary workarounds for just a tiny part of the userbase (1.3 will be released soon, and this happens only to users with super new distros which also manually switched GSC to use 1.2 instead of `master`).
</blockquote></details>

We actually wanted to change the default to `v1.2` (and periodically update to the next stable release), see https://github.com/gramineproject/gsc/pull/70

So... I don't know. I guess I don't mind removing the first commit there (extracting to a separate PR, for example, if someone hits this and definitely wants to use GSC).

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N5lcW4j1yijUq2KlUIv:-N6HJEhiCwZnB2HgWGZ6:b-av6h36) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We actually wanted to change the default to `v1.2` (and periodically update to the next stable release), see https://github.com/gramineproject/gsc/pull/70

So... I don't know. I guess I don't mind removing the first commit there (extracting to a separate PR, for example, if someone hits this and definitely wants to use GSC).
</blockquote></details>

So this PR is blocking https://github.com/gramineproject/gsc/pull/71. Should I wait for this PR, or should I just merge https://github.com/gramineproject/gsc/pull/71? @mkow 

___
___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/701#-N5nkOFVBS6eh8m2PC9z):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why did we observe it in GSC (i.e., in Docker images) but not in our CI? It also uses Ubuntu 20.04, where I hit that bug, and our CI also performs stuff like `apt update`. So why didn't CI fail?
</blockquote></details>

Any update on this? @niedzejkob

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N5lcW4j1yijUq2KlUIv:-N6IRGSd9IJazdD4c6vH:b-mjpse3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So this PR is blocking https://github.com/gramineproject/gsc/pull/71. Should I wait for this PR, or should I just merge https://github.com/gramineproject/gsc/pull/71? @mkow 
</blockquote></details>

Let's finish this one up quicky, I pinged @niedzejkob on priv.

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, all discussions resolved, "squash! " found in commit messages' one-liners

___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/701#-N5nkOFVBS6eh8m2PC9z):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

`apt-get update` in CI is run as a step during a Docker build. I would therefore assume that the relevant layer got cached and isn't actually executed each time CI runs. I currently can't access CI to check the logs for `apt` output.
</blockquote></details>

Ok, this sounds reasonable. Unblocking.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N6Ija3K5zcnFzDyNXXg:-N6Ija3K5zcnFzDyNXXh:b-pv6yqa) (no related file):*
I just realized that we need a corresponding change in GSC (installing `protobuf-compiler`). Blocking until I prepare such a PR and it is approved.

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N6Ija3K5zcnFzDyNXXg:-N6IoZ9s4swlym5a1l2g:b2l69v2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just realized that we need a corresponding change in GSC (installing `protobuf-compiler`). Blocking until I prepare such a PR and it is approved.
</blockquote></details>

https://github.com/gramineproject/gsc/pull/72 -- done, we need to merge this one first.

___

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, all discussions resolved, "squash! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N6Ija3K5zcnFzDyNXXg:-N6IrVGU7OCIN2ykyuW7:b-xjj5rl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/gramineproject/gsc/pull/72 -- done, we need to merge this one first.
</blockquote></details>

Done, gramineproject/gsc#72 is merged. We can proceed with this PR.

___

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/701)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/701#-N6Ija3K5zcnFzDyNXXg:-N6IylbZ1IQ5bV8-o1Ef:b-f9qh4v) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, gramineproject/gsc#72 is merged. We can proceed with this PR.
</blockquote></details>

Blocking to not accidentally merge this before I test it with the latest GSC. Will update this soon.

___

**Pull request merged**
