### PR TITLE
[Docs] Add README to the subprojects dir

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This is to explain the usage of each subproject in the Gramine (and its tools) codebase.

I just found it useful to add such a file, since I needed to analyze the usages today.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1654)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1654)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1654#-NjSZM7A3pR7tPWOnSRV:-NjSZM7A3pR7tPWOnSRW:b-e83ixq) (no related file):*
Renders like this: https://github.com/gramineproject/gramine/blob/dimakuv/add-subprojects-overview-readme/subprojects/README.rst

___

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1654)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1654)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`subprojects/README.rst` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1654#-NjVFJg74TnyovqdgHEF:-NjVFJg74TnyovqdgHEG:b93752f) ([raw file](https://github.com/gramineproject/gramine/blob/8d53ad646dc9aee74b33798b0061c7230ba59ce0/subprojects/README.rst#L16)):*
> ```reStructuredText
> - mbedTLS: used for all crypto- and TLS-operations in Gramine and its tools:
> 
>   - crypto (``libmbedcrypto.a``) is used in Gramine core, for e.g. AES-GCM on
> ```

-> `e.g.` (`for` is redundant)



_Code quote:_
```reStructuredText
for e.g
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1654)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`subprojects/README.rst` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1654#-NjVFJg74TnyovqdgHEF:-NjgVj201cfKfd3ZYeTd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d53ad646dc9aee74b33798b0061c7230ba59ce0/subprojects/README.rst#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `e.g.` (`for` is redundant)
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1654)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1654)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1654)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1654)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
