### PR TITLE
[tests] Allow POSIX shared memory objects in LTP manifest template

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 
Due to the lack of POSIX shared memory support, Gramine previously had an LTP configuration under SGX specifically for skipping those tests that require it.

Now that Gramine has added shared untrusted memory support and it's fine to use it in functionality tests, in this commit we mount the `/dev/shm` directory and allow files within it in the manifest to unblock the relevant LTP tests.

Fixes https://github.com/gramineproject/gramine/issues/51 (https://github.com/gramineproject/graphene/issues/1075).

## How to test this PR? 

Manual testing on some LTP tests previously skipped by the removed `ltp_bug_1075.cfg`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1718)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1718)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1718#-NoGHBjg32vrIMwX4-Hs:-NoGHBjg32vrIMwX4-Ht:bkirkuy) (no related file):*
@anjalirai-intel and @jinengandhi-intel -- you enabled LTP SGX tests in your local CI, right?

Can you take a look at this PR, and also explain how this fits into your local CI? Does this PR help you?

___

**Comment by anjalirai-intel** [comment]
We were able to run some extra tests which uses MAP_SHARED There are couple of tests which are failing post this support in manifest
1. mlock04
2. mmap01
3. mmap001
4. msync03
etc

We will continue to test further

**Review by dimakuv — COMMENTED** [review]
> There are couple of tests which are failing post this support in manifest

@anjalirai-intel Do you mean that these tests worked before (in your local CI, with `MAP_PRIVATE` workaround) and now they don't work (without the `MAP_PRIVATE` workaround but with this PR)? Did you analyze why? Is this a big problem?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1718#-:-NoQWfbJ0_BHAHFm1xun:b7k7lqg)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel)

**Comment by anjalirai-intel** [comment]
Yes, you are correct. they were initially working with MAP_PRIVATE flag change, now we reverted back again to MAP_SHARED and it is failing. I will share the detailed analysis soon

**Comment by anjalirai-intel** [comment]
I looked at couple of tests, they are failing because of [file_map does not currently support writable pass-through mappings on SGX](https://github.com/gramineproject/gramine/blob/a933017d35a7aa3330194521389838de6be53dc4/pal/src/host/linux-sgx/pal_files.c#L263..L268) not because of MAP_SHARED

So, this PR is okay.

But on the other side, is there any way we can avoid this error, one of the test we can refer is [mlock04](https://github.com/linux-test-project/ltp/blob/20230516/testcases/kernel/syscalls/mlock/mlock04.c)

**Review by dimakuv — APPROVED** [review]
> But on the other side, is there any way we can avoid this error, one of the test we can refer is [mlock04](https://github.com/linux-test-project/ltp/blob/20230516/testcases/kernel/syscalls/mlock/mlock04.c)

There is currently no way to avoid this error. So you have two options:
1. Either just keep your local CI as it was; don't use the trick in this PR
2. Or use this PR in your local CI, but add another manifest template that will be used for tests like `mlock04` (this option is probably quite complicated to implemented...)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1718#-:-NopLc1v7mYmudltCGc0:b-ob37n1)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1718#-NoGHBjg32vrIMwX4-Hs:-NopLzY-Czsu5Os0Ii9H:b9762m0) (no related file):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Yes, we have enabled LTP SGX tests. Sure, we can check if this PR helps. We will update the status
</blockquote></details>

Thanks @anjalirai-intel for the report. The PR looks good then, I'm resolving this comment.

___

**Comment by anjalirai-intel** [comment]
thanks @dimakuv  I will modify the test like we did earlier

**Review by mkow — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
