### PR TITLE
[common/protected_files] Remove unused fields

### PR DESCRIPTION
**Pull request by mwkmwkmwk**
## Description of the changes

Obvious cleanup.

## How to test this PR?

Already covered by existing tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — APPROVED** [review]
Thanks for this interesting feedback @llly.

> Changing `file_node_t` will break compatibility of Gramine protected file and SGX SDK protected file.

Are Protected Files currently compatible between Gramine and SGX SDK? I actually thought that the formats diverged already ~2 years ago.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789#-:-NrijpNR9w0AjZiwnW36:bx3cqde)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by llly — COMMENTED** [review]
The structure definition are still the same. Not tested, I suppose compatible.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789#-:-NrimBD-A0iLYK9mJJPG:bdxsa49)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — APPROVED** [review]
@llly We have this line:
```
#define PF_FILE_ID       0x46505f5346415247 /* GRAFS_PF */
```

Doesn't it make Gramine PFs incompatible?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789#-:-NriqRMo3EL4P69H0tf5:b-z6gx1l)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by llly — COMMENTED** [review]
You are right. incompatible. Should we bump PF version?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789#-:-NrisFibAg7tcW6sZxHF:b-jkh6i5)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mwkmwkmwk — COMMENTED** [review]
This is not an incompatible change — all removed fields are in in-memory structures only.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789#-:-NrjQ6hT35405t0SX_z8:b-fm14vy)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by llly — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1789)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
