### PR TITLE
[CI-Examples] Fix a typo in busybox Makefile

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
A typo slipped through review

## How to test this PR? 
Try building busybox example with and without this PR, both in normal and SGX version.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/602)

### CODE REVIEW

**Review by stefanberger — COMMENTED** [review]
Makes this work for me!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/602#-:-N2niJEG-2IVr4RRAmT5:b-vvqpn)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by stefanberger — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/602#-:-N2niPVRCnj2R4jU2-pe:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/602)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[`CI-Examples/busybox/Makefile` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/602#-N2oqdd40dJ3Ez0rcgKZ:-N2oqdd40dJ3Ez0rcgK_:b-v706g1) ([raw file](https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/CI-Examples/busybox/Makefile#L57)):*
> ```Makefile
> 		--output $<.sgx
> 
> busybox.token: busybox.sig:
> ```

Apparently we don't test busybox in any way in our CI.

I remember some discussion on this, where we decided that we won't test Busybox but we'll keep it in CI (because it is very convinient for fast checks of e.g. Gramine's file system). But I'm not sure why we decided not to test at all in CI -- we could just build it and run smth like `gramine-direct busybox echo "Hi"`.

@mkow @boryspoplawski @pwmarcz Anyone remembers why we decided **not** to put Busybox in the CI?

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/602)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

___
*[`CI-Examples/busybox/Makefile` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/602#-N2oqdd40dJ3Ez0rcgKZ:-N2pQZfL3s009u7UpHzU:b96o6ln) ([raw file](https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/CI-Examples/busybox/Makefile#L57)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't remember that (maybe it was before I came to the project), and I can't think of a good reason.
</blockquote></details>

I don't remember why, IMO we should enable it.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/602)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/602)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`CI-Examples/busybox/Makefile` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/602#-N2oqdd40dJ3Ez0rcgKZ:-N2qMEUm5w8W6i8awat2:b-umb8mz) ([raw file](https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/CI-Examples/busybox/Makefile#L57)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't remember why, IMO we should enable it.
</blockquote></details>

I think we did this because we already had `bash` to test and decided it's more complex hence better to test. This was before the examples split, so we just left it in the main repo.
At least I think this is what happen. Makes sense to enable it now though.

**Comment by dimakuv** [comment]
*[`CI-Examples/busybox/Makefile` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/602#-N2oqdd40dJ3Ez0rcgKZ:-N2qfbTZ8BCLMZrUUL74:beiadfd) ([raw file](https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/CI-Examples/busybox/Makefile#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think we did this because we already had `bash` to test and decided it's more complex hence better to test. This was before the examples split, so we just left it in the main repo.
At least I think this is what happen. Makes sense to enable it now though.
</blockquote></details>

Ok, I created #603 to fix it.

**Pull request merged**
