### PR TITLE
[LibOS] Clean up `select` and `poll` implementations

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Fixed some bugs, hopefully the code easier to manage too now.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: 0 of 15 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`libos/src/sys/libos_poll.c` line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NI9ojRn50AinN0hwYeN:-NI9ojRn50AinN0hwYeO:bl8ayss) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L113)):*
> ```C
>             continue;
> 
>             dev_tty_hack:;
> ```

Alternative version (I dislike both):



_Suggestion:_
```C
            if (!(ret == -EAGAIN && handle->uri && !strcmp(handle->uri, "dev:tty"))) {
                if (ret < 0) {
                    unlock(&map->lock);
                    goto out;
                }

                fds[i].revents = events;
                if (events) {
                    ret_events_count++;
                }

                continue;
            }
```

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`libos/src/fs/libos_fs_mem.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICH-dr-h5fYQB4L8jT:-NICH-dr-h5fYQB4L8jU:bal0w1c) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/fs/libos_fs_mem.c#L117)):*
> ```C
> int mem_file_poll(struct libos_mem_file* mem, file_off_t pos, int events, int* out_events) {
>     *out_events = events & (POLLOUT | POLLWRNORM);
>     if ((events & (POLLIN | POLLRDNORM)) && (pos < mem->size))
> ```

Why do you need the first condition? This will be cleared anyway in the below assignment if false.
___
*[`libos/src/fs/libos_fs_pseudo.c` line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICHRXZAejl0iYnnIZN:-NICHRXZAejl0iYnnIZO:bqfuiiy) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/fs/libos_fs_pseudo.c#L487)):*
> ```C
>             *out_events = 0;
>             if ((events & POLLIN) && node->dev.dev_ops.read)
>                 *out_events |= POLLIN;
> ```

Why no `POLLRDNORM`?
___
*[`libos/src/fs/libos_fs_pseudo.c` line 489 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICHW-S1aQa72aJ7IhH:-NICHW-S1aQa72aJ7IhI:bkvyl2r) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/fs/libos_fs_pseudo.c#L489)):*
> ```C
>                 *out_events |= POLLIN;
>             if ((events & POLLOUT) && node->dev.dev_ops.write)
>                 *out_events |= POLLOUT;
> ```

Why no `POLLWRNORM`?
___
*[`libos/src/sys/libos_poll.c` line 95 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICIVQ4DNymXgR2lZbN:-NICIVQ4DNymXgR2lZbO:bdrzjg7) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L95)):*
> ```C
>              * Initial 0,1,2 fds in Gramine are represented by "/dev/tty" (whatever that means)
>              * and have `generic_inode_poll` set as poll callback, which returns `-EAGAIN` on
>              * non-regular-file handles. In such case we let PAL do the actuall polling.
> ```

`actual`
___
*[`libos/src/sys/libos_poll.c` line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NI9ojRn50AinN0hwYeN:-NICJuzzE-9DGmA4E0dl:bfj3bkh) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L113)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Alternative version (I dislike both):
</blockquote></details>

Yeah, both versions are ugly. Let's keep the current one.
___
*[`libos/src/sys/libos_poll.c` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICK5GxAUihWtMmWw-1:-NICK5GxAUihWtMmWw-2:b-lfpm5r) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L120)):*
> ```C
>             pal_handle = __atomic_load_n(&handle->info.sock.pal_handle, __ATOMIC_ACQUIRE);
>             if (!pal_handle) {
>                 /* UNIX sockets that are still not connected have no `pal_handle`. */
> ```

Why only UNIX sockets? Can't other kinds of sockets (INET) have the same problem?
___
*[`libos/src/sys/libos_poll.c` line 239 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICL5Vf14HvpoxcvjFl:-NICL5Vf14HvpoxcvjFm:bcnp098) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L239)):*
> ```C
> 
>     if (tsp) {
>         if (is_user_memory_writable_no_skip(tsp, sizeof(*tsp))) {
> ```

Actually, why do we care about `skip` vs `no_skip` versions? Isn't `libos.check_invalid_pointers = false` already gives you **no guarantees** what happens at runtime, so the user is on his own?
___
*[`libos/src/sys/libos_poll.c` line 344 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICLjSL5TL3qiRPQK7j:-NICLjSL5TL3qiRPQK7k:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L344)):*
> ```C
>     long ret = do_select(nfds, read_set, write_set, except_set, tv ? &timeout_us : NULL);
> 
>     if (tv && is_user_memory_writable_no_skip(tv, sizeof(*tv))) {
> ```

ditto
___
*[`libos/src/sys/libos_poll.c` line 382 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICLtTw07tEGgR5ePu-:-NICLtTw07tEGgR5ePu0:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L382)):*
> ```C
>     long ret = do_select(nfds, read_set, write_set, except_set, tsp ? &timeout_us : NULL);
> 
>     if (tsp && is_user_memory_writable_no_skip(tsp, sizeof(*tsp))) {
> ```

ditto
___
*[`libos/test/ltp/ltp.cfg` line 1364 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICHlC1A-XMhj2bnx7B:-NICHlC1A-XMhj2bnx7C:bud54lg) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/test/ltp/ltp.cfg#L1364)):*
> ```INI
> 
> [personality02]
> skip = yes
> ```

Could you add a comment why you added this?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`libos/src/fs/libos_fs_mem.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICH-dr-h5fYQB4L8jT:-NIEpfEW4PNlUcCmD_6f:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/fs/libos_fs_mem.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need the first condition? This will be cleared anyway in the below assignment if false.
</blockquote></details>

Done.
___
*[`libos/src/fs/libos_fs_pseudo.c` line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICHRXZAejl0iYnnIZN:-NIEqGHRBnN0RyuZe44M:b-us6i9c) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/fs/libos_fs_pseudo.c#L487)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why no `POLLRDNORM`?
</blockquote></details>

Done.
(leftover from an intermediate version, which handled those in actual poll syscall code
___
*[`libos/src/fs/libos_fs_pseudo.c` line 489 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICHW-S1aQa72aJ7IhH:-NIEqG1j8vHAmpwuRw90:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/fs/libos_fs_pseudo.c#L489)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why no `POLLWRNORM`?
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 95 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICIVQ4DNymXgR2lZbN:-NIEqTJLEj_ajBfKkmug:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`actual`
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICK5GxAUihWtMmWw-1:-NIEqdaJAfhwo26l6kqj:b-p69atx) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why only UNIX sockets? Can't other kinds of sockets (INET) have the same problem?
</blockquote></details>

No, only UNIX sockets. IP sockets have pal handles right from beginning.
(also this code was already here before this PR)
___
*[`libos/src/sys/libos_poll.c` line 239 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICL5Vf14HvpoxcvjFl:-NIEqvHx9fI8wjWdL-On:bwm7z3j) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L239)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why do we care about `skip` vs `no_skip` versions? Isn't `libos.check_invalid_pointers = false` already gives you **no guarantees** what happens at runtime, so the user is on his own?
</blockquote></details>

But this can be a valid pointer, just not writable (RO memory). Added a comment.
___
*[`libos/src/sys/libos_poll.c` line 344 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICLjSL5TL3qiRPQK7j:-NIErMWK9RtUDpJlrFBs:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L344)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`libos/src/sys/libos_poll.c` line 382 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICLtTw07tEGgR5ePu-:-NIErNr1Ae0_qLT5Krwm:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L382)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`libos/test/ltp/ltp.cfg` line 1364 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICHlC1A-XMhj2bnx7B:-NIErRHP3oKQi0iTTRmn:b-b20lqf) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/test/ltp/ltp.cfg#L1364)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment why you added this?
</blockquote></details>

Because we do not implement `personality` syscall? This test is just badly written and does not even check return value. It was "working" before, because it tests something we did not do, but should have done in `select`.
Anyway, do we want these comments that a syscall is not implemented in cases where the syscall and test name are the same?

**Review by yamahata — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: 12 of 15 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/sys/libos_poll.c` line 237 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NIGCfG09uKdU8doJIAc:-NIGCfG09uKdU8doJIAd:b5p1qin) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L237)):*
> ```C
> 
>     ret = do_poll(fds, nfds, tsp ? &timeout_us : NULL);
> ```

signal mask isn't restored to the orignal state.
___
*[`libos/src/sys/libos_poll.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NIGE1Cv2PyB99W7OrVS:-NIGE1Cv2PyB99W7OrVT:b-8koift) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L239)):*
> ```C
> 
>     /* If `tsp` is in read-only memory, skip the update. */
>     if (tsp && is_user_memory_writable_no_skip(tsp, sizeof(*tsp))) {
> ```

If g_check_invalid_ptrs is true, -EFAULT should be returned.
___
*[`libos/src/sys/libos_poll.c` line 381 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NIGCkn4EUQvHyKMdEhN:-NIGCkn4EUQvHyKMdEhO:b-a7lftt) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L381)):*
> ```C
> 
>     long ret = do_select(nfds, read_set, write_set, except_set, tsp ? &timeout_us : NULL);
> ```

Signal mask isn't restored to the orignal state.

**Review by yamahata — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: 14 of 15 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 19 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NIGEi7q2SYuahUWXxlx):*
Please mention that FS_POLL_* is dumped and POLL_* is adapted.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: 14 of 15 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[`-- commits` line 19 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NIGEi7q2SYuahUWXxlx):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Please mention that FS_POLL_* is dumped and POLL_* is adapted.
</blockquote></details>

IMO there's no point - this is only a minor part of the PR and doesn't seem important at all
___
*[`libos/src/sys/libos_poll.c` line 237 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NIGCfG09uKdU8doJIAc:-NIGKlrzDXzuuX8NE8_k:beytugk) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L237)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

signal mask isn't restored to the orignal state.
</blockquote></details>

It restored while returning to userapp in `libos_emulate_syscall`
___
*[`libos/src/sys/libos_poll.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NIGE1Cv2PyB99W7OrVS:-NIGL3fB3tZuO98Q_ww9:bp8g38r) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L239)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

If g_check_invalid_ptrs is true, -EFAULT should be returned.
</blockquote></details>

No, see the comment above this `if`
___
*[`libos/src/sys/libos_poll.c` line 381 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NIGCkn4EUQvHyKMdEhN:-NIGLG890h49zhAEf-OP:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L381)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Signal mask isn't restored to the orignal state.
</blockquote></details>

ditto

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @yamahata)

___
*[`libos/src/sys/libos_poll.c` line 239 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICL5Vf14HvpoxcvjFl:-NIYV_Y3Ciw98VzcdudO:b3tsizh) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/src/sys/libos_poll.c#L239)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But this can be a valid pointer, just not writable (RO memory). Added a comment.
</blockquote></details>

I got it now.
___
*[`libos/test/ltp/ltp.cfg` line 1364 at r2](https://reviewable.io/reviews/gramineproject/gramine/1067#-NICHlC1A-XMhj2bnx7B:-NIYVeZd9vRd8nM8XoHD:b-28genv) ([raw file](https://github.com/gramineproject/gramine/blob/af40f6186632d8d299e2ae9d0b87875e79ff9c7d/libos/test/ltp/ltp.cfg#L1364)):*
> It was "working" before, because it tests something we did not do, but should have done ...

Ah, got it. No need for any comments then.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 4 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[`libos/include/libos_fs.h` line 949 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NKTYLnr0xNKPjgATg1z:-NKTYLnr0xNKPjgATg2-:b834v5n) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/include/libos_fs.h#L949)):*
> ```objc
> int generic_inode_hstat(struct libos_handle* hdl, struct stat* buf);
> file_off_t generic_inode_seek(struct libos_handle* hdl, file_off_t offset, int origin);
> int generic_inode_poll(struct libos_handle* hdl, int events, int* out_events);
> ```

In the function above you named it `in_events`. Are they different or you just didn't update all the names when changing them at some point?



_Code quote:_
```objc
int events
```
___
*[`libos/src/sys/libos_poll.c` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NKnQrQ_4Qy8fKpyxt86:-NKnQrQ_4Qy8fKpyxt87:b-8wbtcl) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L2)):*
> /* Copyright (C) 2014 Stony Brook University

This should be dropped, I think you rewrote this whole implementation, the only not-rewritten part is in `pselect6`, but it's also authored by you in some older commit.
___
*[`libos/src/sys/libos_poll.c` line 141 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NKnYyxZ3OhacOORzQx6:-NKnYyxZ3OhacOORzQx7:bn6c96o) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L141)):*
> ```C
>         libos_handles[i] = handle;
>         get_handle(handle);
>         pal_handles[i] = pal_handle;
> ```

The invariants of this loop were pretty hard for me to analyze without any comments/asserts. I see that for each `i` either `fds[i].revents` is set or `libos_handles[i]` + `pal_handles[i]` are.
Could you document this at the top of the loop? It will be easier to reason about this code with such a hint.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[`libos/include/libos_fs.h` line 949 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NKTYLnr0xNKPjgATg1z:-NKsshHLETWK-pz-GryQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/include/libos_fs.h#L949)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In the function above you named it `in_events`. Are they different or you just didn't update all the names when changing them at some point?
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NKnQrQ_4Qy8fKpyxt86:-NKstFHAEu58wjp6lxiA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> /* Copyright (C) 2014 Stony Brook University

This should be dropped, I think you rewrote this whole implementation, the only not-rewritten part is in `pselect6`, but it's also authored by you in some older commit.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 141 at r3](https://reviewable.io/reviews/gramineproject/gramine/1067#-NKnYyxZ3OhacOORzQx6:-NKsuVzb0-bZ7H7Jv4k6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/00dff0e368f4d39bed106138908dd07deb391479/libos/src/sys/libos_poll.c#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The invariants of this loop were pretty hard for me to analyze without any comments/asserts. I see that for each `i` either `fds[i].revents` is set or `libos_handles[i]` + `pal_handles[i]` are.
Could you document this at the top of the loop? It will be easier to reason about this code with such a hint.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @yamahata)

**Review by yamahata — DISMISSED** [review]
> Reviewed 6 of 12 files at r1, 4 of 5 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1067)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
