### PR TITLE
Attempt to fix alpine

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Attempt to fix the alpine pipeline.

## How to test this PR? 

CI/CD

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)

### CODE REVIEW

**Comment by oshogbo** [comment]
Jenkins, test pkg-apk-alpine3.17 please

**Comment by oshogbo** [comment]
Jenkins, test pkg-apk-alpine3.17 please

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`.ci/alpine3.17.dockerfile` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/1942#-O2YUAc-5MyJdP6tTYqm:-O2YUAc-5MyJdP6tTYqn:b-c1iaj5) ([raw file](https://github.com/gramineproject/gramine/blob/38d48fe7801e1e987fadd6c833f24d55d285d24c/.ci/alpine3.17.dockerfile#L11)):*
> ```Dockerfile
> 
> COPY packaging/alpine/APKBUILD /APKBUILD
> RUN adduser -u 1000 --disabled-password abuilder && \
> ```

1000 is the Jenkins user (on the host)? Is it guaranteed to be 1000? Can you add a comment about this hard-coded value here?

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`.ci/alpine3.17.dockerfile` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/1942#-O2YUAc-5MyJdP6tTYqm:-O2Z91YE2WlgZm21giwP:bikly45) ([raw file](https://github.com/gramineproject/gramine/blob/38d48fe7801e1e987fadd6c833f24d55d285d24c/.ci/alpine3.17.dockerfile#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

1000 is the Jenkins user (on the host)? Is it guaranteed to be 1000? Can you add a comment about this hard-coded value here?
</blockquote></details>

It's not on the host, it's from what user is used inside Docker container.
Here is how the pipeline is run by Jenkins:
```
docker run -t -d -u 1000:1001
```
I have added the comment as requested.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1942#-O2_I5AiAyye3dgvLPJF):*
Missing verb

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1942#-O2_I5AiAyye3dgvLPJF):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Missing verb
</blockquote></details>

Ok, maybe something like that:
```
[CI] Ensure a signing key is trusted for indexing during abuild
```

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1942)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
