### PR TITLE
[LibOS] Clear exception flags in the MXCSR register

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

According to the 3.4.1 section in the System V ABI document (version 0.99.6), all floating-point exception status flags should be cleared.

In LibOS, we have to clear MXCSR flags manually as we use a floating expression in the `proc_cpuinfo_atod` function.
This can change the MXCSR register (and actually does).

The bug in the test was reported by @mkow (thank you, nice catch).

## Useful links

[System V Application Binary Interface AMD64 Architecture Processor Supplement Draft Version 0.99.6](https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf
)

## How to test this PR? 

The test has been modified to reflect this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1324)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1324)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1324)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1324)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1324)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1324)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1324)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest Docs please (network issues on some of the nodes?)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-20.04 please

**Pull request merged**
