### PR TITLE
[CI] Fix linux-sgx-vm-gcc-release pipeline after update to Debian 12

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The Jenkins worker node for this pipeline was updated from Debian 11 to Debian12, which broke the pipeline. This commit contains assorted fixes required to make it work again.

The corresponding PR is https://github.com/gramineproject/device-testing-tools/pull/10 (must be merged first).

## How to test this PR? 

Check the status of `linux-sgx-vm-gcc-release` job.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1512)

### CODE REVIEW

**Review by woju — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1512)* status: 3 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1512)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1512)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1512#-NcgaTv-4ZxRHm790OK3:-NcgaTv-4ZxRHm790OK4:b-bjf6kr) ([raw file](https://github.com/gramineproject/gramine/blob/a0d4e2ab55837a93f93498e207aba3977a6ab3a5/.ci/lib/stage-build-sgx-vm.jenkinsfile#L8)):*
> ```
>         git clone https://github.com/gramineproject/device-testing-tools.git
>         cd device-testing-tools
>         git checkout cc9476535bff2d3a68274b8d2ceb7f84b0dce054 # FOR TESTING ONLY, REMOVE ON MERGE
> ```

Blocking to not forget.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1512)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1512)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
