### PR TITLE
[common] Refactor Protected Files, part 3

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This commit refactors PF code without changing functionality (part 3 in a series of commits). In particular, this commit simplifies function `ipf_update_all_data_and_mht_nodes()`.

Extracted from https://github.com/gramineproject/gramine/pull/1841 at the request of @mkow.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1868)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1868)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files.c` line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/1868#-NwtI9KkDmIAf_M2YJZ0:-NwtI9KkDmIAf_M2YJZ1:bjndwqe) ([raw file](https://github.com/gramineproject/gramine/blob/1e42aaaa3632aa5c791bd46083d86df52644dc7b/common/src/protected_files/protected_files.c#L207)):*
> ```C
>     file_node_t** mht_array = NULL;
>     pf_status_t status;
>     void* data;
> ```

Please make this loop-scoped.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1868)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/src/protected_files/protected_files.c` line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/1868#-NwtI9KkDmIAf_M2YJZ0:-NwtKw9f-yXvAaaUNYm9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1e42aaaa3632aa5c791bd46083d86df52644dc7b/common/src/protected_files/protected_files.c#L207)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please make this loop-scoped.
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1868)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1868)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1868)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
