### PR TITLE
Drop support for `loader.preload` and URIs in `libos.entrypoint` in manifests

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Both were long deprecated, time to get rid of them for the next release.

Corresponding examples PR: https://github.com/gramineproject/examples/pull/16.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by pwmarcz — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Documentation/manifest-syntax.rst, line 826 at r1](https://reviewable.io/reviews/gramineproject/gramine/404#-Mwfyom96QbNWlAS9PaD:-Mwfyom96QbNWlAS9PaE:beym1ae) ([raw file](https://github.com/gramineproject/gramine/blob/5b1fc29b5e871c608ea02bbe8c37b3121d769094/Documentation/manifest-syntax.rst#L826)):*
> ```reStructuredText
> ------------------
> 
> There are no deprecated options at the time.
> ```

Not true after you rebase :)

**Review by dimakuv — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)* status: 0 of 19 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 826 at r1](https://reviewable.io/reviews/gramineproject/gramine/404#-Mwfyom96QbNWlAS9PaD:-Mwg3kxDBzDtH15MGCh1:bdiecbc) ([raw file](https://github.com/gramineproject/gramine/blob/5b1fc29b5e871c608ea02bbe8c37b3121d769094/Documentation/manifest-syntax.rst#L826)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Not true after you rebase :)
</blockquote></details>

Right :)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 17 of 19 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Documentation/manifest-syntax.rst, line 826 at r1](https://reviewable.io/reviews/gramineproject/gramine/404#-Mwfyom96QbNWlAS9PaD:-Mwg8LeE69tZjyDKLj7O:bhwq5iv) ([raw file](https://github.com/gramineproject/gramine/blob/5b1fc29b5e871c608ea02bbe8c37b3121d769094/Documentation/manifest-syntax.rst#L826)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Right :)
</blockquote></details>

You should still delete this section, though?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)* status: 17 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 826 at r1](https://reviewable.io/reviews/gramineproject/gramine/404#-Mwfyom96QbNWlAS9PaD:-Mwg9s7NBuczO38S6Av1:b-828ud2) ([raw file](https://github.com/gramineproject/gramine/blob/5b1fc29b5e871c608ea02bbe8c37b3121d769094/Documentation/manifest-syntax.rst#L826)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

You should still delete this section, though?
</blockquote></details>

Oh 🤦

**Review by pwmarcz — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/404)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
