### PR TITLE
[PAL] replace `HANDLE_HDR ` macros with inline code

### PR DESCRIPTION
**Pull request by billionairiam**
## Description of the changes 
Remove `HANDLE_HDR `macros and replace with inline code 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/745#-N6lOJd737CcKnSH1KyE:-N6lOJd737CcKnSH1KyF:b-ssv7bg) (no related file):*
@billionairiam You seem to have misunderstood the request to "inline code".

We didn't mean to replace the macro with an "inline function". We meant literally -- inline the code that is hidden behind the `HANDLE_HDR` macro into the usages of this macro.

E.g., a line like this:
```
    assert(handle && HANDLE_HDR(handle)->type == PAL_TYPE_EVENT);
```
should be changed to this:
```
    assert(handle && handle->hdr.type == PAL_TYPE_EVENT);
```

(this example is taken from https://github.com/gramineproject/gramine/blob/bf998a227065bfdc07937146784f95840ec1707c/pal/src/pal_events.c#L16)

So this PR should modify many files, removing the `HANDLE_HDR` macro completely. This de-obfuscates the source code.

___

**Comment by billionairiam** [comment]
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)_ status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam)
> 
> _[a discussion](https://reviewable.io/reviews/gramineproject/gramine/745#-N6lOJd737CcKnSH1KyE:-N6lOJd737CcKnSH1KyF:b-ssv7bg) (no related file):_ @billionairiam You seem to have misunderstood the request to "inline code".
> 
> We didn't mean to replace the macro with an "inline function". We meant literally -- inline the code that is hidden behind the `HANDLE_HDR` macro into the usages of this macro.
> 
> E.g., a line like this:
> 
> ```
>     assert(handle && HANDLE_HDR(handle)->type == PAL_TYPE_EVENT);
> ```
> 
> should be changed to this:
> 
> ```
>     assert(handle && handle->hdr.type == PAL_TYPE_EVENT);
> ```
> 
> (this example is taken from
> 
> https://github.com/gramineproject/gramine/blob/bf998a227065bfdc07937146784f95840ec1707c/pal/src/pal_events.c#L16
> 
> )
> So this PR should modify many files, removing the `HANDLE_HDR` macro completely. This de-obfuscates the source code.

OK, I will refine it!

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @billionairiam)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/745#-N6lOJd737CcKnSH1KyE:-N6qL6yx4kJbQs_-KQTs:ba80vs9) (no related file):*
<details><summary><i>Previously, billionairiam (Liang Ma) wrote…</i></summary><blockquote>

OK, I will refine it!
</blockquote></details>

Please don't forget to leave the "Done" comments in Reviewable when you're done with some work.

From what I understood, you're done with the changes I requested. Please put "Done" in this thread then.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/745#-N6qMOnuE9SNBOATgW6t:-N6qMOnuE9SNBOATgW6u:b-g6b97f) (no related file):*
Thanks, now it looks good! I'll start the tests in our CI, let's see if we fixed all such occurences.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/745#-N6qLNXm95rWVoQObhEp):*
You have a wrong order of lines :) It shoud have been:
```
[PAL] replace HANDLE_HDR macros with inline code

Signed-off-by: billionairiam <liang3.ma@intel.com>
```

No need to do anything now, we can fix it during the final rebase.
___
*[`pal/include/pal/pal.h` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/745#-N6qLgif5XvF9pEBeQRM:-N6qLgif5XvF9pEBeQRN:buo7fnn) ([raw file](https://github.com/gramineproject/gramine/blob/28f198e848e599bd71746eb2202f3772e57076e9/pal/include/pal/pal.h#L63)):*
> ```objc
> static inline void init_handle_hdr(PAL_HANDLE handle, int pal_type) {
>     handle->hdr.type = pal_type;
> }
> ```

In follow-up PRs, we'll need to remove also these three macros/functions in the same way:
- `PAL_GET_TYPE`
- `UNKNOWN_HANDLE`
- `init_handle_hdr`

**Review by billionairiam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @billionairiam and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/745#-N6lOJd737CcKnSH1KyE:-N6qPVEF7EItvI6uBBcJ:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't forget to leave the "Done" comments in Reviewable when you're done with some work.

From what I understood, you're done with the changes I requested. Please put "Done" in this thread then.
</blockquote></details>

Done.

___

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @billionairiam and @dimakuv)

___
*[`pal/include/pal/pal.h` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/745#-N6qLgif5XvF9pEBeQRM:-N6rEX4m4BeuMzH3HTbS:bxtw1si) ([raw file](https://github.com/gramineproject/gramine/blob/28f198e848e599bd71746eb2202f3772e57076e9/pal/include/pal/pal.h#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In follow-up PRs, we'll need to remove also these three macros/functions in the same way:
- `PAL_GET_TYPE`
- `UNKNOWN_HANDLE`
- `init_handle_hdr`
</blockquote></details>

`init_handle_hdr` is not so obvious, we might need it at some point - we might add more common fields other than type. I wouldnt remove it yet.

**Comment by billionairiam** [comment]
> > Reviewed 15 of 15 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)_ status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @billionairiam and @dimakuv)
> 
> _[`pal/include/pal/pal.h` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/745#-N6qLgif5XvF9pEBeQRM:-N6rEX4m4BeuMzH3HTbS:bxtw1si) ([raw file](https://github.com/gramineproject/gramine/blob/28f198e848e599bd71746eb2202f3772e57076e9/pal/include/pal/pal.h#L63)):_
> 
> Previously, dimakuv (Dmitrii Kuvaiskii) wrote…
> `init_handle_hdr` is not so obvious, we might need it at some point - we might add more common fields other than type. I wouldnt remove it yet.

So can I do those modifies in this PR

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @billionairiam and @dimakuv)

___
*[`pal/include/pal/pal.h` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/745#-N6qLgif5XvF9pEBeQRM:-N6rLJDdDBQPwy4A2oXh:b-mnkft) ([raw file](https://github.com/gramineproject/gramine/blob/28f198e848e599bd71746eb2202f3772e57076e9/pal/include/pal/pal.h#L63)):*
<details><summary><i>Previously, billionairiam (Liang Ma) wrote…</i></summary><blockquote>

So can I do those modifies in this PR
</blockquote></details>

No, please create another PR

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @billionairiam and @dimakuv)

___
*[`pal/include/pal/pal.h` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/745#-N6qLgif5XvF9pEBeQRM:-N6rLnpXBNHkf9U_SxJ1:b-i823li) ([raw file](https://github.com/gramineproject/gramine/blob/28f198e848e599bd71746eb2202f3772e57076e9/pal/include/pal/pal.h#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, please create another PR
</blockquote></details>

Or actually, they are super related, so maybe it makes sens to handle it now? I don't mind either, I just seen @dimakuv asked for a follow-up PR.
cc @mkow @dimakuv

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @billionairiam)

___
*[`pal/include/pal/pal.h` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/745#-N6qLgif5XvF9pEBeQRM:-N6rfiIu8xFiClCpc8Es:b3y2tdw) ([raw file](https://github.com/gramineproject/gramine/blob/28f198e848e599bd71746eb2202f3772e57076e9/pal/include/pal/pal.h#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Or actually, they are super related, so maybe it makes sens to handle it now? I don't mind either, I just seen @dimakuv asked for a follow-up PR.
cc @mkow @dimakuv 
</blockquote></details>

I would prefer them to be in three different PRs. Mainly for @billionairiam's learning -- it is easier to learn our flows on three small PRs than on one bigger one.

**Comment by billionairiam** [comment]
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)_ status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @billionairiam)
> 
> _[`pal/include/pal/pal.h` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/745#-N6qLgif5XvF9pEBeQRM:-N6rfiIu8xFiClCpc8Es:b3y2tdw) ([raw file](https://github.com/gramineproject/gramine/blob/28f198e848e599bd71746eb2202f3772e57076e9/pal/include/pal/pal.h#L63)):_
> 
> Previously, boryspoplawski (Borys Popławski) wrote…
> I would prefer them to be in three different PRs. Mainly for @billionairiam's learning -- it is easier to learn our flows on three small PRs than on one bigger one.

Thanks!!!!!!!!!!!!!

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam and @boryspoplawski)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/745#-N7GYdEc7JpcKMzRMHPE):*
@billionairiam I changed the Signed-off-by name here (from `billionairiam` to `Liang Ma`), that's correct, right? I need your explicit approval.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 10 of 15 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @billionairiam)

**Review by billionairiam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/745#-N7GYdEc7JpcKMzRMHPE):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@billionairiam I changed the Signed-off-by name here (from `billionairiam` to `Liang Ma`), that's correct, right? I need your explicit approval.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

**Review by dimakuv — APPROVED** [review]
> Dismissed @boryspoplawski from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/745)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
