### PR TITLE
[LibOS,PAL,Docs] Remove deprecated syntax for Protected Files

### LINKED ISSUE #1100: [LibOS,PAL/Linux-SGX] Reenable `test_002_attestation_deprecated` on EDMM-enabled machines
### Description of the problem

PR https://github.com/gramineproject/gramine/pull/1054 implemented an initial version of EDMM support.

There is some bug such that `test_002_attestation_deprecated` and `test_003_attestation_deprecated_stdio` LibOS regression tests failed, for no apparent reason. @boryspoplawski didn't have time to debug them, so someone else has to do the debugging, fix the issue and re-enable these tests.

The root cause is not about EDMM, but about the DCAP remote-attestation infrastructure. We mention EDMM here simply because the only machine with the DCAP remote-attestation infrastructure is used for testing EDMM.

### Steps to reproduce

Run these two regression tests on a EDMM-enabled machine (e.g., on the `Jenkins-SGX-EDMM` pipeline).

### Gramine commit hash

Branch `borys/edmm`

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The following syntax was deprecated in Gramine v1.2:
- `sgx.protected_files`
- `sgx.protected_mrenclave_files`
- `sgx.protected_mrsigner_files`
- `sgx.insecure__protected_files_key`

Now that the next version of Gramine will be v1.5, we can safely remove this syntax.

Closes #1100 (will not be relevant anymore).

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1252)

### CODE REVIEW

**Review by kailun-qin — COMMENTED** [review]
Interesting... I'm working on a very similar patch today after reviewing your PR of "exposing SGX sealing keys" (which reminded me of this deprecation... actually all that have passed the deprecation period). :)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1252#-:-NRXXcN-AUG1Ff2TU_ef:b-in8rb2)* status: 0 of 14 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 1002 at r2](https://reviewable.io/reviews/gramineproject/gramine/1252#-NRX_-Hk1GnhTD_d3OTb:-NRX_-Hk1GnhTD_d3OTc:bl5kcxb) ([raw file](https://github.com/gramineproject/gramine/blob/43101b8fa3fd4c1cd6c9304c2094ce009627efb3/Documentation/manifest-syntax.rst#L1002)):*
> ```reStructuredText
> ::
> 
>    fs.insecure__protected_files_key = "[32-character hex value]"
> ```

What about here in the attestation doc: https://github.com/gramineproject/gramine/blob/43101b8fa3fd4c1cd6c9304c2094ce009627efb3/Documentation/attestation.rst?plain=1#L220-L227.

**Review by dimakuv — COMMENTED** [review]
@kailun-qin Maybe then incorporate relevant (and not present in my PR) changes as review comments here?

Also, you can do the second PR in the series then, after this one is merged -- removing `fs.mount.blabla` syntax and `sgx.allowed_files.blabla` + `sgx.trusted_files.blabla` syntax.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1252#-:-NRXpZTo7an9EHqOjkx_:bplanbb)* status: 0 of 14 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1252)* status: 0 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Documentation/manifest-syntax.rst` line 1002 at r2](https://reviewable.io/reviews/gramineproject/gramine/1252#-NRX_-Hk1GnhTD_d3OTb:-NRXq6x20_fuxQoHebK-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/43101b8fa3fd4c1cd6c9304c2094ce009627efb3/Documentation/manifest-syntax.rst#L1002)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about here in the attestation doc: https://github.com/gramineproject/gramine/blob/43101b8fa3fd4c1cd6c9304c2094ce009627efb3/Documentation/attestation.rst?plain=1#L220-L227.
</blockquote></details>

Done.

**Review by kailun-qin — COMMENTED** [review]
> Maybe then incorporate relevant (and not present in my PR) changes as review comments here?

After having addressed the below comment, you have everything :). :lgtm: 

> Also, you can do the second PR in the series then, after this one is merged -- removing fs.mount.blabla syntax and sgx.allowed_files.blabla + sgx.trusted_files.blabla syntax.

Sure, let me work on that.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1252#-:-NR_rs_P8-CiTOakrMVX:b-c1u7zr)* status: 0 of 15 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1252)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1252)* status: all files reviewed, 1 unresolved discussion

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1252)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1252#-NRXN8rLDwkGlFjZtnHN:-NSFML8c-jpgLY08xlhv:bw97uf9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Once this PR is merged, I have another **TODO**: remove deprecated `fs.mount.` syntax (https://gramine.readthedocs.io/en/stable/manifest-syntax.html#fs-mount-points-deprecated-syntax)

I didn't want to lump independent removals in one PR, that's why I don't remove `fs.mount.` syntax here. I also don't want to create two parallel PRs, because they touch the same files, and rebasing would be non-trivial. So decided to chain one PR after another.

I'm blocking myself to not forget to create this other PR once this one is ready for merge.
</blockquote></details>

@kailun-qin This PR will be merged now. Since you wanted to work on removing `fs.mount.` syntax, please go ahead.

___

**Pull request merged**
