### PR TITLE
[LibOS] Move reusable test files into a common directory

### PR DESCRIPTION
**Pull request by stefanberger**
Some test files can be reused for different architectures, so move them
into a common directory.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/599)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/599)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/599)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @stefanberger)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/599#-N2omY_YCEBnxEkEEIO1):*
`reusable test files` -> `reusable ABI test files`. Can be done during final rebase.

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/599)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/599#-N2omY_YCEBnxEkEEIO1):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

You guys do the final rebase then ?
</blockquote></details>

Yeah, we will. Added this to the merge queue

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/599)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/599)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/599#-N2omY_YCEBnxEkEEIO1):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-20.04 please.

Failures are unrelated to this PR:
- `Command ['gramine-direct', 'fcntl14_64'] timed out after 60 s`
- `Command ['gramine-direct', 'fdatasync01'] timed out after 30 s`

**Pull request merged**
