### PR TITLE
[python] Print nicer errors in `gramine-manifest`

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

See the analogous problem and discussion for `gramine-manifest-check`: https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw79aKICx9Ai1ujL3Hk.

## How to test this PR? 

Corrupt a manifest template and try to build.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1862)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1862)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @woju)

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1862)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`python/gramine-manifest` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1862#-NweCBfECL76pgZyggD-:-NweCBfECL76pgZyggD0:b8zae5f) ([raw file](https://github.com/gramineproject/gramine/blob/c6477e0c4de7b5289bb19abbf28f79f3e91697d4/python/gramine-manifest#L10)):*
> ```
> 
> from graminelibos import Manifest
> from tomli import TOMLDecodeError
> ```

1) this is wrong import place, the import should be placed before `graminelibos` WRT PEP 8
2) this should be try/except for tomllib and fall back to tomli if tomllib is not present (see `gramine-manifest-check`)



_Suggestion:_
```
try:
    from tomllib import TOMLDecodeError
except ImportError:
    from tomli import TOMLDecodeError
# or you can import full module and try/except tomllib.TOMLDecodeError as in gramine-manifest-check, but this is also OK
```
___
*[`python/gramine-manifest` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1862#-NweBj-OCcSjZF4gYZTP:-NweBj-OCcSjZF4gYZTQ:bg0mrzd) ([raw file](https://github.com/gramineproject/gramine/blob/c6477e0c4de7b5289bb19abbf28f79f3e91697d4/python/gramine-manifest#L32)):*
> ```
> def main(ctx, string, define, infile, outfile, check):
>     if not bool(string) ^ bool(infile):
>         click.get_current_context().fail('specify exactly one of (infile, -c)')
> ```

(nb, if you want to fix it for consistency with all other exit messages)



_Suggestion:_
```
ctx
```

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1862)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1862)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1862)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1862)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Docs please

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-20.04 please

**Pull request merged**
