### PR TITLE
[Docs,tests] Remove unused asv benchmarks

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

They are stale and unused by anyone. If needed in the future, we can restore them from git history.

I checked with internal Intel teams. Noone is using this stuff.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/211)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-20.04 please (LibOS test `fork_and_exec` failed with `failed restoring checkpoint at vma (-13)`)

**Review by mkow — APPROVED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/211)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/211)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/211)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/211)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
