### PR TITLE
Random fixes for meson and python in preparation for meson devenv

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

This PR contains several random, hopefully uncontroversial fixes to buildsystem and `gramine-{direct,sgx}` script. Split off `meson devenv` PR (#1183). Please see individual commit messages for content and rationale.

## How to test this PR? 

CI should be OK.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1189)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1189)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1189#-NOiKSBWC_cR_1nIwdnG:-NOiKSBWC_cR_1nIwdnH:b-ref3vo) (no related file):*
CI failed.

___
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1189#-NOiKXBe3AOQBWU3u_ZG):*
Could we put the slash in backticks (here and everywhere in commit message)? Hard to read.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1189)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1189#-NOigbUTB8ESUBDM7L9v:-NOigbUTB8ESUBDM7L9w:bfa67oi) (no related file):*
Please change the title of the PR to something less vague (e.g. list the changed components at least).

___
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1189#-NOiKXBe3AOQBWU3u_ZG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we put the slash in backticks (here and everywhere in commit message)? Hard to read.
</blockquote></details>

+1, I also misread it at the first try.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1189)* status: 37 of 39 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1189#-NOigbUTB8ESUBDM7L9v:-NOktCYq8LeUgBQwYjjO:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please change the title of the PR to something less vague (e.g. list the changed components at least).
</blockquote></details>

Done.

___
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1189#-NOiKXBe3AOQBWU3u_ZG):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, I also misread it at the first try.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1189)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1189)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1189)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
