### PR TITLE
[Pal,LibOS] Fix error codes for sendfile and bind syscall flows

### LINKED ISSUE #179: Incorrect or missing error conditions in Gramine leading to LTP test failures
## Description of the problem

We are in the process of upgrading LTP to the latest version and that's where we are seeing failures with the new/modified LTP tests when run with Gramine. Collating multiple such tests which are failing due to incorrect/missing error conditions in Gramine.

- [ ] bind01
- [x] readv02  (UPDATE: failure is due to a bug in new LTP test code being added)
- [ ] sendfile03. 

Log of the test run with Gramine-direct is attached to the bug.

## Steps to reproduce

Since the issues are seen with the LTP upgraded tests and something that we are still migrating to the local CI, follow the below steps to checkout and run the latest LTP test in your local workspace.

Checkout the local CI repo present here `https://github.com/jinengandhi-intel/graphene_local_ci/tree/ltp_upgrade`

```
cd gramine/LibOS/shim/test/ltp
cp -rf <ltp_upgrade_localci_branch>/ltp_src .
cp -rf <ltp_upgrade_localci_branch>ltp_config/* .

# To build the tests and generate manifest files
make -j8 -f Makefile.LTP all LTPCFG=ltp_tests.cfg LTPTESTFILE=./install/runtest/syscalls-new 

# To run the tests
cd install/testcases/bin/
gramine-direct bind01
gramine-direct readv02
gramine-direct sendfile03

```

## Actual results

[bind01_readv02_sendfile03_error.txt](https://github.com/gramineproject/gramine/files/7439038/bind01_readv02_sendfile03_error.txt)

### PR DESCRIPTION
**Pull request by Satya1493**
Signed-off-by: Satyanaraya Illa <satyanaraya.illa@intel.com>

## Description of the changes 
1. [`Sendfile` syscall] Added a check to fail with `EBADF` if output file fd does not have WRITE flag set.
2. [`Bind` syscall] Added a check to return correct return value for error `EADDRNOTAVAIL`.

Fixes #179 

## How to test this PR? 
Follow steps mentioned in #179

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @Satya1493)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/427#-MwemySq8YSXTD-xxj-d:-MwemySr1w3Myy3xuu8h:b-k5dyrt) (no related file):*
What about `readv02` mentioned in #179?

---
___
*[Pal/src/host/Linux/db_sockets.c, line 325 at r1](https://reviewable.io/reviews/gramineproject/gramine/427#-Mwenlk95R6Ae5E10acJ:-MwenlkA-SP_IfNHlvgQ:b-zfvrpc) ([raw file](https://github.com/gramineproject/gramine/blob/32efc88ac45e0113d80ddc0f512980cb563dbbb2/Pal/src/host/Linux/db_sockets.c#L325)):*
> ```C
>             case -EADDRNOTAVAIL:
>                 ret = -PAL_ERROR_ADDRNOTEXIST;
>                 goto failed;
> ```

Good catch! Interestingly, we had this in other similar places in this file, but not here.

Technically, we should use `unix_to_pal_error(ret)` in all these places... But this file needs to be re-written anyway, so to fix the LTP issue, I'm fine with this quick solution.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @Satya1493)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/427#-MwexcciAbcYJux9-c6P:-MwexccjDF3g7tFVIoSC:b-cdmhxv) (no related file):*
@satya1493 Jenkins fails with:
```
sendfile05    1  TFAIL  :  /home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendfile/sendfile05.c:103: sendfile returned unexpected errno, expected: 22, got: 9
```

Please fix.

---

**Review by Satya1493 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/427#-MwemySq8YSXTD-xxj-d:-Mx87jz50teLW81yrVEv:b-9qyyvw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about `readv02` mentioned in #179?
</blockquote></details>

`readv02` failure is due to a bug in new test code being added.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/427#-MwexcciAbcYJux9-c6P:-Mx88nDe-bn1zBoXoX0N:b-886gsx) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@satya1493 Jenkins fails with:
```
sendfile05    1  TFAIL  :  /home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendfile/sendfile05.c:103: sendfile returned unexpected errno, expected: 22, got: 9
```

Please fix.
</blockquote></details>

Fixed

---

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/427#-MwemySq8YSXTD-xxj-d:-Mx8gw4T2M0Yr719YUW2:b-70ecg1) (no related file):*
<details><summary><i>Previously, Satya1493 wrote…</i></summary><blockquote>

`readv02` failure is due to a bug in new test code being added.
</blockquote></details>

Ok. I added your comment to #179 .

---

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @Satya1493)

___
*[-- commits, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/427#-MxCEdYoC46yBgZab32B):*
no period at the end
___
*[-- commits, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/427#-MxCEhb09vkl9_Gg-yYu):*
`Update` -> `Fix`
___
*[LibOS/shim/src/sys/shim_file.c, line 458 at r3](https://reviewable.io/reviews/gramineproject/gramine/427#-MxCFno82ArqTSoiAfx1:-MxCFno82ArqTSoiAfx2:b7w33y5) ([raw file](https://github.com/gramineproject/gramine/blob/dbe4c640ff95434af297c8dc452a5c04e2972f8b/LibOS/shim/src/sys/shim_file.c#L458)):*
> ```C
>     }
> 
>     if (!((out_hdl->flags & O_WRONLY) || (out_hdl->flags & O_RDWR))) {
> ```

`O_WRONLY`, `O_RDWR`, etc. are not just bits in a bitmask, but an enum encoded in some bits of `flags`
___
*[LibOS/shim/src/sys/shim_file.c, line 459 at r3](https://reviewable.io/reviews/gramineproject/gramine/427#-MxCG-yo4dCns_m65bj9:-MxCG-yo4dCns_m65bjA:b-fvvyuf) ([raw file](https://github.com/gramineproject/gramine/blob/dbe4c640ff95434af297c8dc452a5c04e2972f8b/LibOS/shim/src/sys/shim_file.c#L459)):*
> ```C
> 
>     if (!((out_hdl->flags & O_WRONLY) || (out_hdl->flags & O_RDWR))) {
>         /* Linux errors out if output fd doesn't have WRITE flag set */
> ```

There's no `WRITE` flag. Please say instead: `isn't writable`.



_Suggestion:_
```C
isn't writable
```

**Review by Satya1493 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: 2 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[-- commits, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/427#-MxCEdYoC46yBgZab32B):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no period at the end
</blockquote></details>

Done.
___
*[-- commits, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/427#-MxCEhb09vkl9_Gg-yYu):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Update` -> `Fix`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_file.c, line 458 at r3](https://reviewable.io/reviews/gramineproject/gramine/427#-MxCFno82ArqTSoiAfx1:-MxDKnRW15zLebAeo5O-:b-khwf09) ([raw file](https://github.com/gramineproject/gramine/blob/dbe4c640ff95434af297c8dc452a5c04e2972f8b/LibOS/shim/src/sys/shim_file.c#L458)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`O_WRONLY`, `O_RDWR`, etc. are not just bits in a bitmask, but an enum encoded in some bits of `flags`
</blockquote></details>

So, is this not the correct way to check for `O_WRONLY` & `O_RDWR`? If it isn't, we'd have to update other places in the existing code too.

Could you please share how to do this check?
___
*[LibOS/shim/src/sys/shim_file.c, line 459 at r3](https://reviewable.io/reviews/gramineproject/gramine/427#-MxCG-yo4dCns_m65bj9:-MxDI_9h72zOuHD1xNYM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dbe4c640ff95434af297c8dc452a5c04e2972f8b/LibOS/shim/src/sys/shim_file.c#L459)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There's no `WRITE` flag. Please say instead: `isn't writable`.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @Satya1493)

___
*[LibOS/shim/src/sys/shim_file.c, line 458 at r3](https://reviewable.io/reviews/gramineproject/gramine/427#-MxCFno82ArqTSoiAfx1:-MxErF6BEe-L_CWkr8nr:b-1weg8o) ([raw file](https://github.com/gramineproject/gramine/blob/dbe4c640ff95434af297c8dc452a5c04e2972f8b/LibOS/shim/src/sys/shim_file.c#L458)):*
> So, is this not the correct way to check for O_WRONLY & O_RDWR? If it isn't, we'd have to update other places in the existing code too.

Nope, it's not.

> Could you please share how to do this check?

Please try googling, reading documentation and analyzing this yourself, so that you learn something in the way instead of just pasting my code ;)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @Satya1493)

___
*[LibOS/shim/src/sys/shim_file.c, line 459 at r6](https://reviewable.io/reviews/gramineproject/gramine/427#-MxFACzt4448sR6uxHrf:-MxFACzt4448sR6uxHrg:bmj6pqd) ([raw file](https://github.com/gramineproject/gramine/blob/0daf1f12577b3b9c001ebf9eb675248e80634746/LibOS/shim/src/sys/shim_file.c#L459)):*
> ```C
> 
>     int mode = out_hdl->flags & O_ACCMODE;
>     if (!((mode == O_WRONLY) || (mode == O_RDWR))) {
> ```

Not blocking, but the innermost brackets (`()`) are not needed here.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/427)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
