### PR TITLE
[Examples] Remove big examples from this repository

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The following examples are moved to a separate repository https://github.com/gramineproject/examples: Apache, Curl, GCC, Node.js, OpenJDK (Java), OpenVINO, PyTorch, R, TensorFlow-Lite.

Only sufficiently small and useful examples are kept in this repo (Bash, Blender, BusyBox, Lighttpd, Memcached, Nginx, Python, RA-TLS, Redis, SQLite). All these kept examples are included in our Jenkins CI.

As side commits, I also:
- Removed stale and unused `oldwiki/` page from documentation
- Renamed `Examples/` to `CI-Examples/`

See https://github.com/gramineproject/graphene/issues/2558 for context.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/4)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 141 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/4)* status: 7 of 145 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/4#-Mj98a5LC-PMJ3eYYTW_:-Mj98a5LC-PMJ3eYYTWa:blbgrsm) (no related file):*
Blocking until we create https://github.com/gramineproject/examples.

---

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`apps.LTP.fcntl14` timed out)

**Review by mkow — APPROVED** [review]
> Reviewed 137 of 141 files at r1, 1 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-20.04 please (`sendfile09_64` from LTP failed, wasn't seen before, but this is quite a slow test and unrelated to this PR)

**Comment by dimakuv** [comment]
Jenkins, retest DCO please

**Comment by dimakuv** [comment]
Jenkins, retest Docs-18.04 please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
