### PR TITLE
[meson] Indentation fixes for VTune dependency

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Just a random finding in our Meson files.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1172)

### CODE REVIEW

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1172)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1172)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1172)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1172)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
