### PR TITLE
Refactor PAL globals - part 1

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

First PR in a long, upcoming series to make PALs less ugly. Details in commit messages.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/157)

### CODE REVIEW

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/157)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @chiache, @dimakuv, and @pwmarcz)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/157#-MmJiqX62fIGC3EuwtwM):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Please make the commit message more informative. As far as I can see, the main purpose of this PR is: (1) Removing GDB-related code in C; (2) Deprecating unused `destroy_enclave()`; (3) Removing unused `set_signals`, `blocked_signals`, and `runtime_dir` in `pal_linux_state`
</blockquote></details>

I don't think it's useful to list what exactly was removed, all of these were unused anyways? I.e. no one cares for them :)
___
*[-- commits, line 35 at r7](https://reviewable.io/reviews/gramineproject/gramine/157#-MmJwQHy-xtEMxr5zr6R):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like the smiley face :(
</blockquote></details>

Should I just drop it, or replace with `:(`?
___
*[Pal/src/host/Linux-SGX/sgx_gdb_info.c, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/157#-MmJui5N9UQ94XDmpHlJ:-MmKBWHT8_JJ4lmXkkN4:b-nkpm0o) ([raw file](https://github.com/gramineproject/gramine/blob/b737ab250f4e650caa8d3de57dca1efc1d2a597f/Pal/src/host/Linux-SGX/sgx_gdb_info.c#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just to make sure: @pwmarcz You introduced a generic hook for GDB, right, and just forgot to remove this code in your PRs? I see that Jenkins passes, including your LibOS regression test of GDB, so this code snippet must be indeed not used.
</blockquote></details>

My guess was that this was the case, but let's wait for Paweł's comment.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/157)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @chiache, @mkow, and @pwmarcz)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/157#-MmJiqX62fIGC3EuwtwM):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think it's useful to list what exactly was removed, all of these were unused anyways? I.e. no one cares for them :)
</blockquote></details>

I agree with Michal, I don't see how future developers of Gramine may find `removed unused set_signals` helpful.
___
*[-- commits, line 35 at r7](https://reviewable.io/reviews/gramineproject/gramine/157#-MmJwQHy-xtEMxr5zr6R):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should I just drop it, or replace with `:(`?
</blockquote></details>

Drop it and put a dot at the end.
___
*[Pal/src/host/Linux/db_main.c, line 308 at r4](https://reviewable.io/reviews/gramineproject/gramine/157#-MmKF9r07qvafT0WpoA7:-MmMY_3D5HQqUFebQW3a:b-eontqd) ([raw file](https://github.com/gramineproject/gramine/blob/feabb0518627a82c94be0db78dad078bfeb27e55/Pal/src/host/Linux/db_main.c#L308)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Pretty cheap != free (but yeah I get the point).
The thing is it was already there and it wasn't some super hacky code, so I see no reason for removing it.
</blockquote></details>

No strong feelings here. I don't mind removing `pid` field.

For Linux PAL, I don't care about performance at all.

For Linux-SGX PAL, we now have an additional `getpid()` syscall in `sgx_ocall_resume_thread()` -- this is a rather frequent OCALL in multi-threaded apps. The rest of the places is on debugging/profiling paths or rarely occurring paths. So I suggest to cache PID in `sgx_ocall_resume_thread()` in a static global variable and be done with this.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r10, 9 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/157)* status: all files reviewed, 7 unresolved discussions, "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @chiache, and @mkow)

___
*[-- commits, line 57 at r11](https://reviewable.io/reviews/gramineproject/gramine/157#-MmOiPIn4F1nkLdt8_qK):*
Oh, squash and a TODO, smart! We should use this pattern.
___
*[Pal/src/host/Linux/db_main.c, line 98 at r7](https://reviewable.io/reviews/gramineproject/gramine/157#-MmKHzB3C-fFrEHtKwY5:-MmOiqP17uR3jJh--Xfe:b-z5svrj) ([raw file](https://github.com/gramineproject/gramine/blob/d535a3dcdc5e4362dc53b7fb34527b0fcee39a62/Pal/src/host/Linux/db_main.c#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv @pwmarcz any preferences?
</blockquote></details>

It reads well to me, so I'd leave these booleans.

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/157)* status: all files reviewed, 6 unresolved discussions, "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @chiache, @dimakuv, and @mkow)

___
*[-- commits, line 57 at r11](https://reviewable.io/reviews/gramineproject/gramine/157#-MmOiPIn4F1nkLdt8_qK):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oh, squash and a TODO, smart! We should use this pattern.
</blockquote></details>

Yes, this looks better than leaving a blocking "reword this at rebase" discussion.

**Review by mkow — COMMENTED** [review]
FYI: I speculatively rebased the PR to speed up merging it, as I have a lot more changes blocked on it.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/157#-:-MmXAQkd93ZxIxUsOVVm:bjf6wwb)* status: 4 of 40 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @chiache, @dimakuv, and @pwmarcz)

___
*[common/include/api.h, line 112 at r4](https://reviewable.io/reviews/gramineproject/gramine/157#-MmKEFL87gvmp13D2gsa:-MmXKh3z7PHfoBmAwQKC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/feabb0518627a82c94be0db78dad078bfeb27e55/common/include/api.h#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> No, the compiler is smart enough to see that these two immediate values can be safely cast back and forth.

Huh, I didn't expect this. But it seems that it works indeed, so I'll drop this commit on rebase.
</blockquote></details>

Done.

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 4 files at r13, 17 of 19 files at r14, 7 of 10 files at r15, 9 of 11 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/157)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @chiache)

**Pull request merged**
