### PR TITLE
[Pal/Linux-SGX] Switch fully to Meson 

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

This removes remaining parts of `Pal/Linux-SGX` handled by Make: AESM protobuf code, and SGX GDB integration.

As a result, we can get rid of Makefiles for building PAL.

## How to test this PR? 

- Jenkins 
- Try building it yourself
- Try running a program under GDB

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/Makefile, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/122#-MlBXSl15V1Zuequ3bnR:-MlBXSl15V1Zuequ3bnS:b-zc3kvk) ([raw file](https://github.com/gramineproject/gramine/blob/6bbecb8d32c673bc2f042309feb478d91452af16/Pal/Makefile#L3)):*
> ```Makefile
> include ../Scripts/Makefile.configs
> 
> DIRS = regression
> ```

Is there any reason to keep it? I've never used `cd Pal && make regression`. Can we just remove it and ask devs to perform tests via `cd Pal/regression && make regression`? Then we could remove the whole Makefile.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: 14 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/Makefile, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/122#-MlBXSl15V1Zuequ3bnR:-MlBlviVAN4FCyUtb2hD:b-wwsz9y) ([raw file](https://github.com/gramineproject/gramine/blob/6bbecb8d32c673bc2f042309feb478d91452af16/Pal/Makefile#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is there any reason to keep it? I've never used `cd Pal && make regression`. Can we just remove it and ask devs to perform tests via `cd Pal/regression && make regression`? Then we could remove the whole Makefile.
</blockquote></details>

Sounds good, let's see what Jenkins has to say...

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Pal/Makefile, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/122#-MlBXSl15V1Zuequ3bnR:-MlBqdTs5RuFS-JPSdEp:b9e5wco) ([raw file](https://github.com/gramineproject/gramine/blob/6bbecb8d32c673bc2f042309feb478d91452af16/Pal/Makefile#L3)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sounds good, let's see what Jenkins has to say...
</blockquote></details>

Thanks! Jenkins seems to not mind.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/proto/meson.build, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEd6hK7qYiMaq0qjJS:-MlEd6hK7qYiMaq0qjJT:bs8xm1h) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/common/proto/meson.build#L6)):*
> ```
> dependency files generated `proto-c`
> ```

Missing "by"? Or maybe you meant something different?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEkx1A-4fjxmeNtdsA:-MlEkx1A-4fjxmeNtdsB:bfur1f3) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/Pal/src/host/Linux-SGX/sgx_main.c#L27)):*
> ```C
> #include "rpc_queue.h"
> #include "sgx_api.h"
> #include "sgx_gdb.h"
> ```

please sort
___
*[Pal/src/host/Linux-SGX/sgx_gdb.h, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEl8yiEKjmrvj-r_Kk:-MlEl8yiEKjmrvj-r_Kl:bssaq3d) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/Pal/src/host/Linux-SGX/sgx_gdb.h#L1)):*
> ```objc
> #include <stdint.h>
> ```

ditto (moving the file)
___
*[Pal/src/host/Linux-SGX/sgx_gdb.c, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEh2aj0YqSsGFsO-Kp:-MlEh2aj0YqSsGFsO-Kq:b8znie6) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/Pal/src/host/Linux-SGX/sgx_gdb.c#L1)):*
> ```C
> #define _GNU_SOURCE
> ```

Why did you move it out of `gdb_integration` directory?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: 15 of 17 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[common/proto/meson.build, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEd6hK7qYiMaq0qjJS:-MlEooe3D7w3mcjEf01B:bi8w8g2) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/common/proto/meson.build#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> dependency files generated `proto-c`
> ```

Missing "by"? Or maybe you meant something different?
</blockquote></details>

I meant "by". Fixed.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEkx1A-4fjxmeNtdsA:-MlEohn95tpg4hILzwNQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/Pal/src/host/Linux-SGX/sgx_main.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_gdb.c, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEh2aj0YqSsGFsO-Kp:-MlEmVX14VfrK2KFSARw:b-l0jaup) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/Pal/src/host/Linux-SGX/sgx_gdb.c#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why did you move it out of `gdb_integration` directory?
</blockquote></details>

Because Meson directly installs the contents of `gdb_integration` directory, and we don't want it to install this C file.

Also, while these `sgx_gdb.[ch]` files are mostly separate from PAL and URTS, they actually share some code both ways (this file has the sneaky `../sgx_arch.h` include, and one of the URTS files includes `sgx_gdb.h`).

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_gdb.c, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEh2aj0YqSsGFsO-Kp:-MlEzrED8Jlj65Mwbytt:b9hgjgm) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/Pal/src/host/Linux-SGX/sgx_gdb.c#L1)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Because Meson directly installs the contents of `gdb_integration` directory, and we don't want it to install this C file.

Also, while these `sgx_gdb.[ch]` files are mostly separate from PAL and URTS, they actually share some code both ways (this file has the sneaky `../sgx_arch.h` include, and one of the URTS files includes `sgx_gdb.h`).
</blockquote></details>

Hmm, but this makes the repo organization more chaotic: the whole GDB integration is here, except two files which lie somewhere else.
Would it be possible to install only selected files? I think installing the whole directory is a bad idea anyways, it's easy to add a file here and accidentally make it installable.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: 9 of 23 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/meson.build, line 209 at r4](https://reviewable.io/reviews/gramineproject/gramine/122#-MlF6FgH6SrNe8q4QGR7:-MlF6FgH6SrNe8q4QGR8:b-dkh7t4) ([raw file](https://github.com/gramineproject/gramine/blob/205dd8102257eed609c988fde8c43eb9f6b59b3e/Pal/src/host/Linux-SGX/meson.build#L209)):*
> ```Meson
>         'gdb_integration/sgx_gdb.c',
> 
>         # just `sgx_gdb.so`, without `lib`
> ```

On reflection, I'd rather keep the `sgx_gdb.so` filename, so that we don't pretend it's a normal library. But I can go back to `libsgx_gdb.so` if you prefer.
___
*[Pal/src/host/Linux-SGX/sgx_gdb.c, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEh2aj0YqSsGFsO-Kp:-MlF4_hH-gf1Hsu-frG5:b-4vngse) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/Pal/src/host/Linux-SGX/sgx_gdb.c#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but this makes the repo organization more chaotic: the whole GDB integration is here, except two files which lie somewhere else.
Would it be possible to install only selected files? I think installing the whole directory is a bad idea anyways, it's easy to add a file here and accidentally make it installable.
</blockquote></details>

Okay, I see how that would be better. And I can clean up the mess with `common` symlink, we're not running these scripts from repo anymore. Do

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: 9 of 23 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_gdb.c, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/122#-MlEh2aj0YqSsGFsO-Kp:-MlF6NQp0XC2V_3vfJVq:bf94duv) ([raw file](https://github.com/gramineproject/gramine/blob/63e66c58bcf6a052090be5c3325edf5680bea58f/Pal/src/host/Linux-SGX/sgx_gdb.c#L1)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, I see how that would be better. And I can clean up the mess with `common` symlink, we're not running these scripts from repo anymore. Do
</blockquote></details>

*Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

**Review by mkow — DISMISSED** [review]
> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/meson.build, line 209 at r4](https://reviewable.io/reviews/gramineproject/gramine/122#-MlF6FgH6SrNe8q4QGR7:-MlFWqhkE1Z2w_ICQJMM:b-ox1a1v) ([raw file](https://github.com/gramineproject/gramine/blob/205dd8102257eed609c988fde8c43eb9f6b59b3e/Pal/src/host/Linux-SGX/meson.build#L209)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

On reflection, I'd rather keep the `sgx_gdb.so` filename, so that we don't pretend it's a normal library. But I can go back to `libsgx_gdb.so` if you prefer.
</blockquote></details>

Fine with me.

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/122)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
