### PR TITLE
Release 1.6

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This is release PR for 1.6.

This is 100% based on the previous PR for v1.5: https://github.com/gramineproject/gramine/pull/1437

TODOs:
- [ ] After the PR is merged, tag the corresponding commit with `v1.6`.
- [ ] Tag `examples` and `gsc` repos with `v1.6`.

## How to test this PR? 

Manual testing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`debian/changelog` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1677#-NlRrK7581EV61qZ0_al:-NlRrK7581EV61qZ0_am:b-1w2zs8) ([raw file](https://github.com/gramineproject/gramine/blob/20b398dc7ad659fd27a747beb2654315d7d00d27/debian/changelog#L9)):*
> ```
> gramine (1.6) bookworm bullseye jammy focal; urgency=medium
> 
>   * version 1.6
> ```

It seems that we also updated minimal versions/requirements for `python3` and `python3-click`. Doe we need to mention them here?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`debian/changelog` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1677#-NlRrK7581EV61qZ0_al:-NlRuFd78q-X-C-MXOpC:b-latd8x) ([raw file](https://github.com/gramineproject/gramine/blob/20b398dc7ad659fd27a747beb2654315d7d00d27/debian/changelog#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It seems that we also updated minimal versions/requirements for `python3` and `python3-click`. Doe we need to mention them here?
</blockquote></details>

What do you mean? Where do you see it?

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`debian/changelog` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1677#-NlRrK7581EV61qZ0_al:-NlS2YVe5c6uV34O_R8_:b-yd35nb) ([raw file](https://github.com/gramineproject/gramine/blob/20b398dc7ad659fd27a747beb2654315d7d00d27/debian/changelog#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean? Where do you see it?
</blockquote></details>

I meant by these two commits: https://github.com/gramineproject/gramine/commit/3b5c88b116a3fd42e8305eb8f8973ecc648afa7c#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0 and https://github.com/gramineproject/gramine/commit/8f65e6ad7444410d576a63fd0e5f443ced82830c#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0, we made changes to `debian/control`.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`debian/changelog` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1677#-NlRrK7581EV61qZ0_al:-NlS5N3C0wbdZ2ZlAvjy:b-g7tbdr) ([raw file](https://github.com/gramineproject/gramine/blob/20b398dc7ad659fd27a747beb2654315d7d00d27/debian/changelog#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I meant by these two commits: https://github.com/gramineproject/gramine/commit/3b5c88b116a3fd42e8305eb8f8973ecc648afa7c#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0 and https://github.com/gramineproject/gramine/commit/8f65e6ad7444410d576a63fd0e5f443ced82830c#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0, we made changes to `debian/control`.
</blockquote></details>

Done, thanks for explanations.

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1677#-NlSXvlg-TEeZzh6_T1q:-NlSXvlg-TEeZzh6_T1r:b-dw81se) (no related file):*
@woju says there is one last-minute fix to a bug. Blocking until that one is merged.

___

**Review by woju — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

___
*[`debian/changelog` line 13 at r2](https://reviewable.io/reviews/gramineproject/gramine/1677#-NlZL4W1AXV99TLRG4w-:-NlZL4W1AXV99TLRG4w0:b-78iise) ([raw file](https://github.com/gramineproject/gramine/blob/ae9389a0648a9ccdb7f40b5c9a6ca914169b7a21/debian/changelog#L13)):*
> ```
>   * added python3-pkg-resources dependency (if python3 < 3.10)
> 
>  -- Wojtek Porczyk <woju@invisiblethingslab.com>  Mon, 11 Dec 2023 10:00:00 +0200
> ```

(It's winter time). Also above. Also, please add 1 s to the timestamp of `~UNRELEASED` version. You can do it when rebasing, then dismiss my comment if I'm not around.



_Suggestion:_
```
+0100
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1677#-NlSXvlg-TEeZzh6_T1q:-NlZZSEu2Ct6WFfMTLrm:bm5ml0d) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju says there is one last-minute fix to a bug. Blocking until that one is merged.
</blockquote></details>

It was merged: https://github.com/gramineproject/gramine/pull/1679

___
___
*[`debian/changelog` line 13 at r2](https://reviewable.io/reviews/gramineproject/gramine/1677#-NlZL4W1AXV99TLRG4w-:-NlZ_FxD0Flc99w9r4F6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ae9389a0648a9ccdb7f40b5c9a6ca914169b7a21/debian/changelog#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

(It's winter time). Also above. Also, please add 1 s to the timestamp of `~UNRELEASED` version. You can do it when rebasing, then dismiss my comment if I'm not around.
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1677)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Pull request merged**
