### PR TITLE
Bump glibc to 2.36

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

Compiling on systems with glibc-2.36 (like Debian bookworm/12/testing, to be released in half a year) yields the following error:
```
gcc -Wl,-rpath-link=/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/math:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/elf:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/dlfcn:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/nss:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/nis:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/rt:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/resolv:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/mathvec:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/support:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/crypt:/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/nptl -o /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/support/test-container -pie -Wl,-O1 -nostdlib -nostartfiles    -Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/csu/Scrt1.o /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/csu/crti.o `gcc  --print-file-name=crtbeginS.o` /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/support/test-container.o /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/support/libsupport_nonshared.a -Wl,-dynamic-linker=/home/woju/local-gramine/lib/ld-linux-x86-64.so.2  /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/libc.so.6 /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/libc_nonshared.a -Wl,--as-needed /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/elf/ld.so -Wl,--no-as-needed -lgcc  `gcc  --print-file-name=crtendS.o` /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/csu/crtn.o
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/12/libstdc++.so: undefined reference to `arc4random@GLIBC_2.36'
collect2: error: ld returned 1 exit status
make[2]: *** [../Rules:230: /home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/build/support/links-dso-program] Error 1
make[2]: Leaving directory '/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p/support'
make[1]: *** [Makefile:483: support/others] Error 2
make[1]: Leaving directory '/home/woju/gramine/build/subprojects/glibc-2.35-1/crt1.o.p'
make: *** [Makefile:9: all] Error 2
```

Upstream tarball is already available at https://packages.gramineproject.io/distfiles/

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuL2n-CCSx_zH6DtrE:-NJuL2n-CCSx_zH6DtrF:b-8j8mkj) (no related file):*
Did you verify that there are no new places with syscall instruction we should patch?

___
___
*[`subprojects/packagefiles/glibc-2.36/meson.build` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuKvM0-XrvZ2X2bguQ:-NJuKvM0-XrvZ2X2bguR:b-t1rn0x) ([raw file](https://github.com/gramineproject/gramine/blob/9eb8213067c4679524caa1305a47aa560ebd8b42/subprojects/packagefiles/glibc-2.36/meson.build#L75)):*
> ```Meson
>         'glibc-2.36/configure',
>         'glibc-2.36.patch',
>         'hp-timing-2.35.patch',
> ```

What about this patch?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuL2n-CCSx_zH6DtrE:-NJuztwh4x-3JfSyGT_G:b-r7bif7) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Did you verify that there are no new places with syscall instruction we should patch?
</blockquote></details>

Yes, I've grepped for `syscall` in `.c` and `.h` files and didn't find anything else.

___
___
*[`subprojects/packagefiles/glibc-2.36/meson.build` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuKvM0-XrvZ2X2bguQ:-NJv--Nh3DnmMpfh-jGn:bcu019r) ([raw file](https://github.com/gramineproject/gramine/blob/9eb8213067c4679524caa1305a47aa560ebd8b42/subprojects/packagefiles/glibc-2.36/meson.build#L75)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about this patch?
</blockquote></details>

Didn't change a bit, so I've left it alone.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuL2n-CCSx_zH6DtrE:-NJvGnaa0PaFADkZhxab:bjezk28) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, I've grepped for `syscall` in `.c` and `.h` files and didn't find anything else.
</blockquote></details>

But it's also `.S`, `.s` and who knows what else

___
___
*[`subprojects/packagefiles/glibc-2.36/meson.build` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuKvM0-XrvZ2X2bguQ:-NJvGrjF8N4TrDfpcQDE:b-vz47t9) ([raw file](https://github.com/gramineproject/gramine/blob/9eb8213067c4679524caa1305a47aa560ebd8b42/subprojects/packagefiles/glibc-2.36/meson.build#L75)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Didn't change a bit, so I've left it alone.
</blockquote></details>

But the name does not match

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuL2n-CCSx_zH6DtrE:-NJvW6-H9fbJkp3L2Vz4:bp4vp7i) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But it's also `.S`, `.s` and who knows what else
</blockquote></details>

The grep is noisy. I did read this:

```sh
git fgrep syscall | fgrep -v ChangeLog | fgrep -v filelist | fgrep -v NEWS | fgrep -v manual | less
```

...and I didn't found any.

___
___
*[`subprojects/packagefiles/glibc-2.36/meson.build` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuKvM0-XrvZ2X2bguQ:-NJvV7rV4XI7z3dgmz9A:b-dmlk8n) ([raw file](https://github.com/gramineproject/gramine/blob/9eb8213067c4679524caa1305a47aa560ebd8b42/subprojects/packagefiles/glibc-2.36/meson.build#L75)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But the name does not match
</blockquote></details>

The version in filename should be the oldest version that needs the patch (or the oldest version for which the patch was written). This is generally accepted convention, mostly for setups like gentoo where you have multiple ebuilds sharing single `files/` directory, but there's no reason we shouldn't use it. If the patch doesn't change, we shouldn't bump the version in filename.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuL2n-CCSx_zH6DtrE:-NJvdBRuEVq--3J_66IK:b-jjero) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The grep is noisy. I did read this:

```sh
git fgrep syscall | fgrep -v ChangeLog | fgrep -v filelist | fgrep -v NEWS | fgrep -v manual | less
```

...and I didn't found any.
</blockquote></details>

Hint: you can `grep -v -e a -e b -e c`

___
___
*[`subprojects/packagefiles/glibc-2.36/meson.build` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuKvM0-XrvZ2X2bguQ:-NJvdM3g-HqAo8pYCqxR:b-4jrwt6) ([raw file](https://github.com/gramineproject/gramine/blob/9eb8213067c4679524caa1305a47aa560ebd8b42/subprojects/packagefiles/glibc-2.36/meson.build#L75)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The version in filename should be the oldest version that needs the patch (or the oldest version for which the patch was written). This is generally accepted convention, mostly for setups like gentoo where you have multiple ebuilds sharing single `files/` directory, but there's no reason we shouldn't use it. If the patch doesn't change, we shouldn't bump the version in filename.
</blockquote></details>

A) Then it should be something like `2.07`
B) We do not provide older versions, this makes no sense.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`subprojects/packagefiles/glibc-2.36/meson.build` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuKvM0-XrvZ2X2bguQ:-NJvwe3s1ioXeVE-20sS:bxb2fch) ([raw file](https://github.com/gramineproject/gramine/blob/9eb8213067c4679524caa1305a47aa560ebd8b42/subprojects/packagefiles/glibc-2.36/meson.build#L75)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

A) Then it should be something like `2.07`
B) We do not provide older versions, this makes no sense.
</blockquote></details>

If it doesn't make sense, can we just skip version numbers? I think they're carried over from times long gone.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`subprojects/packagefiles/glibc-2.36/meson.build` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuKvM0-XrvZ2X2bguQ:-NJw3meE9dwEzA1CAeSM:boefbzl) ([raw file](https://github.com/gramineproject/gramine/blob/9eb8213067c4679524caa1305a47aa560ebd8b42/subprojects/packagefiles/glibc-2.36/meson.build#L75)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If it doesn't make sense, can we just skip version numbers? I think they're carried over from times long gone.
</blockquote></details>

Fine with me

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: 4 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`subprojects/packagefiles/glibc-2.36/meson.build` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuKvM0-XrvZ2X2bguQ:-NJwGOzB2Xy_9BS2YTQP:b-qy9u5y) ([raw file](https://github.com/gramineproject/gramine/blob/9eb8213067c4679524caa1305a47aa560ebd8b42/subprojects/packagefiles/glibc-2.36/meson.build#L75)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Fine with me
</blockquote></details>

Done. Also renamed the first one to `gramine-syscall.patch`, because `glibc.patch` is non-descriptive (`hp-timing` is also a patch against glibc).

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

___
*[`.ci/lib/stage-test-sgx.jenkinsfile` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1089#-NKEydaA7NLHS6dRmtgd:-NKEydaA7NLHS6dRmtge:b-co1w75) ([raw file](https://github.com/gramineproject/gramine/blob/efdf79f32e2f5687b6934d331edadbd9e2d8a427/.ci/lib/stage-test-sgx.jenkinsfile#L3)):*
> ```
> stage('test-sgx') {
>     sh '''
>         scripts/check-no-syscall.sh "$GRAMINE_PKGLIBDIR"/runtime/glibc/libc.so.6
> ```

Could you do the same with musl?
___
*[`scripts/check-no-syscall.sh` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1089#-NKEyScN1sD4UbwlGjQv:-NKEyScN1sD4UbwlGjQw:bgndefw) ([raw file](https://github.com/gramineproject/gramine/blob/efdf79f32e2f5687b6934d331edadbd9e2d8a427/scripts/check-no-syscall.sh#L2)):*
> ```Shell
> #!/bin/sh
> ```

Please add a comment stating that this is just a heuristic which has a chance of warning us if we missed patching a syscall in glibc. Just to be sure that no one ever uses this for anything other than testing.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: 7 of 9 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[`.ci/lib/stage-test-sgx.jenkinsfile` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1089#-NKEydaA7NLHS6dRmtgd:-NKV4mhmDgfpfElWDk5Y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/efdf79f32e2f5687b6934d331edadbd9e2d8a427/.ci/lib/stage-test-sgx.jenkinsfile#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you do the same with musl?
</blockquote></details>

Done.
___
*[`scripts/check-no-syscall.sh` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1089#-NKEyScN1sD4UbwlGjQv:-NKV4UDT0bwBxp9uANT-:b7ohoh3) ([raw file](https://github.com/gramineproject/gramine/blob/efdf79f32e2f5687b6934d331edadbd9e2d8a427/scripts/check-no-syscall.sh#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a comment stating that this is just a heuristic which has a chance of warning us if we missed patching a syscall in glibc. Just to be sure that no one ever uses this for anything other than testing.
</blockquote></details>

Done. Also I can move it to `.ci` if you think it would be more explicit that this script is only meant for CI. (There are already `run-pylint` and `run-shellcheck` which TBH are also convenient outside of CI).

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1089#-NKV97z333ym-bjQz0z5:-NKV97z333ym-bjQz0z6:b-5kc0yu) (no related file):*
It's broken, do not merge. `--no-addresses` is missing on older binutils. Also, `set -e` didn't fail it, because it was hidden behind pipe. I'll fix it.

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: 7 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1089#-NKV97z333ym-bjQz0z5:-NKYk0EU4aRkfyUKZw5f:bt2vr1b) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It's broken, do not merge. `--no-addresses` is missing on older binutils. Also, `set -e` didn't fail it, because it was hidden behind pipe. I'll fix it.
</blockquote></details>

Fixed.

___

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 3 of 5 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

___
*[`subprojects/packagefiles/glibc-2.36/meson.build` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1089#-NJuKvM0-XrvZ2X2bguQ:-NKmecp0Dwu-6etOn9Bx:bdrarrq) ([raw file](https://github.com/gramineproject/gramine/blob/9eb8213067c4679524caa1305a47aa560ebd8b42/subprojects/packagefiles/glibc-2.36/meson.build#L75)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done. Also renamed the first one to `gramine-syscall.patch`, because `glibc.patch` is non-descriptive (`hp-timing` is also a patch against glibc).
</blockquote></details>

+1, I like the new names, without numbers.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`scripts/check-no-syscall.sh` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1089#-NKEyScN1sD4UbwlGjQv:-NKmztQx-uecRvCWBcR-:bra8xq9) ([raw file](https://github.com/gramineproject/gramine/blob/efdf79f32e2f5687b6934d331edadbd9e2d8a427/scripts/check-no-syscall.sh#L2)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done. Also I can move it to `.ci` if you think it would be more explicit that this script is only meant for CI. (There are already `run-pylint` and `run-shellcheck` which TBH are also convenient outside of CI).
</blockquote></details>

Good idea, please move it.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: 7 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`scripts/check-no-syscall.sh` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1089#-NKEyScN1sD4UbwlGjQv:-NKrY7vr3Qqo_B9vZQ72:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/efdf79f32e2f5687b6934d331edadbd9e2d8a427/scripts/check-no-syscall.sh#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good idea, please move it.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1089)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
