### PR TITLE
[Docs,Pal] Remove "SGX Tools" doc and move examples to manpages

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 

Most of the content documented in "SGX Tools" has been in `Documentation/manpages` and `Documentation/attestation.rst` already.

Move all examples of SGX tools into the corresponding docs so that the README can be removed.

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394)* status: 1 of 5 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 96 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZF8bc1IEjUTcfHLL2:-MvZF8bc1IEjUTcfHLL3:b-fbl349) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L96)):*
> ```reStructuredText
>       URL for the IAS attestation report endpoint (optional).
> 
> Example
> ```

`Example` -> `Examples`
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZCRYl7VxWUG6jl1WH:-MvZCRYm1oaevS_p1TbL:bynvgb) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L99)):*
> ```reStructuredText
> =======
> 
> Example SigRL retrieval::
> ```

`::` make the following block a literal block. Please remove the double `:`.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZD-zrC71N0cvgZ1Y8:-MvZD-zrC71N0cvgZ1Y9:b9gwl0b) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L99)):*
> ```reStructuredText
> =======
> 
> Example SigRL retrieval::
> ```

Can we add emphasis to `SigRL` by enclosing it with backticks or asterisk?
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZFNhE01f0ruWjqDy7:-MvZFNhE01f0ruWjqDy8:bcjxt7c) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L99)):*
> ```reStructuredText
> =======
> 
> Example SigRL retrieval::
> ```

I feel the word `example` here is redundant. We can simply say `sigRL` retrieval.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 101 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZJByz6RvmzEzjvrwt:-MvZJByz6RvmzEzjvrwu:b-qqag4d) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L101)):*
> ```reStructuredText
> Example SigRL retrieval::
> 
> .. code-block:: console
> ```

Any reason to have `console` here? I think we usually have `sh`. If no specific reason, please change everywhere to `sh`.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 106 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDABQ59OeFND2Pmkr:-MvZDABQ59OeFND2Pmks:b-5bm00b) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L106)):*
> ```reStructuredText
>     No SigRL for given EPID group ID ef0a0000
> 
> Example quote verification::
> ```

Change `::` -> `:` and add emphasis to `quote`. Also can remove "Example" and simply say `Quote verification`
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDNNiCXbNabZDeCtg:-MvZDNNiCXbNabZDeCth:b-sushwf) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L120)):*
> ```reStructuredText
>     IAS certificate saved to: ias.cert
>     IAS advisory saved to: ias.adv
>     IAS submission successful
> ```

Please introduce a space after this.
___
*[Documentation/manpages/gramine-sgx-ias-verify-report.rst, line 78 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDG_L2c5J8IxLi8qC:-MvZDG_L2c5J8IxLi8qD:bso7bl8) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L78)):*
> ```reStructuredText
> =======
> 
> Example report verification with all options enabled::
> ```

change `::` -> `:` and remove redundant "Example" word.
___
*[Documentation/manpages/gramine-sgx-ias-verify-report.rst, line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZJmYB5M1XuPckN5d-:-MvZJmYB5M1XuPckN5d0:b5nq52f) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L80)):*
> ```reStructuredText
> Example report verification with all options enabled::
> 
> .. code-block:: console
> ```

change `console` -> `sh`?
___
*[Documentation/manpages/gramine-sgx-quote-dump.rst, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDXoeBFKI3bLeCee2:-MvZDXofBDKCefvAr9Qi:b48m6f6) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-quote-dump.rst#L32)):*
> ```reStructuredText
> =======
> 
> Example output::
> ```

change `::` -> `:`. Better would be to remove `Example output::` and just add `.. code-block:: sh`
___
*[Documentation/manpages/gramine-sgx-quote-dump.rst, line 34 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZJ27Y4vFowWeiM0nn:-MvZJ27Y4vFowWeiM0no:bfhliu1) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-quote-dump.rst#L34)):*
> ```reStructuredText
> Example output::
> 
>     > gramine-sgx-quote-dump -m gr.quote
> ```

Now we can replace `>` with`$`
___
*[Documentation/manpages/is-sgx-available.rst, line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZKG3bE8cOu-rKkVYT:-MvZKG3bE8cOu-rKkVYU:b-yfqkxq) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/is-sgx-available.rst#L47)):*
> ```reStructuredText
> =======
> 
> Example output::
> ```

Remove redundant `Example output::` and simply add a code block ``.. code-block:: sh``.
___
*[Pal/src/host/Linux-SGX/tools/README.rst, line 171 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZLT0PE4exaN6pRnrz:-MvZLT0PE4exaN6pRns-:b-w5vkz8) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux-SGX/tools/README.rst#L171)):*
> ```reStructuredText
> 
> 
> RA-TLS Libraries
> ```

@dimakuv I think we can safely remove this section as it is addressed in `attestation.rst` file.
___
*[Pal/src/host/Linux-SGX/tools/README.rst, line 186 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZLk308ofUSX2gfFwU:-MvZLk308ofUSX2gfFwV:b-w5vkz8) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux-SGX/tools/README.rst#L186)):*
> ```reStructuredText
> 
> 
> Secret Provisioning Libraries
> ```

@dimakuv I think we can safely remove this section as it is addressed in `attestation.rst` file.

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @vijaydhanraj)

___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZD-zrC71N0cvgZ1Y8:-MvZMY16BnCCrqh_Dc3i:bs3o3kn) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L99)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can we add emphasis to `SigRL` by enclosing it with backticks or asterisk?
</blockquote></details>

+1. I would prefer `*SigRL* retrieval` (with asterisk)
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZFNhE01f0ruWjqDy7:-MvZMbTyEjnS5UUdhrX4:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L99)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I feel the word `example` here is redundant. We can simply say `sigRL` retrieval.
</blockquote></details>

+1
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 101 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZJByz6RvmzEzjvrwt:-MvZMcdi6jhArYbTfpJn:bcwxwo6) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L101)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Any reason to have `console` here? I think we usually have `sh`. If no specific reason, please change everywhere to `sh`.
</blockquote></details>

Yeah, I recommended `console` as it is the most "common" one. But I think we use `sh` in all other documentation, so let's use `sh` here as well.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 106 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDABQ59OeFND2Pmkr:-MvZMjnA7wWN7IHfZYn6:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L106)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Change `::` -> `:` and add emphasis to `quote`. Also can remove "Example" and simply say `Quote verification`
</blockquote></details>

+1
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDNNiCXbNabZDeCtg:-MvZMkyU5HjA8Xz3DbL7:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L120)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Please introduce a space after this.
</blockquote></details>

+1
___
*[Documentation/manpages/gramine-sgx-ias-verify-report.rst, line 78 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDG_L2c5J8IxLi8qC:-MvZMlvg6B1P_qrhaT9V:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L78)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

change `::` -> `:` and remove redundant "Example" word.
</blockquote></details>

+1
___
*[Documentation/manpages/gramine-sgx-ias-verify-report.rst, line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZJmYB5M1XuPckN5d-:-MvZMmZC0oPcLR1Ntk2O:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L80)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

change `console` -> `sh`?
</blockquote></details>

+1
___
*[Documentation/manpages/gramine-sgx-quote-dump.rst, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDXoeBFKI3bLeCee2:-MvZMnPy4WfOpkXanVDG:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-quote-dump.rst#L32)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

change `::` -> `:`. Better would be to remove `Example output::` and just add `.. code-block:: sh`
</blockquote></details>

+1
___
*[Documentation/manpages/gramine-sgx-quote-dump.rst, line 34 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZ-G6kCdI6l_gKKAGS:-MvZMoab6Xpfm3DJ9kN5:bzxgts) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-quote-dump.rst#L34)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Simply use `>` instead of `code-block:: cosole+$` to bypass the `unexpected indentation` warning caused by the indents in report_body.
Please kindly let me know if any better approach. Thanks.
</blockquote></details>

See @vijaydhanraj 's reply below.
___
*[Documentation/manpages/is-sgx-available.rst, line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZKG3bE8cOu-rKkVYT:-MvZMrSJ3D-IlkMYim33:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/is-sgx-available.rst#L47)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Remove redundant `Example output::` and simply add a code block ``.. code-block:: sh``.
</blockquote></details>

+1
___
*[Pal/src/host/Linux-SGX/tools/README.rst, line 171 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZLT0PE4exaN6pRnrz:-MvZMGh3E5Weq3G4RTt3:b-ji6p2b) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux-SGX/tools/README.rst#L171)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv I think we can safely remove this section as it is addressed in `attestation.rst` file.
</blockquote></details>

This whole file is removed, yes. We can remove all of this.
___
*[Pal/src/host/Linux-SGX/tools/README.rst, line 186 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZLk308ofUSX2gfFwU:-MvZMNudBcNZFT7ZJLMp:b-ji6p2b) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux-SGX/tools/README.rst#L186)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv I think we can safely remove this section as it is addressed in `attestation.rst` file.
</blockquote></details>

This whole file is removed, yes. We can remove all of this.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394)* status: 1 of 5 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 96 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZF8bc1IEjUTcfHLL2:-MvZO80cE8hr_gKfUUX9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L96)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`Example` -> `Examples`
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZCRYl7VxWUG6jl1WH:-MvZO8oE1ruRlruwGzb3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L99)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`::` make the following block a literal block. Please remove the double `:`.
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZD-zrC71N0cvgZ1Y8:-MvZO9dP7HybQbg5Yx_w:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. I would prefer `*SigRL* retrieval` (with asterisk)
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZFNhE01f0ruWjqDy7:-MvZOAgn0Od8dPummoIs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 101 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZJByz6RvmzEzjvrwt:-MvZOFm76CSbflDLOdKh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I recommended `console` as it is the most "common" one. But I think we use `sh` in all other documentation, so let's use `sh` here as well.
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 106 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDABQ59OeFND2Pmkr:-MvZOOwR9t8sFE7xSFiW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDNNiCXbNabZDeCtg:-MvZOksj67ZtFJqYRbVV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-request.rst#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-ias-verify-report.rst, line 78 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDG_L2c5J8IxLi8qC:-MvZOuhb6pPn9MMeAc6D:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-ias-verify-report.rst, line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZJmYB5M1XuPckN5d-:-MvZOvaz9YOYM9giYHvf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-quote-dump.rst, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZDXoeBFKI3bLeCee2:-MvZPIee17b5XUEOc-3R:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-quote-dump.rst#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-quote-dump.rst, line 34 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZJ27Y4vFowWeiM0nn:-MvZPKmo2ScELUqgiRZY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/gramine-sgx-quote-dump.rst#L34)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Now we can replace `>` with`$`
</blockquote></details>

Done.
___
*[Documentation/manpages/is-sgx-available.rst, line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/394#-MvZKG3bE8cOu-rKkVYT:-MvZPPaLBmzr_yiW0W7g:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82391c684e7ca7cc663d9b576727a21ba8c99b9b/Documentation/manpages/is-sgx-available.rst#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by vijaydhanraj — COMMENTED** [review]
Looks good to me. Thanks!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394#-:-MvZa7uN5xFdQSLpJaQA:b-8a64xx)* status: 1 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @vijaydhanraj)

___
*[-- commits, line 18 at r3](https://reviewable.io/reviews/gramineproject/gramine/394#-Mvbk2QI0X2SkkSdtNG9):*
For the future: please use `git commit --fixup=<base_commit_of_pr>` for new commits.

A good reference: https://blog.sebastian-daschner.com/entries/git-commit-fixup-autosquash

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @kailun-qin and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/394#-MveBqNt0wX6g5RcY_3f:-MveBqNuE8lJ-mr8raer:b-b4nd0f) (no related file):*
In the future, please create PRs from branches in "kailun-qin/<change-descr>" format, even if it's from you private repo - this makes it a bit easier for us to pull it and rebase before merging without polluting our local branch namespaces.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @kailun-qin and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/394#-MveBqNt0wX6g5RcY_3f:-MvfZWf-DazwnVCcMCcS:b-bbe0ut) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In the future, please create PRs from branches in "kailun-qin/<change-descr>" format, even if it's from you private repo - this makes it a bit easier for us to pull it and rebase before merging without polluting our local branch namespaces.
</blockquote></details>

Oops, it was supposed to be `kailun-qin/<change-descr>`, but the last part got formatted out, sorry ;)

---

**Comment by kailun-qin** [comment]
> 

Thanks @mkow ! I'll do this for future PRs.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/394)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
