### PR TITLE
[Docs] Update "Gramine features" with v1.6 features

### LINKED ISSUE #1634: Add new changes to "Gramine features" before v1.6 release
### Description of the feature

This document: https://gramine.readthedocs.io/en/latest/devel/features.html

It must be updated with the following changes that we had in Gramine. Ideally, we should update that document before release v1.6, so that the `stable` documentation shows the correct info for v1.6.

- [ ] Shared untrusted memory. See #827.
- [ ] TODO: anything else?

### Why Gramine should implement it?

For up-to-date documentation.

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Added descriptions of POSIX shared memory, POSIX semaphores, a note on `sendfile()` syscall, a note on `-EINPROGRESS` during non-blocking `connect()`, new "siblings" line in /proc/cpuinfo, three new files under /sys/devices/system/cpu/ (`kernel_max`, `offline`, `present`).

Fixes #1634.

## How to test this PR? 

Temporarily enabled in ReadTheDocs: https://gramine.readthedocs.io/en/dimakuv-docs-update-gramine-features-nov-2023/devel/features.html

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1663)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1663)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Documentation/devel/features.md` line 2709 at r1](https://reviewable.io/reviews/gramineproject/gramine/1663#-NkUs30vDz-zpKndEJxW:-NkUs30vDz-zpKndEJxX:b-sot0y3) ([raw file](https://github.com/gramineproject/gramine/blob/190dfb786e1c209eb09176228372dba0a7fc8679/Documentation/devel/features.md#L2709)):*
> ```Markdown
> 
> Gramine currently has limited support for POSIX semaphores. Gramine does *not* implement System V
> semaphores.
> ```

This part about POSIX semaphores came up rather unexpectedly. Only now I realized that POSIX semaphores should work if `/dev/shm/` files are specified in the manifest, but they will be insecure.

I hope the current text makes it very clear that this is insecure.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1663)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/devel/features.md` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1663#-NkV7Dpt4h9nWcNVGh5M:-NkV7Dpt4h9nWcNVGh5N:bmmr4i0) ([raw file](https://github.com/gramineproject/gramine/blob/190dfb786e1c209eb09176228372dba0a7fc8679/Documentation/devel/features.md#L10)):*
> ```Markdown
> > kernels.
> 
> > ⛏ This is a living document. The last major update happened in **December 2023** and closely
> ```

So, we can't merge it today? :upside_down_face:
___
*[`Documentation/devel/features.md` line 2709 at r1](https://reviewable.io/reviews/gramineproject/gramine/1663#-NkUs30vDz-zpKndEJxW:-NkV8Uug5fVfJEcWRzhK:bjdwhw7) ([raw file](https://github.com/gramineproject/gramine/blob/190dfb786e1c209eb09176228372dba0a7fc8679/Documentation/devel/features.md#L2709)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This part about POSIX semaphores came up rather unexpectedly. Only now I realized that POSIX semaphores should work if `/dev/shm/` files are specified in the manifest, but they will be insecure.

I hope the current text makes it very clear that this is insecure.
</blockquote></details>

Now I'm really glad that I insisted on specifying each file in `/dev/shm` separately :P
___
*[`Documentation/devel/features.md` line 2715 at r1](https://reviewable.io/reviews/gramineproject/gramine/1663#-NkV93vX9nYLag0AiG6Y:-NkV93vX9nYLag0AiG6Z:b-nswioq) ([raw file](https://github.com/gramineproject/gramine/blob/190dfb786e1c209eb09176228372dba0a7fc8679/Documentation/devel/features.md#L2715)):*
> It is the responsibility of the app developer to correctly use POSIX semaphores, with security implications in mind.

I wouldn't suggest that, it's probably impossible. The implementation of these semaphores (which the user doesn't control) may assume that processes using the semaphore are all in the same security domain, so it trusts the data there. In this case one end is untrusted and may trigger some memory corruptions in the enclave this way.
Which is something most users won't consider.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1663)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/devel/features.md` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1663#-NkV7Dpt4h9nWcNVGh5M:-NkVIFnLAB57QLgrM5bb:bfc9bdi) ([raw file](https://github.com/gramineproject/gramine/blob/190dfb786e1c209eb09176228372dba0a7fc8679/Documentation/devel/features.md#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, we can't merge it today? :upside_down_face:
</blockquote></details>

Let me put a blocking comment here, and depending on when it's gonna be merged, I'll fix the month during final rebase.
___
*[`Documentation/devel/features.md` line 2715 at r1](https://reviewable.io/reviews/gramineproject/gramine/1663#-NkV93vX9nYLag0AiG6Y:-NkVIWtd4X_Y48tILDdM:bl0lvs8) ([raw file](https://github.com/gramineproject/gramine/blob/190dfb786e1c209eb09176228372dba0a7fc8679/Documentation/devel/features.md#L2715)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> It is the responsibility of the app developer to correctly use POSIX semaphores, with security implications in mind.

I wouldn't suggest that, it's probably impossible. The implementation of these semaphores (which the user doesn't control) may assume that processes using the semaphore are all in the same security domain, so it trusts the data there. In this case one end is untrusted and may trigger some memory corruptions in the enclave this way.
Which is something most users won't consider.
</blockquote></details>

Done. Just removed this sentence.

Btw, theoretically we could provide a secure implementation of POSIX semaphores, as another patch to Glibc and Musl. I don't think we'll ever bother implementing and maintaining this, but theoretically possible.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1663)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1663)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1663)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`Documentation/devel/features.md` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1663#-NkV7Dpt4h9nWcNVGh5M:-NkVfUsICRASUqtpGjQM:b7fysil) ([raw file](https://github.com/gramineproject/gramine/blob/190dfb786e1c209eb09176228372dba0a7fc8679/Documentation/devel/features.md#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me put a blocking comment here, and depending on when it's gonna be merged, I'll fix the month during final rebase.
</blockquote></details>

Done. Looks like we'll merge this today :)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1663)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
