### PR TITLE
[LibOS] Initialize socket handles to be readable and writable

### LINKED ISSUE #469: EAGAIN while accept()
## Description of the problem
While launching a simple asynch. HTTPS server with gramine-direct v1.1, I am running into an accept() error (11, EAGAIN).
The timeout value (5 * 60 * 1000 s.) is hardcoded in the boost headers. The source for the HTTPS
server is the unmodified example from:

https://www.boost.org/doc/libs/develop/libs/beast/example/http/server/async-ssl/http_server_async_ssl.cpp

## Gramine log excerpt
```
[P1:T1:exhttps] trace: ---- shim_getpid() = 0x1
[P1:T1:exhttps] trace: ---- shim_time(0) = 0x623adaa7
[P1:T1:exhttps] trace: ---- shim_eventfd2(0, 526336) = 0x3
[P1:T1:exhttps] trace: ---- shim_epoll_create1(524288) = 0x4
[P1:T1:exhttps] warning: Unsupported system call timerfd_create
[P1:T1:exhttps] debug: epoll: added 3 (0x7ffff3ef9e18) to epoll handle 0x7ffff3ef9f28
[P1:T1:exhttps] trace: ---- shim_epoll_ctl(4, ADD, 3, {.events=EPOLLIN|EPOLLERR|EPOLLET, .data=0x2327bec4b780}) = 0x0
[P1:T1:exhttps] trace: ---- shim_write(3, 0x2327bf649360, 0x8) ...
[P1:T1:exhttps] trace: ---- return from shim_write(...) = 0x8
[P1:T1:exhttps] trace: ---- shim_socket(INET, STREAM, 6) = 0x5
[P1:T1:exhttps] debug: epoll: added 5 (0x7ffff3efa038) to epoll handle 0x7ffff3ef9f28
[P1:T1:exhttps] trace: ---- shim_epoll_ctl(4, ADD, 5, {.events=EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLET, .data=0x2327bec4b7f0}) = 0x0
[P1:T1:exhttps] trace: ---- shim_setsockopt(5, 1, 2, 0x2327bf64972c, 4) = 0x0
[P1:T1:exhttps] trace: ---- shim_bind(5, 0x2327bf6497d0, 16) = 0x0
[P1:T1:exhttps] trace: ---- shim_listen(5, 4096) = 0x0
[P1:T1:exhttps] trace: ---- shim_ioctl(5, FIONBIO, 0x2327bf649828) ...
[P1:T1:exhttps] trace: ---- return from shim_ioctl(...) = 0x0
[P1:T1:exhttps] trace: ---- shim_accept(5, 0, 0) ...
[P1:T1:exhttps] trace: ---- return from shim_accept(...) = -11
[P1:T1:exhttps] trace: ---- shim_epoll_wait(4, 0x2327bf649340, 128, 300000) ...
[P1:T1:exhttps] trace: ---- return from shim_epoll_wait(...) = 0x1
[P1:T1:exhttps] trace: ---- shim_epoll_wait(4, 0x2327bf649340, 128, 300000) ...
```

While investigating the sources I have found some points I'd like to mention:

Code exccerpt from **v1.1**:
```c
static int __do_accept(struct shim_handle* hdl, int flags, struct sockaddr* addr, int* addrlen) {
    assert(WITHIN_MASK(flags, O_CLOEXEC | O_NONBLOCK));
```

Since flags is 0, this assert is true and the reason for returning with EAGAIN.
Whereas in **v1.0** it was handled in a way which caused no problems:
```c
static int __do_accept(struct shim_handle* hdl, int flags, struct sockaddr* addr, int* addrlen) {
    if (hdl->type != TYPE_SOCK)
        return -ENOTSOCK;
```

The flags are passed from shim/src/bookkeep/shim_handle.c and by checking the relevant structures I have foudn two suspicious comments:
```c
struct shim_handle* __get_fd_handle(uint32_t fd, int* fd_flags, struct shim_handle_map* map) {
  ...
    struct shim_fd_handle* fd_handle = NULL;
	...
    *fd_flags = fd_handle->flags;
  ...
```

shim/include/shim_handle.h we have for the **struct shim_handle**:
```c
    /* TODO: the `flags` and `acc_mode` fields contain duplicate information (the access mode).
     * Instead of `flags`, we should have a field with different name (such as `options`) that
     * contain the open flags without access mode (i.e. set it to `flags & ~O_ACCMODE`). */
    int flags; /* Linux' O_* flags */
    int acc_mode;
```

And for the **struct shim_fd_handle**:
```c
struct shim_fd_handle {
    uint32_t vfd; /* virtual file descriptor */
    int flags;    /* file descriptor flags, only FD_CLOEXEC */
  ...
```

The flags of shim_fd_handle is about FD_CLOEXEC only and flags for shim_handle is
about the O_ flags. In __get_fd_handle though, the shim_fd_handle flags are assigned and checked against O_ flags.

### LINKED ISSUE #489: issue with epoll_wait
## Description of the problem
epoll_wait times out without detecting the events. This was detected while using nginx in reverse proxy mode. The nginx forwards the requests to upstream server but does not recognize the response from upstream server. Captured the packets and saw that upstream server is receiving the request and responding. After debugging into the nginx code figured that epoll_wait is returning zero events and timing out. So, put together a sample test based on opensource socket programming examples to reproduce the epoll_wait issue.

## Steps to reproduce

1. Use the attached testcase epoll_issue.tar.gz
2. Extract the files into CI-Example directory
3. Build using make.
4. run the server normally. The server listens on port 50051
    %./server
5. run the client under gramine
    %gramine-direct ./helloworld
## Expected results
1. The client connects to the server, sends a hello and waits on epoll_wait.
2. server responds back with "hello from server". 
3. epoll_wait in the client recognizes the event and wakes up.
4. client calls recv to receive the message and print

## Actual results
In case of gramine execution, the epoll_wait times out and receives no events. 

## Gramine commit hash
It works only till commit c4c88f9bc1db53460774cd8adb07267236cef039 on 27th Jan 2021. We tried with latest from mainline, v1.1 and they did not work. 

[epoll_issue.tar.gz](https://github.com/gramineproject/gramine/files/8409232/epoll_issue.tar.gz)

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This is a temporary fix - rewrite of the whole subsystem is WIP. Hopefully we don't break anything with this...

Fixes #469, fixes #489

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/499)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please (previous run was successful, just testing some more)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/499)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by boryspoplawski** [comment]
Jenkins, test this please (previous run was successful, just testing some more)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/499)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/499)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/499#-N-1uHGL1l3SfmznPPtg:-N-1uHGL1l3SfmznPPth:b-3gjfbr) (no related file):*
I tested all examples from https://github.com/gramineproject/examples, except OpenVINO (it downloads too much stuff, I decided to skip it since it shouldn't use sockets anyway). All examples pass fine.

I suggest to wait for other feedback until the end of the day, and if everything is fine, then merge.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/499)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/499)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/499#-N-1uHGL1l3SfmznPPtg:-N-6p4jgB1zhPYXcETsd:blnlqk3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I tested all examples from https://github.com/gramineproject/examples, except OpenVINO (it downloads too much stuff, I decided to skip it since it shouldn't use sockets anyway). All examples pass fine.

I suggest to wait for other feedback until the end of the day, and if everything is fine, then merge.
</blockquote></details>

The PR was tested against a wide set of workloads yesterday, they all passed. This PR is ready for merge.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/499)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/499)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
