### PR TITLE
[Meson] Don't require `protoc` in non-SGX builds

### LINKED ISSUE #201: Quick start instructions missing protoc-c install  for non-SGX environment
## Description of the problem
Quick start instructions missing protoc-c install  for non-SGX environment in Ubuntu 20 (focal) environment.
## Steps to reproduce
Fresh Ubuntu 20.04.2 LTS environment. Clone gramine.
while executing " meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=disabled" 
ran into an error. 

## Expected results
no errors
## Actual results
"meson.build:40:0: ERROR: Program 'protoc-c' not found"
## Additional information 
Please provide link to https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/protobuf-c-compiler_1.3.3-1_amd64.deb.html
or inline the following two commands:
Update the package index:
> sudo apt-get update
Install protobuf-c-compiler deb package:
> sudo apt-get install protobuf-c-compiler

or alternately add in sudo apt-get command for build essentials both of "libprotobuf-c-dev  and
    protobuf-c-compiler"

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

Fixes #201.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/206)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/206)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/206)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/206#-Mo3N7kd8OpLWfuf7sot:-Mo3N7ke9X8B4kfkrlyL:b4p0b21) (no related file):*
Can this be further restricted to oot driver? In theory it should be possible.

---

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/206)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/206#-Mo3N7kd8OpLWfuf7sot:-Mo3bnLg9KaOW1T2A27f:bd0byjy) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can this be further restricted to oot driver? In theory it should be possible.
</blockquote></details>

But we need Protobuf anyway. With SGX remote attestation, we *always* talk to the Quoting Enclave through the AESM daemon's socket, no matter if DCAP or EPID and no matter which SGX driver. Talking through AESM *always* uses the Protobuf messages. So there is no way restrict it further.

---

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/206)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/206#-Mo3N7kd8OpLWfuf7sot:-Mo3lwOt3kNI6Un5xUPH:bbe7zz5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But we need Protobuf anyway. With SGX remote attestation, we *always* talk to the Quoting Enclave through the AESM daemon's socket, no matter if DCAP or EPID and no matter which SGX driver. Talking through AESM *always* uses the Protobuf messages. So there is no way restrict it further.
</blockquote></details>

Ah, OK. So please disregard.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/206)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
