### PR TITLE
[common] Remove static function declarations from protected_files_internal.h

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

As suggested in review https://reviewable.io/reviews/gramineproject/gramine/719 we don't want to have a file header with static definitions used in a single file.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`common/src/protected_files/protected_files.c` line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/766#-N7K8p7l6owYFKMiIuyZ:-N7K8p7l6owYFKMiIuy_:b8o5149) ([raw file](https://github.com/gramineproject/gramine/blob/6eb816a31cfe10a6099a2144011cbd036139d185/common/src/protected_files/protected_files.c#L87)):*
> ```C
> }
> 
> static bool ipf_generate_random_key(pf_context_t* pf, pf_key_t* output) {
> ```

I would move this function right-before `ipf_import_metadata_key()`, feels more appropriate there:
- It belongs to a block of functions that have `ipf_` prefix
- It belongs to a block of functions that work on keys
___
*[`common/src/protected_files/protected_files.c` line 203 at r1](https://reviewable.io/reviews/gramineproject/gramine/766#-N7K9mZG1zPpddL8BEg0:-N7K9mZG1zPpddL8BEg1:b92qj0z) ([raw file](https://github.com/gramineproject/gramine/blob/6eb816a31cfe10a6099a2144011cbd036139d185/common/src/protected_files/protected_files.c#L203)):*
> ```C
> }
> 
> static bool ipf_update_all_data_and_mht_nodes(pf_context_t* pf) {
> ```

Maybe move `ipf_init_root_mht()` right-before this function? It belongs to this block of "working with nodes".

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files.c` line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/766#-N7K8p7l6owYFKMiIuyZ:-N7LMedn8WQU0ey4y9SW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6eb816a31cfe10a6099a2144011cbd036139d185/common/src/protected_files/protected_files.c#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would move this function right-before `ipf_import_metadata_key()`, feels more appropriate there:
- It belongs to a block of functions that have `ipf_` prefix
- It belongs to a block of functions that work on keys
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.c` line 203 at r1](https://reviewable.io/reviews/gramineproject/gramine/766#-N7K9mZG1zPpddL8BEg0:-N7LN6_fAHf73-slqfD3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6eb816a31cfe10a6099a2144011cbd036139d185/common/src/protected_files/protected_files.c#L203)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe move `ipf_init_root_mht()` right-before this function? It belongs to this block of "working with nodes".
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/766#-N7gfm_J4u5UirWjuzZ7:-N7gfm_J4u5UirWjuzZ8:b-iu370r) (no related file):*
Hmm, maybe instead of rearranging functions in their topological order we could just forward-declare the ones which need this?
This PR is really PITA to review, and I think the original order was more logical? (at least in some cases)

___
___
*[`common/src/protected_files/protected_files.c` line 67 at r2](https://reviewable.io/reviews/gramineproject/gramine/766#-N7gZes28B-eWblaAhsC:-N7gZes28B-eWblaAhsD:b-vah7kc) ([raw file](https://github.com/gramineproject/gramine/blob/1bedf05a96ac23cbe8ec5c4bf0c01c64992d4a44/common/src/protected_files/protected_files.c#L67)):*
> ```C
> /* ipf prefix means "Intel protected files", these are functions from the SGX SDK implementation */
> static file_node_t* ipf_append_data_node(pf_context_t* pf, uint64_t offset);
> static file_node_t* ipf_append_mht_node(pf_context_t* pf, uint64_t mht_node_number);
> ```

I'd swap this line and the one above, for consistency.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/766#-N7gfm_J4u5UirWjuzZ7:-N7uA5DABdKoH78mFUaD:b-c5z2iq) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, maybe instead of rearranging functions in their topological order we could just forward-declare the ones which need this?
This PR is really PITA to review, and I think the original order was more logical? (at least in some cases)
</blockquote></details>

I don't have a strong opinion but I kinda like new order.
First goes common functions, then nodes one, and so on.
But dunno @dimakuv what you think?

___

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/766#-N7gfm_J4u5UirWjuzZ7:-N7uCK3y6bOiepkut-MU:b-e4nryd) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I don't have a strong opinion but I kinda like new order.
First goes common functions, then nodes one, and so on.
But dunno @dimakuv what you think?
</blockquote></details>

I also like the new order.

___
___
*[`common/src/protected_files/protected_files.c` line 67 at r2](https://reviewable.io/reviews/gramineproject/gramine/766#-N7gZes28B-eWblaAhsC:-N7uCDE31BekH3ZtaEac:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/1bedf05a96ac23cbe8ec5c4bf0c01c64992d4a44/common/src/protected_files/protected_files.c#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd swap this line and the one above, for consistency.
</blockquote></details>

+1

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/766#-N7gfm_J4u5UirWjuzZ7:-N7v_zj8AS6lMOQ-0ppn:b4dzjco) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also like the new order.
</blockquote></details>

Ok, I just read all of them and it doesn't look that bad, resolving.

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`common/src/protected_files/protected_files.c` line 67 at r2](https://reviewable.io/reviews/gramineproject/gramine/766#-N7gZes28B-eWblaAhsC:-N7vb-Nv93HufdW7qgFm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1bedf05a96ac23cbe8ec5c4bf0c01c64992d4a44/common/src/protected_files/protected_files.c#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/766)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
