### PR TITLE
[packaging/docker] Update dockerfile to match post v1.3 repo name

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Since v1.3 Ubuntu 20.04 has dedicated Gramine package.

## How to test this PR? 
Try building docker image

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/947)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/947)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/947#-NDB5mJY7dgJkqH3H9Qj):*




_Suggestion:_
```
Update Dockerfile to match post-v1.3 repo name
```

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/947)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/947#-NDB5mJY7dgJkqH3H9Qj):*
Maybe `post v1.3` -> `1.3+`? It reads more natural to me ("since version 1.3 and above")

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/947)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/947#-NDDEwFgAa-5Zs-bEoK1:-NDDEwFh31AEJ0BBEP7S:beqwdfy) (no related file):*
FYI: I manually verified this on an EPID machine and on an Azure DCAP machine. Everything works.

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/947)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/947#-NDB5mJY7dgJkqH3H9Qj):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe `post v1.3` -> `1.3+`? It reads more natural to me ("since version 1.3 and above")
</blockquote></details>

sgtm

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/947)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/947#-NDB5mJY7dgJkqH3H9Qj):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/947)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/947)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
