### PR TITLE
[LibOS] Warn when app tries using disabled eventfd

### PR DESCRIPTION
**Pull request by NieDzejkob**
## How to test this PR?

See #495 for an example of an application making use of eventfd.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NieDzejkob)

___
*[LibOS/shim/src/sys/shim_eventfd.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/525#-N-awZNw3s7fFXLkG6Ei:-N-awZNw3s7fFXLkG6Ej:b-7r40gs) ([raw file](https://github.com/gramineproject/gramine/blob/00f8af184f9bf8125fda4d2e1498b8b5533ab9f8/LibOS/shim/src/sys/shim_eventfd.c#L36)):*
> ```C
>     if (!allow_eventfd) {
>         /* eventfd is not explicitly allowed in manifest */
>         log_warning("eventfd support is turned off (sys.insecure__allow_eventfd = false)");
> ```

Shouldn't we show the warning only once? We have some other examples where we do it. One example:
```
    static int first = 0;
    if (__atomic_exchange_n(&first, 1, __ATOMIC_RELAXED) == 0) {
        /* if we end up emulating RDTSC/RDTSCP instruction, we cannot use invariant TSC */
        extern uint64_t g_tsc_hz;
        g_tsc_hz = 0;
        log_warning("all RDTSC/RDTSCP instructions are emulated (imprecisely) via gettime() "
                    "syscall.");
    }
```

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NieDzejkob)

___
*[LibOS/shim/src/sys/shim_eventfd.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/525#-N-bocr94ZaN3MsM-9xq:-N-bocr94ZaN3MsM-9xr:bqhjkm5) ([raw file](https://github.com/gramineproject/gramine/blob/00f8af184f9bf8125fda4d2e1498b8b5533ab9f8/LibOS/shim/src/sys/shim_eventfd.c#L36)):*
> ```C
>     if (!allow_eventfd) {
>         /* eventfd is not explicitly allowed in manifest */
>         log_warning("eventfd support is turned off (sys.insecure__allow_eventfd = false)");
> ```

I'd add at the end: "but the app tried to use it" (because the fact that it's off is not a problem in itself).

**Review by NieDzejkob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @NieDzejkob)

___
*[LibOS/shim/src/sys/shim_eventfd.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/525#-N-awZNw3s7fFXLkG6Ei:-N-eJmSp76t_-GdLBc6v:btrr2sr) ([raw file](https://github.com/gramineproject/gramine/blob/00f8af184f9bf8125fda4d2e1498b8b5533ab9f8/LibOS/shim/src/sys/shim_eventfd.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we show the warning only once? We have some other examples where we do it. One example:
```
    static int first = 0;
    if (__atomic_exchange_n(&first, 1, __ATOMIC_RELAXED) == 0) {
        /* if we end up emulating RDTSC/RDTSCP instruction, we cannot use invariant TSC */
        extern uint64_t g_tsc_hz;
        g_tsc_hz = 0;
        log_warning("all RDTSC/RDTSCP instructions are emulated (imprecisely) via gettime() "
                    "syscall.");
    }
```
</blockquote></details>

That's quite a mouthful, and a quick grep shows that it does occur quite a few times in the codebase. Perhaps we should have a macro that handles this? Something like `DO_ONCE { ... }`?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_eventfd.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/525#-N-bocr94ZaN3MsM-9xq:-N-gdACz5UdhyAogJDhg:b5pm3v2) ([raw file](https://github.com/gramineproject/gramine/blob/00f8af184f9bf8125fda4d2e1498b8b5533ab9f8/LibOS/shim/src/sys/shim_eventfd.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add at the end: "but the app tried to use it" (because the fact that it's off is not a problem in itself).
</blockquote></details>

I would add that at the beginning (`The app tried to use eventfd, but it's turned off (manifest_option_here)`) :)
___
*[LibOS/shim/src/sys/shim_eventfd.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/525#-N-awZNw3s7fFXLkG6Ei:-N-gd00s-23MbYd8GQn1:b-h4pzgr) ([raw file](https://github.com/gramineproject/gramine/blob/00f8af184f9bf8125fda4d2e1498b8b5533ab9f8/LibOS/shim/src/sys/shim_eventfd.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sure, that would be nice. You can stuck it into this PR, as a first commit, or create a separate PR and then rebase this one on top.
</blockquote></details>

Please no `DO_ONCE` macros, that's not what we need and it would be tricky as hell (e.g. expecting it to run a whole block of code).

What we need is `log_once`, not sure how to connect that with log levels (do we want `log_warning_once` or ?)

**Review by NieDzejkob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/sys/shim_eventfd.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/525#-N-awZNw3s7fFXLkG6Ei:-N00TQDr7xZcy15K2M-f:b-bjhg5e) ([raw file](https://github.com/gramineproject/gramine/blob/00f8af184f9bf8125fda4d2e1498b8b5533ab9f8/LibOS/shim/src/sys/shim_eventfd.c#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please no `DO_ONCE` macros, that's not what we need and it would be tricky as hell (e.g. expecting it to run a whole block of code).

What we need is `log_once`, not sure how to connect that with log levels (do we want `log_warning_once` or ?)
</blockquote></details>

That's the thing, sometimes the log message is not the only thing being done (see `g_tsc_hz` above). Another option would be to have `if (FIRST_TIME)` / `if (DO_ONCE)` or something like that. Not sure what a good name would be then, though.

(the internals would involve a GNU statement expression to declare the atomic variable)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_eventfd.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/525#-N-awZNw3s7fFXLkG6Ei:-N00V7-d2neLhqeW5w9P:byktjcj) ([raw file](https://github.com/gramineproject/gramine/blob/00f8af184f9bf8125fda4d2e1498b8b5533ab9f8/LibOS/shim/src/sys/shim_eventfd.c#L36)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

That's the thing, sometimes the log message is not the only thing being done (see `g_tsc_hz` above). Another option would be to have `if (FIRST_TIME)` / `if (DO_ONCE)` or something like that. Not sure what a good name would be then, though.

(the internals would involve a GNU statement expression to declare the atomic variable)
</blockquote></details>

Then I wouldn't bother, it's not that bad.

**Review by NieDzejkob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`LibOS/shim/src/sys/shim_eventfd.c` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/525#-N-awZNw3s7fFXLkG6Ei:-N1n4IQu-ILGkAgMayAW:b-wbu3m3) ([raw file](https://github.com/gramineproject/gramine/blob/00f8af184f9bf8125fda4d2e1498b8b5533ab9f8/LibOS/shim/src/sys/shim_eventfd.c#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then I wouldn't bother, it's not that bad.
</blockquote></details>

Rebased on current `master`, the code now uses the `FIRST_TIME()` macro.
___
*[`LibOS/shim/src/sys/shim_eventfd.c` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/525#-N-bocr94ZaN3MsM-9xq:-N1n4NiJ39cgP0sSTiSZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/00f8af184f9bf8125fda4d2e1498b8b5533ab9f8/LibOS/shim/src/sys/shim_eventfd.c#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would add that at the beginning (`The app tried to use eventfd, but it's turned off (manifest_option_here)`) :)
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/525)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
