### PR TITLE
[CI] Update custom Docker seccomp policy

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Commit "[CI] Add custom Docker seccomp policy" from 23. Sep 2021 added a Gramine-specific seccomp policy that takes the default Docker seccomp policy and modifies it to enable `personality` syscall. The default Docker seccomp policy was taken from
https://github.com/moby/moby/blob/2773f81aa5e9e34733675a7aa7e4219391caccb0/profiles/seccomp/default.json, which dates to Mar 2021. In the meantime, this default policy was updated to support new features -- in particular, the `clone3` syscall used by newer Glibc. But since our custom policy was based on an year-old one, using our policy started breaking Docker containers.

This PR updates our custom seccomp policy, derived from https://github.com/moby/moby/blob/7b7d1132e870d4b6265721b673dbb429cc835d6a/profiles/seccomp/default.json, which dates to Aug 2022 (the only difference in our custom policy is the enabled `personality` syscall).

References:
- https://github.com/gramineproject/gramine/commit/1813de6b454706195a8078c8b49227d9f98c28ff -- commit from @boryspoplawski where Docker seccomp policy was introduced
- https://github.com/moby/moby/blob/2773f81aa5e9e34733675a7aa7e4219391caccb0/profiles/seccomp/default.json -- old default Docker seccomp policy (on which commit above was based)
- https://github.com/moby/moby/blob/7b7d1132e870d4b6265721b673dbb429cc835d6a/profiles/seccomp/default.json -- new default Docker seccomp policy (on which this PR is based)
- https://github.com/moby/moby/commit/9f6b562dd12ef7b1f9e2f8e6f2ab6477790a6594 -- most relevant update to the default Docker seccomp policy, explaining `clone3` addition
- https://bugs.launchpad.net/cloud-images/+bug/1943049 -- detailed history of the `clone3` problem; this was the issue @anjalirai-intel hit, thanks to her for root causing!

## Git diffs for convenience

Here are the git diffs that may be of help while reviewing:

- The differences before this PR:
```diff
diff --git a/old_docker_seccomp.json b/docker_seccomp.json
index f94f0e2e..cad844b8 100644
--- a/old_docker_seccomp.json
+++ b/docker_seccomp.json
@@ -421,55 +421,7 @@
            "args": [
                {
                    "index": 0,
-                   "value": 0,
-                   "op": "SCMP_CMP_EQ"
-               }
-           ],
-           "comment": "",
-           "includes": {},
-           "excludes": {}
-       },
-       {
-           "names": [
-               "personality"
-           ],
-           "action": "SCMP_ACT_ALLOW",
-           "args": [
-               {
-                   "index": 0,
-                   "value": 8,
-                   "op": "SCMP_CMP_EQ"
-               }
-           ],
-           "comment": "",
-           "includes": {},
-           "excludes": {}
-       },
-       {
-           "names": [
-               "personality"
-           ],
-           "action": "SCMP_ACT_ALLOW",
-           "args": [
-               {
-                   "index": 0,
-                   "value": 131072,
-                   "op": "SCMP_CMP_EQ"
-               }
-           ],
-           "comment": "",
-           "includes": {},
-           "excludes": {}
-       },
-       {
-           "names": [
-               "personality"
-           ],
-           "action": "SCMP_ACT_ALLOW",
-               {
-                   "index": 0,
-                   "value": 131080,
+                   "value": 4294967295,
                    "op": "SCMP_CMP_EQ"
                }
            ],
@@ -485,8 +437,9 @@
            "args": [
                {
                    "index": 0,
-                   "value": 4294967295,
-                   "op": "SCMP_CMP_EQ"
+                   "value": 18446744073709158391,
+                   "valueTwo": 0,
+                   "op": "SCMP_CMP_MASKED_EQ"
                }
            ],
            "comment": "",
```

- The differences after this PR:
```diff
diff --git a/new_docker_seccomp.json b/docker_seccomp.json
index f1351ba9..3464b07b 100644
--- a/new_docker_seccomp.json
+++ b/docker_seccomp.json
@@ -428,46 +428,7 @@
            "args": [
                {
                    "index": 0,
-                   "value": 0,
-                   "op": "SCMP_CMP_EQ"
-               }
-           ]
-       },
-       {
-           "names": [
-               "personality"
-           ],
-           "action": "SCMP_ACT_ALLOW",
-           "args": [
-               {
-                   "index": 0,
-                   "value": 8,
-                   "op": "SCMP_CMP_EQ"
-               }
-           ]
-       },
-       {
-           "names": [
-               "personality"
-           ],
-           "action": "SCMP_ACT_ALLOW",
-           "args": [
-               {
-                   "index": 0,
-                   "value": 131072,
-                   "op": "SCMP_CMP_EQ"
-               }
-           ]
-       },
-       {
-           "names": [
-               "personality"
-           ],
-           "action": "SCMP_ACT_ALLOW",
-           "args": [
-               {
-                   "index": 0,
-                   "value": 131080,
+                   "value": 4294967295,
                    "op": "SCMP_CMP_EQ"
                }
            ]
@@ -480,8 +441,9 @@
            "args": [
                {
                    "index": 0,
-                   "value": 4294967295,
-                   "op": "SCMP_CMP_EQ"
+                   "value": 18446744073709158391,
+                   "valueTwo": 0,
+                   "op": "SCMP_CMP_MASKED_EQ"
                }
            ]
        },
```

## How to test this PR? 

E.g. using GSC:
```
docker run --device=/dev/sgx_enclave \
  -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
  --security-opt seccomp=gramine/scripts/docker_seccomp.json \
  gsc-python -c 'print("HelloWorld!")'`
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1029)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1029)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1029#-NG2RTwY3oaSz7L5xU-V):*
To be exact `personality` was enabled, but some arguments were filtered.
___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1029#-NG2Rcre0XCw1CrhytyS):*
ditto

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1029)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1029#-NG0nbPZ6KhvfzbPiVie:-NGG0HeQCX0HZq7VrrFx:bng9lc1) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Our Jenkins machines do not understand the new seccomp policy:
```
09:32:00  $ docker run -t -d -u 1000:1000 --env=PATH=/home/jenkins/workspace/graphene-18.04/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin --security-opt seccomp=/home/jenkins/workspace/graphene-18.04/scripts/docker_seccomp.json -w /home/jenkins/workspace/graphene-18.04 -v /home/jenkins/workspace/graphene-18.04:/home/jenkins/workspace/graphene-18.04:rw,z -v 

09:32:06  java.io.IOException: Failed to run image 'local:jenkins-graphene-18.04-8658'. Error: docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: error adding seccomp filter rule for syscall clone3: permission denied: unknown.

09:32:06  	at org.jenkinsci.plugins.docker.workflow.client.DockerClient.run(DockerClient.java:138)
09:32:06  	at org.jenkinsci.plugins.docker.workflow.WithContainerStep$Execution.start(WithContainerStep.java:198)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:322)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
09:32:06  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
09:32:06  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
09:32:06  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
09:32:06  	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
09:32:06  	at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(Docker.groovy:126)
09:32:06  	at org.jenkinsci.plugins.docker.workflow.Docker.node(Docker.groovy:66)
09:32:06  	at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(Docker.groovy:114)
09:32:06  	at WorkflowScript.run(WorkflowScript:5)
09:32:06  	at ___cps.transform___(Native Method)
09:32:06  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
09:32:06  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
09:32:06  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
09:32:06  	at jdk.internal.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)
09:32:06  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:32:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
09:32:06  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
09:32:06  	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
09:32:06  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
09:32:06  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
09:32:06  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
09:32:06  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
09:32:06  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
09:32:06  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
09:32:06  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
09:32:06  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
09:32:06  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
09:32:06  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
09:32:06  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
09:32:06  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
09:32:06  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
09:32:06  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:32:06  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:32:06  	at java.base/java.lang.Thread.run(Thread.java:829)
```

Hm, what should we do here? Should we update our CI nodes to have latest Docker (plus a Java Jenkins Docker plugin??)? @boryspoplawski @woju 
</blockquote></details>

So what should I do now? Maybe just add this seccomp-policy file as a separate file, with the name like `docker-seccomp-aug-2022.json`? And people who have newer Docker engines will use this file?

___

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1029)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1029#-NG0nbPZ6KhvfzbPiVie:-NGH9O0228rHkIT5hyB1:b-pikj2d) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So what should I do now? Maybe just add this seccomp-policy file as a separate file, with the name like `docker-seccomp-aug-2022.json`? And people who have newer Docker engines will use this file?
</blockquote></details>

Do you have any idea at which point/version this seccomp profile starts to work? It it's just a matter of having up-to-date docker, even on e.g. ubuntu18.04 host (not to be confused with inside of docker image/base image), then we should just update our CI :)

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1029)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1029#-NG0nbPZ6KhvfzbPiVie:-NGM24toA2CVPyO7dOrY:b-7fes1p) (no related file):*
@boryspoplawski But what if some user wants to use the Gramine seccomp profile on his machine? And this machine has an old Docker engine? I'm not sure if it's always possible to use newer Docker versions on older OS distros (e.g. Ubuntu 18.04).

> Do you have any idea at which point/version this seccomp profile starts to work?

To be honest, no, I don't know. The `clone3` syscall support was added:
- in commit https://github.com/moby/moby/commit/9f6b562dd12ef7b1f9e2f8e6f2ab6477790a6594
- in Docker version 22.06

___

**Comment by anjalirai-intel** [comment]
You should also update this file
https://github.com/gramineproject/gramine/blob/master/.ci/lib/config-docker.jenkinsfile

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1029)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1029#-NG0nbPZ6KhvfzbPiVie:-NGQVevL1YaofDaVkz3M:bqixrz2) (no related file):*
> Idk then, I guess just add them both to repo and use the new one in CI?

Done. But I'm using the **old** one in CI, because we don't have updated Docker in CI (and I'm not sure it will be easily possible).

___
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1029#-NG2RTwY3oaSz7L5xU-V):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

To be exact `personality` was enabled, but some arguments were filtered.
</blockquote></details>

Done.
___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1029#-NG2Rcre0XCw1CrhytyS):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1029)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1029#-NGR6E5x6AnCx9YgRazO:-NGR6E5x6AnCx9YgRazP:b-wgt3kl) (no related file):*
For other reviewers: it's easiest to diff in local git. Just compare `docker_seccomp_mar_2021.json` with version from previous commit (should be the same) and `docker_seccomp_mar_2021.json` with `docker_seccomp_aug_2022.json` (the diff should be only changes introduced by docker folks) and `docker_seccomp_aug_2022.json` with the original seccomp (the diff should be only personality syscall augmented)

___

**Pull request merged**
