### PR TITLE
[CI] Revert to old source_fallback_urls

### PR DESCRIPTION
**Pull request by woju**
The new domain is not yet ready, so revert to old distfiles.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/128)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
Why revert? Why not add the old domain as an additional fallback?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/128#-:-MlFp0zJ4BfZMICf_mce:bi1q93r)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
+1 to Borys's request.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/128#-:-MlFqrHd5Y5otHraydrW:b-ircyfw)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — APPROVED** [review]
@woju says there is no option to have 2 fallback urls in Meson wrap, resolving.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/128#-:-MlFtkYj9yT5U320E_Yw:b-n1lugb)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/128)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by woju** [comment]
Closing as the https://packages.gramineproject.io/distfiles works now. Old URL redirects to the new one.

**Pull request closed without merging**
