### PR TITLE
[Docs] Add RHEL-8-like distros to list of supported distros

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Otherwise there is a discrepancy between our ["Quick start"](https://gramine.readthedocs.io/en/latest/quickstart.html) and ["Packaging and distributing"](https://gramine.readthedocs.io/en/latest/devel/packaging.html?highlight=20.04#packaging-and-distributing) pages.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/879)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/879)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`Documentation/devel/packaging.rst` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/879#-NBCxdqGCUQ5dO0EhMmG:-NBD1gfE3sXjBXA9qwCj:b-etn9a7) ([raw file](https://github.com/gramineproject/gramine/blob/cf69f3a36b81134241935e6e9038dd3fbbbf749c/Documentation/devel/packaging.rst#L11)):*
But do we want to add them all? Quick start says this:
> like AlmaLinux 8, CentOS 8, Rocky Linux 8, …

Is this really what we want to duplicate (verbatim) here as well?

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/879)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/devel/packaging.rst` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/879#-NBCxdqGCUQ5dO0EhMmG:-NBD7QC23UE-ea_3cIqs:b-rpryh9) ([raw file](https://github.com/gramineproject/gramine/blob/cf69f3a36b81134241935e6e9038dd3fbbbf749c/Documentation/devel/packaging.rst#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But do we want to add them all? Quick start says this:
> like AlmaLinux 8, CentOS 8, Rocky Linux 8, …

Is this really what we want to duplicate (verbatim) here as well?
</blockquote></details>

But why did you pick just one random entry from that list, one which is actually a rather dead distro? I'd either not list anything or list the same distros as on the other page.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/879)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/packaging.rst` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/879#-NBCxdqGCUQ5dO0EhMmG:-NBD8toa4Zv_OJsZqACo:bkyzgkz) ([raw file](https://github.com/gramineproject/gramine/blob/cf69f3a36b81134241935e6e9038dd3fbbbf749c/Documentation/devel/packaging.rst#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But why did you pick just one random entry from that list, one which is actually a rather dead distro? I'd either not list anything or list the same distros as on the other page.
</blockquote></details>

Done. I initially picked CentOS 8 because that's what I observe most users still use when they run Gramine on RHEL-like distros.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/879)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/879)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
