### PR TITLE
[CI] Ubuntu 24.04 and 22.04 part 2/?

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

See #2026 for rationale

## How to test this PR? 

CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2027)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 32 of 32 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2027)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-20.04 please (seems unrelated, this PR doesn't change LTP tests, also, this test seem to be failing sometimes, see: https://github.com/gramineproject/gramine/pull/1996#issuecomment-2373469631)

**Comment by mkow** [comment]
Jenkins, retest pkg-deb-debian12 please
Failed with:
```
22:17:24  hudson.plugins.git.GitException: Command "git submodule update --init --recursive libos/test/ltp/src" returned status code 1:
[...]
22:17:24  fatal: the remote end hung up unexpectedly
```

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 32 of 32 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2027)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
