### PR TITLE
[LibOS] Close open fds on thread exit

### PR DESCRIPTION
**Pull request by kailun-qin**
Fixes https://github.com/gramineproject/gramine/issues/824.

This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_handle.c` line 306 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96NW6M1vZk8lZkX2Hr:-N96NW6N4NFEKj8RWn3k:bv646a5) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/bookkeep/libos_handle.c#L306)):*
> ```C
> 
>     if (!handle_map_locked) {
>         lock(&handle_map->lock);
> ```

waait, you can't do this, it's inherently racy... `locked()` is correct almost only in asserts

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`libos/src/bookkeep/libos_handle.c` line 306 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96NW6M1vZk8lZkX2Hr:-N96RuDE1Tryag43-UWp:b-arl7f3) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/bookkeep/libos_handle.c#L306)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

waait, you can't do this, it's inherently racy... `locked()` is correct almost only in asserts
</blockquote></details>

emm... I didn't check the impl. of `locked()`.

Is adding an additional arg to `detach_fd_handle()` to explicitly sepecify whether a lock is needed makes sense to you? Or any better idea?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_handle.c` line 306 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96NW6M1vZk8lZkX2Hr:-N96Tu573tdWpJtXUxZ7:b-b4iaxl) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/bookkeep/libos_handle.c#L306)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

emm... I didn't check the impl. of `locked()`.

Is adding an additional arg to `detach_fd_handle()` to explicitly sepecify whether a lock is needed makes sense to you? Or any better idea?
</blockquote></details>

In Gramine codebase we usually split functions into `asdf()` and `__asdf()`, with the former being mostly `asdf() { lock(); __asdf(); unlock(); }`. And the callsite calls the correct one, depending whether it has the lock taken or not.
Here the already implemented construction is a bit weirder though (the lock-taking function has some additional logic), so you may need to try some refactoring and see whether it's possible to fix it while preserving our conventions.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`libos/src/bookkeep/libos_handle.c` line 306 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96NW6M1vZk8lZkX2Hr:-N96TGeK-hlQ2mPV5LRt:b-1w68l0) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/bookkeep/libos_handle.c#L306)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In Gramine codebase we usually split functions into `asdf()` and `__asdf()`, with the former being mostly `asdf() { lock(); __asdf(); unlock(); }`. And the callsite calls the correct one, depending whether it has the lock taken or not.
Here the already implemented construction is a bit weirder though (the lock-taking function has some additional logic), so you may need to try some refactoring and see whether it's possible to fix it while preserving our conventions.
</blockquote></details>

Good to know, thanks! Let me take a closer look.

**Comment by kailun-qin** [comment]
@mkow Got a bit confused here: https://github.com/gramineproject/gramine/blob/master/libos/src/bookkeep/libos_handle.c#L378. Looks like not all __asdf() are following the convention?

**Review by mkow — COMMENTED** [review]
I think that part of the codebase is super old and we just never refactored it. It seems that there `__` prefix means just "internal helper".

btw. Please never link to `master` branch, this will be a dangling link in half a year and will confuse people. You have a shortcut on GitHub to covert the current address to the bound one: [Y].

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830#-:-N96jQR9-L7HQ3-0O83-:b53qhg7)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96vDL-A6sy2HrsCzXZ):*
Should be on `process exit`
___
*[`libos/src/bookkeep/libos_handle.c` line 306 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96NW6M1vZk8lZkX2Hr:-N96vPJC-r_UkDwwylgw:b8j5sps) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/bookkeep/libos_handle.c#L306)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Good to know, thanks! Let me take a closer look.
</blockquote></details>

Why do you need this change at all? Please just create another function in this file, like `detach_all_fds` or something and call it in exit.
Btw, we use 1 underscore not 2 (because 2 is reserved by C standard)
___
*[`libos/src/sys/libos_exit.c` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96wnEw4AhjeBfgaF1K:-N96wnEw4AhjeBfgaF1L:bkihugw) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/sys/libos_exit.c#L57)):*
> ```C
>     terminate_ipc_worker();
> 
>     struct libos_handle_map* handle_map = get_thread_handle_map(NULL);
> ```

This shouldn't be here but in related file. This function should not be aware of handle details, it should just call something from different "module"

**Review by kailun-qin — COMMENTED** [review]
Got it and linked to a specific commit, thanks!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830#-:-N97OOn71BktEwAh8frR:b-t04hfj)* status: 0 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96vDL-A6sy2HrsCzXZ):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Should be on `process exit`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 306 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96NW6M1vZk8lZkX2Hr:-N97Of2G5eSahYMC9qgX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/bookkeep/libos_handle.c#L306)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do you need this change at all? Please just create another function in this file, like `detach_all_fds` or something and call it in exit.
Btw, we use 1 underscore not 2 (because 2 is reserved by C standard)
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_exit.c` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96wnEw4AhjeBfgaF1K:-N97P-yz9L1YnX9i9wxf:b-8ezbo2) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/sys/libos_exit.c#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This shouldn't be here but in related file. This function should not be aware of handle details, it should just call something from different "module"
</blockquote></details>

Agree, updated.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/bookkeep/libos_handle.c` line 346 at r3](https://reviewable.io/reviews/gramineproject/gramine/830#-N97QP-sAuFYujZYdtCt:-N97QP-sAuFYujZYdtCu:b-nhjjv2) ([raw file](https://github.com/gramineproject/gramine/blob/8bbd31efa087a883a9184299e7eb9ef0e2bae29b/libos/src/bookkeep/libos_handle.c#L346)):*
> ```C
>                 }
> 
>                 clear_posix_locks(handle);
> ```

Now you run this function under `handle_map->lock`, which previously wasn't the case. Are you sure this is correct?

Update: actually, all posix locks are cleared on exit, this is not needed.
___
*[`libos/src/sys/libos_exit.c` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96wnEw4AhjeBfgaF1K:-N97PjTl1NoWuHBxDjwJ:b-lvj97o) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/sys/libos_exit.c#L57)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Agree, updated.
</blockquote></details>

This should be called in `thread_exit` below, after `int ret = posix_lock_clear_pid(g_process.pid);` and before child exit notification.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/bookkeep/libos_handle.c` line 346 at r3](https://reviewable.io/reviews/gramineproject/gramine/830#-N97QP-sAuFYujZYdtCt:-N97V1wzC_fjDroOOILS:b-2oroin) ([raw file](https://github.com/gramineproject/gramine/blob/8bbd31efa087a883a9184299e7eb9ef0e2bae29b/libos/src/bookkeep/libos_handle.c#L346)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now you run this function under `handle_map->lock`, which previously wasn't the case. Are you sure this is correct?

Update: actually, all posix locks are cleared on exit, this is not needed.
</blockquote></details>

Good catch, thanks for checking, done.
___
*[`libos/src/sys/libos_exit.c` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96wnEw4AhjeBfgaF1K:-N97V4_M4D0RANbItfzU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9efdb354fc5dec02042d5e095d75da602802279/libos/src/sys/libos_exit.c#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This should be called in `thread_exit` below, after `int ret = posix_lock_clear_pid(g_process.pid);` and before child exit notification.
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/bookkeep/libos_handle.c` line 294 at r5](https://reviewable.io/reviews/gramineproject/gramine/830#-N97X8B55hcRANeKb37m:-N97X8B55hcRANeKb37n:b-w6jtxd) ([raw file](https://github.com/gramineproject/gramine/blob/80f186402bd8aeb3b00e6dd9b62d8bec4ec24cad/libos/src/bookkeep/libos_handle.c#L294)):*
> ```C
> }
> 
> static void clear_posix_locks(struct libos_handle* handle) {
> ```

This change doesn't seem needed now, can be restored.
___
*[`libos/src/bookkeep/libos_handle.c` line 333 at r5](https://reviewable.io/reviews/gramineproject/gramine/830#-N97WzoLDTb0XtQ_Q1np:-N97WdrA3R0xAZ0O0qEw:b-t1krwd) ([raw file](https://github.com/gramineproject/gramine/blob/80f186402bd8aeb3b00e6dd9b62d8bec4ec24cad/libos/src/bookkeep/libos_handle.c#L333)):*
> ```C
>     struct libos_handle_map* handle_map = get_thread_handle_map(NULL);
>     assert(handle_map);
>     lock(&handle_map->lock);
> ```

You can use `walk_handle_map`, no need for duplicating this code.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 2 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/bookkeep/libos_handle.c` line 294 at r5](https://reviewable.io/reviews/gramineproject/gramine/830#-N97X8B55hcRANeKb37m:-N97k3BoENtZaOkBv1Ek:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/80f186402bd8aeb3b00e6dd9b62d8bec4ec24cad/libos/src/bookkeep/libos_handle.c#L294)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This change doesn't seem needed now, can be restored.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 333 at r5](https://reviewable.io/reviews/gramineproject/gramine/830#-N97WzoLDTb0XtQ_Q1np:-N97k5X-0ByjP8K2RA68:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/80f186402bd8aeb3b00e6dd9b62d8bec4ec24cad/libos/src/bookkeep/libos_handle.c#L333)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can use `walk_handle_map`, no need for duplicating this code.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 669 at r6](https://reviewable.io/reviews/gramineproject/gramine/830#-N97kAFVBOxlch6uG6hJ:-N97kAFVBOxlch6uG6hK:biwntcd) ([raw file](https://github.com/gramineproject/gramine/blob/8705f51e2bc0a875ab97447ad21c1b1c00c60fd9/libos/src/bookkeep/libos_handle.c#L669)):*
> ```C
>     lock(&map->lock);
> 
>     for (uint32_t i = 0; i <= map->fd_top && map->fd_top != FD_NULL; i++) {
> ```

callback may change `map->fd_top` to FD_NULL in some cases, so updated the logic here.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: 2 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/bookkeep/libos_handle.c` line 328 at r6](https://reviewable.io/reviews/gramineproject/gramine/830#-N97scxv64SW6gw1eQbl:-N9CKP5h9rbAzkJG-lNs:b-zh7rhv) ([raw file](https://github.com/gramineproject/gramine/blob/8705f51e2bc0a875ab97447ad21c1b1c00c60fd9/libos/src/bookkeep/libos_handle.c#L328)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How can this be NULL?
</blockquote></details>

It's inherited from a previous logic, but indeed, after switching to `walk_handle_map()`, it's not needed. Thanks.
___
*[`libos/src/bookkeep/libos_handle.c` line 669 at r6](https://reviewable.io/reviews/gramineproject/gramine/830#-N97kAFVBOxlch6uG6hJ:-N9CKAub87m0hRqqNCCY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8705f51e2bc0a875ab97447ad21c1b1c00c60fd9/libos/src/bookkeep/libos_handle.c#L669)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please swap the condition  (so it's more like: `is_fd_top_valid && use_fd_top`)
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_exec.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/830#-N9C5QwOC0kb4pCQKXH8:-N9CKF7p5OT5ZXCtRYiT:b6dzfig) ([raw file](https://github.com/gramineproject/gramine/blob/8705f51e2bc0a875ab97447ad21c1b1c00c60fd9/libos/src/sys/libos_exec.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this change? How can this be NULL?
</blockquote></details>

Ah right, after switching to `walk_handle_map()`, it's not needed.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/sys/libos_exec.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/830#-N9C5QwOC0kb4pCQKXH8:-N9CUSOn5NJlzkqVmaty:b-ida7x5) ([raw file](https://github.com/gramineproject/gramine/blob/8705f51e2bc0a875ab97447ad21c1b1c00c60fd9/libos/src/sys/libos_exec.c#L21)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Ah right, after switching to `walk_handle_map()`, it's not needed.
</blockquote></details>

But this was always `walk_handle_map()` :)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r5, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/830#-N9aqPVCDWrHc0NP9SEY:-N9arKL8BKs3XCsD5hNT:buicdgc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does this PR fix https://github.com/gramineproject/gramine/issues/824 ? It should. Please verify and add `Fixes #824` to the PR description.
</blockquote></details>

Yes, I've verified manually. Updated the PR description.

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/830#-N96vDL-A6sy2HrsCzXZ):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/830)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
