### PR TITLE
[CI] Ubuntu 24.04 and 22.04 part 6/6

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

See #2026 for rationale. This PR concludes the series.

## How to test this PR? 

- CI
- To check if I haven't missed anything from the previous PR, `git fetch && git diff origin/woju/ubuntu-noble-3 origin/woju/noble-stack-5` (should be empty).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2031)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2031)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 29 at r3](https://reviewable.io/reviews/gramineproject/gramine/2031#-O9E9YUuCEoammv-GNOF):*
`enable` (typo)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 8 of 8 files at r2, 15 of 31 files at r5, 8 of 16 files at r6, 1 of 1 files at r7, 14 of 14 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2031)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/2031#-O9IBc3J9EX4PE9U3lZq):*
I think this commit is missing the removal of 20.04 from `check-python-platlib.jenkinsfile`?

**Review by dimakuv — DISMISSED** [review]
> Reviewed 8 of 16 files at r6, 1 of 1 files at r7, 14 of 14 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2031)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2031)* status: 18 of 36 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 29 at r3](https://reviewable.io/reviews/gramineproject/gramine/2031#-O9E9YUuCEoammv-GNOF):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`enable` (typo)
</blockquote></details>

Done.
___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/2031#-O9IBc3J9EX4PE9U3lZq):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this commit is missing the removal of 20.04 from `check-python-platlib.jenkinsfile`?
</blockquote></details>

Done. Yes, and also missed removing the dockerfile.

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 18 files at r9, 1 of 1 files at r10, 14 of 14 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2031)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, 8 of 8 files at r2, 8 of 16 files at r6, 3 of 18 files at r9, 1 of 1 files at r10, 14 of 14 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2031)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)

___
*[`-- commits` line 11 at r11](https://reviewable.io/reviews/gramineproject/gramine/2031#-O9JXYAr8cCqsde_aWnw):*
-> answers



_Code quote:_
```
anwers
```

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 35 files at r12, 11 of 19 files at r13, 1 of 1 files at r14, 14 of 14 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2031)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow and @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 35 files at r12, 11 of 19 files at r13, 1 of 1 files at r17, 14 of 14 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2031)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
