### PR TITLE
[PAL/Linux-SGX] Remove unused `dummy_debug_variable`

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

No idea why it was used and who introduced it. Git history ends in our infamous "First commit".

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1954)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1954)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1954)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by oshogbo** [comment]
Jenkins, test this please

**Review by oshogbo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1954#-:-O2sAxDB8SCB4PK89ma2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1954)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1954)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
