### PR TITLE
Retire Dmitrii Kuvaiskii from active maintainers

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

See commit message.

This PR should be merged at or around Friday, when Dmitrii's maintainership ends, WRT decision #2043 (proposed by Dmitrii himself).

The commit dates were doctored to 01.11.2024 00:00 UTC, please don't break that accidentally.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2046)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2046)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2046#-OAJ9OjS3-HzIptvnNkD):*
Thanks! It was an honor to work with all of you; I've learnt a lot and I had a lot of fun :)

As for the commit body message -- not blocking, but I would skip this.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2046)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2046#-OAJ9OjS3-HzIptvnNkD):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks! It was an honor to work with all of you; I've learnt a lot and I had a lot of fun :)

As for the commit body message -- not blocking, but I would skip this.
</blockquote></details>

I wish I could block this PR for as long as possible :)

It was an honor to work with you and you'll definitely be missed (with or without the commit message). Take care and all the best!

**Review by monavij — COMMENTED** [review]
Thanks for your contributions Dmitrii. You will be missed.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2046#-:-OAUmxwh159WDSZ4KONr:b-6mzhl8)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2046)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2046#-OAJ9OjS3-HzIptvnNkD):*
Thanks for all the work!

> As for the commit body message -- not blocking, but I would skip this.

@woju: Your call, but if Dmitrii prefers to skip that, then I would skip.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2046)* status: all files reviewed, 2 unresolved discussions (waiting on @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2046#-OAe34VRC_GQPeJjH8RP):*




_Suggestion:_
```
[Docs] Retire Dmitrii Kuvaiskii from active maintainers
```

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2046)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2046#-OAe34VRC_GQPeJjH8RP):*
Done.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2046#-OAJ9OjS3-HzIptvnNkD):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Thanks for all the work!

> As for the commit body message -- not blocking, but I would skip this.

@woju: Your call, but if Dmitrii prefers to skip that, then I would skip.
</blockquote></details>

I won't skip it. We shall not reduce Dima's memory to a line in `.mailcap`, and I think git log is a decent place to remember him.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2046)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2046)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-22.04-Sanitizers please (TCS limit exceeded in `rlimit_nofile`, happens from time to time, unrelated to the PR)

**Pull request merged**
