### PR TITLE
More ASan  fixes

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

Some small issues found while running ASan for SGX.

## How to test this PR? 

Jenkins should be enough.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/34#-MjVE4Fl5VAAnf_E7kQG:-MjVE4Fm7gw9kyobD63f:b-x5xft7) (no related file):*
Jenkins failed on "Jenkins-Direct-Sanitizers" in a previously not seen way.

---

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/34#-MjVE4Fl5VAAnf_E7kQG:-MjYv6Am3OvwFJtSp3fa:b-3gi1nk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Jenkins failed on "Jenkins-Direct-Sanitizers" in a previously not seen way.
</blockquote></details>

This is a problem described in gramineproject/graphene#1248 (cannot unlink a file without read permissions); it's not caused by this PR, but appeared because I unskipped a new LTP test. 

I'm attempting to fix it in #39.

---

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/34#-MjVE4Fl5VAAnf_E7kQG:-MjZMN1J8bzaSqrJeGmn:b-rbj9g3) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is a problem described in gramineproject/graphene#1248 (cannot unlink a file without read permissions); it's not caused by this PR, but appeared because I unskipped a new LTP test. 

I'm attempting to fix it in #39.
</blockquote></details>

Then let's make this PR blocked on #39 

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/34#-MjVE4Fl5VAAnf_E7kQG:-Mj_DdGq-IVaKRvaLxIP:bjf3pvj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Then let's make this PR blocked on #39 
</blockquote></details>

Should work now.

---

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
