### PR TITLE
Remove support for OOT (out-of-tree) SGX driver

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

See commit message.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 49 of 49 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`debian/control` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBjvjaVClASalEolFdy:-OBjvjaVClASalEolFdz:b-ujvhtz) ([raw file](https://github.com/gramineproject/gramine/blob/72b5631684928b7cfd0e62bc74bdb76179989324/debian/control#L13)):*
> ```
>  libprotobuf-c-dev,
>  libsgx-dcap-quote-verify-dev,
>  linux-libc-dev (>= 5.11) | linux-headers-amd64 (>= 5.11),
> ```

Don't we need linux-headers for `sgx.h`? Where does `sgx.h` come from?
___
*[`pal/src/host/linux-sgx/host_framework.c` line 551 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBkcJKj4u-pXVcqHCmS:-OBkcJKj4u-pXVcqHCmT:bk2btvu) ([raw file](https://github.com/gramineproject/gramine/blob/72b5631684928b7cfd0e62bc74bdb76179989324/pal/src/host/linux-sgx/host_framework.c#L551)):*
> ```C
> int init_enclave(sgx_arch_secs_t* secs, sgx_sigstruct_t* sigstruct, sgx_arch_token_t* token) {
> #ifndef CONFIG_SGX_DRIVER_OOT
>     __UNUSED(token);
> ```

Now we can just remove this argument.
___
*[`pal/src/host/linux-sgx/host_main.c` line 224 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBkbgxr10mz3RWIPO8H:-OBkbgxr10mz3RWIPO8I:b-7flyi1) ([raw file](https://github.com/gramineproject/gramine/blob/72b5631684928b7cfd0e62bc74bdb76179989324/pal/src/host/linux-sgx/host_main.c#L224)):*
> ```C
>     log_debug("Token file: %s", token_path);
> 
>     ret = read_enclave_token(token_fd, enclave_token);
> ```

`read_enclave_token()` is unused now

**Review by efu39 — COMMENTED** [review]
> Reviewed 49 of 49 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`pal/src/host/linux-sgx/host_main.c` line 204 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBl6GS6ERdN8j3-LG45:-OBl6GS6ERdN8j3-LG46:bbfjrzn) ([raw file](https://github.com/gramineproject/gramine/blob/1b342d3f3a23d43acc05cf37e46a82bb1ccd650e/pal/src/host/linux-sgx/host_main.c#L204)):*
> ```C
> static int get_enclave_token(sgx_arch_token_t* enclave_token, sgx_sigstruct_t* enclave_sigstruct) {
>     return create_dummy_enclave_token(enclave_sigstruct, enclave_token);
> }
> ```

Since the `get_enclave_token` function is only creating a dummy token, wondering if the function and the code related to the generated dummy token can all be removed. 



_Code quote:_
```C
static int get_enclave_token(sgx_arch_token_t* enclave_token, sgx_sigstruct_t* enclave_sigstruct) {
    return create_dummy_enclave_token(enclave_sigstruct, enclave_token);
}
```
___
*[`pal/src/host/linux-sgx/host_main.c` line 274 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBlAhJT6Q5vTQFMTmYh:-OBlAhJT6Q5vTQFMTmYi:b-1gd12v) ([raw file](https://github.com/gramineproject/gramine/blob/1b342d3f3a23d43acc05cf37e46a82bb1ccd650e/pal/src/host/linux-sgx/host_main.c#L274)):*
> ```C
>         log_error("Reading enclave token failed: %s", unix_strerror(ret));
>         goto out;
>     }
> ```

The error message should be updated (or removed?), the function is no longer reading token file. Also `create_dummy_enclave_token()` never returns ret < 0



_Code quote:_
```C
    ret = get_enclave_token(&enclave_token, &enclave_sigstruct);
    if (ret < 0) {
        log_error("Reading enclave token failed: %s", unix_strerror(ret));
        goto out;
    }
```
___
*[`pal/src/host/linux-sgx/host_main.c` line 278 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBl8Yyk4AdtWhyU1vlW:-OBl8Yyk4AdtWhyU1vlX:b3l7rhc) ([raw file](https://github.com/gramineproject/gramine/blob/1b342d3f3a23d43acc05cf37e46a82bb1ccd650e/pal/src/host/linux-sgx/host_main.c#L278)):*
> ```C
> #ifdef DEBUG
>     if (enclave->profile_enable) {
>         if (!(enclave_token.body.attributes.flags & SGX_FLAGS_DEBUG)) {
> ```

Maybe consider checking`enclave_sigstruct.body` instead since the dummy token value was derived from it?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: 47 of 51 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @efu39 and @mkow)

___
*[`debian/control` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBjvjaVClASalEolFdy:-OBym66D1kFisi5OCfjj:blnp5vh) ([raw file](https://github.com/gramineproject/gramine/blob/72b5631684928b7cfd0e62bc74bdb76179989324/debian/control#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Don't we need linux-headers for `sgx.h`? Where does `sgx.h` come from?
</blockquote></details>

`/usr/include/x86_64-linux-gnu/asm/sgx.h` comes from `linux-libc-dev` (the one that gets included by `#include <asm/sgx.h>` without `-I` to gcc's commandline) . linux-headers (particularly `linux-headers-$(uname -r)-common` package) also contains `sgx.h`, and you can set up `-I` so that it also works as `<asm/sgx.h>`, however it's not technically meant to be used like that, because `linux-headers` is meant for compiling kernel modules, not normal software, and you include it as `#include <uapi/asm/sgx.h>` (the other one, `#include <asm/sgx.h>`, is not the one that you want).

The problem is (was), for each distro release there's only one `linux-libc-dev` matching the stable kernel version that does not get updated during the lifetime of a particular release (for 2 years it only gets backports) and on focal (Ubuntu 20.04) it was 5.4.0. So even if you installed newer kernel, you still got `linux-libc-dev` 5.4-something, so you can't `#include <asm/sgx.h>`. So we had that machinery to make up for it and steal `sgx.h` from `linux-headers`. Now that all supported distros run their base kernel >= 5.11, we can just remove it all.

Technically you should have reworked `meson.build` in the PR that removed 20.04 to always use `/usr/include` for `upstream` (and then change this dependency here), but since I knew we were going to make bigger change to `meson.build` and `#ifdef`s in that area when removing OOT, I didn't bother mentioning it then.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 551 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBkcJKj4u-pXVcqHCmS:-OByz5iY5HxCd9tge9Ut:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72b5631684928b7cfd0e62bc74bdb76179989324/pal/src/host/linux-sgx/host_framework.c#L551)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now we can just remove this argument.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 204 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBl6GS6ERdN8j3-LG45:-OByz9tlAwlbFIO6ncep:btv3p5c) ([raw file](https://github.com/gramineproject/gramine/blob/1b342d3f3a23d43acc05cf37e46a82bb1ccd650e/pal/src/host/linux-sgx/host_main.c#L204)):*
<details><summary><i>Previously, efu39 (Erica Fu) wrote…</i></summary><blockquote>

Since the `get_enclave_token` function is only creating a dummy token, wondering if the function and the code related to the generated dummy token can all be removed.
</blockquote></details>

Done. Yes, `create_dummy_enclave_token` we can remove, but I don't know anything about `get_optional_sgx_features`, so I'll leave it, unless you're sure it's unneeded?
___
*[`pal/src/host/linux-sgx/host_main.c` line 224 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBkbgxr10mz3RWIPO8H:-OByz6cD32mdZj_nAmzG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72b5631684928b7cfd0e62bc74bdb76179989324/pal/src/host/linux-sgx/host_main.c#L224)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`read_enclave_token()` is unused now
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 274 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBlAhJT6Q5vTQFMTmYh:-OByzSwg2KsEIswAOKpR:b1moqal) ([raw file](https://github.com/gramineproject/gramine/blob/1b342d3f3a23d43acc05cf37e46a82bb1ccd650e/pal/src/host/linux-sgx/host_main.c#L274)):*
<details><summary><i>Previously, efu39 (Erica Fu) wrote…</i></summary><blockquote>

The error message should be updated (or removed?), the function is no longer reading token file. Also `create_dummy_enclave_token()` never returns ret < 0
</blockquote></details>

Done. All true, I removed it, and I took liberty to make `get_optional_sgx_features` `void` when refactoring.
___
*[`pal/src/host/linux-sgx/host_main.c` line 278 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBl8Yyk4AdtWhyU1vlW:-OByzXJKExjDWT8NVtJA:bgp9cfp) ([raw file](https://github.com/gramineproject/gramine/blob/1b342d3f3a23d43acc05cf37e46a82bb1ccd650e/pal/src/host/linux-sgx/host_main.c#L278)):*
<details><summary><i>Previously, efu39 (Erica Fu) wrote…</i></summary><blockquote>

Maybe consider checking`enclave_sigstruct.body` instead since the dummy token value was derived from it?
</blockquote></details>

`enclave_sigstruct` does not have `.body`, but yes, we should read from SIGSTRUCT.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @efu39 and @woju)

___
*[`debian/control` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBjvjaVClASalEolFdy:-OBzjSKj9iCyZqybP--5:b-lg05om) ([raw file](https://github.com/gramineproject/gramine/blob/72b5631684928b7cfd0e62bc74bdb76179989324/debian/control#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`/usr/include/x86_64-linux-gnu/asm/sgx.h` comes from `linux-libc-dev` (the one that gets included by `#include <asm/sgx.h>` without `-I` to gcc's commandline) . linux-headers (particularly `linux-headers-$(uname -r)-common` package) also contains `sgx.h`, and you can set up `-I` so that it also works as `<asm/sgx.h>`, however it's not technically meant to be used like that, because `linux-headers` is meant for compiling kernel modules, not normal software, and you include it as `#include <uapi/asm/sgx.h>` (the other one, `#include <asm/sgx.h>`, is not the one that you want).

The problem is (was), for each distro release there's only one `linux-libc-dev` matching the stable kernel version that does not get updated during the lifetime of a particular release (for 2 years it only gets backports) and on focal (Ubuntu 20.04) it was 5.4.0. So even if you installed newer kernel, you still got `linux-libc-dev` 5.4-something, so you can't `#include <asm/sgx.h>`. So we had that machinery to make up for it and steal `sgx.h` from `linux-headers`. Now that all supported distros run their base kernel >= 5.11, we can just remove it all.

Technically you should have reworked `meson.build` in the PR that removed 20.04 to always use `/usr/include` for `upstream` (and then change this dependency here), but since I knew we were going to make bigger change to `meson.build` and `#ifdef`s in that area when removing OOT, I didn't bother mentioning it then.
</blockquote></details>

I see, thanks for the explanation!
___
*[`pal/src/host/linux-sgx/host_framework.c` line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBzlSs_44zb8gBc4Yyn:-OBzlSsa-7OAcZB7qE9S:b-35i7v7) ([raw file](https://github.com/gramineproject/gramine/blob/e5e19e0f7190fe4adec6aadc9d622b352bd27e7c/pal/src/host/linux-sgx/host_framework.c#L124)):*
> ```C
>     secs->ssa_frame_size = SSA_FRAME_SIZE / g_page_size; /* SECS expects SSA frame size in pages */
>     secs->misc_select = sig->misc_select;
>     memcpy(&secs->attributes, &sig->attributes, sizeof(sgx_attributes_t));
> ```

Now this memcpy doesn't make much sense, you're copying 2 fields and then right afterwards overwrite one of them.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: 50 of 51 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @efu39 and @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBzlSs_44zb8gBc4Yyn:-OC-5Tnt9aGUJ59C8-kO:bt6swfu) ([raw file](https://github.com/gramineproject/gramine/blob/e5e19e0f7190fe4adec6aadc9d622b352bd27e7c/pal/src/host/linux-sgx/host_framework.c#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now this memcpy doesn't make much sense, you're copying 2 fields and then right afterwards overwrite one of them.
</blockquote></details>

I can do it like that, but I'm unconvinced this is cleaner. It starts to rely that no-one will remove `*out_xfrm = ` line in `get_optional_sgx_features`.

I also thought about moving this initialisation to `host_main.c` just before `create_enclave()` invocation, where two secs fields, `base` and `size`, are initialised, because they're copied from `struct pal_enclave`, not passed here. Or even refactoring to a dedicated constructor, probably `create_secs(struct pal_enclave*, sgx_sigstruct_t*)`. I could use a suggestion either way.

**Review by efu39 — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061#-:-OC-alLb-GugM8f-94D1:bg7igkv)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBzlSs_44zb8gBc4Yyn:-OC0fCQV77w-GkRoEsIC:b-5kkyks) ([raw file](https://github.com/gramineproject/gramine/blob/e5e19e0f7190fe4adec6aadc9d622b352bd27e7c/pal/src/host/linux-sgx/host_framework.c#L124)):*
> It starts to rely that no-one will remove `*out_xfrm =` line in `get_optional_sgx_features`.

I don't understand this argument... That's literally what `get_optional_sgx_features()` does - it returns some value via argument (`out_xfrm`). It's like saying "what if someone removes `return sum;` from `sum_some_numbers` function?".

> I also thought about moving this initialisation to `host_main.c` just before `create_enclave()` invocation, where two secs fields, `base` and `size`, are initialised, because they're copied from `struct pal_enclave`, not passed here. Or even refactoring to a dedicated constructor, probably `create_secs(struct pal_enclave*, sgx_sigstruct_t*)`. I could use a suggestion either way.

I like the `create_secs()` idea, but plz not in this PR, it's already large.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBzlSs_44zb8gBc4Yyn:-OC2g7-t-n_Fc97XP79a:bfvikxx) ([raw file](https://github.com/gramineproject/gramine/blob/e5e19e0f7190fe4adec6aadc9d622b352bd27e7c/pal/src/host/linux-sgx/host_framework.c#L124)):*
Well, previous version would work if that line was removed, because `get_optional_sgx_features()` would just light optional bits (and *only* those optional bits) without providing base value (which was provided by memset). Which would also be a correct behaviour, as the documentation (a lack of it) provides no clue which was intended, and the function name is ambiguous.

> plz not in this PR, it's already large.

Sure.

**Comment by woju** [comment]
Jenkins, test Jenkins-Direct-24.04 please (fdatasync01 timed out)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/2061#-OBzlSs_44zb8gBc4Yyn:-OC50lL37JAqpnRn0Tx3:b-8kcklv) ([raw file](https://github.com/gramineproject/gramine/blob/e5e19e0f7190fe4adec6aadc9d622b352bd27e7c/pal/src/host/linux-sgx/host_framework.c#L124)):*
> the function name is ambiguous

But the argument is called `out_xfrm` - that means it's used as a return value which is written but not read by the function (that's how you "return a tuple" in C...).

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 47 of 49 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2061#-OC6W8vl-J2dK3hV7s4S:-OC6W8vm2f_vvj6ZgtE9:beg9ktg) (no related file):*
What about https://github.com/gramineproject/gramine/blob/e1405529111807ba2f3fad8fcb911b1e5d8f38d1/Documentation/devel/packaging.rst#L19-L20 and https://github.com/gramineproject/gramine/blob/e1405529111807ba2f3fad8fcb911b1e5d8f38d1/python/gramine-sgx-sigstruct-view#L52?
___
*[`Documentation/devel/building.rst` line 87 at r3](https://reviewable.io/reviews/gramineproject/gramine/2061#-OC6TPVT6KFQQ_cPRf5f:-OC6TPVT6KFQQ_cPRf5g:bdvw8ud) ([raw file](https://github.com/gramineproject/gramine/blob/3c6048389216f82707c71f38564a465a1569857a/Documentation/devel/building.rst#L87)):*
> ```reStructuredText
> - Install out-of-tree driver and use our provided patches to the Linux kernel
>   version 5.4. See section :ref:`legacy-kernel-and-hardware` for the exact
>   steps.
> ```

What about here?



_Code quote:_
```reStructuredText
- Install out-of-tree driver and use our provided patches to the Linux kernel
  version 5.4. See section :ref:`legacy-kernel-and-hardware` for the exact
  steps.
```
___
*[`Documentation/devel/building.rst` line 154 at r3](https://reviewable.io/reviews/gramineproject/gramine/2061#-OC6Rfdb47WnHYrKEiBW:-OC6Rfdb47WnHYrKEiBX:bfmkyk0) ([raw file](https://github.com/gramineproject/gramine/blob/3c6048389216f82707c71f38564a465a1569857a/Documentation/devel/building.rst#L154)):*
> ```reStructuredText
> built both).
> 
> Since Gramine 1.9, we only support upstream, in-kernel driver and the
> ```

-> v1.9



_Code quote:_
```reStructuredText
1.9
```
___
*[`Documentation/devel/building.rst` line 350 at r3](https://reviewable.io/reviews/gramineproject/gramine/2061#-OC6TGIw2I_9idATBQwq:-OC6TGIw2I_9idATBQwr:bt58xlr) ([raw file](https://github.com/gramineproject/gramine/blob/3c6048389216f82707c71f38564a465a1569857a/Documentation/devel/building.rst#L350)):*
> ```reStructuredText
> Although we recommend kernel version 5.11 or later, Gramine can be run on older
> kernels with out-of-tree SGX driver. OOT driver is also the only possibility to
> run Gramine on non-FLC hardware. In this configuration, we require kernel at
> ```

What about here and all related places below?



_Code quote:_
```reStructuredText
Although we recommend kernel version 5.11 or later, Gramine can be run on older
kernels with out-of-tree SGX driver. OOT driver is also the only possibility to
run Gramine on non-FLC hardware. In this configuration, we require kernel at
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 40 at r3](https://reviewable.io/reviews/gramineproject/gramine/2061#-OC6YnoY9PSw43EtQUlM:-OC6YnoY9PSw43EtQUlN:b-hutv3p) ([raw file](https://github.com/gramineproject/gramine/blob/3c6048389216f82707c71f38564a465a1569857a/pal/src/host/linux-sgx/host_framework.c#L40)):*
> ```C
> 
> static void get_optional_sgx_features(uint64_t xfrm, uint64_t xfrm_mask, uint64_t* out_xfrm) {
>     /* see also sgx_get_token.py:get_optional_sgx_features(), used for legacy non-FLC machines */
> ```

We don't really have this file now?



_Code quote:_
```C
sgx_get_token.py
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 40 at r3](https://reviewable.io/reviews/gramineproject/gramine/2061#-OC6Z3CH8Xr0AaO-gMzY:-OC6Z3CH8Xr0AaO-gMzZ:b-p29vvu) ([raw file](https://github.com/gramineproject/gramine/blob/3c6048389216f82707c71f38564a465a1569857a/pal/src/host/linux-sgx/host_framework.c#L40)):*
> ```C
> 
> static void get_optional_sgx_features(uint64_t xfrm, uint64_t xfrm_mask, uint64_t* out_xfrm) {
>     /* see also sgx_get_token.py:get_optional_sgx_features(), used for legacy non-FLC machines */
> ```

But it's said that "OOT driver is also the only possibility to run Gramine on non-FLC hardware"?



_Code quote:_
```C
used for legacy non-FLC machines
```

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2061)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`Documentation/devel/building.rst` line 360 at r1](https://reviewable.io/reviews/gramineproject/gramine/2061#-OCJ_GKy5HcCB89iXM7r:-OCJ_GKzBaOY3NdUxaJi:b9duj5s) ([raw file](https://github.com/gramineproject/gramine/blob/1b342d3f3a23d43acc05cf37e46a82bb1ccd650e/Documentation/devel/building.rst#L360)):*
> ```reStructuredText
> check kernel's ``.config`` and consult your distro documentation.
> 
> 1. Install Linux kernel with patched FSGSBASE
> ```

Finally gone!

**Pull request merged**
