### PR TITLE
[Docs] Update "Gramine features"

### LINKED ISSUE #1295: Add new changes to "Gramine features" before v1.5 release
### Description of the feature

This document: https://gramine.readthedocs.io/en/latest/devel/features.html

It must be updated with the following changes that we had in Gramine. Ideally, we should update that document before release v1.5, so that the `stable` documentation shows the correct info for v1.5.

- [x] Dummy support for ancillary data in `sendmsg`/`recvmsg`. See https://github.com/gramineproject/gramine/pull/1210.
- [x] SGX-specific keys are under `/dev/attestation/keys/`. See https://github.com/gramineproject/gramine/pull/1249
- [x] Pseudo-files (`/dev`, `/proc`, `/sys`) cannot be removed. See https://github.com/gramineproject/gramine/pull/1266
- [x] Added dummy support for `setsid`/`getsid`. See https://github.com/gramineproject/gramine/pull/1264
- [x] Added `sys.disallow_subprocesses` manifest option.
- [x] Added flexible socket- and device-specific IOCTL support.
- [x] Added `flock`.
- [x] Gramine now treats (e)poll error ((E)POLLERR) and hang-up ((E)POLLHUP/(E)POLLRDHUP) events separately
- [x] Remove all "removed deprecated" manifest options and pseudo-files.

### Why Gramine should implement it?

For up-to-date documentation.

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Added descriptions for flock, dummy support for ancillary data in networking, poll/epoll improvements, flexible IOCTLs, session management, `/dev/attestation/keys/_sgx_*` files.

Fixes #1295.

## How to test this PR? 

I temporarily enabled rendering for this PR here: https://gramine.readthedocs.io/en/dimakuv-update-gramine-features-doc-june-2023/devel/features.html

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/devel/features.md` line 2417 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6YzKZC6-1R94Io-Yy:-NZ6YzKZC6-1R94Io-Yz:bv2r7ou) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L2417)):*
> ```Markdown
> - no support for auto binding in the `listen()` system call;
> - dummy support for ancillary data (aka control messages): received messages always indicate there
>   is no ancillary data attached to them.
> ```

Should we update here: https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/Documentation/devel/features.md#L2515-L2517 as well?
___
*[`Documentation/devel/features.md` line 2778 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6Z4lH9cleu03Bd2H9:-NZ6Z4lH9cleu03Bd2HA:bcj68kk) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L2778)):*
> ```Markdown
> `sys.allowed_ioctls` manifest options](../manifest-syntax.html#allowed-ioctls). Read the
> documentation to learn how to use this feature. There is also a corresponding
> [whitepaper](https://arxiv.org/abs/2203.01813). Note that arbitrary IOCTLs specified in the manifest
> ```

whitepaper for xxx (e.g., communication with hardware accelerators)



_Code quote:_
```Markdown
[whitepaper](https://arxiv.org/abs/2203.01813)
```

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/devel/features.md` line 383 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6d88e4AqZnnCWqmtH:-NZ6d88e4AqZnnCWqmtI:bjmgykr) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L383)):*
> ```Markdown
>   <sup>[23](#misc)</sup>
> 
> - ▣ `flock()`
> ```

Blocked on #1416.
___
*[`Documentation/devel/features.md` line 2244 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6fdzAAdeJTzB50KY7:-NZ6fdzAAdeJTzB50KY8:b5l5wqy) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L2244)):*
> ```Markdown
> termination would be incorrect. Gramine currently errs on the side of caution and does *not* release
> a file lock if the process has children; this may leak resources or deadlock but doesn't introduce
> unsafe behavior.
> ```

May need to be updated, depends on what we decide to do in the flock PR.
___
*[`Documentation/devel/features.md` line 3014 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6gfAx5xEfs4QJRsAM:-NZ6gbO-C5I3qrcmvfn6:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L3014)):*
> ```Markdown
> the calling process the leader of the new session, which is enough for many workloads (e.g. JVM).
> However, there are serious limitations:
> - in `getsid()`, not possible to get session id of other processes (only of this process),
> ```





_Suggestion:_
```Markdown
in `getsid()`, it's not possible to get session
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/devel/features.md` line 2417 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6YzKZC6-1R94Io-Yy:-NZ6z2z51x_uSaW8c0y4:b-gb8692) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L2417)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we update here: https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/Documentation/devel/features.md#L2515-L2517 as well?
</blockquote></details>

But I think that paragraph is correct. We don't support ancillary data, we just make sure we "report no ancillary data" in network packets.

Or, if you insist, I could replace with `always ignore ancillary data`.
___
*[`Documentation/devel/features.md` line 2778 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6Z4lH9cleu03Bd2H9:-NZ6zcIH02lPTXDeXC-p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L2778)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

whitepaper for xxx (e.g., communication with hardware accelerators)
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 3014 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6gfAx5xEfs4QJRsAM:-NZ6zkXF7wUg3YUrOfvP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L3014)):*
> ```Markdown
> the calling process the leader of the new session, which is enough for many workloads (e.g. JVM).
> However, there are serious limitations:
> - in `getsid()`, not possible to get session id of other processes (only of this process),
> ```

Done.

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/devel/features.md` line 2417 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6YzKZC6-1R94Io-Yy:-NZ97YDX5_oP3SGXI7_j:b-k6thc6) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L2417)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But I think that paragraph is correct. We don't support ancillary data, we just make sure we "report no ancillary data" in network packets.

Or, if you insist, I could replace with `always ignore ancillary data`.
</blockquote></details>

OK, fair enough. I don't insist. Thanks!
___
*[`Documentation/devel/features.md` line 2240 at r3](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ97l2H31Z8zPKIPpiZ:-NZ97l2H31Z8zPKIPpi_:bor98dd) ([raw file](https://github.com/gramineproject/gramine/blob/cb27b0c889a42be2464e847504f1dd07eee2562c/Documentation/devel/features.md#L2240)):*
> ```Markdown
> 
> BSD (flock) locks are currently experimental and are *disabled* by default. To enable them, use
> ``sys.experimental__enable_flock`` manifest option. There is at least one problem with BSD locks
> ```

add a link to the manifest option (as the others do)



_Code quote:_
```Markdown
manifest option
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/devel/features.md` line 2244 at r1](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ6fdzAAdeJTzB50KY7:-NZ9xCyV8oB3s-LFzsQO:by2ssss) ([raw file](https://github.com/gramineproject/gramine/blob/0474a1644479b084e4cf3d0662879c3f4d05bad1/Documentation/devel/features.md#L2244)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

May need to be updated, depends on what we decide to do in the flock PR.
</blockquote></details>

I updated to what the current status of flock is.
___
*[`Documentation/devel/features.md` line 2240 at r3](https://reviewable.io/reviews/gramineproject/gramine/1429#-NZ97l2H31Z8zPKIPpiZ:-NZ9xBb0-UF31DzO4Ll7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cb27b0c889a42be2464e847504f1dd07eee2562c/Documentation/devel/features.md#L2240)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

add a link to the manifest option (as the others do)
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1429)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
