### PR TITLE
[LibOS] Raise SIGALRM when setitimer's real time timer expires

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

Raise SIGALRM when setitimer's real time timer expires and setitimer() serves as an alarm() replacement.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/888)

### CODE REVIEW

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/888)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`libos/src/sys/libos_alarm.c` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/888#-NBJgZKADWkOiiaXuqv_:-NBJgZKADWkOiiaXuqva:b-74etdw) ([raw file](https://github.com/gramineproject/gramine/blob/f4f575054f5a89492344bc6563a2e52aaa78ccc7/libos/src/sys/libos_alarm.c#L15)):*
> ```C
> #include "libos_signal.h"
> #include "libos_table.h"
> #include "libos_utils.h"
> ```

This code deserves a proper cleanup, but I guess this could be the first step...

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/888)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @stefanberger)

___
*[`libos/src/sys/libos_alarm.c` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/888#-NBLsInaAQ3mc9Z7KQXX:-NBLsInaAQ3mc9Z7KQXY:b-21wbji) ([raw file](https://github.com/gramineproject/gramine/blob/f4f575054f5a89492344bc6563a2e52aaa78ccc7/libos/src/sys/libos_alarm.c#L57)):*
> ```C
> static spinlock_t g_real_itimer_lock = INIT_SPINLOCK_UNLOCKED;
> 
> static void signal_itimer(IDTYPE target, void* arg) {
> ```

`target` -> `caller` (so that we have uniformity in naming with `signal_alarm()`)
___
*[`libos/src/sys/libos_alarm.c` line 72 at r1](https://reviewable.io/reviews/gramineproject/gramine/888#-NBLsNZB1dYBL9OzXiYV:-NBLsNZB1dYBL9OzXiYW:b-99jbs9) ([raw file](https://github.com/gramineproject/gramine/blob/f4f575054f5a89492344bc6563a2e52aaa78ccc7/libos/src/sys/libos_alarm.c#L72)):*
> ```C
>     spinlock_unlock(&g_real_itimer_lock);
> 
>     signal_current_proc(SIGALRM);
> ```

So the itimer simply never raised an alarm? Nice emulation we had...

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/888)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @stefanberger)

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/888)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/sys/libos_alarm.c` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/888#-NBLsInaAQ3mc9Z7KQXX:-NBMQYRW29mPtrxsIT9h:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f4f575054f5a89492344bc6563a2e52aaa78ccc7/libos/src/sys/libos_alarm.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`target` -> `caller` (so that we have uniformity in naming with `signal_alarm()`)
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/888)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_alarm.c` line 72 at r1](https://reviewable.io/reviews/gramineproject/gramine/888#-NBLsNZB1dYBL9OzXiYV:-NBMiSiw3k7YCgDmbpOK:b-wz7qca) ([raw file](https://github.com/gramineproject/gramine/blob/f4f575054f5a89492344bc6563a2e52aaa78ccc7/libos/src/sys/libos_alarm.c#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So the itimer simply never raised an alarm? Nice emulation we had...
</blockquote></details>

Yes, nobody really uses this, I guess.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/888)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/888)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/888)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
