### PR TITLE
Release 1.7

### PR DESCRIPTION
**Pull request by woju**
Release checklist: #1847

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1848)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1848)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`debian/changelog` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1848#-NvkzKNt8fBv_Ufb18k2:-NvkzKNt8fBv_Ufb18k3:b-5dhubt) ([raw file](https://github.com/gramineproject/gramine/blob/0d5fd8c50baee6419842bf7d9e2357fa2e66904b/debian/changelog#L5)):*
> ```
>   * version 1.7
>   * added support for secure eventfd
>   * added support for assortment of file-level operations on encrypted files
> ```

I see no reason to have this `file-level` adjective -- all operations are file-level operations...
___
*[`debian/changelog` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1848#-Nvkz6jp-0CwSENxI4hv:-Nvkz6jq-Gvl7USD6umC:bg8lkng) ([raw file](https://github.com/gramineproject/gramine/blob/0d5fd8c50baee6419842bf7d9e2357fa2e66904b/debian/changelog#L10)):*
> ```
>      * truncate() to arbitrary length
>      * stat() on directories
>      * chmod() on directories
> ```

Please remove the last two items (`stat` and `chmod`) -- these were fixes to the regressions I introduced (during `unlink()` on corrupted files)

**Review by woju — COMMENTED** [review]
No, it's the correct one: I speculatively merged `gramine-manifest-check`, because there already is the decision that we will merge it, and I didn't want to send packages without it to QA, because it adds breaking change: the check is enabled on `gramine-sgx-sign` by default, so if anyone has a manifest with syntax problems, signing will fail.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1848#-:-NvqHNEZ6JloPomey1f9:bqu6rfg)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`debian/changelog` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1848#-NvkzKNt8fBv_Ufb18k2:-NvqI67R7wX_ljckiTFX:bni5dgh) ([raw file](https://github.com/gramineproject/gramine/blob/0d5fd8c50baee6419842bf7d9e2357fa2e66904b/debian/changelog#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see no reason to have this `file-level` adjective -- all operations are file-level operations...
</blockquote></details>

Done, but not pushed, will push with `~rc2` or final. Feel free to keep blocked unitl I push.
___
*[`debian/changelog` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1848#-Nvkz6jp-0CwSENxI4hv:-NvqIFGK4hNehNcjvkO2:b-nb1fog) ([raw file](https://github.com/gramineproject/gramine/blob/0d5fd8c50baee6419842bf7d9e2357fa2e66904b/debian/changelog#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the last two items (`stat` and `chmod`) -- these were fixes to the regressions I introduced (during `unlink()` on corrupted files)
</blockquote></details>

Done, but not pushed, will push with `~rc2` or final.

**Review by llly — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1848)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1848)* status: 0 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @llly)

___
*[`debian/changelog` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1848#-NvkzKNt8fBv_Ufb18k2:-NwAq0O-2RRyNTyGS2Gb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0d5fd8c50baee6419842bf7d9e2357fa2e66904b/debian/changelog#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done, but not pushed, will push with `~rc2` or final. Feel free to keep blocked unitl I push.
</blockquote></details>

Done.
___
*[`debian/changelog` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1848#-Nvkz6jp-0CwSENxI4hv:-NwAq0pdBs-IVxu2C1kp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0d5fd8c50baee6419842bf7d9e2357fa2e66904b/debian/changelog#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done, but not pushed, will push with `~rc2` or final.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1848)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1848)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1848)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
