### PR TITLE
Drop hacks and workarounds for Ubuntu 18.04

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

For now only the simpler ones, more complicated ones will go into separate PRs.

## How to test this PR? 

Check if it still works on all supported platforms.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1373)

### CODE REVIEW

**Review by kailun-qin — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1373)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWNVgCDEm6ReOnaEu3M):*
not blocking, but I would add a "partial" before "hacks and workarounds"

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1373)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWNZAlj4SwFNmljOMYq:-NWNYP8W6g87SNGa3U1H:b4q2o4k) (no related file):*
> For now only the simpler ones, more complicated ones will go into separate PRs.

How do we define "simpler" and "more complicated"? How do we know this PR is complete for all "simpler" ones? Do we have a plan for the coming PRs?

___

**Review by kailun-qin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1373)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWNZAlj4SwFNmljOMYq:-NWQS5_07blawTjhFVhW:b-9nxole) (no related file):*
> Do we have to define this anyhow? It's mostly my loose judgement to which I didn't pay much attention, because I think it doesn't matter. I just picked the ones which seem trivial and can be grouped into a single commit.

No, we don't. Thanks for the explanation! I'm fine w/ it, would just like to understand a bit more about the logic (so I can double check if we miss anything). :)

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWNVgCDEm6ReOnaEu3M):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Something like this? Couldn't make "partial" to work grammatically with the rest of the sentence.
</blockquote></details>

sure, looks good, thx!

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1373)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWNZAlj4SwFNmljOMYq:-NWRbgf12nGmbE0fmMe2:bgb3f2e) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Do we have to define this anyhow? It's mostly my loose judgement to which I didn't pay much attention, because I think it doesn't matter. I just picked the ones which seem trivial and can be grouped into a single commit.

No, we don't. Thanks for the explanation! I'm fine w/ it, would just like to understand a bit more about the logic (so I can double check if we miss anything). :)


</blockquote></details>

Ah, now I understand your question :) Please just check if I didn't miss anything related to the changes included here - e.g. whether I missed another instance of something fixed here.
We'll do a bigger search through the codebase after all the obvious places are fixed.

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1373)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWfNIvy4xXWAbbVay9v:-NWfNIvy4xXWAbbVay9w:byauci) (no related file):*
I checked it on two of my machines:
1. Local development machine with Ubuntu 20.04
2. MS Azure VM with Ubuntu 20.04

Both work fine.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWfNSMe1O4dYjflz18T:-NWfNSMe1O4dYjflz18U:bfekucm) (no related file):*
@anjalirai-intel @jinengandhi-intel Could you test this PR on different OS distros? It should fail on Ubuntu 18.04 and succeed on Ubuntu 20.04, Ubuntu 22.04, Debian 11, and these kinds of recent OSes.

But I'm also curious whether this PR still works on RHEL/CentOS type of systems. Could you provide such a table, what works and what fails? Thanks in advance!

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWNVgCDEm6ReOnaEu3M):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

sure, looks good, thx!
</blockquote></details>

+1 to the proposed change.

**Review by jinengandhi-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1373)* status: all files reviewed, 2 unresolved discussions (waiting on @anjalirai-intel and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWfNSMe1O4dYjflz18T:-NWmHCNk1mCtalYcZU3w:b-sy9jou) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@anjalirai-intel @jinengandhi-intel Could you test this PR on different OS distros? It should fail on Ubuntu 18.04 and succeed on Ubuntu 20.04, Ubuntu 22.04, Debian 11, and these kinds of recent OSes.

But I'm also curious whether this PR still works on RHEL/CentOS type of systems. Could you provide such a table, what works and what fails? Thanks in advance!
</blockquote></details>

We ran the nightly and no regression seen.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1373)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1373#-NWfNSMe1O4dYjflz18T:-NWpkG_784H9QzF1R6L7:bgoes7c) (no related file):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

We ran the nightly and no regression seen.
</blockquote></details>

Thanks, then I'm resolving this comment. This PR is ready for merge, I'll prepare it now.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1373)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
