### PR TITLE
Rename Graphene to Gramine

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Absolutely all file names and mentions (apart from the links to the old Graphene repo for open issues) are changed from Graphene to Gramine.

The name "Graphene" was deemed too common, could be impossible to trademark, and collided with several other software projects. Thus, a new name "Gramine" was chosen.

~~Must be rebased on top of #3 and #4.~~

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 197 of 382 files at r1, 203 of 203 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/17#-MkDFypI2iYY5qUC-AMt:-MkDFypJ9mWUCxUHKhpw:b-4an6m6) (no related file):*
Thinking more about this, I started to like the backward compatible version of the rename more - we'll need to switch between old and new branches for a while, and if both have different cmdline tools then it will be quite annoying.
Could you create a small wrapper which would print a deprecation warning and then `exec` the right script, and symlink `graphene-` tools to it?

---
___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkCWAuq5s-nzuOHYM87):*
As discussed on the call, could you include a short explanation for rename in both the commit message and the main readme?
___
*[CONTRIBUTING.rst, line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkCwjJa3iYqWyW2L9vo:-MkCwjJa3iYqWyW2L9vp:bczccui) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/CONTRIBUTING.rst#L36)):*
> ```reStructuredText
> contributions, and would hate for anyone to waste time implementing a change
> that will not be accepted for a design flaw. It is much better to reach out for
> advice first by emailing support@gramineproject.io.
> ```

I just tried, this alias doesn't work yet. I think we can use `gramine-users@googlegroups.com` for now.
___
*[CONTRIBUTING.rst, line 39 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkChK-nEvpvqhf2JtNJ:-MkChK-nEvpvqhf2JtNK:b-sxbqy1) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/CONTRIBUTING.rst#L39)):*
> ```reStructuredText
> 
> Or you can see the archives at this google group:
> https://groups.google.com/forum/#!forum/gramine-support
> ```

Should be gramine-users (we'll have a few different "levels" now, but we can write more details about it later).
___
*[README.rst, line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkD9uJ5Bpz4GFNEZL1F:-MkD9uJ6AJ90aBZSSkIc:bdlibwk) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/README.rst#L47)):*
> previously

I think "formerly" is more commonly used in such places? But not blocking.
___
*[Documentation/quickstart.rst, line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkDTGYQ96mr6uKZuE_y:-MkDTGYS5jtyXurZZfXH:b-1pe1gc) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/quickstart.rst#L118)):*
> ```
> Additional applications enabled in Gramine
> ```

I'd rather say something like "sample configurations for" or similar, current version sounds weird.
___
*[Documentation/tutorials/pytorch/index.rst, line 123 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkDZ2bd7LTZ_FT5NppZ:-MkDZ2bd7LTZ_FT5Npp_:b-hjzbvu) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/tutorials/pytorch/index.rst#L123)):*
> ```reStructuredText
> We start with a very simple example script written in Python3 for PyTorch-based
> ML inferencing. Gramine already provides a minimalistic and *insecure* `PyTorch
> example <https://github.com/gramineproject/examples>`__
> ```

this link is now wrong (not specific enough)
___
*[Documentation/tutorials/pytorch/index.rst, line 404 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkE4bysAnPViN27kpvL:-MkE4bysAnPViN27kpvM:b9mjv28) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/tutorials/pytorch/index.rst#L404)):*
> ```reStructuredText
> the confidential wrap key::
> 
>    cd <gramine examples repository>/pytorch-confidential
> ```

This doesn't exist (yet?).
___
*[LibOS/shim/include/shim_process.h, line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkE5HkP0awYl57ylBay:-MkE5HkP0awYl57ylBaz:b-iay8u4) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/LibOS/shim/include/shim_process.h#L64)):*
> ```objc
>     /* Complete command line for the process, as reported by /proc/[pid]/cmdline; currently filled
>      * once during initialization, using static buffer and restricted to STR_SIZE. This is enough
>      * for current workloads but see https://github.com/gramineproject/graphene/issues/2279. */
> ```

This probably won't be resolved soon, so I transferred this issue to `https://github.com/gramineproject/gramine/issues/79`.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 387 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkEc6goDeqr1UFWe0oC:-MkEc6goDeqr1UFWe0oD:b-nm1vwd) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/LibOS/shim/src/sys/shim_epoll.c#L387)):*
> ```C
>             /* TODO: This loop is wrong. If there are 2 epoll_items with the same pal_handle (e.g.
>              * due to dup-ed fd), only the first will be updated.
>              * GH issue: https://github.com/gramineproject/graphene/issues/1848 */
> ```

ditto: `https://github.com/gramineproject/gramine/issues/80`

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: 386 of 402 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/17#-MkDFypI2iYY5qUC-AMt:-MkGi8NqDJi7VP6Ltyzv:b-8o8hw4) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Thinking more about this, I started to like the backward compatible version of the rename more - we'll need to switch between old and new branches for a while, and if both have different cmdline tools then it will be quite annoying.
Could you create a small wrapper which would print a deprecation warning and then `exec` the right script, and symlink `graphene-` tools to it?
</blockquote></details>

Done. I dislike the current hack, but hopefully we'll remove it soon.

---
___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkCWAuq5s-nzuOHYM87):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

As discussed on the call, could you include a short explanation for rename in both the commit message and the main readme?
</blockquote></details>

Done.
___
*[CONTRIBUTING.rst, line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkCwjJa3iYqWyW2L9vo:-MkGin0ZBpllnlZFGGDx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/CONTRIBUTING.rst#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I just tried, this alias doesn't work yet. I think we can use `gramine-users@googlegroups.com` for now.
</blockquote></details>

Done.
___
*[CONTRIBUTING.rst, line 39 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkChK-nEvpvqhf2JtNJ:-MkGinJo2dibxWpZK5tw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/CONTRIBUTING.rst#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should be gramine-users (we'll have a few different "levels" now, but we can write more details about it later).
</blockquote></details>

Done.
___
*[README.rst, line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkD9uJ5Bpz4GFNEZL1F:-MkGixOI8ZcNhMNwrLRt:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/README.rst#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> previously

I think "formerly" is more commonly used in such places? But not blocking.
</blockquote></details>

Done
___
*[Documentation/quickstart.rst, line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkDTGYQ96mr6uKZuE_y:-MkGjCWzAxTDWPH3kdTX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/quickstart.rst#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Additional applications enabled in Gramine
> ```

I'd rather say something like "sample configurations for" or similar, current version sounds weird.
</blockquote></details>

Done.
___
*[Documentation/tutorials/pytorch/index.rst, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkGjN2OEpEPoibZURKB:-MkGjN2OEpEPoibZURKC:b-whvje3) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/tutorials/pytorch/index.rst#L10)):*
> ```reStructuredText
>    This page describes the steps required for the old Graphene repository. It
>    will be soon updated with the steps for the new Gramine and Examples
>    repositories.
> ```

FYI: Please note this TODO. We'll need a separate PR to verify this tutorial and fix it.
___
*[Documentation/tutorials/pytorch/index.rst, line 123 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkDZ2bd7LTZ_FT5NppZ:-MkGjiPu3IprqcwWXS04:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/tutorials/pytorch/index.rst#L123)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this link is now wrong (not specific enough)
</blockquote></details>

Done.
___
*[Documentation/tutorials/pytorch/index.rst, line 374 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkGjuzh1RNs4Ni-lAOH:-MkGjuzh1RNs4Ni-lAOI:bqutder) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/tutorials/pytorch/index.rst#L374)):*
> ```reStructuredText
> 
>    cd <gramine examples repository>
>    cp -R pytorch pytorch-confidential
> ```

FYI: @mkow This is where we create this directory `pytorch-confidential`
___
*[Documentation/tutorials/pytorch/index.rst, line 404 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkE4bysAnPViN27kpvL:-MkGjy-t0wijV05hv9ft:b-8fth2b) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/tutorials/pytorch/index.rst#L404)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This doesn't exist (yet?).
</blockquote></details>

It does, see my comment above (I mean, this directory is created in this tutorial, it's not a real dir that we plan to have in our repo)
___
*[LibOS/shim/include/shim_process.h, line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkE5HkP0awYl57ylBay:-MkGkCRx5aBDYYJNjwkg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/LibOS/shim/include/shim_process.h#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This probably won't be resolved soon, so I transferred this issue to `https://github.com/gramineproject/gramine/issues/79`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 387 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkEc6goDeqr1UFWe0oC:-MkGkLGf5_h_7HK7GRre:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/LibOS/shim/src/sys/shim_epoll.c#L387)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto: `https://github.com/gramineproject/gramine/issues/80`
</blockquote></details>

Done.

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 12 of 382 files at r1, 11 of 203 files at r2, 10 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: 395 of 402 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/17#-MkH32Uy5FjYRJQxb9Jo:-MkH32Uz1BOYcqUDDkJ4:b-pg800z) ([raw file](https://github.com/gramineproject/gramine/blob/4afb35c3ecc91f5b651d835bad82d0347c2321c6/.github/ISSUE_TEMPLATE.md#L7)):*
> ```Markdown
> 
> IMPORTANT: please do not post general questions here;
> if you have questions, please use mailing list: support@gramineproject.io
> ```

@mkow what is this address supposed to be?
___
*[Scripts/legacy-graphene-to-gramine, line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/17#-MkH4WN_EwB89ZSfGCeH:-MkH4WNaEh9KCCO4EfSb:b9iivi3) ([raw file](https://github.com/gramineproject/gramine/blob/4afb35c3ecc91f5b651d835bad82d0347c2321c6/Scripts/legacy-graphene-to-gramine#L5)):*
> ```
> # Copyright (C) 2021 Intel Corporation
> 
> REPLACED=${0/graphene/gramine}
> ```

`${//}` is bashism and you could do without it by `REPLACED="gramine-${0#graphene-}"`, because you know that `graphene-` goes at the beginning of the string. Then you can fix shebang to `#!/bin/sh`.
___
*[Scripts/legacy-graphene-to-gramine, line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/17#-MkH47Cm2NDCyPc9bu2s:-MkH47Cm2NDCyPc9bu2t:bl83cmw) ([raw file](https://github.com/gramineproject/gramine/blob/4afb35c3ecc91f5b651d835bad82d0347c2321c6/Scripts/legacy-graphene-to-gramine#L8)):*
> ```
> 
> echo "WARNING: Graphene was renamed to Gramine recently. Consider using new executable names." >&2
> echo "         (For now, we replaced call to '$(basename $0)' with '$(basename $REPLACED)')." >&2
> ```

`$(basename "$REPLACED")` (`""` quotes inside `()`), unless you're 100% sure you'll never get space in there.
___
*[Scripts/meson.build, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/17#-MkH5UvzCHgLC_fOl52C:-MkH5Uw-3BGQtkZiP1DA:b-kbynww) ([raw file](https://github.com/gramineproject/gramine/blob/4afb35c3ecc91f5b651d835bad82d0347c2321c6/Scripts/meson.build#L12)):*
> ```Meson
> endforeach
> 
> install_data(
> ```

Can you move this to `tools/`? It's a CLI thing exposed (almost exposed) to users, and in scripts we have internal things for buildsystem and CI.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: 395 of 402 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/17#-MkH32Uy5FjYRJQxb9Jo:-MkH7Tym-xHJgC7rKuRF:b-rd5w4i) ([raw file](https://github.com/gramineproject/gramine/blob/4afb35c3ecc91f5b651d835bad82d0347c2321c6/.github/ISSUE_TEMPLATE.md#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@mkow what is this address supposed to be?
</blockquote></details>

ah, sorry, fixed while reviewing

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[CONTRIBUTING.rst, line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/17#-MkHXlp9AWj1QPk0Lt7p:-MkHXlpAA7bqJx_QC5pI:byr7eke) ([raw file](https://github.com/gramineproject/gramine/blob/e03a4b444ef3ed98377e0f5b3ad6c15319197bad/CONTRIBUTING.rst#L39)):*
> ```reStructuredText
> 
> Or you can see the archives at this google group:
> https://groups.google.com/forum/#!forum/gramine-users
> ```

This links nowadays redirects to `https://groups.google.com/g/gramine-users`, which is shorter and nicer.
___
*[README.rst, line 113 at r4](https://reviewable.io/reviews/gramineproject/gramine/17#-MkHZIn7-MG8XXtmmPdc:-MkHZIn8BVfpEBi58Xvq:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e03a4b444ef3ed98377e0f5b3ad6c15319197bad/README.rst#L113)):*
> ```reStructuredText
> 
> For any questions, please send an email to gramine-users@googlegroups.com
> (`public archive <https://groups.google.com/forum/#!forum/gramine-users>`__).
> ```

ditto
___
*[Documentation/quickstart.rst, line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkDTGYQ96mr6uKZuE_y:-MkHZWjTD7sbNGsg-DeO:b-iohch4) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/quickstart.rst#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But now you dropped the "applications" word altogether ;)
___
*[Documentation/tutorials/pytorch/index.rst, line 374 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkGjuzh1RNs4Ni-lAOH:-MkHZjCP7JBT0SR-hmCX:b-x5m1ny) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/tutorials/pytorch/index.rst#L374)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: @mkow This is where we create this directory `pytorch-confidential`
</blockquote></details>

Aaah, I see.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: 395 of 403 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[CONTRIBUTING.rst, line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/17#-MkHXlp9AWj1QPk0Lt7p:-MkHcsUk9FbAypFnxJCj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e03a4b444ef3ed98377e0f5b3ad6c15319197bad/CONTRIBUTING.rst#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This links nowadays redirects to `https://groups.google.com/g/gramine-users`, which is shorter and nicer.
</blockquote></details>

Done.
___
*[README.rst, line 113 at r4](https://reviewable.io/reviews/gramineproject/gramine/17#-MkHZIn7-MG8XXtmmPdc:-MkHd6VnCwwRPYVNAIOi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e03a4b444ef3ed98377e0f5b3ad6c15319197bad/README.rst#L113)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Documentation/quickstart.rst, line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkDTGYQ96mr6uKZuE_y:-MkHdOtO6z13wIhxR0-N:b-b8jf3m) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/quickstart.rst#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But now you dropped the "applications" word altogether ;)
</blockquote></details>

Done. I hope I understood you right this time.
___
*[Scripts/legacy-graphene-to-gramine, line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/17#-MkH4WN_EwB89ZSfGCeH:-MkHe3udDPHGJShe5HpV:bm5kzh9) ([raw file](https://github.com/gramineproject/gramine/blob/4afb35c3ecc91f5b651d835bad82d0347c2321c6/Scripts/legacy-graphene-to-gramine#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`${//}` is bashism and you could do without it by `REPLACED="gramine-${0#graphene-}"`, because you know that `graphene-` goes at the beginning of the string. Then you can fix shebang to `#!/bin/sh`.
</blockquote></details>

Done. It didn't work exactly like you proposed because the path of `$0` is an absolute path. So I split it into the path-to-executable and the basename-of-executable.
___
*[Scripts/legacy-graphene-to-gramine, line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/17#-MkH47Cm2NDCyPc9bu2s:-MkHe99sAcx3ISKOCeVo:b-dwrtt5) ([raw file](https://github.com/gramineproject/gramine/blob/4afb35c3ecc91f5b651d835bad82d0347c2321c6/Scripts/legacy-graphene-to-gramine#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`$(basename "$REPLACED")` (`""` quotes inside `()`), unless you're 100% sure you'll never get space in there.
</blockquote></details>

Done. Well, actually not applicable anymore.
___
*[Scripts/meson.build, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/17#-MkH5UvzCHgLC_fOl52C:-MkHdkgJ4DGQIHRgE_bS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4afb35c3ecc91f5b651d835bad82d0347c2321c6/Scripts/meson.build#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can you move this to `tools/`? It's a CLI thing exposed (almost exposed) to users, and in scripts we have internal things for buildsystem and CI.
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Documentation/quickstart.rst, line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/17#-MkDTGYQ96mr6uKZuE_y:-MkHj2f4-DOZJ7ofA8fi:b1tuaju) ([raw file](https://github.com/gramineproject/gramine/blob/b7ee1071147946a5fc2c318f011de97b2468b25e/Documentation/quickstart.rst#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I hope I understood you right this time.
</blockquote></details>

Ok, now it's fine ;)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: 402 of 403 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[tools/legacy-graphene-to-gramine, line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/17#-MkHrnBg9syH-WglVPdU:-MkHutkU9ZeyZhwRfjR7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc13a64c8aa7284517db0c796761059c014691c5/tools/legacy-graphene-to-gramine#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Those two still need quotes like this: `"$(basename "$0")"`.
</blockquote></details>

Done.
___
*[Scripts/legacy-graphene-to-gramine, line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/17#-MkH47Cm2NDCyPc9bu2s:-MkHuvanA3muaHDxBzwY:b1yo8aj) ([raw file](https://github.com/gramineproject/gramine/blob/4afb35c3ecc91f5b651d835bad82d0347c2321c6/Scripts/legacy-graphene-to-gramine#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not done, moved comment to new file.
</blockquote></details>

Done, hopefully.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[tools/legacy-graphene-to-gramine, line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/17#-MkHrnBg9syH-WglVPdU:-MkI_ucRCsDhvC54A7JX:by00pho) ([raw file](https://github.com/gramineproject/gramine/blob/bc13a64c8aa7284517db0c796761059c014691c5/tools/legacy-graphene-to-gramine#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What's the difference between this and `ORIGBASE=$(basename "$0")`? I don't think there is, in this context.

**Review by woju — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[tools/legacy-graphene-to-gramine, line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/17#-MkHrnBg9syH-WglVPdU:-MkJQ0VW2bkyiLxhJZXX:bc0frdh) ([raw file](https://github.com/gramineproject/gramine/blob/bc13a64c8aa7284517db0c796761059c014691c5/tools/legacy-graphene-to-gramine#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the difference between this and `ORIGBASE=$(basename "$0")`? I don't think there is, in this context.
</blockquote></details>

If basename contains whitespace like `first-word second-word`, then `ORIGBASE=first-word second-word` is an invocation of `second-word` command with modified environment. Which is not what we want.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[tools/legacy-graphene-to-gramine, line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/17#-MkHrnBg9syH-WglVPdU:-MkJhHqODcZqZgOuNwa7:b-4si1kx) ([raw file](https://github.com/gramineproject/gramine/blob/bc13a64c8aa7284517db0c796761059c014691c5/tools/legacy-graphene-to-gramine#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If basename contains whitespace like `first-word second-word`, then `ORIGBASE=first-word second-word` is an invocation of `second-word` command with modified environment. Which is not what we want.
</blockquote></details>

```
$ cat 'w1 w2' 
#!/bin/sh

function w1() {
    echo "WUT"
}
function w2() {
    echo "WUT 2"
}

A=$(basename "$0")

for i in $A; do echo $i; done
[borys@... test]$ ./w1\ w2 
w1
w2
```

**Review by mkow — APPROVED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/17)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
