### PR TITLE
[Pal] Add updatable timeout to `DkStreamsWaitEvents`

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Currently only used by epoll

Fixes https://github.com/gramineproject/graphene/issues/435

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/385)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/385)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNk7EY0Bnsh6PIHHUM:-MvNk7EY0Bnsh6PIHHUN:bisjo0n) (no related file):*
Please add that this fixes https://github.com/gramineproject/graphene/issues/435

---
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 268 at r1](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNiY-cCVgYAaDFgNUt:-MvNiY-cCVgYAaDFgNUu:b-a8q3i3) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/LibOS/shim/src/ipc/shim_ipc_worker.c#L268)):*
> ```C
>         }
> 
>         int ret = DkStreamsWaitEvents(items_cnt, handles, events, ret_events, NULL);
> ```

Please add `/*timeout_us=*/`
___
*[LibOS/shim/src/sys/shim_poll.c, line 208 at r1](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNkWqT2fADsKsnS3m4:-MvNkWqT2fADsKsnS3m5:bmlo4si) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/LibOS/shim/src/sys/shim_poll.c#L208)):*
Interestingly, `man poll` says this:
> Specifying a negative value  in  timeout  means  an infinite  timeout.

At the same time, `man epoll_wait` explicitly talks about `-1`.

So maybe use a check `timeout_ms < 0` here?
___
*[Pal/src/host/Linux/db_object.c, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNmbsj3yQYLIrU2pza:-MvNmbsj3yQYLIrU2pzb:bm9hoql) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/Pal/src/host/Linux/db_object.c#L24)):*
> ```C
>                          pal_wait_flags_t* ret_events, uint64_t* timeout_us) {
>     int ret;
>     uint64_t remaining_time = timeout_us ? *timeout_us : 0;
> ```

Could you add a suffix `_us` to this variable?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1537 at r1](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNnVWWEgGD8nontCOd:-MvNnVWWEgGD8nontCOe:bm9hoql) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1537)):*
> ```C
>     size_t nfds_bytes = nfds * sizeof(struct pollfd);
>     ms_ocall_poll_t* ms;
>     uint64_t remaining_time = timeout_us ? *timeout_us : (uint64_t)-1;
> ```

Could you add a suffix `_us` to this variable?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/385)* status: 16 of 20 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNk7EY0Bnsh6PIHHUM:-MvPYLU-27SDh7BJ2PK0:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add that this fixes https://github.com/gramineproject/graphene/issues/435
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 268 at r1](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNiY-cCVgYAaDFgNUt:-MvPYUXWA-cp6GKtlNNP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/LibOS/shim/src/ipc/shim_ipc_worker.c#L268)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `/*timeout_us=*/`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_poll.c, line 208 at r1](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNkWqT2fADsKsnS3m4:-MvPZZf8-NaA9rg79oB2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/LibOS/shim/src/sys/shim_poll.c#L208)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interestingly, `man poll` says this:
> Specifying a negative value  in  timeout  means  an infinite  timeout.

At the same time, `man epoll_wait` explicitly talks about `-1`.

So maybe use a check `timeout_ms < 0` here?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_object.c, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNmbsj3yQYLIrU2pza:-MvPZrVu2OUGBmBcMBoT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/Pal/src/host/Linux/db_object.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a suffix `_us` to this variable?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1537 at r1](https://reviewable.io/reviews/gramineproject/gramine/385#-MvNnVWWEgGD8nontCOd:-MvP_3a98-ZIsO66kVGJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1537)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a suffix `_us` to this variable?
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/385)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 16 of 20 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/385)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/include/pal/pal.h, line 624 at r2](https://reviewable.io/reviews/gramineproject/gramine/385#-MvflwQWD9BwFtW2bnZL:-MvflwQWD9BwFtW2bnZM:b-ma4f3t) ([raw file](https://github.com/gramineproject/gramine/blob/175d84f30c8180bc5c0aa091e33d18c3170c6a89/Pal/include/pal/pal.h#L624)):*
> ```objc
>  * \brief Poll - wait for an event to happen on at least one handle
>  *
>  * \param count the number of items in \p handle_array
> ```

While we're rewriting this doc, could you align the descriptions and separate them with at least 2 spaces from the parameter names? I'd like to make these more readable. Something like:



_Suggestion:_
```objc
 * \param count               the number of items in \p handle_array
 * \param handle_array        array of handles to poll
 * \param events              requested events for each handle
 * \param[out] ret_events     events that were detected on each handle
 * \param[in,out] timeout_us  timeout for the wait (`NULL` to block indefinitely)
```

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/385)* status: 19 of 20 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/pal/pal.h, line 624 at r2](https://reviewable.io/reviews/gramineproject/gramine/385#-MvflwQWD9BwFtW2bnZL:-MvjKgYG4bqXpo-ap9F1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/175d84f30c8180bc5c0aa091e33d18c3170c6a89/Pal/include/pal/pal.h#L624)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

While we're rewriting this doc, could you align the descriptions and separate them with at least 2 spaces from the parameter names? I'd like to make these more readable. Something like:
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/385)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/385)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/385)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
