### PR TITLE
[CI] Add tools for testing device passthrough in Gramine SGX

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This PR moves two tools from now-archived repository "device-testing-tools":
- `gramine-device-testing-module` -- dummy kernel module, implementing a device which can be passed to Gramine to test device-related functionality (in particular shared untrusted memory and ioctls).
- `initramfs_builder` -- set of scripts to build and run the virtual machine, which will contain both Gramine and the above device.

These tools will be used in CI in a follow-up PR (see https://github.com/gramineproject/gramine/pull/1032).

## How to test this PR? 

I tested the tools manually on an SGX-enabled machine with Ubuntu 22.04. In #1032, these tools will be tested automatically by the Jenkins CI pipeline `linux-sgx-vm-gcc-release`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)

### CODE REVIEW

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: 0 of 12 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`.ci/gramine-device-testing-module/.gitignore` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwUk-bAsOZNIm-ydwx:-NKwUk-bAsOZNIm-ydwy:b-albslb) ([raw file](https://github.com/gramineproject/gramine/blob/25ce598f508cbec499e327b38729af87ff988aae/.ci/gramine-device-testing-module/.gitignore#L5)):*
> ```ignore
> /gramine-testing-dev.*
> /Module.symvers
> /modules.order
> ```

Do we want to make them directory specific? Shouldn't we just add them to general/main .gitignore.
___
*[`.ci/gramine-device-testing-module/main.c` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwVKgA1Ij-8CprLbrV:-NKwVKgA1Ij-8CprLbrW:b-ixt3we) ([raw file](https://github.com/gramineproject/gramine/blob/25ce598f508cbec499e327b38729af87ff988aae/.ci/gramine-device-testing-module/main.c#L1)):*
> ```C
> /* These must come before includes. */
> ```

Do we wan't to add copyrights?
As this is copy/paste - I won't review this file.
___
*[`.ci/initramfs_builder/run.sh` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwWSwC0YR745lcEYBN:-NKwWSwC0YR745lcEYBO:b-7vs8pw) ([raw file](https://github.com/gramineproject/gramine/blob/25ce598f508cbec499e327b38729af87ff988aae/.ci/initramfs_builder/run.sh#L10)):*
> ```Shell
>     -initrd initramfs.cpio.gz \
>     -nographic \
>     -monitor /dev/null \
> ```

Shouldn't this be `-monitor none` ?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: 0 of 14 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKx5WgF20adrg8qix3q:-NKx5WgF20adrg8qix3r:b-cne0f7) (no related file):*
I verified now that it works manually. Ready for review.

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: 0 of 14 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKx92Mu8lZeoC6TBHGp:-NKx92Mu8lZeoC6TBHGq:b-85i63v) (no related file):*
LGTM.

___

**Review by donporter — APPROVED** [review]
> Reviewed 7 of 12 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwRFTPD_kcsk0Dow4S:-NLBcpvNEHPMzy3FExCk:b-6mqbl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The tools are copied as-is from corresponding subdirs in this repo: https://github.com/gramineproject/device-testing-tools

Note that subdirs of that repo `qemu` and `tools` are unneeded and were not copied here. The former has patches to build SGX-enabled QEMU; however in recent Debian/Ubuntu the official QEMU package is already SGX-enabled. The latter has a tool `download` which already exists in our core Gramine repo (under `scripts/`).
</blockquote></details>

For maintenance reasons I'd prefer if the kernel module was in separate repository. It needs to be packaged and deployed separately, and I don't think there will be many changes that would need to be kept in sync with gramine.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwRFTPD_kcsk0Dow4S:-NLKk6h42fJMV5iTLc-2:b-ahb3rx) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For maintenance reasons I'd prefer if the kernel module was in separate repository. It needs to be packaged and deployed separately, and I don't think there will be many changes that would need to be kept in sync with gramine.
</blockquote></details>

@woju This was requested by @boryspoplawski and agreed with by @mkow. See: https://github.com/gramineproject/device-testing-tools/pull/6#pullrequestreview-1201839454

But I don't mind either way. Just need to decide on one course of action, and I'll oblige.

Since Borys is not active in the project anymore, it's a matter of asking Michal -- @mkow what do you think?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKx92Mu8lZeoC6TBHGp:-NLKkUYg9d0hi5zuKbSG:b-nav911) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

LGTM.
</blockquote></details>

Thanks for checking.

___

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwRFTPD_kcsk0Dow4S:-NLL2mEy78UntJd_MDz5:bn53gjh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju This was requested by @boryspoplawski and agreed with by @mkow. See: https://github.com/gramineproject/device-testing-tools/pull/6#pullrequestreview-1201839454

But I don't mind either way. Just need to decide on one course of action, and I'll oblige.

Since Borys is not active in the project anymore, it's a matter of asking Michal -- @mkow what do you think?
</blockquote></details>

I did not read the PR, but the testing kernel module should **never** be packaged. It's probably even vulnerable, which reminds me you should probably fix that first (there should be TODOs in the code).

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwRFTPD_kcsk0Dow4S:-NLLwOPo1r26wqlA1pZO:b-q5iij7) (no related file):*
> I did not read the PR, but the testing kernel module should never be packaged.

We probably understood Woju's use of the word `packaged` differently. Yes, this kernel module is **dummy testing module for our CI**, it will never be actually used anywhere else other than in an ephemeral VM (which we create every time anew in the CI pipeline).

I understood Woju's remark about packaging/deploying as simply "kernel modules don't have anything to do with core Gramine, so they should be in the separate repo, and then Gramine CI should `git clone` this separate repo" (something that I'm doing currently in https://github.com/gramineproject/gramine/pull/1032)

Or @woju did I misunderstand your point? Given the additional info that this kernel module is for CI testing only and in a confined VM environment, do you still want it in a separate repo (as it is now, in https://github.com/gramineproject/device-testing-tools)?

___

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwRFTPD_kcsk0Dow4S:-NLMho5eEu1IDh34_9mY:b-qe4ivo) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Going with this line of thought you should remove `CI-Examples`, all "regression" tests and probably `.ci`...
</blockquote></details>

I need it to be wrapped at least in dkms to survive `apt-get update` which would update the kernel package. Optimally it will be a `deb` package, but only for our own purposes and not distributed through our repo. So it needs to be in a separate repo, so we don't have to build and distribute it together with whole gramine. AFAIU (please correct me) we don't need it to be redeployed in CI for each gramine commit, but we'll have it running for each CI host once and don't touch it.

I don't know anything about it being vulnerable, but if it's "probably even vulnerable", then I doubly don't want it in the main repo.

___

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwRFTPD_kcsk0Dow4S:-NLSDO0f6dRk_Mbv0GI7:b-tquil9) (no related file):*
> I need it to be wrapped at least in dkms to survive apt-get update

I don't think you do. This module is not running on the hosts, but inside a VM. You don't want the module to be up to date with the newest available kernel, but the one that is actually running at this moment (because that one is used in the VM). Also you need to rebuild the initrafms for the VM.

I think it should be built on each reboot (or each CI run, but that's probably too expensive).

Anyway, I'm off, if you have any questions for me ping me on gitter

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwRFTPD_kcsk0Dow4S:-NLVKdzzCOrbONn78bZ7:bdqmy5v) (no related file):*
> AFAIU (please correct me) we don't need it to be redeployed in CI for each gramine commit, but we'll have it running for each CI host once and don't touch it.

No, that's not how we wanted this. Please see my PR on how it is added to CI: https://github.com/gramineproject/gramine/pull/1032/files#diff-5b3e1246acc113f2049a46659ee647254743386e9ab7914c15777b146a5fe09e

> I think it should be built on each reboot (or each CI run, but that's probably too expensive).

We agreed to build both the testing kernel module and the initramfs on each CI run (see also my link above). It's not that expensive at all, why would it be.

So based on the conversation between @woju and @boryspoplawski, I am leaning towards keeping the kernel module in the separate repo (as it is currently: https://github.com/gramineproject/device-testing-tools). I will let @mkow be the tie-breaker in this conversation.

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1098)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @oshogbo, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1098#-NKwRFTPD_kcsk0Dow4S:-NLkdXSx6w17D3FJURON:bf09aro) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> AFAIU (please correct me) we don't need it to be redeployed in CI for each gramine commit, but we'll have it running for each CI host once and don't touch it.

No, that's not how we wanted this. Please see my PR on how it is added to CI: https://github.com/gramineproject/gramine/pull/1032/files#diff-5b3e1246acc113f2049a46659ee647254743386e9ab7914c15777b146a5fe09e

> I think it should be built on each reboot (or each CI run, but that's probably too expensive).

We agreed to build both the testing kernel module and the initramfs on each CI run (see also my link above). It's not that expensive at all, why would it be.

So based on the conversation between @woju and @boryspoplawski, I am leaning towards keeping the kernel module in the separate repo (as it is currently: https://github.com/gramineproject/device-testing-tools). I will let @mkow be the tie-breaker in this conversation.
</blockquote></details>

I agree with Borys, this shouldn't be packaged because it's likely vulnerable and should be used only by maintainers / experienced devs.
I'm fine with both keeping it in a separate repo and with merging here, but not packaging.

___

**Pull request closed without merging**
