### PR TITLE
[LibOS] Rewrite `unix` regression test

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Extracted from https://github.com/gramineproject/gramine/pull/986, with comments from @boryspoplawski resolved.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/996)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/996)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/test/regression/test_libos.py` line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEpYbfACsvLfdRKFMT5:-NEpYbfB24OMBJUBV5O0:b-r3vmee) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/test_libos.py#L1295)):*
> ```Python
>             os.remove("tmp/dummy")
>         if os.path.exists("tmp/unix_socket"):
>             os.remove("tmp/unix_socket")
> ```

These removals are currently not needed because Gramine never creates actual host files anyway. Well, actually, even if we add corresponding host files (as I suggested in #986), the files won't be located here anyway. I guess I can just remove these lines then?
___
*[`libos/test/regression/unix.c` line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEpYzFsEN6nY5AGa_E8:-NEpYzFt5bRQaTIQmJFf:b3hjyvy) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/unix.c#L87)):*
> ```C
>     CHECK(close(pipefd));
> 
> #if 0 /* FIXME: currently Gramine doesn't reflect named UNIX sockets in file system */
> ```

FYI: I will uncomment this snippet once I re-implement #986, in a follow up PR
___
*[`libos/test/regression/unix.c` line 149 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEpZ3Lc56UaxZU0dHw7:-NEpZ3Lc56UaxZU0dHw8:b3hjyvy) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/unix.c#L149)):*
> ```C
>     }
> 
> #if 0 /* FIXME: currently Gramine doesn't reflect named UNIX sockets in file system */
> ```

FYI: I will uncomment this snippet once I re-implement #986, in a follow up PR

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/996)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/test/regression/test_libos.py` line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEpYbfACsvLfdRKFMT5:-NEqSz9o7MFQgKL8efTc:busqjsr) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/test_libos.py#L1295)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These removals are currently not needed because Gramine never creates actual host files anyway. Well, actually, even if we add corresponding host files (as I suggested in #986), the files won't be located here anyway. I guess I can just remove these lines then?
</blockquote></details>

i guess
___
*[`libos/test/regression/unix.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEqVC6aDeEngCkffvpi:-NEqVC6b6OzBHkIQ750V:b-nsh0ma) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/unix.c#L35)):*
> ```C
>     if (ret == 0 || errno != ENOENT) {
>         errx(1, "nonexisting-socket connect didn't fail with ENOENT");
>     }
> ```

`CHECK(close(s))` missing
___
*[`libos/test/regression/unix.c` line 140 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEqWBb565-ULm4AsJzN:-NEqWBb565-ULm4AsJzO:b-s9l9wn) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/unix.c#L140)):*
> ```C
>         return 0;
>     }
> ```

You can close both ends of `pipefds` here
___
*[`libos/test/regression/unix.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEqW8nD54B8H_JytyV3:-NEqW8nD54B8H_JytyV4:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/unix.c#L141)):*
> ```C
>     }
> 
>     for (int i = 0; i < 2; i++) {
> ```





_Suggestion:_
```C
size_t 
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/996)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/test/regression/test_libos.py` line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEpYbfACsvLfdRKFMT5:-NEtO_4b66UnKdZkTYWI:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/test_libos.py#L1295)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

i guess
</blockquote></details>

Done
___
*[`libos/test/regression/unix.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEqVC6aDeEngCkffvpi:-NEtOi119ch2zvojoc6r:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/unix.c#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`CHECK(close(s))` missing
</blockquote></details>

Done.
___
*[`libos/test/regression/unix.c` line 140 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEqWBb565-ULm4AsJzN:-NEtOrC96qiSNA7e2rbu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/unix.c#L140)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can close both ends of `pipefds` here
</blockquote></details>

Done.
___
*[`libos/test/regression/unix.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEqW8nD54B8H_JytyV3:-NEtOu0UA_bhVeHczZYS:b-8x6pct) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/unix.c#L141)):*
> ```C
>     }
> 
>     for (int i = 0; i < 2; i++) {
> ```

Done, but out of curiosity -- is it just your preference, or is there something more at play?

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/996)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`libos/test/regression/unix.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/996#-NEqW8nD54B8H_JytyV3:-NEu6fY_7RKagrDM7gEC:b4obsb3) ([raw file](https://github.com/gramineproject/gramine/blob/a6cdce77e2aa59e92c88a4dbe934472396eb79ed/libos/test/regression/unix.c#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, but out of curiosity -- is it just your preference, or is there something more at play?
</blockquote></details>

We require that in our coding guidelines, so we shouldn't make exceptions even for places where it truly does not matter. Also who knows what changes will be made to this loop at some point in the future, it might start to matter then

**Review by mkow — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/996)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-20.04 please (`fcntl14_64` LTP test timed out, unrelated issues)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/996)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
