### PR TITLE
[LibOS] Log itimer event re-registration failure in callback

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 
Though there is not much we could do when `install_async_event()` fails, it's better to check the return of it and print a warning message if this fails.

## How to test this PR? 
CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1786)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1786)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`libos/src/sys/libos_alarm.c` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1786#-NrdPMC2E3lObFOYTg-u:-NrdPMC2E3lObFOYTg-v:byl4wve) ([raw file](https://github.com/gramineproject/gramine/blob/c5a5a5a8d11a4532f2d819f68290be41d1214040/libos/src/sys/libos_alarm.c#L71)):*
> ```C
>         int64_t ret = install_async_event(/*object=*/NULL, next_reset, &signal_itimer,
>                                           /*arg=*/NULL);
>         if (ret < 0)
> ```

Can we add `{ }` in this IF, because we have a multi-line statement in the body. And it hurts my eyes without the brackets.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1786)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_alarm.c` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1786#-NrdPMC2E3lObFOYTg-u:-NrdVzQLAPw25u1BK_Oc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c5a5a5a8d11a4532f2d819f68290be41d1214040/libos/src/sys/libos_alarm.c#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add `{ }` in this IF, because we have a multi-line statement in the body. And it hurts my eyes without the brackets.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1786)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1786)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1786#-Ns3nJTq1qWGUo0S0LPu):*
hotmail?
___
*[`libos/src/sys/libos_alarm.c` line 74 at r2](https://reviewable.io/reviews/gramineproject/gramine/1786#-Ns3o7ZR4wFIGhYrT_3q:-Ns3o7ZR4wFIGhYrT_3r:bdini3j) ([raw file](https://github.com/gramineproject/gramine/blob/c17cad9a7509b3b46b43fcee2838c470a9db98cb/libos/src/sys/libos_alarm.c#L74)):*
> ```C
>             log_warning(
>                 "failed to re-enqueue the next timer event initially set up by 'setitimer()': %s",
>                 unix_strerror(ret));
> ```

Actually, should we warn or maybe die? Hard to say how critical is missing a timer event...

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1786)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1786#-Ns3nJTq1qWGUo0S0LPu):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

hotmail?
</blockquote></details>

oops, thanks for noticing! My dev machine went away these days so I used my PC to commit.
___
*[`libos/src/sys/libos_alarm.c` line 74 at r2](https://reviewable.io/reviews/gramineproject/gramine/1786#-Ns3o7ZR4wFIGhYrT_3q:-Ns6OEcmDfFP0VPScp2j:bt1oy4p) ([raw file](https://github.com/gramineproject/gramine/blob/c17cad9a7509b3b46b43fcee2838c470a9db98cb/libos/src/sys/libos_alarm.c#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, should we warn or maybe die? Hard to say how critical is missing a timer event...
</blockquote></details>

I'm fine w/ error+die.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1786)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`libos/src/sys/libos_alarm.c` line 74 at r2](https://reviewable.io/reviews/gramineproject/gramine/1786#-Ns3o7ZR4wFIGhYrT_3q:-Ns7LeUM-NWKigzniWp4:b2hm53u) ([raw file](https://github.com/gramineproject/gramine/blob/c17cad9a7509b3b46b43fcee2838c470a9db98cb/libos/src/sys/libos_alarm.c#L74)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I'm fine w/ error+die.
</blockquote></details>

I'm fine too. Should not happen in reality anyway.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1786)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
