### PR TITLE
[Docs] Add section on patched `libgomp` to Perf doc

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This info was scattered around Gramine repositories. Let's summarize it in our documentation.

## How to test this PR? 

I enabled ReadTheDocs branch to look at it: https://gramine.readthedocs.io/en/dimakuv-docs-mention-libgomp-perf/performance.html#gnu-libgomp-performance-bottleneck.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1652)

### CODE REVIEW

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1652)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/performance.rst` line 439 at r1](https://reviewable.io/reviews/gramineproject/gramine/1652#-NjD_gfxBxpP6h8AXIYL:-NjD_gfy5FWOdJ6k34qR:b-9ixu32) ([raw file](https://github.com/gramineproject/gramine/blob/b5a4d505615ba969afd486cfc7cdc61579ce240c/Documentation/performance.rst#L439)):*
> ```reStructuredText
> We would like to note that an alternative implementation of OpenMP -- the
> ``libiomp`` library -- does **not** have any performance bottlenecks under
> Gramine SGX. We recommend to switch to this library whenever possible, instead
> ```

sounds a bit absolute... :) but I'm fine w/ it.



_Code quote:_
```reStructuredText
``libiomp`` library -- does **not** have any performance bottlenecks under
Gramine SGX. We recommend to switch to this library whenever possible, instead
```

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1652)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/performance.rst` line 429 at r1](https://reviewable.io/reviews/gramineproject/gramine/1652#-NjEZ2bF5TPNCKKbNfu_:-NjEZ2bF5TPNCKKbNfua:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b5a4d505615ba969afd486cfc7cdc61579ce240c/Documentation/performance.rst#L429)):*
> ```reStructuredText
> modify your Gramine manifest (as the library is placed into the Gramine
> runtime-libraries directory, which is typically already a part of the manifest).
> However, sometimes using the patched libgomp requires to specify the
> ```





_Suggestion:_
```reStructuredText
using the patched libgomp requires specifying
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1652)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/performance.rst` line 429 at r1](https://reviewable.io/reviews/gramineproject/gramine/1652#-NjEZ2bF5TPNCKKbNfu_:-NjGtxUr-7FBM8QLRBN3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b5a4d505615ba969afd486cfc7cdc61579ce240c/Documentation/performance.rst#L429)):*
> ```reStructuredText
> modify your Gramine manifest (as the library is placed into the Gramine
> runtime-libraries directory, which is typically already a part of the manifest).
> However, sometimes using the patched libgomp requires to specify the
> ```

Done.
___
*[`Documentation/performance.rst` line 439 at r1](https://reviewable.io/reviews/gramineproject/gramine/1652#-NjD_gfxBxpP6h8AXIYL:-NjGuJCv5POYCyzE1lNz:b-hmpluz) ([raw file](https://github.com/gramineproject/gramine/blob/b5a4d505615ba969afd486cfc7cdc61579ce240c/Documentation/performance.rst#L439)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

sounds a bit absolute... :) but I'm fine w/ it.
</blockquote></details>

Done

Also I noticed that I put `libiomp` in double-backticks, which we don't do (at least in this document) with library names. So I just emphasize this library name in italics now.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1652)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/performance.rst` line 439 at r2](https://reviewable.io/reviews/gramineproject/gramine/1652#-NjIfXhZ5n45ClE5xYSV:-NjJQ5AG6h3d8-2QyTVT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/66e9c19372f2603bfa948ae2f6a04cb37eece123/Documentation/performance.rst#L439)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double space
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1652)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1652)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1652)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
