### PR TITLE
[CI] Expand timeout for blender example in CI

### PR DESCRIPTION
**Pull request by woju**
## How to test this PR? 

Liberally submit Jenkins-Debug-* pipelines in CI, none should time out on blender.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1117)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1117)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1117#-NLcPcpz2jamECvswDxo:-NLcPcpz2jamECvswDxp:b-vx8uja) (no related file):*
Depends on https://github.com/gramineproject/gramine/pull/1092.

___

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1117)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1117#-NLcPcpz2jamECvswDxo:-NLeO7cREaxdq6AEGuM6:b-80jufe) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Depends on https://github.com/gramineproject/gramine/pull/1092.
</blockquote></details>

I don't see a connection between these two PRs, but ok, we'll merge 1092 first.

___

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1117)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1117#-NLcPcpz2jamECvswDxo:-NLffN957t5wMsEtMsvH:b-wgx0o) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see a connection between these two PRs, but ok, we'll merge 1092 first.
</blockquote></details>

This PR targeted #1092 branch.

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1117)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (Internet connection seemed to be low)

**Pull request merged**
