### PR TITLE
Rework sgx_include_path and build against linux-libc-dev

### PR DESCRIPTION
**Pull request by woju**
## How to test this PR? 

On Ubuntu: try 20.04 (should build from aux kernel sources, as it has kernel < 5.11) and 22.04 (has upstream driver).

If you have only a single machine/containser: use Debian 11 and  you need to either have installed or not installed `linux-libc-dev (>= 5.11)`.

```sh
apt-get install kernel-headers-amd64 -t bullseye-backports
apt-get build-dep . -t bullseye-backports # shouldn't install newer linux-libc-dev, but check it
debuild # should build with aux kernel
apt-get install linux-libc-dev -t bullseye-backports
debuild # should build with #include <asm/sgx.h>
```

CI will build only `#include <asm/sgx.h>`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKEvsSf3H6vlamnKr9l:-NKEvsSf3H6vlamnKr9m:b-b52wg) (no related file):*
@jinengandhi-intel: Could you check this PR?

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKn48Qi3tdrMsknUl9G):*
What does it mean "optional, newer kernels"? Do you mean Linux distros which ship their own patched Linux kernels, that put the SGX header file under exotic paths?
___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKn5NUyA0IAwJakr8he):*
Don't we need to update our documentation mentioning this package `linux-libc-dev` which is a pre-requisite and needs to be installed?

This package is needed only for Debian distros, right?

**Review by jinengandhi-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKEvsSf3H6vlamnKr9l:-NKpgXif5oa4m4Q1oddp:b-3531af) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@jinengandhi-intel: Could you check this PR?
</blockquote></details>

So you want to test this PR against all distros and confirm that the SGX driver path is resolved correctly and the build passes, is that right?

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jinengandhi-intel and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKEvsSf3H6vlamnKr9l:-NKrVQ2e1tGNg_Zesb_s:b8pei5l) (no related file):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

So you want to test this PR against all distros and confirm that the SGX driver path is resolved correctly and the build passes, is that right?
</blockquote></details>

Yes, that's right.

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @jinengandhi-intel)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKn48Qi3tdrMsknUl9G):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does it mean "optional, newer kernels"? Do you mean Linux distros which ship their own patched Linux kernels, that put the SGX header file under exotic paths?
</blockquote></details>

I mean Debian and Ubuntu, which don't have `linux-libc-dev` packages for `linux-image-<version>-amd64` packages. For those, the SGX header is somewhere in `/usr/src`, which is not a standard path (not in the default set of paths that gcc searches for includes).
___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKn5NUyA0IAwJakr8he):*
> this package linux-libc-dev which is a pre-requisite and needs to be installed

It's part of `build-essential` set. You don't need to specify it separately.

> This package is needed only for Debian distros, right?

Every distro has some similar package. On RHEL-like distros it's called `kernel-headers` (not to be confused with `kernel-devel`). I didn't check but probably you don't need to specify it either.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jinengandhi-intel and @woju)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKn48Qi3tdrMsknUl9G):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I mean Debian and Ubuntu, which don't have `linux-libc-dev` packages for `linux-image-<version>-amd64` packages. For those, the SGX header is somewhere in `/usr/src`, which is not a standard path (not in the default set of paths that gcc searches for includes).
</blockquote></details>

Hm, why do you call them `optional, newer kernels`? Why not smth like `not those that put the SGX header in a non-standard path, like Debian/Ubuntu`?
___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKn5NUyA0IAwJakr8he):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> this package linux-libc-dev which is a pre-requisite and needs to be installed

It's part of `build-essential` set. You don't need to specify it separately.

> This package is needed only for Debian distros, right?

Every distro has some similar package. On RHEL-like distros it's called `kernel-headers` (not to be confused with `kernel-devel`). I didn't check but probably you don't need to specify it either.
</blockquote></details>

Got it.

**Review by jinengandhi-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKEvsSf3H6vlamnKr9l:-NL4m6AV9xoJF5VONxqH:br0ls9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, that's right.
</blockquote></details>

We have verified Gramine build on Ubuntu 18.04, Ubuntu 20.04, Ubuntu 22.04, Gramine OOT, CentOS & RHEL. We also ran some  PAL, LibOS, FS tests and they are passing.

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKn48Qi3tdrMsknUl9G):*
> why do you call them optional, newer kernels?

Because they are optional (full distro works without those kernels, unless you have HW issues, possibly you need newer kernel for some new driver) and are newer than the default kernel (see 1).

> Why not smth like not those that put the SGX header in a non-standard path, like Debian/Ubuntu?

It's incorrect to conclude that Debian/Ubuntu put kernel headers in non-standard paths. There are several standard paths for kernel headers, because they are meant for different things:
- `linux-libc-dev` are kernel headers meant for userspace programs that interface kernel ABI (syscalls et al.), in reality they're mostly included by libc headers and only indirectly by "real" userspace programs; they're extracted from `uapi/` directories in kernel tree by kernel's buildsystem and put into layout suitable for `/usr/include` (so that `#include <>` works as advertised).
- `linux-headers-\*` are kernel headers meant for building kernel modules; the standard paths are `/lib/modules/$(KERNELRELEASE)/build` and/or `/lib/modules/$(KERNELRELEASE)/source` (and also other paths linked from there), but distros package those into `/usr/src` and symlink from there (I think it's because they split packages mostly to save disk space by not redistributing multiple copies of the same files for different archs). They contain both `uapi/` and non-UAPI headers, mirrored from kernel tree directly.

Distros do as prescribed, only we've been abusing `/usr/src`, because 1) we didn't have better option (we had to wait until sufficiently new `linux-libc-dev` trickles down to stable versions), 2) we knew how distros like to package it's kernels. But there's nothing there that we really can rely on, long-term.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1090#-NKn48Qi3tdrMsknUl9G):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> why do you call them optional, newer kernels?

Because they are optional (full distro works without those kernels, unless you have HW issues, possibly you need newer kernel for some new driver) and are newer than the default kernel (see 1).

> Why not smth like not those that put the SGX header in a non-standard path, like Debian/Ubuntu?

It's incorrect to conclude that Debian/Ubuntu put kernel headers in non-standard paths. There are several standard paths for kernel headers, because they are meant for different things:
- `linux-libc-dev` are kernel headers meant for userspace programs that interface kernel ABI (syscalls et al.), in reality they're mostly included by libc headers and only indirectly by "real" userspace programs; they're extracted from `uapi/` directories in kernel tree by kernel's buildsystem and put into layout suitable for `/usr/include` (so that `#include <>` works as advertised).
- `linux-headers-\*` are kernel headers meant for building kernel modules; the standard paths are `/lib/modules/$(KERNELRELEASE)/build` and/or `/lib/modules/$(KERNELRELEASE)/source` (and also other paths linked from there), but distros package those into `/usr/src` and symlink from there (I think it's because they split packages mostly to save disk space by not redistributing multiple copies of the same files for different archs). They contain both `uapi/` and non-UAPI headers, mirrored from kernel tree directly.

Distros do as prescribed, only we've been abusing `/usr/src`, because 1) we didn't have better option (we had to wait until sufficiently new `linux-libc-dev` trickles down to stable versions), 2) we knew how distros like to package it's kernels. But there's nothing there that we really can rely on, long-term.
</blockquote></details>

Amazing explanation, thank you!

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by woju** [comment]
If Jenkins-Debug-20.04 fails (esp. on `large_mmap`), plz `@`-ping me, I've been rearranging CI executors and this job went to a suspect node.

**Comment by woju** [comment]
Jenkins, test Jenkins-SGX-18.04-apps please

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1090)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
