### PR TITLE
[GitHub] Add issue creator templates

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

As discussed some time ago, let's try this.

## How to test this PR? 

https://github.com/mkow/test/issues/new/choose

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`.github/ISSUE_TEMPLATE/1-bug-report.yml` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/951#-ND_MQarDt9hnZQtSCWG:-ND_MQasDFoA15IlgEiS:b-s2532p) ([raw file](https://github.com/gramineproject/gramine/blob/1b0962f6ba56dd7cece7b801a896d64f3a8f6398/.github/ISSUE_TEMPLATE/1-bug-report.yml#L13)):*
> ```YAML
> 
>         **IMPORTANT**: Please do not post general questions here, the issue tracker is for bugs and feature requests only. If you have a question, please either:
>              - Open [a discussion thread](https://github.com/gramineproject/gramine/discussions)
> ```

Maybe we should point it to `general` category? Currently we mostly have meeting notes there.
___
*[`.github/ISSUE_TEMPLATE/1-bug-report.yml` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/951#-ND_MAgU4zx4rMpOuxw8:-ND_MAgV3rXSqfBpB6K5:bbyuunt) ([raw file](https://github.com/gramineproject/gramine/blob/1b0962f6ba56dd7cece7b801a896d64f3a8f6398/.github/ISSUE_TEMPLATE/1-bug-report.yml#L23)):*
> ```YAML
>     attributes:
>       label: Steps to reproduce
>       description: '**@@@ PLEASE ENSURE THAT THE ISSUE REPRODUCES ON THE CURRENT MASTER BRANCH @@@**'
> ```

Do we need these `@@@`? They were just to make this more visible, but with the new layout, I'm not sure it's needed anymore.
Not blocking

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: 2 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`.github/ISSUE_TEMPLATE/1-bug-report.yml` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/951#-ND_MQarDt9hnZQtSCWG:-NDbZHa-4lBmqZt0mG-W:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1b0962f6ba56dd7cece7b801a896d64f3a8f6398/.github/ISSUE_TEMPLATE/1-bug-report.yml#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe we should point it to `general` category? Currently we mostly have meeting notes there.
</blockquote></details>

Done.
___
*[`.github/ISSUE_TEMPLATE/1-bug-report.yml` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/951#-ND_MAgU4zx4rMpOuxw8:-NDbZJYU1nXsEQMgwcOh:b1rfut2) ([raw file](https://github.com/gramineproject/gramine/blob/1b0962f6ba56dd7cece7b801a896d64f3a8f6398/.github/ISSUE_TEMPLATE/1-bug-report.yml#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we need these `@@@`? They were just to make this more visible, but with the new layout, I'm not sure it's needed anymore.
Not blocking
</blockquote></details>

I can remove, wasn't sure whether to keep or not.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`.github/ISSUE_TEMPLATE/1-bug-report.yml` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/951#-ND_MQarDt9hnZQtSCWG:-NDbnv0O8tFX2i8nhXh7:b-k6q22d) ([raw file](https://github.com/gramineproject/gramine/blob/1b0962f6ba56dd7cece7b801a896d64f3a8f6398/.github/ISSUE_TEMPLATE/1-bug-report.yml#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done what? I don't see a change. Borys asked to change to `https://github.com/gramineproject/gramine/discussions/categories/general`.

Looks like you only applied the change in `config.yml`
___
*[`.github/ISSUE_TEMPLATE/1-bug-report.yml` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/951#-ND_MAgU4zx4rMpOuxw8:-NDbo3BU6MbMH9sab8l6:b-imsclg) ([raw file](https://github.com/gramineproject/gramine/blob/1b0962f6ba56dd7cece7b801a896d64f3a8f6398/.github/ISSUE_TEMPLATE/1-bug-report.yml#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I can remove, wasn't sure whether to keep or not.
</blockquote></details>

Yes, I also didn't like these `@@@`. I suggest to remove.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`.github/ISSUE_TEMPLATE/1-bug-report.yml` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/951#-ND_MQarDt9hnZQtSCWG:-NDbu-se26eIDb5kX53k:b-ixhtm6) ([raw file](https://github.com/gramineproject/gramine/blob/1b0962f6ba56dd7cece7b801a896d64f3a8f6398/.github/ISSUE_TEMPLATE/1-bug-report.yml#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done what? I don't see a change. Borys asked to change to `https://github.com/gramineproject/gramine/discussions/categories/general`.

Looks like you only applied the change in `config.yml`
</blockquote></details>

You mean to update the preview in my test repo? Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`.github/ISSUE_TEMPLATE/1-bug-report.yml` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/951#-ND_MQarDt9hnZQtSCWG:-NDc1imYDYcfbIO1_TaR:b-h7c3xh) ([raw file](https://github.com/gramineproject/gramine/blob/1b0962f6ba56dd7cece7b801a896d64f3a8f6398/.github/ISSUE_TEMPLATE/1-bug-report.yml#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You mean to update the preview in my test repo? Done.
</blockquote></details>

No, I mean here, in the `Open a discussion thread` -- do you want to jump to Discussions or to more specific General Discussions?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`.github/ISSUE_TEMPLATE/1-bug-report.yml` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/951#-ND_MQarDt9hnZQtSCWG:-NDc_t7D6dDsIVf2XlIH:bmeq8at) ([raw file](https://github.com/gramineproject/gramine/blob/1b0962f6ba56dd7cece7b801a896d64f3a8f6398/.github/ISSUE_TEMPLATE/1-bug-report.yml#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, I mean here, in the `Open a discussion thread` -- do you want to jump to Discussions or to more specific General Discussions?
</blockquote></details>

Yes, you updated only one link (the one where this comment is, is still old)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/951)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
