### PR TITLE
[PAL] Refactor `pal_files.c` code (trivial changes)

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Some trivial changes which I wanted to do long time ago.

Should be useful before we start real work on refactoring Trusted Files.

## How to test this PR? 

Existing tests are enough. No functional changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: 0 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/src/host/linux/pal_files.c` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-Nrih52e1CGGnvaNFBKt:-Nrih52e1CGGnvaNFBKu:b-gixyki) ([raw file](https://github.com/gramineproject/gramine/blob/63ee38d5eb28f5a880a973c28de7be6f0dc6f290/pal/src/host/linux/pal_files.c#L161)):*
> ```C
>     if (ret < 0)
>         return (ret == -EINVAL || ret == -EBADF) ? -PAL_ERROR_BADHANDLE
>                                                  : -PAL_ERROR_DENIED;
> ```

FYI: These manual UNIX-to-PAL error conversions are from the times when we didn't have `unix_to_pal_error()` function.
___
*[`pal/src/host/linux/pal_files.c` line 381 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-NrihEga8EVB-1RkbXDp:-NrihEgb8yEDmOVmoxt6:b-rik2pq) ([raw file](https://github.com/gramineproject/gramine/blob/2cd13c19efa62c8bc7ff07a89845cceee4ea8780/pal/src/host/linux/pal_files.c#L381)):*
> ```C
>     .attrsetbyhdl   = &file_attrsetbyhdl,
>     .rename         = &file_rename,
> };
> ```

FYI: I consider it much more readable to have these global callback lists at the very end of the file.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 106 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-NrihLqqEftoguVy_WEc:-NrihLqr4vzdpH4ran9H:bkex73e) ([raw file](https://github.com/gramineproject/gramine/blob/63ee38d5eb28f5a880a973c28de7be6f0dc6f290/pal/src/host/linux-sgx/pal_files.c#L106)):*
> ```C
>         *handle = hdl;
>         return 0;
>     }
> ```

FYI: This was 100% duplicate code, see below.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 434 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-NrihTCR0lL1zcsM08PC:-NrihTCR0lL1zcsM08PD:b-5sy18p) ([raw file](https://github.com/gramineproject/gramine/blob/63ee38d5eb28f5a880a973c28de7be6f0dc6f290/pal/src/host/linux-sgx/pal_files.c#L434)):*
> ```C
>         ret = -PAL_ERROR_INVAL;
>         goto out;
>     }
> ```

FYI: The `path = malloc()` snippet was left from the times when we had Protected/Encrypted Files implemented in PAL. When we moved them to the Common + LibOS code, we forgot to remove this snippet. Now it's completely unused so I remove it.
___
*[`pal/src/host/linux-sgx/pal_host.h` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-NriheLf2KxyJCgd33cG:-NriheLf2KxyJCgd33cH:bekrle3) ([raw file](https://github.com/gramineproject/gramine/blob/2cd13c19efa62c8bc7ff07a89845cceee4ea8780/pal/src/host/linux-sgx/pal_host.h#L52)):*
> ```objc
>             PAL_IDX fd;
>             char* realpath;
>             size_t size;
> ```

FYI: Renamed `handle.file.total` to a more understandable `handle.file.size`

**Review by llly — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_files.c` line 396 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-NrmzyEa5YgV4MZy6Hrg:-NrmzNpHB3aKPrvjjkWQ:b-8x6php) ([raw file](https://github.com/gramineproject/gramine/blob/2cd13c19efa62c8bc7ff07a89845cceee4ea8780/pal/src/host/linux-sgx/pal_files.c#L396)):*
> ```C
> 
> static int file_attrsetbyhdl(PAL_HANDLE handle, PAL_STREAM_ATTR* attr) {
>     int fd  = handle->file.fd;
> ```

You removed `int fd = handle->file.fd;` in most functions but some are left.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: 2 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux/pal_files.c` line 175 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-Ns4o5R_-JSee-Mqs3TE:-Ns4o5R_-JSee-Mqs3TF:b-d7x3av) ([raw file](https://github.com/gramineproject/gramine/blob/2cd13c19efa62c8bc7ff07a89845cceee4ea8780/pal/src/host/linux/pal_files.c#L175)):*
> ```C
> static int file_attrsetbyhdl(PAL_HANDLE handle, PAL_STREAM_ATTR* attr) {
>     int ret = DO_SYSCALL(fchmod, handle->file.fd, attr->share_flags);
>     return ret < 0 ? unix_to_pal_error(ret) : ret;
> ```

Regarding this pattern of changes in this whole PR: I'd prefer to return 0 instead of `ret` on success, just in case one of the syscalls has weird semantics and returns >= 0.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_files.c` line 112 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-Ns5H3Gt3UWN9pyIFOAO:-Ns5H3Gu32B9yi6HL-p8:b-vi36g9) ([raw file](https://github.com/gramineproject/gramine/blob/2cd13c19efa62c8bc7ff07a89845cceee4ea8780/pal/src/host/linux-sgx/pal_files.c#L112)):*
> ```C
>     }
> 
>     /* at this point, we work with a trusted or allowed file */
> ```

Not just trusted? Right above you have:

```C
    if (!tf) {
        *handle = hdl;
        return 0;
    }
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @llly and @mkow)

___
*[`pal/src/host/linux/pal_files.c` line 175 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-Ns4o5R_-JSee-Mqs3TE:-Ns7TQK4BUoqG5v9cY-L:b5gel6n) ([raw file](https://github.com/gramineproject/gramine/blob/2cd13c19efa62c8bc7ff07a89845cceee4ea8780/pal/src/host/linux/pal_files.c#L175)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Regarding this pattern of changes in this whole PR: I'd prefer to return 0 instead of `ret` on success, just in case one of the syscalls has weird semantics and returns >= 0.
</blockquote></details>

Done. Everywhere except `file_read` and `file_write`, where ret is equal to the number of bytes received/sent.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 112 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-Ns5H3Gt3UWN9pyIFOAO:-Ns7QmTW1hxwlDSaKT_5:b97wupp) ([raw file](https://github.com/gramineproject/gramine/blob/2cd13c19efa62c8bc7ff07a89845cceee4ea8780/pal/src/host/linux-sgx/pal_files.c#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not just trusted? Right above you have:

```C
    if (!tf) {
        *handle = hdl;
        return 0;
    }
```
</blockquote></details>

`tf` means "allowed or trusted file". There are also "encrypted/protected files" -- those do NOT have a `tf`.

Confusing? Yes: https://github.com/gramineproject/gramine/blob/fac30bc3511ce0ac3daaa514fa36cd0f30f17baf/pal/src/host/linux-sgx/enclave_tf_structs.h#L26-L28

So the current code is correct, though un-readable :(
___
*[`pal/src/host/linux-sgx/pal_files.c` line 396 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-NrmzyEa5YgV4MZy6Hrg:-Ns7ReLw-jgx1QiXA6hN:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/2cd13c19efa62c8bc7ff07a89845cceee4ea8780/pal/src/host/linux-sgx/pal_files.c#L396)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

You removed `int fd = handle->file.fd;` in most functions but some are left.
</blockquote></details>

Done

**Review by llly — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`pal/src/host/linux-sgx/pal_files.c` line 112 at r1](https://reviewable.io/reviews/gramineproject/gramine/1790#-Ns5H3Gt3UWN9pyIFOAO:-Ns91Ldp2VwwE02qHOiw:b-jqj1gj) ([raw file](https://github.com/gramineproject/gramine/blob/2cd13c19efa62c8bc7ff07a89845cceee4ea8780/pal/src/host/linux-sgx/pal_files.c#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`tf` means "allowed or trusted file". There are also "encrypted/protected files" -- those do NOT have a `tf`.

Confusing? Yes: https://github.com/gramineproject/gramine/blob/fac30bc3511ce0ac3daaa514fa36cd0f30f17baf/pal/src/host/linux-sgx/enclave_tf_structs.h#L26-L28

So the current code is correct, though un-readable :(
</blockquote></details>

ugh...

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_files.c` line 356 at r3](https://reviewable.io/reviews/gramineproject/gramine/1790#-NsBBU6fBfAnPI4KxNZ7:-NsBBU6fBfAnPI4KxNZ8:b-naekdr) ([raw file](https://github.com/gramineproject/gramine/blob/19978fc2cd56b3e0cd37f345ad6d226bdb8c5372/pal/src/host/linux-sgx/pal_files.c#L356)):*
> ```C
> 
> static int file_flush(PAL_HANDLE handle) {
>     ocall_fsync(handle->file.fd);
> ```

Any speicial reason that the return value is not checked here?



_Code quote:_
```C
ocall_fsync(handle->file.fd);
```

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin, @llly, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_files.c` line 356 at r3](https://reviewable.io/reviews/gramineproject/gramine/1790#-NsBBU6fBfAnPI4KxNZ7:-NsCZGu87xTmSLgk2Ju2:bwvlf45) ([raw file](https://github.com/gramineproject/gramine/blob/19978fc2cd56b3e0cd37f345ad6d226bdb8c5372/pal/src/host/linux-sgx/pal_files.c#L356)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Any speicial reason that the return value is not checked here?
</blockquote></details>

Done. I first didn't want to modify the original code, but you're right, let's just fix it now.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1790)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
