### PR TITLE
Dockerfile optimization

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Apply the good practice in our Dockerfile.
- clear the apt cache files after installation [DL3009](https://github.com/codacy/codacy-hadolint/blob/master/codacy-hadolint/docs/description/DL3009.md)
- execute update and install in the same "RUN" command. Docker caches each RUN statement. This means that the `apt update` and `apt install` can get unsynchronized, and `apt install` can report that some packages are missing.

## How to test this PR? 

```
docker build
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1583)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1583)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1583#-NfoTic34T6ZidRiM4E3):*
`installation` (typo)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1583)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1583)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1583)* status: all files reviewed, all discussions resolved, "squash! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1583)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
