### PR TITLE
[Docs] Move "Management Team" to a separate file

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This is in preparation for the bigger reorganization of documentation.

Extracted from https://github.com/gramineproject/gramine/pull/1241.

## How to test this PR? 

I created a RTD job to see the rendering: https://gramine.readthedocs.io/en/dimakuv-docs-mv-management-team/management-team.html#the-procedure-for-adding-and-removing-maintainers. Notice the "Management Team" menu. Compare with our classic: https://gramine.readthedocs.io/

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1347)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1347)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Documentation/index.rst` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/1347#-NVTnYeF8PLhEVWNkRql:-NVTnYeF8PLhEVWNkRqm:bqcjahi) ([raw file](https://github.com/gramineproject/gramine/blob/2a1edd76ecfa0bb3db8a36e4af47aeb58b317918/Documentation/index.rst#L124)):*
> ```reStructuredText
> 
> .. toctree::
>    :caption: Resources
> ```

FYI: This item will have more sub-items in a later PR (it will also contains Glossary and Gramine Users)

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1347)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1347)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1347)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1347)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1347)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
