### PR TITLE
[LibOS] Check read/write/except set buffers on `select`

### LINKED ISSUE #1110: [LibOS] Missing checks on buffers in `select` and `pselect6` syscalls
### Description of the problem

There are no checks on the accessability (RW access) of buffers `read_set`, `write_set` and `except_set` in system calls `select` and `pselect6`.

Here is the relevant snippet of `select` implementation: https://github.com/gramineproject/gramine/blob/cc9175d472a96914117ae0c1ca1bcf920452a75b/libos/src/sys/libos_poll.c#L332-L345

Here is the relevant snippet of `pselect6` implementation: https://github.com/gramineproject/gramine/blob/cc9175d472a96914117ae0c1ca1bcf920452a75b/libos/src/sys/libos_poll.c#L360-L384

We must have checks against the user-provided size `nfds` of each of these three buffers, and return `EFAULT` if some buffers are inaccessible for write. Similar to this: https://github.com/gramineproject/gramine/blob/cc9175d472a96914117ae0c1ca1bcf920452a75b/libos/src/sys/libos_poll.c#L208-L209

### Gramine commit hash

cc9175d472a96914117ae0c1ca1bcf920452a75b

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Fixes #1110 

## How to test this PR? 

CI is enough.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)

### CODE REVIEW

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/sys/libos_poll.c` line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVVq6YAHreQAcRo5op:-NLVVq6YAHreQAcRo5oq:bvrbwxh) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L332)):*
> ```C
> }
> 
> long libos_syscall_select(int nfds, fd_set* read_set, fd_set* write_set, fd_set* except_set,
> ```

Should we check if `nfds` isn't negative?



_Code quote:_
```C
int nfds
```
___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVPJ3F7ZEesH6M3xW-:-NLVPJ3F7ZEesH6M3xW0:b8gfjyh) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
> ```C
> long libos_syscall_select(int nfds, fd_set* read_set, fd_set* write_set, fd_set* except_set,
>                           struct __kernel_timeval* tv) {
>     size_t set_len = UDIV_ROUND_UP(nfds, BITS_IN_TYPE(fd_set));
> ```

It took me a moment to understand this part.
Maybe it's worth documenting it in commit or comment?
Or its just my unawareness.
Dunno.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @oshogbo)

___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVPJ3F7ZEesH6M3xW-:-NLW2T7-EiMqBuQ2S4pb:b-6v8ekh) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It took me a moment to understand this part.
Maybe it's worth documenting it in commit or comment?
Or its just my unawareness.
Dunno.
</blockquote></details>

For sure I'd at least change the name to `set_byte_size`, "set length" is misleading, as the number of elements in this set is `nfds`, not `UDIV_ROUND_UP(nfds, BITS_IN_TYPE(fd_set))`.
___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLW3Ab05c2FX9FmnT9j:-NLW3Ab05c2FX9FmnT9k:bid1es4) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
> ```C
> long libos_syscall_select(int nfds, fd_set* read_set, fd_set* write_set, fd_set* except_set,
>                           struct __kernel_timeval* tv) {
>     size_t set_len = UDIV_ROUND_UP(nfds, BITS_IN_TYPE(fd_set));
> ```

Isn't this wrong? Why are you taking the size of the whole structure?



_Code quote:_
```C
BITS_IN_TYPE(fd_set)
```
___
*[`libos/src/sys/libos_poll.c` line 372 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLW3JHB-LvhHFrxaydD:-NLW3JHB-LvhHFrxaydE:b-tl63l6) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L372)):*
> ```C
> 
> long libos_syscall_pselect6(int nfds, fd_set* read_set, fd_set* write_set, fd_set* except_set,
>                             struct __kernel_timespec* tsp, void* _sigmask_argpack) {
> ```

ditto x3

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/src/sys/libos_poll.c` line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVVq6YAHreQAcRo5op:-NLWWIuxBSpyZVucOvMK:b-rnuxor) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L332)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Should we check if `nfds` isn't negative?
</blockquote></details>

Done.

We actually did this in the common func `do_select()`. But I moved it now into callers for two reasons:
1. Now we use `nfds` for this new memory-accessible check
2. It doesn't make sense to have such syscall checks not in outer syscall emulations.
___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVPJ3F7ZEesH6M3xW-:-NLWWfC95xbxvwsZzJt8:bvj0typ) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
Done.

> Maybe it's worth documenting it in commit or comment?

Is it clearer now that I'm checking `fd_set::fds_bits`?

> For sure I'd at least change the name to `set_byte_size` ...

You're incorrect. This is *not* the size of the struct in bytes. It's the length of the `fd_set[]` (aka `fd_set*`) array provided in the func args.

Each `fd_set` is 128 bytes in size (which allows to accomodate 1024 bits, i.e. 1024 FDs). See Linux source: https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/posix_types.h#L26

So I'm calculating the expected length of the array of `fd_set` items. E.g., if `nfds = 1024`, then the length must be `1`. If `nfds = 1025`, then the length must be `2`.
___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLW3Ab05c2FX9FmnT9j:-NLWXZI10LhmPILUEiIe:bpsr6d2) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this wrong? Why are you taking the size of the whole structure?
</blockquote></details>

I renamed the variable and use `fds_bits` field now. Hopefully this is better?
___
*[`libos/src/sys/libos_poll.c` line 372 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLW3JHB-LvhHFrxaydD:-NLWXgcMBgT5CuR5lytL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L372)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto x3
</blockquote></details>

Done.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVPJ3F7ZEesH6M3xW-:-NLX3I-x3BCiiHlHBRyt:b-bupb50) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
> Is it clearer now that I'm checking ?

To be honest, I don't think that the naming changes a lot here, as I think this is quite tricky part in `select`. I still won't mind a small introduction to it in the comment for further reference - but it's nice to have - not blocking.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVPJ3F7ZEesH6M3xW-:-NL_ET8X3NecdVxaP67s:b-iaikx4) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> Is it clearer now that I'm checking ?

To be honest, I don't think that the naming changes a lot here, as I think this is quite tricky part in `select`. I still won't mind a small introduction to it in the comment for further reference - but it's nice to have - not blocking.
</blockquote></details>

Done. The comment is a bit too long now, please tell me how to shorten it (if needed).

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVPJ3F7ZEesH6M3xW-:-NLrhwOX5u_5raMyPzib:b4p0uiw) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. The comment is a bit too long now, please tell me how to shorten it (if needed).
</blockquote></details>

Still wasn't too clear for me, in "that typically has a size of 128B" that this is a static size of an array inlined in the struct, not a pointer. This "typically" sounds like it was a pointer to a dynamically allocated array or the struct could be overallocated.
___
*[`libos/src/sys/libos_poll.c` line 336 at r3](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLrgErTDjuw4-M8npvR:-NLrgErTDjuw4-M8npvS:btzng12) ([raw file](https://github.com/gramineproject/gramine/blob/89b08c6c7e9349dd11f3494088e6248d5e9a8ffa/libos/src/sys/libos_poll.c#L336)):*
> ```C
>     /* Each of `read_set`, `write_set` and `except_set` is an array of fd_set items; each fd_set
>      * item has a single field `fd_set::fds_bits` that typically has a size of 128B (which allows to
>      * accomodate 1024 bits, i.e. 1024 file descriptors). Therefore we calculate how many fd_set
> ```

as usual :upside_down_face: 



_Suggestion:_
```C
accommodate
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVPJ3F7ZEesH6M3xW-:-NLu2dBkEDAr8DTmnBoS:bqsas9i) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
> This "typically" sounds like it was a pointer to a dynamically allocated array or the struct could be overallocated.

I don't understand your comment. Do you want me to remove the word "typically" from the text?

Originally, I added this word "typically" because in this PR, there is no assumption that the size is 128B -- it can be anything. But for illustration purposes, I used the current implementation in the Linux kernel, which has `fd_set::fds_bits` being 128B in size.
___
*[`libos/src/sys/libos_poll.c` line 336 at r3](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLrgErTDjuw4-M8npvR:-NLu39zc2kAIYgc6eSk5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/89b08c6c7e9349dd11f3494088e6248d5e9a8ffa/libos/src/sys/libos_poll.c#L336)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

as usual :upside_down_face: 
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVPJ3F7ZEesH6M3xW-:-NLwZaqo6tAt2ss7HWNK:b-f76s0) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
`a single field` -> `a single inline array of constant size` maybe?

> being 128B in size

I think this is true only on x64? But we can leave the current version of this part, as it has "typically" in it.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/sys/libos_poll.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1111#-NLVPJ3F7ZEesH6M3xW-:-NLz08X_2BjoUCEPk--u:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/04838db216ddb5921d47e278b9895e656ec4f796/libos/src/sys/libos_poll.c#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`a single field` -> `a single inline array of constant size` maybe?

> being 128B in size

I think this is true only on x64? But we can leave the current version of this part, as it has "typically" in it.
</blockquote></details>

Done

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by oshogbo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111#-:-NM0tLnjA5l3S5kVrvwi:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1111)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
