### PR TITLE
[LibOS] Clean up checkpoint/restore of a VMA

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This is purely cosmetic (removing dead code, improving comments). No functional changes (and if there are, it is my bug).

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/413)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/413)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 1284 at r1](https://reviewable.io/reviews/gramineproject/gramine/413#-Mw1wVW7EDvh6JGwRqsn:-Mw1wVW7EDvh6JGwRqso:bnzt6rv) ([raw file](https://github.com/gramineproject/gramine/blob/3880ca1213f0d26c0f0d278a9d8adb211e471770/LibOS/shim/src/bookkeep/shim_vma.c#L1284)):*
> ```C
> 
>         ADD_CP_FUNC_ENTRY(off);
>         ADD_CP_ENTRY(ADDR, (void*)remap_in_child);
> ```

FYI: This is an ugly bool->pointer cast, but I don't know how to make it better.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/413)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/413#-Mw2NXxQ7zlLeIr7V1g8:-Mw2NXxRDMpJTP9JbCKG:b-byts1f) (no related file):*
Blocking on @boryspoplawski's review, he knows this part much better than me and should review it.

---

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/413)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/413#-Mw2NXxQ7zlLeIr7V1g8:-Mw9xELd59nA6_2Q87OA:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Blocking on @boryspoplawski's review, he knows this part much better than me and should review it.
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 1236 at r1](https://reviewable.io/reviews/gramineproject/gramine/413#-MwA0hdk2gSe2ALWjFNl:-MwA0hdk2gSe2ALWjFNm:bsf5vb) ([raw file](https://github.com/gramineproject/gramine/blob/3880ca1213f0d26c0f0d278a9d8adb211e471770/LibOS/shim/src/bookkeep/shim_vma.c#L1236)):*
> ```C
>             DO_CP(handle, vma->file, &new_vma->file);
> 
>         bool remap_in_child = true;
> ```

This is counterintuitive - `remap_in_child` is `true`, e.g. when `vma->flags & VMA_UNMAPPED` and we do not perform any mapping in child.
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 1236 at r1](https://reviewable.io/reviews/gramineproject/gramine/413#-MwA6K5_AiCm_h81WF5H:-MwA6K5_AiCm_h81WF5I:b-ruc9t3) ([raw file](https://github.com/gramineproject/gramine/blob/3880ca1213f0d26c0f0d278a9d8adb211e471770/LibOS/shim/src/bookkeep/shim_vma.c#L1236)):*
> ```C
>             DO_CP(handle, vma->file, &new_vma->file);
> 
>         bool remap_in_child = true;
> ```

Maybe `remap_from_file`? Just an idea, not blocking.
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 1284 at r1](https://reviewable.io/reviews/gramineproject/gramine/413#-Mw1wVW7EDvh6JGwRqsn:-MwA6dCm3Ip4TIbOXdty:bv2e3dp) ([raw file](https://github.com/gramineproject/gramine/blob/3880ca1213f0d26c0f0d278a9d8adb211e471770/LibOS/shim/src/bookkeep/shim_vma.c#L1284)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: This is an ugly bool->pointer cast, but I don't know how to make it better.
</blockquote></details>

From what I see it's kept in `uintptr_t` (and there is a cast in this macro).
Please just cast directly to `uintptr_t` (it's not needed, but let's be explicit).

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/413)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/413#-Mw2NXxQ7zlLeIr7V1g8:-MwAhfFwA055zvysnIfC:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 1236 at r1](https://reviewable.io/reviews/gramineproject/gramine/413#-MwA6K5_AiCm_h81WF5H:-MwAiYC8C7i6GgTtP7Lp:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/3880ca1213f0d26c0f0d278a9d8adb211e471770/LibOS/shim/src/bookkeep/shim_vma.c#L1236)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe `remap_from_file`? Just an idea, not blocking.
</blockquote></details>

Done
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 1236 at r1](https://reviewable.io/reviews/gramineproject/gramine/413#-MwA0hdk2gSe2ALWjFNl:-MwAjLXC4C7hYcRMJaMy:bgyis9k) ([raw file](https://github.com/gramineproject/gramine/blob/3880ca1213f0d26c0f0d278a9d8adb211e471770/LibOS/shim/src/bookkeep/shim_vma.c#L1236)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is counterintuitive - `remap_in_child` is `true`, e.g. when `vma->flags & VMA_UNMAPPED` and we do not perform any mapping in child.
</blockquote></details>

Done. I added a bit more logic to make it explicit that we require a mapped file-backed VMA.
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 1284 at r1](https://reviewable.io/reviews/gramineproject/gramine/413#-Mw1wVW7EDvh6JGwRqsn:-MwAiZFa4PL18HrrF8AA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3880ca1213f0d26c0f0d278a9d8adb211e471770/LibOS/shim/src/bookkeep/shim_vma.c#L1284)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

From what I see it's kept in `uintptr_t` (and there is a cast in this macro).
Please just cast directly to `uintptr_t` (it's not needed, but let's be explicit).
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/413)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/413)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/413)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/413)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
