### PR TITLE
[Pal,meson] Link Gramine patched mbedTLS statically

### PR DESCRIPTION
**Pull request by kailun-qin**
## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/456#-My7g_ue6PVTH4BlV-D1:-My7g_ue6PVTH4BlV-D2:b-mczf7s) (no related file):*
@woju Could you take a quick look at this PR, as an expert on Meson?

---
___
*[meson.build, line 239 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gQjR4MmTxCJDkjq4:-My7gQjR4MmTxCJDkjq5:bdfb2wk) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/meson.build#L239)):*
> ```Meson
> 
>     mbedtls_proj = subproject('mbedtls-mbedtls-2.26.0')
>     mbedtls_dep = mbedtls_proj.get_variable('mbedtls_dep')
> ```

Is there actually anything that uses this `mbedtls_dep` now? Maybe it can be simply removed now?
___
*[subprojects/packagefiles/mbedtls/meson.build, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gCyBCmW6BLIpDBxq:-My7gCyBCmW6BLIpDBxr:b-5fe0b6) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/meson.build#L70)):*
> ```Meson
>     ],
> 
>     build_by_default: true,
> ```

Why is this option? In the `mbedtls_libs`, there are these two lines instead of this one:
```
    install: true,
    install_dir: get_option('libdir'),
```

@woju What's the difference between these two options?

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7QkzN-UFMdryr_Jn4):*
I think it should be:



_Suggestion:_
```
Link mbedTLS statically to Gramine-provided shared libraries
```
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/meson.build, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7I1G89YqrqEVM8JWH:-My7I1G89YqrqEVM8JWI:b-86xo7r) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/Pal/src/host/Linux-SGX/tools/ra-tls/meson.build#L2)):*
> ```Meson
> libra_tls_inc = include_directories('.')
> ```

Please add a comment somewhere explaining why we need to link mbedtls statically (because ra-tls is loaded dynamically to user's software and we don't want our patched mbedtls to collide with libraries the program already uses).
___
*[subprojects/packagefiles/mbedtls/compile-gramine.sh, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My84Fp18fD4qQ6Y_uBg:-My84Fp18fD4qQ6Y_uBh:b-vvxhjz) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/compile-gramine.sh#L7)):*
> ```Shell
> # Generate position-independent code even for a static library, so that it can be used in
> # Gramine-provided shared libraries
> CFLAGS="$CFLAGS -fPIC"
> ```

Aren't you overwriting the assignment from above?

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/456#-My7g_ue6PVTH4BlV-D1:-My88h2jDanykeuOVQl3:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Could you take a quick look at this PR, as an expert on Meson?
</blockquote></details>

Done.

---
___
*[subprojects/packagefiles/mbedtls/compile-gramine.sh, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My8J3JFAUe8AikBHXr6:-My8J3JGCcY06tUxFy9o:b-sl42lm) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/compile-gramine.sh#L7)):*
> ```Shell
> # Generate position-independent code even for a static library, so that it can be used in
> # Gramine-provided shared libraries
> CFLAGS="$CFLAGS -fPIC"
> ```

Why this is needed? mbedtls adds `-fPIC` on its own: https://github.com/ARMmbed/mbedtls/blob/v2.26.0/library/Makefile#L38
___
*[subprojects/packagefiles/mbedtls/meson.build, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gCyBCmW6BLIpDBxq:-My86eyA2XQ-Bn4fmzXu:b-iteoe) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/meson.build#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this option? In the `mbedtls_libs`, there are these two lines instead of this one:
```
    install: true,
    install_dir: get_option('libdir'),
```

@woju What's the difference between these two options?
</blockquote></details>

`install*` is if you want `.a` files in `/usr/lib`, but IIUC we don't, so it's not here. Without `install`, it might be that they don't get built because ninja won't build things that it judges unneeded (for example, if you unpack the subproject and `meson setup` it directly, no-one uses it). Normally we shouldn't need this, but it doesn't hurt and possibly helps with debugging (I'm not sure about this one, @kailun-qin might confirm).

What I think is wrong, is this `mbedtls_static_libs` is wholly unneed, and you can `mbedtls_static_dep = declare_dependency` off `mbedtl_libs`, if we added respective outputs to `mbedtls_libs`. `SHARED=1` does not disable building static libs: https://github.com/ARMmbed/mbedtls/blob/v2.26.0/library/Makefile#L176-L180

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

___
*[subprojects/packagefiles/mbedtls/compile-gramine.sh, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My8J3JFAUe8AikBHXr6:-My8dpDsDcuZFPn-tpaS:b-y4tj88) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/compile-gramine.sh#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It does so only with `SHARED`, from what I can see for static it's omitted.
</blockquote></details>

Oh, right. So if we remove `SHARED` (see below) this will be needed, or if we build once this will be unneeded. I'll keep this blocked until resolution of that other discussion.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gCyBCmW6BLIpDBxq:-My8cT2bEgzI8lVtUukH:b-u8lod4) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/meson.build#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@woju but I don't think we need to build shared with this PR?
</blockquote></details>

IDK, probably? (see @dimakuv's question elsewhere). If so, this PR should remove shared libs altogether. What's being reviewed is suboptimal, because it compiles mbedtls one time too many.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[subprojects/packagefiles/mbedtls/compile-gramine.sh, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My84Fp18fD4qQ6Y_uBg:-My9Uz344O1F3O21Hwbv:b6tdu3e) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/compile-gramine.sh#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's just appending.
</blockquote></details>

Oh, sorry, I misread it.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7QkzN-UFMdryr_Jn4):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it should be:
</blockquote></details>

Sure, will do.
___
*[meson.build, line 239 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gQjR4MmTxCJDkjq4:-MyAPiMt-0CI4dNtLiVC:bedl2py) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/meson.build#L239)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is there actually anything that uses this `mbedtls_dep` now? Maybe it can be simply removed now?
</blockquote></details>

`LibOS/shim/test/regression/attestation` uses `mbedtls_dep` as well, but I think it's no harm to make it statically linked to mbedtls.

Actually, it's used by `libsgx_utl` (see my change in `Pal/src/host/Linux-SGX/tools/common/meson.build`) so all relevant Gramine tool executables as well. Not sure if we should make this static too.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/meson.build, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7I1G89YqrqEVM8JWH:-MyAQ-jK70jg8awLuFzH:bt1x36r) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/Pal/src/host/Linux-SGX/tools/ra-tls/meson.build#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a comment somewhere explaining why we need to link mbedtls statically (because ra-tls is loaded dynamically to user's software and we don't want our patched mbedtls to collide with libraries the program already uses).
</blockquote></details>

Sure, will do.
___
*[subprojects/packagefiles/mbedtls/compile-gramine.sh, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My8J3JFAUe8AikBHXr6:-MyARMcw11TrN464zHRq:b-2h2ipj) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/compile-gramine.sh#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Oh, right. So if we remove `SHARED` (see below) this will be needed, or if we build once this will be unneeded. I'll keep this blocked until resolution of that other discussion.
</blockquote></details>

Can be removed accordingly as we build once with `SHARED`.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gCyBCmW6BLIpDBxq:-MyAQ4J68mElGGhnxJCq:b-kl5ssh) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/meson.build#L70)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IDK, probably? (see @dimakuv's question elsewhere). If so, this PR should remove shared libs altogether. What's being reviewed is suboptimal, because it compiles mbedtls one time too many.
</blockquote></details>

We still need to build shared as it's explicitly linked by CI-Examples/ra-tls-mbedtls and CI-Examples/ra-tls-secret-prov, https://github.com/gramineproject/gramine/blob/29f127542a4d81a8b461f05a4b36344d89bed3fa/CI-Examples/ra-tls-mbedtls/Makefile#L72.

But as @woju pointed out, `mbedtls_static_libs` is not necessary if we add addional outputs to `mbedtls_libs` (as `SHARED=1` does not disable building static libs).

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin, @mkow, and @woju)

___
*[meson.build, line 239 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gQjR4MmTxCJDkjq4:-MyBfn7U4iEcMgubm4Z3:b-5qv0tv) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/meson.build#L239)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

`LibOS/shim/test/regression/attestation` uses `mbedtls_dep` as well, but I think it's no harm to make it statically linked to mbedtls.

Actually, it's used by `libsgx_utl` (see my change in `Pal/src/host/Linux-SGX/tools/common/meson.build`) so all relevant Gramine tool executables as well. Not sure if we should make this static too.
</blockquote></details>

We can definitely make all these statically-linked too. All these internal Gramine tools/tests should use statically-linked mbedTLS, in my opinion.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gCyBCmW6BLIpDBxq:-MyBgWVI7R_C9eNtaHEb:b1hf55p) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/meson.build#L70)):*
> We still need to build shared as it's explicitly linked by CI-Examples/ra-tls-mbedtls and CI-Examples/ra-tls-secret-prov

Yeah, for the examples we need to build shared libs.

But I agree with everyone that we shouldn't build mbedTLS twice, we should have just one build target that creates both shared and static libs.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: 1 of 11 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[meson.build, line 239 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gQjR4MmTxCJDkjq4:-MyBpp-l2WNT9YK6mWrP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/meson.build#L239)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We can definitely make all these statically-linked too. All these internal Gramine tools/tests should use statically-linked mbedTLS, in my opinion.
</blockquote></details>

Done.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/456#-My7gCyBCmW6BLIpDBxq:-MyBpsPVAQjpTvpRROam:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65abb176dcfb285fce7e6b67c630bc5ab19c317b/subprojects/packagefiles/mbedtls/meson.build#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> We still need to build shared as it's explicitly linked by CI-Examples/ra-tls-mbedtls and CI-Examples/ra-tls-secret-prov

Yeah, for the examples we need to build shared libs.

But I agree with everyone that we shouldn't build mbedTLS twice, we should have just one build target that creates both shared and static libs.
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

___
*[Pal/src/host/Linux-SGX/tools/ias-request/meson.build, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/456#-MyBqeED2UyJ4EH9d6Xl:-MyBqeED2UyJ4EH9d6Xm:b-70zyr4) ([raw file](https://github.com/gramineproject/gramine/blob/3499d915b373ed48c8dd62d0d315e1df2bd909dc/Pal/src/host/Linux-SGX/tools/ias-request/meson.build#L6)):*
> ```Meson
>     dependencies: [
>         sgx_util_dep,
>         mbedtls_dep,
> ```

This dependency was redundant? Well, I guess this dep is already incorporated in `sgx_util_dep`.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/meson.build, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/456#-MyBqzBU0GkBIEqWZQwc:-MyBqzBU0GkBIEqWZQwd:b-h1lnnd) ([raw file](https://github.com/gramineproject/gramine/blob/e44bdd0a94a449fe9444ed85ff1c78b966c85996/Pal/src/host/Linux-SGX/tools/ra-tls/meson.build#L2)):*
> ```Meson
> # Link mbedtls statically to Gramine-provided libraries, e.g., RA-TLS and secret
> # provisioning libraries.
> ```

`Secret Provisioning libraries` (capital letters please)
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/meson.build, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/456#-MyBqrRZ-SZVmOFhX2dQ:-MyBqrRZ-SZVmOFhX2dR:b3udj7z) ([raw file](https://github.com/gramineproject/gramine/blob/e44bdd0a94a449fe9444ed85ff1c78b966c85996/Pal/src/host/Linux-SGX/tools/ra-tls/meson.build#L4)):*
> ```Meson
> # provisioning libraries.
> # This is because they are loaded dynamically to users' software and we don't
> # want our patched mbedtls to collide with libraries the program already uses.
> ```

There is no need to start `This is because` from the new line -- this is all one paragraph.

Also, please re-wrap to 100 char limit.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Pal/src/host/Linux-SGX/tools/ias-request/meson.build, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/456#-MyBqeED2UyJ4EH9d6Xl:-MyBuLSvCtnKNmDVmflR:b-ne685n) ([raw file](https://github.com/gramineproject/gramine/blob/3499d915b373ed48c8dd62d0d315e1df2bd909dc/Pal/src/host/Linux-SGX/tools/ias-request/meson.build#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This dependency was redundant? Well, I guess this dep is already incorporated in `sgx_util_dep`.
</blockquote></details>

Yep, exactly.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/meson.build, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/456#-MyBqzBU0GkBIEqWZQwc:-MyBuS6l8kGcw6i42g80:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e44bdd0a94a449fe9444ed85ff1c78b966c85996/Pal/src/host/Linux-SGX/tools/ra-tls/meson.build#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Secret Provisioning libraries` (capital letters please)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/meson.build, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/456#-MyBqrRZ-SZVmOFhX2dQ:-MyBuSfc63-qvrZidY51:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e44bdd0a94a449fe9444ed85ff1c78b966c85996/Pal/src/host/Linux-SGX/tools/ra-tls/meson.build#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need to start `This is because` from the new line -- this is all one paragraph.

Also, please re-wrap to 100 char limit.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — DISMISSED** [review]
> Reviewed 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 9 of 10 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/456#-MyIVLi05Frr3YnAPKjT:-MyIXYnC5V5OjXVByush:bol5fkr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We shouldn't use this PR as is. It breaks our ability to switch between Gramine commits (before this PR and after this PR).

This is because we modify `subprojects/packagefiles/mbedtls/meson.build`. Subprojects are not correctly updated in Meson when we switch between Gramine commits, so mbedTLS is not getting rebuilt as expected.

We had the same problem when we updated Glibc. @pwmarcz I tried to use your workaround (with the `-1` suffix) but failed. Well, I didn't try much :) Could you give a hint on how to implement painless switching of mbedTLS subprojects, or maybe even take over this PR to implement this?
</blockquote></details>

Oh. That's unfortunate.

The workaround would be basically renaming the subproject to `mbedtls-mbedtls-2.26.0-1`: rename the wrap file, and change all references to it.

However, you also need to make sure that the sources are being extracted to a directory with `-1` suffix. Unfortunately the upstream tarball already has a top-level directory without such suffix, and we cannot get rid of it. Best we can do is tell Meson to extract to `mbedtls-mbedtls-2.26.0-1/mbedtls-mbedtls-2.26.0`, and adjust build scripts accordingly.

See 1fd075ee309af308d75a474156518f3b9807567d for the workaround as applied to glibc: `lead_directory_missing = true` in the wrap file, and the changes in `meson.build` in glibc.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/456#-MyIVLi05Frr3YnAPKjT:-MyMJz_R4PbyFVAYIlej:bl7eyvo) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oh. That's unfortunate.

The workaround would be basically renaming the subproject to `mbedtls-mbedtls-2.26.0-1`: rename the wrap file, and change all references to it.

However, you also need to make sure that the sources are being extracted to a directory with `-1` suffix. Unfortunately the upstream tarball already has a top-level directory without such suffix, and we cannot get rid of it. Best we can do is tell Meson to extract to `mbedtls-mbedtls-2.26.0-1/mbedtls-mbedtls-2.26.0`, and adjust build scripts accordingly.

See 1fd075ee309af308d75a474156518f3b9807567d for the workaround as applied to glibc: `lead_directory_missing = true` in the wrap file, and the changes in `meson.build` in glibc.
</blockquote></details>

Thanks Pawel. I implemented a new fixup commit that applies the approach from https://github.com/gramineproject/gramine/commit/1fd075ee309af308d75a474156518f3b9807567d.

All, please review this fixup. I tested it manually, by switching between this and other PRs, and it works nicely for me.

---

**Review by mkow — DISMISSED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/456)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
