### PR TITLE
[LTP] Add `fcntl14_64` to list of tests with unbufferred output

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
yes

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/642)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/642)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/642)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/642)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/642)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/642#-N4cW6L23Hl6jsfVFthu:-N4cW6L3C1J-gIa4mnzH:b-jtln5h) (no related file):*
> TODO: take a look at the CI output to check that the new test also prints its output (to make sure there's no dumb typo here).

What about this? Did anyone do this?

___

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/642)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/642#-N4cW6L23Hl6jsfVFthu:-N4iRaV2-hoLszdKPws0:b-w7dojd) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> TODO: take a look at the CI output to check that the new test also prints its output (to make sure there's no dumb typo here).

What about this? Did anyone do this?
</blockquote></details>

Yes and it doesn't work - it doesn't print the output for any of the tests. Locally testing it prints only output for `fcntl14`, never for anything else. From what I've debugged so far, `section.name == "DEFAULT"` in most cases, only some of the tests contain the test name there.

___

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/642)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/642#-N4cW6L23Hl6jsfVFthu:-N4iY7JN2AihuQDSJ_GY:bc2fz3) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes and it doesn't work - it doesn't print the output for any of the tests. Locally testing it prints only output for `fcntl14`, never for anything else. From what I've debugged so far, `section.name == "DEFAULT"` in most cases, only some of the tests contain the test name there.
</blockquote></details>

Ok I stashed the fix here. Unfortunately had to force-push and swap the order of commits, but the changes are so small it shouldnt be a problem

___

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/642)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/642#-N4cW6L23Hl6jsfVFthu:-N4idJkL6Gso5vYVnpkw:bde7ywf) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok I stashed the fix here. Unfortunately had to force-push and swap the order of commits, but the changes are so small it shouldnt be a problem
</blockquote></details>

Still does not work on jenkins, I'll continue debugging tomorrow

___

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/642)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/642#-N4cW6L23Hl6jsfVFthu:-N4nRUk10uIcw5lxSwu_:b-m04uyi) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Still does not work on jenkins, I'll continue debugging tomorrow
</blockquote></details>

The culprit is `pytest-xdist` plugin we use to spawn multiple worker threads for pytest (using `-n4`). It basically does not support not capturing stdout/stderr. https://pytest-xdist.readthedocs.io/en/latest/#pytest-xdist: ```Due to how pytest-xdist is implemented, the `-s/--capture=no` option does not work.```
I tried to find some workaround, but this seem to be plain impossible by design (of pytest-xdist).
cc @niedzejkob @woju 

___

**Pull request closed without merging**
