### PR TITLE
[CI] Ubuntu 24.04 and 22.04 part 4/?

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

See #2026 for rationale

## How to test this PR? 

CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2029)

### CODE REVIEW

**Comment by woju** [comment]
Jenkins, test Jenkins-SGX-20.04-apps please

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2029)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/2029#-O9E78I-Dhktptlepl5v):*
`pipe` -> `pipe04`
___
*[`.ci/ubuntu22.04.dockerfile` line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/2029#-O9E5tZEEzUUHj5bR9fC:-O9E5tZEEzUUHj5bR9fD:bgynwm0) ([raw file](https://github.com/gramineproject/gramine/blob/39c0ca9369947e4df0a6d425dc076d7dc5de09ec/.ci/ubuntu22.04.dockerfile#L53)):*
> ```Dockerfile
> # gdb: tested in libos suite
> # ncat: used in scripts/wait_for_server
> # linux-libc-dev: among others, needed to compile busybox (CI-Examples/busybox)
> ```

That's wrong now, after we merged this commit: https://github.com/gramineproject/gramine/commit/e9cab24e3c6530fa5a0d47f6bb4e04d7c0ed0fe9

I don't mind keeping this package, seems important anyway, but I would change the comment to something more generic
___
*[`.ci/ubuntu22.04.dockerfile` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/2029#-O9E6q5t57f8egpH1DmU:-O9E6q5t57f8egpH1DmV:bwuamh2) ([raw file](https://github.com/gramineproject/gramine/blob/39c0ca9369947e4df0a6d425dc076d7dc5de09ec/.ci/ubuntu22.04.dockerfile#L61)):*
> ```Dockerfile
> # sqlite3: CI-Examples/sqlite
> # libsgx-*: CI-Examples/ra-tls-*
> # curl: CI-Examples/ra-tls-secret-prov
> ```

Out of curiosity -- why is this list not sorted?
___
*[`.ci/ubuntu24.04.dockerfile` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/2029#-O9E6SD-3SB41T7pPm2f:-O9E6SD-3SB41T7pPm2g:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/39c0ca9369947e4df0a6d425dc076d7dc5de09ec/.ci/ubuntu24.04.dockerfile#L54)):*
> ```Dockerfile
> # gdb: tested in libos suite
> # ncat: used in scripts/wait_for_server
> # linux-libc-dev: among others, needed to compile busybox (CI-Examples/busybox)
> ```

ditto

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2029)* status: 1 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/2029#-O9E78I-Dhktptlepl5v):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`pipe` -> `pipe04`
</blockquote></details>

Done.
___
*[`.ci/ubuntu22.04.dockerfile` line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/2029#-O9E5tZEEzUUHj5bR9fC:-O9EZFkc0KJUwWL92yhK:b-yqg651) ([raw file](https://github.com/gramineproject/gramine/blob/39c0ca9369947e4df0a6d425dc076d7dc5de09ec/.ci/ubuntu22.04.dockerfile#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's wrong now, after we merged this commit: https://github.com/gramineproject/gramine/commit/e9cab24e3c6530fa5a0d47f6bb4e04d7c0ed0fe9

I don't mind keeping this package, seems important anyway, but I would change the comment to something more generic
</blockquote></details>

No, I think it shouldn't be there at all, if we don't need it.
___
*[`.ci/ubuntu22.04.dockerfile` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/2029#-O9E6q5t57f8egpH1DmU:-O9EZBnT1hzjep6Y5Xff:b2swx97) ([raw file](https://github.com/gramineproject/gramine/blob/39c0ca9369947e4df0a6d425dc076d7dc5de09ec/.ci/ubuntu22.04.dockerfile#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Out of curiosity -- why is this list not sorted?
</blockquote></details>

Historical reason, I've been adding stuff to it. Fixed.
___
*[`.ci/ubuntu24.04.dockerfile` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/2029#-O9E6SD-3SB41T7pPm2f:-O9EZLP8Be0DX-qiiR_s:bs4q9op) ([raw file](https://github.com/gramineproject/gramine/blob/39c0ca9369947e4df0a6d425dc076d7dc5de09ec/.ci/ubuntu24.04.dockerfile#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Ditto.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 5 of 5 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2029)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2029)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 5 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2029)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — DISMISSED** [review]
> Reviewed 5 of 5 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2029)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2029)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2029)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
