### PR TITLE
[LibOS] Fix `readdir` not able to detect directory deletion

### LINKED ISSUE #390: Readir systemcall not able to detect directory deletion while running inside SGX enclave
## Description of the problem
Readir systemcall not able to detect directory deletion while running inside SGX enclave. However, able to detect directory creation.

## Steps to reproduce
 - Please use attached sample program for reproducing this issue.
 - Extract the archive and compile as below.
     o cd subDir_experiments_SGX/Ctest
     o mkdir /tmp/dir_test
     o export GRAMINE_DIR=<Path of Gramine source dir>
     o make clean all SGX=1
     o ./ctest -> This is to run directly on host machine
     o gramine-sgx ctest -> This is to run in SGX enclave
     o This sample program checks the directories in /tmp/dir_test for every 2 secs and displays in the console (for 10 iterations). 
     o In another terminal cd /tmp/dir_test and create / delete directories as below
     o mkdir 1 2 3 4
     o rmdir 3 4

## Expected results
  - Able to detect directory creation & deletion while the program is running.
## Actual results
  - While running in enclave, able to detect only the directory creation and not directory deletion. The deleted directories are also getting read from readdir syscall.
  
## Gramine commit hash
 Tested with Release TAG v1.1
[subDir_experiments_SGX.tar.gz](https://github.com/gramineproject/gramine/files/8024672/subDir_experiments_SGX.tar.gz)

### PR DESCRIPTION
**Pull request by sahason**
Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
This commit fixes the issue of `readdir` not being able to detect directory deletion. When the directories have been deleted the state of those directories is not modified inside gramine and the state remains valid. As a fix, the list of old directory entries is compared with the recently fetched list of directory entries by `readdir`. If an old directory entry is not found in the latest list change the state of that directory entry to `DENTRY_NEGATIVE` and make it invalid.

Fixes #390.

## How to test this PR? 
Follow Readme.txt.
[subDir_experiments_SGX.tar.gz](https://github.com/gramineproject/gramine/files/8124870/subDir_experiments_SGX.tar.gz)

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/425)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/425)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz and @sahason)

___
*[LibOS/shim/src/fs/shim_namei.c, line 657 at r1](https://reviewable.io/reviews/gramineproject/gramine/425#-MwejEHe60rdDE4gByVG:-MwejEHe60rdDE4gByVH:b45zozl) ([raw file](https://github.com/gramineproject/gramine/blob/af67b3a10d8bc419ab67a21ebef0496e3f207a23/LibOS/shim/src/fs/shim_namei.c#L657)):*
> ```C
>         if (removed) {
>             /* Dentry that does not correspond to a real file is still valid. */
>             if (((child->state & DENTRY_VALID) && !(child->state & DENTRY_NEGATIVE)) &&
> ```

Not blocking but we could remove one set of braces (`( ... )`) that surrounds the first two conditions.
___
*[LibOS/shim/src/fs/shim_namei.c, line 658 at r1](https://reviewable.io/reviews/gramineproject/gramine/425#-MwejNyp79W39Vk2u7az:-MwejNyp79W39Vk2u7b-:b-7vdsn1) ([raw file](https://github.com/gramineproject/gramine/blob/af67b3a10d8bc419ab67a21ebef0496e3f207a23/LibOS/shim/src/fs/shim_namei.c#L658)):*
> ```C
>             /* Dentry that does not correspond to a real file is still valid. */
>             if (((child->state & DENTRY_VALID) && !(child->state & DENTRY_NEGATIVE)) &&
>                 (child->fs == child->mount->fs)) {
> ```

@pwmarcz @sahason What exactly does this condition verify? "The child's FS is the same as the mount point's FS of this child". In which cases it can be different? Is it the scenario when the `child` dentry was under this directory, then it was deleted and then re-created but now under another mount (but under the same dir)? I'm confused here.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/425)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 657 at r1](https://reviewable.io/reviews/gramineproject/gramine/425#-MwejEHe60rdDE4gByVG:-Mwfh1ogEalWfi3gt3Ld:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/af67b3a10d8bc419ab67a21ebef0496e3f207a23/LibOS/shim/src/fs/shim_namei.c#L657)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not blocking but we could remove one set of braces (`( ... )`) that surrounds the first two conditions.
</blockquote></details>

Done
___
*[LibOS/shim/src/fs/shim_namei.c, line 658 at r1](https://reviewable.io/reviews/gramineproject/gramine/425#-MwejNyp79W39Vk2u7az:-MwfgPcw1DnxKkO9gXpm:b-9zgrxb) ([raw file](https://github.com/gramineproject/gramine/blob/af67b3a10d8bc419ab67a21ebef0496e3f207a23/LibOS/shim/src/fs/shim_namei.c#L658)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@pwmarcz @sahason What exactly does this condition verify? "The child's FS is the same as the mount point's FS of this child". In which cases it can be different? Is it the scenario when the `child` dentry was under this directory, then it was deleted and then re-created but now under another mount (but under the same dir)? I'm confused here.
</blockquote></details>

As suggested by Pawel to address a corner case of not to remove a dentry that is actually from another filesystem (i.e. child->fs != child->mount->fs). This is the case for example for named pipes. If you don't exclude them, listing a directory will cause such synthetic files to disappear.

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/425)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[LibOS/shim/src/fs/shim_namei.c, line 658 at r1](https://reviewable.io/reviews/gramineproject/gramine/425#-MwejNyp79W39Vk2u7az:-Mwfm7AD2g5U4kaKJhNO:b-obwbvr) ([raw file](https://github.com/gramineproject/gramine/blob/af67b3a10d8bc419ab67a21ebef0496e3f207a23/LibOS/shim/src/fs/shim_namei.c#L658)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

As suggested by Pawel to address a corner case of not to remove a dentry that is actually from another filesystem (i.e. child->fs != child->mount->fs). This is the case for example for named pipes. If you don't exclude them, listing a directory will cause such synthetic files to disappear.
</blockquote></details>

It looks like it's not obvious from the code, and the comment does not explain it well. I suggest changing the comment above to: `Do not remove dentries added by Gramine (named pipes, sockets, synthetic mountpoints)`.
___
*[LibOS/shim/src/fs/shim_namei.c, line 658 at r2](https://reviewable.io/reviews/gramineproject/gramine/425#-Mwfn7kA5lcVcrvcrTph:-Mwfn7kA5lcVcrvcrTpi:b5089sz) ([raw file](https://github.com/gramineproject/gramine/blob/c570ccec9e6755f455b7dd65a6b267f12bc358e9/LibOS/shim/src/fs/shim_namei.c#L658)):*
> ```C
>             /* Dentry that does not correspond to a real file is still valid. */
>             if ((child->state & DENTRY_VALID) && !(child->state & DENTRY_NEGATIVE) &&
>                 (child->fs == child->mount->fs)) {
> ```

This should be a rare case, can you add a `log_debug`? It will be helpful in case something breaks.

Something like: `File no longer present, removing dentry: %s` with `dent->name`.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/425)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 658 at r1](https://reviewable.io/reviews/gramineproject/gramine/425#-MwejNyp79W39Vk2u7az:-MwgG1jbCLJU8KXJwigU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/af67b3a10d8bc419ab67a21ebef0496e3f207a23/LibOS/shim/src/fs/shim_namei.c#L658)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It looks like it's not obvious from the code, and the comment does not explain it well. I suggest changing the comment above to: `Do not remove dentries added by Gramine (named pipes, sockets, synthetic mountpoints)`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_namei.c, line 658 at r2](https://reviewable.io/reviews/gramineproject/gramine/425#-Mwfn7kA5lcVcrvcrTph:-MwgG2LM6nNiwRCU1jIY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c570ccec9e6755f455b7dd65a6b267f12bc358e9/LibOS/shim/src/fs/shim_namei.c#L658)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This should be a rare case, can you add a `log_debug`? It will be helpful in case something breaks.

Something like: `File no longer present, removing dentry: %s` with `dent->name`.
</blockquote></details>

Done.

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/425)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/425)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/425)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by pwmarcz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/425)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
