### PR TITLE
[LTP] Increase timeouts when running with ASan

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

Gramine compiled with ASan builds is 2x slower, and some tests like
`sendfile09` often fail because of that.

## How to test this PR? 

Jenkins will, hopefully, pass :)

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[.ci/lib/config-asan.jenkinsfile, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/118#-Ml5oGLkCtUPDf1i69_1:-Ml5oGLkCtUPDf1i69_2:b-g13dkn) ([raw file](https://github.com/gramineproject/gramine/blob/7732e9bbb67682cca567d7cc0aa3b19390dbb342/.ci/lib/config-asan.jenkinsfile#L2)):*
> ```
> env.ASAN = '1'
> env.TIMEOUT_FACTOR = '2'
> ```

NP: `LTP_TIMEOUT_FACTOR`
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 125 at r1](https://reviewable.io/reviews/gramineproject/gramine/118#-Ml5ovLD6ktA3siey4fE:-Ml5ovLD6ktA3siey4fF:bhkc0ci) ([raw file](https://github.com/gramineproject/gramine/blob/7732e9bbb67682cca567d7cc0aa3b19390dbb342/LibOS/shim/test/ltp/runltp_xml.py#L125)):*
> ```Python
>         cmd (iterable): the command (full *argv*)
>     '''
>     def __init__(self, suite, tag, cmd, timeout_factor):
> ```

Maybe add default `1` also here?
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 624 at r1](https://reviewable.io/reviews/gramineproject/gramine/118#-Ml5p5aVBhB1gBzMjo3j:-Ml5p5aVBhB1gBzMjo3k:b3wf1zm) ([raw file](https://github.com/gramineproject/gramine/blob/7732e9bbb67682cca567d7cc0aa3b19390dbb342/LibOS/shim/test/ltp/runltp_xml.py#L624)):*
> ```Python
>         config[config.default_section][key] = value
> 
>     suite = TestSuite(config, args.timeout_factor)
> ```

Hm, won't this cause `timeout_factor` argument to be `None` (and override the default) if missing from cli?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/118#-Ml5prKu4Fm1wKlqRf24:-Ml5prKv26l7QD3V8jKB:b4zmadn) ([raw file](https://github.com/gramineproject/gramine/blob/7732e9bbb67682cca567d7cc0aa3b19390dbb342/LibOS/shim/test/ltp/runltp_xml.py#L60)):*
> ```Python
> argparser.add_argument('--timeout-factor', '-T', metavar='N',
>     type=float,
>     help='multiply all timeouts by N')
> ```

I guess you should add a default value here.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: 0 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[.ci/lib/config-asan.jenkinsfile, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/118#-Ml5oGLkCtUPDf1i69_1:-Ml5tKYaAsJI7-QPOEIr:b2nhktp) ([raw file](https://github.com/gramineproject/gramine/blob/7732e9bbb67682cca567d7cc0aa3b19390dbb342/.ci/lib/config-asan.jenkinsfile#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: `LTP_TIMEOUT_FACTOR`
</blockquote></details>

OK.
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/118#-Ml5prKu4Fm1wKlqRf24:-Ml5tRLP2O_c9bg64lhV:bidrs83) ([raw file](https://github.com/gramineproject/gramine/blob/7732e9bbb67682cca567d7cc0aa3b19390dbb342/LibOS/shim/test/ltp/runltp_xml.py#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess you should add a default value here.
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 125 at r1](https://reviewable.io/reviews/gramineproject/gramine/118#-Ml5ovLD6ktA3siey4fE:-Ml5taHF78KdktTsp8de:b2nhktp) ([raw file](https://github.com/gramineproject/gramine/blob/7732e9bbb67682cca567d7cc0aa3b19390dbb342/LibOS/shim/test/ltp/runltp_xml.py#L125)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe add default `1` also here?
</blockquote></details>

OK.
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 624 at r1](https://reviewable.io/reviews/gramineproject/gramine/118#-Ml5p5aVBhB1gBzMjo3j:-Ml5tbyZ2fpgDRT8ublo:b-8lyzsr) ([raw file](https://github.com/gramineproject/gramine/blob/7732e9bbb67682cca567d7cc0aa3b19390dbb342/LibOS/shim/test/ltp/runltp_xml.py#L624)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, won't this cause `timeout_factor` argument to be `None` (and override the default) if missing from cli?
</blockquote></details>

Yes, I forgot the default in argument definition. Should work now.

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/118)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
