### PR TITLE
[mbedtls,CI-Examples] Upgrade mbedTLS to version 3.3.0

### PR DESCRIPTION
**Pull request by kailun-qin**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)

### CODE REVIEW

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: 0 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NJt56VL0BoVY1YWLx49:-NJt56VL0BoVY1YWLx4A:b-jrmnwi) ([raw file](https://github.com/gramineproject/gramine/blob/6a13434ee71cc0e420f6cf95a789d941f0b328c2/subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h#L15)):*
> ```objc
> #include "mbedtls/mbedtls_config.h"
> 
> #define MBEDTLS_CMAC_C
> ```

It's enabled by default in `mbedtls_config.h`:https://github.com/Mbed-TLS/mbedtls/blob/eab43a62c3c80076cd35261a853dc781cd281f0c/include/mbedtls/mbedtls_config.h#L2377.
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NJt4TdW4-ovDxVTWAmU:-NJt4TdW4-ovDxVTWAmV:borrvch) ([raw file](https://github.com/gramineproject/gramine/blob/6a13434ee71cc0e420f6cf95a789d941f0b328c2/subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h#L17)):*
> ```objc
> #define MBEDTLS_CMAC_C
> 
> #include "mbedtls/check_config.h"
> ```

It's recommanded to not include `check_config.h` anymore from mbedTLS 3.0-migration-guide: https://github.com/Mbed-TLS/mbedtls/blob/eab43a62c3c80076cd35261a853dc781cd281f0c/docs/3.0-migration-guide.md?plain=1#L52.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKEs3Mu5WxG67Tb8Rbw:-NKEs3Mu5WxG67Tb8Rbx:b-151gek) (no related file):*
Not strictly related, but reading the migration guide you linked it seems that we need more changes. See: https://github.com/Mbed-TLS/mbedtls/blob/eab43a62c3c80076cd35261a853dc781cd281f0c/docs/3.0-migration-guide.md?plain=1#L173-L183
and
https://github.com/gramineproject/gramine/blob/6a13434ee71cc0e420f6cf95a789d941f0b328c2/common/src/crypto/adapters/mbedtls_adapter.c#L449-L450

___
___
*[`subprojects/mbedtls-mbedtls-3.3.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKEtpGP0ZBnK0jZ0c2a:-NKEtpGP0ZBnK0jZ0c2b:b-vai557) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/subprojects/mbedtls-mbedtls-3.3.0.wrap#L4)):*
> ```
> directory = mbedtls-mbedtls-3.3.0
> source_url = https://github.com/ARMmbed/mbedtls/archive/mbedtls-3.3.0.tar.gz
> source_fallback_url = https://packages.gramineproject.io/distfiles/mbedtls-3.3.0.tar.gz
> ```

@woju: Please mirror this file, and @kailun-qin: please test links when you change them ;)

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKEs3Mu5WxG67Tb8Rbw:-NKG7UsL0NUp-sXzyyCG:b-1a9oei) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not strictly related, but reading the migration guide you linked it seems that we need more changes. See: https://github.com/Mbed-TLS/mbedtls/blob/eab43a62c3c80076cd35261a853dc781cd281f0c/docs/3.0-migration-guide.md?plain=1#L173-L183
and
https://github.com/gramineproject/gramine/blob/6a13434ee71cc0e420f6cf95a789d941f0b328c2/common/src/crypto/adapters/mbedtls_adapter.c#L449-L450
</blockquote></details>

Pls kindly note that only the **hex**-encoded primes were removed while the **binary** form is still there: https://github.com/Mbed-TLS/mbedtls/blob/eab43a62c3c80076cd35261a853dc781cd281f0c/docs/3.0-migration-guide.md?plain=1#L181-L182.

Changing from the hex to binary presentation was done in our last migration from 2.x to 3.x: https://github.com/gramineproject/gramine/pull/796/files#diff-51abbbe7cde57ef17576477f7e62bfdefe1b865fca493449b07b2384680aa820.

___
___
*[`subprojects/mbedtls-mbedtls-3.3.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKEtpGP0ZBnK0jZ0c2a:-NKG8XnQAx7lgWZiX7qV:bt1x36r) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/subprojects/mbedtls-mbedtls-3.3.0.wrap#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju: Please mirror this file, and @kailun-qin: please test links when you change them ;)
</blockquote></details>

Sure, will do.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKEs3Mu5WxG67Tb8Rbw:-NKG9ztJ1hJFF3_VdzWQ:byff4m7) (no related file):*
> Pls kindly note that only the hex-encoded primes were removed while the binary form is still there

And how does this relate to the reason why they were removed from mbedtls?

> Changing from the hex to binary presentation was done in our last migration from 2.x to 3.x

That change would have made sense even without the hex macros being removed by mbedtls, and I actually doubt the reviewers noticed that there's more to it than just using more compact data representation.

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKEs3Mu5WxG67Tb8Rbw:-NKmyAhE8sXqi8vMAA_G:b-2825rq) (no related file):*
@mkow I don't think you're right. The current parameters that we use are fine (I mean the `RFC3526` parameters).

I remember reviewing these 1-2 years ago with a crypto expert. He said that these primes are fine (in fact, we can even find the commit where I modified them to better ones: https://github.com/gramineproject/gramine/commit/248780dd31e37c6f9992fa8d65954b23a9bf5c90)

Now, looking at the migration guide of mbedTLS, the paragraph is not written very nicely. Please pay attention to **two independent claims** in this paragraph:

> The primes from RFC 5114 are deprecated because their derivation is not
documented and therefore their usage constitutes a security risk; they are fully
removed from the library. Please use parameters from RFC 3526 (still in the
library, only in binary form) or RFC 7919 (also available in the library) or
other trusted sources instead.

So yes, `RFC5114` must never be used (first sentence). But `RFC3526` is fine (second sentence).

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKmzklVCq_gqB9ySJ0I:-NKmzklVCq_gqB9ySJ0J:bb74zub) (no related file):*
@kailun-qin Just for my own understanding -- was there a particular reason to update to mbedTLS 3.3.0? Like, did anything fail or anything was missing?

Anyway, thanks for the PR! I was waiting for that `MBEDTLS_CMAC_C` being a default for ages!

___
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKn0uoT810vxFRu-0Ro:-NKn0uoT810vxFRu-0Rp:b-f7fo0g) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h#L8)):*
> ```objc
> /*
>  * This is the configuration for Gramine's userspace build of mbedtls. It overrides the default
>  * `mbedtls/mbedtls_config.h`.
> ```

Actually, now there is nothing to override. This file can be removed, and all its usages can be removed.

@kailun-qin Could you do this simplification -- remove this file and its mentions from the mbedTLS build?
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NJt56VL0BoVY1YWLx49:-NKn0WZa7MD4eFnaFRg9:b-818n3h) ([raw file](https://github.com/gramineproject/gramine/blob/6a13434ee71cc0e420f6cf95a789d941f0b328c2/subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h#L15)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's enabled by default in `mbedtls_config.h`:https://github.com/Mbed-TLS/mbedtls/blob/eab43a62c3c80076cd35261a853dc781cd281f0c/include/mbedtls/mbedtls_config.h#L2377.
</blockquote></details>

This link is better: https://github.com/Mbed-TLS/mbedtls/blob/v3.3.0/include/mbedtls/mbedtls_config.h#L2347 (because it points directly to tag `v3.3.0`). But yes, it is finally in the default config!
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKn1vXp8o9oKF88A6Nu:-NKn1vXp8o9oKF88A6Nv:b11pxqt) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L35)):*
> ```objc
> #define MBEDTLS_NO_UDBL_DIVISION
> #define MBEDTLS_OID_C
> #define MBEDTLS_PKCS1
> ```

This doesn't seem to exist in mbedTLS... Could you double-check and remove this macro?
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKn2JH0AKxdowQDylOA:-NKn2JH0AKxdowQDylOB:b-50f3io) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L46)):*
> ```objc
> #define MBEDTLS_SSL_PROTO_TLS1_2
> #define MBEDTLS_SSL_SRV_C
> #define MBEDTLS_SSL_TLS_C
> ```

FYI: I went through all macros in this file and checked if they exist and make sense in v3.3.0. Looks like only one macro (`MBEDTLS_PKCS1`) is useless, the others are fine.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin, @mkow, and @woju)

___
*[`subprojects/mbedtls-mbedtls-3.3.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKEtpGP0ZBnK0jZ0c2a:-NKn2gNCDtDUcECN9KbU:bxxs5tl) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/subprojects/mbedtls-mbedtls-3.3.0.wrap#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sure, will do.
</blockquote></details>

Woju added this file, I verified its hash, everything looks good.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKEs3Mu5WxG67Tb8Rbw:-NKnBnxE5hQT1Bh-CHyA:b44kz6y) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I don't think you're right. The current parameters that we use are fine (I mean the `RFC3526` parameters).

I remember reviewing these 1-2 years ago with a crypto expert. He said that these primes are fine (in fact, we can even find the commit where I modified them to better ones: https://github.com/gramineproject/gramine/commit/248780dd31e37c6f9992fa8d65954b23a9bf5c90)

Now, looking at the migration guide of mbedTLS, the paragraph is not written very nicely. Please pay attention to **two independent claims** in this paragraph:

> The primes from RFC 5114 are deprecated because their derivation is not
documented and therefore their usage constitutes a security risk; they are fully
removed from the library. Please use parameters from RFC 3526 (still in the
library, only in binary form) or RFC 7919 (also available in the library) or
other trusted sources instead.

So yes, `RFC5114` must never be used (first sentence). But `RFC3526` is fine (second sentence).
</blockquote></details>

Uh, you're right, there were two separate reasons listed there, I misread it (although I also think it's badly written). Resolving.

___

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: 5 of 10 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKmzklVCq_gqB9ySJ0I:-NKuiUwsBXDLW6mjY27a:b-urdn1b) (no related file):*
> Just for my own understanding -- was there a particular reason to update to mbedTLS 3.3.0? Like, did anything fail or anything was missing?

No, not really. Just a periodic update to keep up to the latest version for mbedTLS (as we planned previously, pls kindly see the discussions e.g., in https://github.com/gramineproject/gramine/pull/426#pullrequestreview-893552175 and https://github.com/gramineproject/gramine/pull/426#pullrequestreview-893719381).

___
___
*[`CI-Examples/ra-tls-mbedtls/Makefile` line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKutISw9BJ6fyhdQ_fa:-NKutISx77b8B0Qkb43V:b-2kwban) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/CI-Examples/ra-tls-mbedtls/Makefile#L68)):*
> ```Makefile
> 	touch $@
> 
> .SECONDARY: mbedtls/.mbedtls_configured
> ```

I think this is also not needed.
___
*[`subprojects/mbedtls-mbedtls-3.3.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKEtpGP0ZBnK0jZ0c2a:-NKujTbDDRM28XxpZzlP:bvgubtc) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/subprojects/mbedtls-mbedtls-3.3.0.wrap#L4)):*
> Woju added this file, I verified its hash, everything looks good.

Thanks for checking!
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKn0uoT810vxFRu-0Ro:-NKul4t30cuWg1AVq9UW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, now there is nothing to override. This file can be removed, and all its usages can be removed.

@kailun-qin Could you do this simplification -- remove this file and its mentions from the mbedTLS build?
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKn1vXp8o9oKF88A6Nu:-NKumq7b7gBXfsKEE7dp:b-853raf) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't seem to exist in mbedTLS... Could you double-check and remove this macro?
</blockquote></details>

Right, it's invalid. Removed.

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKmzklVCq_gqB9ySJ0I:-NKw6lBI9rTFIE2ycEh5:bb6ywmx) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Just for my own understanding -- was there a particular reason to update to mbedTLS 3.3.0? Like, did anything fail or anything was missing?

No, not really. Just a periodic update to keep up to the latest version for mbedTLS (as we planned previously, pls kindly see the discussions e.g., in https://github.com/gramineproject/gramine/pull/426#pullrequestreview-893552175 and https://github.com/gramineproject/gramine/pull/426#pullrequestreview-893719381).
</blockquote></details>

LGTM

___
___
*[`CI-Examples/ra-tls-mbedtls/Makefile` line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/1088#-NKutISw9BJ6fyhdQ_fa:-NKw6qjM-_Qp1INu3OOZ:bi8zjp) ([raw file](https://github.com/gramineproject/gramine/blob/41fe836b5a9b92b6ad484b619da504e594d6954a/CI-Examples/ra-tls-mbedtls/Makefile#L68)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think this is also not needed.
</blockquote></details>

Yep. Both `MBEDTLS_CMAC_C` and `MBEDTLS_ERROR_C` config params are already the default in mbedTLS 3.3.0, so no need for this additional "reconfiguration" step.

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1088)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
