### PR TITLE
[PAL/Linux-SGX] Remove insecure `enclave_untrusted.c`

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
See the commit message.

## How to test this PR? 
Hopefully normal CI is enough.
I've also manually tested by adding 2048x `PalEventCrete` and then `PalObjectClose` on all of them in `libos_init.c` with ASAN enabled.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/916)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/916)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC59cda0xKmVz6XuEbv):*
I'd mention in the one-liner that this is a security fix

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/916)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC59cda0xKmVz6XuEbv):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd mention in the one-liner that this is a security fix
</blockquote></details>

Any proposal on exact wording?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/916)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC59cda0xKmVz6XuEbv):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Any proposal on exact wording?
</blockquote></details>

Maybe just ``Remove insecure `enclave_untrusted.c` ``? I don't have better ideas.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/916)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5CQ6zCMnVxRwXd-l_):*
Can we add an empty line to visually split these two paragraphs?
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC59cda0xKmVz6XuEbv):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Any proposal on exact wording?
</blockquote></details>

Maybe simply 
```
[...] Remove insecure `enclave_untrusted.c`
```
___
*[`pal/src/host/linux-sgx/pal_events.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5CjajA8rQeXiqklnB:-NC5CjajA8rQeXiqklnC:bxke1rt) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L32)):*
> ```C
>         if (ret < 0) {
>             spinlock_unlock(&g_untrusted_page_lock);
>             return ret;
> ```

This returns UNIX error code, but we want PAL error codes.
___
*[`pal/src/host/linux-sgx/pal_events.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EACf2iGoF38uZ8Uz:-NC5EACf2iGoF38uZ8V-:bdk7ku9) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L75)):*
> ```C
>         addr_to_munmap = untrusted_users_counter_ptr;
>         if (ALIGN_DOWN(g_untrusted_page_next_entry, PAGE_SIZE) == (uintptr_t)addr_to_munmap) {
>             g_untrusted_page_next_entry = 0;
> ```

Why is this needed?
___
*[`pal/src/host/linux-sgx/pal_events.c` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EWKr3WhRjAqxV2zF:-NC5EWKr3WhRjAqxV2zG:b-4zcu43) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L82)):*
> ```C
>     }
> #ifdef ASAN
>     asan_poison_region((uintptr_t)addr, 2 * sizeof(uint32_t), ASAN_POISON_HEAP_LEFT_REDZONE);
> ```

Maybe add an assert here that `addr % 8 == 0`?
___
*[`pal/src/host/linux-sgx/pal_events.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EmpB2NLO86LvsJDh:-NC5EmpB2NLO86LvsJDi:bxzrp7z) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L88)):*
> ```C
>     if (addr_to_munmap) {
> #ifdef ASAN
>         /* First 64 bits are for users counter - already not poisoned. */
> ```

Not blocking, but why couldn't we just unpoison the whole page?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/916)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC59cda0xKmVz6XuEbv):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe simply 
```
[...] Remove insecure `enclave_untrusted.c`
```
</blockquote></details>

Heh, seems we have a winner :)
___
*[`pal/src/host/linux-sgx/pal_events.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EACf2iGoF38uZ8Uz:-NC5GVz94U27mUtyacm4:b-f881k1) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Otherwise `g_untrusted_page_next_entry` will point to a deallocated memory.
___
*[`pal/src/host/linux-sgx/pal_events.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EmpB2NLO86LvsJDh:-NC5GaKi6d0c7qXB8q2G:bvhu1go) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not blocking, but why couldn't we just unpoison the whole page?
</blockquote></details>

I think trying to unpoison an already unpoisoned region is also a memory bug reported by ASan.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/916)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5CQ6zCMnVxRwXd-l_):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add an empty line to visually split these two paragraphs?
</blockquote></details>

Done.
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC59cda0xKmVz6XuEbv):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Heh, seems we have a winner :)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_events.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5CjajA8rQeXiqklnB:-NC5GKGW9PRrkumteA8X:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This returns UNIX error code, but we want PAL error codes.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_events.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EACf2iGoF38uZ8Uz:-NC5GLVyCy7KOm0CsHAG:bmegf5d) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L75)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Otherwise `g_untrusted_page_next_entry` will point to a deallocated memory.
</blockquote></details>

Because we are about to unmap this page. Think about scenario:
1. Thread allocates one entry here.
2. The same thread frees it.

We have users == 0, and `g_untrusted_page_next_entry = page + 0xc`.  What we could do is free only if we use the whole page, but I didn't bother. I can try if you want
___
*[`pal/src/host/linux-sgx/pal_events.c` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EWKr3WhRjAqxV2zF:-NC5Gs4qBM-shDIuTZ4F:bczybs5) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add an assert here that `addr % 8 == 0`?
</blockquote></details>

`asan_poison_region` has it inside
___
*[`pal/src/host/linux-sgx/pal_events.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EmpB2NLO86LvsJDh:-NC5Gx212QnArMhx_6e3:b8sbshh) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think trying to unpoison an already unpoisoned region is also a memory bug reported by ASan.
</blockquote></details>

I didn't try, but I thought it would be an error to unpoison already unpoisoned memory

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/916)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/916)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`pal/src/host/linux-sgx/pal_events.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EACf2iGoF38uZ8Uz:-NC5JeOuDOqbHeXprgfn:b-ex6255) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L75)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because we are about to unmap this page. Think about scenario:
1. Thread allocates one entry here.
2. The same thread frees it.

We have users == 0, and `g_untrusted_page_next_entry = page + 0xc`.  What we could do is free only if we use the whole page, but I didn't bother. I can try if you want
</blockquote></details>

Ah, ok, got it. No need to bother.
___
*[`pal/src/host/linux-sgx/pal_events.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/916#-NC5EmpB2NLO86LvsJDh:-NC5JkdU544-Vj_XcYQ_:b32w0x) ([raw file](https://github.com/gramineproject/gramine/blob/af5208856fc52f328678a46cac6a84778a9d8154/pal/src/host/linux-sgx/pal_events.c#L88)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I didn't try, but I thought it would be an error to unpoison already unpoisoned memory
</blockquote></details>

OK

**Pull request merged**
