### PR TITLE
[common] Refactor Protected Files, part 5

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This commit refactors PF code without changing functionality (part 5 in a series of commits). In particular, this commit renames variables, struct definitions, struct fields and functions for readability. This is the last commit in this series.

Closes #1841.

Note that this PR is based on #1869.

## How to test this PR? 

N/A

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1894)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1894)* status: 0 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`common/src/protected_files/protected_files.c` line 188 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-NzX80OR6t96dRLk6f2-:-NzX80OR6t96dRLk6f20:b9k1ytj) ([raw file](https://github.com/gramineproject/gramine/blob/7ce9dae933c45fbf42d570284f980e8cc5d7f9f9/common/src/protected_files/protected_files.c#L188)):*
> ```C
> }
> 
> static bool ipf_generate_nonced_metadata_key(pf_context_t* pf, pf_key_t* output) {
> ```

FYI: I'm not particularly happy with this name (the "nonced" part, which should be read as "generate the key dervied from the nonce")

**Comment by woju** [comment]
Jenkins, test this please

**Comment by woju** [comment]
Jenkins, test this please

**Comment by woju** [comment]
Jenkins, test this please

**Comment by woju** [comment]
Jenkins, test this please

**Comment by woju** [comment]
Jenkins, test this please

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1894)* status: 3 of 5 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files_format.h` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk2L9J5UTDHAT8ioRU:-Nzk2L9J5UTDHAT8ioRV:bp1gwhk) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/common/src/protected_files/protected_files_format.h#L63)):*
> ```objc
> typedef struct _metadata_decrypted_header {
>     char     file_path[PATH_MAX_SIZE];
>     uint64_t file_size;
> ```

I assume this is the size after decryption? Not the encrypted file (storing which wouldn't make much sense).
Could you add a short comment here clarifying that?
___
*[`common/src/protected_files/protected_files_internal.h` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-NzjzeMMAa3PunvRVCaX:-NzjzeMMAa3PunvRVCaY:b-66rz7o) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/common/src/protected_files/protected_files_internal.h#L28)):*
> ```objc
>     metadata_decrypted_header_t metadata_decrypted_header; // contains file path, size, etc.
> 
>     file_node_t root_mht_node;     // root MHT node is always needed (for files bigger than 3KB)
> ```

Please undo the comment change (mistake when rebasing?)



_Code quote:_
```objc
// root MHT node is always needed (for files bigger than 3KB)
```
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk4IrP5NNe9RC8WcmZ:-Nzk4IrP5NNe9RC8Wcm_:b-htrxf7) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/tools/sgx/pf_tamper/pf_tamper.c#L83)):*
> ```C
>  * - Node 0: metadata (metadata_node_t)
>  *   - metadata_plaintext_header_t
>  *   - metadata_decrypted_header_t (may include MD_USER_DATA_SIZE bytes of data)
> ```

I'd mark somehow that it's not that struct which is in the file, it's the encryption of it.



_Suggestion:_
```C
enc(metadata_decrypted_header_t) (may include MD_USER_DATA_SIZE bytes of data)
```
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 131 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk53KT6PLIHEISa2qk:-Nzk53KU5fgBX7XftdMz:bcu7eb7) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/tools/sgx/pf_tamper/pf_tamper.c#L131)):*
> ```C
>     DBG("metadata_plaintext_header_t.metadata_key_nonce     : 0x%04lx (0x%04lx)\n",
>         offsetof(metadata_plaintext_header_t, metadata_key_nonce),
>         FIELD_SIZEOF(metadata_plaintext_header_t, metadata_key_nonce));
> ```

copy-paste fail? what happened to mac?
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk69KS38ocbMelh1rH:-Nzk69KS38ocbMelh1rI:brjc20u) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/tools/sgx/pf_tamper/pf_tamper.c#L164)):*
> ```C
>     truncate_file("trunc_meta_plain_5", FIELD_TRUNCATED(metadata_plaintext_header_t,
>                 metadata_key_nonce));
>     truncate_file("trunc_meta_plain_6", offsetof(metadata_plaintext_header_t, metadata_key_nonce));
> ```

another copy-paste fail?
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk6K846FXOAo8zeAPi:-Nzk6K846FXOAo8zeAPj:bagdpjd) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/tools/sgx/pf_tamper/pf_tamper.c#L164)):*
> ```C
>     truncate_file("trunc_meta_plain_5", FIELD_TRUNCATED(metadata_plaintext_header_t,
>                 metadata_key_nonce));
>     truncate_file("trunc_meta_plain_6", offsetof(metadata_plaintext_header_t, metadata_key_nonce));
> ```

This PR is super-tedious to review and you've made multiple copy-paste/find-and-replace errors :/ Would it be possible to split it further into smaller PRs, with less renames at the same time? It would clean up the diff a bit. Finding all those errors manually will take hours :/

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1894)* status: 3 of 5 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`common/src/protected_files/protected_files_format.h` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk2L9J5UTDHAT8ioRU:-Nzm6maD4pUv1uKH3Wyv:b11mhvl) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/common/src/protected_files/protected_files_format.h#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I assume this is the size after decryption? Not the encrypted file (storing which wouldn't make much sense).
Could you add a short comment here clarifying that?
</blockquote></details>

Done, in a new PR
___
*[`common/src/protected_files/protected_files_internal.h` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-NzjzeMMAa3PunvRVCaX:-NzmA14Z5zoY2NKWh8M9:b11mhvl) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/common/src/protected_files/protected_files_internal.h#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please undo the comment change (mistake when rebasing?)
</blockquote></details>

Done, in a new PR
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk4IrP5NNe9RC8WcmZ:-NzmA2qwD6JCIgusTdhS:b-svhf26) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/tools/sgx/pf_tamper/pf_tamper.c#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd mark somehow that it's not that struct which is in the file, it's the encryption of it.
</blockquote></details>

Will be done later
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 131 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk53KT6PLIHEISa2qk:-NzmA4tXDJoqf0z21Sm_:btu80ev) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/tools/sgx/pf_tamper/pf_tamper.c#L131)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

copy-paste fail? what happened to mac?
</blockquote></details>

Yeah, copy-paste fail
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk69KS38ocbMelh1rH:-NzmA6No62-pHSsfus3f:bb77u1k) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/tools/sgx/pf_tamper/pf_tamper.c#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

another copy-paste fail?
</blockquote></details>

Yeah
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/1894#-Nzk6K846FXOAo8zeAPi:-NzmA6qG-6Exg6YKC-SG:b-35v6ec) ([raw file](https://github.com/gramineproject/gramine/blob/841235931b2b78ad5f0cccbfc0b7c98272d24c80/tools/sgx/pf_tamper/pf_tamper.c#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This PR is super-tedious to review and you've made multiple copy-paste/find-and-replace errors :/ Would it be possible to split it further into smaller PRs, with less renames at the same time? It would clean up the diff a bit. Finding all those errors manually will take hours :/
</blockquote></details>

Done: https://github.com/gramineproject/gramine/pull/1899

I will split the rest of the changes (that are all accumulated in this super-tedious PR) in another 3-4 smaller PRs. The first one in the rest of the series is #1899.

In the next PRs, I plan to introduce renames one at a time (well, I will group those that are easy to review together).

**Comment by dimakuv** [comment]
Superseded by #1899

**Pull request closed without merging**
