### PR TITLE
[Pal] Add missing frees after "toml_string_in"

### PR DESCRIPTION
**Pull request by kailun-qin**
## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 734 at r1](https://reviewable.io/reviews/gramineproject/gramine/396#-MvbnUpq7WzSPCh453-4:-MvbnUpq7WzSPCh453-5:bnmrhoz) ([raw file](https://github.com/gramineproject/gramine/blob/aae06b0a21fcc11eab5e8d9b2659739a41cc9c8d/Pal/src/host/Linux-SGX/sgx_main.c#L734)):*
> ```C
>     /* EPID is used if SPID is a non-empty string in manifest, otherwise DCAP/ECDSA */
>     enclave_info->use_epid_attestation = sgx_ra_client_spid_str && strlen(sgx_ra_client_spid_str);
>     free(sgx_ra_client_spid_str);
> ```

I don't like this solution. If we want to do proper memory cleanup, we need to do it also on failure paths. With your PR, we don't free `sgx_ra_client_spid_str`, `profile_mode_str`, `profile_str` in many error paths (e.g., the `Detected EPID ...` path above).

I suggest to:
- revert `sgx_ra_client_spid_str` freeing logic as it was before
- make all other strings logic similar to `sgx_ra_client_spid_str`: declare in the very beginning of the function as NULLs and free in the `out:` label.

This way we'll have a clean and concise logic for freeing all temporary strings.

**Review by dimakuv — COMMENTED** [review]
The first item is not a concern. We use this pattern almost everywhere in Gramine, and a few "dummy" `free`s at runtime don't hurt.

The second item -- yes, please also change these places as well. I guess you're talking about only this function `parse_loader_config()`? Note that we skip freeing memory on error paths in many initialization functions because we don't really care about this (Linux will terminate the Gramine process anyway, cleaning up all the memory)... But in this particular function `parse_loader_config()` we should do proper cleaning. Ideally of course in all functions, but we didn't want to waste our time on these low-priority things.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396#-:-MvbueucDXVhav8Ky1Mq:badf60i)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 734 at r1](https://reviewable.io/reviews/gramineproject/gramine/396#-MvbnUpq7WzSPCh453-4:-Mvc3xD6DLKGQBaousPM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/aae06b0a21fcc11eab5e8d9b2659739a41cc9c8d/Pal/src/host/Linux-SGX/sgx_main.c#L734)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this solution. If we want to do proper memory cleanup, we need to do it also on failure paths. With your PR, we don't free `sgx_ra_client_spid_str`, `profile_mode_str`, `profile_str` in many error paths (e.g., the `Detected EPID ...` path above).

I suggest to:
- revert `sgx_ra_client_spid_str` freeing logic as it was before
- make all other strings logic similar to `sgx_ra_client_spid_str`: declare in the very beginning of the function as NULLs and free in the `out:` label.

This way we'll have a clean and concise logic for freeing all temporary strings.
</blockquote></details>

Done.

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 598 at r2](https://reviewable.io/reviews/gramineproject/gramine/396#-Mvd8xSe4d44W0JnOOwJ:-Mvd8xSe4d44W0JnOOwK:b-7w5gul) ([raw file](https://github.com/gramineproject/gramine/blob/ce33944e7857938d540ca76ec39604faa318a532/Pal/src/host/Linux-SGX/sgx_main.c#L598)):*
> ```C
>     char* sgx_ra_client_spid_str = NULL;
>     char* profile_str = NULL;
> #ifdef DEBUG
> ```

I wouldn't bother with this `ifdef` and just declare + free it unconditionally, but not blocking on this.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 598 at r2](https://reviewable.io/reviews/gramineproject/gramine/396#-Mvd8xSe4d44W0JnOOwJ:-MvdA1Mb87WNs2kN1fXn:b9a5btw) ([raw file](https://github.com/gramineproject/gramine/blob/ce33944e7857938d540ca76ec39604faa318a532/Pal/src/host/Linux-SGX/sgx_main.c#L598)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I wouldn't bother with this `ifdef` and just declare + free it unconditionally, but not blocking on this.
</blockquote></details>

I guess he did this because of some compiler warnings? But if not then I'm also fine with dropping `#ifdef DEBUG` (but not blocking).

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 598 at r2](https://reviewable.io/reviews/gramineproject/gramine/396#-Mvd8xSe4d44W0JnOOwJ:-MvdB6Jt041GUJrFh4sW:b3q0thn) ([raw file](https://github.com/gramineproject/gramine/blob/ce33944e7857938d540ca76ec39604faa318a532/Pal/src/host/Linux-SGX/sgx_main.c#L598)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess he did this because of some compiler warnings? But if not then I'm also fine with dropping `#ifdef DEBUG` (but not blocking).
</blockquote></details>

There should be no warnings as we call `free` on it.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 598 at r2](https://reviewable.io/reviews/gramineproject/gramine/396#-Mvd8xSe4d44W0JnOOwJ:-MvdBahx8amcYPj3kSmI:bmfjqe6) ([raw file](https://github.com/gramineproject/gramine/blob/ce33944e7857938d540ca76ec39604faa318a532/Pal/src/host/Linux-SGX/sgx_main.c#L598)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There should be no warnings as we call `free` on it.
</blockquote></details>

I know we do, but `free()` is quite special and compiler knows its semantics, so I wouldn't be surprised if this actually emitted a warning.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/396)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
