### PR TITLE
[CI-Examples] Apply grouped targets make hack to all examples

### PR DESCRIPTION
**Pull request by NieDzejkob**
## Description of the changes 

Following up n #495, I switch the rest of the examples to use the preferred method of having make generate two files with one command.

## How to test this PR? 

CI should be enough.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/588#-N2BOYtkEWM0qXLeqDyP):*
Not blocking, but do we want to call this a hack? I mean, in such case, make would be just one huge pile of hacks :)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @NieDzejkob)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/588#-N2BOYtkEWM0qXLeqDyP):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not blocking, but do we want to call this a hack? I mean, in such case, make would be just one huge pile of hacks :)
</blockquote></details>

Whatever from my side :) If you don't like "hack" then maybe "workaround"?
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/588#-N2BTZ4F-qAvP9Pw9z2Y):*
> Apply grouped targets make hack to all examples

I stared at this on email for quite a while trying to parse and understand what this sentence means. And then noticed that you meant _Make_, not _make_ (an English verb) :P

Please change to "Make".

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @NieDzejkob)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/588#-N2BOYtkEWM0qXLeqDyP):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Whatever from my side :) If you don't like "hack" then maybe "workaround"?
</blockquote></details>

Workaround sounds better to me

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/588#-N2C8Kyz3Uj0FfmnKgfu:-N2C8Kyz3Uj0FfmnKgfv:bpq6gc7) (no related file):*
Jenkins-Direct-Sanitizers failed, while unrelated to this PR, it needs to be investigated. There is nothing suspicious, except that it took 6s to print the first debug message (`Gramine was build from commit...`) form the start of Gramine (`gramine-dirext rust-...`). The timeout on waiting for the server to start listening was 5s, so whole test timedout.

___

**Review by NieDzejkob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/588#-N2BTZ4F-qAvP9Pw9z2Y):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Apply grouped targets make hack to all examples

I stared at this on email for quite a while trying to parse and understand what this sentence means. And then noticed that you meant _Make_, not _make_ (an English verb) :P

Please change to "Make".
</blockquote></details>

Okay. Applied the commit message suggestions and rebased on top of current `master`.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/588)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
