### PR TITLE
[PAL/Linux-SGX,tools] Fix misc memory leaks

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Two memory leaks detected by Klocwork.

## How to test this PR? 

CI is enough.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/779)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/779)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux/pal_sockets.c` line 241 at r1](https://reviewable.io/reviews/gramineproject/gramine/779#-N7_ZT2Q25IAOFKh-Hzn:-N7_ZT2R4vQEsa9AJUTr:b-id855h) ([raw file](https://github.com/gramineproject/gramine/blob/47f63673df0ae234b45e332a023f3681d2143e3e/pal/src/host/linux/pal_sockets.c#L241)):*
> ```C
>         if (ret < 0) {
>             /* This should never happen, but we have to handle it somehow. */
>             free(client);
> ```

Isn't `fd` also leaking here and above?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/779)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/host/linux/pal_sockets.c` line 241 at r1](https://reviewable.io/reviews/gramineproject/gramine/779#-N7_ZT2Q25IAOFKh-Hzn:-N7_jRgD5fndk2RFtj3Z:b9pkljy) ([raw file](https://github.com/gramineproject/gramine/blob/47f63673df0ae234b45e332a023f3681d2143e3e/pal/src/host/linux/pal_sockets.c#L241)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't `fd` also leaking here and above?
</blockquote></details>

Done. You are right. I also switched to a more correct closing of the file (both closes the `fd` and frees memory)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/779)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/779)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/779#-N7bG3CY7m2ywQQM7XAN):*




_Suggestion:_
```
[PAL/Linux,tools] Fix misc memory leaks
```

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/779)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/779#-N7bG3CY7m2ywQQM7XAN):*
Done.
Also changed `memory` -> `resource` (this has changed after PR submission) and the description. It's not perfect (two of these leaks are solved with a single change), but I didn't want to write a long essay explaining such a simple fix.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/779)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
