### PR TITLE
[tests] set up the test numbering

### PR DESCRIPTION
**Pull request by oshogbo**
## How to test this PR? 
```
ninja all
ninja install
gramine-test -C LibOS/shim/test/abi/x86_64/ pytest
```

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/567#-N1J3dzV3D9ADMfDcjao):*
`Set up` (capital letter). Can be done during final rebase.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/567#-N1J3dzV3D9ADMfDcjao):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Set up` (capital letter). Can be done during final rebase.
</blockquote></details>

Also, shouldn't it be `tests` (instead of `the test`)?

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/567#-N1J3dzV3D9ADMfDcjao):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Also, shouldn't it be `tests` (instead of `the test`)?
</blockquote></details>

ok.

**Comment by oshogbo** [comment]
I have fixed commit message.
I have rebased it to current master.
IMHO its ready for merging.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)* status: 0 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/567#-N1KFtwIDpmmRgX8nmDP:-N1KFtwIDpmmRgX8nmDQ:b-pnl9wk) (no related file):*
@oshogbo 
1. Please use reviewable for comments.
2. If you check the commits you will see that something failed with your rebase. Maybe did not fetch current master?
3. We have a merge queue. When the times comes for the PR, only then we do the rebase (basically not to do it twice).

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)* status: 0 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/567#-N1KFtwIDpmmRgX8nmDP:-N1KGwcP2pTOP3zqvp3I:bajnify) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@oshogbo 
1. Please use reviewable for comments.
2. If you check the commits you will see that something failed with your rebase. Maybe did not fetch current master?
3. We have a merge queue. When the times comes for the PR, only then we do the rebase (basically not to do it twice).
</blockquote></details>

Yeah, something went wrong :)

`This branch is 3 commits ahead, 2 commits behind gramineproject/gramine:master.`

---

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)* status: 0 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/567#-N1KFtwIDpmmRgX8nmDP:-N1KqDef-WgU5rfsLdmA:bi6368) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, something went wrong :)

`This branch is 3 commits ahead, 2 commits behind gramineproject/gramine:master.`
</blockquote></details>

1. Will do.
2. Fixed.
3. Ok.

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/567)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
