### PR TITLE
[PAL/Linux-SGX] Log invalid search domains/hostname in `post_callback()`

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 
Gramine's logging configuration is done in the PAL-common logic (to avoid duplication), which is executed after the PAL-specific logic. So previously, the warnings about invalid search domain names and/or hostname (which are checked and produced during the PAL-specific logic) didn't show up in Gramine logs.

This commit saves the invalid DNS information, and prints the warnings in `post_callback()`, which is after logging is configured.

Fixes https://github.com/gramineproject/gramine/issues/1626.

## How to test this PR? 
Manual testing w/ invalid search domain names in `/etc/resolv.conf` or hostname.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1630)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1630)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1630#-NhzZOCFB9Xfbiwr8fJ8:-NhzZOCFB9Xfbiwr8fJ9:bnb3ba2) (no related file):*
Nice! Thanks, this is much better than changing to `log_error()` level.

___
___
*[`pal/src/host/linux-sgx/pal_main.c` line 561 at r1](https://reviewable.io/reviews/gramineproject/gramine/1630#-NhzZ6QCCa8ma_1vgzT5:-NhzZ6QCCa8ma_1vgzT6:b95dovn) ([raw file](https://github.com/gramineproject/gramine/blob/9053178702cddf7d45c6db1bbed942b85086b708/pal/src/host/linux-sgx/pal_main.c#L561)):*
> ```C
>         }
>         if (g_invalid_dns_host_conf.hostname != NULL) {
>             log_warning("The hostname on the host: %s seems to be invalid. "
> ```

Why did you add `:`? I would just remove it. If you want to highlight the hostname, then better surround it with double quotes (like done later for `localhost`).

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1630)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 561 at r1](https://reviewable.io/reviews/gramineproject/gramine/1630#-NhzZ6QCCa8ma_1vgzT5:-NhzddNODorhyvFx7dPY:b10kcvw) ([raw file](https://github.com/gramineproject/gramine/blob/9053178702cddf7d45c6db1bbed942b85086b708/pal/src/host/linux-sgx/pal_main.c#L561)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you add `:`? I would just remove it. If you want to highlight the hostname, then better surround it with double quotes (like done later for `localhost`).
</blockquote></details>

Done, I'm simply removing it

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1630)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 561 at r1](https://reviewable.io/reviews/gramineproject/gramine/1630#-NhzZ6QCCa8ma_1vgzT5:-Nhzx2g-0tFwlheBhuRP:bueuldd) ([raw file](https://github.com/gramineproject/gramine/blob/9053178702cddf7d45c6db1bbed942b85086b708/pal/src/host/linux-sgx/pal_main.c#L561)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done, I'm simply removing it
</blockquote></details>

Now there is no sense in keeping the `g_invalid_dns_host_conf.hostname` string, a boolean would suffice.

I actually like to print the bad hostname, please keep it.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1630)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 561 at r1](https://reviewable.io/reviews/gramineproject/gramine/1630#-NhzZ6QCCa8ma_1vgzT5:-Ni-FEq3EJ4FwPRv90CH:b-qpkd) ([raw file](https://github.com/gramineproject/gramine/blob/9053178702cddf7d45c6db1bbed942b85086b708/pal/src/host/linux-sgx/pal_main.c#L561)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now there is no sense in keeping the `g_invalid_dns_host_conf.hostname` string, a boolean would suffice.

I actually like to print the bad hostname, please keep it.
</blockquote></details>

Ah, I misread your previous suggestion (where you only suggested to remove `:`, but not the bad hostname) -- sorry about it. Updated again by keeping the bad hostname and highlighting it w/ double quotes.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1630)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1630)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1630)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
