### PR TITLE
[LibOS] Add simple `fallocate` syscall implementation

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Only `0` mode is supported. If file size is smaller than requested `offset + length`, it's simply extended, otherwise nothing happens.

Closes #519

## How to test this PR? 
Couple of LTP tests enabled.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: 0 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_util.c, line 64 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-T9ZPc6QeYJ4E-velT:-N-T9ZPc6QeYJ4E-velU:b-sb0klu) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/fs/shim_fs_util.c#L64)):*
> ```C
>     buf->st_mode = inode->type | inode->perm;
>     buf->st_size = inode->size;
>     buf->st_blksize = PAGE_SIZE;
> ```

One of LTP tests requires that, otherwise it starts writing `0` size chunks and nothings works as that test expects.
I've picked `PAGE_SIZE` as most suitable value, but not sure if that's a good idea.
wdyt? @pwmarcz @mkow @dimakuv

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: 0 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/sys/shim_open.c, line 615 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TBVT46MwXq-YElO4b:-N-TBVT46MwXq-YElO4c:b-v8e3jb) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L615)):*
> ```C
> 
>     /* Simple implemenation: extend the file if required, otherwise act as a no-op. */
>     lock(&handle->inode->lock);
> ```

This does not work well if 2 threads do `fallocate` at once. Also multiprocess cases are completely broken. Idk to what extent is that a problem or what to do with it.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_util.c, line 64 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-T9ZPc6QeYJ4E-velT:-N-TG5gcBGwuWWIz9wu_:bg8r6pe) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/fs/shim_fs_util.c#L64)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No idea what's best, but it'd be good to have a comment here that explains that decision - otherwise people will later wonder why do we set `st_blksize` and what's the deeper meaning behind that specific value.
</blockquote></details>

That's for sure, I just wanted to settle first on what we put here.
___
*[LibOS/shim/src/sys/shim_open.c, line 577 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TDcm69GHtY74tf2Yu:-N-TGb0EEFHNz9f6tnBb:b3h1jf7) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L577)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't think that's the right check, `handle->type` only corresponds to the filesystem (and e.g. the `chroot` filesystem actually deals with character devices, and conversely `tmpfs` filesystem is completely valid here).

If you want to check file type (regular file, pipe, device...), check for`handle->inode->type` (`S_IFIFO` etc.)
</blockquote></details>

All right, I'm not in sync with all the fs changes.
Done.
Update: not done. Pipes do not have inode...

Unrelated: why do we need `handle->is_dir` if we can check `handle->inode->type`? I suppose all dir handles have `inode`...
___
*[LibOS/shim/src/sys/shim_open.c, line 614 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TDBS11imDREux-vrg:-N-TIDpm1oGVNCXM4_vI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L614)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Typo (`implemenation` -> `implementation`)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 615 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TBVT46MwXq-YElO4b:-N-TIGGUDi6o6Q4l74_n:b-y7fie4) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L615)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm not sure, but it definitely deserves at least a TODO comment.
</blockquote></details>

Is a TODO enough? Do we even want to merge it as it is?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_open.c, line 615 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TBVT46MwXq-YElO4b:-N-U9SRv-3OFoPxFFyQH:b-h6rs4c) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L615)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> This does not work well if 2 threads do fallocate at once.

Why? Because two threads may simulteneously arrive at `fs->fs_ops->truncate()`? But the `truncate` callback must have proper synchronization (and it does, looking at examples of `tmpfs_truncate()` and `chroot_truncate()`).

> Also multiprocess cases are completely broken.

Why? Because one process won't see the updated size of the file done by another process? But isn't it a general problem with FS operations (like, if two processes call `ftruncate()`, there will be the same problem)? And if so, then it's not the problem of this PR.
</blockquote></details>

The problem is we read `size` and then truncate the file. We may race the truncate to actually shrink the file and lose data. Note that normal `fallocate` does not have this problem, since specifying len + offset smalle than file won't destroy any data.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_open.c, line 615 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TBVT46MwXq-YElO4b:-N-WbuCL3vO1VEFt_-Rx:b-5w7j3a) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L615)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The problem is we read `size` and then truncate the file. We may race the truncate to actually shrink the file and lose data. Note that normal `fallocate` does not have this problem, since specifying len + offset smalle than file won't destroy any data.
</blockquote></details>

I see. So ideally we want an inter-process lock here, with sending a notification that the size of the file changed.

I still think this implementation is useful, and we already have similar synchronization problems in other syscall implementations -- @pwmarcz may say which ones exactly (or that I'm wrong). So a TODO would be fine here.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_util.c, line 64 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-T9ZPc6QeYJ4E-velT:-N-XRi7i84twMRcwSEDB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/fs/shim_fs_util.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to adding the comment.

I'm fine with `PAGE_SIZE`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 568 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TqMSu5kYS9s8xiYOD:-N-U1o19-cXH3WF6R70M:bw9yffv) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L568)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about support for the `FALLOC_FL_KEEP_SIZE` flag? If the mode is zero and this flag is set, we can just do a no-op and return success.

Similarly, there is also `FALLOC_FL_UNSHARE` flag. Well, I don't think we can support this flag. I also don't think any sane workload will use it.
</blockquote></details>

There are even more flags, but we've not seen a workload using them. I wouldn't bother implementing, unless we need to.
___
*[LibOS/shim/src/sys/shim_open.c, line 577 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TDcm69GHtY74tf2Yu:-N-XRklZ-lQrMfQZ8Nen:bzewu1v) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L577)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All right, I'm not in sync with all the fs changes.
Done.
Update: not done. Pipes do not have inode...

Unrelated: why do we need `handle->is_dir` if we can check `handle->inode->type`? I suppose all dir handles have `inode`...

</blockquote></details>

Ok, should be better now.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_open.c, line 568 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TqMSu5kYS9s8xiYOD:-N-XYDpM4_5oIyF1cf-i:b1yb4sj) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L568)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There are even more flags, but we've not seen a workload using them. I wouldn't bother implementing, unless we need to.
</blockquote></details>

OK, sounds fair.
___
*[LibOS/shim/src/sys/shim_open.c, line 593 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-XY_sG81FywQrQFzd6:-N-XY_sG81FywQrQFzd7:bmytjkx) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L593)):*
> ```C
>         goto out;
>     }
>     if (handle->is_dir) {
> ```

So what about this missing check on the directory? This check was redundant?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_open.c, line 593 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-XY_sG81FywQrQFzd6:-N-XZkFY3g6DX4iMeo7P:bxu9uhf) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L593)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So what about this missing check on the directory? This check was redundant?
</blockquote></details>

It wasn't, but is not needed in the new version (which checks `S_IFREG` instead of filesystem type).

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

**Review by pwmarcz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_open.c, line 614 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TDBS11imDREux-vrg:-N-Y16dL4TTw9uKhYIaM:b-kcmxcs) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L614)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done? I see no diff on this line.
___
*[LibOS/shim/src/sys/shim_open.c, line 615 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TBVT46MwXq-YElO4b:-N-Y1ISXBFkdoqsg27o4:b-ur9f17) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L615)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see. So ideally we want an inter-process lock here, with sending a notification that the size of the file changed.

I still think this implementation is useful, and we already have similar synchronization problems in other syscall implementations -- @pwmarcz may say which ones exactly (or that I'm wrong). So a TODO would be fine here.
</blockquote></details>

@dimakuv I'm sure you're right, but I don't remember where else we have such problems.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/sys/shim_open.c, line 614 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TDBS11imDREux-vrg:-N-Y8Csj7KbzzJTZ5luh:bwqsnu1) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L614)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Not done? I see no diff on this line.
</blockquote></details>

Indeed not done.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_open.c, line 614 at r1](https://reviewable.io/reviews/gramineproject/gramine/522#-N-TDBS11imDREux-vrg:-N-YKCxJ6pDlE2dglpg8:brm26ly) ([raw file](https://github.com/gramineproject/gramine/blob/4b445dcd2f1a7a203dd1a8f22e683e24287d5d80/LibOS/shim/src/sys/shim_open.c#L614)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indeed not done.
</blockquote></details>

Idk, what happened, I remember fixing it...
Should be done now.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pwmarcz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/522)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
