### PR TITLE
[CI-Examples] Drop hacks in Makefiles for old Make versions

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Part of the 20.04 deprecation - we can finally use modern and less buggy tools!

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2050)

### CODE REVIEW

**Review by kailun-qin — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2050)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2050)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`CI-Examples/README.md` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2050#-OAvhoGY94nWg7fsHWpg:-OAvhoGY94nWg7fsHWph:b-mp2f4z) ([raw file](https://github.com/gramineproject/gramine/blob/4da3fc6f715e3aecb122a8810cac7355de757c9b/CI-Examples/README.md#L4)):*
> ```Markdown
> 
> This folder contains application integration examples. They are tested on
> Ubuntu 22.04 and 24.04.
> ```

24.04. and 22.04 please, as in other PR.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2050)* status: 14 of 15 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`CI-Examples/README.md` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2050#-OAvhoGY94nWg7fsHWpg:-OAwmSFl1wI-GaAITRHp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4da3fc6f715e3aecb122a8810cac7355de757c9b/CI-Examples/README.md#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

24.04. and 22.04 please, as in other PR.
</blockquote></details>

Done.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2050)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2050)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2050)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2050)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
