### PR TITLE
Drop support for dictionary syntax for files in manifest

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

We've been printing a warning about this for half a year and two releases (1.0 and 1.1) now, time to get rid of it.

And also we can finally fix the checksum vs hash confusion in our codebase.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwulmrBbGN2o1aQUc8:-MuwulmrBbGN2o1aQUc9:b3x72yq) (no related file):*
> How to test this PR? 
> CI.

CI disagreed :)

---
___
*[Documentation/tutorials/pytorch/index.rst, line 263 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwvrdDBFvVX9wPEGRG:-MuwvrdEBFxxfioLJZuC:b-e6xri7) ([raw file](https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/Documentation/tutorials/pytorch/index.rst#L263)):*
> ```reStructuredText
> the actual file name.
> 
> The way these Trusted Files work is before Gramine runs PyTorch inside the SGX
> ```

Why did you drop this paragraph?
___
*[Documentation/tutorials/pytorch/index.rst, line 264 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwvab48yi3I_rgxVhe:-Muwvab48yi3I_rgxVhf:b-aru0tb) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/Documentation/tutorials/pytorch/index.rst#L264)):*
> ```reStructuredText
> files inside them are hashed.
> 
> The PyTorch manifest template also contains ``sgx.allowed_files`` list. They
> ```

`they specify` -> `it specifies`
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 710 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwwlt2A4hJBykH1oBn:-Muwwlt2A4hJBykH1oBo:b-9dqbxz) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/Pal/src/host/Linux-SGX/enclave_framework.c#L710)):*
> ```C
>         if (ret < 0) {
>             log_error("normalize_and_register_file(\"%s\", \"%s\") failed", toml_trusted_uri_str,
>                       toml_trusted_sha256_str);
> ```

Printing `ret` could be useful as well
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 770 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwwuSG3folHflqgetk:-MuwwuSHB-ocKooZCYLv:bks3kfr) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/Pal/src/host/Linux-SGX/enclave_framework.c#L770)):*
> ```C
>         ret = normalize_and_register_file(toml_allowed_file_str, /*hash_str=*/NULL);
>         if (ret < 0) {
>             log_error("normalize_and_register_file(\"%s\", NULL) failed", toml_allowed_file_str);
> ```

ditto (`ret`)
___
*[python/graminelibos/manifest.py, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwx20d-FbyotYBuT3l:-Muwx20d-FbyotYBuT3m:brdolvp) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/python/graminelibos/manifest.py#L3)):*
> ```Python
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # Copyright (c) 2021 Wojtek Porczyk <woju@invisiblethingslab.com>
> # Copyright (c) 2022 Intel Corporation
> ```

Shouldn't this list all years?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: 6 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwulmrBbGN2o1aQUc8:-MuwyIcD3-3dLcWA-Bw5:b-ckkt5m) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> How to test this PR? 
> CI.

CI disagreed :)
</blockquote></details>

Fixed (pylint, this time surprisingly with a valid issue).

---
___
*[Documentation/tutorials/pytorch/index.rst, line 263 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwvrdDBFvVX9wPEGRG:-MuwySCs-o-Oy0tCMWLU:bynwlg6) ([raw file](https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/Documentation/tutorials/pytorch/index.rst#L263)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you drop this paragraph?
</blockquote></details>

Because now I describe almost all of this above. Didn't see a point in repeating this and not sure if mentioning `gramine-sgx-sign` here is important.
___
*[Documentation/tutorials/pytorch/index.rst, line 264 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwvab48yi3I_rgxVhe:-Muwynpg4oopV0iMecoO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/Documentation/tutorials/pytorch/index.rst#L264)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`they specify` -> `it specifies`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 710 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwwlt2A4hJBykH1oBn:-Muwz-BfBn5B-__qm2wk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/Pal/src/host/Linux-SGX/enclave_framework.c#L710)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Printing `ret` could be useful as well
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 770 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwwuSG3folHflqgetk:-Muwz4ao2RRe1hAfklvo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/Pal/src/host/Linux-SGX/enclave_framework.c#L770)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`ret`)
</blockquote></details>

Done.
___
*[python/graminelibos/manifest.py, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwx20d-FbyotYBuT3l:-Muwz64L8J-Huf-lfT9l:b-d0kiv5) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/python/graminelibos/manifest.py#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this list all years?
</blockquote></details>

I don't think so, for most cases I think only the most recent change is important.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/tutorials/pytorch/index.rst, line 263 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwvrdDBFvVX9wPEGRG:-MuxDZYQ7aN5m4mccWML:b-4j6mei) ([raw file](https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/Documentation/tutorials/pytorch/index.rst#L263)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because now I describe almost all of this above. Didn't see a point in repeating this and not sure if mentioning `gramine-sgx-sign` here is important.
</blockquote></details>

Previous version described in detail, that this list is iterated, hashes gathered and a new manifest is created, with these hashes. Now this info is missing.
Current version basically says: set all needed files in this list, some magic will happen, something gets hashed somewhere, all is secure, don't bother looking into details.
___
*[python/graminelibos/manifest.py, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwx20d-FbyotYBuT3l:-MuxEoBT-OnCSBqKf7y8:bqzaqi1) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/python/graminelibos/manifest.py#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think so, for most cases I think only the most recent change is important.
</blockquote></details>

I think for copyrights it should be the first year, not most recent.
If you are not sure how this should be (I'm definitely not), leave the old version/list all years. I guess I would prefer the latter, in this case `2020-2022`

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/374#-MuyzEvv6aQz0Bp7m8Un:-MuyzEvwBbU54ow195Gn:bya9p6h) (no related file):*
So this PR is in preparation for release v1.2, right? I mean, we agreed previously that we keep legacy deprecated features for only two releases, and so this TOML-dictionary syntax is available on v1.0 and v1.1, and with this PR it won't be available on v1.2.

Makes sense to me. Do we have any other features that are deprecated from v1.0 (other than "booleans as 1/0")? We can remove them as well. I found these points in our documentation, we need to check them:

- https://gramine.readthedocs.io/en/latest/manifest-syntax.html#libos-entrypoint -- see the NOTE. Is this something that is still supported @pwmarcz? If yes, we can drop it in v1.2.
- https://gramine.readthedocs.io/en/latest/manifest-syntax.html#preloaded-library-deprecated-option

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz3Ord3jbxHn4qShyO:-Muz3Ord3jbxHn4qShyP:bgpf05m) (no related file):*
I verified manually that Examples and GSC do *not* use the deprecated syntax, so we should be good.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz3laN8VGmylLERzkQ:-Muz3laN8VGmylLERzkR:bvja66e) (no related file):*
Found this un-modified snippet: https://gramine.readthedocs.io/en/latest/manpages/gramine-manifest.html#example

---
___
*[Documentation/tutorials/pytorch/index.rst, line 263 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwvrdDBFvVX9wPEGRG:-Muz06mS4Z40LZylNL5C:betqj8h) ([raw file](https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/Documentation/tutorials/pytorch/index.rst#L263)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Previous version described in detail, that this list is iterated, hashes gathered and a new manifest is created, with these hashes. Now this info is missing.
Current version basically says: set all needed files in this list, some magic will happen, something gets hashed somewhere, all is secure, don't bother looking into details.
</blockquote></details>

What about the compromise variant: we add one sentence to the previous paragraph (kept by Michal and modified) that says something like `The file hashes are calculated during the generation of the final SGX manifest file (using the utility gramine-sgx-sign) and appended to this manifest file, to be read in runtime by Gramine.`

I don't see a need in the whole paragraph, but one sentence describing the magic behind the scenes doesn't hurt.
___
*[Documentation/tutorials/pytorch/index.rst, line 374 at r2](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz1IuN9nYn-pvT7dry:-Muz1IuN9nYn-pvT7drz:bpbtzfb) ([raw file](https://github.com/gramineproject/gramine/blob/228f223196a8392d0f3e69a5ebabb79f0abcbc5f/Documentation/tutorials/pytorch/index.rst#L374)):*
> ```reStructuredText
> 
>    cd <gramine repository>/CI-Examples/ra-tls-secret-prov
>    make -C ../../Pal/src/host/Linux-SGX/tools/ra-tls dcap
> ```

This is wrong, we modified the installation of Gramine to have DCAP libraries already. This step is not needed at all.

Michal, do you want to change these places in this PR, or should we ignore these? I have a couple more comments like this.
___
*[Documentation/tutorials/pytorch/index.rst, line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz1abiBWtEudsoPrxO:-Muz1abiBWtEudsoPrxP:b-3b2wzt) ([raw file](https://github.com/gramineproject/gramine/blob/228f223196a8392d0f3e69a5ebabb79f0abcbc5f/Documentation/tutorials/pytorch/index.rst#L380)):*
> ```reStructuredText
> for preparation and verification of SGX quotes (needed for SGX remote
> attestation). The last line builds the required DCAP binaries and copies
> relevant Gramine utilities such as ``pf_crypt`` to encrypt input files.
> ```

This last sentence is meaningless now, that we install Gramine with all the required libs and utilities.
___
*[Documentation/tutorials/pytorch/index.rst, line 409 at r2](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz1kcR5EmKxBh-ncgD:-Muz1kcR5EmKxBh-ncgE:b629kt) ([raw file](https://github.com/gramineproject/gramine/blob/228f223196a8392d0f3e69a5ebabb79f0abcbc5f/Documentation/tutorials/pytorch/index.rst#L409)):*
> ```reStructuredText
>    cp <gramine repository>/CI-Examples/ra-tls-secret-prov/libs/libsgx_util.so .
>    cp <gramine repository>/CI-Examples/ra-tls-secret-prov/libs/libmbed*.so* .
>    cp <gramine repository>/CI-Examples/ra-tls-secret-prov/pf_crypt .
> ```

All this copying is meaningless.
___
*[Documentation/tutorials/pytorch/index.rst, line 424 at r2](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz1mk67v6gmUzvgTn4:-Muz1mk67v6gmUzvgTn5:b-kw7dav) ([raw file](https://github.com/gramineproject/gramine/blob/228f223196a8392d0f3e69a5ebabb79f0abcbc5f/Documentation/tutorials/pytorch/index.rst#L424)):*
> ```reStructuredText
>    LD_LIBRARY_PATH=. ./pf_crypt encrypt -w files/wrap-key -i plaintext/input.jpg -o input.jpg
>    LD_LIBRARY_PATH=. ./pf_crypt encrypt -w files/wrap-key -i plaintext/classes.txt -o classes.txt
>    LD_LIBRARY_PATH=. ./pf_crypt encrypt -w files/wrap-key -i plaintext/alexnet-pretrained.pt -o alexnet-pretrained.pt
> ```

This should be simply `gramine-sgx-pf-crypt`
___
*[Documentation/tutorials/pytorch/index.rst, line 547 at r2](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz1uYZ2ZDpiRd4jKyx:-Muz1uYZ2ZDpiRd4jKyy:b-kw7dav) ([raw file](https://github.com/gramineproject/gramine/blob/228f223196a8392d0f3e69a5ebabb79f0abcbc5f/Documentation/tutorials/pytorch/index.rst#L547)):*
> ```reStructuredText
> encryption of input files. In order to decrypt it, use the following command::
> 
>    LD_LIBRARY_PATH=. ./pf_crypt decrypt -w files/wrap-key -i result.txt -o plaintext/result.txt
> ```

This should be simply `gramine-sgx-pf-crypt`

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/374#-MuyzEvv6aQz0Bp7m8Un:-MuzG3rB5leIIIoJbpEU:b-qpdepx) (no related file):*
>https://gramine.readthedocs.io/en/latest/manifest-syntax.html#libos-entrypoint -- see the NOTE. Is this something that is still supported @pwmarcz? If yes, we can drop it in v1.2.

We support the `file:` prefix by stripping it and displaying a warning (in `shim_handle.c`). The NOTE doesn't say anything about that support, it just tells you to remove the `file:` prefix yourself. But I agree both the code and the note can be removed, the old syntax with `file:` is from before 1.0.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/374#-MuyzEvv6aQz0Bp7m8Un:-MuzRefH36NwZMkibWPi:b-jf3kye) (no related file):*
> So this PR is in preparation for release v1.2, right?

Yup. Mostly to not forget doing it later.

> I found these points in our documentation, we need to check them:

I'll prepare another PRs to drop them.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz3Ord3jbxHn4qShyO:-MuzS1vM37nRiVzU8O0q:b-ucfknh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I verified manually that Examples and GSC do *not* use the deprecated syntax, so we should be good.
</blockquote></details>

Thanks!

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz3laN8VGmylLERzkQ:-MuzSONWCCvU6AW1k3Vd:bske53w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Found this un-modified snippet: https://gramine.readthedocs.io/en/latest/manpages/gramine-manifest.html#example
</blockquote></details>

But I _do_ fix it in this PR?

---
___
*[Documentation/tutorials/pytorch/index.rst, line 263 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwvrdDBFvVX9wPEGRG:-MuzSYWc08XXzKCRnQyD:b-igzby8) ([raw file](https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/Documentation/tutorials/pytorch/index.rst#L263)):*
> set all needed files in this list, some magic will happen, something gets hashed somewhere, all is secure, don't bother looking into details.

I don't agree with this, it says exactly what the user needs to know - that we'll hash the file contents build-time and then allow using the files in runtime only if the hash matches. That's all the user needs to know and it's enough to understand security properties of it, it's not "some magic and it's secure".

> `The file hashes are calculated during the generation of the final SGX manifest file (using the utility gramine-sgx-sign) and appended to this manifest file, to be read in runtime by Gramine.`

But I already say "will be hashed during build and allowed to be read later in runtime only if the hash matches", it would mostly be a repetition. Or you mean replacing this sentence with yours?
___
*[Documentation/tutorials/pytorch/index.rst, line 374 at r2](https://reviewable.io/reviews/gramineproject/gramine/374#-Muz1IuN9nYn-pvT7dry:-MuzTPk6AmTcxoMlZWdE:b-djfq7y) ([raw file](https://github.com/gramineproject/gramine/blob/228f223196a8392d0f3e69a5ebabb79f0abcbc5f/Documentation/tutorials/pytorch/index.rst#L374)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is wrong, we modified the installation of Gramine to have DCAP libraries already. This step is not needed at all.

Michal, do you want to change these places in this PR, or should we ignore these? I have a couple more comments like this.
</blockquote></details>

No, let's do this separately, I already have enough discussions open here :P Do you maybe want to submit a PR for these? You know all the RA stuff much better than me.
___
*[python/graminelibos/manifest.py, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwx20d-FbyotYBuT3l:-MuzTjSc33BbUmLQU2og:bn2fy9t) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/python/graminelibos/manifest.py#L3)):*
> I think for copyrights it should be the first year, not most recent.

Aren't they here mostly to know when someone's copyright ends? (i.e. after N years you loose it according to law) Why would it matter when it started?

This is a simplification anyways, the real copyrights are per-change and each changed part of the code has a date of creation where it copyright starts. So, here it's just a simplified info to give you the rough idea who may still be owning copyright to this code.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: 8 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Documentation/tutorials/pytorch/index.rst, line 263 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-MuwvrdDBFvVX9wPEGRG:-MuzXkL57YehNN51U_XB:b-47yzv) ([raw file](https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/Documentation/tutorials/pytorch/index.rst#L263)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I meant expanding your sentence.
</blockquote></details>

Check now.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[python/graminelibos/manifest.py, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwx20d-FbyotYBuT3l:-MuzoJoXEDAeQL7Wkr3q:b2nfddv) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/python/graminelibos/manifest.py#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I think for copyrights it should be the first year, not most recent.

Aren't they here mostly to know when someone's copyright ends? (i.e. after N years you loose it according to law) Why would it matter when it started?

This is a simplification anyways, the real copyrights are per-change and each changed part of the code has a date of creation where it copyright starts. So, here it's just a simplified info to give you the rough idea who may still be owning copyright to this code.
</blockquote></details>

Since when law started to follow logic?

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[python/graminelibos/manifest.py, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwx20d-FbyotYBuT3l:-Muzsz_46lYpWHvJoaXY:bh4qzko) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/python/graminelibos/manifest.py#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Since when law started to follow logic?
</blockquote></details>

I nominate this as the Best Comment of the Year.

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[python/graminelibos/manifest.py, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/374#-Muwx20d-FbyotYBuT3l:-Mv-C_qMDuK-HsSAGR2P:b-q9wx59) ([raw file](https://github.com/gramineproject/gramine/blob/d1a59c13a49fe4199e9145f2d28751157980f10a/python/graminelibos/manifest.py#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I nominate this as the Best Comment of the Year.
</blockquote></details>

Ok, did some googling and it seems that these copyright notices are mostly useless anyways and are more like "FYI, this code is governed by some copyrights" but the copyrights would work even without any notices. So, I'd use the simplest version which is useful for anyone interested in using this code, which is IMO listing the owner plus the most recent update (to know when the code will go to the public domain).
I'll prepare a quick PR to make it more clear in our contributing guide.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/374)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
