### PR TITLE
[Docs] Update Cloud Deployment instructions

### PR DESCRIPTION
**Pull request by mythi**
## Description of the changes 

Minor updates to the cloud deployment instuctions based on a quick
sanity check using Ubuntu 20.04 based VMs with both DCsv2 and
DCsv3 instances.

These nodes run with the upstream SGX.

Fixes: #138

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/216)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/216)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mythi)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/216#-MoDwkqt8M8EC0bvQ6yI:-MoDwkqt8M8EC0bvQ6yJ:bgjrcp4) (no related file):*
@mythi Feel free to git-amend and git-force-push this PR to fix the commit message.

---
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/216#-MoDwA5v7KGkFcL4vBMS):*
Fix please: `...the upstream SGX driver`.
___
*[Documentation/cloud-deployment.rst, line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/216#-MoDwLHb58O6F1p_Q_Hl:-MoDwLHb58O6F1p_Q_Hm:b6jtwhx) ([raw file](https://github.com/gramineproject/gramine/blob/e143e244b7c3bbcf6898c098730c5305dbe84b20/Documentation/cloud-deployment.rst#L21)):*
> ```reStructuredText
> <https://docs.microsoft.com/en-us/azure/virtual-machines/dcv2-series>`__ and
> `DCsv3 <https://docs.microsoft.com/en-us/azure/virtual-machines/dcv3-series>`__
> VM instances. The description below uses a DCsv3 VM running Ubuntu 20.04.
> ```

Could you surround `DCsv3 VM` with `*` (to make it italic font), for better visibility for readers? This is a very important point here.
___
*[Documentation/cloud-deployment.rst, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/216#-MoDwU_47qBIh2ZszfQV:-MoDwU_47qBIh2ZszfQW:b-p7ql0d) ([raw file](https://github.com/gramineproject/gramine/blob/e143e244b7c3bbcf6898c098730c5305dbe84b20/Documentation/cloud-deployment.rst#L36)):*
> ```reStructuredText
>        autoconf bison gawk libcurl4-openssl-dev libprotobuf-c-dev ninja-build \
>        protobuf-c-compiler python3 python3-click python3-jinja2 python3-pip \
>        python3-protobuf wget pkg-config
> ```

Could you sort `pkg-config` in this list? It will go right before `protobuf-c-compiler`.

**Comment by mythi** [comment]
@dimakuv all comments addressed

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/216)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/216)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/216)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/216)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
