### PR TITLE
[LibOS] Remove more unused kernel stuff

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

As suggested by @pwmarcz in #183. Those are unused.

## How to test this PR?

No stipulation.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/184)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/184)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[-- commits, line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/184#-MnBPeqj1qwidDn0dmb1):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to everyone (Michal, Borys, Pawel). No need for split in commits, just a single commit.
</blockquote></details>

@woju Do you want to rebase this PR with all commits squashed into one? Alternatively, I can do it.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/184)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[-- commits, line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/184#-MnBPeqj1qwidDn0dmb1):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Do you want to rebase this PR with all commits squashed into one? Alternatively, I can do it.
</blockquote></details>

@woju Ping.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/184)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow, @pwmarcz, and @woju)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/184#-MpH466DDDR7HoTGak9p):*
https://reviewable.io/reviews/gramineproject/gramine/157#-MmJiqX62fIGC3EuwtwM

**Review by pwmarcz — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/184)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/184)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/184)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/184)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/184#-MpH466DDDR7HoTGak9p):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

https://reviewable.io/reviews/gramineproject/gramine/157#-MmJiqX62fIGC3EuwtwM
</blockquote></details>

Fixed after talking with woju that he's ok with this.
___
*[-- commits, line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/184#-MvJ3KTA3pNqNrFGSJu8):*
FYI: I noticed that woju missed some more declarations which can also be deleted, so I just added them to this commit.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/184)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

**Pull request merged**
