### PR TITLE
[LibOS] Change prefix from `shim_` do `libos_`

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This is main part of the rename - changes prefix on everything in LibOS code.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/681)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/681)* status: 0 of 124 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/681#-N5I3-xi41BVHbfew09w:-N5I3-xi41BVHbfew09x:b-r1q4v6) (no related file):*
https://github.com/gramineproject/gramine/pull/680 must be merged first

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 124 of 124 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/681)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/681#-N5I3-xi41BVHbfew09w:-N5JYVY42zRSZGQXvbWv:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

https://github.com/gramineproject/gramine/pull/680 must be merged first
</blockquote></details>

Done.

___
___
*[`Documentation/index.rst` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/681#-N5JZ3Kk7DF6kN3OzrHo:-N5JZ3Kk7DF6kN3OzrHp:b-uxkxd5) ([raw file](https://github.com/gramineproject/gramine/blob/a5ddd167b51f6d2ba130840c759e0ebabe74a10a/Documentation/index.rst#L109)):*
> ```reStructuredText
>    :caption: LibOS
> 
>    libos/libos-init
> ```

There was a bug in this PR. The reference to the `shim-init.rst` file was changed to `libos-init.rst`, but the file was not renamed itself.
___
*[`Documentation/devel/new-syscall.rst` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/681#-N5JZgW95YJJlaN6UaUh:-N5JZgW95YJJlaN6UaUi:biz713o) ([raw file](https://github.com/gramineproject/gramine/blob/a5ddd167b51f6d2ba130840c759e0ebabe74a10a/Documentation/devel/new-syscall.rst#L10)):*
> ```reStructuredText
> 
> For example, assume we are implementing :manpage:`sched_setaffinity(2)`. You
> must add the prototype of the function implementing it to :file:`shim_table.h`::
> ```

FYI: Reminder for myself and other reviewers: this PR does **not** change filenames, so here the reference to `shim_table.h` is correct. This will be changed in a follow-up PR.

I only took a liberty to rename one file inside `Documentation/`, because that change was simple and contained.
___
*[`libos/include/shim_table.h` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/681#-N5Jb-Ad5PgUuCbN3VX-:-N5Jb-Ad5PgUuCbN3VX0:b-e5q6d4) ([raw file](https://github.com/gramineproject/gramine/blob/a5ddd167b51f6d2ba130840c759e0ebabe74a10a/libos/include/shim_table.h#L18)):*
> ```objc
> typedef void (*libos_syscall_t)(void);
> 
> extern libos_syscall_t libos_table[];
> ```

`libos_table` doesn't mean much. I suggest to rename to `libos_syscall_table`.

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/681)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[`Documentation/index.rst` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/681#-N5JZ3Kk7DF6kN3OzrHo:-N5Ji-Y22FA98Q3EEL30:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a5ddd167b51f6d2ba130840c759e0ebabe74a10a/Documentation/index.rst#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There was a bug in this PR. The reference to the `shim-init.rst` file was changed to `libos-init.rst`, but the file was not renamed itself.
</blockquote></details>

Done
___
*[`libos/include/shim_table.h` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/681#-N5Jb-Ad5PgUuCbN3VX-:-N5Ji0lb0gN4sBxy95f9:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a5ddd167b51f6d2ba130840c759e0ebabe74a10a/libos/include/shim_table.h#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`libos_table` doesn't mean much. I suggest to rename to `libos_syscall_table`.
</blockquote></details>

Done

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/681)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`Documentation/index.rst` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/681#-N5JZ3Kk7DF6kN3OzrHo:-N5L0cWNCjQPEkybj-Bd:bkv2qsq) ([raw file](https://github.com/gramineproject/gramine/blob/a5ddd167b51f6d2ba130840c759e0ebabe74a10a/Documentation/index.rst#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I wanted to avoid any file renames in this PR, but I guess this one shouldnt be a problem

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 121 of 124 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/681)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5MeYX84baJI2pIW8FY):*




_Suggestion:_
```
from `shim_` to `libos_`
```
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5Mect65QxNfZN20gq1):*




_Suggestion:_
```
This is the main
```
___
*[`libos/include/shim_types.h` line 159 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5MmpGd3chI8ybTSwG0:-N5MmpGd3chI8ybTSwG1:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/44cd806683534d6db0f198c335e6e4f0f57a2cd5/libos/include/shim_types.h#L159)):*
> ```objc
> typedef Elf64_auxv_t elf_auxv_t;
> 
> /* typedef for libos internal types */
> ```





_Suggestion:_
```objc
LibOS
```
___
*[`libos/src/shim_checkpoint.c` line 366 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5MninA5ucoDX6ulhZU:-N5MninA5ucoDX6ulhZV:b-ocjdwn) ([raw file](https://github.com/gramineproject/gramine/blob/44cd806683534d6db0f198c335e6e4f0f57a2cd5/libos/src/shim_checkpoint.c#L366)):*
> ```C
> 
>     struct libos_palhdl_entry* palhdl_entries = (struct libos_palhdl_entry*)(base +
>                                                                            hdr->palhdl_offset);
> ```

alignment broke here
___
*[`libos/src/arch/x86_64/shim_context.c` line 81 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5Mq61p9eHoF4qjFT4C:-N5Mq61p9eHoF4qjFT4D:b-w1j229) ([raw file](https://github.com/gramineproject/gramine/blob/44cd806683534d6db0f198c335e6e4f0f57a2cd5/libos/src/arch/x86_64/shim_context.c#L81)):*
> ```C
> 
>     struct libos_xstate* xstate = (struct libos_xstate*)xstate_extended;
>     char* bytes_after_xstate   = (char*)xstate_extended + g_libos_xsave_size;
> ```

please fix alignment (ideally, just remove it)
___
*[`libos/src/sys/shim_poll.c` line 58 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5N2Dg93TOK6VmqiLFC:-N5N2Dg93TOK6VmqiLFD:b-2y6s2h) ([raw file](https://github.com/gramineproject/gramine/blob/44cd806683534d6db0f198c335e6e4f0f57a2cd5/libos/src/sys/shim_poll.c#L58)):*
> ```C
>     struct fds_mapping_t {
>         struct libos_handle* hdl; /* NULL if no mapping (handle is not used in polling) */
>         nfds_t idx;              /* index from fds array to pals array */
> ```

please fix alignment

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/681)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5MeYX84baJI2pIW8FY):*
Done.
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5Mect65QxNfZN20gq1):*
Done.
___
*[`libos/include/shim_types.h` line 159 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5MmpGd3chI8ybTSwG0:-N5N5SvZ9R8JVRVREH3D:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/44cd806683534d6db0f198c335e6e4f0f57a2cd5/libos/include/shim_types.h#L159)):*
> ```objc
> typedef Elf64_auxv_t elf_auxv_t;
> 
> /* typedef for libos internal types */
> ```

Done.
___
*[`libos/src/shim_checkpoint.c` line 366 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5MninA5ucoDX6ulhZU:-N5N5iPk2yyVWpCqjb6p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/44cd806683534d6db0f198c335e6e4f0f57a2cd5/libos/src/shim_checkpoint.c#L366)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

alignment broke here
</blockquote></details>

Done.
___
*[`libos/src/arch/x86_64/shim_context.c` line 81 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5Mq61p9eHoF4qjFT4C:-N5N5qUu9RhLSYpkwIsE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/44cd806683534d6db0f198c335e6e4f0f57a2cd5/libos/src/arch/x86_64/shim_context.c#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment (ideally, just remove it)
</blockquote></details>

Done.
___
*[`libos/src/sys/shim_poll.c` line 58 at r2](https://reviewable.io/reviews/gramineproject/gramine/681#-N5N2Dg93TOK6VmqiLFC:-N5N5vCh5VNRtmMRTYKh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/44cd806683534d6db0f198c335e6e4f0f57a2cd5/libos/src/sys/shim_poll.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/681)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/681)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
