### PR TITLE
[LibOS] Remove `shim_qstr`

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

This finishes the conversion: all usages of `shim_qstr` use regular heap-allocated C strings instead.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEnI985izbs9MzEudF:-MqEnI99EBj34ITb1gRr:b-83sjoh) (no related file):*
Nice!

---
___
*[LibOS/shim/include/shim_handle.h, line 220 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEjV2P1zZR0y-F4qLS:-MqEjV2P1zZR0y-F4qLT:b-n1eb60) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/include/shim_handle.h#L220)):*
> ```objc
>     bool needs_et_poll_out;
> 
>     char* uri; /* PAL URI for this handle (if any). Does not change. */
> ```

Is it possible to add `const` here or do we use it as `char*` somewhere?
___
*[LibOS/shim/src/sys/shim_pipe.c, line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEmPur-eEkG3vh8rE8:-MqEmPur-eEkG3vh8rE9:b-qlw37x) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/src/sys/shim_pipe.c#L58)):*
> ```C
>     cli->uri = strdup(uri);
>     if (!srv->uri || !cli->uri) {
>         ret = -ENOENT;
> ```

NP: we should free both `uri`s and set them to NULL here

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/sys/shim_pipe.c, line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEmPur-eEkG3vh8rE8:-MqEnVXmCD6fy7mBF8V-:b-wginx3) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/src/sys/shim_pipe.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: we should free both `uri`s and set them to NULL here
</blockquote></details>

Scratch that, it's ok (we free these uris together with handles).

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_handle.h, line 220 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEjV2P1zZR0y-F4qLS:-MqEzpgQ7hV0KKz2tc1e:b-7r4gmu) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/include/shim_handle.h#L220)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is it possible to add `const` here or do we use it as `char*` somewhere?
</blockquote></details>

We don't modify it, but it's owned by this object and freed by it. I think using `const char*` (and later `free((char*)hdl->uri)`) would make that ownership less visible, suggest you can assign string literals to it, etc.

(The same happened earlier with `shim_dentry.name`, which also newer changes, and is also an owned `char*` field).

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 727 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEy3ln6uvAIIxX9cRL:-MqEy3ln6uvAIIxX9cRM:bsyhaxa) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/src/bookkeep/shim_handle.c#L727)):*
> ```C
> 
>         if (hdl->uri)
>             DO_CP_MEMBER(str, hdl, new_hdl, uri);
> ```

How actually is `uri` buffer migrated? Here we only copy the pointer. I'm also not sure how this code worked before, but I'm probably missing something.
___
*[LibOS/shim/src/sys/shim_pipe.c, line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEzYS77ClJLmEQ82W8:-MqEzYS77ClJLmEQ82W9:b-uln2mt) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/src/sys/shim_pipe.c#L78)):*
> ```C
>     ret = 0;
> 
> out:
> ```

Don't we need to free `srv->uri` and `cli->uri` here on error? (if so, then be careful, they may be uninitialized at some points)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: 16 of 17 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 727 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEy3ln6uvAIIxX9cRL:-MqF6n7r7Ls3BOsPp5Xj:b2i6ca6) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/src/bookkeep/shim_handle.c#L727)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How actually is `uri` buffer migrated? Here we only copy the pointer. I'm also not sure how this code worked before, but I'm probably missing something.
</blockquote></details>

`DO_CP_MEMBER(str, ...)` calls the checkpoint function for "str", [see here](https://github.com/gramineproject/gramine/blob/1a7d2f7c06be31f5b38155b8fc493cdd52447e92/LibOS/shim/src/shim_checkpoint.c#L221).
___
*[LibOS/shim/src/sys/shim_pipe.c, line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEzYS77ClJLmEQ82W8:-MqF7h3j--z6xz8v660Y:b-apfv9n) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/src/sys/shim_pipe.c#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Don't we need to free `srv->uri` and `cli->uri` here on error? (if so, then be careful, they may be uninitialized at some points)
</blockquote></details>

They should be cleaned up together with handles. But since you're the second person to ask, it's probably less confusing to do it here.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 727 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEy3ln6uvAIIxX9cRL:-MqF8toCAo50IxGrc4pI:b-qfaanf) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/src/bookkeep/shim_handle.c#L727)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`DO_CP_MEMBER(str, ...)` calls the checkpoint function for "str", [see here](https://github.com/gramineproject/gramine/blob/1a7d2f7c06be31f5b38155b8fc493cdd52447e92/LibOS/shim/src/shim_checkpoint.c#L221).
</blockquote></details>

Ah, I see, thanks.
___
*[LibOS/shim/src/sys/shim_pipe.c, line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEzYS77ClJLmEQ82W8:-MqF9MHY8cTNPIOZCxeR:b-iys39z) ([raw file](https://github.com/gramineproject/gramine/blob/88390bcff1c78d32609e1a2596923a26d673cf4f/LibOS/shim/src/sys/shim_pipe.c#L78)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

They should be cleaned up together with handles. But since you're the second person to ask, it's probably less confusing to do it here.
</blockquote></details>

Ah, I see now, my confusion stems from my incorrect assumption that `srv` and `cli` are out-only arguments. But now I see that they are in-out, so the caller will need to free them anyways.

**Review by dimakuv — APPROVED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/267#-MqEnI985izbs9MzEudF:-MqFBOwU2HjCZjTf38gq:bemxspg) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Awesome PR! It's interesting how we finally removed a feature that was added as a "performance optimization".

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/267)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
