### PR TITLE
Release 1.6.2

### PR DESCRIPTION
**Pull request by woju**
Release PR for 1.6.2

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1808)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1808)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1808#-NshnASm-8lf9PpJpsst):*
Blocking until we drop `~rc1`.



_Code quote:_
```
~rc1
```
___
*[`debian/changelog` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1808#-NshnO99BOrnAzYDfvZw:-NshnO99BOrnAzYDfvZx:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f3873b573a65acacf044656686a9a24596b9b8d1/debian/changelog#L4)):*
> ```
> 
>   * version 1.6.2
>   * fixed security bug degenerating trusted_files to protected_files on fork
> ```





_Suggestion:_
```
  * fixed a security bug degenerating trusted_files to allowed_files on fork
```

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1808)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1808)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1808)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1808#-NshnASm-8lf9PpJpsst):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Blocking until we drop `~rc1`.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1808)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1808)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
