### PR TITLE
[LibOS] Remove the last usages of "shim" and "DK" names

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes

Found a few survivors left after the recent renamings.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/831)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/831)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/831)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`libos/src/sys/libos_clone.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aMLmB-v9aaws6zCh1:-N9aMLmC5y_a4giWKkur:b8acs46) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/libos/src/sys/libos_clone.c#L39)):*
> ```C
>  *    around the user provided function.
>  * 4) PAL layer allocates a stack and then invokes the clone syscall.
>  * 5) PAL runs thread_init function on PAL allocated Stack.
> ```

`Stack` -> `stack`
___
*[`libos/src/sys/libos_clone.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aMhYm3ydnNHGtbe5o:-N9aMhYm3ydnNHGtbe5p:b3bvqdh) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/libos/src/sys/libos_clone.c#L39)):*
> ```C
>  *    around the user provided function.
>  * 4) PAL layer allocates a stack and then invokes the clone syscall.
>  * 5) PAL runs thread_init function on PAL allocated Stack.
> ```

`thread_init` -> `pal_thread_init` (we recently renamed this func)
___
*[`libos/src/sys/libos_clone.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aMShcC-uyjmne-yru:-N9aMShcC-uyjmne-yrv:b-njbvbv) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/libos/src/sys/libos_clone.c#L41)):*
> ```C
>  * 5) PAL runs thread_init function on PAL allocated Stack.
>  * 6) thread_init calls our wrapper and gives the user provided stack address.
>  * 7) In the wrapper function, we just do the stack switch to user. Provided stack and execute the
> ```

`to user. Provided` -> `to user-provided`
___
*[`libos/src/sys/libos_clone.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aMVPu0lcGF-KJ5gyG:-N9aMVPu0lcGF-KJ5gyH:b-sxaacq) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/libos/src/sys/libos_clone.c#L42)):*
> ```C
>  * 6) thread_init calls our wrapper and gives the user provided stack address.
>  * 7) In the wrapper function, we just do the stack switch to user. Provided stack and execute the
>  *    user Provided function.
> ```

`user-provided`
___
*[`libos/src/sys/libos_clone.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aMlI_CgwFmg6l0Q7j:-N9aMlI_CgwFmg6l0Q7k:b-twdbi) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/libos/src/sys/libos_clone.c#L42)):*
> ```C
>  * 6) thread_init calls our wrapper and gives the user provided stack address.
>  * 7) In the wrapper function, we just do the stack switch to user. Provided stack and execute the
>  *    user Provided function.
> ```

In general, this comment is not that useful. I'm Ok to keep it, but I'm also Ok to remove it completely.
___
*[`pal/include/pal_internal.h` line 182 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aMwTp8hhi_5fusUHv:-N9aMwTp8hhi_5fusUHw:bp59zxf) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/pal/include/pal_internal.h#L182)):*
> ```objc
> int _PalGetCPUInfo(struct pal_cpu_info* info);
> 
> /* Internal PAL calls, in case any of the internal routines needs to use them */
> ```

`needs` -> `need`

Or just remove this comment.
___
*[`pal/include/pal_internal.h` line 248 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aN0JMELX1pjZwP77g:-N9aN0JMELX1pjZwP77h:beccp9w) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/pal/include/pal_internal.h#L248)):*
> ```objc
> pal_event_handler_t _PalGetExceptionHandler(enum pal_event event);
> 
> /* other PAL calls */
> ```

Just remove this?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/831)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`libos/src/sys/libos_clone.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aMlI_CgwFmg6l0Q7j:-N9bTA362L87RhGr1SL4:bhojlca) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/libos/src/sys/libos_clone.c#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In general, this comment is not that useful. I'm Ok to keep it, but I'm also Ok to remove it completely.
</blockquote></details>

Yeah, I didn't comment on it because it was already here, but I also don't think it's useful. It's also misleading/wrong in some parts...

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/831)* status: 1 of 3 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/sys/libos_clone.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aMlI_CgwFmg6l0Q7j:-N9d10u4BEAIzF0AOt79:b-efh9ol) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/libos/src/sys/libos_clone.c#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, I didn't comment on it because it was already here, but I also don't think it's useful. It's also misleading/wrong in some parts...
</blockquote></details>

Ok, removing, I also think it's super-low-quality and we'd be better without it.
___
*[`pal/include/pal_internal.h` line 182 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aMwTp8hhi_5fusUHv:-N9d1oKO0ggPPYK4G9JM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/pal/include/pal_internal.h#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`needs` -> `need`

Or just remove this comment.
</blockquote></details>

Done.
___
*[`pal/include/pal_internal.h` line 248 at r1](https://reviewable.io/reviews/gramineproject/gramine/831#-N9aN0JMELX1pjZwP77g:-N9d1rA64Ek_d05Twlqi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9742e71d8b0aaadeb438e59a13c8d89e5c016587/pal/include/pal_internal.h#L248)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just remove this?
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/831)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/831)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/831)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
