### PR TITLE
Change `num_*` to `*_cnt` naming for consistency

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

We use both conventions in various places, let's unify this.

## How to test this PR? 

CI, no functional changes intended.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)

### CODE REVIEW

**Review by vijaydhanraj — COMMENTED** [review]
Looks good, but I think `num_async_signals` variable got missed in https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux/pal_host.h#L124,
https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux/arch/x86_64/db_arch_exception.c#L31

Also, https://github.com/gramineproject/gramine/blob/master/LibOS/shim/include/arch/x86_64/shim_types-arch.h#L9 define be renamed from`NUM_SIGS`-> `SIGS_CNT`

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319#-:-Msh1Wok9GdFIgxa3Pcq:b-uhgsuw)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/319#-MsiJnwV1ElbWiZ3ZCew:-MsiJnwW4lPt0tb-zqit:bss8ft7) (no related file):*
I agree with Vijay, we should also change those two `num_` occurences.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: 9 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/319#-MsiJnwV1ElbWiZ3ZCew:-Msj78GFAaVNxzbC9zNY:b4540sv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Vijay, we should also change those two `num_` occurences.
</blockquote></details>

Fixed. I thought that these two were mimicking a standard POSIX function signature/macro, but seems it's not the case.

---

**Review by dimakuv — DISMISSED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/319#-MskWG5c5UyXj6wMzE8Y:-MskWG5c5UyXj6wMzE8Z:bmft85w) (no related file):*
Again, I have to verbosely disagree with this convention: when looking at names like `SIGS_CNT` I have no idea what `CNT` stands for - it doesn't seem to be "a well known" abbreviation.
While `NUM_SIGS` may sound a bit weird, at least it has clear meaning - "number of signals".
But since rest of you seem to be in favor of this, I'm not blocking.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/319#-MskWG5c5UyXj6wMzE8Y:-MskZCqg7P8Yu1A4AmfW:b-gayl0r) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Again, I have to verbosely disagree with this convention: when looking at names like `SIGS_CNT` I have no idea what `CNT` stands for - it doesn't seem to be "a well known" abbreviation.
While `NUM_SIGS` may sound a bit weird, at least it has clear meaning - "number of signals".
But since rest of you seem to be in favor of this, I'm not blocking.
</blockquote></details>

Hmm, I actually forgot that you were against this, sorry.
The problem with `NUM_ITEMS` for me is as you said, it reads weirdly, because there's "of" missing. `ITEMS_CNT` seem more natural for me and doesn't have this problem. Also, `_cnt` seem to be already more popular in our codebase (~3 times more popular).

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/319#-MskWG5c5UyXj6wMzE8Y:-Msl2nC6CcI93Ub-V8RS:b-w5ubca) (no related file):*
> Also, _cnt seem to be already more popular in our codebase (~3 times more popular).

Because you've already changed some of them :)

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/319#-MskWG5c5UyXj6wMzE8Y:-Msl8Ch26FoG2u6aF8hs:b-v61syp) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Also, _cnt seem to be already more popular in our codebase (~3 times more popular).

Because you've already changed some of them :)
</blockquote></details>

Hmm, that might have happened :P Although I don't remember, I only remember us discussing this topic some time ago, in the context I don't remember :)

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/319#-MskWG5c5UyXj6wMzE8Y:-Mslixfj7e89UHyS8Qd_:b-rrysib) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, that might have happened :P Although I don't remember, I only remember us discussing this topic some time ago, in the context I don't remember :)
</blockquote></details>

Approving just so you can merge faster

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/319)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
