### PR TITLE
[Docs] Update DCAP orientation guide to 1.14

### PR DESCRIPTION
**Pull request by kailun-qin**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/769)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/769)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-20.04 please (`fcntl14_64` LTP test failed, cannot reproduce locally and clearly unrelated)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`fdatasync01` LTP test failed, cannot reproduce locally and clearly unrelated)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/769)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/769)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please (some jobs will most probably fail, because the Gramine web site certificate expired; but let's check this)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/769)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (cert issue should be resolved)

**Pull request merged**
