### PR TITLE
[Pal/Linux-SGX] `enclave_entry.S`: Capitalize regs' names in comments

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

@mkow asked for this in his belated review of #291.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/305)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/305)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/305)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 404 at r1](https://reviewable.io/reviews/gramineproject/gramine/305#-MsXlRo48hrPUWu2PHGj:-MsXlRo48hrPUWu2PHGk:be27cme) ([raw file](https://github.com/gramineproject/gramine/blob/2f74cb1fc64fa393aa866073c1168a99a4be226a/Pal/src/host/Linux-SGX/enclave_entry.S#L404)):*
> ```
> 
> .Lcssa1_exception_emulate_restore_sgx_context_inst2:
> 	# emulate jmp *GS:SGX_TMP_RIP
> ```

In this case I would leave the old version as this is just asm snippet. Maybe just wrap it in ``` ` ``` ?
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 825 at r1](https://reviewable.io/reviews/gramineproject/gramine/305#-MsXlw9x5epKPQnM4g7f:-MsXlw9y65p48G7UJxRH:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2f74cb1fc64fa393aa866073c1168a99a4be226a/Pal/src/host/Linux-SGX/enclave_entry.S#L825)):*
> ```
> 	# (6) thread is done and returns from exception handler via _restore_sgx_context() and updates
> 	#     SGX_TMP_RIP (overwrites enclave_tls::tmp_rip). Now the thread returned in the middle of
> 	#     _restore_sgx_context() and will try to jmp *GS:SGX_TMP_RIP but this value is lost, and
> ```

ditto

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/305)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 404 at r1](https://reviewable.io/reviews/gramineproject/gramine/305#-MsXlRo48hrPUWu2PHGj:-MsZ5h7Y61wpwoCJYmH4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2f74cb1fc64fa393aa866073c1168a99a4be226a/Pal/src/host/Linux-SGX/enclave_entry.S#L404)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In this case I would leave the old version as this is just asm snippet. Maybe just wrap it in ``` ` ``` ?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 825 at r1](https://reviewable.io/reviews/gramineproject/gramine/305#-MsXlw9x5epKPQnM4g7f:-MsZ5p7lDXCMcaDt1Tnv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2f74cb1fc64fa393aa866073c1168a99a4be226a/Pal/src/host/Linux-SGX/enclave_entry.S#L825)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/305)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/305)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/305)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/305)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
