### PR TITLE
[Docs] Update to Gramine v1.0

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Seems we're there!

## How to test this PR? 

Check the new readme on GitHub rich diff + render the docs and check CONTRIBUTING.rst. The release link is not working yet, as the release doesn't exist yet.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/140)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/140)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by chiache — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/140)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[README.rst, line 66 at r1](https://reviewable.io/reviews/gramineproject/gramine/140#-MlVp4qK4PzkzFBUZiD8:-MlVp4qK4PzkzFBUZiD9:be57rg6) ([raw file](https://github.com/gramineproject/gramine/blob/2a90b861f0269ccbb59d4149223e977248d815a2/README.rst#L66)):*
> ```reStructuredText
> ensured that all risky configurations are clearly warned about to prevent
> insecure deployments. More details (including a list of all breaking changes)
> is available on the `v1.0 release page
> ```

is -> are

**Review by chiache — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/140)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/140)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-20.04 please (`sendfile09` timed out, known issue)

**Pull request merged**
