### PR TITLE
[python] Stop using deprecated cryptography.io's `backend` argument

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

As in the title.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053)

### CODE REVIEW

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2053#-OBBJ1J7ABk2lfLgjRp1:-OBBJ1J7ABk2lfLgjRp2:b-juff9q) (no related file):*
Please add version qualifiers to package depenencies:

```diff
diff --git i/debian/control w/debian/control
index 29979f7a4bdac8abbecb406f1bb007c6b018d15b..484085bf1c449641768b2b546d92c6bc1e83370c 100644
--- i/debian/control
+++ w/debian/control
@@ -40,7 +40,7 @@ Depends:
  python3,
  python3 (>= 3.10) | python3-pkg-resources,
  python3-click (>= 6.7),
- python3-cryptography,
+ python3-cryptography (>= 3.1),
  python3-jinja2,
  python3-pyelftools,
  python3-tomli (>= 1.1.0),
diff --git i/gramine.spec w/gramine.spec
index 29618a01946fdeeeaa4300f6e5831e2279ccd08e..dec68c774266ec4c082ecbe93bb3feca7e01250a 100644
--- i/gramine.spec
+++ w/gramine.spec
@@ -34,7 +34,7 @@ BuildRequires: python3-sphinx_rtd_theme
 %endif
 
 Requires: python3-click >= 6.7
-Requires: python3-cryptography
+Requires: python3-cryptography >= 3.1
 Requires: python3-jinja2
 Requires: python3-protobuf
 Requires: python3-pyelftools
diff --git i/packaging/alpine/APKBUILD w/packaging/alpine/APKBUILD
index 47353d753ee1e7b1819f4fe241510e501e0d2ffd..41ba15ecccd16ab1518db25a30e14ad11fff885e 100644
--- i/packaging/alpine/APKBUILD
+++ w/packaging/alpine/APKBUILD
@@ -37,7 +37,7 @@ makedepends="
     "
 depends="
     py3-click>=6.7
-    py3-cryptography
+    py3-cryptography>=3.1
     py3-elftools
     py3-jinja2
     py3-tomli
```

3.1 number is taken from https://cryptography.io/en/latest/faq/#what-happened-to-the-backend-argument, not tested.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053)* status: 2 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2053#-OBBJ1J7ABk2lfLgjRp1:-OBBOP0XAmDafDFpqKiS:b-896fix) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please add version qualifiers to package depenencies:

```diff
diff --git i/debian/control w/debian/control
index 29979f7a4bdac8abbecb406f1bb007c6b018d15b..484085bf1c449641768b2b546d92c6bc1e83370c 100644
--- i/debian/control
+++ w/debian/control
@@ -40,7 +40,7 @@ Depends:
  python3,
  python3 (>= 3.10) | python3-pkg-resources,
  python3-click (>= 6.7),
- python3-cryptography,
+ python3-cryptography (>= 3.1),
  python3-jinja2,
  python3-pyelftools,
  python3-tomli (>= 1.1.0),
diff --git i/gramine.spec w/gramine.spec
index 29618a01946fdeeeaa4300f6e5831e2279ccd08e..dec68c774266ec4c082ecbe93bb3feca7e01250a 100644
--- i/gramine.spec
+++ w/gramine.spec
@@ -34,7 +34,7 @@ BuildRequires: python3-sphinx_rtd_theme
 %endif
 
 Requires: python3-click >= 6.7
-Requires: python3-cryptography
+Requires: python3-cryptography >= 3.1
 Requires: python3-jinja2
 Requires: python3-protobuf
 Requires: python3-pyelftools
diff --git i/packaging/alpine/APKBUILD w/packaging/alpine/APKBUILD
index 47353d753ee1e7b1819f4fe241510e501e0d2ffd..41ba15ecccd16ab1518db25a30e14ad11fff885e 100644
--- i/packaging/alpine/APKBUILD
+++ w/packaging/alpine/APKBUILD
@@ -37,7 +37,7 @@ makedepends="
     "
 depends="
     py3-click>=6.7
-    py3-cryptography
+    py3-cryptography>=3.1
     py3-elftools
     py3-jinja2
     py3-tomli
```

3.1 number is taken from https://cryptography.io/en/latest/faq/#what-happened-to-the-backend-argument, not tested.
</blockquote></details>

Done.

**Review by woju — APPROVED** [review]
Approved pending CI.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053#-:-OBBSV63BG_OJ22quH9I:bgazfi3)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053)* status: all files reviewed, 1 unresolved discussion

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2053#-OBIZFB044SvRlORF526:-OBIZFB044SvRlORF527:b4zech1) (no related file):*
@woju: *pkg-rpm-almalinux9* pipeline failed with:
```
11:47:57  ../pal/src/host/linux-sgx/host_platform.c:10:10: fatal error: aesm.pb-c.h: No such file or directory
11:47:57     10 | #include "aesm.pb-c.h"
11:47:57        |          ^~~~~~~~~~~~~
11:47:57  compilation terminated.
```

but... it doesn't make sense? How could this PR cause it?

**Comment by woju** [comment]
Jenkins, test pkg-rpm-almalinux9 please

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2053#-OBIZFB044SvRlORF526:-OBVq4VJ8eZ14dw-m6EN:b-o2s5kt) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju: *pkg-rpm-almalinux9* pipeline failed with:
```
11:47:57  ../pal/src/host/linux-sgx/host_platform.c:10:10: fatal error: aesm.pb-c.h: No such file or directory
11:47:57     10 | #include "aesm.pb-c.h"
11:47:57        |          ^~~~~~~~~~~~~
11:47:57  compilation terminated.
```

but... it doesn't make sense? How could this PR cause it?
</blockquote></details>

IDK what was that. It seems to have been a fluke. `meson.build`s are correct.

**Review by woju — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053#-:-OBfLR-T92ubCYBPtOcV:bb6ywmx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2053)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
