### PR TITLE
[tests] Fix error message in `fcntl_lock` test

### PR DESCRIPTION
**Pull request by billionairiam**
## Description of the changes 

Fix error message in the `fcntl_lock` test

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1243)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1243)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @billionairiam)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1243#-NR2FDwb4j3wEo6V0Qgk):*
I will modify the commit title to `[tests] Fix error message in fcntl_lock test`

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1243)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @billionairiam)

___
*[`libos/test/regression/fcntl_lock.c` line 289 at r1](https://reviewable.io/reviews/gramineproject/gramine/1243#-NR2NV505ah26qMlFrcW:-NR2NV505ah26qMlFrcX:bieeu5g) ([raw file](https://github.com/gramineproject/gramine/blob/64bb69fb054962adb3ac3768881d028a8fd8f7f4/libos/test/regression/fcntl_lock.c#L289)):*
> ```C
>         read_pipe(pipes[1]);
> 
>         int fd2 = dup(g_fd);
> ```

Shouldn't we use CHECK?
```
int fd2 = CHECK(dup(g_fd));
CHECK(close(fd2));
```

As we are here we can change all the places - up to you.

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1243)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

___
*[`libos/test/regression/fcntl_lock.c` line 289 at r1](https://reviewable.io/reviews/gramineproject/gramine/1243#-NR2NV505ah26qMlFrcW:-NR2Q8cpDbrO9cXLyEfB:b-vgc2pj) ([raw file](https://github.com/gramineproject/gramine/blob/64bb69fb054962adb3ac3768881d028a8fd8f7f4/libos/test/regression/fcntl_lock.c#L289)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Shouldn't we use CHECK?
```
int fd2 = CHECK(dup(g_fd));
CHECK(close(fd2));
```

As we are here we can change all the places - up to you.
</blockquote></details>

Well, I wouldn't care much here.

Ideally we'll have one huge PR someday that makes all our tests to uniformly use `common.h` macros.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1243)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @oshogbo)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1243)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1243)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1243)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
