### PR TITLE
[tools/sgx] Free secret after its use in `secret_provision_constructor()`

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This memory leak was found by Klocwork. Note that `setenv()` makes a
copy of the secret, so the originally allocated secret must be freed.

## How to test this PR? 

CI is enough.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/854)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/854)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 390 at r1](https://reviewable.io/reviews/gramineproject/gramine/854#-NA3iO5m4oIUhyMabUsj:-NA3iO5m4oIUhyMabUsk:b-lk24ir) ([raw file](https://github.com/gramineproject/gramine/blob/7d81603c0017cf0e56d85bbec8512dc30fadc6b0/tools/sgx/ra-tls/secret_prov_attest.c#L390)):*
> ```C
>         }
> 
>         ret = secret_provision_get(ctx, &secret, &secret_size);
> ```

FYI: Here we allocated the `secret`.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 450 at r1](https://reviewable.io/reviews/gramineproject/gramine/854#-NA3iT9PCgTnjotiUqnj:-NA3iT9PCgTnjotiUqnk:bykby3t) ([raw file](https://github.com/gramineproject/gramine/blob/7d81603c0017cf0e56d85bbec8512dc30fadc6b0/tools/sgx/ra-tls/secret_prov_attest.c#L450)):*
> ```C
> 
>         /* put the secret into an environment variable */
>         setenv(SECRET_PROVISION_SECRET_STRING, (const char*)secret, /*overwrite=*/1);
> ```

FYI: Here we made a copy of `secret`, so the user will use this copy.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/854)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/854#-NA494bD-l40OCcPEO0O):*
This is a bit long (73), how about:
```[tools/sgx] Add missing secret free in `secret_provision_constructor()` ```
or even:
```[tools/sgx] Free secret in `secret_provision_constructor()` ```
as it's rather obvious we do not not add a free before use :)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/854)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/854#-NA494bD-l40OCcPEO0O):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is a bit long (73), how about:
```[tools/sgx] Add missing secret free in `secret_provision_constructor()` ```
or even:
```[tools/sgx] Free secret in `secret_provision_constructor()` ```
as it's rather obvious we do not not add a free before use :)
</blockquote></details>

Sure, will do on final rebase.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/854)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/854)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/854#-NA494bD-l40OCcPEO0O):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sure, will do on final rebase.
</blockquote></details>

Done

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/854)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/854)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
