### PR TITLE
[Docs] Always specify `--prefix` in `meson setup` commands

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

It is recommended to always specify the prefix explicitly, especially since the default prefix (`/usr/local`) doesn't work on Alpine.

See https://mesonbuild.com/Builtin-options.html for `prefix` explanation.

Also see #1427 for discussions.

## How to test this PR? 

Check the docs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1434)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1434)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZAtq_G4zqxmgzYt543:-NZAtq_G4zqxmgzYt544:b-c8k2qz) (no related file):*
What about [CONTRIBUTING.rst](https://github.com/gramineproject/gramine/blob/0665da5e373949043906355866e12cd1b60440b8/CONTRIBUTING.rst?plain=1#L197)?

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1434)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZAtq_G4zqxmgzYt543:-NZAvnj5BtA9jdfWoHm_:b-896fix) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about [CONTRIBUTING.rst](https://github.com/gramineproject/gramine/blob/0665da5e373949043906355866e12cd1b60440b8/CONTRIBUTING.rst?plain=1#L197)?
</blockquote></details>

Done.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1434)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1434)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZAth_H8Brh0J3AKff9:-NZAth_H8Brh0J3AKffA:b-d2h485) (no related file):*
@woju should review this

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZB0ito9t0dB8-5kBaX:-NZB0ito9t0dB8-5kBaY:b-w7ql4n) (no related file):*
@jinengandhi-intel: You may be interested in this change - building instructions were slightly changed here.

___
___
*[`Documentation/devel/building.rst` line 134 at r2](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZB0U9F7f-Y2dnzm7oL:-NZB0U9F7f-Y2dnzm7oM:b-uqhisa) ([raw file](https://github.com/gramineproject/gramine/blob/426804afdb2885e74acab99f7be782665e868a63/Documentation/devel/building.rst#L134)):*
> ```reStructuredText
>    Meson documentation recommends to always override the ``--prefix`` default.
>    For a system-wide installation from sources, ``/usr/local`` is typically a
>    correct value.  For some distros (e.g. Alpine), the correct value is
> ```

`a correct value` -> `the correct value`
___
*[`Documentation/devel/building.rst` line 134 at r2](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZB0ZLs1KfUDLO7ncKr:-NZB0ZLs1KfUDLO7ncKs:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/426804afdb2885e74acab99f7be782665e868a63/Documentation/devel/building.rst#L134)):*
> ```reStructuredText
>    Meson documentation recommends to always override the ``--prefix`` default.
>    For a system-wide installation from sources, ``/usr/local`` is typically a
>    correct value.  For some distros (e.g. Alpine), the correct value is
> ```





_Suggestion:_
```reStructuredText
value. For
```

**Review by jinengandhi-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1434)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZB0ito9t0dB8-5kBaX:-NZB1d6fAAht6CUSfdXi:b-82xemh) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@jinengandhi-intel: You may be interested in this change - building instructions were slightly changed here.
</blockquote></details>

Thanks Michal for the update. LGTM.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1434)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/devel/building.rst` line 134 at r2](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZB0U9F7f-Y2dnzm7oL:-NZB2KV79SPMnP4CfgM0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/426804afdb2885e74acab99f7be782665e868a63/Documentation/devel/building.rst#L134)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`a correct value` -> `the correct value`
</blockquote></details>

Done.
___
*[`Documentation/devel/building.rst` line 134 at r2](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZB0ZLs1KfUDLO7ncKr:-NZB2M856EtCSTr5QklF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/426804afdb2885e74acab99f7be782665e868a63/Documentation/devel/building.rst#L134)):*
> ```reStructuredText
>    Meson documentation recommends to always override the ``--prefix`` default.
>    For a system-wide installation from sources, ``/usr/local`` is typically a
>    correct value.  For some distros (e.g. Alpine), the correct value is
> ```

Done.

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1434)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1434)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1434#-NZAth_H8Brh0J3AKff9:-NZBTt4C-lOYUy8Gaf_B:b-anshzk) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju should review this
</blockquote></details>

I disagree with always putting `--prefix` everywhere. Overriding the default value by itself is pointless. It's not realistic that meson's default will ever change, so there's no reason to prepare for it.

Further, I disagree with Meson's docs recommendation, because there are important cases were you are not supposed to do that, one of them being packages where this is done by distro-provided defaults (like https://salsa.debian.org/debian/debhelper/-/blob/950761f439dd00ae1c6fb75c72dd589837b34c61/lib/Debian/Debhelper/Buildsystem/meson.pm#L59).

What we need is this part where we explain that on some distros you need to adjust some parts. We can make it a bigger section (not just `.. note::`) which would list all per-distro quirks that you need to take into consideration. This is the second quirk we've encountered, for third distro we've got here (Ubuntu is Debian derivative, so I count them both as one), so 67% sounds like it will be needed also in the future.

Alternatively we could put `--prefix=/usr` everywhere (without `local`), and explain that we're suggesting it because it's most likely to work *everywhere* and brace for BSD developer's wrath. But just writing `--prefix=/usr/local` is pointless: it doesn't fix alpine's problem and it doesn't fix CentOS problem. Logically it would follow that we should always put all the options, irrespective of their defaults.

___

**Comment by dimakuv** [comment]
Based on @woju's comment, it was easier to close this PR and create a new one: https://github.com/gramineproject/gramine/pull/1436

**Pull request closed without merging**
