### PR TITLE
[PAL/Linux] Log a message on `mmap()` returning `-ENOMEM`

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 

Linux can return `-ENOMEM` if a request to `mmap()` exceeds the process's maximum number of mappings. After commit c0a2765 "[LibOS,PAL/Linux-SGX] Add EDMM lazy allocation support", this can occur during the checkpoint/restore on the Linux PAL. In such case, each committed page is sent separately and Linux creates a mapping for each one, which can result in a large number of mappings.

This commit makes this failure more visible and provides a hint to the user on what can be done on the host.

Related to https://github.com/gramineproject/examples/issues/107.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2023)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2023)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2023)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`pal/src/host/linux/pal_memory.c` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_VFZ01wp4cYYc3zu:-O9F_VFZ01wp4cYYc3zv:bxn7bax) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L43)):*
> ```C
>         int ret = PTR_TO_ERR(res_addr);
>         if (ret == -ENOMEM && FIRST_TIME()) {
>             log_error("Host Linux returned -ENOMEM on mmap(); this may happen because process's "
> ```

I think that's the correct spelling, but I'm not 100% sure, the rules are a bit weird.



_Suggestion:_
```C
process'
```
___
*[`pal/src/host/linux/pal_memory.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_djQDVQ3uL9vURiY:-O9F_djQDVQ3uL9vURiZ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L44)):*
> ```C
>         if (ret == -ENOMEM && FIRST_TIME()) {
>             log_error("Host Linux returned -ENOMEM on mmap(); this may happen because process's "
>                       "maximum number of mappings is exceeded. Gramine cannot handle this case. "
> ```





_Suggestion:_
```C
would be exceeded
```
___
*[`pal/src/host/linux/pal_memory.c` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_BdHDt0ZXbJvpd5O:-O9F_BdHDt0ZXbJvpd5P:b-185uaj) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L46)):*
> ```C
>                       "maximum number of mappings is exceeded. Gramine cannot handle this case. "
>                       "You may want to increase the value in /proc/sys/vm/max_map_count.");
>         }
> ```

This should be debug-only, `ENOMEM` is pretty common in normal apps (e.g. trying to allocate a large contiguous chunk, if `ENOMEM` then retrying with 2 smaller chunks, etc.) and it also corresponds to other possible causes of failure.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2023)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`pal/src/host/linux/pal_memory.c` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_VFZ01wp4cYYc3zu:-O9Fbesr9wP_b2oFvGqo:b8l6ty6) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think that's the correct spelling, but I'm not 100% sure, the rules are a bit weird.
</blockquote></details>

I think the correct possessive form of process should be `process's`, but I'm not a native speaker so I can't say for sure. :)
___
*[`pal/src/host/linux/pal_memory.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_djQDVQ3uL9vURiY:-O9Fbv0WDweKrHLxRUHd:b-h1scnp) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L44)):*
> ```C
>         if (ret == -ENOMEM && FIRST_TIME()) {
>             log_error("Host Linux returned -ENOMEM on mmap(); this may happen because process's "
>                       "maximum number of mappings is exceeded. Gramine cannot handle this case. "
> ```

I basically mirror the logging msg for `munmap()` returning `-ENOMEM`: https://github.com/gramineproject/gramine/blob/91c90b4f0c55b599397fc8ba18c765b0bc665eca/pal/src/host/linux/pal_memory.c#L52-L54. Do we want to also update that?
___
*[`pal/src/host/linux/pal_memory.c` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_BdHDt0ZXbJvpd5O:-O9FceUr-PhhgjiqMPu7:b-ldcfz) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be debug-only, `ENOMEM` is pretty common in normal apps (e.g. trying to allocate a large contiguous chunk, if `ENOMEM` then retrying with 2 smaller chunks, etc.) and it also corresponds to other possible causes of failure.
</blockquote></details>

Agree, I'll update in the fixup (after we align on the above comments).

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2023)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`pal/src/host/linux/pal_memory.c` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_VFZ01wp4cYYc3zu:-O9HA0r55DiwmQL9w_i7:b1e1ug8) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L43)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think the correct possessive form of process should be `process's`, but I'm not a native speaker so I can't say for sure. :)
</blockquote></details>

I think the rules are not clear on this and kinda both are ok, so unblocking. But out of curiosity, maybe @donporter would have a minute to elaborate on this :)
___
*[`pal/src/host/linux/pal_memory.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_djQDVQ3uL9vURiY:-O9HAMagDq2LJ4F27HpC:blrt2pa) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L44)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I basically mirror the logging msg for `munmap()` returning `-ENOMEM`: https://github.com/gramineproject/gramine/blob/91c90b4f0c55b599397fc8ba18c765b0bc665eca/pal/src/host/linux/pal_memory.c#L52-L54. Do we want to also update that?
</blockquote></details>

Oh. Yeah, I'd update also that one.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2023)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux/pal_memory.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_djQDVQ3uL9vURiY:-O9HOPtcApn3LMb2pNXh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh. Yeah, I'd update also that one.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_memory.c` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/2023#-O9F_BdHDt0ZXbJvpd5O:-O9HOUkf0BuFgYtHOOwt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3968717c86ef69089a9c58e29bb3206f9ce180c2/pal/src/host/linux/pal_memory.c#L46)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Agree, I'll update in the fixup (after we align on the above comments).
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2023)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2023)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2023)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Direct-24.04-Sanitizers please (pipe04 from LTP timed out, we probably have to extend its timeout even more).

**Comment by mkow** [comment]
Jenkins, retest linux-sgx-vm-gcc-release please (`gramine-sgx-gen-private-key` failed with "cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([])", seems like a bug in cryptography.io?)

**Pull request merged**
