### PR TITLE
[mbedtls] Upgrade mbedTLS to version 3.5.0

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 

This commit introduces the following changes along with the upgrade of mbedTLS to version 3.5.0:
* updating the sonames of mbedTLS-produced libs;
* dropping our `enforce-aes-ni.patch` and instead adding the newly introduced `MBEDTLS_AES_USE_HARDWARE_ONLY` config option to enforce the use of AES-NI in Gramine shipped mbedTLS versions (which will otherwise crash at runtime if running on non-AES-NI platforms).

## How to test this PR? 
CI. Ideally also on a non-AES-NI platform.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1593)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1593)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

**Review by dimakuv — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1593)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by woju — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1593)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`subprojects/mbedtls-mbedtls-3.5.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1593#-Ng75nVP8nOAGOOajgO0:-NgIR0lu4E4nwR8LmbsA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b8c9d7ef9da2f8182b44da0d776102f46b5fd1bd/subprojects/mbedtls-mbedtls-3.5.0.wrap#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

@woju: Would you pls help mirror this file? Thanks!

I'll test against it afterwards.
</blockquote></details>

Done.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1593)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`subprojects/mbedtls-mbedtls-3.5.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1593#-Ng75nVP8nOAGOOajgO0:-NgIW3K90poMkviYMCFU:bbrtdam) ([raw file](https://github.com/gramineproject/gramine/blob/b8c9d7ef9da2f8182b44da0d776102f46b5fd1bd/subprojects/mbedtls-mbedtls-3.5.0.wrap#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! I tested it -- everything looks good.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1593)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1593)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1593)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1593#-NgY7Rt86FATc6dgvuGC:-NgY7Rt86FATc6dgvuGD:bktuxai) (no related file):*
FYI: I tested the rebased-and-ready-for-merge version manually by injecting `#error` directives into the software-AES code paths in mbedTLS and making sure it still compiles.

___

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1593)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1593#-NgY7Rt86FATc6dgvuGC:-NgZWf9n6IYzxVFsgh3N:b-ucfknh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I tested the rebased-and-ready-for-merge version manually by injecting `#error` directives into the software-AES code paths in mbedTLS and making sure it still compiles.
</blockquote></details>

Thanks!

___

**Pull request merged**
