### PR TITLE
Release 1.4

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

This is the release PR for 1.4. During release testing it will be rebased to newer commits from `master` and the version in the second-to-last commit will be updated to next `~rc` numbers.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7SeK7MFZhWIXWVQt):*
?



_Code quote:_
```
Gramine 1.4
```
___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7KCPBTV7R2J3zs3O):*




_Suggestion:_
```
Gramine
```
___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7WoK6SHq81PctYG-):*




_Suggestion:_
```
version to 1.4post~UNRELEASED
```
___
*[`debian/changelog` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC8GCiBB52UeGsDIZY:-NNC8GCiBB52UeGsDIZZ:by436v6) ([raw file](https://github.com/gramineproject/gramine/blob/e9850cb952af995d2c23fa2ba5a7007c30820f41/debian/changelog#L9)):*
> ```
>   * remove python3-protobuf dependency
>   * add perl dependency
>   * fix conflicting files in ratls packages
> ```

RA-TLS



_Code quote:_
```
ratls
```
___
*[`debian/changelog` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC83ci7vb4Zt1zBhcS:-NNC83ci7vb4Zt1zBhcT:b-aa1xxd) ([raw file](https://github.com/gramineproject/gramine/blob/e9850cb952af995d2c23fa2ba5a7007c30820f41/debian/changelog#L16)):*
> ```
>   * package mbedtls_gramine
> 
>  -- Wojtek Porczyk <woju@invisiblethingslab.com>  Wed, 2 Feb 2023 12:00:00 +0100
> ```

What's the point of writing the precise hour if it's fake?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7SeK7MFZhWIXWVQt):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

https://github.com/torvalds/linux/commit/830b3c68c1fb1e9176028d02ef86f3cf76aa2476
___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7KCPBTV7R2J3zs3O):*
Done.
___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7WoK6SHq81PctYG-):*
Done.
___
*[`debian/changelog` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC8GCiBB52UeGsDIZY:-NNCES6yDC-CebyPmfv5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9850cb952af995d2c23fa2ba5a7007c30820f41/debian/changelog#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

RA-TLS
</blockquote></details>

Done.
___
*[`debian/changelog` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC83ci7vb4Zt1zBhcS:-NNCETiT4wTgF9tuRVGy:b-fgs3eu) ([raw file](https://github.com/gramineproject/gramine/blob/e9850cb952af995d2c23fa2ba5a7007c30820f41/debian/changelog#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of writing the precise hour if it's fake?
</blockquote></details>

1) It's required by the format, because
2) The value is used in several places that have 1 s precision, like `SOURCE_DATE_EPOCH` environment variable.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7SeK7MFZhWIXWVQt):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

https://github.com/torvalds/linux/commit/830b3c68c1fb1e9176028d02ef86f3cf76aa2476
</blockquote></details>

?

I can also post links to random unrelated projects :) But what does it have to do with Gramine?

https://github.com/dotnet/runtime/commit/d037e070ebe5c83838443f869d5800752b0fcb13
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNCpYLO-wwEfep2w6_n):*
Please keep the proper grammatical form in one-liners.



_Code quote:_
```
Last minute fixes to documentation before 1.4
```

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7SeK7MFZhWIXWVQt):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?

I can also post links to random unrelated projects :) But what does it have to do with Gramine?

https://github.com/dotnet/runtime/commit/d037e070ebe5c83838443f869d5800752b0fcb13
</blockquote></details>

What is happening in this thread? Does @mkow want the line `Bump Gramine version to 1.4`, and @woju replied with the link that Linux kernel simply does `Linux x.y`, and @mkow replied with another random example?

Anyway, we should keep our git messages consistent, so I vote for `Bump Gramine version to 1.4`

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: 1 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7SeK7MFZhWIXWVQt):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is happening in this thread? Does @mkow want the line `Bump Gramine version to 1.4`, and @woju replied with the link that Linux kernel simply does `Linux x.y`, and @mkow replied with another random example?

Anyway, we should keep our git messages consistent, so I vote for `Bump Gramine version to 1.4`
</blockquote></details>

I've reworded to `Bump Gramine version to 1.4`, but I still think that just `Gramine x.y` is cleaner and more explicit what is being checked out (`git show`)
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNCpYLO-wwEfep2w6_n):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please keep the proper grammatical form in one-liners.
</blockquote></details>

Done

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: all files reviewed, 2 unresolved discussions (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1151#-NO4pPB43gXRGPG2fCY6:-NO4pPB43gXRGPG2fCY7:b-7tu4bv) (no related file):*
TODO: review commit split after the final rebase.

___
___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7SeK7MFZhWIXWVQt):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I've reworded to `Bump Gramine version to 1.4`, but I still think that just `Gramine x.y` is cleaner and more explicit what is being checked out (`git show`)
</blockquote></details>

I don't see how it's cleaner, looking at `Gramine x.y` commit one-liner I have no idea what this commit changes in the codebase. And it's quite often the case in other projects that such commits contain also a lot of random changes. `Bump Gramine version to 1.4` is both concise and clearly states what the commit contains.
___
*[`meson.build` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1151#-NO4qYk53uoQ3lgABf3B:-NO4qYk53uoQ3lgABf3C:b-i60p4a) ([raw file](https://github.com/gramineproject/gramine/blob/32504a91010df1bcab3b8fdf0e1fdb8160059771/meson.build#L8)):*
> ```Meson
>     'gramine',
>     'c', 'cpp',
>     version: '1.4post~UNRELEASED',
> ```

Just noticed: Previously we used a dash before "UNRELEASED", why this change? It breaks the convention we used before.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1151#-NO4pPB43gXRGPG2fCY6:-NO9HRUv0yqTRaPl1ORa:b1fus6b) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO: review commit split after the final rebase.
</blockquote></details>

No. The commits are single purpose and easy to revert if need be. There's no need to split them further.

___
___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7SeK7MFZhWIXWVQt):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't see how it's cleaner, looking at `Gramine x.y` commit one-liner I have no idea what this commit changes in the codebase. And it's quite often the case in other projects that such commits contain also a lot of random changes. `Bump Gramine version to 1.4` is both concise and clearly states what the commit contains.
</blockquote></details>

You know what's changed: the version. It's nice when you look at e.g. `git log --oneline`.
___
*[`meson.build` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1151#-NO4qYk53uoQ3lgABf3B:-NO9HgUR0x-Oj1jLc0UV:b-beh7hi) ([raw file](https://github.com/gramineproject/gramine/blob/32504a91010df1bcab3b8fdf0e1fdb8160059771/meson.build#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just noticed: Previously we used a dash before "UNRELEASED", why this change? It breaks the convention we used before.
</blockquote></details>

That was wrong, because this is true: `1.3.1post < 1.3.1post-UNRELEASED` (go check yourself: `dpkg --compare-versions 1.3.1post-UNRELEASED '>>' 1.3.1post`, `rpmdev-vercmp 1.3.1post-UNRELEASED 1.3.1post`, and versions with tilde). Which is unfortunate, because `-UNRELEASED` shouldn't be something that makes the version later. So we use tilde, which is special when sorting versions: it sorts negative, even before empty. This is also the reason why we have `~rc1`, not `-rc1`, because this is true `1.4~rc1 << 1.4 << 1.4-rc1`. I didn't fix that before, because I think it didn't bite us, but now when I touch this line, I'm taking an opportunity to make it right.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: all files reviewed, 2 unresolved discussions (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1151#-NO4pPB43gXRGPG2fCY6:-NO9Q8FT6IQ9DbOSDEaf:b-di5avt) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No. The commits are single purpose and easy to revert if need be. There's no need to split them further.
</blockquote></details>

? This is a TODO for me to not forget to check if the split makes sense.

___
___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1151#-NNC7SeK7MFZhWIXWVQt):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

You know what's changed: the version. It's nice when you look at e.g. `git log --oneline`.
</blockquote></details>

That's often not the case in random open source projects. I don't see any advantage of this convention when you can just say directly what you changed in a commit.
___
*[`meson.build` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1151#-NO4qYk53uoQ3lgABf3B:-NO9QfJp6WbmicY5nsXe:b-ydern6) ([raw file](https://github.com/gramineproject/gramine/blob/32504a91010df1bcab3b8fdf0e1fdb8160059771/meson.build#L8)):*
> That was wrong, because this is true: `1.3.1post` < `1.3.1post-UNRELEASED`
> because `-UNRELEASED` shouldn't be something that makes the version later

But this is indeed a later version of the codebase, not an earlier?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1151)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

___
*[`meson.build` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1151#-NO4qYk53uoQ3lgABf3B:-NO9ddYSB0wQQIzwevie:b-5qa99j) ([raw file](https://github.com/gramineproject/gramine/blob/32504a91010df1bcab3b8fdf0e1fdb8160059771/meson.build#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> That was wrong, because this is true: `1.3.1post` < `1.3.1post-UNRELEASED`
> because `-UNRELEASED` shouldn't be something that makes the version later

But this is indeed a later version of the codebase, not an earlier?
</blockquote></details>

`1.3.1post-UNRELEASED` is later than `1.3.1`, but should be earlier than `1.3.1post` (which it wasn't). Not that we'd release such a version, but there are projects that have `X.Ypost1` versions (instead of second `.`), so this should be explicit. Moreover, there's slight incompatibility between rpm and deb world, where `1.3.1post-UNRELEASED << 1.3.1post1`, but `1.3.1post-UNRELEASED >> 1.3.1post-1`, and in rpm both `1.3.1post-UNRELEASED < 1.3.1post1` and `1.3.1post-UNRELEASED < 1.3.1post-1`. I also want to avoid `-` if possible, because it's used as separator between version and revision, though this problem is entirely possible to work around.

**Pull request merged**
