### PR TITLE
[LibOS] Introduce inodes, rewrite chroot filesystem

### PR DESCRIPTION
**Pull request by pwmarcz**
Moved over from old repo: gramineproject/graphene#2646.

## Description of the changes 

This change begins the migration to inodes: file data will be kept in a separate structure (inode) instead of dentry. In this step, inodes are still optional, and only the `chroot` filesystem is rewritten to use them.

The main use case for inodes is proper handling of `rename` and `unlink` operations. The new `chroot` filesystem should do that much better than the old one. I also added a regression test (`rename_unlink`) with that checks various cases.

Fixes gramineproject/graphene#382 (but does not fix *all* rename issues, the main filesystem code is untouched yet).

Fixes gramineproject/graphene#2104 (there should be no stale data remaining after deleting/renaming a file).

## Why?

I finally decided to do that because it turns out the `chroot` filesystem *does* contain partial support for unlinking open files (you can open a file, then `unlink` it, and it will still work). It was based on a pretty bad hack (a handle contains a copy of file metadata, along with "version" attribute), and I'm not sure if it could even handle all corner cases.

I did not want to lose that partial support, and I did not want the rewritten version to include any such hacks (I would have to also replace it in `tmpfs`, and so on). Also, since a pure "dentry-based" architecture starts to really show its limitations, I don't want to base more changes on it.

I removed the experimental file position sync; I want to finish this refactoring before returning to work on sync engine.

Note that this also removes some uses of legacy structures (`atomic_int`, `shim_qstr`), though not all of them.

## Next steps

First, I plan to gradually rewrite other filesystems (starting with `tmpfs`) to use inodes. Then, I can remove the redundant fields from dentry, switching to inode completely.

I expect that the end result will make both objects (dentry and inode) much simpler than the existing dentry. The dentry will not contain any "custom" data (and probably can have much simpler locking rules), while the inode will not contain any links to children and parents.

## How to test this PR? 

This is about the `chroot` filesystem, so I expect it to be reasonably covered by existing tests (regression and LTP). I also added the `rename_unlink` regression test.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)

### CODE REVIEW

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: 0 of 20 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/chroot/fs.c, line 758 at r1](https://reviewable.io/reviews/gramineproject/gramine/5#-Mj95OR40VDG098P2Sr0:-Mj95OR40VDG098P2Sr1:b-7gqb0i) ([raw file](https://github.com/gramineproject/gramine/blob/cdda4c351f487db906d2ee5ab20070958bd5f9ef/LibOS/shim/src/fs/chroot/fs.c#L758)):*
> ```C
> 
>     if (!hdl->pal_handle) {
>         PAL_HANDLE palhdl = NULL;
> ```

GCC complains with `-Wmaybe-uninitialized` without that... am I not seeing something, or is that warning a little too paranoid?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: 0 of 20 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/chroot/fs.c, line 758 at r1](https://reviewable.io/reviews/gramineproject/gramine/5#-Mj95OR40VDG098P2Sr0:-Mj97i5W0hhFaJJUCtsd:b-dwmb33) ([raw file](https://github.com/gramineproject/gramine/blob/cdda4c351f487db906d2ee5ab20070958bd5f9ef/LibOS/shim/src/fs/chroot/fs.c#L758)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

GCC complains with `-Wmaybe-uninitialized` without that... am I not seeing something, or is that warning a little too paranoid?
</blockquote></details>

Ah, okay, GCC didn't infer that `pal_to_unix_errno()` won't return 0. If I just put `return ret` in `chroot_reopen`, the warning's gone.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: 0 of 20 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/test/regression/test_libos.py, line 533 at r1](https://reviewable.io/reviews/gramineproject/gramine/5#-Mj99KRB98glxMKC0hV4:-Mj99KRB98glxMKC0hV5:bi4rrrc) ([raw file](https://github.com/gramineproject/gramine/blob/cdda4c351f487db906d2ee5ab20070958bd5f9ef/LibOS/shim/test/regression/test_libos.py#L533)):*
> ```Python
>         self.assertIn('TEST OK', stdout)
> 
>     def test_033_rename_unlink_chroot(self):
> ```

One more thing: let me add this test for PF as well (probably needs to be skipped before https://github.com/oscarlab/graphene/pull/2521)...

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: 0 of 20 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/test/regression/test_libos.py, line 533 at r1](https://reviewable.io/reviews/gramineproject/gramine/5#-Mj99KRB98glxMKC0hV4:-Mj9L2jr4ZsV1qiwC4aY:b-3ljfmm) ([raw file](https://github.com/gramineproject/gramine/blob/cdda4c351f487db906d2ee5ab20070958bd5f9ef/LibOS/shim/test/regression/test_libos.py#L533)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

One more thing: let me add this test for PF as well (probably needs to be skipped before https://github.com/oscarlab/graphene/pull/2521)...
</blockquote></details>

Done. I added a test but I'm keeping it skipped for now.

**Review by pwmarcz — COMMENTED** [review]
>Moved over from old repo: gramineproject/graphene#2646.

Looks like Reviewable did not trigger immediately (because I copied over the old Reviewable link to PR description). This is the diff from the latest version of old PR to `r1` in this one:

```diff
diff --git a/LibOS/shim/src/fs/chroot/fs.c b/LibOS/shim/src/fs/chroot/fs.c
index 2b6f10b0..047c4cbf 100644
--- a/LibOS/shim/src/fs/chroot/fs.c
+++ b/LibOS/shim/src/fs/chroot/fs.c
@@ -755,12 +755,13 @@ static int chroot_checkin(struct shim_handle* hdl) {
      * restore). */
 
     if (!hdl->pal_handle) {
-        PAL_HANDLE palhdl;
+        PAL_HANDLE palhdl = NULL;
         int ret = chroot_reopen(hdl, &palhdl);
         if (ret < 0) {
             log_warning("%s: failed to open %s: %d", __func__, qstrgetstr(&hdl->uri), ret);
             return ret;
         }
+        assert(palhdl);
         hdl->pal_handle = palhdl;
     }
     return 0;
```

It's a fix for `-Wmaybe-uninitialized`, as mentioned in the Reviewable comment inline.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5#-:-Mj9k9F9EnFBtGMBPG9r:b8cbap)* status: 0 of 20 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: 19 of 20 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/manifest.template, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/5#-Mj9qtC-EnIkuUmmvLkQ:-Mj9reAkCu87c21wrEah:b5rhto2) ([raw file](https://github.com/gramineproject/gramine/blob/17e978194c98d5da9c11eec530e64f5ac0695122/LibOS/shim/test/regression/manifest.template#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

This is for the `rename_unlink` test (which we run with tmpfs).

Previously (in `r1`), it was part of a special manifest. However, I realized this is a similar case to protected files (in fact, the `rename_unlink` test now has three cases: tmpfs, chroot, and chroot+PF), so since we keep `sgx.protected_files` in the common manifest, we should keep the tmpfs mount there as well.

(And as I keep improving/rewriting our filesystem tests, other tests probably will also need to use tmpfs).
___
*[LibOS/shim/test/regression/test_libos.py, line 553 at r2](https://reviewable.io/reviews/gramineproject/gramine/5#-Mj9qnrX8OgRxDq0G2tE:-Mj9syrh-e4cVWcXReVB:b-c0lwbw) ([raw file](https://github.com/gramineproject/gramine/blob/17e978194c98d5da9c11eec530e64f5ac0695122/LibOS/shim/test/regression/test_libos.py#L553)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Since you've introduced a helper function, please use it here as well.
</blockquote></details>

That helper function cleans up the files on host, which we don't here because it's tmpfs.

But yeah, it's confusing to have an abstraction that covers 2 cases out of 3. I rewrote it without a helper function.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/test/regression/manifest.template, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/5#-Mj9qtC-EnIkuUmmvLkQ:-Mj9wkMHDymsZzaZcVzA:bchvl4t) ([raw file](https://github.com/gramineproject/gramine/blob/17e978194c98d5da9c11eec530e64f5ac0695122/LibOS/shim/test/regression/manifest.template#L25)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is for the `rename_unlink` test (which we run with tmpfs).

Previously (in `r1`), it was part of a special manifest. However, I realized this is a similar case to protected files (in fact, the `rename_unlink` test now has three cases: tmpfs, chroot, and chroot+PF), so since we keep `sgx.protected_files` in the common manifest, we should keep the tmpfs mount there as well.

(And as I keep improving/rewriting our filesystem tests, other tests probably will also need to use tmpfs).
</blockquote></details>

But `rename_unlink` still has its own manifest, doesn't it?
Update: reviewable is weird and shows that file was renamed and below that "File not in pull request at selected revision.". So the current state is that there is no such file. Resolving.

**Review by mkow — COMMENTED** [review]
> Reviewed 17 of 20 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBN3z-E7UCx7_0IiX_:-MjBN3z-E7UCx7_0IiXa:buewmwq) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/include/shim_fs.h#L152)):*
> ```
> Inode
> ```

I think original "inodes" from Linux are written lowercase ;) See https://man7.org/linux/man-pages/man7/inode.7.html.
___
*[LibOS/shim/include/shim_handle.h, line 204 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBViUQ-RwnO7KiqdVb:-MjBViUQ-RwnO7KiqdVc:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/include/shim_handle.h#L204)):*
> ```objc
> 
>     /*
>      * Inode associated with this handle. Currently optional, and only for the use of underlying
> ```

ditto
___
*[LibOS/shim/src/fs/chroot/fs.c, line 398 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBZ0Tb21dmsuCAQqK0:-MjBZ0Tb21dmsuCAQqK1:b-8h7ats) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/src/fs/chroot/fs.c#L398)):*
> ```C
>     file_off_t pos = hdl->info.chroot.pos;
> 
>     /* Make sure won't overflow `pos` */
> ```

broken English, should be either "it won't overflow" or "to not overflow"
___
*[LibOS/shim/src/fs/chroot/fs.c, line 435 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBZA-JC0TsdZD81rYE:-MjBZA-JC0TsdZD81rYF:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/src/fs/chroot/fs.c#L435)):*
> ```C
>     file_off_t pos = hdl->info.chroot.pos;
> 
>     /* Make sure won't overflow `pos` */
> ```

ditto
___
*[LibOS/shim/test/regression/rename_unlink.c, line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBfwux1f5lqhlW0Kj4:-MjBfwux1f5lqhlW0Kj5:b-cyrwov) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/rename_unlink.c#L32)):*
> ```C
>     while (size > 0) {
>         ssize_t n = write(fd, str, size);
>         if (n == -1) {
> ```

Could you add a comment here saying why we treat EINTR as error here? Someone can copy this code out of the test and miss this quirk.
___
*[LibOS/shim/test/regression/rename_unlink.c, line 46 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBg70u6pMUUBQSn7HQ:-MjBg70u6pMUUBQSn7HR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/rename_unlink.c#L46)):*
> ```C
>     while (size > 0) {
>         ssize_t n = read(fd, str, size);
>         if (n == -1) {
> ```

ditto
___
*[LibOS/shim/test/regression/rename_unlink.c, line 226 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBiYYx2v_4YC59GOug:-MjBiYYx2v_4YC59GOuh:beawsvn) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/rename_unlink.c#L226)):*
> ```C
>         err(1, "unlink %s", path);
> }
> ```

Could we also have a test which writes to an unlinked fd and then checks if the write didn't end up appearing on the accessible-by-path FS? I.e. something like: `fd=create(path); unlink(fd); write(fd, "asdf"); seek_and_check_if_fd_has("asdf") && check_if_not_exist(path)`.
Or maybe it doesn't seem useful to test this?
___
*[LibOS/shim/test/regression/send_handle.manifest.template, line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBkZCI0PEhWvahBbMN:-MjBkZCI0PEhWvahBbMO:b-1m9ux7) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/send_handle.manifest.template#L25)):*
> ```
> sgx.protected_files = [
>   "file:tmp/pf/",
> ]
> ```

missing newline

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/test/regression/rename_unlink.c, line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBfwux1f5lqhlW0Kj4:-MjBncYB9MmjKZRgcMmN:bzcblew) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/rename_unlink.c#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a comment here saying why we treat EINTR as error here? Someone can copy this code out of the test and miss this quirk.
</blockquote></details>

Then also add than we treat EAGAIN as error (blocking fd). And EFAULT (str is assumed to be vaild). And EBADF (fd is assumed to be valid). I won't list all here here. So why would we list them in a comment?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/test/regression/rename_unlink.c, line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBfwux1f5lqhlW0Kj4:-MjC25X66VqpD_gXjf8N:bxqxgqz) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/rename_unlink.c#L32)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then also add than we treat EAGAIN as error (blocking fd). And EFAULT (str is assumed to be vaild). And EBADF (fd is assumed to be valid). I won't list all here here. So why would we list them in a comment?
</blockquote></details>

Because in typical "write/read all" functions you have special handling only for EINTR and return other errors to the caller. And here this handling is missing.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 17 of 20 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, 8 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: 17 of 20 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBN3z-E7UCx7_0IiX_:-MjDwPbPEk3k62GAvnBQ:b-qipspi) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/include/shim_fs.h#L152)):*
Yes, in that it's "an inode", not "an Inode". But the linked man page also capitalizes it at the beginning of the sentence/heading:

>Inode number

>Inode numbers are guaranteed to be unique only within a filesystem

`git grep Inode` in Linux repo also shows usages like that.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 398 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBZ0Tb21dmsuCAQqK0:-MjDx1ro1-_GbiA-seoh:bpztw2) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/src/fs/chroot/fs.c#L398)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

broken English, should be either "it won't overflow" or "to not overflow"
</blockquote></details>

I meant "we won't overflow". Fixed.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 435 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBZA-JC0TsdZD81rYE:-MjDx44MEz7HxZ_lur9S:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/src/fs/chroot/fs.c#L435)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/rename_unlink.c, line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBfwux1f5lqhlW0Kj4:-MjDxOLu9jiMgb_7JX2Z:bh0ly3w) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/rename_unlink.c#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because in typical "write/read all" functions you have special handling only for EINTR and return other errors to the caller. And here this handling is missing.
</blockquote></details>

Yeah, I'm not super happy with omitting EINTR handling in this test only (most of other tests do not install signal handlers either), but I don't care about it too much. I added a comment.
___
*[LibOS/shim/test/regression/rename_unlink.c, line 226 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBiYYx2v_4YC59GOug:-MjDzyc_A9agbeb7oejP:b2az2fr) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/rename_unlink.c#L226)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we also have a test which writes to an unlinked fd and then checks if the write didn't end up appearing on the accessible-by-path FS? I.e. something like: `fd=create(path); unlink(fd); write(fd, "asdf"); seek_and_check_if_fd_has("asdf") && check_if_not_exist(path)`.
Or maybe it doesn't seem useful to test this?
</blockquote></details>

Sounds good, and adding another function here is cheap. Done.

(This doesn't need inodes, btw: it already passes on tmpfs).
___
*[LibOS/shim/test/regression/send_handle.manifest.template, line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBkZCI0PEhWvahBbMN:-MjE0CYHDVmCfmmZBces:b-5rkeg9) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/send_handle.manifest.template#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing newline
</blockquote></details>

Oops, I thought I deleted this file (we rely on the global `manifest.template`). Fixed.

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_fs.h, line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBN3z-E7UCx7_0IiX_:-MjEMMITBTJixHCQok-3:bxmyv1q) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/include/shim_fs.h#L152)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, in that it's "an inode", not "an Inode". But the linked man page also capitalizes it at the beginning of the sentence/heading:

>Inode number

>Inode numbers are guaranteed to be unique only within a filesystem

`git grep Inode` in Linux repo also shows usages like that.
</blockquote></details>

Huh, they seem to indeed write it this way. Weird, but I'm resolving then.
___
*[LibOS/shim/test/regression/send_handle.manifest.template, line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine/5#-MjBkZCI0PEhWvahBbMN:-MjEMxy13EjRAKtsJo6L:b-3lox29) ([raw file](https://github.com/gramineproject/gramine/blob/bec771f6dfb385ba7a379b40388775c540bb4616/LibOS/shim/test/regression/send_handle.manifest.template#L25)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oops, I thought I deleted this file (we rely on the global `manifest.template`). Fixed.
</blockquote></details>

Heh, and I dind't notice that it's unused :)

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
