### PR TITLE
[tools/sgx] Detect EDECCSSA and AEX-Notify in `is-sgx-available`

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

As in the title.

## How to test this PR? 

Run the tool on a server with these feature and without.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1890)

### CODE REVIEW

**Review by mwkmwkmwk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1890#-:-NyQmmaf3Zys7ykh6BsB:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1890)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1890)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mwkmwkmwk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1890)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1890)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
