### PR TITLE
[LibOS] Use the syscall interface for custom calls

### LINKED ISSUE #25: Rename external APIs
(As discussed in gramineproject/graphene#2662)

Graphene's patched code currently uses an API that contains some internal names ("shim_*", "syscalldb"). I propose the following changes:

* `SYSCALLDB` macro -> `GRAPHENE_SYSCALL`
* `shim_register_library` and possibly other functions -> `graphene_register_library`
* `SHIM_*_OFFSET` -> `GRAPHENE_*_OFFSET`
* `shim_entry_api.h` -> `graphene_entry_api.h`
  *  Other `shim_*.h` files are internal, but this one is a public header file included in patched code

etc.

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

This change modifies Gramine's custom calls (`register_library`, `run_test`) to use the same interface as system calls (with a dummy syscall number). This is so that these calls are executed on LibOS's stack, not the user application stack, which will make it possible to implement ASan stack sanitization.

At the same time, names in the syscall interface are updated (`gramine_entry_api.h`, `GRAMINE_SYSCALL` etc.).

This change requires rebuilding the patched Glibc. Unfortunately, this currently does not happen automatically. You can trigger the rebuild by removing the `subprojects/glibc-2.34` directory.

Fixes #25.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)

### CODE REVIEW

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: 0 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
This is because we abuse Meson for patching Glibc :(

If we really want to, I can think of a way to force rebuild: rename our files and directories to `glibc-2.34-1`.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/221#-MoY5WWiCo4fP4t8eADp:-MoY5WWiCo4fP4t8eADq:b-c19x1e) (no related file):*
Hurray! We have reasonable names in the external interface with patched libraries!

---
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is because we abuse Meson for patching Glibc :(

If we really want to, I can think of a way to force rebuild: rename our files and directories to `glibc-2.34-1`.
</blockquote></details>

I don't think we should bother.
___
*[LibOS/shim/include/arch/x86_64/gramine_entry_api.h, line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoY3noc6n_gu1PF8Ubs:-MoY3noc6n_gu1PF8Ubt:b4o8z1r) ([raw file](https://github.com/gramineproject/gramine/blob/e704db2b4127202198266344b06da40d153b8c75/LibOS/shim/include/arch/x86_64/gramine_entry_api.h#L51)):*
> ```objc
> 
> /* Magic syscall number for Gramine custom calls */
> #define GRAMINE_CUSTOM_SYSCALL_NR ((unsigned long)-1)
> ```

Hm, do we want this looks-like-errno number? This may be confusing during debug.

Maybe some other constant which would look more like "ok, definitely not a regular Linux syscall but also not some errno/corrupted value"?

Looking at this table https://chromium.googlesource.com/chromiumos/docs/+/master/constants/syscalls.md#cross_arch-numbers, maybe we could use smth like `10000` or `1000000`?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think we should bother.
</blockquote></details>

I'm still not sure, but as a counterpoint: if we don't do anything, this will be annoying not only when you pull new master, but also when working with feature branches that still have the old version.

(If you pull new master and don't rebuild Glibc, Gramine will crash; if you rebuild Glibc and run an old version, debugging will not work because of  `register_library`).
___
*[LibOS/shim/include/arch/x86_64/gramine_entry_api.h, line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoY3noc6n_gu1PF8Ubs:-MoY7EhwBZNvUF4k4ueK:b-pmod3u) ([raw file](https://github.com/gramineproject/gramine/blob/e704db2b4127202198266344b06da40d153b8c75/LibOS/shim/include/arch/x86_64/gramine_entry_api.h#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, do we want this looks-like-errno number? This may be confusing during debug.

Maybe some other constant which would look more like "ok, definitely not a regular Linux syscall but also not some errno/corrupted value"?

Looking at this table https://chromium.googlesource.com/chromiumos/docs/+/master/constants/syscalls.md#cross_arch-numbers, maybe we could use smth like `10000` or `1000000`?
</blockquote></details>

Sounds good. @boryspoplawski @mkow what do you think?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
> Gramine will crash

Yeah, true, this is bad. Well, depends on how much effort it will be to implement this, and how much of a hack it looks like.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @woju)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Gramine will crash

Yeah, true, this is bad. Well, depends on how much effort it will be to implement this, and how much of a hack it looks like.
</blockquote></details>

I don't think it's too hacky. @woju what do you think? Does renaming everything to `glibc-2.34-1` sound good?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow, @pwmarcz, and @woju)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
> This is because we abuse Meson for patching Glibc :(

What is the alternative? I'm adding musl and just followed what we have for glibc. The process was super annoying, since I had to remove the subdirectory after each change...

+1 to rename
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoYdh9S5zlFSbblDCmV):*
Do we want such comment in the commit message? (If we do the rename then probably not, but if we dont?)
___
*[LibOS/shim/include/shim_entry.h, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoYe3057g7a0p8qeUme:-MoYe3057g7a0p8qeUmf:bfvb5u6) ([raw file](https://github.com/gramineproject/gramine/blob/e704db2b4127202198266344b06da40d153b8c75/LibOS/shim/include/shim_entry.h#L9)):*
> ```objc
>  * This file describes Gramine's entrypoints from userspace (mostly from patched glibc).
>  *
>  * The userspace wrappers for these functions are defined in `gramine_entry_api.h`.
> ```

Alternative approach: `libos_entry_api.h`, so that this does not get confused with ecalls.
(Not blocking, just raising a discussion).
___
*[LibOS/shim/include/arch/x86_64/gramine_entry_api.h, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoYio5z2z4bKeHnFOXK:-MoYio5z2z4bKeHnFOXL:bxketzt) ([raw file](https://github.com/gramineproject/gramine/blob/e704db2b4127202198266344b06da40d153b8c75/LibOS/shim/include/arch/x86_64/gramine_entry_api.h#L1)):*
> ```objc
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

git and reveiwable got lost, this does not show as rename + edit, so had to diff manually and we lost history of this file.
I have no idea how to do it differently thought :(
___
*[LibOS/shim/include/arch/x86_64/gramine_entry_api.h, line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoY3noc6n_gu1PF8Ubs:-MoYhybb8v7tXZeiMyMM:b-26p1ai) ([raw file](https://github.com/gramineproject/gramine/blob/e704db2b4127202198266344b06da40d153b8c75/LibOS/shim/include/arch/x86_64/gramine_entry_api.h#L51)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sounds good. @boryspoplawski @mkow what do you think?
</blockquote></details>

This is arch specific file, so we can pick something that fits x64 only (tho I would add a small comment about it). I would go for `0x100000` - high enough and has top bits clear (so we don't accidentally hit X32 bit).

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: 11 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
> What is the alternative? I'm adding musl and just followed what we have for glibc. The process was super annoying, since I had to remove the subdirectory after each change...

The alternative is not to use Meson? Use something else for building and installing these patched projects. This would complicate the build process, but might be better for our sanity :)

I did the rename. A small hack was necessary: the directory inside tarball is `glibc-2.34`, so I'm telling Meson to unpack it to a subdirectory, i.e. `glibc-2.34-1/glibc-2.34`.
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoYdh9S5zlFSbblDCmV):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we want such comment in the commit message? (If we do the rename then probably not, but if we dont?)
</blockquote></details>

I thought it would be helpful for developers wondering why Gramine suddenly crashes.

But renaming sounds better. I'm adding a `squash!` commit with new wording.
___
*[LibOS/shim/include/shim_entry.h, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoYe3057g7a0p8qeUme:-MoYv86V0MPpnXDCpLfX:b-x3ubey) ([raw file](https://github.com/gramineproject/gramine/blob/e704db2b4127202198266344b06da40d153b8c75/LibOS/shim/include/shim_entry.h#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Alternative approach: `libos_entry_api.h`, so that this does not get confused with ecalls.
(Not blocking, just raising a discussion).
</blockquote></details>

I prefer `gramine_*` because `libos_*` is not Gramine-specific.

(I can do renames, but since it's annoying to rebuild the patches, I'll do it at the end if there's consensus).
___
*[LibOS/shim/include/arch/x86_64/gramine_entry_api.h, line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoY3noc6n_gu1PF8Ubs:-MoYwZIx0X5HxwZjgq0U:b-k1y5pj) ([raw file](https://github.com/gramineproject/gramine/blob/e704db2b4127202198266344b06da40d153b8c75/LibOS/shim/include/arch/x86_64/gramine_entry_api.h#L51)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is arch specific file, so we can pick something that fits x64 only (tho I would add a small comment about it). I would go for `0x100000` - high enough and has top bits clear (so we don't accidentally hit X32 bit).
</blockquote></details>

OK. Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: 15 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
> The alternative is not to use Meson? Use something else for building and installing these patched projects. This would complicate the build process, but might be better for our sanity :)

Time to restore our old makefiles? :)
For real now: I think a makefile just downloading, patching and building glibc would be pretty small and easy, especially if we wrote it from scratch.
___
*[subprojects/glibc-2.34-1.wrap, line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/221#-MoZ3-vy3rE5hP8Sajmx:-MoZ3-vy3rE5hP8Sajmy:b-3qxvkn) ([raw file](https://github.com/gramineproject/gramine/blob/c85428f8b832c897988071ba29d5d2550aa6b7af/subprojects/glibc-2.34-1.wrap#L14)):*
> ```
> patch_directory = glibc-2.34
> 
> # this unpacks the sources to `glibc-2.34-1/glibc-2.34`
> ```

What's the point?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: 15 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The alternative is not to use Meson? Use something else for building and installing these patched projects. This would complicate the build process, but might be better for our sanity :)

Time to restore our old makefiles? :)
For real now: I think a makefile just downloading, patching and building glibc would be pretty small and easy, especially if we wrote it from scratch.
</blockquote></details>

I guess... but we have quite a few of these projects that we download, patch and build, and they all have the same problem, it's just that some are modified less often than others. If you change the patches for `toml` and `uthash`, things will explode too. So it'd be good to have the same solution for all these projects.

But yeah, maybe that solution needs to be something different than Meson, seeing how painful it is to use...
___
*[subprojects/glibc-2.34-1.wrap, line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/221#-MoZ3-vy3rE5hP8Sajmx:-MoZ6Zt-84FZ4Usnwdv6:bryykuj) ([raw file](https://github.com/gramineproject/gramine/blob/c85428f8b832c897988071ba29d5d2550aa6b7af/subprojects/glibc-2.34-1.wrap#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point?
</blockquote></details>

We really want the directory to be `subprojects/glibc-2.34-1`, not `subprojects/glibc-2.34`. Otherwise, Meson will see the directory exists, and not rebuild anything (even though the subproject name has changed).

Unfortunately, since the the tarball contains the `glibc-2.34` directory, there's no way to directly unpack the files into `glibc-2.34-1`, i.e. renaming the top-level directory. What you can do is `lead_directory_missing`, which makes Meson create a directory and unpack the tarball *inside* it.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[subprojects/glibc-2.34-1.wrap, line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/221#-MoZ3-vy3rE5hP8Sajmx:-MoZHiNS-rnZ393QpAiW:b-i9flki) ([raw file](https://github.com/gramineproject/gramine/blob/c85428f8b832c897988071ba29d5d2550aa6b7af/subprojects/glibc-2.34-1.wrap#L14)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We really want the directory to be `subprojects/glibc-2.34-1`, not `subprojects/glibc-2.34`. Otherwise, Meson will see the directory exists, and not rebuild anything (even though the subproject name has changed).

Unfortunately, since the the tarball contains the `glibc-2.34` directory, there's no way to directly unpack the files into `glibc-2.34-1`, i.e. renaming the top-level directory. What you can do is `lead_directory_missing`, which makes Meson create a directory and unpack the tarball *inside* it.
</blockquote></details>

I thought `directory` property forces meson to unpack into such directory, but seems it just specify where to find the result of unpacking.

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I guess... but we have quite a few of these projects that we download, patch and build, and they all have the same problem, it's just that some are modified less often than others. If you change the patches for `toml` and `uthash`, things will explode too. So it'd be good to have the same solution for all these projects.

But yeah, maybe that solution needs to be something different than Meson, seeing how painful it is to use...
</blockquote></details>

I think I'm annoyed enough to work on this. But first let's hear from others @dimakuv @mkow @woju

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, all discussions resolved, "squash! " and "fixup! " found in commit messages' one-liners

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think I'm annoyed enough to work on this. But first let's hear from others @dimakuv @mkow @woju 
</blockquote></details>

I don't have a strong opinion on this. I'm not too annoyed at periodically deleting the subprojects. But I'm also not working on any such changes, so I don't need to rm them every 5 minutes :)

Anyway, why not the Meson hack with renaming from Pawel? If it works, I would prefer this hack instead of Makefiles.
___
*[LibOS/shim/include/shim_entry.h, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoYe3057g7a0p8qeUme:-MobhTW9EqbRW2MOfwBo:b-gpl7er) ([raw file](https://github.com/gramineproject/gramine/blob/e704db2b4127202198266344b06da40d153b8c75/LibOS/shim/include/shim_entry.h#L9)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I prefer `gramine_*` because `libos_*` is not Gramine-specific.

(I can do renames, but since it's annoying to rebuild the patches, I'll do it at the end if there's consensus).
</blockquote></details>

I like `gramine_entry_api.h`, as it is now. I don't think this can be confused with ECALLs -- those have `sgx_entry`, `enclave_entry` names -- very specific to SGX and ECALLs.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, all discussions resolved, "squash! " and "fixup! " found in commit messages' one-liners

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't have a strong opinion on this. I'm not too annoyed at periodically deleting the subprojects. But I'm also not working on any such changes, so I don't need to rm them every 5 minutes :)

Anyway, why not the Meson hack with renaming from Pawel? If it works, I would prefer this hack instead of Makefiles.
</blockquote></details>

I think rename is a good workaround for now, but this is getting worse with each project.

To sum up:
* No dependency tracking: Meson doesn't rebuild these subprojects if you change a patch or anything else.
* The projects are tied to a specific Meson build, so I have to rebuild glibc for each Gramine version (debug, release, sanitizers...), and rebuild it each time I recreate a build dir for some reason.
* We implement most of the functionality ourselves using a messy `compile.sh` shell script:
  * Copy the source code to another location, apply patches
  * Invoke external build system, then copy the build artifact back where Meson expects them
  * Manage build output (so that we don't output megabytes of build logs to console)
* Meson needs to know exactly what files will be produced in order to install them
  * For LTP, which installs thousands of files, I gave up and [create and then unpack a tarball instead ](https://github.com/gramineproject/gramine/pull/222)

Looking at the list above, I think that having a separate system for building all of these dependencies FAR outweighs the costs of fighting Meson.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think rename is a good workaround for now, but this is getting worse with each project.

To sum up:
* No dependency tracking: Meson doesn't rebuild these subprojects if you change a patch or anything else.
* The projects are tied to a specific Meson build, so I have to rebuild glibc for each Gramine version (debug, release, sanitizers...), and rebuild it each time I recreate a build dir for some reason.
* We implement most of the functionality ourselves using a messy `compile.sh` shell script:
  * Copy the source code to another location, apply patches
  * Invoke external build system, then copy the build artifact back where Meson expects them
  * Manage build output (so that we don't output megabytes of build logs to console)
* Meson needs to know exactly what files will be produced in order to install them
  * For LTP, which installs thousands of files, I gave up and [create and then unpack a tarball instead ](https://github.com/gramineproject/gramine/pull/222)

Looking at the list above, I think that having a separate system for building all of these dependencies FAR outweighs the costs of fighting Meson.
</blockquote></details>

Fully agreed with @pwmarcz

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, 5 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/221)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoXcnIh6S_v-OS5rRsw):*
> No dependency tracking: Meson doesn't rebuild these subprojects if you change a patch or anything else.

I'm still very negatively surprised by this... I assumed that Meson will have rough edges, as it's a relatively new buildsystem, but I assumed that a modern buildsystem wouldn't include such a broken UX/design...

> We implement most of the functionality ourselves using a messy compile.sh shell script: 

I think this part could be fixed by this PR: https://github.com/mesonbuild/meson/pull/4570, but it got stuck a few months ago.

> Looking at the list above, I think that having a separate system for building all of these dependencies FAR outweighs the costs of fighting Meson.

That unfortunately may be true.
___
*[LibOS/shim/include/arch/x86_64/gramine_entry_api.h, line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/221#-MoY3noc6n_gu1PF8Ubs:-MpcveGzBRXTyPXJzO8B:b-fnnqzt) ([raw file](https://github.com/gramineproject/gramine/blob/e704db2b4127202198266344b06da40d153b8c75/LibOS/shim/include/arch/x86_64/gramine_entry_api.h#L51)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK. Done.
</blockquote></details>

Late to the game, but +1 to the decision you've made :)

**Pull request merged**
