### PR TITLE
[tools] Split `libsgx_util.a` in IAS lib and other-utils lib

### LINKED ISSUE #1459: Gramine Build is failing with latest meson version 1.2.0
### Description of the problem

As part of Gramine Readme, any meson version above 0.56 is required to install for Gramine Build, But with latest meson version it is failing with **_"/usr/bin/ld: ias.c:(.text+0xdae): undefined reference to `curl_easy_strerror'"_**

**Gramine Readme**
sudo python3 -m pip install 'meson>=0.56'

As part of our ci dockerfile, we are restricting meson version to less than 0.57, This should also be in sync with readme and updated to meson>=0.56
```
RUN python3 -m pip install -U \
    'tomli>=1.1.0' \
    'tomli-w>=0.4.0' \
    'meson>=0.56,<0.57' \
```
https://github.com/gramineproject/gramine/blob/master/.ci/ubuntu20.04.dockerfile#L103

**Solution:**
Meson version-1.1.1 is compatible and gramine build goes through

### Steps to reproduce

meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled
ninja -C build/

### Expected results

ninja build should go through

### Actual results

```
ninja build
.....
....
[381/389] Linking target tools/sgx/ra-tls/libra_tls_verify_epid.so
FAILED: tools/sgx/ra-tls/libra_tls_verify_epid.so 
cc  -o tools/sgx/ra-tls/libra_tls_verify_epid.so tools/sgx/ra-tls/libra_tls_verify_epid.so.p/ra_tls_verify_epid.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libra_tls_verify_epid.so -Wl,--whole-archive tools/sgx/ra-tls/libra_tls_verify.a -Wl,--no-whole-archive '-Wl,-rpath,$ORIGIN/../../../subprojects/mbedtls-mbedtls-3.4.0:$ORIGIN/../../../subprojects/curl-7.84.0' -Wl,-rpath-link,/gramine/build/subprojects/mbedtls-mbedtls-3.4.0 -Wl,-rpath-link,/gramine/build/subprojects/curl-7.84.0 subprojects/mbedtls-mbedtls-3.4.0/libmbedcrypto_gramine.a subprojects/mbedtls-mbedtls-3.4.0/libmbedtls_gramine.a subprojects/mbedtls-mbedtls-3.4.0/libmbedx509_gramine.a tools/sgx/common/libsgx_util.a -Wl,--end-group -Wl,--version-script=/gramine/tools/sgx/ra-tls/ra_tls.map
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_send_request':
ias.c:(.text+0x23f): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x259): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x275): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x291): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x2a1): undefined reference to `curl_easy_perform'
/usr/bin/ld: ias.c:(.text+0x2bd): undefined reference to `curl_easy_getinfo'
/usr/bin/ld: ias.c:(.text+0x40b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x44c): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x48e): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x4a1): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x4b7): undefined reference to `curl_easy_strerror'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o):ias.c:(.text+0x51f): more undefined references to `curl_easy_strerror' follow
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_init':
ias.c:(.text+0x7cd): undefined reference to `curl_global_init'
/usr/bin/ld: ias.c:(.text+0x7f5): undefined reference to `curl_easy_init'
/usr/bin/ld: ias.c:(.text+0x885): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x8a2): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x8b7): undefined reference to `curl_slist_append'
/usr/bin/ld: ias.c:(.text+0x8cb): undefined reference to `curl_slist_append'
/usr/bin/ld: ias.c:(.text+0x8e3): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x902): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x921): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x956): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x993): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x9d3): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x9f9): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xa0b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xa23): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xa43): undefined reference to `curl_easy_strerror'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_cleanup':
ias.c:(.text+0xa6e): undefined reference to `curl_slist_free_all'
/usr/bin/ld: ias.c:(.text+0xa77): undefined reference to `curl_easy_cleanup'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_get_sigrl':
ias.c:(.text+0xb4e): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xb67): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xb81): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xb9b): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xbab): undefined reference to `curl_easy_perform'
/usr/bin/ld: ias.c:(.text+0xbc7): undefined reference to `curl_easy_getinfo'
/usr/bin/ld: ias.c:(.text+0xd23): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xd6b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xd83): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xd9b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xdae): undefined reference to `curl_easy_strerror'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o):ias.c:(.text+0xded): more undefined references to `curl_easy_strerror' follow
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_cleanup':
ias.c:(.text+0xa97): undefined reference to `curl_global_cleanup'
collect2: error: ld returned 1 exit status
[382/389] Linking target tools/sgx/ias-request/gramine-sgx-ias-request
FAILED: tools/sgx/ias-request/gramine-sgx-ias-request 
cc  -o tools/sgx/ias-request/gramine-sgx-ias-request tools/sgx/ias-request/gramine-sgx-ias-request.p/ias_request.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 '-Wl,-rpath,$ORIGIN/../../../subprojects/curl-7.84.0:$ORIGIN/../../../subprojects/mbedtls-mbedtls-3.4.0' -Wl,-rpath-link,/gramine/build/subprojects/curl-7.84.0 -Wl,-rpath-link,/gramine/build/subprojects/mbedtls-mbedtls-3.4.0 -Wl,--start-group tools/sgx/common/libsgx_util.a subprojects/mbedtls-mbedtls-3.4.0/libmbedcrypto_gramine.a subprojects/mbedtls-mbedtls-3.4.0/libmbedtls_gramine.a subprojects/mbedtls-mbedtls-3.4.0/libmbedx509_gramine.a -Wl,--end-group
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_send_request':
ias.c:(.text+0x23f): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x259): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x275): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x291): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x2a1): undefined reference to `curl_easy_perform'
/usr/bin/ld: ias.c:(.text+0x2bd): undefined reference to `curl_easy_getinfo'
/usr/bin/ld: ias.c:(.text+0x40b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x44c): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x48e): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x4a1): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x4b7): undefined reference to `curl_easy_strerror'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o):ias.c:(.text+0x51f): more undefined references to `curl_easy_strerror' follow
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_init':
ias.c:(.text+0x7cd): undefined reference to `curl_global_init'
/usr/bin/ld: ias.c:(.text+0x7f5): undefined reference to `curl_easy_init'
/usr/bin/ld: ias.c:(.text+0x885): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x8a2): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x8b7): undefined reference to `curl_slist_append'
/usr/bin/ld: ias.c:(.text+0x8cb): undefined reference to `curl_slist_append'
/usr/bin/ld: ias.c:(.text+0x8e3): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x902): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x921): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x956): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x993): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x9d3): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x9f9): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xa0b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xa23): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xa43): undefined reference to `curl_easy_strerror'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_cleanup':
ias.c:(.text+0xa6e): undefined reference to `curl_slist_free_all'
/usr/bin/ld: ias.c:(.text+0xa77): undefined reference to `curl_easy_cleanup'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_get_sigrl':
ias.c:(.text+0xb4e): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xb67): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xb81): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xb9b): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xbab): undefined reference to `curl_easy_perform'
/usr/bin/ld: ias.c:(.text+0xbc7): undefined reference to `curl_easy_getinfo'
/usr/bin/ld: ias.c:(.text+0xd23): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xd6b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xd83): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xd9b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xdae): undefined reference to `curl_easy_strerror'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o):ias.c:(.text+0xded): more undefined references to `curl_easy_strerror' follow
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_cleanup':
ias.c:(.text+0xa97): undefined reference to `curl_global_cleanup'
collect2: error: ld returned 1 exit status
[383/389] Linking target tools/sgx/ra-tls/libsecret_prov_verify_epid.so
FAILED: tools/sgx/ra-tls/libsecret_prov_verify_epid.so 
cc  -o tools/sgx/ra-tls/libsecret_prov_verify_epid.so tools/sgx/ra-tls/libsecret_prov_verify_epid.so.p/ra_tls_verify_epid.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libsecret_prov_verify_epid.so -Wl,--whole-archive tools/sgx/ra-tls/libsecret_prov_verify.a -Wl,--no-whole-archive '-Wl,-rpath,$ORIGIN/../../../subprojects/mbedtls-mbedtls-3.4.0:$ORIGIN/../../../subprojects/curl-7.84.0' -Wl,-rpath-link,/gramine/build/subprojects/mbedtls-mbedtls-3.4.0 -Wl,-rpath-link,/gramine/build/subprojects/curl-7.84.0 subprojects/mbedtls-mbedtls-3.4.0/libmbedcrypto_gramine.a subprojects/mbedtls-mbedtls-3.4.0/libmbedtls_gramine.a subprojects/mbedtls-mbedtls-3.4.0/libmbedx509_gramine.a tools/sgx/common/libsgx_util.a tools/sgx/ra-tls/libra_tls_verify.a -Wl,--end-group -Wl,--version-script=/gramine/tools/sgx/ra-tls/secret_prov.map -pthread
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_send_request':
ias.c:(.text+0x23f): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x259): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x275): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x291): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x2a1): undefined reference to `curl_easy_perform'
/usr/bin/ld: ias.c:(.text+0x2bd): undefined reference to `curl_easy_getinfo'
/usr/bin/ld: ias.c:(.text+0x40b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x44c): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x48e): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x4a1): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x4b7): undefined reference to `curl_easy_strerror'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o):ias.c:(.text+0x51f): more undefined references to `curl_easy_strerror' follow
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_init':
ias.c:(.text+0x7cd): undefined reference to `curl_global_init'
/usr/bin/ld: ias.c:(.text+0x7f5): undefined reference to `curl_easy_init'
/usr/bin/ld: ias.c:(.text+0x885): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x8a2): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x8b7): undefined reference to `curl_slist_append'
/usr/bin/ld: ias.c:(.text+0x8cb): undefined reference to `curl_slist_append'
/usr/bin/ld: ias.c:(.text+0x8e3): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x902): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x921): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0x956): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x993): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x9d3): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0x9f9): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xa0b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xa23): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xa43): undefined reference to `curl_easy_strerror'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_cleanup':
ias.c:(.text+0xa6e): undefined reference to `curl_slist_free_all'
/usr/bin/ld: ias.c:(.text+0xa77): undefined reference to `curl_easy_cleanup'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_get_sigrl':
ias.c:(.text+0xb4e): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xb67): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xb81): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xb9b): undefined reference to `curl_easy_setopt'
/usr/bin/ld: ias.c:(.text+0xbab): undefined reference to `curl_easy_perform'
/usr/bin/ld: ias.c:(.text+0xbc7): undefined reference to `curl_easy_getinfo'
/usr/bin/ld: ias.c:(.text+0xd23): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xd6b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xd83): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xd9b): undefined reference to `curl_easy_strerror'
/usr/bin/ld: ias.c:(.text+0xdae): undefined reference to `curl_easy_strerror'
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o):ias.c:(.text+0xded): more undefined references to `curl_easy_strerror' follow
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_cleanup':
ias.c:(.text+0xa97): undefined reference to `curl_global_cleanup'
collect2: error: ld returned 1 exit status
```

### Gramine commit hash

39fe991e4dee70003ac0f76db020038bce5f980e

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, Gramine's `libsgx_util.a` contained both the IAS (Intel Attestation Service, used for EPID SGX remote attestation) functionality and the other functionality (protected files, string/debug utilities, SGX quote utilities). This mix was wrong because this static lib is installed together with Gramine, but IAS part is not stand-alone -- it depends on `libcurl.a`, which is not installed together with Gramine.

Meson v1.2.0 began to fail on this "installed static lib that links against a not-installed static lib" scenario (previously Meson only printed a warning which we overlooked). This PR splits the functionality of `libsgx_util.a` into two parts: one Gramine-internal lib `libsgx_ias_util.a` used only for IAS binaries, and the other `libsgx_util.a` used for everything else (including used by external users).

This PR doesn't introduce any regression, since external users were never supposed to use IAS-specific APIs.

Fixes #1459.

See #1459 for the context and explanations.

## How to test this PR? 

CI tests that the new split doesn't break our existing tools.

I also manually verified tools like `gramine-sgx-ias-verify-report`.

Finally, one can verify with GSC that doesn't have the `!=1.2.*` trick and uses this branch.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1472)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1472)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1472#-NaBMvow8qbOBgw5W-m4:-NaBMvox0nMQLSRy6D97:bc0bn8t) (no related file):*
For reviewers, here's how I tested this PR with GSC.

Use the latest GSC master. For me it was https://github.com/gramineproject/gsc/commit/c2990e0c2bb3d5c5eaec664c7c8a6fb6d3c81e2e. And remove our workaround of *not* using Meson v1.2.0:
```diff
diff --git a/templates/debian/Dockerfile.compile.template b/templates/debian/Dockerfile.compile.template
@@ -23,7 +23,7 @@ RUN env DEBIAN_FRONTEND=noninteractive apt-get update \
-    && /usr/bin/python3 -B -m pip install 'tomli>=1.1.0' 'tomli-w>=0.4.0' 'meson>=0.56,!=1.2.*'
+    && /usr/bin/python3 -B -m pip install 'tomli>=1.1.0' 'tomli-w>=0.4.0' 'meson>=0.56'
```

### Without this PR (`master` branch of Gramine)

```yaml
$ cat config.yaml

Distro: "ubuntu:20.04"
Registry: ""
Gramine:
    Repository: "https://github.com/gramineproject/gramine.git"
    Branch:     "master"
SGXDriver:
    Repository: ""
    Branch:     ""
```

```bash
$ docker build --tag ubuntu20.04-bash --file test/ubuntu20.04-bash.dockerfile .
... success ...

$ ./gsc build --insecure-args ubuntu20.04-bash test/ubuntu20.04-bash.manifest
...
[392/396] Linking target tools/sgx/verify-ias-report/gramine-sgx-ias-verify-report
FAILED: tools/sgx/verify-ias-report/gramine-sgx-ias-verify-report
cc  -o tools/sgx/verify-ias-report/gramine-sgx-ias-verify-report ...
/usr/bin/ld: tools/sgx/common/libsgx_util.a(ias.c.o): in function `ias_send_request.isra.0':
ias.c:(.text+0x4f7): undefined reference to `curl_easy_setopt'
...
ninja: build stopped: subcommand failed.
Failed to build unsigned graminized Docker image `gsc-ubuntu20.04-bash-unsigned`.
```

### With this PR

```yaml
$ cat config.yaml

Distro: "ubuntu:20.04"
Registry: ""
Gramine:
    Repository: "https://github.com/gramineproject/gramine.git"
    Branch:     "dimakuv/split-libsgx-util"
SGXDriver:
    Repository: ""
    Branch:     ""
```

```bash
$ docker build --tag ubuntu20.04-bash --file test/ubuntu20.04-bash.dockerfile .
... success ...

$ ./gsc build --insecure-args ubuntu20.04-bash test/ubuntu20.04-bash.manifest
... success ...

$ ./gsc sign-image ubuntu20.04-bash enclave-key.pem
... success ...

$ docker run --device=/dev/sgx_enclave       -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket       gsc-ubuntu20.04-bash -c ls
... successful ls output ...

```

___

**Review by woju — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1472)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @woju)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/1472#-NaBSj1lBPeoUEm4noy7):*
> [...] This commit doesn't introduce any regression, since external
> users were never supposed to use IAS-specific APIs.

I wonder if this is true, we might not know what people really do. I don't think there's any way but to merge this and wait for bug report, should it arrive.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1472)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @woju)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/1472#-NaBSj1lBPeoUEm4noy7):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> [...] This commit doesn't introduce any regression, since external
> users were never supposed to use IAS-specific APIs.

I wonder if this is true, we might not know what people really do. I don't think there's any way but to merge this and wait for bug report, should it arrive.
</blockquote></details>

Will change to a milder `This commit should not introduce any regression ...` (during final rebase)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1472)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @woju)

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1472)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1472)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @woju)

**Review by dimakuv — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1472)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/1472#-NaBSj1lBPeoUEm4noy7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will change to a milder `This commit should not introduce any regression ...` (during final rebase)
</blockquote></details>

Done

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1472)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
