### PR TITLE
[common] Refactor Protected Files, part 1

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This commit refactors PF code without changing functionality (part 1 in a series of commits). In particular, this commit removes unused functions, variables, fields, typedefs and macros.

Extracted from #1841 at the request of @mkow.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1866)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1866)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1866)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1866)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1866)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
