### PR TITLE
[common] Make `DIV_ROUND_UP()` overflow-safe

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

There are no security bugs related to this right now, but looks like something which may end up used for untrusted size calculations someday.

## How to test this PR? 

https://godbolt.org/z/e96rW16G4

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/440)

### CODE REVIEW

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/440)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[common/include/api.h, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/440#-MxWn-r96OD8XSEjsoz9:-MxWn-r96OD8XSEjsozA:bxca5xj) ([raw file](https://github.com/gramineproject/gramine/blob/d5c994b6c42fdefeff60bd31f9239f269775eef7/common/include/api.h#L81)):*
> ```objc
> 
> /* Safe against overflows. May be slower than `(((n) + (d) - 1) / (d))` (which is not
>  * overflow-safe!), but hopefully the compiler will merge division and modulo into one
> ```

Seems it is actually smart enough!
See https://godbolt.org/z/ae439jhdx.



_Code quote:_
```objc
but hopefully the compiler will merge division and modulo
```

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/440)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/440)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/440)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/440)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
