### PR TITLE
[PAL/Linux-SGX] Rework SGX driver path resolving

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Continuation of https://github.com/gramineproject/gramine/pull/997, where we planned to move resolving of DCAP/upstream driver paths to the runtime, so that we can have a single build supporting both the upstreamed driver and the legacy DCAP one.

## How to test this PR? 

Same as with https://github.com/gramineproject/gramine/pull/997, please run on different drivers.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsGaBL6cr5v3eEpG9F):*
Don't we want to say that "the OOT DCAP driver and the upstream driver have the exact same userspace interface, so it is safe to unify them".
___
*[`pal/src/host/linux-sgx/generated_offsets.c` line 184 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsH9PKAy9Q23spXkAM:-NFsH9PKAy9Q23spXkAN:b-6v4rnj) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/generated_offsets.c#L184)):*
> ```C
>     DEFINE(PAL_FP_XSTATE_MAGIC2_SIZE, PAL_FP_XSTATE_MAGIC2_SIZE),
> 
>     /* driver type */
> ```

This is purely for `sgx_get_token.py`, right? Can we specify it in the comment? This is really a hack that these macros are defined in this file (with offsets...).
___
*[`pal/src/host/linux-sgx/host_framework.c` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsJYkq5Yi9M3JnUJXA:-NFsJYkr-K-fmj42ukvz:b-h9ixtc) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/host_framework.c#L16)):*
> ```C
> int open_sgx_driver(void) {
>     const char* paths_to_try[] = {
> #if defined(CONFIG_SGX_DRIVER_DEVICE)
> ```

Wait, is this correct? You will always have this macro defined, because it is always set in https://github.com/gramineproject/gramine/blob/master/meson.build#L161
___
*[`pal/src/host/linux-sgx/host_framework.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsHRSl1ltNNJ0Dyju-:-NFsHRSl1ltNNJ0Dyju0:bt6avfi) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/host_framework.c#L17)):*
> ```C
>     const char* paths_to_try[] = {
> #if defined(CONFIG_SGX_DRIVER_DEVICE)
>     /* The user explicitly specified the device path in build config. */
> ```

I wonder if anyone ever used this meson define? I was recently surprised to find that we have this option.

I don't want to remove this though, it's a nice (though not advertised) feature. Just curious if it was ever useful for anyone.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsIKR73ju9LceMe9a7:-NFsIKR73ju9LceMe9a8:bc95558) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/host_framework.c#L275)):*
> ```C
> 
> #ifdef CONFIG_SGX_DRIVER_OOT
>     /* older drivers (DCAP v1.5- and old out-of-tree) only supports adding one page at a time */
> ```

I would remove the mention of DCAP v1.5. Just
```
/* legacy out-of-tree driver only supports adding one page at a time */
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 325 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsIjoFAei6pmoHCn5C:-NFsIjoFAei6pmoHCn5D:b78q892) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/host_framework.c#L325)):*
> ```C
>     }
> 
>     /* newer DCAP driver (version 1.6+) allows adding a range of pages for performance, use it */
> ```

I would just remove this comment. Or at least say "upstream/DCAP driver ..."

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NFslqGkC67iUlT8oyGo:b3o06sk) (no related file):*
Trying this on MS Azure Ubuntu 18.04 VM, with `-Dsgx_driver=upstream` (the default), results in not being to find the SGX header:
```
$ meson setup ...
Has header "/usr/include/asm/sgx.h" : NO
Has header "/usr/src/linux-headers-5.4.0-1094-azure/arch/x86/include/uapi/asm/sgx.h" : NO

meson.build:140:12: ERROR: Problem encountered: Invalid SGX driver configuration (-Dsgx_driver and/or -Dsgx_driver_include_path); searched for "asm/sgx.h" under directories: ['/usr/include/', '/usr/src/linux-headers-5.4.0-1094-azure/arch/x86/include/uapi']
```

This is of course not a road block -- a person should just find/download the `sgx.h` file from upstream Linux, and specify the path to it in `-Dsgx_driver_include_path=<...>`.

I know we had this conversation before, but isn't it annoying to users? There is nothing bad in Ubuntu 18.04, and we should continue supporting it for a while, especially on MS Azure. And the problem for advanced users is that they know that MS Azure Ubuntu 18.04 has the `dcap1.6` OOT driver. So their first thought will be "Ok, I'll go and grab [the DCAP header file](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/DCAP_1.6/driver/linux/include/uapi/asm/sgx_oot.h)". But this is a wrong file, Gramine will refuse to even look for its name (`sgx_oot.h`), because our Meson logic hard-codes the name of the file: https://github.com/gramineproject/gramine/blob/cda5d4d1585d0f5f4c0e2fb650cf7ff9064ad1ef/meson.build#L108

So we have a surprised user who specifies a seemingly correct header file, but Gramine refuses to see it. So the user needs to somehow understand that Gramine expects **not a DCAP but an upstream** header file, and download [this one](https://elixir.bootlin.com/linux/v6.0/source/arch/x86/include/asm/sgx.h) and put it in a directory with a special format `<dirs>/asm/sgx.h`, and specify `-Dsgx_driver_include_path=<dirs>`.

This is close to insanity. Let's fix it. I propose two options:
1. Ship `sgx.h` with Gramine and specify it in `meson.build` as a fall-back option.
2. Specify the complete file path, not the include path, in `Dsgx_driver_include_path`. But here we should be backwards-compatible...

___
___
*[`pal/src/host/linux-sgx/host_framework.c` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsJYkq5Yi9M3JnUJXA:-NFsoF3w09Jh516nPW3-:bj1iudi) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/host_framework.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, is this correct? You will always have this macro defined, because it is always set in https://github.com/gramineproject/gramine/blob/master/meson.build#L161
</blockquote></details>

Yes, this is definitely incorrect, I tried it. Maybe we'll just use it like this?
```c
    const char* paths_to_try[] = {
#if defined(CONFIG_SGX_DRIVER_DEVICE)
    /* Always try to use the device path specified in build config first. */
    CONFIG_SGX_DRIVER_DEVICE,
#endif
#if defined(CONFIG_SGX_DRIVER_OOT)
    "/dev/isgx",
#elif defined(CONFIG_SGX_DRIVER_UPSTREAM)
    /* DCAP and upstreamed version used different paths in the past. */
    "/dev/sgx_enclave",
    "/dev/sgx/enclave",
#else
    #error This config should be unreachable.
#endif
    };
```

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: 3 of 5 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NFt30kkAQdV4SHefswe:b-9tzvej) (no related file):*
> There is nothing bad in Ubuntu 18.04

There's a lot of bad things in 18.04, mainly that it's super old, so people should really stop using it.

Where do people know about the manual header download from? I guess we have it somewhere in the docs? Shouldn't we just fix/update the instructions there?

___
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsGaBL6cr5v3eEpG9F):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want to say that "the OOT DCAP driver and the upstream driver have the exact same userspace interface, so it is safe to unify them".
</blockquote></details>

Will add on final rebase.
___
*[`pal/src/host/linux-sgx/generated_offsets.c` line 184 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsH9PKAy9Q23spXkAM:-NFstj0l0kUlgd7rvrYO:b-kqqdrz) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/generated_offsets.c#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is purely for `sgx_get_token.py`, right? Can we specify it in the comment? This is really a hack that these macros are defined in this file (with offsets...).
</blockquote></details>

But we use `DEFINE()` also for other stuff here, so it's not an exception just for this specific case.
Anyways, I don't like writing that the only user is `sgx_get_token.py`, it will turn incorrect after someone uses it elsewhere (and probably miss updating this comment).
___
*[`pal/src/host/linux-sgx/host_framework.c` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsJYkq5Yi9M3JnUJXA:-NFsuP6rCkeObnMba_gh:b23vp7n) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/host_framework.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this is definitely incorrect, I tried it. Maybe we'll just use it like this?
```c
    const char* paths_to_try[] = {
#if defined(CONFIG_SGX_DRIVER_DEVICE)
    /* Always try to use the device path specified in build config first. */
    CONFIG_SGX_DRIVER_DEVICE,
#endif
#if defined(CONFIG_SGX_DRIVER_OOT)
    "/dev/isgx",
#elif defined(CONFIG_SGX_DRIVER_UPSTREAM)
    /* DCAP and upstreamed version used different paths in the past. */
    "/dev/sgx_enclave",
    "/dev/sgx/enclave",
#else
    #error This config should be unreachable.
#endif
    };
```
</blockquote></details>

Ooohh, right -.- Thanks for noticing.
Fixed.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsHRSl1ltNNJ0Dyju-:-NFsupWM7jgavxG0q0SM:b7iwc77) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/host_framework.c#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I wonder if anyone ever used this meson define? I was recently surprised to find that we have this option.

I don't want to remove this though, it's a nice (though not advertised) feature. Just curious if it was ever useful for anyone.
</blockquote></details>

I used it a few times in the past, but it's rather useful for us than for the users.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsIKR73ju9LceMe9a7:-NFsv31w6kiGPjWqcGDX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/host_framework.c#L275)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove the mention of DCAP v1.5. Just
```
/* legacy out-of-tree driver only supports adding one page at a time */
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 325 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsIjoFAei6pmoHCn5C:-NFswD7D6CgHQK2IoyvR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/host_framework.c#L325)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would just remove this comment. Or at least say "upstream/DCAP driver ..."
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NFtDf99AF-fryQrT7E3:b-y7ytql) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> There is nothing bad in Ubuntu 18.04

There's a lot of bad things in 18.04, mainly that it's super old, so people should really stop using it.

Where do people know about the manual header download from? I guess we have it somewhere in the docs? Shouldn't we just fix/update the instructions there?
</blockquote></details>

I think the only place in the documentation is here: https://gramine.readthedocs.io/en/latest/devel/building.html#id2

But what do you want to explain there? That people need to download `sgx.h`, put it in a special dir `asm/sgx.h` and specify it? Well, yes, we can do it, though I find this solution not user-friendly...

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFtEks8BlxJakQzAFct:-NFtEks8BlxJakQzAFcu:bkwqzdu) (no related file):*
Looks good to me now. I will test it tomorrow on a bunch of my machines (unfortunately, no legacy driver, but a lot of different DCAP drivers :)). Blocking myself to not forget to test.

___
___
*[`pal/src/host/linux-sgx/generated_offsets.c` line 184 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsH9PKAy9Q23spXkAM:-NFtECuIECuwHkqzJM5X:blhtnaj) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/generated_offsets.c#L184)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But we use `DEFINE()` also for other stuff here, so it's not an exception just for this specific case.
Anyways, I don't like writing that the only user is `sgx_get_token.py`, it will turn incorrect after someone uses it elsewhere (and probably miss updating this comment).
</blockquote></details>

Well, my point is that this particular snippet is a hack and shouldn't be in this file... But whatever, I'm not blocking.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NFwzDwg1QtiXZzC1601:b-dkwt5z) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think the only place in the documentation is here: https://gramine.readthedocs.io/en/latest/devel/building.html#id2

But what do you want to explain there? That people need to download `sgx.h`, put it in a special dir `asm/sgx.h` and specify it? Well, yes, we can do it, though I find this solution not user-friendly...
</blockquote></details>

UPDATE: After testing (see my other comment), I'm still not happy with this approach (I'd prefer to ship the header file together with Gramine), but we can deal with it -- maybe just adding a sentence in docs.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFtEks8BlxJakQzAFct:-NFwufjL74xVsRdOp-SJ:b-ipc44o) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks good to me now. I will test it tomorrow on a bunch of my machines (unfortunately, no legacy driver, but a lot of different DCAP drivers :)). Blocking myself to not forget to test.
</blockquote></details>

Everything works, but because of the SGX header file, I had to hack around on MS Azure Ubuntu 18.04 with DCAP v1.6 driver:
- Download `https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/arch/x86/include/uapi/asm/sgx.h?h=v5.11` into `$HOME/driver/asm/`.
- Specify `-Dsgx_driver_include_path=$HOME/driver/` during `meson setup`

Not too bad but annoying.

The rest worked fine, including trying first `/dev/sgx_enclave` (non-existing on this machine) and then falling back to `/dev/sgx/enclave` (existing).

___

**Review by woju — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NFxYJLa2ZpGaESwGWWc:bfp04bv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

UPDATE: After testing (see my other comment), I'm still not happy with this approach (I'd prefer to ship the header file together with Gramine), but we can deal with it -- maybe just adding a sentence in docs.
</blockquote></details>

I don't want to carry `asm/sgx.h` header simply because we don't have to — it works in latest version of distros, only not in 18.04 which is four years old, half a year from EOL, and if people still run it, it's their problem and they need to make up for its deficiencies. I'd be happy to just `#include <asm/sgx.h>` and leave `-Dsgx_driver_include_path` for OOT, or even totally remove it and force people to do `CFLAGS=-I/opt/intel/linux-sgx-driver meson setup build/`.

Seriously, the less complexity we carry, the better for our project.

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NHRa6Ph98Cu2avesr98:b94qgju) (no related file):*
> it works in latest version of distros, only not in 18.04 which is four years old, half a year from EOL, and if people still run it, it's their problem and they need to make up for its deficiencies

+1

> Seriously, the less complexity we carry, the better for our project.

+1

@dimakuv: The point of my previous question was: even without this PR users need to read the docs and check the special setup for 18.04? Now this special setup changed, but it was never out-of-the-box on 18.04 Azure?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFtEks8BlxJakQzAFct:-NHR__-R3-2u28EQtJje:b-8tyuz6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Everything works, but because of the SGX header file, I had to hack around on MS Azure Ubuntu 18.04 with DCAP v1.6 driver:
- Download `https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/arch/x86/include/uapi/asm/sgx.h?h=v5.11` into `$HOME/driver/asm/`.
- Specify `-Dsgx_driver_include_path=$HOME/driver/` during `meson setup`

Not too bad but annoying.

The rest worked fine, including trying first `/dev/sgx_enclave` (non-existing on this machine) and then falling back to `/dev/sgx/enclave` (existing).
</blockquote></details>

Hmm, but didn't you have to do the same also before this PR? What exactly has changed in the Azure setup with this PR?

___
___
*[`pal/src/host/linux-sgx/generated_offsets.c` line 184 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsH9PKAy9Q23spXkAM:-NHR_5h57nLdi0WzjPGm:bd57wv7) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/generated_offsets.c#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, my point is that this particular snippet is a hack and shouldn't be in this file... But whatever, I'm not blocking.
</blockquote></details>

Hmm, I don't see why this would be a hack, the very purpose of this file is to forward a selected set of preprocessor directives from C to other languages we use.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NHTPeLJD9GgW1_4Chqw:brbb2yr) (no related file):*
> even without this PR users need to read the docs and check the special setup for 18.04? Now this special setup changed, but it was never out-of-the-box on 18.04 Azure?

Now there is *zero* information about DCAP driver in our docs (https://gramine.readthedocs.io/en/latest/devel/building.html#id2). Why can't we add a note that "if you have a DCAP driver installed on the system (e.g. on 18.04 Azure), then you can still use the `upstream` driver and specify the upstream header file [link to Linux header file]. This is because the DCAP and the upstream drivers are API compatible".

I mean, the special setup changed from **being described in the documentation** to **no mention in the documentation whatsoever**. I don't like this.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFtEks8BlxJakQzAFct:-NHTQV5t0z9GItLL8KNU:b-ejpkh) (no related file):*
> Hmm, but didn't you have to do the same also before this PR? What exactly has changed in the Azure setup with this PR?

Nothing with this PR, but with your previous PR (https://github.com/gramineproject/gramine/pull/997).

I should have tested and blocked on this issue (missing documentation about this DCAP driver case) on that older PR :(

___
___
*[`pal/src/host/linux-sgx/generated_offsets.c` line 184 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsH9PKAy9Q23spXkAM:-NHTR3X8DCCFSBbzKqTA:b-txepjp) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/generated_offsets.c#L184)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I don't see why this would be a hack, the very purpose of this file is to forward a selected set of preprocessor directives from C to other languages we use.
</blockquote></details>

This is a hack because the file is named `generated_offsets`. I'd be fine if it would be called `generated_macros`. Whatever, I'm not blocking.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NHW_xLO9zzSCennyZr7:b-dqdwoa) (no related file):*
// Merging both threads.

> I mean, the special setup changed from being described in the documentation to no mention in the documentation whatsoever. I don't like this.

> Nothing with this PR, but with your previous PR (#997).
> I should have tested and blocked on this issue (missing documentation about this DCAP driver case) on that older PR :(

Ah, I see. As you're the only one with Azure access right now, could you write down the exact instructions for me? (I mean, same as you wrote above, but with precise links etc., as I don't have a way to test it)

___
___
*[`pal/src/host/linux-sgx/generated_offsets.c` line 184 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsH9PKAy9Q23spXkAM:-NHW_2TOA2g2YO06Jwbs:bxbifqz) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/generated_offsets.c#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a hack because the file is named `generated_offsets`. I'd be fine if it would be called `generated_macros`. Whatever, I'm not blocking.
</blockquote></details>

Ah, that's what you mean. Yeah, I agree that the name is not valid anymore, although I don't like "macros" either, because e.g. in Python you don't have macros. Maybe `generated_constants`?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NHZkV7oCgEt16auCJOG:bce1j1n) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, here are the instructions.

First, my clean Azure CC VM 18.04 has these characteristics:
```
dimakuv@accvm:~$ uname -a
Linux accvm 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

dimakuv@accvm:~$ dmesg | grep -i sgx
[    5.677051] sgx: intel_sgx: Intel SGX DCAP Driver v1.33.2
```

In other words, we have Linux 5.4 (with no upstream SGX driver) and a specially installed out-of-tree DCAP driver v1.33.2 (which is equal to GitHub v1.6).

---

Now the instructions:
```
# get SGX upstream driver header
mkdir -p $HOME/driver/asm/
wget -O $HOME/driver/asm/sgx.h https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/arch/x86/include/uapi/asm/sgx.h?h=v5.11

# install Gramine
git clone https://github.com/gramineproject/gramine.git
cd gramine/
git checkout mkow/autofind-dcap-driver  ## FIXME: this is to test your PR!
meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled -Dsgx_driver_include_path=$HOME/driver
ninja -C build/
sudo ninja -C build/ install

# try helloworld
cd CI-Examples/helloworld/
make SGX=1
gramine-sgx helloworld  # WORKS!
```
</blockquote></details>

So, just to ensure I understand correctly: on 18.04+Azure we'll support/recommend custom builds with this special path manually specified during build, right? Instead of using a package and downloading the header to some system-global location.
Or maybe you only wrote these instructions for me to test it, and it's not what you want me to put into the docs? (ofc with the PR-specific stuff stripped)

___
___
*[`pal/src/host/linux-sgx/generated_offsets.c` line 184 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsH9PKAy9Q23spXkAM:-NHZm-aB2ZlpdZPv4OCG:brb98bh) ([raw file](https://github.com/gramineproject/gramine/blob/c26fc818d7e1cc2ea29295be36a4d09811629cae/pal/src/host/linux-sgx/generated_offsets.c#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, it's not relevant to this PR. But if you want to create another PR, then `generated_constants` sounds good to me.
</blockquote></details>

Yeah, I didn't mean to add it into this PR, was discussing in general.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NHZt3OW2rTqXR7o7b_G:b-mch365) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, just to ensure I understand correctly: on 18.04+Azure we'll support/recommend custom builds with this special path manually specified during build, right? Instead of using a package and downloading the header to some system-global location.
Or maybe you only wrote these instructions for me to test it, and it's not what you want me to put into the docs? (ofc with the PR-specific stuff stripped)
</blockquote></details>

No. We can still recommend using the package (`gramine` package starting from version v1.4), even on Ubuntu 18.04 on Azure. It will work.

I'm only talking about the Building page in documentation -- that we need to add some notes/instructions here: https://gramine.readthedocs.io/en/latest/devel/building.html#id2. Nothing else than that -- just for people who want to build Gramine themselves with an out-of-tree DCAP driver.

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NHfAxHxEQxF2FeaNKDJ:b-47yzv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No. We can still recommend using the package (`gramine` package starting from version v1.4), even on Ubuntu 18.04 on Azure. It will work.

I'm only talking about the Building page in documentation -- that we need to add some notes/instructions here: https://gramine.readthedocs.io/en/latest/devel/building.html#id2. Nothing else than that -- just for people who want to build Gramine themselves with an out-of-tree DCAP driver.
</blockquote></details>

Check now.

___

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFslqGkC67iUlT8oyGn:-NHhh9fa6ERSDF60iC9T:bs4uam1) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Check now.
</blockquote></details>

Done, looks good now. Thanks.

___

**Review by woju — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: 4 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1027#-NFsGaBL6cr5v3eEpG9F):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Will add on final rebase.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1027)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
