### PR TITLE
Build RPM packages for AlmaLinux 8 and 9 (compatible with all RHEL-like distros)

### PR DESCRIPTION
**Pull request by woju**
## How to test this PR? 

Build the packages yourself (with `mock` for example)

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1102)

### CODE REVIEW

**Comment by woju** [comment]
Jenkins, test pkg-rpm-almalinux9 please

**Comment by woju** [comment]
Jenkins, test pkg-rpm-almalinux9 please

**Comment by woju** [comment]
Jenkins, test pkg-rpm-almalinux9 please

**Comment by woju** [comment]
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NM9BHf_ArS7GHr8KURi):*
FYI the commits are split like this, because "Build packages for AlmaLinux {8,9}" can be merged *ad libitum*, depending on the discussion which distros do we support.

**Comment by woju** [comment]
Jenkins, test pkg-rpm-almalinux9 please

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1102)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEHMjUAfldRuz3WM__):*
Shouldn't we rename it to `[debian] Require ninja-build v1.8 or higher` + maybe a commit body message with a quick explanation why starting with this version?
___
*[`gramine.spec` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMELyu-ATsBQ1wysmHU:-NMELyu-ATsBQ1wysmHV:b-2fcf4t) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L9)):*
> ```Ruby
> Release: 1%{?dist}
> Group: Development Tools
> Summary: A lightweight guest OS designed to run a single application
> ```

- `A lightweight usermode guest OS...`
- `... a single Linux application`

 to be uniform with Debian/Ubuntu: https://github.com/gramineproject/gramine/blob/ff9ec79ab27fb4f95daa35656d1410c695264509/debian/control#L33
___
*[`gramine.spec` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEM_tb84Faq9PvVEnj:-NMEM_tb84Faq9PvVEnk:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L50)):*
> ```Ruby
> 
> %description
> A lightweight guest OS designed to run a single application
> ```

ditto
___
*[`gramine.spec` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEN8FW5fMlyAao1lzn:-NMEN8FW5fMlyAao1lzo:b-1hix8j) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L70)):*
> ```Ruby
> %meson_install
> 
> rm -f %{buildroot}/%{_libdir}/%{name}/direct/libpal.a
> ```

Interesting, why do we have this one... And why do you need to delete it?
___
*[`gramine.spec` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMENPRB3_C859-9OG8P:-NMENPRB3_C859-9OG8Q:bpsvq6d) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L90)):*
> ```Ruby
> ln -sf libmbedcrypto_%{name}.so.6 %{buildroot}/%{_libdir}/libmbedcrypto_%{name}.so
> ln -sf libmbedtls_%{name}.so.13 %{buildroot}/%{_libdir}/libmbedtls_%{name}.so
> ln -sf libmbedx509_%{name}.so.1 %{buildroot}/%{_libdir}/libmbedx509_%{name}.so
> ```

Where did you get these numbers from?

I see these numbers in the install dir of the latest `master` branch:
```
libmbedcrypto_gramine.so.13
libmbedtls_gramine.so.19
libmbedx509_gramine.so.4
```

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1102)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEHMjUAfldRuz3WM__):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we rename it to `[debian] Require ninja-build v1.8 or higher` + maybe a commit body message with a quick explanation why starting with this version?
</blockquote></details>

Technically there's no change in the requirements (there's transititive dependency through `meson` package against `ninja >= 1.6`, but the earliest package available is `1.8` in bionic, cf. https://tracker.debian.org/pkg/ninja-build, https://packages.ubuntu.com/search?keywords=ninja%2Dbuild&searchon=all&suite=all&section=all). However, if you look at `common/proto/meson.build`, we refrain from using 1.10-feature and this dependency just reflects that. It's generally better to have explicit version, because without those, it's harder to ask yourself a question, "can I use this feature/version?".
___
*[`gramine.spec` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMELyu-ATsBQ1wysmHU:-NMTG9-v93argGSlp05d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

- `A lightweight usermode guest OS...`
- `... a single Linux application`

 to be uniform with Debian/Ubuntu: https://github.com/gramineproject/gramine/blob/ff9ec79ab27fb4f95daa35656d1410c695264509/debian/control#L33
</blockquote></details>

Done.
___
*[`gramine.spec` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEM_tb84Faq9PvVEnj:-NMTGF7wElC0nr856dKH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`gramine.spec` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEN8FW5fMlyAao1lzn:-NMTGGjh7ctM6boVQBxH:baqvv9e) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interesting, why do we have this one... And why do you need to delete it?
</blockquote></details>

I don't remember, but I must've put it there for a reason. I wonder what'll happen without it.
___
*[`gramine.spec` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMENPRB3_C859-9OG8P:-NMTCpmD-RcpmYSbHBnN:b-dz5awv) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Where did you get these numbers from?

I see these numbers in the install dir of the latest `master` branch:
```
libmbedcrypto_gramine.so.13
libmbedtls_gramine.so.19
libmbedx509_gramine.so.4
```
</blockquote></details>

Copied from some previous attempt, possibly very old.

Also, this is not what ended up in package:
```
% rpmquery -l gramine-1.3.1post~UNRELEASED-1.el8.x86_64.rpm | fgrep libmbedcrypto
/usr/lib64/gramine/runtime/glibc/libmbedcrypto_gramine.a
/usr/lib64/gramine/runtime/glibc/libmbedcrypto_gramine.so
/usr/lib64/gramine/runtime/glibc/libmbedcrypto_gramine.so.13
/usr/lib64/libmbedcrypto_gramine.a
/usr/lib64/libmbedcrypto_gramine.so
/usr/lib64/libmbedcrypto_gramine.so.13
```
I wonder if we really need those explicit links at all.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1102)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEHMjUAfldRuz3WM__):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Technically there's no change in the requirements (there's transititive dependency through `meson` package against `ninja >= 1.6`, but the earliest package available is `1.8` in bionic, cf. https://tracker.debian.org/pkg/ninja-build, https://packages.ubuntu.com/search?keywords=ninja%2Dbuild&searchon=all&suite=all&section=all). However, if you look at `common/proto/meson.build`, we refrain from using 1.10-feature and this dependency just reflects that. It's generally better to have explicit version, because without those, it's harder to ask yourself a question, "can I use this feature/version?".
</blockquote></details>

Ok, forget about the "quick explanation" part. But do we want to change the commit title? Right now it's very vague ("we fixed something").
___
*[`gramine.spec` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEN8FW5fMlyAao1lzn:-NMTQ1y56qbwQd7cBDuy:b-3c4epe) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L70)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't remember, but I must've put it there for a reason. I wonder what'll happen without it.
</blockquote></details>

Well, Jenkins passed :)
___
*[`gramine.spec` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMENPRB3_C859-9OG8P:-NMTQAOJ-tpizYSjN4CT:b-3c4epe) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L90)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Copied from some previous attempt, possibly very old.

Also, this is not what ended up in package:
```
% rpmquery -l gramine-1.3.1post~UNRELEASED-1.el8.x86_64.rpm | fgrep libmbedcrypto
/usr/lib64/gramine/runtime/glibc/libmbedcrypto_gramine.a
/usr/lib64/gramine/runtime/glibc/libmbedcrypto_gramine.so
/usr/lib64/gramine/runtime/glibc/libmbedcrypto_gramine.so.13
/usr/lib64/libmbedcrypto_gramine.a
/usr/lib64/libmbedcrypto_gramine.so
/usr/lib64/libmbedcrypto_gramine.so.13
```
I wonder if we really need those explicit links at all.
</blockquote></details>

Well, Jenkins passed :)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1102)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEHMjUAfldRuz3WM__):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, forget about the "quick explanation" part. But do we want to change the commit title? Right now it's very vague ("we fixed something").
</blockquote></details>

What about this version? It says what is done, and why it's included in a PR called "RPM packages".
___
*[`gramine.spec` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMENPRB3_C859-9OG8P:-NMZCc4mCGZW9hu5UITD:b-cuef9l) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, Jenkins passed :)
</blockquote></details>

Unfortunately it says almost nothing. Those packages are not tested.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1102)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMEHMjUAfldRuz3WM__):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

What about this version? It says what is done, and why it's included in a PR called "RPM packages".
</blockquote></details>

Looks good, thanks
___
*[`gramine.spec` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMENPRB3_C859-9OG8P:-NMXpxHu9Oe47Q31sj2E:bkrwyoj) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L90)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Unfortunately it says almost nothing. Those packages are not tested.
</blockquote></details>

You mean not tested in our CI? Won't we test them manually before release (and right after release)?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1102)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`gramine.spec` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMENPRB3_C859-9OG8P:-NMcOtNo9N2G5-rj-leX:bftn5v5) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You mean not tested in our CI? Won't we test them manually before release (and right after release)?
</blockquote></details>

Yes, in CI they're just built and archived. Testing is done manually by Jinen's team.

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1102)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`gramine.spec` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1102#-NMENPRB3_C859-9OG8P:-NMYhjBnEk12qUEkpKO3:bkq973u) ([raw file](https://github.com/gramineproject/gramine/blob/d20d7c29982ee9ad425d3c0366d276fc731c9539/gramine.spec#L90)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, in CI they're just built and archived. Testing is done manually by Jinen's team.
</blockquote></details>

Ok, got it.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1102)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
