### PR TITLE
[Docs] Add missing packages to installation instructions

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Yes

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`Documentation/devel/building.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1022#-NFs1tTx1sBRGntNtYw4:-NFs1tTx1sBRGntNtYw5:bybg8hc) ([raw file](https://github.com/gramineproject/gramine/blob/33764b3712c301499e9e18a39af75e8a99f25d29/Documentation/devel/building.rst#L40)):*
> ```reStructuredText
>     sudo apt-get install -y build-essential \
>         autoconf bison gawk nasm ninja-build pkg-config python3 python3-click \
>         python3-jinja2 python3-pip python3-pyelftools wget
> ```

`pip` is unneccesary on two latest ubuntuLTSs (22.04 and 20.04; it's only for 18.04), so I'd prefer to have it instead `apt-get install meson python3-toml` and rewrite the next paragraph to say that on 18.04 you need to install from pip. Or just remove, we don't generally support 18.04.

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`Documentation/devel/building.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1022#-NFs1tTx1sBRGntNtYw4:-NFs5XjD3mBydeVpCeac:b26vg9b) ([raw file](https://github.com/gramineproject/gramine/blob/33764b3712c301499e9e18a39af75e8a99f25d29/Documentation/devel/building.rst#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`pip` is unneccesary on two latest ubuntuLTSs (22.04 and 20.04; it's only for 18.04), so I'd prefer to have it instead `apt-get install meson python3-toml` and rewrite the next paragraph to say that on 18.04 you need to install from pip. Or just remove, we don't generally support 18.04.
</blockquote></details>

@woju But the paragraph right-below talks about > Ubuntu 20.10, so it doesn't look like required versions of Meson and TOML are there on Ubuntu 20.04?

Also, we support Ubuntu 18.04 (with some requirements for FSGSBASE and SGX-driver enablements). So I didn't understand your last sentence.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`Documentation/devel/building.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1022#-NFs1tTx1sBRGntNtYw4:-NFsjeV77w8slhobnwZH:bksihz) ([raw file](https://github.com/gramineproject/gramine/blob/33764b3712c301499e9e18a39af75e8a99f25d29/Documentation/devel/building.rst#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju But the paragraph right-below talks about > Ubuntu 20.10, so it doesn't look like required versions of Meson and TOML are there on Ubuntu 20.04?

Also, we support Ubuntu 18.04 (with some requirements for FSGSBASE and SGX-driver enablements). So I didn't understand your last sentence.
</blockquote></details>

I don't intend to rewrite these docs, but in the current format they are wrong (2nd command **is** `pip`), which I fixed.
Yes, currently we still support 18.04.

**Review by woju — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`Documentation/devel/building.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1022#-NFs1tTx1sBRGntNtYw4:-NFxF627DxhuBlXAZuRy:bcsi7po) ([raw file](https://github.com/gramineproject/gramine/blob/33764b3712c301499e9e18a39af75e8a99f25d29/Documentation/devel/building.rst#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't intend to rewrite these docs, but in the current format they are wrong (2nd command **is** `pip`), which I fixed.
Yes, currently we still support 18.04.
</blockquote></details>

Hmm, right, 20.04 has meson 0.53, so it still applies.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1022)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
