### PR TITLE
Small CPUID refactoring

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Split out from #314. See commit messages.

## How to test this PR? 

CI, no functional changes intended.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 294 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-MsfkRMK3cPa-vTUJjPG:-MsfkRMK3cPa-vTUJjPH:bu4lr7y) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L294)):*
> ```C
>         if (subleaf == 0x0) {
>             /* EAX = 1DH, ECX = 0: special subleaf, returns EAX=max_palette, EBX=ECX=EDX=0 */
>             if (!IS_IN_RANGE_INCL(values[CPUID_WORD_EAX], 1, 16) || values[CPUID_WORD_EBX] != 0 || values[CPUID_WORD_ECX] != 0 ||
> ```

Please wrap to 100 chars
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-MsflJQHBJupApyaKvbJ:-MsflJQI2kJz4L8sr4ho:ber8xxk) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L307)):*
> ```C
>                     !IS_IN_RANGE_INCL(values[CPUID_WORD_ECX] & 0xFFFF, 1, 256) || /* max_rows */
>                     (values[CPUID_WORD_ECX] >> 16) != 0 || values[CPUID_WORD_EDX] != 0) {
>                 log_error("Unexpected values in Tile Information CPUID Leaf (subleaf=%x)", subleaf);
> ```

Could you change `%x` to `%#x`? It's unrelated, but it's a small enough that we shouldn't care.
I've grepped whole repo, this is the only place with such issue.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 315 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-MsfmKWTAtncsdQ-7TU8:-MsfmKWTAtncsdQ-7TU9:bln5w5u) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L315)):*
> ```C
>         if (!IS_IN_RANGE_INCL(values[CPUID_WORD_EBX] & 0xFF, 1, 0xFF) || /* tmul_maxk (rows or columns) */
>                 !IS_IN_RANGE_INCL((values[CPUID_WORD_EBX] >> 8) & 0xFFFF, 1, 0xFFFF) || /* tmul_maxn */
>                 (values[CPUID_WORD_EBX] >> 24) != 0 || values[CPUID_WORD_EAX] != 0 || values[CPUID_WORD_ECX] != 0 ||
> ```

ditto (wrap)

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 304 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-Msg3RtA5vIpLIFKlkuA:-Msg3RtA5vIpLIFKlkuB:b-vffdfc) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L304)):*
> ```C
>                     !IS_IN_RANGE_INCL(values[CPUID_WORD_EAX] >> 16, 1, 0xFFFF) || /* bytes_per_tile */
>                     !IS_IN_RANGE_INCL(values[CPUID_WORD_EBX] & 0xFFFF, 1, 0xFFFF) || /* bytes_per_row */
>                     !IS_IN_RANGE_INCL(values[CPUID_WORD_EBX] >> 16, 1, 256) || /* max_names (# of tile regs) */
> ```

Comments seem to exceed the 100 chars limit. Should we wrap here as well?

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 304 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-Msg3RtA5vIpLIFKlkuA:-Msg8l0k910l4hlFO48v:bpo183l) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L304)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Comments seem to exceed the 100 chars limit. Should we wrap here as well?
</blockquote></details>

Maybe move these comments to the top-level comment, smth like:
```
/*
 * EAX = 1DH, ECX > 0: subleaf for each supported palette, returns palette limits:
 *    EAX, low bits -- total_tile_bytes
 *    EAX, high bits -- bytes_per_tile
 *    ... and so on ...
 */
```
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 315 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-MsfmKWTAtncsdQ-7TU8:-Msg94kWAvynpNPiZH--:b-nfmfhe) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L315)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (wrap)
</blockquote></details>

ditto for the proposal (move to the top-level comment)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: 3 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 294 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-MsfkRMK3cPa-vTUJjPG:-MsgIO8L8zC_F1qi6zFq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L294)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please wrap to 100 chars
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 304 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-Msg3RtA5vIpLIFKlkuA:-MsgISdu-yyYU4EQ3zl_:bwj29kj) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L304)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe move these comments to the top-level comment, smth like:
```
/*
 * EAX = 1DH, ECX > 0: subleaf for each supported palette, returns palette limits:
 *    EAX, low bits -- total_tile_bytes
 *    EAX, high bits -- bytes_per_tile
 *    ... and so on ...
 */
```
</blockquote></details>

What about now?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-MsflJQHBJupApyaKvbJ:-MsgJChB30dUgnvV95V9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L307)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you change `%x` to `%#x`? It's unrelated, but it's a small enough that we shouldn't care.
I've grepped whole repo, this is the only place with such issue.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 315 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-MsfmKWTAtncsdQ-7TU8:-MsgJJPdCrNi7e9h2q5r:b-7xvu7b) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L315)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto for the proposal (move to the top-level comment)
</blockquote></details>

check now

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 304 at r1](https://reviewable.io/reviews/gramineproject/gramine/317#-Msg3RtA5vIpLIFKlkuA:-MsgPE5VBAVupxdf1Ttm:bhwlr84) ([raw file](https://github.com/gramineproject/gramine/blob/58ba6879d12f16ee02a46bc61b5d9cb9b6d1f02e/Pal/src/host/Linux-SGX/db_misc.c#L304)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about now?
</blockquote></details>

Nice, much better!
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 296 at r3](https://reviewable.io/reviews/gramineproject/gramine/317#-MsgOdwGDoqQbPY032io:-MsgOdwGDoqQbPY032ip:bfme7lw) ([raw file](https://github.com/gramineproject/gramine/blob/eac7c85ae3c1f6adbc56c4cd964dccf72d745c6e/Pal/src/host/Linux-SGX/db_misc.c#L296)):*
> ```C
>             if (!IS_IN_RANGE_INCL(values[CPUID_WORD_EAX], 1, 16) || values[CPUID_WORD_EBX] != 0
>                     || values[CPUID_WORD_ECX] != 0
>                     || values[CPUID_WORD_EDX] != 0) {
> ```

Now these two can fit in one line.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 296 at r3](https://reviewable.io/reviews/gramineproject/gramine/317#-MsgOdwGDoqQbPY032io:-MsgScHqCwNS5wV5_TXY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/eac7c85ae3c1f6adbc56c4cd964dccf72d745c6e/Pal/src/host/Linux-SGX/db_misc.c#L296)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now these two can fit in one line.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/317)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
