### PR TITLE
[Pal/Linux-SGX] Compile with Meson

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

(I'm basing this on [previous branch by @woju](https://github.com/gramineproject/graphene/compare/woju/meson-pal-sgx...woju:woju/meson-pal-sgx#diff-dbfb17c4f18d0348f7dd11e2b30dc6b18557413fe0146d0f0fed91a03df17ad2), hence the `Co-authored-by`.)

This converts *almost* all of Linux-SGX to Meson. The Makefile still generates the following:

* `gsgx.h` header (generated using a Python script)
* `aesm.pb-c.[ch]` (generated by protobuf)
* `sgx_gdb.so` (compiled by `cc`, but with almost no dependencies on rest of Gramine)

The first item looks complicated (at least the solution proposed by @woju is). The remaining two are easier, but still, I'd *really* prefer not to bundle them here. This PR already does a lot.

## How to test this PR? 

Try compiling and running it.

Apparently Meson doesn't react to changes in subprojects, so you might want to delete `subprojects/mbedtls-2.26.0` before rebuilding; it keeps using the old `meson.build` otherwise.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz and @woju)

___
*[Pal/src/host/Linux-SGX/Makefile, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvBOKbA-Wz6g3HtLHP:-MkvBOKc54AtbONtB0mP:bcsaerw) ([raw file](https://github.com/gramineproject/gramine/blob/3db673bae9e034d2dd9694ee3c066a6118c5caff/Pal/src/host/Linux-SGX/Makefile#L28)):*
> ```Makefile
> 	$(RM) -r *.o *.e *.i *.s $(host_files) $(CLEAN_FILES) *.d gdb_integration/*.d signer/*.pyc \
> 	         __pycache__ signer/__pycache__
> 	$(RM) -r protected-files/*.o protected-files/*.d
> ```

This line can be removed.
___
*[Pal/src/host/Linux-SGX/meson.build, line 69 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvD3bm3Xe2WvH1UsAh:-MkvD3bn5fENj95uWbHF:b-bcdtrp) ([raw file](https://github.com/gramineproject/gramine/blob/3db673bae9e034d2dd9694ee3c066a6118c5caff/Pal/src/host/Linux-SGX/meson.build#L69)):*
> ```Meson
> 
> # TODO: after meson 0.54 those two targets can be combined, and the second one might be passed to
> # installs in python/ directory
> ```

We now require meson 0.55+. So whatever this TODO asks to do, it can be done. But I don't understand what it means to combine these two targets, so not blocking.

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkuwPphBV_PM8wuHPH0):*
+ `Signed-off-by: Wojtek Porczyk <woju@invisiblethingslab.com>`
___
*[Pal/src/host/Linux-SGX/meson.build, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvNahQ-CK4VE_5B7KE:-MkvNahQ-CK4VE_5B7KF:b-c4c01t) ([raw file](https://github.com/gramineproject/gramine/blob/3db673bae9e034d2dd9694ee3c066a6118c5caff/Pal/src/host/Linux-SGX/meson.build#L191)):*
> ```Meson
>     dependencies: [
>         common_dep,
>         dependency('libprotobuf-c'),
> ```

Can you move this dependency together with other in toplevel `meson.build`?
___
*[Pal/src/host/Skeleton/meson.build, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvN78nE_wI9X8jLVa7:-MkvN78nE_wI9X8jLVa8:b-iijo5m) ([raw file](https://github.com/gramineproject/gramine/blob/7e59c4d0a64e1bb51aa8e8908c6a1fe1a43337d8/Pal/src/host/Skeleton/meson.build#L12)):*
> ```Meson
> libgramine_pal_skeleton = cc.find_library('gramine-lib',
>     dirs: join_paths(meson.current_source_dir(), '.lib'))
> ```

If you removed this, then we probably can also remove `make -C ... PAL_HOST=Skeleton` from CI.

**Comment by woju** [comment]
> gsgx.h header (generated using a Python script)

That this was generated in meson (not in make) was killer feature for packaging, because we need to compile pal-sgx three times, once for each driver. So we still can't just make three separate builddirs, we need three separate packaging setups.

**Review by pwmarcz — COMMENTED** [review]
I agree it sounds important, but I still don't want to bundle it in this PR. I can submit a next PR based on this one.

More on why I'm doing it this way:

The solution on your branch introduces a global `include` directory and auto-generated `gramine-config.h`. It might well be the best solution, but it still adds a new mechanism for this one thing, so I think it's worth adding and discussing separately.

It also seems like that PR would require more testing: we're talking about supporting four different drivers (upstream, out-of-tree, DCAP 1.6, and DCAP 1.10), and I think Jenkins does not cover them all.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107#-:-Mkv_AgBDTA2wQGj1ERe:bhk90a3)* status: 10 of 15 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @pwmarcz, and @woju)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkuwPphBV_PM8wuHPH0):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

+ `Signed-off-by: Wojtek Porczyk <woju@invisiblethingslab.com>`
</blockquote></details>

OK, I'll add it during rebase.
___
*[Pal/src/host/Linux-SGX/Makefile, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvBOKbA-Wz6g3HtLHP:-Mkva-q-BIywy_i24j0m:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3db673bae9e034d2dd9694ee3c066a6118c5caff/Pal/src/host/Linux-SGX/Makefile#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This line can be removed.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/meson.build, line 69 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvD3bm3Xe2WvH1UsAh:-Mkva4Ne9jTqEo3PEc81:bz9mg1) ([raw file](https://github.com/gramineproject/gramine/blob/3db673bae9e034d2dd9694ee3c066a6118c5caff/Pal/src/host/Linux-SGX/meson.build#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We now require meson 0.55+. So whatever this TODO asks to do, it can be done. But I don't understand what it means to combine these two targets, so not blocking.
</blockquote></details>

@woju Should we? I would prefer to leave this TODO for now.
___
*[Pal/src/host/Linux-SGX/meson.build, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvNahQ-CK4VE_5B7KE:-MkvaM-z7q6yrVwOhMFU:b-ia8yql) ([raw file](https://github.com/gramineproject/gramine/blob/3db673bae9e034d2dd9694ee3c066a6118c5caff/Pal/src/host/Linux-SGX/meson.build#L191)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can you move this dependency together with other in toplevel `meson.build`?
</blockquote></details>

You mean, create a `*_dep` variable for it? Done.
___
*[Pal/src/host/Skeleton/meson.build, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvN78nE_wI9X8jLVa7:-Mkvb77A6A4lrqTSln_2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7e59c4d0a64e1bb51aa8e8908c6a1fe1a43337d8/Pal/src/host/Skeleton/meson.build#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If you removed this, then we probably can also remove `make -C ... PAL_HOST=Skeleton` from CI.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
Our current Jenkins only covers the legacy out-of-tree driver, IIRC. So yes, no testing for different drivers.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107#-:-Mkvhw_t-L4xGeFsdoVZ:bh8o401)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @woju)

___
*[Pal/src/host/Linux-SGX/meson.build, line 69 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvD3bm3Xe2WvH1UsAh:-MkviFUf6hhm7FaBKT-P:bpxb3oq) ([raw file](https://github.com/gramineproject/gramine/blob/3db673bae9e034d2dd9694ee3c066a6118c5caff/Pal/src/host/Linux-SGX/meson.build#L69)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

@woju Should we? I would prefer to leave this TODO for now.
</blockquote></details>

OK, sure

**Review by woju — DISMISSED** [review]
Sure. Yes,  that's correct, we have OOT driver in Jenkins.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107#-:-Mkwf2lr3tNJwy3r313w:bpe6opb)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux-SGX/meson.build, line 69 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvD3bm3Xe2WvH1UsAh:-MkwelGxARTJxCc8se0k:b-q54x4m) ([raw file](https://github.com/gramineproject/gramine/blob/3db673bae9e034d2dd9694ee3c066a6118c5caff/Pal/src/host/Linux-SGX/meson.build#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, sure
</blockquote></details>

Yes, not now. There's `install:` to rethink.
___
*[Pal/src/host/Linux-SGX/meson.build, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/107#-MkvNahQ-CK4VE_5B7KE:-MkwewNU0JPj9KePRy0e:bily6mp) ([raw file](https://github.com/gramineproject/gramine/blob/3db673bae9e034d2dd9694ee3c066a6118c5caff/Pal/src/host/Linux-SGX/meson.build#L191)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

You mean, create a `*_dep` variable for it? Done.
</blockquote></details>

Yes. Thanks.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[Pal/src/Makefile, line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-Mkwm9sjAJYJmRmn6Rni:-Mkwm9sjAJYJmRmn6Rnj:b5lka73) ([raw file](https://github.com/gramineproject/gramine/blob/9c556458f674b701b19ceb84f083fc97478e3da2/Pal/src/Makefile#L13)):*
> ```Makefile
> ifeq ($(PAL_HOST),Linux-SGX)
> 	$(MAKE) -C $(HOST_DIR)
> endif
> ```

Hmm, don't we need an `else` clause? I'm not sure how "raw" are Make `ifdefs`, but I'd guess they may be similar to C, in which case, this recipe will turn into a dependency-only declaration if `$(PAL_HOST) != Linux-SGX`.
___
*[Pal/src/Makefile, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-Mkwnqpu3eC0Ku2871xu:-Mkwnqpu3eC0Ku2871xv:bn4usz) ([raw file](https://github.com/gramineproject/gramine/blob/baee61e25f03af14a90be289987277de3b916cf6/Pal/src/Makefile#L35)):*
> ```Makefile
> ifeq ($(ARCH),x86_64)
> CFLAGS += $(call cc-option, -fstack-protector-strong -mstack-protector-guard=tls \
> 	                        -mstack-protector-guard-reg=%gs -mstack-protector-guard-offset=8)
> ```

Where did these flags go? I guess we now set them globally, for all in-enclave stuff?
___
*[subprojects/packagefiles/mbedtls/compile.sh, line 27 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-MkwnAeG4vscBUmvE2fF:-Mkwn6yq0lEgLoSz74SZ:b-pojyj5) ([raw file](https://github.com/gramineproject/gramine/blob/9c556458f674b701b19ceb84f083fc97478e3da2/subprojects/packagefiles/mbedtls/compile.sh#L27)):*
> ```Shell
> patch -p1 --directory "$PRIVATE_DIR" <"$CURRENT_SOURCE_DIR"/gramine.patch
> 
> # Disable the default stack protector, because it conflicts with the one used by Gramine
> ```

I'd add a TODO here saying that we should have two builds of mbedtls (one for enclave and one for outside/tools), then we wouldn't need to disable this security mitigation (because we could configure it per-object).

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: 14 of 16 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Pal/src/Makefile, line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-Mkwm9sjAJYJmRmn6Rni:-MkziYDy4v7efwE_dc8b:b2dr2qw) ([raw file](https://github.com/gramineproject/gramine/blob/9c556458f674b701b19ceb84f083fc97478e3da2/Pal/src/Makefile#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, don't we need an `else` clause? I'm not sure how "raw" are Make `ifdefs`, but I'd guess they may be similar to C, in which case, this recipe will turn into a dependency-only declaration if `$(PAL_HOST) != Linux-SGX`.
</blockquote></details>

That's the idea, I think - for non-SGX we want `host_lib_recurse` to be no-op, and declaring it as a phony dependency-only target achieves that.
___
*[Pal/src/Makefile, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-Mkwnqpu3eC0Ku2871xu:-MkziKRcDYkWXQA8zWyu:bj5asa8) ([raw file](https://github.com/gramineproject/gramine/blob/baee61e25f03af14a90be289987277de3b916cf6/Pal/src/Makefile#L35)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Where did these flags go? I guess we now set them globally, for all in-enclave stuff?
</blockquote></details>

Yes, this is now `cflags_custom_stack_protector` in main `meson.build`.
___
*[subprojects/packagefiles/mbedtls/compile.sh, line 27 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-MkwnAeG4vscBUmvE2fF:-MkzjKcLDWgQbg9GiVRl:b-e78cnr) ([raw file](https://github.com/gramineproject/gramine/blob/9c556458f674b701b19ceb84f083fc97478e3da2/subprojects/packagefiles/mbedtls/compile.sh#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add a TODO here saying that we should have two builds of mbedtls (one for enclave and one for outside/tools), then we wouldn't need to disable this security mitigation (because we could configure it per-object).
</blockquote></details>

Actually it looks like I misunderstood, `mbedtls_pal` is the library that we use in-enclave. So these options are supposed to go to `compile-pal.sh`.

@woju, is that right?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: 14 of 16 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[subprojects/packagefiles/mbedtls/compile.sh, line 27 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-MkwnAeG4vscBUmvE2fF:-MkzrBTI7ve3c3TmvpoA:b-cqzbk5) ([raw file](https://github.com/gramineproject/gramine/blob/9c556458f674b701b19ceb84f083fc97478e3da2/subprojects/packagefiles/mbedtls/compile.sh#L27)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually it looks like I misunderstood, `mbedtls_pal` is the library that we use in-enclave. So these options are supposed to go to `compile-pal.sh`.

@woju, is that right?
</blockquote></details>

Oh, but we also have to determine whether these custom options work or not (GCC in 18.04 and Clang don't have them). They really should be passed from Meson. I don't know how to do that easily, so I'll leave a TODO.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/Makefile, line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-Mkwm9sjAJYJmRmn6Rni:-Ml-d5TxA5JD0aadiWQ7:bhyau90) ([raw file](https://github.com/gramineproject/gramine/blob/9c556458f674b701b19ceb84f083fc97478e3da2/Pal/src/Makefile#L13)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That's the idea, I think - for non-SGX we want `host_lib_recurse` to be no-op, and declaring it as a phony dependency-only target achieves that.
</blockquote></details>

It doesn't, if I'm understanding this case correctly. In Make, if you just write `a: b` then `make a` will fail saying that there's no recipe to make `a`. You need to write either `a: b;` or:
```Make
a: b
	@:
```

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/107#-Ml-eKuN9T2OOIVyfFNR:-Ml-eKuN9T2OOIVyfFNS:bfn7o62) (no related file):*
Hmm, I get:
> ```Pal/src/host/Linux-SGX/meson.build:92:0: ERROR: Link target '<CustomTarget 54091a3@@mbedtls_pal@cus: ['/home/mkow/gramine/subprojects/mbedtls-mbedtls-2.26.0/compile-pal.sh', '@CURRENT_SOURCE_DIR@', '/home/mkow/gramine/build/subprojects/mbedtls-mbedtls-2.26.0', '@PRIVATE_DIR@', '@OUTPUT@', '--', 'SUFFIX=_pal']>' is not linkable.```

When trying to clean-build this PR. My invocation: `meson setup build/ --werror --buildtype=debug -Ddirect=enabled -Dsgx=enabled --prefix=~/gramine-install`. Any ideas what I'm doing wrong?

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: 15 of 16 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/107#-Ml-eKuN9T2OOIVyfFNR:-Ml0GHX-CNgK2dx3xZ86:bvvgg1k) (no related file):*
Maybe you need to do a "cleaner" build, did you delete the `subprojects/mbedtls-2.26.0` directory?

>Apparently Meson doesn't react to changes in subprojects, so you might want to delete `subprojects/mbedtls-2.26.0` before rebuilding; it keeps using the old `meson.build` otherwise.

(This part of `mbedtls` subproject is unused on master, and broken, this PR contains a fix - see the end of `subprojects/packagefiles/mbedtls/meson.build`).

---
___
*[Pal/src/Makefile, line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-Mkwm9sjAJYJmRmn6Rni:-Ml0GnflDOShPa-V2XYw:b-7h6u48) ([raw file](https://github.com/gramineproject/gramine/blob/9c556458f674b701b19ceb84f083fc97478e3da2/Pal/src/Makefile#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It doesn't, if I'm understanding this case correctly. In Make, if you just write `a: b` then `make a` will fail saying that there's no recipe to make `a`. You need to write either `a: b;` or:
```Make
a: b
	@:
```
</blockquote></details>

It still works without the `@:`, but Make says "nothing to be done for `host_lib_recurse`". Looks like Make considers the `host_lib_recurse` target already satisfied, probably because it's phony. Weird.

Anyway, I added `@:` here. Hopefully this won't stay for long anyway.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/107#-Ml-eKuN9T2OOIVyfFNR:-Ml0M9lK4sb-dbAQqKmS:b-nsjmpm) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Maybe you need to do a "cleaner" build, did you delete the `subprojects/mbedtls-2.26.0` directory?

>Apparently Meson doesn't react to changes in subprojects, so you might want to delete `subprojects/mbedtls-2.26.0` before rebuilding; it keeps using the old `meson.build` otherwise.

(This part of `mbedtls` subproject is unused on master, and broken, this PR contains a fix - see the end of `subprojects/packagefiles/mbedtls/meson.build`).
</blockquote></details>

Oh, that's really bad... So, it's actually not enough to delete `build/` for a clean build? Is there a Meson subcommand to do a proper cleanup?
CC: @woju

---
___
*[Pal/src/Makefile, line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/107#-Mkwm9sjAJYJmRmn6Rni:-Ml0Kz150t6TN8f7M_-x:b-psi5oy) ([raw file](https://github.com/gramineproject/gramine/blob/9c556458f674b701b19ceb84f083fc97478e3da2/Pal/src/Makefile#L13)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It still works without the `@:`, but Make says "nothing to be done for `host_lib_recurse`". Looks like Make considers the `host_lib_recurse` target already satisfied, probably because it's phony. Weird.

Anyway, I added `@:` here. Hopefully this won't stay for long anyway.
</blockquote></details>

Ah, right, no idea how this interacts with `.PHONY` :) But anyways, even if it worked, I don't enjoy #ifdefs changing the code structure. Now it looks good :)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/107)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
