### PR TITLE
[Pal] Support direct mode in Windows WSL

### PR DESCRIPTION
**Pull request by guzongmin**
Windows WSL does not have "/sys/devices/system/node/" folder, just
ignore the check and use the default value.

Signed-off-by: Zongmin Gu <zongmin.gu@intel.com>

## Description of the changes 
The direct mode does not work under Windows WSL. The reason is: WSL does not have 
 /sys/devices/system/node/ folder, the PAL is not able to get the node information. In this
case, using the default node number 0 is a good solution.

## How to test this PR? 
Execute the Gramine hello world in Windows WSL with direct mode.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @guzongmin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/679#-N5FA4tu-wa_Hab7lsBn:-N5FA4tu-wa_Hab7lsBo:bi6leq8) (no related file):*
Please use up-to-date `master` when submitting PRs, this one has outdated base.

___

**Review by guzongmin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/679#-N5FA4tu-wa_Hab7lsBn:-N5ZMnS1DDvQbrT2_7g7:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use up-to-date `master` when submitting PRs, this one has outdated base.
</blockquote></details>

Done.

___

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @guzongmin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/679#-N5Zii_t4p7P9Qah0nu9:-N5Zii_t4p7P9Qah0nuA:blg19p4) (no related file):*
Your commit's author line points to a different GitHub account than you use to post the PR. Please ACK here from @ZongminGu account that this is ok (this is to prevent posting commits as someone else without their knowledge).
Ideally, for the future, please just open PRs from the same account as stated in the commits.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZlwwA28NAJoRLuwKX:-N5ZlwwA28NAJoRLuwKY:by7yjra) (no related file):*
Doesn't this PR introduce a few memory corruptions? Now you'll have dangling pointers in `struct pal_cpu_core_info`, pointing to a non-existent NUMA node. I guess this PR even fails on ASan...
Instead of making global state weird (0 NUMA nodes?) just create a single, fake node and fill all the structures with some sane defaults.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZhGas-cvxi3vafZ0M):*
(we changed this convention a few days ago, together with directory renames)



_Suggestion:_
```
[PAL]
```
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZhQZz0uEmMrBkXZCk):*
It's now "Windows Windows Subsystem for Linux", but I think it's justified here - WSL alone may not be recognizable by everyone ;)



_Code quote:_
```
Windows WSL
```
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZiYkP0cwWqs8IgYoZ):*
please fix wrapping
___
*[`pal/src/host/linux-common/topo_info.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5Zk_yZ7n53iafIeTdi:-N5Zk_yZ7n53iafIeTdj:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/52df45c190f95f3e3b5be5d7e8922ed42a336da7/pal/src/host/linux-common/topo_info.c#L284)):*
> ```C
>     size_t nodes_cnt = 0;
>     /* Get the CPU node number. By default, the number is 0.
>      * Some system does not have the file, for example, Windows WSL.
> ```





_Suggestion:_
```C
Some systems do
```
___
*[`pal/src/host/linux-common/topo_info.c` line 285 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZknGIDEMFcr_y0Uwv:-N5ZknGIDEMFcr_y0Uww:btkl8q9) ([raw file](https://github.com/gramineproject/gramine/blob/52df45c190f95f3e3b5be5d7e8922ed42a336da7/pal/src/host/linux-common/topo_info.c#L285)):*
> ```C
>     /* Get the CPU node number. By default, the number is 0.
>      * Some system does not have the file, for example, Windows WSL.
>      * So, do not need to check the return value of the function. */
> ```

You're conflating many possible errors here. Please instead ignore the failure only on `-ENOENT` and update this comment.



_Code quote:_
```C
So, do not need to check the return value of the function. */
```
___
*[`pal/src/host/linux-common/topo_info.c` line 320 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZlfWI88I1sRUGt8k3:-N5ZlfWI88I1sRUGt8k4:b-2y6s2h) ([raw file](https://github.com/gramineproject/gramine/blob/52df45c190f95f3e3b5be5d7e8922ed42a336da7/pal/src/host/linux-common/topo_info.c#L320)):*
> ```C
>     if (nodes_cnt > 0) {
>         ret = iterate_ranges_from_file("/sys/devices/system/node/online", set_numa_node_online,
>                                    numa_nodes);
> ```

please fix alignment

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @guzongmin and @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZhGas-cvxi3vafZ0M):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(we changed this convention a few days ago, together with directory renames)
</blockquote></details>

Did we? I don't think we discussed this

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @guzongmin)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZhGas-cvxi3vafZ0M):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Did we? I don't think we discussed this
</blockquote></details>

It's even _you_ who applied this change to the guidelines... (in https://github.com/gramineproject/gramine/pull/672)

**Review by guzongmin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @guzongmin, and @mkow)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZiYkP0cwWqs8IgYoZ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix wrapping
</blockquote></details>

What is the meaning of "wrapping" here? I do not get it.

**Review by guzongmin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)* status: 1 of 2 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @ZongminGu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZlwwA28NAJoRLuwKX:-N5t1RUp6aa77hW_hMPf:b2rx6tg) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Doesn't this PR introduce a few memory corruptions? Now you'll have dangling pointers in `struct pal_cpu_core_info`, pointing to a non-existent NUMA node. I guess this PR even fails on ASan...
Instead of making global state weird (0 NUMA nodes?) just create a single, fake node and fill all the structures with some sane defaults.
</blockquote></details>

Thanks for your comments. I updated the code to use some default values in this case.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/679#-N5Zii_t4p7P9Qah0nu9:-N5t1gIt5paezicoxi-Y:bo2roi0) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Your commit's author line points to a different GitHub account than you use to post the PR. Please ACK here from @ZongminGu account that this is ok (this is to prevent posting commits as someone else without their knowledge).
Ideally, for the future, please just open PRs from the same account as stated in the commits.
</blockquote></details>

I almost forget the old account. I have deleted the old one. This account is my only GitHub account linked with zongmin.gu@intel.com. Thank you for pointing it out.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZhGas-cvxi3vafZ0M):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's even _you_ who applied this change to the guidelines... (in https://github.com/gramineproject/gramine/pull/672)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5Zk_yZ7n53iafIeTdi:-N5t2If68Ep43IVBWzPl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/52df45c190f95f3e3b5be5d7e8922ed42a336da7/pal/src/host/linux-common/topo_info.c#L284)):*
> ```C
>     size_t nodes_cnt = 0;
>     /* Get the CPU node number. By default, the number is 0.
>      * Some system does not have the file, for example, Windows WSL.
> ```

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 285 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZknGIDEMFcr_y0Uwv:-N5t2Ke_3L_TTd4y-A9W:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/52df45c190f95f3e3b5be5d7e8922ed42a336da7/pal/src/host/linux-common/topo_info.c#L285)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You're conflating many possible errors here. Please instead ignore the failure only on `-ENOENT` and update this comment.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 320 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZlfWI88I1sRUGt8k3:-N5t2Nei-4SsZ8cZPrs5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/52df45c190f95f3e3b5be5d7e8922ed42a336da7/pal/src/host/linux-common/topo_info.c#L320)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)* status: 1 of 2 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @guzongmin and @mkow)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65C3nH49UwUiRzDiZc):*




_Suggestion:_
```
 Windows Subsystem for linux (WSL)
```
___
*[`pal/src/host/linux-common/topo_info.c` line 320 at r2](https://reviewable.io/reviews/gramineproject/gramine/679#-N5ZlfWI88I1sRUGt8k3:-N65CAUmB4VeUqFkGkcy:bgqy620) ([raw file](https://github.com/gramineproject/gramine/blob/52df45c190f95f3e3b5be5d7e8922ed42a336da7/pal/src/host/linux-common/topo_info.c#L320)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now you exceed our line length limit ;) Same below.
___
*[`pal/src/host/linux-common/topo_info.c` line 282 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65CvQyAzcZ2hK4XRHd:-N65CvQyAzcZ2hK4XRHe:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L282)):*
> ```C
>         return ret;
> 
>     bool is_cpu_nodes_existing = false;
> ```





_Suggestion:_
```C
is_numa_nodes_info_available
```
___
*[`pal/src/host/linux-common/topo_info.c` line 283 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65GgaU6rv-5oS7b2O6:-N65GgaV8ynfRgkJj-rF:b-lmgywu) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L283)):*
> ```C
> 
>     bool is_cpu_nodes_existing = false;
>     size_t nodes_cnt = 1;
> ```

Now you miscalculate the number of nodes in normal case.
Please be more careful when submitting PRs, you are making a lot of typos and bugs. You should carefully test and self-review all the changes before publishing.
___
*[`pal/src/host/linux-common/topo_info.c` line 286 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65DQcu-8Gb2HbDOBJv:-N65DQcv36GRhCpi7bvJ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L286)):*
> ```C
>     /* Get the CPU node number. By default, the number is 1.
>      * Some systems do not have the file, for example, Windows Subsystem for Linux.
>      * So, ignor the -ENOENT error.*/
> ```





_Suggestion:_
```C
So, we ignore
```
___
*[`pal/src/host/linux-common/topo_info.c` line 289 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65EyQBA3LMsJqJ_bwi:-N65EyQBA3LMsJqJ_bwj:b-tpimv7) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L289)):*
> ```C
>     ret = iterate_ranges_from_file("/sys/devices/system/node/possible", get_ranges_end, &nodes_cnt);
>     if (ret < 0)
>     {
> ```

wrong formatting
___
*[`pal/src/host/linux-common/topo_info.c` line 296 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65FJvb8BtVRs-Kn-jR:-N65FJvb8BtVRs-Kn-jS:bc0gfl4) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L296)):*
> ```C
>     } else {
>         is_cpu_nodes_existing = true;
>     }
> ```

Please change to something like:
```C
if (ret < 0 && ret != -ENOENT)
    return ret;
bool is_numa_nodes_info_available = ret == 0;
```
___
*[`pal/src/host/linux-common/topo_info.c` line 401 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65CLGTDfZqXfuv_VmF:-N65CLGTDfZqXfuv_VmG:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L401)):*
> ```C
>         }
>     } else {
>         /*Set the distance with default value in Ubuntu 20.04*/
> ```





_Suggestion:_
```C
/* Set the distance to the default value from Ubuntu 20.04. */
```

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/679)* status: 1 of 2 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @guzongmin and @mkow)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65C3nH49UwUiRzDiZc):*
Well, also `linux` -> `Linux`
___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N66zonL5-RLU4gulpQS):*
This sentence `just ignore the check and use the default value` doesn't make sense to me. I guess a better wording will be `so we create a single fake NUMA node`.
___
*[`pal/src/host/linux-common/topo_info.c` line 282 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65CvQyAzcZ2hK4XRHd:-N66znVkC_Vll2dQoK6o:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L282)):*
> ```C
>         return ret;
> 
>     bool is_cpu_nodes_existing = false;
> ```

+1
___
*[`pal/src/host/linux-common/topo_info.c` line 289 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65EyQBA3LMsJqJ_bwi:-N66zcad4G49ZURwn744:bk5hhgn) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L289)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

wrong formatting
</blockquote></details>

Michal means that we don't put `{` on a separate line.
___
*[`pal/src/host/linux-common/topo_info.c` line 296 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65FJvb8BtVRs-Kn-jR:-N66zavS7wSUrHbKUQO1:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L296)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please change to something like:
```C
if (ret < 0 && ret != -ENOENT)
    return ret;
bool is_numa_nodes_info_available = ret == 0;
```
</blockquote></details>

+1
___
*[`pal/src/host/linux-common/topo_info.c` line 401 at r3](https://reviewable.io/reviews/gramineproject/gramine/679#-N65CLGTDfZqXfuv_VmF:-N67-AKK6nRl0ao8PLhi:b9rwlj0) ([raw file](https://github.com/gramineproject/gramine/blob/4ac7e9361401620b5d49487c822ef150bf35bfc2/pal/src/host/linux-common/topo_info.c#L401)):*
> ```C
>         }
>     } else {
>         /*Set the distance with default value in Ubuntu 20.04*/
> ```

But this is not about Ubuntu OS distro, but about the Linux kernel. So please replace with e.g. `... in Linux 5.4`

**Comment by dimakuv** [comment]
I'm closing this PR, as it seems very low priority (if needed at all), and the original author is not pursuing it anymore.

**Pull request closed without merging**
