### PR TITLE
[PAL] Update "pal_loader" to "gramine-*" in warnings

### PR DESCRIPTION
**Pull request by mkow**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/833)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/833)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`pal/src/host/linux/pal_main.c` line 119 at r1](https://reviewable.io/reviews/gramineproject/gramine/833#-N96uskODEibODU1a12E:-N96uskP2vdQClCXMBCR:bji0lej) ([raw file](https://github.com/gramineproject/gramine/blob/2adef58ec2ce6b3cb55950eadf7c96c0ddc26c4e/pal/src/host/linux/pal_main.c#L119)):*
> ```C
>                "\tChildren:      %s <path to libpal.so> child <parent_stream_fd> args...",
>                self, self);
>     log_always("This is an internal interface. Use gramine-* wrappers to launch applications in "
> ```

This is Linux PAL, so you can just use `gramine-direct` here
___
*[`pal/src/host/linux-sgx/host_main.c` line 1015 at r1](https://reviewable.io/reviews/gramineproject/gramine/833#-N96ux6C5feGAmGwIZqL:-N96ux6C5feGAmGwIZqM:bbhoct2) ([raw file](https://github.com/gramineproject/gramine/blob/2adef58ec2ce6b3cb55950eadf7c96c0ddc26c4e/pal/src/host/linux-sgx/host_main.c#L1015)):*
> ```C
>                "\tChildren:      %s <path to libpal.so> child <parent_stream_fd> args...",
>                self, self);
>     log_always("This is an internal interface. Use gramine-* wrappers to launch applications in "
> ```

ditto (`gramine-sgx`)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/833)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux/pal_main.c` line 119 at r1](https://reviewable.io/reviews/gramineproject/gramine/833#-N96uskODEibODU1a12E:-N96wv0Z-fake0nHN3bY:bxix0zu) ([raw file](https://github.com/gramineproject/gramine/blob/2adef58ec2ce6b3cb55950eadf7c96c0ddc26c4e/pal/src/host/linux/pal_main.c#L119)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is Linux PAL, so you can just use `gramine-direct` here
</blockquote></details>

Ah, right, fixed.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1015 at r1](https://reviewable.io/reviews/gramineproject/gramine/833#-N96ux6C5feGAmGwIZqL:-N96wx0M-REH4yZ9e-s9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2adef58ec2ce6b3cb55950eadf7c96c0ddc26c4e/pal/src/host/linux-sgx/host_main.c#L1015)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`gramine-sgx`)
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/833)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/833)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Pull request merged**
