### PR TITLE
[gramine] Remove PAL_NUM type

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 
Get rid of PAL_NUM and replace it with standard types.

## How to test this PR?
Build with clang and gcc.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x0kcq0_XRx-Hhxm1e:-N2x0kcq0_XRx-Hhxm1f:b-nj2ezs) (no related file):*
@boryspoplawski: Will this conflict significantly with #579? If so, then I guess we should wait with merging it?

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2wufDd0zkiHgXtLMSm):*
We usually drop the component tag if it's a global change. Or, in this case, `[Pal]` would also be technically fine - the change itself is in PAL API, LibOS only needs to adopt to it.



_Code quote:_
```
[gramine] 
```
___
*[`Pal/include/pal/pal.h` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2wzyGQCDsxKMurBSyB:-N2wzyGQCDsxKMurBSyC:bfur1f3) ([raw file](https://github.com/gramineproject/gramine/blob/660a9d4ce5531ec2029bd9f065b4b866aea09695/Pal/include/pal/pal.h#L12)):*
> ```objc
> #define PAL_H
> 
> #include <sys/types.h>
> ```

please sort
___
*[`Pal/include/pal/pal.h` line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x-1m1AIsm_yEItOAG:-N2x-1m1AIsm_yEItOAH:b3eyt8) ([raw file](https://github.com/gramineproject/gramine/blob/660a9d4ce5531ec2029bd9f065b4b866aea09695/Pal/include/pal/pal.h#L123)):*
> ```objc
>      * see e.g. SYSTEM_INFO::dwAllocationGranularity on Windows.
>      */
>     uint64_t alloc_align;
> ```

Not `size_t` or `uintptr_t`? On 32-bit this should be 32-bit.
___
*[`Pal/src/db_misc.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x3xmd6i5CZDVG-oIJ:-N2x3xmd6i5CZDVG-oIK:b4qay90) ([raw file](https://github.com/gramineproject/gramine/blob/132ebc14fd339232a95538b920efa85e6119693c/Pal/src/db_misc.c#L32)):*
> ```C
>     long quota = _DkMemoryAvailableQuota();
>     if (quota < 0)
>         quota = 0;
> ```

good riddance
___
*[`Pal/src/db_streams.c` line 467 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x49wADCK8JyjvZ24k:-N2x49wADCK8JyjvZ24l:be66uox) ([raw file](https://github.com/gramineproject/gramine/blob/660a9d4ce5531ec2029bd9f065b4b866aea09695/Pal/src/db_streams.c#L467)):*
> ```C
> }
> 
> int DkStreamSetLength(PAL_HANDLE handle, size_t length) {
> ```

This has to be `off_t`
___
*[`Pal/src/host/Linux-SGX/db_pipes.c` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x4nwqCnBG6S4AGuJC:-N2x4nwqCnBG6S4AGuJD:b4qx1k2) ([raw file](https://github.com/gramineproject/gramine/blob/660a9d4ce5531ec2029bd9f065b4b866aea09695/Pal/src/host/Linux-SGX/db_pipes.c#L89)):*
> ```C
>     spinlock_unlock(&g_handshake_helper_thread_list_lock);
> 
>     __atomic_store_n(&handle->pipe.handshake_done, true, __ATOMIC_RELEASE);
> ```

@boryspoplawski: Was there any reason we put `0`/`1` here instead of a usual `bool`? I faintly remember that we discussed this during the review...

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: 24 of 27 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2wufDd0zkiHgXtLMSm):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We usually drop the component tag if it's a global change. Or, in this case, `[Pal]` would also be technically fine - the change itself is in PAL API, LibOS only needs to adopt to it.
</blockquote></details>

Done.
___
*[`Pal/include/pal/pal.h` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2wzyGQCDsxKMurBSyB:-N2x9zqI19D-qu_GCV_L:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/660a9d4ce5531ec2029bd9f065b4b866aea09695/Pal/include/pal/pal.h#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.
___
*[`Pal/include/pal/pal.h` line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x-1m1AIsm_yEItOAG:-N2x9PZ54l8AH9NAiLeY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/660a9d4ce5531ec2029bd9f065b4b866aea09695/Pal/include/pal/pal.h#L123)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not `size_t` or `uintptr_t`? On 32-bit this should be 32-bit.
</blockquote></details>

Done.
___
*[`Pal/src/db_streams.c` line 467 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x49wADCK8JyjvZ24k:-N2x9I1NDqMJfigKezgS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/660a9d4ce5531ec2029bd9f065b4b866aea09695/Pal/src/db_streams.c#L467)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This has to be `off_t`
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 24 of 27 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x0kcq0_XRx-Hhxm1e:-N2xNI9C5x6G2ntGc4Gk:b-gwe5wn) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski: Will this conflict significantly with #579? If so, then I guess we should wait with merging it?
</blockquote></details>

There will be some conflicts, yes. Shouldn't be that bad though. It will definitely be easier to rebase this than #579 but I won't insist on waiting, not such a big issue

___
___
*[`Documentation/devel/new-syscall.rst` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xMXD10LIrMMuD_Wda:-N2xMXD2D0BtKCCX6ANX:b-re20s0) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Documentation/devel/new-syscall.rst#L46)):*
> ```reStructuredText
> the PAL call::
> 
>    bool DkThreadSetCPUAffinity(uint32_t cpu_num, PAL_IDX* cpu_indexes);
> ```

Why `uint32_t`?
___
*[`Pal/include/pal/pal.h` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xFTNM4pn4BEmOMYyL:-N2xFTNM4pn4BEmOMYyM:b-bahzoi) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L17)):*
> ```objc
> #include <stdint.h>
> #include <stdnoreturn.h>
> #include <sys/types.h>
> ```

No no, please never include stuff from `sys/*`. These headers contain stuff other than types too (e.g. function declarations).
Why do you even need it?
___
*[`Pal/include/pal/pal.h` line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xG1ed-kOm8BuklEyy:-N2xG1ed-kOm8BuklEyz:bbf9gfk) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L215)):*
> ```objc
>  * \param exit_code  The exit value returned to the host.
>  */
> noreturn void DkProcessExit(int exit_code);
> ```

`unsigned`
___
*[`Pal/include/pal/pal.h` line 322 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xGL7iBNA2cC_24mq1:-N2xGL7iBNA2cC_24mq2:bl0rnhv) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L322)):*
> ```objc
>  * directory entries.
>  */
> int DkStreamRead(PAL_HANDLE handle, off_t offset, size_t* count, void* buffer, char* source,
> ```

I would leave the old version with `unsigned` offset, it cannot be negative here anyway.
___
*[`Pal/include/pal/pal.h` line 338 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xGQfn0zTHmKhgWHya:-N2xGQfn0zTHmKhgWHyb:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L338)):*
> ```objc
>  * \returns 0 on success, negative error code on failure.
>  */
> int DkStreamWrite(PAL_HANDLE handle, off_t offset, size_t* count, void* buffer,
> ```

ditto
___
*[`Pal/include/pal/pal.h` line 365 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xGc7N9EW7uz_iHwAP:-N2xGc7N9EW7uz_iHwAQ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L365)):*
> ```objc
>  * \returns 0 on success, negative error code on failure.
>  */
> int DkStreamMap(PAL_HANDLE handle, void** addr_ptr, pal_prot_flags_t prot, off_t offset,
> ```

ditto
___
*[`Pal/include/pal/pal.h` line 382 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xGdl16G2M53olxyzc:-N2xGdl16G2M53olxyzd:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L382)):*
> ```objc
>  * \returns 0 on success, negative error code on failure.
>  */
> int DkStreamSetLength(PAL_HANDLE handle, off_t length);
> ```

ditto
___
*[`Pal/regression/Memory.c` line 91 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xHzS20oabFveXOleK:-N2xHzS20oabFveXOleL:bwlemm7) ([raw file](https://github.com/gramineproject/gramine/blob/132ebc14fd339232a95538b920efa85e6119693c/Pal/regression/Memory.c#L91)):*
> ```C
>     /* Testing available memory (must be within valid range) */
>     PAL_NUM avail = DkMemoryAvailableQuota();
>     if (avail > 0 && avail < DkGetPalPublicState()->mem_total)
> ```

You removed `> 0` check, why?
___
*[`Pal/src/db_process.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xIIdREgUpsdpJXAmL:-N2xIIdS4AS-3QeuMSAi:bbf9gfk) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/src/db_process.c#L20)):*
> ```C
> }
> 
> noreturn void DkProcessExit(int exitcode) {
> ```

`unsigned`
___
*[`Pal/src/host/Linux-SGX/db_pipes.c` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x4nwqCnBG6S4AGuJC:-N2xKQVwAliipzac5jXt:b1kn2x8) ([raw file](https://github.com/gramineproject/gramine/blob/660a9d4ce5531ec2029bd9f065b4b866aea09695/Pal/src/host/Linux-SGX/db_pipes.c#L89)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski: Was there any reason we put `0`/`1` here instead of a usual `bool`? I faintly remember that we discussed this during the review...
</blockquote></details>

I think it was "something something, no idea how bools are stored (because they could be anything) and we know gcc atomics are buggy wrt types, so plain integer is better", not sure though, I barely remember this.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`Documentation/devel/new-syscall.rst` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xMXD10LIrMMuD_Wda:-N2xRi_lBKtLkYgR8i-H:buljl3t) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Documentation/devel/new-syscall.rst#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why `uint32_t`?
</blockquote></details>

If I understand correctly this is a CPU number I figure out it makes more sense to use 32 bits value, but I don't have strong opinion here. Maybe `size_t` is better here.
___
*[`Pal/include/pal/pal.h` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xFTNM4pn4BEmOMYyL:-N2xRw3H9tMhg5WUakZP:bn61nhx) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No no, please never include stuff from `sys/*`. These headers contain stuff other than types too (e.g. function declarations).
Why do you even need it?
</blockquote></details>

For `off_t`.  Do you prefer `fcntl.h` or `stdio.h` or `unistd.h` ?
I guess all of these have some kind of function declarations.
___
*[`Pal/include/pal/pal.h` line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xG1ed-kOm8BuklEyy:-N2xSK1i4zqd2L78BfJQ:b-s8neir) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L215)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`unsigned`
</blockquote></details>

Why? The _DkProcessExit expects `int`.
Or maybe we should change both?
___
*[`Pal/include/pal/pal.h` line 322 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xGL7iBNA2cC_24mq1:-N2xRdgS9PsD4wLvkW8Q:bt2boo4) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L322)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would leave the old version with `unsigned` offset, it cannot be negative here anyway.
</blockquote></details>

I guess we are trying to figure out this offline.
___
*[`Pal/regression/Memory.c` line 91 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xHzS20oabFveXOleK:-N2xRPVW1PquSeJYMKZt:b-xi7iii) ([raw file](https://github.com/gramineproject/gramine/blob/132ebc14fd339232a95538b920efa85e6119693c/Pal/regression/Memory.c#L91)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You removed `> 0` check, why?
</blockquote></details>

My bad. It still can be 0.
___
*[`Pal/src/db_process.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xIIdREgUpsdpJXAmL:-N2xRJix5PHgL2Tm3BCH:b-ltalmv) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/src/db_process.c#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`unsigned`
</blockquote></details>

Why?
The  _DkProcessExit expects `int`.



_Code quote:_
```C
 _DkProcessExit(
```

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`Documentation/devel/new-syscall.rst` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xMXD10LIrMMuD_Wda:-N2xTfJO3bWHk1YUImj5:bt7p0eo) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Documentation/devel/new-syscall.rst#L46)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

If I understand correctly this is a CPU number I figure out it makes more sense to use 32 bits value, but I don't have strong opinion here. Maybe `size_t` is better here.
</blockquote></details>

Idk, what rest of the codebase use for CPU indexes?
cc @mkow 
___
*[`Pal/include/pal/pal.h` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xFTNM4pn4BEmOMYyL:-N2xU1Iu9X7SljYgG9cM:b-9kxup2) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L17)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

For `off_t`.  Do you prefer `fcntl.h` or `stdio.h` or `unistd.h` ?
I guess all of these have some kind of function declarations.
</blockquote></details>

None of them. Also don't use `off_t`, it's definitely not what we want (it's 32bit on 32bit systems).
___
*[`Pal/include/pal/pal.h` line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xG1ed-kOm8BuklEyy:-N2xXF_20Re0tBE_q867:brstcli) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L215)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Why? The _DkProcessExit expects `int`.
Or maybe we should change both?
</blockquote></details>

Hmm, I think we should change them - these APIs handle unsigned numbers.
But unblocking, I'm not insisting on changing them in this PR, it's a bit unrelated
___
*[`Pal/src/db_process.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xIIdREgUpsdpJXAmL:-N2xY-YZ-dGFvbN1IW-h:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/src/db_process.c#L20)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Why?
The  _DkProcessExit expects `int`.
</blockquote></details>

ditto

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: 25 of 27 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`Documentation/devel/new-syscall.rst` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xMXD10LIrMMuD_Wda:-N3-Rq1yCSYAQCKSh8QJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Documentation/devel/new-syscall.rst#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`size_t`, I think.
</blockquote></details>

Done.
___
*[`Pal/include/pal/pal.h` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xFTNM4pn4BEmOMYyL:-N3-RqfI3RlJPLIu4Rl-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

None of them. Also don't use `off_t`, it's definitely not what we want (it's 32bit on 32bit systems).
</blockquote></details>

Done.
___
*[`Pal/include/pal/pal.h` line 322 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xGL7iBNA2cC_24mq1:-N3-Rtfi4Tuen40rT0nR:b-7aqqdc) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L322)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I guess we are trying to figure out this offline.
</blockquote></details>

`size_t` it is.
___
*[`Pal/include/pal/pal.h` line 338 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xGQfn0zTHmKhgWHya:-N3-Rw0Z2qMxPiUPVDuh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L338)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Pal/include/pal/pal.h` line 365 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xGc7N9EW7uz_iHwAP:-N3-RwW_3jFKwJbBBQMb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L365)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Pal/include/pal/pal.h` line 382 at r2](https://reviewable.io/reviews/gramineproject/gramine/608#-N2xGdl16G2M53olxyzc:-N3-Rx4f9M6KrKMpzTCn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f215b87f05c8d9f637a062911a76e31a648ea85b/Pal/include/pal/pal.h#L382)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 22 of 27 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/608#-N3IurU2C10W57hn6kkT:-N3IurU2C10W57hn6kkU:byfe16z) (no related file):*
Hurray, only `PAL_IDX` left!

___
___
*[`Pal/src/db_misc.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x3xmd6i5CZDVG-oIJ:-N3Iu89IAy8xM_3j1mw7:bqmwn77) ([raw file](https://github.com/gramineproject/gramine/blob/132ebc14fd339232a95538b920efa85e6119693c/Pal/src/db_misc.c#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

good riddance
</blockquote></details>

Only fools check for errors :)
___
*[`Pal/src/db_streams.c` line 467 at r1](https://reviewable.io/reviews/gramineproject/gramine/608#-N2x49wADCK8JyjvZ24k:-N3IuNrD0RnZAO-aoPk-:bc0jd8u) ([raw file](https://github.com/gramineproject/gramine/blob/660a9d4ce5531ec2029bd9f065b4b866aea09695/Pal/src/db_streams.c#L467)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Feels like I missed part of the (offline) discussion? But whatever, `uint64_t` sounds correct to me.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/608)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
