### PR TITLE
[Docs] Update logo

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Old logo still contained the old name.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/335)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/335)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/335)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/335)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/335)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
