### PR TITLE
[gitignore] Deduplicate entries

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 
Deduplicate entries that are shared between different group tests.
This change should simplify adding the simple test directories in the future.

## How to test this PR? 
```
$ touch asd.xml abi/asd.xml abi/x86_64/asd.xml
$ git status
```

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/554)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/554)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/554#-N0fYuhW9xbQ7C3FJyaG):*




_Suggestion:_
```
future
```

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/554)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/554#-N0fYuhW9xbQ7C3FJyaG):*
Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/554)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow)

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/554)* status: all files reviewed, 1 unresolved discussion, "squash! " found in commit messages' one-liners (waiting on @mkow)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/554)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/554)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
