### PR TITLE
[PAL] Drop `ms_` prefix

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

@mkow in https://github.com/gramineproject/gramine/pull/850 suggested that this `ms_` prefix is obsolote and useless.
So lets remove it.

## How to test this PR? 

Gramine test suite.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: 0 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/870#-NArynz130SXCt4mjeK6:-NArynz130SXCt4mjeK7:bbcafr3) (no related file):*
The idea is good, but you also need to rename `ms` objects. I suggest to rename to `ocall` and `ecall`, depending on the context.

___

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/870#-NArynz130SXCt4mjeK6:-NAtRYLDBjuo-tWYOB1g:b-kzhpqy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The idea is good, but you also need to rename `ms` objects. I suggest to rename to `ocall` and `ecall`, depending on the context.
</blockquote></details>

There's some more we should do:
- remove `typedefs` (IMO in this PR, since it will collide a lot),
- change names of the objects to also not be `ms` - you did this here, but only a very small part. 
    -  `ocall_exit_t ms` -> `struct ocall_exit` `ocall_args`/`ocall_exit_args` or something

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtSx6q0mR-Pon2-6r-:-NAtSx6q0mR-Pon2-6r0:b-4b438a) (no related file):*
This is a very bad timing for this PR, it will conflict with changes I'm making (they are not yet public, but are high priority and will be merged before next release). Please consult with others next time before you submit a huge rename

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtRQL8D1HI_0kT3aYT):*




_Suggestion:_
```
[PAL/Linux-SGX]
```
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 445 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtU0Un-7fWWFw5Lhv1:-NAtU0Un-7fWWFw5Lhv2:b41kahq) ([raw file](https://github.com/gramineproject/gramine/blob/b019df18cba624006578d6f14c7f8a7da3592b2b/pal/src/host/linux-sgx/enclave_ocalls.c#L445)):*
> ```C
>     void* obuf = NULL;
>     ocall_read_t* ms;
>     void* ptrbuf;
> ```

What is `ptrbuf` short for? Pleas use some meaningful name or well known abbreviation. Maybe `untrusted_buf`?
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 503 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtWzP3A9TkGIAkmceA:-NAtUDfS4xjsoeMpX5NN:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b019df18cba624006578d6f14c7f8a7da3592b2b/pal/src/host/linux-sgx/enclave_ocalls.c#L503)):*
> ```C
>     void* obuf = NULL;
>     ocall_write_t* ms;
>     const void* ptrbuf;
> ```

ditto
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 568 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtX0EE706YoE1t2cio:-NAtX0EE706YoE1t2cip:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b019df18cba624006578d6f14c7f8a7da3592b2b/pal/src/host/linux-sgx/enclave_ocalls.c#L568)):*
> ```C
>     void* obuf = NULL;
>     ocall_pread_t* ms;
>     void* ptrbuf;
> ```

ditto
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 627 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtX2vI7OKIv6-9gjA6:-NAtX2vI7OKIv6-9gjA7:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b019df18cba624006578d6f14c7f8a7da3592b2b/pal/src/host/linux-sgx/enclave_ocalls.c#L627)):*
> ```C
>     void* obuf = NULL;
>     ocall_pwrite_t* ms;
>     const void* ptrbuf;
> ```

ditto
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1926 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtXTlyDUu2ZhpiCjtt:-NAtXTlyDUu2ZhpiCjtu:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b019df18cba624006578d6f14c7f8a7da3592b2b/pal/src/host/linux-sgx/enclave_ocalls.c#L1926)):*
> ```C
> 
>     ocall_debug_describe_location_t* ms;
>     char* ptrbuf;
> ```

ditto
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 2020 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtXcyA8Z9UZQ6GizC-:-NAtXcyA8Z9UZQ6GizC0:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b019df18cba624006578d6f14c7f8a7da3592b2b/pal/src/host/linux-sgx/enclave_ocalls.c#L2020)):*
> ```C
> 
>     if (retval >= 0) {
>         ocall_get_quote_t quota_copied;
> ```





_Suggestion:_
```C
quote_copied;
```
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtYWFl4OX2jmpthPhT:-NAtYWFl4OX2jmpthPhU:bomh2no) ([raw file](https://github.com/gramineproject/gramine/blob/b019df18cba624006578d6f14c7f8a7da3592b2b/pal/src/host/linux-sgx/pal_ecall_types.h#L31)):*
> ```objc
>     struct pal_topo_info* topo_info;
> 
>     struct rpc_queue*  rpc_queue; /* pointer to RPC queue in untrusted mem */
> ```

Please either align or one space

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtSx6q0mR-Pon2-6r-:-NDWnpEJ8t2U28ZpRT4K:b-ycqyjc) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is a very bad timing for this PR, it will conflict with changes I'm making (they are not yet public, but are high priority and will be merged before next release). Please consult with others next time before you submit a huge rename
</blockquote></details>

@oshogbo Could you revive this PR and rebase to the latest master? Now should be a good time to merge this PR.

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: 1 of 6 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`pal/src/host/linux-sgx/enclave_ecalls.c` line 72 at r2](https://reviewable.io/reviews/gramineproject/gramine/870#-NEphiz_4zLzBC1o6qqs:-NEq9EfO5sAFfPE_zZuj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/020027680df580fbf593746d7b7c7c55a66e2296/pal/src/host/linux-sgx/enclave_ecalls.c#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Better name please. Maybe `start_args`?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 2020 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtXcyA8Z9UZQ6GizC-:-NEq9PqgAJ-TG9olaN27:b-eyvin8) ([raw file](https://github.com/gramineproject/gramine/blob/b019df18cba624006578d6f14c7f8a7da3592b2b/pal/src/host/linux-sgx/enclave_ocalls.c#L2020)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Really done.
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1345 at r2](https://reviewable.io/reviews/gramineproject/gramine/870#-NEpsGrD3o3ibvMQSTwb:-NEq8v3o0eH4H396_vz_:batvlf0) ([raw file](https://github.com/gramineproject/gramine/blob/020027680df580fbf593746d7b7c7c55a66e2296/pal/src/host/linux-sgx/enclave_ocalls.c#L1345)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Doesn't this fit in one line?
</blockquote></details>

This fit but I wanted these two conditions to look the same as the next one doesn't fit.
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1354 at r2](https://reviewable.io/reviews/gramineproject/gramine/870#-NEpsWhT8N8YOpVGLMKJ:-NEq8ZHe5ly5n2gMD7fi:b-u3b9nq) ([raw file](https://github.com/gramineproject/gramine/blob/020027680df580fbf593746d7b7c7c55a66e2296/pal/src/host/linux-sgx/enclave_ocalls.c#L1354)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

It is 1 character too long.



_Code quote:_
```C
            size_t untrusted_local_addrlen;
            untrusted_local_addrlen = COPY_UNTRUSTED_VALUE(&ocall_accept_args->local_addrlen);
```
___
*[`pal/src/host/linux-sgx/host_ecalls.c` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/870#-NEpwa_b1odOjZ0hsIht:-NEq9TMhEsdLTUv1rI9q:bm54er) ([raw file](https://github.com/gramineproject/gramine/blob/020027680df580fbf593746d7b7c7c55a66e2296/pal/src/host/linux-sgx/host_ecalls.c#L26)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think this is UB (or at least unspecified), please move this `strlen` out of initialization (it was already here, but noticed just now).
</blockquote></details>

Can't it just be `strlen(libpal_uri)` ?
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/870#-NEpxdMZ-UcM4QYetr3B:-NEq9nqlDCA2x9PH0WyO:b-foy5tv) ([raw file](https://github.com/gramineproject/gramine/blob/020027680df580fbf593746d7b7c7c55a66e2296/pal/src/host/linux-sgx/host_ocalls.c#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What this `p` stands for? Why not just `args`?
</blockquote></details>

From pointer, but yea `args` makes more sense.
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/870#-NAtYWFl4OX2jmpthPhT:-NEq9zQj3oT46Qri1r5Z:b-zabb3d) ([raw file](https://github.com/gramineproject/gramine/blob/b019df18cba624006578d6f14c7f8a7da3592b2b/pal/src/host/linux-sgx/pal_ecall_types.h#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Oh, you meant `rpc_queue` ok.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1345 at r2](https://reviewable.io/reviews/gramineproject/gramine/870#-NEpsGrD3o3ibvMQSTwb:-NEqQyyG6CTbIKpxRxAA:bib75em) ([raw file](https://github.com/gramineproject/gramine/blob/020027680df580fbf593746d7b7c7c55a66e2296/pal/src/host/linux-sgx/enclave_ocalls.c#L1345)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This fit but I wanted these two conditions to look the same as the next one doesn't fit.
</blockquote></details>

I don't find that convincing, but not insisting.
___
*[`pal/src/host/linux-sgx/host_ecalls.c` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/870#-NEpwa_b1odOjZ0hsIht:-NEqREvK7WQAObaTWXr1:b-d8e4rr) ([raw file](https://github.com/gramineproject/gramine/blob/020027680df580fbf593746d7b7c7c55a66e2296/pal/src/host/linux-sgx/host_ecalls.c#L26)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Can't it just be `strlen(libpal_uri)` ?
</blockquote></details>

Works as well
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/870#-NEpxdMZ-UcM4QYetr3B:-NEqRJflCJjYYGuQwTTe:b-s7jtkb) ([raw file](https://github.com/gramineproject/gramine/blob/020027680df580fbf593746d7b7c7c55a66e2296/pal/src/host/linux-sgx/host_ocalls.c#L35)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

From pointer, but yea `args` makes more sense.
</blockquote></details>

But please apply to the whole file

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/870#-NEpxdMZ-UcM4QYetr3B:-NEtyDKV00Ag8HobN0DL:bsb2ni4) ([raw file](https://github.com/gramineproject/gramine/blob/020027680df580fbf593746d7b7c7c55a66e2296/pal/src/host/linux-sgx/host_ocalls.c#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But please apply to the whole file
</blockquote></details>

Duh...

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 717 at r4](https://reviewable.io/reviews/gramineproject/gramine/870#-NEuH1nZDMXpjXnRGnqO:-NEuH1nZDMXpjXnRGnqP:b-pzseub) ([raw file](https://github.com/gramineproject/gramine/blob/8ea7e9ed36fc0817c56efbf40d2c55a45cd8c0e9/pal/src/host/linux-sgx/host_ocalls.c#L717)):*
> ```C
> 
> static long sgx_ocall_debug_describe_location(void* args) {
>     struct ocall_debug_describe_location* debug_args = (struct ocall_debug_describe_location*)args;
> ```

`debug_args` -> `ocall_debug_args` (or even `ocall_debug_describe_args`)
___
*[`pal/src/host/linux-sgx/pal_ocall_types.h` line 193 at r4](https://reviewable.io/reviews/gramineproject/gramine/870#-NEuHNqJCdGwEEiiCQJD:-NEuHNqJCdGwEEiiCQJE:b-ydsysr) ([raw file](https://github.com/gramineproject/gramine/blob/8ea7e9ed36fc0817c56efbf40d2c55a45cd8c0e9/pal/src/host/linux-sgx/pal_ocall_types.h#L193)):*
> ```objc
>     size_t cpumask_size;
>     void* cpu_mask;
> };
> ```

Unrelated to this PR, but why do we have two structs that have the exact same layout? I think we should just combine into one.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 717 at r4](https://reviewable.io/reviews/gramineproject/gramine/870#-NEuH1nZDMXpjXnRGnqO:-NEuMPMoBG_A1ebGWKde:b6ufwhn) ([raw file](https://github.com/gramineproject/gramine/blob/8ea7e9ed36fc0817c56efbf40d2c55a45cd8c0e9/pal/src/host/linux-sgx/host_ocalls.c#L717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`debug_args` -> `ocall_debug_args` (or even `ocall_debug_describe_args`)
</blockquote></details>

Do we want such long name?
___
*[`pal/src/host/linux-sgx/pal_ocall_types.h` line 193 at r4](https://reviewable.io/reviews/gramineproject/gramine/870#-NEuHNqJCdGwEEiiCQJD:-NEuMTFf50E76n9-iRsH:b-gs32tw) ([raw file](https://github.com/gramineproject/gramine/blob/8ea7e9ed36fc0817c56efbf40d2c55a45cd8c0e9/pal/src/host/linux-sgx/pal_ocall_types.h#L193)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Unrelated to this PR, but why do we have two structs that have the exact same layout? I think we should just combine into one.
</blockquote></details>

I guess each ocall has it own structure, but I'm not sure about that.
@mkow ?

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_ocall_types.h` line 193 at r4](https://reviewable.io/reviews/gramineproject/gramine/870#-NEuHNqJCdGwEEiiCQJD:-NEuRD5t2XSXLaa4GzZB:b-chnszr) ([raw file](https://github.com/gramineproject/gramine/blob/8ea7e9ed36fc0817c56efbf40d2c55a45cd8c0e9/pal/src/host/linux-sgx/pal_ocall_types.h#L193)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I guess each ocall has it own structure, but I'm not sure about that.
@mkow ?
</blockquote></details>

Let's not do that in this PR.
Generally idk much about this, I guess `getaffinity` could be allocating the urts memory itself (but currently it does not)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 717 at r4](https://reviewable.io/reviews/gramineproject/gramine/870#-NEuH1nZDMXpjXnRGnqO:-NEuRgRrCa15zSsANJaf:b7luqqw) ([raw file](https://github.com/gramineproject/gramine/blob/8ea7e9ed36fc0817c56efbf40d2c55a45cd8c0e9/pal/src/host/linux-sgx/host_ocalls.c#L717)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Do we want such long name?
</blockquote></details>

Yes, we must add the `ocall_` prefix, for uniformity with everything else in this file. This is the only occurence of a args object *without* `ocall_` prefix.

But yes, for shortness let's just call it `ocall_debug_args`.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_ocall_types.h` line 193 at r4](https://reviewable.io/reviews/gramineproject/gramine/870#-NEuHNqJCdGwEEiiCQJD:-NEuRuGbB_XKdAqmH_k3:bvr967z) ([raw file](https://github.com/gramineproject/gramine/blob/8ea7e9ed36fc0817c56efbf40d2c55a45cd8c0e9/pal/src/host/linux-sgx/pal_ocall_types.h#L193)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Let's not do that in this PR.
Generally idk much about this, I guess `getaffinity` could be allocating the urts memory itself (but currently it does not)
</blockquote></details>

Definitely not doing it in this PR, just noticed this and got curious.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/870#-NEuwG7e5kfBvyVy87dQ):*
Double fixup.
But it shouldn't be an issue.
Sorry for that.
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 717 at r4](https://reviewable.io/reviews/gramineproject/gramine/870#-NEuH1nZDMXpjXnRGnqO:-NEuwKtQBRrJIW8jG-Q9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8ea7e9ed36fc0817c56efbf40d2c55a45cd8c0e9/pal/src/host/linux-sgx/host_ocalls.c#L717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, we must add the `ocall_` prefix, for uniformity with everything else in this file. This is the only occurence of a args object *without* `ocall_` prefix.

But yes, for shortness let's just call it `ocall_debug_args`.
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 719 at r6](https://reviewable.io/reviews/gramineproject/gramine/870#-NEv74LI7cHCtH5faOdT:-NEv74LJESf27dutZHuq:b-hfgopm) ([raw file](https://github.com/gramineproject/gramine/blob/99ed20cf17ebc8eb390fd8b86b32acfc8fa22613/pal/src/host/linux-sgx/host_ocalls.c#L719)):*
> ```C
>     struct ocall_debug_describe_location* ocall_debug_args;
> 
>     ocall_debug_args = args;
> ```

This should be one line with above.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 719 at r6](https://reviewable.io/reviews/gramineproject/gramine/870#-NEv74LI7cHCtH5faOdT:-NEv9mRW0Mw6KiAwS0rx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/99ed20cf17ebc8eb390fd8b86b32acfc8fa22613/pal/src/host/linux-sgx/host_ocalls.c#L719)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This should be one line with above.
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: all files reviewed, 1 unresolved discussion

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/870)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
