### PR TITLE
Use `gramine-test` for building LTP manifests 

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

This removes the last part that used the old Makefile scripts.

## How to test this PR? 

Try to build LTP and LTP manifests locally.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/243)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/243)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/243#-MpLTIkK4PbSjEzy0Lzf:-MpLTIkL70UACFXrnjVF:b-3ufgbl) (no related file):*
This PR makes me very happy!

---
___
*[LibOS/shim/test/ltp/manifest.template, line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/243#-MpLST7O9Np25pKyUd9t:-MpLST7O9Np25pKyUd9u:bza9lul) ([raw file](https://github.com/gramineproject/gramine/blob/4367a803744c03a45edfa936a542e43233a5ec11/LibOS/shim/test/ltp/manifest.template#L11)):*
> ```
> 
> fs.root.type = "chroot"
> fs.root.uri = "file:{{ binary_dir }}"
> ```

Smart!
___
*[python/graminelibos/util_tests.py, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/243#-MpLTBrs-9BRJ1ELDW5r:-MpLTBrs-9BRJ1ELDW5s:b-v1ublr) ([raw file](https://github.com/gramineproject/gramine/blob/4367a803744c03a45edfa936a542e43233a5ec11/python/graminelibos/util_tests.py#L28)):*
> ```Python
> 
>     - `binary_dir`: path to test binaries, passed as `binary_dir` to manifest templates; expands
>       @GRAMINE_PKGLIBDIR@ to library directory of Gramine's installation
> ```

Please add the new `manifests_cmd` key

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/243)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[python/graminelibos/util_tests.py, line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/243#-MpLaCCZ9KF-tLHVS-af:-MpLaCCZ9KF-tLHVS-ag:b-3ws64l) ([raw file](https://github.com/gramineproject/gramine/blob/4367a803744c03a45edfa936a542e43233a5ec11/python/graminelibos/util_tests.py#L54)):*
> ```Python
>         self.arch_libdir = _CONFIG_SYSLIBDIR
> 
>         # Used by LTP, for `libstdbuf.so`
> ```

I have mixed feelings. On one hand this is LTP specific, so we shouldn't be putting it in here; worst case we could generate it in ltp manifest template. On the other this is quite generic and probably every system has it...

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/243)* status: 18 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[python/graminelibos/util_tests.py, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/243#-MpLTBrs-9BRJ1ELDW5r:-MpM21T36lvidW6tfZAc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4367a803744c03a45edfa936a542e43233a5ec11/python/graminelibos/util_tests.py#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add the new `manifests_cmd` key
</blockquote></details>

Done.
___
*[python/graminelibos/util_tests.py, line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/243#-MpLaCCZ9KF-tLHVS-af:-MpM2B9w1iNrqkErUjt1:b-vee6uy) ([raw file](https://github.com/gramineproject/gramine/blob/4367a803744c03a45edfa936a542e43233a5ec11/python/graminelibos/util_tests.py#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I have mixed feelings. On one hand this is LTP specific, so we shouldn't be putting it in here; worst case we could generate it in ltp manifest template. On the other this is quite generic and probably every system has it...
</blockquote></details>

I don't like the idea of having logic like this in the template, both on principle, and because it will get executed 300+ times.

Unfortunately I can't think of a better place. We could implement another hook for such things in `tests.toml`, but that doesn't sound too good, either.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/243)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/243)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/243)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/243)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
