### PR TITLE
[common] Fix value of strtol/strtoll endptr if nothing was converted

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

Fix value of strtol/strtoll endptr if nothing was converted

Resolves: https://github.com/gramineproject/gramine/issues/907

## How to test this PR? 

Run PAL regression test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)

### CODE REVIEW

**Review by oshogbo — COMMENTED** [review]
Thank you for looking into this.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945#-:-ND8Ul_l5YFelpn9HuZI:b-290w0w)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[`common/src/string/atoi.c` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/945#-ND8TuyH3nHOjtNe9jYj:-ND8TuyH3nHOjtNe9jYk:b13jrb8) ([raw file](https://github.com/gramineproject/gramine/blob/1fa8d4ad294486522aa30312f6df03f866b1306c/common/src/string/atoi.c#L63)):*
> ```C
> 
> long strtol(const char* str, char** out_end, int base) {
>     int nothing = 1;
> ```

`bool`?
___
*[`pal/regression/test_pal.py` line 447 at r1](https://reviewable.io/reviews/gramineproject/gramine/945#-ND8Tntm2FTVe5-hO9JK:-ND8Tntm2FTVe5-hO9JL:b84beln) ([raw file](https://github.com/gramineproject/gramine/blob/1fa8d4ad294486522aa30312f6df03f866b1306c/pal/regression/test_pal.py#L447)):*
> ```Python
>         self.assertIn('Generate Random Bits OK', stderr)
> 
>         # Results of strtoull conversions
> ```

Why `strtoull`?

**Review by stefanberger — COMMENTED** [review]
Glad I could help.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945#-:-ND8ipDiCuTKCQ3zYuCu:blulfdw)* status: 0 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`common/src/string/atoi.c` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/945#-ND8TuyH3nHOjtNe9jYj:-ND8ivq-78vF1xC3eXVV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fa8d4ad294486522aa30312f6df03f866b1306c/common/src/string/atoi.c#L63)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

`bool`?
</blockquote></details>

Done.
___
*[`pal/regression/test_pal.py` line 447 at r1](https://reviewable.io/reviews/gramineproject/gramine/945#-ND8Tntm2FTVe5-hO9JK:-ND8iw_G4idTEhy8LFEj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fa8d4ad294486522aa30312f6df03f866b1306c/pal/regression/test_pal.py#L447)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Why `strtoull`?
</blockquote></details>

Done.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: 0 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @oshogbo)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/945#-ND90OT48hfgbF8h1Y7v):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Something is wrong with this PR, this commit shouldn't be here.
</blockquote></details>

Odd. Rebasing helped.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo and @stefanberger)

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND93skuBtteCFsGIXsi):*
We don't put that kind of info in the commit message (but we do in Github PR description), we rather explain what's exactly is fixed and why.
___
*[`common/src/string/atoi.c` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND9649i3ov1z_kCEB0t:-ND9649i3ov1z_kCEB0u:b-32220w) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/common/src/string/atoi.c#L64)):*
> ```C
> 
> long strtol(const char* str, char** out_end, int base) {
>     bool nothing = true;
> ```

That's very... broad word. Maybe `nothing_parsed`?
___
*[`common/src/string/atoi.c` line 74 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND953oBDCGnnevTNTHR:-ND953oBDCGnnevTNTHS:bothjkt) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/common/src/string/atoi.c#L74)):*
> ```C
>         int digit = parse_digit(*s, base);
>         if (digit == -1) {
>             if (nothing) {
> ```

Hmm, wouldn't it be more readable if you just changed `*out_end = (char*)(nothing ? str : s)` at the end?
This looks weird to me here. Also I don't think it works correctly if `str == "        "`
___
*[`pal/regression/Misc.c` line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND97xsr2EvC06VnACNp:-ND97xsr2EvC06VnACNq:b8p2u2t) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/pal/regression/Misc.c#L98)):*
> ```C
>         pal_printf("Generate Random Bits OK\n");
> 
>     const char* ptr = "123 asd";
> ```

Please create another file for this test, `Misc.c` is rather for miscellaneous PAL API functions.
___
*[`pal/regression/Misc.c` line 101 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND97hzX8_yszuXM2xfc:-ND97hzY5OGUWHnKeSEd:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/pal/regression/Misc.c#L101)):*
> ```C
>     const char* next = ptr;
> 
>     for (int i = 0; i < 2; i++) {
> ```





_Suggestion:_
```C
size_t
```
___
*[`pal/regression/Misc.c` line 103 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND98FTQ3q0D1UJ3UnFa:-ND98FTQ3q0D1UJ3UnFb:b9mnfxw) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/pal/regression/Misc.c#L103)):*
> ```C
>     for (int i = 0; i < 2; i++) {
>        long long a = strtoll(ptr, (char**)&next, 10);
>        pal_printf("%lld %x(%c) %x(%c)\n", a, *ptr, *ptr, *next, *next);
> ```

Actually, in new code (this test is rather old) we check the expected values in the C code itself rather python running the test (unless it's super hard to do). You can check `printf_test.c` for a example similar to this
___
*[`pal/regression/Misc.c` line 103 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND98sLV0TK2ahJC27w4:-ND98sLV0TK2ahJC27w5:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/pal/regression/Misc.c#L103)):*
> ```C
>     for (int i = 0; i < 2; i++) {
>        long long a = strtoll(ptr, (char**)&next, 10);
>        pal_printf("%lld %x(%c) %x(%c)\n", a, *ptr, *ptr, *next, *next);
> ```





_Suggestion:_
```C
"%d %lld %#x(%c) %#x(%c)\n", i, a,
```

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: 2 of 8 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @oshogbo, and @stefanberger)

___
*[`common/src/string/atoi.c` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND9649i3ov1z_kCEB0t:-ND9Jfmt2Qq9jW8Th6Wk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/common/src/string/atoi.c#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That's very... broad word. Maybe `nothing_parsed`?
</blockquote></details>

Done.
___
*[`pal/regression/Misc.c` line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND97xsr2EvC06VnACNp:-ND9JkdV6nsnhM8m6x5w:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/pal/regression/Misc.c#L98)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please create another file for this test, `Misc.c` is rather for miscellaneous PAL API functions.
</blockquote></details>

Done.
___
*[`pal/regression/Misc.c` line 101 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND97hzX8_yszuXM2xfc:-ND9Jk-m034vbtLvksIM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/pal/regression/Misc.c#L101)):*
> ```C
>     const char* next = ptr;
> 
>     for (int i = 0; i < 2; i++) {
> ```

Done.
___
*[`pal/regression/Misc.c` line 103 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND98FTQ3q0D1UJ3UnFa:-ND9JlUk9c3GtxWEabqN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/pal/regression/Misc.c#L103)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, in new code (this test is rather old) we check the expected values in the C code itself rather python running the test (unless it's super hard to do). You can check `printf_test.c` for a example similar to this
</blockquote></details>

Done.
___
*[`pal/regression/Misc.c` line 103 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND98sLV0TK2ahJC27w4:-ND9JmLF-sD9H0Hn16aH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/pal/regression/Misc.c#L103)):*
> ```C
>     for (int i = 0; i < 2; i++) {
>        long long a = strtoll(ptr, (char**)&next, 10);
>        pal_printf("%lld %x(%c) %x(%c)\n", a, *ptr, *ptr, *next, *next);
> ```

Done.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: 2 of 8 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @oshogbo)

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND93skuBtteCFsGIXsi):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We don't put that kind of info in the commit message (but we do in Github PR description), we rather explain what's exactly is fixed and why.
</blockquote></details>

This way you can auto-close issues by merging the code. I thought you guys did it like this before.
___
*[`common/src/string/atoi.c` line 74 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND953oBDCGnnevTNTHR:-ND9M4AyDJ2MTzkcg-Vc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9ac5499fe6bf4a0871daddcfa570e9703f97c6/common/src/string/atoi.c#L74)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, wouldn't it be more readable if you just changed `*out_end = (char*)(nothing ? str : s)` at the end?
This looks weird to me here. Also I don't think it works correctly if `str == "        "`
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: 7 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo and @stefanberger)

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/gramineproject/gramine/945#-ND93skuBtteCFsGIXsi):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

This way you can auto-close issues by merging the code. I thought you guys did it like this before.
</blockquote></details>

We put that in the Github PR description, not in the commit message.
___
*[`pal/regression/libc_test.c` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/945#-ND9HYQo2pZVGH20NLXA:-ND9HYQo2pZVGH20NLXB:bm26i3m) ([raw file](https://github.com/gramineproject/gramine/blob/b0384e7b871d99e7b3f12916a49c43d0499fb3f4/pal/regression/libc_test.c#L1)):*
> ```C
> #include "api.h"
> ```

`libc_test`? More like `strtoll_test`
___
*[`pal/regression/libc_test.c` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/945#-ND9mL0EDYudjANFuC3r:-ND9mL0EDYudjANFuC3s:bwgyhnv) ([raw file](https://github.com/gramineproject/gramine/blob/8f3584b2f944e399dc4c11507b7cde4164c499a0/pal/regression/libc_test.c#L28)):*
> ```C
> 
>     long long a = strtoll(ptr, (char**)&next, 10);
>     TEST("123 31(1) 20( )", "%lld %x(%c) %x(%c)", a, *ptr, *ptr, *next, *next);
> ```

Uhm, what's the point of this? When suggesting to peek at `printf_test.c` I didn't mean to literally take what's there...
Here you can just compare values to expected, no need for these string manipulations (including snprintf).
Like `if (a != 123 || *next != ' ')` or even better `if (a != 123 || next != ptr + 3)`

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: 7 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @oshogbo, and @stefanberger)

___
*[`pal/regression/libc_test.c` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/945#-ND9HYQo2pZVGH20NLXA:-ND9o6vb81LE0rk6V7_E:bhjt0wa) ([raw file](https://github.com/gramineproject/gramine/blob/b0384e7b871d99e7b3f12916a49c43d0499fb3f4/pal/regression/libc_test.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`libc_test`? More like `strtoll_test`
</blockquote></details>

It could be the first test case for libc.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: 7 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo and @stefanberger)

___
*[`pal/regression/libc_test.c` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/945#-ND9HYQo2pZVGH20NLXA:-ND9okUPEhvGedJs807d:b-x0k7vg) ([raw file](https://github.com/gramineproject/gramine/blob/b0384e7b871d99e7b3f12916a49c43d0499fb3f4/pal/regression/libc_test.c#L1)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

It could be the first test case for libc.
</blockquote></details>

We already have other files testing functions from standard library (well our implementations of them)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @stefanberger)

___
*[`pal/regression/strtoll_test.c` line 15 at r8](https://reviewable.io/reviews/gramineproject/gramine/945#-NDi-i6i8Bn9U5zv0i1K:-NDi-i6j4UkE0ST-w3l7:b-ec73r9) ([raw file](https://github.com/gramineproject/gramine/blob/a1604f6183c1c3a288622819aa5d5f4560101fbf/pal/regression/strtoll_test.c#L15)):*
> ```C
> 
>     long long a = strtoll(ptr, (char**)&next, 10);
>     if (a != 123 || *ptr != '1' || next != ptr + 3) {
> ```

What's the point of comparing `*ptr != '1'` and printing it's content below? It's constant
___
*[`pal/regression/strtoll_test.c` line 23 at r8](https://reviewable.io/reviews/gramineproject/gramine/945#-NDi0GNM6lY5Fw8VSpe0:-NDi0GNM6lY5Fw8VSpe1:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a1604f6183c1c3a288622819aa5d5f4560101fbf/pal/regression/strtoll_test.c#L23)):*
> ```C
>     /* nothing to convert */
>     a = strtoll(ptr, (char**)&next, 10);
>     if (a != 0 || *ptr != ' ' || next != ptr) {
> ```

ditto
___
*[`pal/regression/strtoll_test.c` line 31 at r8](https://reviewable.io/reviews/gramineproject/gramine/945#-NDi0Slf3zyy0pGX9WcL:-NDi0Slg64s7tqLTju2R:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a1604f6183c1c3a288622819aa5d5f4560101fbf/pal/regression/strtoll_test.c#L31)):*
> ```C
>     next = ptr;
>     a = strtoll(ptr, (char**)&next, 10);
>     if (a != 0 || *ptr != ' ' || next != ptr) {
> ```

ditto

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`pal/regression/strtoll_test.c` line 15 at r8](https://reviewable.io/reviews/gramineproject/gramine/945#-NDi-i6i8Bn9U5zv0i1K:-NDi7kFt60a2a2EXVB-q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a1604f6183c1c3a288622819aa5d5f4560101fbf/pal/regression/strtoll_test.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of comparing `*ptr != '1'` and printing it's content below? It's constant
</blockquote></details>

Done.
___
*[`pal/regression/strtoll_test.c` line 23 at r8](https://reviewable.io/reviews/gramineproject/gramine/945#-NDi0GNM6lY5Fw8VSpe0:-NDi7kXl58NZJlplETPm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a1604f6183c1c3a288622819aa5d5f4560101fbf/pal/regression/strtoll_test.c#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/regression/strtoll_test.c` line 31 at r8](https://reviewable.io/reviews/gramineproject/gramine/945#-NDi0Slf3zyy0pGX9WcL:-NDi7lnN5b5mzIsMQ-Yn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a1604f6183c1c3a288622819aa5d5f4560101fbf/pal/regression/strtoll_test.c#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @oshogbo, and @stefanberger)

___
*[`pal/regression/strtoll_test.c` line 15 at r8](https://reviewable.io/reviews/gramineproject/gramine/945#-NDi-i6i8Bn9U5zv0i1K:-NDjEhRZ4GrBC1U6FSVe:bwsdpmk) ([raw file](https://github.com/gramineproject/gramine/blob/a1604f6183c1c3a288622819aa5d5f4560101fbf/pal/regression/strtoll_test.c#L15)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You still print it

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, 3 of 5 files at r7, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @stefanberger)

___
*[`-- commits` line 5 at r10](https://reviewable.io/reviews/gramineproject/gramine/945#-NDl92UdALnds8hsK2RM):*
`points` -> `must point`

I'll fix it during final rebase
___
*[`pal/regression/strtoll_test.c` line 8 at r10](https://reviewable.io/reviews/gramineproject/gramine/945#-NDl9l252FmKWZi94hVl:-NDl9l252FmKWZi94hVm:bikqefj) ([raw file](https://github.com/gramineproject/gramine/blob/2a0d0e32b1abf29421e5c6e664b63777011bbaf9/pal/regression/strtoll_test.c#L8)):*
> ```C
>     pal_printf("\n");   \
>     PalProcessExit(1);  \
> })
> ```

This deserves to be put into `pal_regression.h`. Please move there.
___
*[`pal/regression/test_pal.py` line 32 at r10](https://reviewable.io/reviews/gramineproject/gramine/945#-NDl9LIi0NBiIdv6MMs9:-NDl9LIj6ISi_jIBi1tu:b-jeze2z) ([raw file](https://github.com/gramineproject/gramine/blob/2a0d0e32b1abf29421e5c6e664b63777011bbaf9/pal/regression/test_pal.py#L32)):*
> ```Python
>         self.assertIn("TEST OK", stderr)
> 
>     def test_003_strtoll(self):
> ```

`003` -> `004`

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: 7 of 11 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`-- commits` line 5 at r10](https://reviewable.io/reviews/gramineproject/gramine/945#-NDl92UdALnds8hsK2RM):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`points` -> `must point`

I'll fix it during final rebase
</blockquote></details>

Done.
___
*[`pal/regression/strtoll_test.c` line 8 at r10](https://reviewable.io/reviews/gramineproject/gramine/945#-NDl9l252FmKWZi94hVl:-NDm1bkhDk7gI_qV9NcL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2a0d0e32b1abf29421e5c6e664b63777011bbaf9/pal/regression/strtoll_test.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This deserves to be put into `pal_regression.h`. Please move there.
</blockquote></details>

Done.
___
*[`pal/regression/test_pal.py` line 32 at r10](https://reviewable.io/reviews/gramineproject/gramine/945#-NDl9LIi0NBiIdv6MMs9:-NDm1eoC8FBaF4qEqG8d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2a0d0e32b1abf29421e5c6e664b63777011bbaf9/pal/regression/test_pal.py#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`003` -> `004`
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, 1 of 6 files at r5, 1 of 2 files at r6, 3 of 5 files at r7, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

___
*[`-- commits` line 5 at r10](https://reviewable.io/reviews/gramineproject/gramine/945#-NDl92UdALnds8hsK2RM):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, 2 unresolved discussions (waiting on @oshogbo)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/945)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
