### PR TITLE
[LibOS] Print Gramine commit hash on startup

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
You know why we need it...

## How to test this PR? 
Just build Gramine and run it with log_level = "debug"

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_init.c, line 387 at r1](https://reviewable.io/reviews/gramineproject/gramine/229#-Mogpi346Yr_rLHewLZe:-Mogpi346Yr_rLHewLZf:b16qpgd) ([raw file](https://github.com/gramineproject/gramine/blob/48cfa3a8103625a1eb230952f85a80f0ab9aea2a/LibOS/shim/src/shim_init.c#L387)):*
> ```C
> 
>     extern const char g_gramine_commit_hash[];
>     log_debug("Gramine was build from commit: %s", g_gramine_commit_hash);
> ```

`built`

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/meson.build, line 133 at r1](https://reviewable.io/reviews/gramineproject/gramine/229#-MohwBG81GN09dAHEyFp:-MohwBG81GN09dAHEyFq:b-citqhd) ([raw file](https://github.com/gramineproject/gramine/blob/48cfa3a8103625a1eb230952f85a80f0ab9aea2a/LibOS/shim/src/meson.build#L133)):*
> ```Meson
>     command: ['git', 'rev-parse', '--verify', 'HEAD' ],
>     fallback: 'OOT',
>     input: 'gramine_hash_template.c',
> ```

We have `gsgx.h.in`, maybe this should be called `gramine_hash.c.in`?
___
*[LibOS/shim/src/meson.build, line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/229#-MohvkrAD5vFrntW5_Z9:-MohvkrC1ea9Lshk4lZg:b-7s2636) ([raw file](https://github.com/gramineproject/gramine/blob/48cfa3a8103625a1eb230952f85a80f0ab9aea2a/LibOS/shim/src/meson.build#L135)):*
> ```Meson
>     input: 'gramine_hash_template.c',
>     output: 'gramine_hash.c',
>     replace_string: 'GRAMINE_COMMIT_HASH',
> ```

`@GRAMINE_COMMIT_HASH@`? That's the convention recommended by Meson (the default here is `@VCS_TAG@`), and we already follow it for other template variables (see `gsgx.h.in` and `python/graminelibos/__init__.py`).

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: 0 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/meson.build, line 133 at r1](https://reviewable.io/reviews/gramineproject/gramine/229#-MohwBG81GN09dAHEyFp:-MoiJwM08LS4TaBFqi5w:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48cfa3a8103625a1eb230952f85a80f0ab9aea2a/LibOS/shim/src/meson.build#L133)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We have `gsgx.h.in`, maybe this should be called `gramine_hash.c.in`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/meson.build, line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/229#-MohvkrAD5vFrntW5_Z9:-MoiJxOnEhWMW5ovLCYF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48cfa3a8103625a1eb230952f85a80f0ab9aea2a/LibOS/shim/src/meson.build#L135)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`@GRAMINE_COMMIT_HASH@`? That's the convention recommended by Meson (the default here is `@VCS_TAG@`), and we already follow it for other template variables (see `gsgx.h.in` and `python/graminelibos/__init__.py`).
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 387 at r1](https://reviewable.io/reviews/gramineproject/gramine/229#-Mogpi346Yr_rLHewLZe:-MoiJy1r05HLPXfQ0hiI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48cfa3a8103625a1eb230952f85a80f0ab9aea2a/LibOS/shim/src/shim_init.c#L387)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`built`
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

**Review by pwmarcz — APPROVED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/meson.build, line 132 at r2](https://reviewable.io/reviews/gramineproject/gramine/229#-MoieTrL8uCGuet_3j-d:-MoieTrL8uCGuet_3j-e:b-oavxya) ([raw file](https://github.com/gramineproject/gramine/blob/dd389a9d5e64dda8921c1aedcd9039cbe99d4021/LibOS/shim/src/meson.build#L132)):*
> ```Meson
> gramine_hash_src = vcs_tag(
>     command: ['git', 'rev-parse', '--verify', 'HEAD' ],
>     fallback: 'OOT',
> ```

`fallback` should be left as default, or `meson.project_version()`. This is needed for packaging, because packages are built from tarballs.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[LibOS/shim/src/meson.build, line 132 at r2](https://reviewable.io/reviews/gramineproject/gramine/229#-MoieTrL8uCGuet_3j-d:-Moii5SN6f4wjNpArcBe:b-5yhwq2) ([raw file](https://github.com/gramineproject/gramine/blob/dd389a9d5e64dda8921c1aedcd9039cbe99d4021/LibOS/shim/src/meson.build#L132)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`fallback` should be left as default, or `meson.project_version()`. This is needed for packaging, because packages are built from tarballs.
</blockquote></details>

We don't really care about these - this is for cases when people build Gramine from sources.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @pwmarcz, and @woju)

___
*[LibOS/shim/src/meson.build, line 132 at r2](https://reviewable.io/reviews/gramineproject/gramine/229#-MoieTrL8uCGuet_3j-d:-Moiiff07w6geSG6qegj:b5yd9gw) ([raw file](https://github.com/gramineproject/gramine/blob/dd389a9d5e64dda8921c1aedcd9039cbe99d4021/LibOS/shim/src/meson.build#L132)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We don't really care about these - this is for cases when people build Gramine from sources.
</blockquote></details>

But since the version is clearly distinguishable from hash, done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/meson.build, line 132 at r2](https://reviewable.io/reviews/gramineproject/gramine/229#-MoieTrL8uCGuet_3j-d:-MoixECP1aB24T_Q_v2E:b-mhme6p) ([raw file](https://github.com/gramineproject/gramine/blob/dd389a9d5e64dda8921c1aedcd9039cbe99d4021/LibOS/shim/src/meson.build#L132)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But since the version is clearly distinguishable from hash, done.
</blockquote></details>

We can have the version "unreleased" in all commits but the release.

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/229)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
