### PR TITLE
[Pal/Linux] Change Linux PAL to use flexible IOCTLs

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Final part of the series of PRs.

- First PR is https://github.com/gramineproject/gramine/pull/1386
- Second PR is https://github.com/gramineproject/gramine/pull/1387

## How to test this PR? 

CI is enough. It was modified in this PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1388#-NXnVHrNApssBawXD33z):*
PAL



_Code quote:_
```
Pal
```
___
*[`pal/src/host/linux/pal_devices.c` line 262 at r1](https://reviewable.io/reviews/gramineproject/gramine/1388#-NXnYN3l6lLWMEVWKqYD:-NXnYN3l6lLWMEVWKqYE:bywt0tv) ([raw file](https://github.com/gramineproject/gramine/blob/9c158f30e2c633964b239bc7a45944f447fb1399/pal/src/host/linux/pal_devices.c#L262)):*
> ```C
>     }
> 
>     /* deep-copy the IOCTL argument's input data outside of enclave, execute the IOCTL OCALL, and
> ```

this is inapplicable here



_Code quote:_
```C
enclave
```
___
*[`pal/src/host/linux/pal_devices.c` line 263 at r1](https://reviewable.io/reviews/gramineproject/gramine/1388#-NXnYXub1nkOjdvwEKiW:-NXnYXub1nkOjdvwEKiX:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9c158f30e2c633964b239bc7a45944f447fb1399/pal/src/host/linux/pal_devices.c#L263)):*
> ```C
> 
>     /* deep-copy the IOCTL argument's input data outside of enclave, execute the IOCTL OCALL, and
>      * deep-copy the IOCTL argument's output data back into enclave */
> ```

ditto



_Code quote:_
```C
enclave
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1388#-NXnVHrNApssBawXD33z):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

PAL
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_devices.c` line 262 at r1](https://reviewable.io/reviews/gramineproject/gramine/1388#-NXnYN3l6lLWMEVWKqYD:-NXnmSTs0Q2R5NrgQWet:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9c158f30e2c633964b239bc7a45944f447fb1399/pal/src/host/linux/pal_devices.c#L262)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

this is inapplicable here
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_devices.c` line 263 at r1](https://reviewable.io/reviews/gramineproject/gramine/1388#-NXnYXub1nkOjdvwEKiW:-NXnmSo49yd50ecW2tXq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9c158f30e2c633964b239bc7a45944f447fb1399/pal/src/host/linux/pal_devices.c#L263)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by kailun-qin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux/pal_devices.c` line 221 at r2](https://reviewable.io/reviews/gramineproject/gramine/1388#-NXr45OU0v-ICdHLhI29:-NXr45OU0v-ICdHLhI2A:b-ql5sv8) ([raw file](https://github.com/gramineproject/gramine/blob/15806a69110189bd13d0ac9b922c410a7d87b057/pal/src/host/linux/pal_devices.c#L221)):*
> ```C
> static bool memcpy_to_gramine(void* ptr, size_t max_size, const void* host_ptr, size_t host_size) {
>     __UNUSED(max_size);
>     memcpy(ptr, host_ptr, host_size);
> ```

Please keep the `host_size > max_size` check (from the SGX version; mostly for better bug detection, so an assert is also fine if you prefer).

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/host/linux/pal_devices.c` line 221 at r2](https://reviewable.io/reviews/gramineproject/gramine/1388#-NXr45OU0v-ICdHLhI29:-NXs_rVJE2HatAd0L5ml:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/15806a69110189bd13d0ac9b922c410a7d87b057/pal/src/host/linux/pal_devices.c#L221)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please keep the `host_size > max_size` check (from the SGX version; mostly for better bug detection, so an assert is also fine if you prefer).
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1388)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
