### PR TITLE
[common] Refactor Protected Files slightly

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This PR refactors PF code without changing functionality:
- Many renames of data structs, variable names, func names
- More readable comments (and fixing incorrect comments)
- Removed unused `pf_get_handle()`
- Removed unused `g_pf_mrenclave_key`, `g_pf_wrap_key`, etc.
- Removed all mentions of `list`/`LIST` operations (were unused)

This PR contains changes (renames) in `pf_tamper.c`, but this file and corresponding tool are not tested and most probably broken. We did the changes purely to survive compilation.

## How to test this PR? 

No functional changes, CI is enough.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841)* status: 0 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1841#-NvCJDffBd7Wlpl-L8b0:-NvCJDffBd7Wlpl-L8b1:bw2gsdz) (no related file):*
FYI: I will submit a new ReadTheDocs document with description of Protected/Encrypted Files. The names in that document will correspond to the names created in this PR.

___
___
*[`common/src/protected_files/protected_files_internal.h` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1841#-NvCIcv37wpelKSkzmKV:-NvCIcv47j0jX96cmS_D:b-lt42o1) ([raw file](https://github.com/gramineproject/gramine/blob/ae14b3db790b8a7ea0f0c290ab6436100f11bc02/common/src/protected_files/protected_files_internal.h#L16)):*
> ```objc
> #include "protected_files_format.h"
> 
> struct pf_context {
> ```

For reviewers' convenience, renames:
- `file_metadata` -> `metadata_node`
- `encrypted_part_plain` -> `metadata_decrypted_header`
- `root_mht` -> `root_mht_node`
- `file` -> `host_file_handle`
- `user_kdk_key` -> `kdk`
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 160 at r1](https://reviewable.io/reviews/gramineproject/gramine/1841#-NvCJ3OKBQpBQTxSA-5o:-NvCJ3OKBQpBQTxSA-5p:bmvwrnj) ([raw file](https://github.com/gramineproject/gramine/blob/ae14b3db790b8a7ea0f0c290ab6436100f11bc02/tools/sgx/pf_tamper/pf_tamper.c#L160)):*
> ```C
>     truncate_file("trunc_meta_plain_3", offsetof(metadata_plaintext_header_t, minor_version));
>     truncate_file("trunc_meta_plain_4", offsetof(metadata_plaintext_header_t, metadata_key_salt));
>     truncate_file("trunc_meta_plain_5", FIELD_TRUNCATED(metadata_plaintext_header_t, metadata_key_salt));
> ```

FYI: I decided not to care about 100-char limit in this file -- maybe it's time to just delete this file, as it is broken for several years already...

**Review by g2flyer — COMMENTED** [review]
I like the house-cleaning of removing unused stuff and i also like the renaming which makes names clearer.  Only "complaint" i have is that pf_tamper.c is imho still used and while functionally still correct according to my tests probably will have to be properly formatted? (100 char line limits)?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841#-:-Nvc6Tz45Kf6yVyi5nLv:b-udmjsg)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files_internal.h` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1841#-NvCIcv37wpelKSkzmKV:-Nvc64c1AgCTgVfiQITx:bz0eroo) ([raw file](https://github.com/gramineproject/gramine/blob/ae14b3db790b8a7ea0f0c290ab6436100f11bc02/common/src/protected_files/protected_files_internal.h#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For reviewers' convenience, renames:
- `file_metadata` -> `metadata_node`
- `encrypted_part_plain` -> `metadata_decrypted_header`
- `root_mht` -> `root_mht_node`
- `file` -> `host_file_handle`
- `user_kdk_key` -> `kdk`
</blockquote></details>

nonce/id -> salt seems another criticial (but meaningful) rename?
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 160 at r1](https://reviewable.io/reviews/gramineproject/gramine/1841#-NvCJ3OKBQpBQTxSA-5o:-NvbjaLA3NPoiVMqsOxf:b-s5z3jb) ([raw file](https://github.com/gramineproject/gramine/blob/ae14b3db790b8a7ea0f0c290ab6436100f11bc02/tools/sgx/pf_tamper/pf_tamper.c#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I decided not to care about 100-char limit in this file -- maybe it's time to just delete this file, as it is broken for several years already...
</blockquote></details>

Sorry for my ignorance but looking at code i thought `pf_tamper` is still used `libos/test/fs/test_enc.py` and seems to work in that case, so at least only partially broken? In any case, deleting the file would break these tests?  In any case, your changes seem to work as ` (cd libos/test/fs; gramine-test pytest -v)` passes properly for me.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @g2flyer)

___
*[`common/src/protected_files/protected_files_internal.h` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1841#-NvCIcv37wpelKSkzmKV:-Nvfj_eFDKBwV8rNXC5d:b-b97zrk) ([raw file](https://github.com/gramineproject/gramine/blob/ae14b3db790b8a7ea0f0c290ab6436100f11bc02/common/src/protected_files/protected_files_internal.h#L16)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

nonce/id -> salt seems another criticial (but meaningful) rename?
</blockquote></details>

Yes, sure. This question is not actionable, right? I don't see anywhere in the code/commit message where I can add this info on `nonce -> salt`.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 160 at r1](https://reviewable.io/reviews/gramineproject/gramine/1841#-NvCJ3OKBQpBQTxSA-5o:-Nvfkgc1Dw6iuMjdunN4:b8t8oxr) ([raw file](https://github.com/gramineproject/gramine/blob/ae14b3db790b8a7ea0f0c290ab6436100f11bc02/tools/sgx/pf_tamper/pf_tamper.c#L160)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

Sorry for my ignorance but looking at code i thought `pf_tamper` is still used `libos/test/fs/test_enc.py` and seems to work in that case, so at least only partially broken? In any case, deleting the file would break these tests?  In any case, your changes seem to work as ` (cd libos/test/fs; gramine-test pytest -v)` passes properly for me.
</blockquote></details>

Done, you're right, my bad. It is still used, see `test_enc.py::TC_50_EncryptedFiles::test_500_invalid`.

**Review by g2flyer — COMMENTED** [review]
> Reviewed 6 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1841#-NwEdO4O-p7eXjiUOhel:-NwG-6p9-lpA-W5Bp5Kg:b-mbsx6j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Based on review of #1845, I changed `mac` -> `tag` everywhere.
</blockquote></details>

I see why this other comment lead you to a change here for consistency.  In the other review, though, i was mainly objecting to the use of _g_mac which seemed technically incorrect (whereas mac as more general and a bit vaguer term still could be considered still somewhat ok here).  I fear that`tag` with no attribution to authentication seems not to capture the meaning in the name alone and folks would have to look at comment in structure definition to know for sure .  I probably would use `auth_tag` instead of `tag` or just left `mac`

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841)* status: 1 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @g2flyer)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1841#-NwEdO4O-p7eXjiUOhel:-NwIykoi55lUt1jTHV0k:bbjs8j9) (no related file):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

I see why this other comment lead you to a change here for consistency.  In the other review, though, i was mainly objecting to the use of _g_mac which seemed technically incorrect (whereas mac as more general and a bit vaguer term still could be considered still somewhat ok here).  I fear that`tag` with no attribution to authentication seems not to capture the meaning in the name alone and folks would have to look at comment in structure definition to know for sure .  I probably would use `auth_tag` instead of `tag` or just left `mac`
</blockquote></details>

Done, reverted the previous change and renamed now from `gmac` -> `mac`.

___

**Review by g2flyer — COMMENTED** [review]
Looks so good i couldn't find anything else to comment on :-)

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841#-:-NwKn4Cl9M3F5dFx1_eR:bt1qgq2)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1841#-NweLeIgAgLx153pXdUW:-NwhaPSE-jVS0d4dv2Og:bfvh907) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you split this into smaller PRs? There are a lot of independent changes here, despite that "slightly" in the name ;) (the diff has ~600 lines)
</blockquote></details>

Hm, the diff itself is pretty simple. Most of the lines are trivial renames of variables.

But yes, I can split this PR into several ones. What about this split:
- Remove unused functions and variables
- Modify some weird `while()` loops into more readable `for()` loops
- Remove redundant/incorrect comments
- Move structs around
- Renames of data structs, variable names, func names (this PR I'll do only when PRs before are merged, otherwise merge conflicts will be too painful for me)

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1841#-NweLeIgAgLx153pXdUW:-Nws0GVq76mNoDNzSJva:b4y7s9p) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds good. The split should make the merging faster, because I guess there won't be any discussion for most of these parts, but there can be a few for the comment rewrite and variable renaming.
</blockquote></details>

- https://github.com/gramineproject/gramine/pull/1866
- https://github.com/gramineproject/gramine/pull/1867
- https://github.com/gramineproject/gramine/pull/1868
- https://github.com/gramineproject/gramine/pull/1869

This PR was split in 4 above PRs + there will be one more PR after the above ones are merged (that's to not have too many merge conflicts).

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1841)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1841#-NweLeIgAgLx153pXdUW:-O-orefEAVVMb-QvFcnf:b-srylho) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

- https://github.com/gramineproject/gramine/pull/1866
- https://github.com/gramineproject/gramine/pull/1867
- https://github.com/gramineproject/gramine/pull/1868
- https://github.com/gramineproject/gramine/pull/1869

This PR was split in 4 above PRs + there will be one more PR after the above ones are merged (that's to not have too many merge conflicts).
</blockquote></details>

Ok, this PR was split into 9 PRs. The last one is #1919. I'm closing this PR now, everything was moved into other PRs.

___

**Pull request closed without merging**
