### PR TITLE
[tests] Rewrite seek_tell test

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

As pointed out  in review https://reviewable.io/reviews/gramineproject/gramine/719 this test is ugly.
Rewrite it to self check whatever it can.
We can trust `stat` while determine the size of file as the `libos/test/fs/stat.c` test verifies this. 

## How to test this PR?

```
gramine-test -C libos/test/fs pytest
gramine-test --sgx -C libos/test/fs pytest
```

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)

### CODE REVIEW

**Review by oshogbo — COMMENTED** [review]
Please notice that this test passed after re-run: https://leeroy.cs.unc.edu/job/graphene-debug-18.04/8161/testReport/

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767#-:-N7HG4IB0ipU_112Gjnz:b-hd8r74)* status: 0 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Comment by oshogbo** [comment]
Jenkins, test this please

**Review by oshogbo — COMMENTED** [review]
The logs from the failed test, for feature reference:
```
AssertionError: Command ['loader', 'gramine/direct/libpal.so', 'init', 'rename_unlink', 'tmp/file1', 'tmp/file2'] timed out after 10 s
```

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767#-:-N7HLwL9ATQY3gnlLd_a:b-1qodrt)* status: 0 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/767#-N7KPfHn8zP-xgyPQL1z):*
`test` -> `FS test`
___
*[`libos/test/fs/common.h` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/767#-N7KPjKf3OpSlZU6SZw3:-N7KPjKf3OpSlZU6SZw4:b2r4huq) ([raw file](https://github.com/gramineproject/gramine/blob/4b4e885fdbeffcae02730b1e4b9c6d8ec595b9fe/libos/test/fs/common.h#L51)):*
> ```objc
> void* alloc_buffer(size_t size);
> void fill_random(void* buffer, size_t size);
> size_t file_size(const char *path);
> ```

Wrong alignment of `*`
___
*[`libos/test/fs/common.c` line 172 at r1](https://reviewable.io/reviews/gramineproject/gramine/767#-N7KPkyWB9oCdLP_JM3F:-N7KPkyWB9oCdLP_JM3G:b2r4huq) ([raw file](https://github.com/gramineproject/gramine/blob/4b4e885fdbeffcae02730b1e4b9c6d8ec595b9fe/libos/test/fs/common.c#L172)):*
> ```C
> }
> 
> size_t file_size(const char *path) {
> ```

Wrong alignment of `*`
___
*[`libos/test/fs/seek_tell.c` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/767#-N7KREQC-qB0HD_kF6j_:-N7KREQD5OOybk0DUqrd:b-4m1grn) ([raw file](https://github.com/gramineproject/gramine/blob/4b4e885fdbeffcae02730b1e4b9c6d8ec595b9fe/libos/test/fs/seek_tell.c#L77)):*
> ```C
>         }
>     }
>     size += EXTEND_SIZE;
> ```

Why do you increment the size in two places? Why not just `size += EXTEND_SIZE + 1` right-after `write_fd()`?
___
*[`libos/test/fs/seek_tell.c` line 122 at r1](https://reviewable.io/reviews/gramineproject/gramine/767#-N7KRsdn8atxYI3ZPIXC:-N7KRsdn8atxYI3ZPIXD:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4b4e885fdbeffcae02730b1e4b9c6d8ec595b9fe/libos/test/fs/seek_tell.c#L122)):*
> ```C
>         }
>     }
>     size += EXTEND_SIZE;
> ```

ditto

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners

___
*[`libos/test/fs/seek_tell.c` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/767#-N7KREQC-qB0HD_kF6j_:-N7LOqrF4w01A4HQ6yB9:b9wy775) ([raw file](https://github.com/gramineproject/gramine/blob/4b4e885fdbeffcae02730b1e4b9c6d8ec595b9fe/libos/test/fs/seek_tell.c#L77)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I figured out that this way is more evident to the reader.
If we add it at the end, the reader may start thinking about why there is +1? Write is a little bit hidden in the code.
Additionally - if you decide to use size in the code, you always have a current size.
</blockquote></details>

OK, if you feel it's more readable.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/fs/common.c` line 172 at r2](https://reviewable.io/reviews/gramineproject/gramine/767#-N96S1Wy8ozJLg5g8Pvb:-N96S1Wz2xhwHdt_x04K:bpboz3n) ([raw file](https://github.com/gramineproject/gramine/blob/13ce11613242930bc315b869973e028c720e9f85/libos/test/fs/common.c#L172)):*
> ```C
> }
> 
> size_t file_size(const char* path) {
> ```

```C
size_t file_size(...)
```

File size may not fit into `size_t`.
___
*[`libos/test/fs/seek_tell.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/767#-N96V-AT8u1jPgv42aOs:-N96V-AU19thGwH-iAZi:bl7gmky) ([raw file](https://github.com/gramineproject/gramine/blob/13ce11613242930bc315b869973e028c720e9f85/libos/test/fs/seek_tell.c#L20)):*
> ```C
>     seek_fd(path, f, 0, SEEK_SET);
>     off_t pos = tell_fd(path, f);
>     VERIFYU("tell position mismatch", 0, (size_t)pos);
> ```

You may lose higher bits here. Ditto for the whole PR.



_Code quote:_
```C
(size_t)pos
```

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/fs/common.c` line 172 at r2](https://reviewable.io/reviews/gramineproject/gramine/767#-N96S1Wy8ozJLg5g8Pvb:-N9BgXJhAX_EKBqYfeRk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/13ce11613242930bc315b869973e028c720e9f85/libos/test/fs/common.c#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

```C
size_t file_size(...)
```

File size may not fit into `size_t`.
</blockquote></details>

Done.
___
*[`libos/test/fs/seek_tell.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/767#-N96V-AT8u1jPgv42aOs:-N9BgYhp-O9tJamXNuzn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/13ce11613242930bc315b869973e028c720e9f85/libos/test/fs/seek_tell.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You may lose higher bits here. Ditto for the whole PR.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/fs/seek_tell.c` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/767#-N9DxKmC7yvCWwP8mIm6:-N9DxKmC7yvCWwP8mIm7:b-wyx8bd) ([raw file](https://github.com/gramineproject/gramine/blob/1f14a2bfd958d3aeb3770cfa1abe1dfed3e8e347/libos/test/fs/seek_tell.c#L10)):*
> ```C
>     uint64_t __r = (got);                                   \
>     if (__l != __r) {                                       \
>         fatal_error("%s:%d %s (expected %zu, got %zu)",     \
> ```

I think this won't compile on 32-bit because `%zu` won't match `uint64_t`.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/fs/seek_tell.c` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/767#-N9DxKmC7yvCWwP8mIm6:-N9WMrWB4HVU7Rs9DCW2:b7ojk32) ([raw file](https://github.com/gramineproject/gramine/blob/1f14a2bfd958d3aeb3770cfa1abe1dfed3e8e347/libos/test/fs/seek_tell.c#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this won't compile on 32-bit because `%zu` won't match `uint64_t`.
</blockquote></details>

You are right.
I don't like these `PRIu64` macros, is `%ju` ok with you?

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/fs/seek_tell.c` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/767#-N9DxKmC7yvCWwP8mIm6:-N9WsY9ICiGiPtY4Nn7Y:b-vtqqmd) ([raw file](https://github.com/gramineproject/gramine/blob/1f14a2bfd958d3aeb3770cfa1abe1dfed3e8e347/libos/test/fs/seek_tell.c#L10)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

You are right.
I don't like these `PRIu64` macros, is `%ju` ok with you?
</blockquote></details>

Nah, `%ju` is for `uintmax_t`, which is different (and also non-standard). I also don't like `PRIu64`, but I think there's no better way.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/fs/seek_tell.c` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/767#-N9DxKmC7yvCWwP8mIm6:-N9WwAs84Xd_l_QwUVgw:bmupxpd) ([raw file](https://github.com/gramineproject/gramine/blob/1f14a2bfd958d3aeb3770cfa1abe1dfed3e8e347/libos/test/fs/seek_tell.c#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nah, `%ju` is for `uintmax_t`, which is different (and also non-standard). I also don't like `PRIu64`, but I think there's no better way.
</blockquote></details>

I would say `%llu` is fine, it must be >= 64 bit

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/fs/seek_tell.c` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/767#-N9DxKmC7yvCWwP8mIm6:-N9XOLR25pDAXN6Udn6s:b2b45y8) ([raw file](https://github.com/gramineproject/gramine/blob/1f14a2bfd958d3aeb3770cfa1abe1dfed3e8e347/libos/test/fs/seek_tell.c#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would say `%llu` is fine, it must be >= 64 bit
</blockquote></details>

llu is fine on 32 but its is generating format errors on 64.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/fs/seek_tell.c` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/767#-N9DxKmC7yvCWwP8mIm6:-N9XVIHOAogJy9NH0gFh:bcko4c) ([raw file](https://github.com/gramineproject/gramine/blob/1f14a2bfd958d3aeb3770cfa1abe1dfed3e8e347/libos/test/fs/seek_tell.c#L10)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

llu is fine on 32 but its is generating format errors on 64.
</blockquote></details>

Ah, because i64 is probably typedef'ed to long int. Well, then unfortunately `PRIu64` is the only way

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/fs/seek_tell.c` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/767#-N9DxKmC7yvCWwP8mIm6:-N9bowA-D2Y1JdeNgqKj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1f14a2bfd958d3aeb3770cfa1abe1dfed3e8e347/libos/test/fs/seek_tell.c#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, because i64 is probably typedef'ed to long int. Well, then unfortunately `PRIu64` is the only way
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/fs/seek_tell.c` line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/767#-N9d4NS18OAI_PcUjHau:-N9d4NS18OAI_PcUjHav:ba3vl7v) ([raw file](https://github.com/gramineproject/gramine/blob/bcc8443c8bc503eeaea7842310374d756641c750/libos/test/fs/seek_tell.c#L12)):*
> ```C
>     uint64_t __r = (got);                                               \
>     if (__l != __r) {                                                   \
>         fatal_error("%s:%d %s (expected %""PRIu64, got %""PRIu64)",     \
> ```

Have you actually tested this change?

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/fs/seek_tell.c` line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/767#-N9d4NS18OAI_PcUjHau:-N9fvKfd9r_F2AEUsk98:b813a8z) ([raw file](https://github.com/gramineproject/gramine/blob/bcc8443c8bc503eeaea7842310374d756641c750/libos/test/fs/seek_tell.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Have you actually tested this change?
</blockquote></details>

If you asked me blindly, I would say that I have.
But obviously I have omitted it somehow.

**Review by oshogbo — COMMENTED** [review]
Jenkins, test this please

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767#-:-N9fwZXDB06MSgQqrBNG:b-9ef0ot)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by oshogbo — COMMENTED** [review]
The LTP test failed, which is not related to this change:
```
test_ltp.py:196: in test_ltp
    returncode, stdout, _stderr = run_command(full_cmd, timeout=timeout, can_fail=True)
../../../usr/lib/python3.6/site-packages/graminelibos/regression.py:148: in run_command
    raise AssertionError('Command {} timed out after {} s'.format(cmd, timeout))
E   AssertionError: Command ['gramine-direct', 'fcntl14_64'] timed out after 60 s
```

I guess its because this PR was not rebased yet.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767#-:-N9gjcHC6cjC9cSWsvaL:b-3c5ivl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
@oshogbo It works fine for you locally? But yes, should be unrelated to your PR.

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767#-:-N9l4KgAA1g4N_s89dNs:bb3m8au)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/767)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
