### PR TITLE
Drop deprecated syntax of loader.entrypoint

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

As in the title.

## How to test this PR? 

Please verify that I didn't miss any place.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Direct-24.04-Debug please (fdatasync01 from LTP timed out, known and unrelated to the PR)

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`Documentation/manifest-syntax.rst` line 1395 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBBPzj2EsFCy65X8I0Y:-OBBPzj2EsFCy65X8I0Z:b6ixdsw) ([raw file](https://github.com/gramineproject/gramine/blob/a08a455d7910dff7c202d61a19466cb049fc72fb/Documentation/manifest-syntax.rst#L1395)):*
> ```reStructuredText
> See :ref:`vtune-sgx-profiling` for more information.
> 
> Deprecated options
> ```

Did we just ran out of deprecated options?
___
*[`libos/test/regression/toml_parsing.manifest.template` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBBQDGH0lCsYCGqD0E9:-OBBQDGH0lCsYCGqD0EA:bhjckiu) ([raw file](https://github.com/gramineproject/gramine/blob/a08a455d7910dff7c202d61a19466cb049fc72fb/libos/test/regression/toml_parsing.manifest.template#L3)):*
> ```
> # This test contains tricky/legacy TOML syntax, just to test TOML parsing and have some coverage
> 
> {% set entrypoint = "helloworld" -%}
> ```

This looks wrong, it probably causes Jinja substitution near `libos.entrypoint` assignment below to fail, and your tests still fails as expected, but not for the reason you think it should fail.
___
*[`python/graminelibos/manifest.py` line 347 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBBR2070fU2B7Ilv3dk:-OBBR2070fU2B7Ilv3dl:b-h4d41z) ([raw file](https://github.com/gramineproject/gramine/blob/dd2d9bf2354f98ed2988a93809a91b4ffda9d849/python/graminelibos/manifest.py#L347)):*
> ```Python
>         loader_entrypoint = loader.setdefault('entrypoint', {})
> 
>         if not isinstance(loader_entrypoint, dict):
> ```

N/B, but I'd write `collections.abc.Mapping` (https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping), in case someone user a mapping different than `dict`, but still duck-compatible.

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`libos/test/regression/toml_parsing.manifest.template` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBBQDGH0lCsYCGqD0E9:-OBBS18Q3k_mxPKIKvKX:bxcte6c) ([raw file](https://github.com/gramineproject/gramine/blob/a08a455d7910dff7c202d61a19466cb049fc72fb/libos/test/regression/toml_parsing.manifest.template#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This looks wrong, it probably causes Jinja substitution near `libos.entrypoint` assignment below to fail, and your tests still fails as expected, but not for the reason you think it should fail.
</blockquote></details>

Ah, no, it's repeated below, sorry.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`Documentation/manifest-syntax.rst` line 1395 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBBPzj2EsFCy65X8I0Y:-OBBTGKGAOi9t_k4IPuV:b-x0paxf) ([raw file](https://github.com/gramineproject/gramine/blob/a08a455d7910dff7c202d61a19466cb049fc72fb/Documentation/manifest-syntax.rst#L1395)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Did we just ran out of deprecated options?
</blockquote></details>

Yes :)
___
*[`python/graminelibos/manifest.py` line 347 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBBR2070fU2B7Ilv3dk:-OBBTVve2axHRPPWQCA5:b-67q2iv) ([raw file](https://github.com/gramineproject/gramine/blob/dd2d9bf2354f98ed2988a93809a91b4ffda9d849/python/graminelibos/manifest.py#L347)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

N/B, but I'd write `collections.abc.Mapping` (https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping), in case someone user a mapping different than `dict`, but still duck-compatible.
</blockquote></details>

This is directly outputted from TOML parsing or the code in this very function, so I think it's fine. I.e. that "someone" would need to be us in this very function or TOML would need to change the API.
Also, in other places in this file we do the same, so I'd rather keep it as is, if you don't insist.

**Review by woju — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`python/graminelibos/manifest.py` line 347 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBBR2070fU2B7Ilv3dk:-OBBUhNXBS-CI5PNzVWA:bln1jso) ([raw file](https://github.com/gramineproject/gramine/blob/dd2d9bf2354f98ed2988a93809a91b4ffda9d849/python/graminelibos/manifest.py#L347)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is directly outputted from TOML parsing or the code in this very function, so I think it's fine. I.e. that "someone" would need to be us in this very function or TOML would need to change the API.
Also, in other places in this file we do the same, so I'd rather keep it as is, if you don't insist.
</blockquote></details>

I don't. Let's wait for someone using this code as library, function-by-function, to file a ticket asking for this as a feature request.

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBDne8A9SQzgHLeNc0h:-OBDne8A9SQzgHLeNc0i:b-bemeg9):*
-> `[PAL] Drop deprecated syntax of loader.entrypoint`?



_Code quote:_
```
Drop deprecated syntax of loader.entrypoint
```
___
*[`python/graminelibos/manifest.py` line 348 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBDoycyALmZ20Rtocc2:-OBDoycyALmZ20Rtocc3:b-wdilm) ([raw file](https://github.com/gramineproject/gramine/blob/dd2d9bf2354f98ed2988a93809a91b4ffda9d849/python/graminelibos/manifest.py#L348)):*
> ```Python
> 
>         if not isinstance(loader_entrypoint, dict):
>             raise ManifestError('Unknown loader.entrypoint format (not a TOML table)')
> ```

to make it more informative, like:
 
```python
raise ManifestError(f'Unknown loader.entrypoint format (not a TOML table): {loader_entrypoint!r}')
```
?



_Code quote:_
```Python
raise ManifestError('Unknown loader.entrypoint format (not a TOML table)')
```
___
*[`libos/test/regression/mock_syscalls.manifest.template` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBDlQHrCqv8YfLFXbfP:-OBDlQHrCqv8YfLFXbfQ:b8325vj) ([raw file](https://github.com/gramineproject/gramine/blob/a08a455d7910dff7c202d61a19466cb049fc72fb/libos/test/regression/mock_syscalls.manifest.template#L39)):*
> ```
> 
> sgx.trusted_files = [
>   "file:{{ gramine.libos }}",
> ```

This can also be removed.



_Code quote:_
```
  "file:{{ gramine.libos }}",
```

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBDne8A9SQzgHLeNc0h:-OBIabYp5Sq4XFQ1IuAt:bk5odft):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `[PAL] Drop deprecated syntax of loader.entrypoint`?
</blockquote></details>

Will do at rebase.
___
*[`libos/test/regression/mock_syscalls.manifest.template` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBDlQHrCqv8YfLFXbfP:-OBIahytAiu-A2TZM9tn:b-z67ro2) ([raw file](https://github.com/gramineproject/gramine/blob/a08a455d7910dff7c202d61a19466cb049fc72fb/libos/test/regression/mock_syscalls.manifest.template#L39)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This can also be removed.
</blockquote></details>

Done, nice catch!
___
*[`python/graminelibos/manifest.py` line 348 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBDoycyALmZ20Rtocc2:-OBIao1Z1uPrlpI7Lcfe:b-hgi7eu) ([raw file](https://github.com/gramineproject/gramine/blob/dd2d9bf2354f98ed2988a93809a91b4ffda9d849/python/graminelibos/manifest.py#L348)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

to make it more informative, like:
 
```python
raise ManifestError(f'Unknown loader.entrypoint format (not a TOML table): {loader_entrypoint!r}')
```
?
</blockquote></details>

That was my original version actually, but when testing I noticed that it ended up confusing - with the most likely way to specify this option wrong (which is specifying a string, like in the old syntax), we get an error: `Unknown loader.entrypoint format (not a TOML table): "file:some_uri_here"`. It would be more helpful if we printed it with the key name and assignment (`loader.entrypoint = "file:some_uri_here"`) but we can't easily do it 1-1 as it really is in the source TOML. So, I'd keep it as is, unless you have some better idea :)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`python/graminelibos/manifest.py` line 348 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBDoycyALmZ20Rtocc2:-OBImo380YbBnn4_3qyp:bhgwgry) ([raw file](https://github.com/gramineproject/gramine/blob/dd2d9bf2354f98ed2988a93809a91b4ffda9d849/python/graminelibos/manifest.py#L348)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That was my original version actually, but when testing I noticed that it ended up confusing - with the most likely way to specify this option wrong (which is specifying a string, like in the old syntax), we get an error: `Unknown loader.entrypoint format (not a TOML table): "file:some_uri_here"`. It would be more helpful if we printed it with the key name and assignment (`loader.entrypoint = "file:some_uri_here"`) but we can't easily do it 1-1 as it really is in the source TOML. So, I'd keep it as is, unless you have some better idea :)
</blockquote></details>

Indeed, that's also confusing... Let's keep it as is then.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2054#-OBDne8A9SQzgHLeNc0h:-OBLG1J49Itu53s-l_nC:b-896fix):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Will do at rebase.
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2054)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
