### PR TITLE
[Docs] Adjust building instructions paragraphs

### PR DESCRIPTION
**Pull request by efu39**
## Description of the changes 
Rearrange some paragraphs of building instructions and add a troubleshooting subsection under 'run a sample application'.

## How to test this PR? 
Build and verify documentation locally.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1676)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1676)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @efu39)

___
*[`Documentation/run-sample-application.rst` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnHY4UZ-equs0xqDien:-NnHY4UZ-equs0xqDieo:b2zxhnr) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/run-sample-application.rst#L49)):*
> ```reStructuredText
> below.
> 
> Troubleshooting
> ```

But we've already had the following in the top-level doc: https://github.com/gramineproject/gramine/blob/5d38bb14077cf87f1ddb3cef07f6f2ab70621276/Documentation/index.rst?plain=1#L78-L83?

Both of the troubleshooting items listed would go to the `sgx-setup` section (prerequisite). Why not instead simply add a note pointing to `sgx-setup` at the beginning of this doc?



_Code quote:_
```reStructuredText
Troubleshooting
```
___
*[`Documentation/devel/building.rst` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnH_3408BQu44yB1Ny4:-NnH_3408BQu44yB1Ny5:bbrka52) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/devel/building.rst#L129)):*
> ```reStructuredText
> 
>    meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled \
>        -Dsgx_driver=(upstream|oot) -Dsgx_driver_include_path=<path-to-sgx-driver-sources>
> ```

not sure if it's the right syntax (or is there one?)... maybe `<upstream,oot>`?



_Code quote:_
```reStructuredText
(upstream|oot)
```

**Review by kailun-qin — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1676)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @efu39)

**Review by efu39 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1676)* status: 1 of 4 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnDgUwH9QygwiRiRDu9):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to squash all three commits into a single commit and do something like this:
```
[Docs] Minor updates and rearrangements

- Add Troubleshooting section in "Run a sample application" page.
- Rearrange build instruction paragraphs in "Build Gramine" section.
- Add Installation Prerequisites in "Building documentation" section.
```

Just squash now (though we strongly discourage this practice in the Gramine review process -- but here it's fine otherwise it will be very painful to add fixup commits to this PR later).
</blockquote></details>

squashed the commits into one as suggested.
___
*[`Documentation/run-sample-application.rst` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnHY4UZ-equs0xqDien:-NnyXafC1MnHAb1e87fh:bkfffg7) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/run-sample-application.rst#L49)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But we've already had the following in the top-level doc: https://github.com/gramineproject/gramine/blob/5d38bb14077cf87f1ddb3cef07f6f2ab70621276/Documentation/index.rst?plain=1#L78-L83?

Both of the troubleshooting items listed would go to the `sgx-setup` section (prerequisite). Why not instead simply add a note pointing to `sgx-setup` at the beginning of this doc?
</blockquote></details>

Added a prerequisite section pointing to `sgx-setup` at the beginning as suggested. 

For the troubleshooting section, I think it might be helpful for the new users with the errors they might encounter but I'm open if removal is preferred. 
___
*[`Documentation/run-sample-application.rst` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnDh-H57bpbKx0HPO_K:-NnybuZ61YDTnEnDg1GM:bvclzih) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/run-sample-application.rst#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about:
```
- **"Signing key does not exist" error**
```
</blockquote></details>

looks good. changed to this. 
___
*[`Documentation/run-sample-application.rst` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnDhDLv8WhZZN5HaZhO:-Nnyc1jN102xs-q92ub-:b-7rl0jd) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/run-sample-application.rst#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to add double-quotes:
```
- **"Cannot open SGX driver device" error**
```
</blockquote></details>

done.
___
*[`Documentation/run-sample-application.rst` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnDhJ97AWi3_O4U8Mxg:-Nnyc9fQ-z50KLl1tKwB:brpmqc3) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/run-sample-application.rst#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove this `Gramine is starting` line. It's not relevant to the error.
</blockquote></details>

removed.
___
*[`Documentation/run-sample-application.rst` line 66 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnDhTRkAkEn1SYuDgm6:-NnycC7O6tRt3AIDkq0X:b-7rl0jd) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/run-sample-application.rst#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would make it shorter:
```
   error: Cannot open SGX driver device. [...]
```
</blockquote></details>

done.
___
*[`Documentation/run-sample-application.rst` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnDhMh_DXuiM5p4eFmO:-NnycEuJ-Zsb4f_XE_62:brpmqc3) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/run-sample-application.rst#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove this line too. It's irrelevant information.
</blockquote></details>

removed.
___
*[`Documentation/devel/building.rst` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnH_3408BQu44yB1Ny4:-NnycGbN0W9WAXjz67wY:b-v7p2xy) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/devel/building.rst#L129)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

not sure if it's the right syntax (or is there one?)... maybe `<upstream,oot>`?
</blockquote></details>

'(upstream|oot)' is what I found as some what convention. Thanks.
- https://www.ibm.com/docs/en/flashsystem-v7000u/1.6.1?topic=commands-command-syntax-conventions
- '(amend|reword)' example in https://git-scm.com/docs/git-commit
___
*[`Documentation/devel/howto-doc.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnDhhIRBtQbRjYNy9Qk:-NnycoEI2TGXpY6W87N5:b-qssebl) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/devel/howto-doc.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think the correct form is `Installing prerequisites`
</blockquote></details>

fixed.

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1676)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Documentation/run-sample-application.rst` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnHY4UZ-equs0xqDien:-NoBNIQX7ce8WSSR8OoT:bm1gzd8) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/run-sample-application.rst#L49)):*
<details><summary><i>Previously, efu39 (Erica Fu) wrote…</i></summary><blockquote>

Added a prerequisite section pointing to `sgx-setup` at the beginning as suggested. 

For the troubleshooting section, I think it might be helpful for the new users with the errors they might encounter but I'm open if removal is preferred.
</blockquote></details>

I agree with @efu39, I think it's good to have the section in our Example page (which is a [separate page](https://gramine.readthedocs.io/en/stable/run-sample-application.html), so users may only look at this page and wonder "I have a problem, what do I do now?")
___
*[`Documentation/devel/building.rst` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnH_3408BQu44yB1Ny4:-NoBNe5s4loM9ABg39J_:bmqu01v) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/devel/building.rst#L129)):*
<details><summary><i>Previously, efu39 (Erica Fu) wrote…</i></summary><blockquote>

'(upstream|oot)' is what I found as some what convention. Thanks.
- https://www.ibm.com/docs/en/flashsystem-v7000u/1.6.1?topic=commands-command-syntax-conventions
- '(amend|reword)' example in https://git-scm.com/docs/git-commit
</blockquote></details>

I agree with @efu39, I think it looks obvious

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1676)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`Documentation/run-sample-application.rst` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnHY4UZ-equs0xqDien:-No9y5x32FZ-yfEHDk0a:b-fy3r1p) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/run-sample-application.rst#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with @efu39, I think it's good to have the section in our Example page (which is a [separate page](https://gramine.readthedocs.io/en/stable/run-sample-application.html), so users may only look at this page and wonder "I have a problem, what do I do now?")
</blockquote></details>

Thanks, I'm fine w/ the troubleshooting section.
___
*[`Documentation/devel/building.rst` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/1676#-NnH_3408BQu44yB1Ny4:-No9yGmq-h5P_1zH6end:bd9pifs) ([raw file](https://github.com/gramineproject/gramine/blob/befbd42b9ea5c06ad0d7e141d3442b7544438dd9/Documentation/devel/building.rst#L129)):*
<details><summary><i>Previously, efu39 (Erica Fu) wrote…</i></summary><blockquote>

'(upstream|oot)' is what I found as some what convention. Thanks.
- https://www.ibm.com/docs/en/flashsystem-v7000u/1.6.1?topic=commands-command-syntax-conventions
- '(amend|reword)' example in https://git-scm.com/docs/git-commit
</blockquote></details>

Thanks! Looks good.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by kailun-qin — APPROVED** [review]
Jenkins, test this please

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1676#-:-NoVeIP54W7ZWU02W9-c:bkop2df)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1676#-NoCdkXZ8kFlw7EEE1iR:-NoVdu6nDvi4bDBfbCuV:b6fs7n3) (no related file):*
>Could you let me know how or where to see this warning?

I guess `make html man SPHINXOPTS="-W"` would generate the warning (as error) as expected?

___

**Comment by kailun-qin** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1676)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by woju — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1676)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, test this please

**Pull request merged**
