### PR TITLE
[Pal/Linux-SGX] Fix bugs in `ra_tls_create_key_and_crt_der()` API

### LINKED ISSUE #289: Incomplete pointer check in create_key_and_crt, misleading size passing in ra_tls_create_key_and_crt_der inside libra_tls_attest.so
## Description of the problem
The problem lies in `gramine/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c`. 

In function `create_key_and_crt`, line 200, it checks null pointer condition by follows. 

```
static int create_key_and_crt(mbedtls_pk_context* key, mbedtls_x509_crt* crt, uint8_t** crt_der,
                              size_t* crt_der_size) {
    int ret;

    if (!key || !crt)
        return MBEDTLS_ERR_X509_FATAL_ERROR;
```

However, in exported function `ra_tls_create_key_and_crt_der`, it uses the function `create_key_and_crt` as follows.

```
    ret = create_key_and_crt(&key, NULL, der_crt, der_crt_size);
    if (ret < 0) {
        goto out;
    }
```

We can easily see that `MBEDTLS_ERR_X509_FATAL_ERROR` will always be returned, thus making the exported function useless.

The function `create_key_and_crt` seems to require parameter `crt` or `crt_der && crt_der_size`. 

In function `create_key_and_crt`, line 249, it checks the latter before use.

```
    if (crt_der && crt_der_size) {
        crt_der_buf = malloc(size);
        if (!crt_der_buf) {
            ret = MBEDTLS_ERR_X509_ALLOC_FAILED;
            goto out;
        }
```

Or, it checks the former before use. 

```
    if (crt) {
        ret = mbedtls_x509_crt_parse_der(crt, output_buf + output_buf_size - size, size);
        if (ret < 0)
            goto out;
    }
```

So it looks safe to even not check those pointers, but considering what the function does, I think checking with `||` will suffice.

There is also another bug in function `ra_tls_create_key_and_crt_der`. The size of pre-output buffer is specified to be `1024`, but it seems that this is not sufficient. In fact, the source code in ra-tls from [Intel Labs](https://github.com/cloud-security-research/sgx-ra-tls/blob/099a36e5b80932b8d5bfacd656c3489a6379241e/mbedtls-ra-attester.c#L262) uses `16 * 1024`. I changed it to `4 * 1024`. 

```
    uint8_t* output_buf    = NULL;
    size_t output_buf_size = 1024; /* enough for any public key */
```

Also, the size of the buffer is specified as `sizeof(output_buf)` in two places, but this is not true, because `sizeof` will return the size of the pointer. This should be changed to `output_buf_size`. 

```
    /* populate der_key; note that der_crt was already populated */
    int size = mbedtls_pk_write_key_der(&key, output_buf, sizeof(output_buf));
    if (size < 0) {
        ret = size;
        goto out;
    }
```

```
    /* note that mbedtls_pk_write_key_der() wrote data at the end of the output_buf */
    memcpy(der_key_buf, output_buf + sizeof(output_buf) - size, size);
    *der_key      = der_key_buf;
    *der_key_size = size;
```

## Steps to reproduce

This bug is still here on current master commit `4d919534dfec67a9aba8f9a3b85119241f539101`.

Just try the following example source that I made for an example. Manifest is omitted because it seems straight forward.

```
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

int ra_tls_create_key_and_crt_der(uint8_t** der_key, size_t* der_key_size, uint8_t** der_crt,
                                  size_t* der_crt_size);

int main(){
        int ret;
        uint8_t * key, * crt;
        size_t key_size, crt_size;
        FILE * f = NULL;

        ret = ra_tls_create_key_and_crt_der(&key, &key_size, &crt, &crt_size);
        if(ret){
                printf("create certificate error with code %d\n", ret);
                exit(ret);
        }

        printf("Writing %lu bytes to key.pem\n", key_size);
        f = fopen("key.pem", "w");
        fwrite(key, sizeof(*key), key_size, f);
        fclose(f);

        printf("Writing %lu bytes to cert.crt\n", crt_size);
        f = fopen("cert.crt", "w");
        fwrite(crt, sizeof(*crt), crt_size, f);
        fclose(f);

        printf("End of Program\n");
}
```

## Expected results
```
Writing 1767 bytes to key.pem
Writing 2227 bytes to cert.crt
End of Program
```

## Actual results
```
create certificate error with code -12288
```
## Additional information
I myself did a simple patch and just rebuilt the library. Here is a `git diff` output of it.
```
diff --git a/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c b/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c
index dff5d375..92e7c615 100644
--- a/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c
+++ b/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c
@@ -197,7 +197,7 @@ static int create_key_and_crt(mbedtls_pk_context* key, mbedtls_x509_crt* crt, ui
                               size_t* crt_der_size) {
     int ret;

-    if (!key || !crt)
+    if (!key || (!crt && !(crt_der && crt_der_size)))
         return MBEDTLS_ERR_X509_FATAL_ERROR;

     mbedtls_ctr_drbg_context ctr_drbg;
@@ -293,7 +293,7 @@ int ra_tls_create_key_and_crt_der(uint8_t** der_key, size_t* der_key_size, uint8

     uint8_t* der_key_buf   = NULL;
     uint8_t* output_buf    = NULL;
-    size_t output_buf_size = 1024; /* enough for any public key */
+    size_t output_buf_size = 4 * 1024; /* enough for any public key */

     output_buf = malloc(output_buf_size);
     if (!output_buf) {
@@ -307,7 +307,7 @@ int ra_tls_create_key_and_crt_der(uint8_t** der_key, size_t* der_key_size, uint8
     }

     /* populate der_key; note that der_crt was already populated */
-    int size = mbedtls_pk_write_key_der(&key, output_buf, sizeof(output_buf));
+    int size = mbedtls_pk_write_key_der(&key, output_buf, output_buf_size);
     if (size < 0) {
         ret = size;
         goto out;
@@ -320,7 +320,7 @@ int ra_tls_create_key_and_crt_der(uint8_t** der_key, size_t* der_key_size, uint8
     }

     /* note that mbedtls_pk_write_key_der() wrote data at the end of the output_buf */
-    memcpy(der_key_buf, output_buf + sizeof(output_buf) - size, size);
+    memcpy(der_key_buf, output_buf + output_buf_size - size, size);
     *der_key      = der_key_buf;
     *der_key_size = size;

```

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

See #289 for the context and analysis.

The function got stale because it was not covered by our CI tests. This PR modifies the CI example `ra-tls-mbedtls` to use this function.

Fixes #289.

## How to test this PR? 

`ra-tls-mbedtls` CI example was updated.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/295)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/295)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[CI-Examples/ra-tls-mbedtls/src/server.c, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/295#-Muqwus89ew6Fv4QppH6:-Muqwus89ew6Fv4QppH7:bzakfl8) ([raw file](https://github.com/gramineproject/gramine/blob/05006b26985de75a1efd87be25157689de72a653/CI-Examples/ra-tls-mbedtls/src/server.c#L73)):*
> ```C
>     const char* pers = "ssl_server";
> 
>     void* ra_tls_attest_lib         = NULL;
> ```

Please un-align.
___
*[CI-Examples/ra-tls-mbedtls/src/server.c, line 142 at r1](https://reviewable.io/reviews/gramineproject/gramine/295#-Mur08bHBh9gZo2N3NCw:-Mur08bHBh9gZo2N3NCx:bi0y7tg) ([raw file](https://github.com/gramineproject/gramine/blob/05006b26985de75a1efd87be25157689de72a653/CI-Examples/ra-tls-mbedtls/src/server.c#L142)):*
> ```C
>         }
> 
>         ret = mbedtls_pk_parse_key(&pkey, (const unsigned char*)der_key, der_key_size, NULL, 0);
> ```

This `const` shouldn't be needed.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/295)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[CI-Examples/ra-tls-mbedtls/src/server.c, line 136 at r1](https://reviewable.io/reviews/gramineproject/gramine/295#-MusASco7eUtNp6GiBQJ:-MusASco7eUtNp6GiBQK:b-h5xn2m) ([raw file](https://github.com/gramineproject/gramine/blob/05006b26985de75a1efd87be25157689de72a653/CI-Examples/ra-tls-mbedtls/src/server.c#L136)):*
> ```C
>         }
> 
>         ret = mbedtls_x509_crt_parse(&srvcert, (const unsigned char*)der_crt, der_crt_size);
> ```

This `const` as well.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/295)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[CI-Examples/ra-tls-mbedtls/src/server.c, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/295#-Muqwus89ew6Fv4QppH6:-MutKKRP4hKKKzXGY5pU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/05006b26985de75a1efd87be25157689de72a653/CI-Examples/ra-tls-mbedtls/src/server.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please un-align.
</blockquote></details>

Done.
___
*[CI-Examples/ra-tls-mbedtls/src/server.c, line 136 at r1](https://reviewable.io/reviews/gramineproject/gramine/295#-MusASco7eUtNp6GiBQJ:-MutKSMM4XPgZq5ZNXeQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/05006b26985de75a1efd87be25157689de72a653/CI-Examples/ra-tls-mbedtls/src/server.c#L136)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This `const` as well.
</blockquote></details>

Done.
___
*[CI-Examples/ra-tls-mbedtls/src/server.c, line 142 at r1](https://reviewable.io/reviews/gramineproject/gramine/295#-Mur08bHBh9gZo2N3NCw:-MutKYGQEWqxwdZle6wb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/05006b26985de75a1efd87be25157689de72a653/CI-Examples/ra-tls-mbedtls/src/server.c#L142)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This `const` shouldn't be needed.
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/295)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/295)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/295)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/295)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
