### PR TITLE
[Docs] Add SECURITY.md

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The text is based on
https://github.com/electron/electron/blob/28-x-y/SECURITY.md.

The text is kept rather minimal as per discussions with @woju and @mkow.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBVbt4s8GIoWgl_oI:-NjSBVbt4s8GIoWgl_oJ:b-63jaq) (no related file):*
FYI: GitHub renders the file like this: https://github.com/gramineproject/gramine/blob/dimakuv/add-security-md/SECURITY.rst

___
___
*[`SECURITY.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBXtN1-vaAeVCToHu:-NjSBXtN1-vaAeVCToHv:btia4lc) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L12)):*
> ```reStructuredText
> Please note that the Gramine team analyzes security bugs only on the current
> ``master`` branch. This implies that you must reproduce the bug on master before
> reporting.
> ```

This paragraph was suggested by @mkow 
___
*[`SECURITY.rst` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBaSiACIGZTWePdT7:-NjSBaSiACIGZTWePdT8:bwzeopx) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L20)):*
> ```reStructuredText
> 
> Report security bugs in third-party dependencies (e.g., in mbedTLS) to the
> person or team maintaining that dependency.
> ```

Do we want this paragraph?

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSMk-B6LrPo7KxBc3Q:-NjSMk-B6LrPo7KxBc3R:baopg1a) (no related file):*
What about: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/README.rst#L90-L93 then?

___
___
*[`SECURITY.rst` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBaSiACIGZTWePdT7:-NjSNQk0Bys6z-NpKSLj:bupfoz3) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want this paragraph?
</blockquote></details>

I feel like it's not really needed.

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBVbt4s8GIoWgl_oI:-NjSW6Ya9bVcrlRYWYJr:b-jdbfoq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: GitHub renders the file like this: https://github.com/gramineproject/gramine/blob/dimakuv/add-security-md/SECURITY.rst
</blockquote></details>

Unfortunately this is misleading, because we also care about https://github.com/gramineproject/gramine/security, and that won't be there. GitHub renders only plaintext `SECURITY` and markdown `SECURITY.md` (and it can't even render the proper suffix of `SECURITY.markdown`, it insists on a suffix for https://en.wikipedia.org/wiki/Modula). This can't be .rst. 

See test repos:
- https://github.com/woju/test-security
  https://github.com/woju/test-security/security
- https://github.com/woju/test-security-md
  https://github.com/woju/test-security-md/security
- https://github.com/woju/test-security-markdown
  https://github.com/woju/test-security-markdown/security
- https://github.com/woju/test-security-rst
  https://github.com/woju/test-security-rst/security

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSMk-B6LrPo7KxBc3Q:-NjSRpWB4raR5-qxeyQo:b-y4hbwa) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/README.rst#L90-L93 then?
</blockquote></details>

I don't see a problem with keeping that in README (until those addresses go out of sync, then it would be bad). Maybe we can add link to SECURITY.md in README?

The point of adding SECURITY.md is to add another entry in https://github.com/gramineproject/gramine/issues/new/choose, which will replace "report security vulnerability" option (see other discussion). We already have that option by means of `.github/ISSUE-TEMPLATE`. IIUC this security.md thingy was a finding on some analyzer report geared towards people who don't think about providing proper channel for reproting vulns, so to my understanding this PR is mostly to silence some annoying scanner, not to have any measurable benefit to our project.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSSaUgACDmrE-nTQpf:-NjSSaUgACDmrE-nTQpg:b-4vckez) (no related file):*
I think you should remove this: https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/.github/ISSUE_TEMPLATE/config.yml#L6-L9, because it will be redundant.

___
___
*[`SECURITY.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBXtN1-vaAeVCToHu:-NjSR16e1p_z5-gkpFmY:b4vwlsz) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This paragraph was suggested by @mkow
</blockquote></details>

I disagree with the text: bugs in our stable packages are also to be reported, if accidentally fixed on master, because they might cause us to rush the next release.
___
*[`SECURITY.rst` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBaSiACIGZTWePdT7:-NjSR7xT7CxOVHfx-5qc:b-zu0dg) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L20)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I feel like it's not really needed.
</blockquote></details>

First of all, it's incorrect, we want to know about bugs in subprojects which we statically link against, because a bug in subproject affects us until we release, even if fixed upstream and packaged by distros.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSMk-B6LrPo7KxBc3Q:-NjS_5aa6UsYJdRN5LTH:b-11s1jy) (no related file):*
> We already have that option by means of `.github/ISSUE-TEMPLATE`.

Oh, I actually didn't realize this. Indeed we already have this.

Then what would be the additional benefit of SECURITY.md? Maybe we should just remove it. (Or remove the ISSUE-TEMPLATE item.)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSSaUgACDmrE-nTQpf:-NjS_Fh78Xpfm6jaHs7Q:b-gyrogu) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I think you should remove this: https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/.github/ISSUE_TEMPLATE/config.yml#L6-L9, because it will be redundant.
</blockquote></details>

@mkow @kailun-qin  Which option you prefer?

___
___
*[`SECURITY.rst` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBaSiACIGZTWePdT7:-NjS_KRE4fchCP1jd0K_:b-i9lk3p) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L20)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

First of all, it's incorrect, we want to know about bugs in subprojects which we statically link against, because a bug in subproject affects us until we release, even if fixed upstream and packaged by distros.
</blockquote></details>

Ok, I'll remove this para.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSMk-B6LrPo7KxBc3Q:-NjS_Wtv10kS7eXiUmjP:b-mzsd90) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> We already have that option by means of `.github/ISSUE-TEMPLATE`.

Oh, I actually didn't realize this. Indeed we already have this.

Then what would be the additional benefit of SECURITY.md? Maybe we should just remove it. (Or remove the ISSUE-TEMPLATE item.)
</blockquote></details>

I don't care much either way. Maybe I slightly prefer SECURITY.md, because it shows up on /security, and also will finally tick that checkbox on someone's report so they'll stop bothering us.

___

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`SECURITY.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSri15AvhOPMGtoijK:-NjSri15AvhOPMGtoijL:b-blaxq1) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L4)):*
> The Gramine team and community take security bugs in Gramine seriously.

Please don't. Literally every mail / announcement from corporations after they got hacked and all the user private data got leaked start with exactly this sentence, it became kind of a meme now and is associated with actually not caring about security but having a big PR department writing flowery statements.
I'd just drop this whole paragraph and replace with a single sentence somewhere later in the document saying that if the submission is correct, we'll acknowledge the reporter in the commit message. And also ask in that sentence for the preferred name / nick to put there.
___
*[`SECURITY.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBXtN1-vaAeVCToHu:-NjSpzqn-j7kBs8QdpLp:b84r1ln) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I disagree with the text: bugs in our stable packages are also to be reported, if accidentally fixed on master, because they might cause us to rush the next release.
</blockquote></details>

That's IMO a very exotic corner case and it's IMO not worth to complicate the instructions. So, I vote for the current version.
Also, in practice, I believe the current description will prevent a lot of bogus reports.
___
*[`SECURITY.rst` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBaSiACIGZTWePdT7:-NjSqspnEkX7Tzct9ilO:b-9390wc) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L20)):*
> we want to know about bugs in subprojects which we statically link against

Yeah, but after they are confirmed by their maintainers. I don't think we'll be able (or rather, have time) to analyze a report for some mbedtls internals, and especially, to correctly fix it. @woju: Please keep in mind that a huge part of security and normal bug reports are bogus and we want to limit noise-to-signal ratio.

But I'm not blocking, this paragraph is not strictly needed because most security professionals already know this and comply to it.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSSaUgACDmrE-nTQpf:-NjSt8uqB5G5482ZeemO:b-o935lu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow @kailun-qin  Which option you prefer?
</blockquote></details>

I'm neutral, I don't care that much, we already have this info everywhere :)

___

**Comment by monavij** [comment]
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm neutral, I don't care that much, we already have this info everywhere :)
</blockquote></details>

I don't care as well, but  since it's expected from security projects, I would go with SECUIRTY.md.

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSMk-B6LrPo7KxBc3Q:-NjVSTYW5grKfIaLzucI:b-7btmyy) (no related file):*
> Maybe we can add link to SECURITY.md in README?

+1.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSSaUgACDmrE-nTQpf:-NjVRuWO7UHlNIGV1J4y:bb8qlja) (no related file):*
<details><summary><i>Previously, monavij (Mona Vij) wrote…</i></summary><blockquote>

I don't care as well, but  since it's expected from security projects, I would go with SECUIRTY.md.
</blockquote></details>

I also slightly prefer SECURITY.md.

___
___
*[`SECURITY.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBXtN1-vaAeVCToHu:-NjVQTSc8I6L-uXGXcFY:bo6h4u6) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L12)):*
> So, I vote for the current version.

+1. We actually don't have any sense of LTS versions/branches at present.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: 0 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBVbt4s8GIoWgl_oI:-NjgYPGJEc4Y_foaxx82:b-896fix) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Unfortunately this is misleading, because we also care about https://github.com/gramineproject/gramine/security, and that won't be there. GitHub renders only plaintext `SECURITY` and markdown `SECURITY.md` (and it can't even render the proper suffix of `SECURITY.markdown`, it insists on a suffix for https://en.wikipedia.org/wiki/Modula). This can't be .rst. 

See test repos:
- https://github.com/woju/test-security
  https://github.com/woju/test-security/security
- https://github.com/woju/test-security-md
  https://github.com/woju/test-security-md/security
- https://github.com/woju/test-security-markdown
  https://github.com/woju/test-security-markdown/security
- https://github.com/woju/test-security-rst
  https://github.com/woju/test-security-rst/security
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSMk-B6LrPo7KxBc3Q:-NjgWPYXBMffb9FcOO7n:b-896fix) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Maybe we can add link to SECURITY.md in README?

+1.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSSaUgACDmrE-nTQpf:-NjgWOiF8YbxNsoTY1e0:b-896fix) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I also slightly prefer SECURITY.md.
</blockquote></details>

Done.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjgYRAO9Fvw-2wvPFjU):*
Blocking myself: change to `.md`
___
*[`SECURITY.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSri15AvhOPMGtoijK:-NjgXiofDmlLQpCa4Zgp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> The Gramine team and community take security bugs in Gramine seriously.

Please don't. Literally every mail / announcement from corporations after they got hacked and all the user private data got leaked start with exactly this sentence, it became kind of a meme now and is associated with actually not caring about security but having a big PR department writing flowery statements.
I'd just drop this whole paragraph and replace with a single sentence somewhere later in the document saying that if the submission is correct, we'll acknowledge the reporter in the commit message. And also ask in that sentence for the preferred name / nick to put there.
</blockquote></details>

Done.
___
*[`SECURITY.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBXtN1-vaAeVCToHu:-NjgXmxzAoUs0YBgyM6t:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L12)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> So, I vote for the current version.

+1. We actually don't have any sense of LTS versions/branches at present.
</blockquote></details>

Done.
___
*[`SECURITY.rst` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjSBaSiACIGZTWePdT7:-NjgY8E_CU1RMh5BIXwy:b-mhujjy) ([raw file](https://github.com/gramineproject/gramine/blob/e49742ba700327ad36796e6c761f04b9985faa5e/SECURITY.rst#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> we want to know about bugs in subprojects which we statically link against

Yeah, but after they are confirmed by their maintainers. I don't think we'll be able (or rather, have time) to analyze a report for some mbedtls internals, and especially, to correctly fix it. @woju: Please keep in mind that a huge part of security and normal bug reports are bogus and we want to limit noise-to-signal ratio.

But I'm not blocking, this paragraph is not strictly needed because most security professionals already know this and comply to it.
</blockquote></details>

Done. Currently just removed it.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

**Review by kailun-qin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1653#-Njj-1Ut1AtDH61QlVlF):*
Now it's actually just a single paragraph, not the whole text, I'd make it a bit more precise here.

**Review by woju — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1653#-NjgYRAO9Fvw-2wvPFjU):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself: change to `.md`
</blockquote></details>

Done
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1653#-Njj-1Ut1AtDH61QlVlF):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now it's actually just a single paragraph, not the whole text, I'd make it a bit more precise here.
</blockquote></details>

Done

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1653)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
