### PR TITLE
improved CI-Examples lighttpd configuration for better performance 

### PR DESCRIPTION
**Pull request by nniryanb**
improved CI-Examples lighttpd configuration for better performance

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1640)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1640)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @nniryanb)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1640#-NiY8ETH5TPzl_dgdgsZ:-NiY8ETH5TPzl_dgdgs_:b-k5wz62) (no related file):*
@nniryanb Thanks for the PR!

However, I think we basically consider [CI-Examples](https://github.com/gramineproject/gramine/tree/master/CI-Examples) as the sample applications to demonstarte the usage/usability of Gramine and for CI testing (as the name implies), but not really for performance considerations/references.

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1640)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @nniryanb)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1640#-NiY8ETH5TPzl_dgdgsZ:-NiYg_JkEcomHS-ou4E_:b-1a88w2) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

@nniryanb Thanks for the PR!

However, I think we basically consider [CI-Examples](https://github.com/gramineproject/gramine/tree/master/CI-Examples) as the sample applications to demonstarte the usage/usability of Gramine and for CI testing (as the name implies), but not really for performance considerations/references.
</blockquote></details>

I agree with @kailun-qin.

We *could* update `lighttpd-generic.conf`, but only if you elaborate why these changes are required.

We definitely don't want to update `lighttpd.manifest.template`, because our examples are supposed to be debuggable (`sgx.debug = true`) and with minimal memory footprint (`sgx.enclave_size = "256M"`).

Also, I don't think `sgx.max_threads = 254` makes any sense -- isn't lighttpd **single-threaded**?

@nniryanb If you think these changes are relevant in some situations, I suggest to create a discussion under https://github.com/gramineproject/gramine/discussions and post your patch there, explaining why this is required and for what cases.

___
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1640#-NiYgWkpEh6wUj3kb0sW):*
Btw, there is no Makefile patch in this PR.

**Comment by nniryanb** [comment]
it simply maxes out at 300 to 400 concurrent connections and causes timeouts with the default settings, with this small change I got it to perform perfectly at 1000 concurrent GETs with less than 1 ms response times, nothing is wrong, simply an attempt to make the first experience of gramine better for the beginner.

**Comment by nniryanb** [comment]
and yes I reversed the Makefile edit, because the docs all point to 127.0.0.1, however it is best to assign a specific ip to bind to a specific network interface when testing.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1640)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @nniryanb)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1640#-NiY8ETH5TPzl_dgdgsZ:-Ni_GYjq5HzgPCxjEWdl:bjtx5bc) (no related file):*
> it simply maxes out at 300 to 400 concurrent connections and causes timeouts with the default settings, with this small change I got it to perform perfectly at 1000 concurrent GETs with less than 1 ms response times, nothing is wrong, simply an attempt to make the first experience of gramine better for the beginner.

Sure, I don't mind the changes in `lighttpd-generic.conf`. Would you be willing to fix the PR to keep only those changes, and also update the commit message with the explanation why these changes are beneficial (rewording of what you said above)?

___

**Comment by nniryanb** [comment]
nevermind.

**Pull request closed without merging**
