### PR TITLE
[LibOS] Add `fadvise64` syscall implementation

### PR DESCRIPTION
**Pull request by kailun-qin**
The original requirement is from https://github.com/gramineproject/gramine/issues/511.

In Gramine's threat model, `fadvise64()` is not required to do anything meaningful. Thus, only do sanity checks and simply implement all the others as no-op.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)

### CODE REVIEW

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5joXgi0om4n7fu1b9w):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What do you mean by "threat model"? We are not required to do anything because of that syscall semantics (which we emulate).
</blockquote></details>

The wording is a copy-paste from the initial issue. I can guess the intention but I think it's fine to just remove it to avoid any confusions.
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5juNNs4XEv9fzygypB):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would recommend reading point 7 from https://gramine.readthedocs.io/en/stable/devel/onboarding.html#fixing-a-bug (or the whole document). This commit is should be just squashed into the previous one it serves no purpose.
</blockquote></details>

Got it, thanks.
___
*[`libos/include/shim_table.h` line 162 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5jvZZDEaG45u0w19Xe:-N5mTsGY3ee2NY6EHFrN:bsleslz) ([raw file](https://github.com/gramineproject/gramine/blob/8184bd47eea53c2f8b607f59770c82525f45b0ef/libos/include/shim_table.h#L162)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wrong signature (type of `len`): https://elixir.bootlin.com/linux/latest/source/mm/fadvise.c#L212
</blockquote></details>

I just followed https://elixir.bootlin.com/linux/latest/source/mm/fadvise.c#L205, also the `posix_fadvise` signature in manpage. WDYT?
___
*[`libos/src/sys/shim_open.c` line 644 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5k42bgAg4jtuLYp6aI:-N5mVEE05W4MBLRjmGPJ:b102coi) ([raw file](https://github.com/gramineproject/gramine/blob/8184bd47eea53c2f8b607f59770c82525f45b0ef/libos/src/sys/shim_open.c#L644)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this check? This is not required by the kernel from what I can see.
</blockquote></details>

Yep indeed. Fixed.
___
*[`libos/src/sys/shim_open.c` line 647 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5jw7pk8-GzsmFib4Ri:-N5mWSqHEFJgvcrbf43o:b8vc0bo) ([raw file](https://github.com/gramineproject/gramine/blob/8184bd47eea53c2f8b607f59770c82525f45b0ef/libos/src/sys/shim_open.c#L647)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If you fix the signature this check won't be needed.
</blockquote></details>

I'll leave it for now and let you confirm the signature.
___
*[`libos/src/sys/shim_open.c` line 650 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5jwU1n41wZEhz78F5A:-N5mWhCF71Pi9anTMtWi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8184bd47eea53c2f8b607f59770c82525f45b0ef/libos/src/sys/shim_open.c#L650)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of having this as a separate function? Both functions (caller and callee) are small and this doesn't improve readability - just inline it
</blockquote></details>

Done.
___
*[`libos/src/sys/shim_open.c` line 658 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5k48GX2Y6O5PYtsRHo:-N5mcQkJ87PDIo8iAASM:b-ytfls8) ([raw file](https://github.com/gramineproject/gramine/blob/8184bd47eea53c2f8b607f59770c82525f45b0ef/libos/src/sys/shim_open.c#L658)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We need to check if it's really a file, not that it's not a pipe.
</blockquote></details>

Well, the intention was to check whether its a pipe, if so then -ESPIPE. (similar check for `fallocate`: https://github.com/gramineproject/gramine/blob/0a7112ab9a875c1618638465a6c2b50a5743d5bb/libos/src/sys/shim_open.c#L578, also see https://elixir.bootlin.com/linux/latest/source/mm/fadvise.c#L43)
___
*[`libos/src/sys/shim_open.c` line 662 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5jyFnR5bJG19WZAjSO:-N5mWoM4CJLMRaMDc-kX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8184bd47eea53c2f8b607f59770c82525f45b0ef/libos/src/sys/shim_open.c#L662)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (this comment makes no sense to me, as in commit message)
</blockquote></details>

Done.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/include/shim_table.h` line 162 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5jvZZDEaG45u0w19Xe:-N5o9RFp-WhSirMHCLTP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8184bd47eea53c2f8b607f59770c82525f45b0ef/libos/include/shim_table.h#L162)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin But your link refers to *another system call* called `fadvise64_64`. So I agree with Borys.
</blockquote></details>

Done.
___
*[`libos/src/sys/shim_open.c` line 647 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5jw7pk8-GzsmFib4Ri:-N5o9h3v9t17MKXk7V0Q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8184bd47eea53c2f8b607f59770c82525f45b0ef/libos/src/sys/shim_open.c#L647)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Borys, not needed
</blockquote></details>

Done.
___
*[`libos/src/sys/shim_open.c` line 628 at r2](https://reviewable.io/reviews/gramineproject/gramine/699#-N5nxiuQ7Wu-MnH1uRPM:-N5o9ahU9V-4OPJ9hBxo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/576c5b70159ebffc5d5a80a4fcefad3c8ee19c04/libos/src/sys/shim_open.c#L628)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`loff_t len` -> `size_t len`
</blockquote></details>

Done.
___
*[`libos/src/sys/shim_open.c` line 650 at r2](https://reviewable.io/reviews/gramineproject/gramine/699#-N5nySDH3f1si1TqSeSp:-N5o9kQ19EJXBviz9D2A:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/576c5b70159ebffc5d5a80a4fcefad3c8ee19c04/libos/src/sys/shim_open.c#L650)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add empty lines between separate code snippets (like different checks), otherwise it is hard to read.
</blockquote></details>

Done.
___
*[`libos/src/sys/shim_open.c` line 655 at r2](https://reviewable.io/reviews/gramineproject/gramine/699#-N5nyYu6562eVTvvXkkm:-N5oA2WY1JO7y69OCIE-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/576c5b70159ebffc5d5a80a4fcefad3c8ee19c04/libos/src/sys/shim_open.c#L655)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

First, we prefer to use `/* */`. Second, the sentence looks weird, I suggest a simple:
```
/* currently just a no-op */
```
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/gramineproject/gramine/699#-N69zYnF-SniAJZ9li9F):*
> Thus, only do sanity checks and simply implement all the others as no-op.

All the others what? I don't understand this sentence.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/gramineproject/gramine/699#-N69zYnF-SniAJZ9li9F):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Thus, only do sanity checks and simply implement all the others as no-op.

All the others what? I don't understand this sentence.
</blockquote></details>

Currently, we only implement sanity checks in`fadvise64`and the core logic is just a no-op (returning 0 directly). Please feel free to rephrase the commit message you think is more appropriate. Thanks!

**Review by dimakuv — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/699#-N5juNNs4XEv9fzygypB):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Got it, thanks.
</blockquote></details>

Done.
___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/gramineproject/gramine/699#-N69zYnF-SniAJZ9li9F):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Currently, we only implement sanity checks in`fadvise64`and the core logic is just a no-op (returning 0 directly). Please feel free to rephrase the commit message you think is more appropriate. Thanks!
</blockquote></details>

Done. I rephrased during the final rebase.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 3 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/699)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
