### PR TITLE
[LibOS] Allow setting `O_NONBLOCK` on not connected UNIX sockets

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
And some code clean ups.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/677)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/677)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/677#-N5EYbLBBiwyQe5p0J01):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you remind again why we talk only about UNIX sockets, even though the change is in a generic function `src/fs/socket/fs.c: set_flags()`?

Is it simply because `handle->pal_handle == NULL` can *only* happen on UNIX sockets?
</blockquote></details>

Yes, excatly. Maybe a comment is due, explaining that all implementations allowing `pal_handle` to be `NULL` should set the currently enabled flags when they instantiate `pal_handle`?
___
*[`libos/include/shim_fs.h` line 168 at r2](https://reviewable.io/reviews/gramineproject/gramine/677#-N5EX8kKAmK4juc0pj6J:-N5Fpl9s2142i1QCw9SM:bakd4q3) ([raw file](https://github.com/gramineproject/gramine/blob/fd0c88e23973f27ea72ca3e363943e4bcf36104f/libos/include/shim_fs.h#L168)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like that now we have `handle` name here, but `hdl` everywhere else in this file (and associated files with callback implementations). Maybe we should revert to `hdl` for uniformity, and have a proper separate PR will do this name change?

UPDATE: I see that you already have callback implementations with `handle`. So we already have a non-uniformity. Resolving.
</blockquote></details>

I just dislike `hdl` so I use `handle` in the new code I write. I wouldn't create a PR just for this rename, it would touch half of the LibOS code...
___
*[`libos/src/net/unix.c` line 136 at r2](https://reviewable.io/reviews/gramineproject/gramine/677#-N5EZhUi0h32FHv9fCPA:-N5Fqjz08yD0GyUY9cGw:bo1s579) ([raw file](https://github.com/gramineproject/gramine/blob/fd0c88e23973f27ea72ca3e363943e4bcf36104f/libos/src/net/unix.c#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I always have to pause and think about this comment. Maybe

`so this is race-free` -> ```so using `options` when creating the socket below is race-free ```
</blockquote></details>

Slightly reworded, let me know it it looks ok
___
*[`libos/src/net/unix.c` line 245 at r2](https://reviewable.io/reviews/gramineproject/gramine/677#-N5EZzw83L3v-rest_8d:-N5FqnkaCg6EL3-OggvK:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/fd0c88e23973f27ea72ca3e363943e4bcf36104f/libos/src/net/unix.c#L245)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I always have to pause and think about this comment. Maybe

`so this is race-free` -> ```so using `options` when creating the socket below is race-free ```
</blockquote></details>

ditto
___
*[`libos/src/sys/shim_fcntl.c` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/677#-N5Ea5fWDkJmN0jJjPlf:-N5FqvS69mCWTJHcjRMT:bk7ncr4) ([raw file](https://github.com/gramineproject/gramine/blob/fd0c88e23973f27ea72ca3e363943e4bcf36104f/libos/src/sys/shim_fcntl.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Incorrect in the sense that this has no "handle-specific" logic (like updating PAL handle's attributes and doing additional locking)?

I agree that this looks incorrect and hopefully is never used (instead the handle-specific callback is always used).
</blockquote></details>

Just that it only saves the value, doesn't actually **do** anything with it. For some handles and some flags it's probably fine (e.g. because code using them always check them), but generally sounds incorrect. IMO each handle type should have it's own callback and deal with these options as it wishes (then just memorizing them would be fine)>
___
*[`libos/src/sys/shim_pipe.c` line 58 at r2](https://reviewable.io/reviews/gramineproject/gramine/677#-N5EYMqH2W_vDi7Y3sfz:-N5FrGG4AtLCnSkY2Uzr:b-fmsmep) ([raw file](https://github.com/gramineproject/gramine/blob/fd0c88e23973f27ea72ca3e363943e4bcf36104f/libos/src/sys/shim_pipe.c#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You just simplified it because who cares about modifications to `srv` and `cli` out arguments if this func anyway returns an error?
</blockquote></details>

This function is always used on newly created handles. I'm not sure why it doesn't create them itself, why does it take them as arguments (and populate).
Generally I think that having a function which initializes part of an already half initialized object is a bad smell (unless the initial object was fully initialized, the function just changes parts of it and all failures are fatal, i.e. the object is destroyed)>

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/677)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/677)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/src/fs/pipe/fs.c` line 216 at r1](https://reviewable.io/reviews/gramineproject/gramine/677#-N5B6kIX3Irka1UcluP2:-N5Fx183AbBCwpKoowgW:b-rpahry) ([raw file](https://github.com/gramineproject/gramine/blob/f0e82493b00facf778a82f23d987da93c8e60d9b/libos/src/fs/pipe/fs.c#L216)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

FYI: this was a bug.
</blockquote></details>

:grimacing: 
___
*[`libos/src/fs/pipe/fs.c` line 192 at r3](https://reviewable.io/reviews/gramineproject/gramine/677#-N5FwicU7X_lXtghULeQ:-N5FwicU7X_lXtghULeR:b-sobsqn) ([raw file](https://github.com/gramineproject/gramine/blob/42629f613d31cc2d00351049137cefb6d1d38e01/libos/src/fs/pipe/fs.c#L192)):*
> ```C
>     }
> 
>     handle->flags = (handle->flags & ~mask) | flags;
> ```

Not sure if it matters, but `handle->flags` is still `int` (i.e. signed, and different than the types you used here).
___
*[`libos/src/sys/shim_fcntl.c` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/677#-N5Ea5fWDkJmN0jJjPlf:-N5FzGOY5dDrEao4Ilbe:bntf3an) ([raw file](https://github.com/gramineproject/gramine/blob/fd0c88e23973f27ea72ca3e363943e4bcf36104f/libos/src/sys/shim_fcntl.c#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Just that it only saves the value, doesn't actually **do** anything with it. For some handles and some flags it's probably fine (e.g. because code using them always check them), but generally sounds incorrect. IMO each handle type should have it's own callback and deal with these options as it wishes (then just memorizing them would be fine)>
</blockquote></details>

Could you add this explanation to the comment?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/677)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/pipe/fs.c` line 192 at r3](https://reviewable.io/reviews/gramineproject/gramine/677#-N5FwicU7X_lXtghULeQ:-N5G9_BX9ciMlWGFPvaA:bhcpoay) ([raw file](https://github.com/gramineproject/gramine/blob/42629f613d31cc2d00351049137cefb6d1d38e01/libos/src/fs/pipe/fs.c#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not sure if it matters, but `handle->flags` is still `int` (i.e. signed, and different than the types you used here).
</blockquote></details>

The highest bit cannot be ever set, so it does not. We should change it to `unsigned int`, but not in this PR.
___
*[`libos/src/sys/shim_fcntl.c` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/677#-N5Ea5fWDkJmN0jJjPlf:-N5GAebY93hBS6b2e89m:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fd0c88e23973f27ea72ca3e363943e4bcf36104f/libos/src/sys/shim_fcntl.c#L35)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add this explanation to the comment?
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/677)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`libos/src/fs/pipe/fs.c` line 192 at r3](https://reviewable.io/reviews/gramineproject/gramine/677#-N5FwicU7X_lXtghULeQ:-N5GC3ZsDfoXOCxAitlG:b7h8ijt) ([raw file](https://github.com/gramineproject/gramine/blob/42629f613d31cc2d00351049137cefb6d1d38e01/libos/src/fs/pipe/fs.c#L192)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The highest bit cannot be ever set, so it does not. We should change it to `unsigned int`, but not in this PR.
</blockquote></details>

yeah, I know, it's more like a stylistic issue ;)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/677)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Pull request merged**
