### PR TITLE
[PAL/Linux-SGX] Split `host_enclave.[c|h]` into two

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, `host_enclave.[c|h]` contained both ECALLs and OCALLs. This PR splits the file into `host_ecalls.[c|h]` and `host_ocalls.c`.

Also, this PR removes useless ODEBUG/EDEBUG macros.

## How to test this PR? 

CI is enough.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/737)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/737)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_ecalls.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/737#-N6Yu0Mu8DEO4p-9gnOh:-N6Yu0Mu8DEO4p-9gnOi:bloymvs) ([raw file](https://github.com/gramineproject/gramine/blob/2df7f5b8bf55a6b72d1cbff551f1b6b3b4aef067/pal/src/host/linux-sgx/host_ecalls.c#L19)):*
> ```C
> rpc_queue_t* g_rpc_queue = NULL; /* pointer to untrusted queue */
> 
> static int rpc_thread_loop(void* arg) {
> ```

Wait, rpc threads handle ocalls, why this is in `host_ecalls.c`?
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/737#-N6YuH9wAidCfu4vmkWL:-N6YuH9wAidCfu4vmkWM:b-tm7ytt) ([raw file](https://github.com/gramineproject/gramine/blob/2df7f5b8bf55a6b72d1cbff551f1b6b3b4aef067/pal/src/host/linux-sgx/host_ocalls.c#L18)):*
> ```C
> #include "cpu.h"
> #include "debug_map.h"
> #include "host_ecalls.h"
> ```

Why ocalls need ecalls header?

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/737)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/737)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_ecalls.c` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/737#-N6gwwW_3Nr7JQofS7IF:-N6gwwW_3Nr7JQofS7IG:b-p0lr3k) ([raw file](https://github.com/gramineproject/gramine/blob/18f2e9d7c9d94366900b7f426248405ed812a579/pal/src/host/linux-sgx/host_ecalls.c#L8)):*
> ```C
> #include <asm/errno.h>
> #include <linux/futex.h>
> #include <linux/signal.h>
> ```

Hmm, most of these aren't needed anymore?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/737)* status: 6 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/host_ecalls.c` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/737#-N6gwwW_3Nr7JQofS7IF:-N6h1VfRENEpzpeIQwxt:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/18f2e9d7c9d94366900b7f426248405ed812a579/pal/src/host/linux-sgx/host_ecalls.c#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, most of these aren't needed anymore?
</blockquote></details>

Done

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/737)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
