### PR TITLE
[PAL/Linux-SGX,Docs] Update comments after the recent file renamings

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Seems we forgot that.

## How to test this PR? 

Just read the comments and verify.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1970)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1970)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1970#-O48tk5q3qnH__EAPdyD:-O48tk5q3qnH__EAPdyE:b-r4ex7m) ([raw file](https://github.com/gramineproject/gramine/blob/7edbbd5645925baa0dcf03cb4fbc94c985011a1b/pal/src/host/linux-sgx/host_exception.c#L16)):*
> ```C
>                      * ../../../include/arch/x86_64/linux/ucontext.h:136:5: error: unknown type name ‘__sigset_t’
>                      *      __sigset_t uc_sigmask;
>                      */
> ```

I think this FIXME is also stale now?



_Code quote:_
```C
#include "sigset.h" /* FIXME: this include can't be sorted, otherwise we get:
                     * In file included from host_exception.c:19:0:
                     * ../../../include/arch/x86_64/linux/ucontext.h:136:5: error: unknown type name ‘__sigset_t’
                     *      __sigset_t uc_sigmask;
                     */
```

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1970)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1970#-O49QU6q6KUsGbbmDlVV):*
Not so "recent" already, but ok
___
*[`pal/src/host/linux-sgx/host_exception.c` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1970#-O48tk5q3qnH__EAPdyD:-O49Qv0cCophtLhzp3Ei:bc195pd) ([raw file](https://github.com/gramineproject/gramine/blob/7edbbd5645925baa0dcf03cb4fbc94c985011a1b/pal/src/host/linux-sgx/host_exception.c#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think this FIXME is also stale now?
</blockquote></details>

Worked for me too (sorting `sigset.h`). @mkow Could you then fix this?

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1970)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1970)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1970)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
