### PR TITLE
Lowercase "LibOS", "Pal" and "Scripts"

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
I've split the commit in two parts (2nd is a fixup for convenience of merging): 
1. Rename. This I recommend reviewing manually in your favorite command line. Then mark all files from this commit as reviewed in reviewable (this can be done with `X` - capital x - to mark all files as reviewed and then the big button at the top "next unreviewed diff").
2. All other changes (mainly paths fixups due to rename0. This commit can be easily reviewed in reviewable.

I changed the mode to commit-by-commit review, so above should be easy.
Well, if you are brave enough, don't use reviewable at all - it doesn't handle so many files well.

## How to test this PR? 
CI should be enough.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/672)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 630 of 630 files at r1, 60 of 60 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/672)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/672#-N579n2z1XWTWEUUaqUi:-N579n3-716br2HVtUoz:b-km9cs3) (no related file):*
I think we should also update `CONTRIBUTING.rst` - it now says "Should include which component was changed (Pal-{Linux,SGX} / LibOS / Docs / CI)" - we probably want to say now "PAL"? That's the correct casing of this component name, we used "Pal" only because of that weird directory name.

___

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/672)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/672)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/672)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
