### PR TITLE
[PAL,LibOS,common] PAL_ERROR should always be negative

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Expect PAL_ERROR to be negative.
Followup of https://github.com/gramineproject/gramine/pull/1900 .

## How to test this PR? 

CI/CD.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jJl-y3OIK1com1Cpn):*




_Suggestion:_
```
always
```
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jJmYdC_T2NqhZypki):*
missing verb - you need to describe what the commit actually changes, fact statements are not clear whether they describe the situation before the commit or after it (or both)
___
*[`libos/include/libos_internal.h` line 148 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jK98i-osFZpd2h76T:-O3jK98i-osFZpd2h76U:b-7pc40b) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/libos/include/libos_internal.h#L148)):*
> ```objc
>  * \brief Translate PAL error code into UNIX error code.
>  */
> int pal_to_unix_errno(long err);
> ```

Why `long` -> `int` change? I'm not sure what is the best here, but I also don't understand why you changed it.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jJmYdC_T2NqhZypki):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing verb - you need to describe what the commit actually changes, fact statements are not clear whether they describe the situation before the commit or after it (or both)
</blockquote></details>

+1

I would change to `Enforce that PAL_ERROR is always negative`
___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kaddb-g3XaSV637c-:-O3kaddb-g3XaSV637c0:bulgglg) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/common/src/crypto/adapters/mbedtls_adapter.c#L27)):*
> ```C
> 
> static int mbedtls_to_pal_error(int error) {
>     assert(error <= 0);
> ```

This looks a bit unrelated. I would add this in the commit body message as "Also, this commit adds an assert on mbedTLS errors being negative."
___
*[`libos/include/libos_internal.h` line 148 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jK98i-osFZpd2h76T:-O3kan9KCq-RIXBKVK2b:bun3l6k) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/libos/include/libos_internal.h#L148)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why `long` -> `int` change? I'm not sure what is the best here, but I also don't understand why you changed it.
</blockquote></details>

Yes, I would also keep `long` here.
___
*[`libos/src/libos_init.c` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kbLzu4OUQ5SmafNzk:-O3kbLzu4OUQ5SmafNzl:bcqfrdy) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/libos/src/libos_init.c#L78)):*
> ```C
>     assert(err <= 0);
>     unsigned long perr = -err;
>     return (perr < PAL_ERROR_NATIVE_COUNT) ? pal_errno_to_unix_errno_table[perr] : -EINVAL;
> ```

Actually, I wonder why we have this if check. I would imagine that having a PAL error that is "outside of PAL-error-codes range" should be treated as a programmer error, i.e. I would add an assert here.

This may be for a follow-up PR, but I would like to discuss this and agree on some action first.
___
*[`pal/src/host/linux-sgx/pal_linux_error.h` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kbqUP4VdWWHGmKjaD:-O3kbqUP4VdWWHGmKjaE:bgamkay) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/pal/src/host/linux-sgx/pal_linux_error.h#L1)):*
> ```objc
> #pragma once
> ```

Isn't this file 100% the same as the previous file?

Let's move them to https://github.com/gramineproject/gramine/tree/master/pal/include/host/linux-common.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kaddb-g3XaSV637c-:-O3kc_Gr9ESCYWXnaxmH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/common/src/crypto/adapters/mbedtls_adapter.c#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks a bit unrelated. I would add this in the commit body message as "Also, this commit adds an assert on mbedTLS errors being negative."
</blockquote></details>

Done.
___
*[`libos/include/libos_internal.h` line 148 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jK98i-osFZpd2h76T:-O3kYiEA7szoSy_-FnB5:bugihje) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/libos/include/libos_internal.h#L148)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why `long` -> `int` change? I'm not sure what is the best here, but I also don't understand why you changed it.
</blockquote></details>

From the C standard ([https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf)):
```
errno expands to a modifiable lvalue of type int.
```

Ofc it's a little bit more complex in `errno.h` to ensure the thread safty.
However, functions like strerror(3) also expect int.

Therefore, I figured out that if we return an "errno" we want to return a type that represents `errno`.

However, we are not strictly bound to this. So, if you see a good reason to keep it as `long`, I will drop this change.

**Review by dimakuv — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/include/libos_internal.h` line 148 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jK98i-osFZpd2h76T:-O3kh95x-swyIBhNeic0:bc1gmn2) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/libos/include/libos_internal.h#L148)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

From the C standard ([https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf)):
```
errno expands to a modifiable lvalue of type int.
```

Ofc it's a little bit more complex in `errno.h` to ensure the thread safty.
However, functions like strerror(3) also expect int.

Therefore, I figured out that if we return an "errno" we want to return a type that represents `errno`.

However, we are not strictly bound to this. So, if you see a good reason to keep it as `long`, I will drop this change.
</blockquote></details>

Ok, the explanation makes sense to me, resolving.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: 3 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jJmYdC_T2NqhZypki):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1

I would change to `Enforce that PAL_ERROR is always negative`
</blockquote></details>

Done.
___
*[`libos/src/libos_init.c` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kbLzu4OUQ5SmafNzk:-O3kdjt75L-8Ooya-BTc:beyb0qv) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/libos/src/libos_init.c#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, I wonder why we have this if check. I would imagine that having a PAL error that is "outside of PAL-error-codes range" should be treated as a programmer error, i.e. I would add an assert here.

This may be for a follow-up PR, but I would like to discuss this and agree on some action first.
</blockquote></details>

Ok, added todo's.
___
*[`pal/src/host/linux-sgx/pal_linux_error.h` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kbqUP4VdWWHGmKjaD:-O3keGNy-QmQZhwEi5m2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/pal/src/host/linux-sgx/pal_linux_error.h#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't this file 100% the same as the previous file?

Let's move them to https://github.com/gramineproject/gramine/tree/master/pal/include/host/linux-common.
</blockquote></details>

Done.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: 3 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jJl-y3OIK1com1Cpn):*
Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow)

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/src/libos_init.c` line 76 at r3](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kznc_9FqfoUU34Hfe:-O3kznc_9FqfoUU34Hff:bmo0viq) ([raw file](https://github.com/gramineproject/gramine/blob/8b6410a8ca1d8986c2320b8b7cb8b2883f8a67e2/libos/src/libos_init.c#L76)):*
> ```C
> 
> int pal_to_unix_errno(long err) {
>     assert(err <= 0);
> ```

hmm... why not `assert(err < 0)` (in the commit msg, we also have "Enforce that `PAL_ERROR` is always **negative**)?



_Code quote:_
```C
assert(err <= 0);
```

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/libos_init.c` line 76 at r3](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kznc_9FqfoUU34Hfe:-O3l3Gcb2L_Rr8TgA4ZO:b9vm1o4) ([raw file](https://github.com/gramineproject/gramine/blob/8b6410a8ca1d8986c2320b8b7cb8b2883f8a67e2/libos/src/libos_init.c#L76)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

hmm... why not `assert(err < 0)` (in the commit msg, we also have "Enforce that `PAL_ERROR` is always **negative**)?
</blockquote></details>

`PAL_ERROR_SUCCESS` is 0.
We are ensuring that errors are negative, however, the SUCCESS still is 0.

Does changing commit-msg to:
```
Enforce that PAL_ERROR errors are always negative
```
Makes more sense?

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/src/libos_init.c` line 76 at r3](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kznc_9FqfoUU34Hfe:-O3l56BpECQF-t-sjqKQ:bxus0vf) ([raw file](https://github.com/gramineproject/gramine/blob/8b6410a8ca1d8986c2320b8b7cb8b2883f8a67e2/libos/src/libos_init.c#L76)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

`PAL_ERROR_SUCCESS` is 0.
We are ensuring that errors are negative, however, the SUCCESS still is 0.

Does changing commit-msg to:
```
Enforce that PAL_ERROR errors are always negative
```
Makes more sense?
</blockquote></details>

Yeah, I'm also fine w/ changing the commit msg if we do have in our code base that we call `pal_to_unix_errno(PAL_ERROR_SUCCESS)` (well in general, I think we control our code and I'm not sure that's the intended way of usage).

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/libos_init.c` line 76 at r3](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kznc_9FqfoUU34Hfe:-O3lAlhuC-GH9zlEUUbc:bctoysr) ([raw file](https://github.com/gramineproject/gramine/blob/8b6410a8ca1d8986c2320b8b7cb8b2883f8a67e2/libos/src/libos_init.c#L76)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yeah, I'm also fine w/ changing the commit msg if we do have in our code base that we call `pal_to_unix_errno(PAL_ERROR_SUCCESS)` (well in general, I think we control our code and I'm not sure that's the intended way of usage).
</blockquote></details>

@kailun-qin Yes, we have such places in our codebase, and I consider it Ok to call like this.

**Review by kailun-qin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/libos_init.c` line 76 at r3](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3kznc_9FqfoUU34Hfe:-O3lBkHR4Ir6DsKMafwq:bo7fbwc) ([raw file](https://github.com/gramineproject/gramine/blob/8b6410a8ca1d8986c2320b8b7cb8b2883f8a67e2/libos/src/libos_init.c#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin Yes, we have such places in our codebase, and I consider it Ok to call like this.
</blockquote></details>

thanks, I'm unblocking then

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: all files reviewed, all discussions resolved, "squash! " found in commit messages' one-liners

___
*[`libos/include/libos_internal.h` line 148 at r1](https://reviewable.io/reviews/gramineproject/gramine/1961#-O3jK98i-osFZpd2h76T:-O3m0zyM5QXq4NfiYhGJ:b-tchytk) ([raw file](https://github.com/gramineproject/gramine/blob/54e0be6a56befd257d59a8e30d9146b5af014e9a/libos/include/libos_internal.h#L148)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, the explanation makes sense to me, resolving.
</blockquote></details>

Ah, it makes sense then, resolving.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
