### PR TITLE
[Docs] Add a page with description and link to CCZoo

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

CCZoo is an Intel-backed project that collects end-to-end confidential computing solutions. Many of these solutions build on top of Gramine.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3WWYsJD-r6GlVWfufV:bv2119f) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
> Some of the solutions are also validated on the public cloud services

"validated"? Is this a typo/wrong word?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/625#-N3Ut3k3D3TG6wkLw4f_:-N3Y40x3BXePKZ6VEDT3:brrx3ag) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

cczoo might want to fix their links to our quickstart to `/en/stable`, possibly after we sort out the #624.
</blockquote></details>

@RodgerZhu Could you do that? Woju is talking about this: https://cczoo.readthedocs.io/en/latest/LibOS/libos.html?highlight=gramine#gramine-official-link.

In that page, you have links like `https://gramine.readthedocs.io/en/latest/quickstart.html`. But we want to promote the "stable" version of Gramine now (which is currently v1.2), so the link should be `https://gramine.readthedocs.io/en/stable/quickstart.html`.

___
___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3Y4V5nEEXgG_OFwYjG:bc5l5zl) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Some of the solutions are also validated on the public cloud services

"validated"? Is this a typo/wrong word?
</blockquote></details>

This is taken from the CCZoo README: https://github.com/intel/confidential-computing-zoo/blob/main/README.md

What is the problem with this word? In this context, it means that "solutions/tutorials were validated to run correctly on a MS Azure public cloud, some other cloud, etc". Or you prefer some other word like `verified`/`confirmed`/`checked`?

**Comment by RodgerZhu** [comment]
> 

Hi @dimakuv  @woju , as I can't open Reviewable because of network blocking issue. So, I reply to the comments directly here.
I've updated all related links to the stable version.  Please check here: https://cczoo.readthedocs.io/en/latest/LibOS/libos.html#gramine-official-link

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/625#-N3Ut3k3D3TG6wkLw4f_:-N3YOBpj7WZuFG_So6wQ:bons3vm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@RodgerZhu Could you do that? Woju is talking about this: https://cczoo.readthedocs.io/en/latest/LibOS/libos.html?highlight=gramine#gramine-official-link.

In that page, you have links like `https://gramine.readthedocs.io/en/latest/quickstart.html`. But we want to promote the "stable" version of Gramine now (which is currently v1.2), so the link should be `https://gramine.readthedocs.io/en/stable/quickstart.html`.
</blockquote></details>

@woju Please note that @rodgerzhu did this already. Thanks @rodgerzhu !

___

**Review by woju — APPROVED** [review]
thanks!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625#-:-N3YxJwPBBvo2wICWd6q:bd5l6mr)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/625#-N3Ut3k3D3TG6wkLw4f_:-N3YxM7b5lHu8CMJYNDW:b-hrtzrn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Please note that @rodgerzhu did this already. Thanks @rodgerzhu !
</blockquote></details>

I think there's one occurence left:
```
documents/readthedoc/docs/source/Solutions/tensorflow-serving-cluster/index.rst:127:- Gramine. Follow `Quick Start <https://gramine.readthedocs.io/en/latest/quickstart.html>`__
```
but this is just what grep found, I didn't read the document so it's possibly warranted. I'm unblocking,

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/625#-N3Ut3k3D3TG6wkLw4f_:-N3Z-1pu6bqyfdHUIAdF:bwm3u0h) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I think there's one occurence left:
```
documents/readthedoc/docs/source/Solutions/tensorflow-serving-cluster/index.rst:127:- Gramine. Follow `Quick Start <https://gramine.readthedocs.io/en/latest/quickstart.html>`__
```
but this is just what grep found, I didn't read the document so it's possibly warranted. I'm unblocking,
</blockquote></details>

@rodgerzhu Could you fix that last occurence too?

___

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3ZKLO31_tb2e56ZHNM:b-ybxdws) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is taken from the CCZoo README: https://github.com/intel/confidential-computing-zoo/blob/main/README.md

What is the problem with this word? In this context, it means that "solutions/tutorials were validated to run correctly on a MS Azure public cloud, some other cloud, etc". Or you prefer some other word like `verified`/`confirmed`/`checked`?
</blockquote></details>

I'd prefer "verified" or "checked", "validated" doesn't seem to work here well and I wasn't sure what you mean by it.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3Zlqvf9rE8UxAgRAvt:bco5z6p) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer "verified" or "checked", "validated" doesn't seem to work here well and I wasn't sure what you mean by it.
</blockquote></details>

Done. Chose "verified."

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3Zx2gABpHgWXVlYOuZ:bc1n4zf) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Chose "verified."
</blockquote></details>

@mkow "Validated" is a formal term and means checking if the solution (mostly its specification) meets some not-so-technical "customer requirements" (itself a term you may have heard), i.e. if this program will be useful to solve some problem. This is opposed to "verified" which is checking if the implementation matches some technical specification (without consideration if the spec is actually useful to anyone). Those are not to be mixed. It's parallel to "authentication" vs "authorization". In this case, I believe "validated" was correct.

https://en.wikipedia.org/wiki/Verification_and_validation

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3aOlP3B9M-bG8A3d6K:b-4j9dc9) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju: According to your own definition it should be "verified" here. What @dimakuv means (and see his explanation above) is that someone ran this on the listed platforms and confirmed that it indeed works. It's purely technical thing whether these examples run correctly on platform XYZ.
</blockquote></details>

Nope, they were checking if they can sell a solution of "gramine as deployed on Azure". Validation is perfectly fine there. And it's not my definition, it's IEEE.

**Comment by RodgerZhu** [comment]
> 

Good Catch @woju !
Thanks @dimakuv  @woju   @mkow .
I'm sure all the links are stable versions now.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3cNfLRAtOd0TNZ0bXW:b-nhg6td) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Nope, they were checking if they can sell a solution of "gramine as deployed on Azure". Validation is perfectly fine there. And it's not my definition, it's IEEE.
</blockquote></details>

Based on the info provided by Woju, I agree with him -- `validated` sounds like a more correct term.

But if we have a problem with both `validated` and `verified`, maybe I'll replace with a more vague `checked`?

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3cvJJBBiMP3che26SM:ba29dyl) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Based on the info provided by Woju, I agree with him -- `validated` sounds like a more correct term.

But if we have a problem with both `validated` and `verified`, maybe I'll replace with a more vague `checked`?
</blockquote></details>

+1 to "checked"

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3cyuCnDAt7ITpZ5Ln4:bd3vwag) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to "checked"
</blockquote></details>

Done. Replaced with `checked`.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — DISMISSED** [review]
LGTM, thanks.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625#-:-N3e1kcI-o5eALdfmgvT:b2c0zco)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/625#-N3Ut3k3D3TG6wkLw4f_:-N3e1mnw20LUt8TTbY_O:b93hkmg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@rodgerzhu Could you fix that last occurence too?
</blockquote></details>

It's fixed now.

___
___
*[`Documentation/tutorials/cczoo/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/625#-N3WWYsI28gGa_Bzhmij:-N3e1GqO1BXpBoLLHOuM:b-s6a9ba) ([raw file](https://github.com/gramineproject/gramine/blob/f42978fc53a25ef1b916f34124a40124ab54772a/Documentation/tutorials/cczoo/index.rst#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Replaced with `checked`.
</blockquote></details>

"Checked" is OK. Also OK is general term "tested", which spans both verifying and validating. Validating is closely related to "acceptance testing" (and the details are far over what we're doing here).

I'll resolve this.

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/625)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
