### PR TITLE
Fix available memory accounting

### LINKED ISSUE #1017: [LibOS] `g_allocated_pages` integer overflow
### Description of the problem

During `clone` and `execve` flow, `g_allocated_pages` which traces allocated enclave memory get integer overflow. So there is a penitential bug in new VMA Bookkeep, though it doesn't break cases.
I also checked the commit just before VMA Bookkeep rework, this issue doesn't exist.

### Steps to reproduce

Add a log ` log_error("g_allocated_pages = %#lx, size = %#lx", g_allocated_pages, size);` after
https://github.com/gramineproject/gramine/blob/f01b21540c46e43ddd5a6c5cc46ef900b13e09ad/pal/src/host/linux-sgx/pal_memory.c#L63
then build and install Gramine.

Build `CI-Examples/bash` with all log.
Run `gramine-sgx bash` then type `ls` to trigger syscall `clone` and `execve`.

### Expected results

All logs in `error: g_allocated_pages = ?, size = ?`, `g_allocated_pages`  are positive as signed int.

### Actual results

```
[P2:T2:bash] trace: ---- execve("/bin/ls", [ls,], [LD_LIBRARY_PATH=/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu,PWD=/,]) ...
error: g_allocated_pages = 0x96d, size = 0x5000
error: g_allocated_pages = 0x968, size = 0x5000
error: g_allocated_pages = 0x963, size = 0x5000
.......
error: g_allocated_pages = 0x213, size = 0x104000
error: g_allocated_pages = 0x14, size = 0x1ff000
error: g_allocated_pages = 0x10, size = 0x4000
error: g_allocated_pages = 0x7, size = 0x9000
error: g_allocated_pages = 0xfffffffffffffffd, size = 0xa000
error: g_allocated_pages = 0xfffffffffffffffc, size = 0x1000
error: g_allocated_pages = 0xffffffffffffffbc, size = 0x40000
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x1000
[P2:T2:ls] debug: loading "file:/bin/ls"
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x5000
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x5000
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x5000
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x5000
[P2:T2:ls] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
```

### Gramine commit hash

181fb270826a8cbe924d5caba59107e8b26f56c7

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
See each commit.
Fixes #1017

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)* status: 0 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`libos/src/bookkeep/libos_vma.c` line 1575 at r3](https://reviewable.io/reviews/gramineproject/gramine/1036#-NGZME3J7KJ_kJGc3PJA:-NGZME3KEFxu_N1nEZRk:bk4wspu) ([raw file](https://github.com/gramineproject/gramine/blob/b194bc3c233b98edd3850323ba11d69caef13e2b/libos/src/bookkeep/libos_vma.c#L1575)):*
> ```C
>     /* This memory accounting is just a simple heuristic, which does not account swap, reserverd
>      * memory, unmapped VMAs etc. */
>     return MIN(total_memory_size, g_pal_public_state->mem_total);
> ```

IDK what to do with this, it's not real memory used, but virtual address space, but Gramine uses it as the former.
___
*[`libos/src/fs/proc/info.c` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1036#-NGZLzap4FVdwmEMY1Fi:-NGZLzap4FVdwmEMY1Fj:b8ojy7i) ([raw file](https://github.com/gramineproject/gramine/blob/89dc8548b110383a456a2cff1aae603f454e459f/libos/src/fs/proc/info.c#L41)):*
> ```C
>     } meminfo[] = {
>         { "MemTotal:      %8lu kB\n", g_pal_public_state->mem_total / 1024 },
>         { "MemFree:       %8lu kB\n", free_mem / 1024 },
> ```

This makes no sense, we use total sum of virtual memory as actually consumed memory...

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 14 of 14 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/src/bookkeep/libos_vma.c` line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_pD0jBEK9KlNxEn16:-NG_pD0jBEK9KlNxEn17:bx1y2rd) ([raw file](https://github.com/gramineproject/gramine/blob/47f5f53cae31bd869cc583be4334a2489a3df1de/libos/src/bookkeep/libos_vma.c#L269)):*
> ```C
> 
>             avl_tree_insert(&vma_tree, &new_vma->tree_node);
>             total_memory_size_sub(end - begin);
> ```

FYI: This is the case where the to-be-removed memory region is completely *inside* the region of `vma`.
___
*[`libos/src/bookkeep/libos_vma.c` line 271 at r1](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_p6jm-tAcI79Y4zDr:-NG_p6jm-tAcI79Y4zDs:bs9el4j) ([raw file](https://github.com/gramineproject/gramine/blob/670cc12609520d01ca4e73af37d57f975faa215d/libos/src/bookkeep/libos_vma.c#L271)):*
> ```C
> 
>             avl_tree_insert(&vma_tree, &new_vma->tree_node);
>             total_memory_size_add(new_vma->end - new_vma->begin);
> ```

Strange, this was completely bogus?
___
*[`libos/src/bookkeep/libos_vma.c` line 274 at r1](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_pStC5C5LOOqdPbKY:-NG_pStC5C5LOOqdPbKZ:b-lug0ne) ([raw file](https://github.com/gramineproject/gramine/blob/47f5f53cae31bd869cc583be4334a2489a3df1de/libos/src/bookkeep/libos_vma.c#L274)):*
> ```C
>         }
> 
>         total_memory_size_sub(vma->end - begin);
> ```

FYI: This is the case when there is an overlap of to-be-removed memory region with the region of `vma`:
```
|--- vma ---|
    |--- to-be-removed region ---|
```
___
*[`libos/src/bookkeep/libos_vma.c` line 304 at r1](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_qWIR9qIYIeldbgbn:-NG_qWIR9qIYIeldbgbo:b-91w4n9) ([raw file](https://github.com/gramineproject/gramine/blob/47f5f53cae31bd869cc583be4334a2489a3df1de/libos/src/bookkeep/libos_vma.c#L304)):*
> ```C
>             vma->offset += end - vma->begin;
>         }
>         total_memory_size_sub(end - vma->begin);
> ```

FYI: This is the case where region of `vma` exceeds the `end` address.
___
*[`libos/src/bookkeep/libos_vma.c` line 905 at r1](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_qr7q8JmHp-kLrnH_:-NG_qr7q8JmHp-kLrnHa:bp7vhn2) ([raw file](https://github.com/gramineproject/gramine/blob/670cc12609520d01ca4e73af37d57f975faa215d/libos/src/bookkeep/libos_vma.c#L905)):*
> ```C
> 
>         avl_tree_insert(&vma_tree, &new_vma1->tree_node);
>         total_memory_size_add(new_vma1->end - new_vma1->begin);
> ```

We remove these calls because here we're just changing protections, so it should not result in any change in the total memory size?
___
*[`libos/src/bookkeep/libos_vma.c` line 1573 at r3](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_rVRJCRYKspgNiWYB:-NG_rVRKAkiZR9LBxzae:b-etg3vt) ([raw file](https://github.com/gramineproject/gramine/blob/b194bc3c233b98edd3850323ba11d69caef13e2b/libos/src/bookkeep/libos_vma.c#L1573)):*
> ```C
>     size_t total_memory_size = g_total_memory_size;
>     spinlock_unlock(&vma_tree_lock);
>     /* This memory accounting is just a simple heuristic, which does not account swap, reserverd
> ```

typo: should be `reserved`
___
*[`libos/src/bookkeep/libos_vma.c` line 1575 at r3](https://reviewable.io/reviews/gramineproject/gramine/1036#-NGZME3J7KJ_kJGc3PJA:-NG_r62T3SD7Umlg_3z-:b2yklqo) ([raw file](https://github.com/gramineproject/gramine/blob/b194bc3c233b98edd3850323ba11d69caef13e2b/libos/src/bookkeep/libos_vma.c#L1575)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IDK what to do with this, it's not real memory used, but virtual address space, but Gramine uses it as the former.
</blockquote></details>

Whatever... Well, maybe add a comment here? That this func technically returns virtual space usage, but callers of this func expect physical space usage, but we currently neglect this mismatch.

UPDATE: Ok, you did it in the fixup commit.
___
*[`libos/src/fs/proc/info.c` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_nDzY8KqF3iUaT4OJ:-NG_nDzY8KqF3iUaT4OK:b-l5oadg) ([raw file](https://github.com/gramineproject/gramine/blob/89dc8548b110383a456a2cff1aae603f454e459f/libos/src/fs/proc/info.c#L24)):*
> ```C
> 
>     size_t free_mem = g_pal_public_state->mem_total - get_total_memory_usage();
>     assert(free_mem <= g_pal_public_state->mem_total);
> ```

Why do you have this assert in some places, but not in other places?
___
*[`libos/src/fs/proc/info.c` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1036#-NGZLzap4FVdwmEMY1Fi:-NG_mi1o7Nk3v4GfI86T:b5pdr09) ([raw file](https://github.com/gramineproject/gramine/blob/89dc8548b110383a456a2cff1aae603f454e459f/libos/src/fs/proc/info.c#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This makes no sense, we use total sum of virtual memory as actually consumed memory...
</blockquote></details>

Yes, it makes no sense, but it's also the best (only?) thing we can report here. I guess we could try to account for reserved-only memory, but I don't believe apps really care about the value.

It's misleading, I agree. Do we care though?

UPDATE: Ok, you already added a comment in the func that is used to calculate `free_mem`.
___
*[`libos/src/sys/libos_getrlimit.c` line 169 at r2](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_nLVTBEHmRSL8Lnw5:-NG_nLVTBEHmRSL8Lnw6:b-h6tih3) ([raw file](https://github.com/gramineproject/gramine/blob/89dc8548b110383a456a2cff1aae603f454e459f/libos/src/sys/libos_getrlimit.c#L169)):*
> ```C
>         return -EFAULT;
> 
>     size_t free_mem = g_pal_public_state->mem_total - get_total_memory_usage();
> ```

E.g., here you don't have the assert.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/bookkeep/libos_vma.c` line 905 at r1](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_qr7q8JmHp-kLrnH_:-NGb7VsF5GGC5QcAaok8:b-70vv13) ([raw file](https://github.com/gramineproject/gramine/blob/670cc12609520d01ca4e73af37d57f975faa215d/libos/src/bookkeep/libos_vma.c#L905)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We remove these calls because here we're just changing protections, so it should not result in any change in the total memory size?
</blockquote></details>

Should? It can't. Every VMAs (or part of it) that is added was previously removed in this very function.
___
*[`libos/src/fs/proc/info.c` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_nDzY8KqF3iUaT4OJ:-NGb7jbdEO_Vq0Fxgf8g:b-8gqt3c) ([raw file](https://github.com/gramineproject/gramine/blob/89dc8548b110383a456a2cff1aae603f454e459f/libos/src/fs/proc/info.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have this assert in some places, but not in other places?
</blockquote></details>

I? I just removed `PalMemoryAvailableQuota` and used libos interface, that's all. I did not add or remove any other code (including asserts)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/src/bookkeep/libos_vma.c` line 905 at r1](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_qr7q8JmHp-kLrnH_:-NGuP6M3-cKm5QcP6f0D:baoxo7q) ([raw file](https://github.com/gramineproject/gramine/blob/670cc12609520d01ca4e73af37d57f975faa215d/libos/src/bookkeep/libos_vma.c#L905)):*
> was previously removed in this very function

? Where?
___
*[`libos/src/fs/proc/info.c` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_nDzY8KqF3iUaT4OJ:-NGuPND09FrbciKSTrD4:b8du2o3) ([raw file](https://github.com/gramineproject/gramine/blob/89dc8548b110383a456a2cff1aae603f454e459f/libos/src/fs/proc/info.c#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I? I just removed `PalMemoryAvailableQuota` and used libos interface, that's all. I did not add or remove any other code (including asserts)
</blockquote></details>

Sorry, my blooper.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/bookkeep/libos_vma.c` line 905 at r1](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_qr7q8JmHp-kLrnH_:-NGvv6hVDXetTstIm9PS:b-wiwxg6) ([raw file](https://github.com/gramineproject/gramine/blob/670cc12609520d01ca4e73af37d57f975faa215d/libos/src/bookkeep/libos_vma.c#L905)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> was previously removed in this very function

? Where?
</blockquote></details>

`split_vma` shrinks it's first argument (here: `vma`), which in this code is also inside the vma tree 
___
*[`libos/src/bookkeep/libos_vma.c` line 1573 at r3](https://reviewable.io/reviews/gramineproject/gramine/1036#-NG_rVRJCRYKspgNiWYB:-NGvvlPWDX7ZQxlkRGTe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b194bc3c233b98edd3850323ba11d69caef13e2b/libos/src/bookkeep/libos_vma.c#L1573)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: should be `reserved`
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 14 of 14 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1036#-NGxuIjf0Vma4ytM-it_:-NGxuIjgEEqlgs5o_loq:b-tnkujc) (no related file):*
TODO for myself: verify commit split before merging.

___

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1036#-NGxuIjf0Vma4ytM-it_:-NGzNo91Du5C7aW_m8Qz:brqp5vu) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO for myself: verify commit split before merging.
</blockquote></details>

FYI: I verified the commit split, looks good to me.

___

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1036)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
