### PR TITLE
Fix python installation on Ubuntu 22.04

### LINKED ISSUE #1201: Unable to build gramine successfully on Ubuntu 22.04 without prefix option
### Description of the problem

When you try to build Gramine from sources in a fresh 22.04 system and you don’t specify the prefix, Graminelibos library is not installed in correct path. Graminelibos should install in **/usr/local/lib/python3.10/dist-packages/graminelibos** but instead of that it is getting installed in **/usr/local/graminelibos.** 

**Ubuntu 20.04:**
```
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_20.04_6.0/gramine/build/python/graminelibos/__init__.py to /usr/local/lib/python3.8/dist-packages/graminelibos
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_20.04_6.0/gramine/python/graminelibos/gen_jinja_env.py to /usr/local/lib/python3.8/dist-packages/graminelibos
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_20.04_6.0/gramine/python/graminelibos/manifest.py to /usr/local/lib/python3.8/dist-packages/graminelibos

```
**Ubuntu 22.04:**
```
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_22.04_6.0.9/gramine/build/python/graminelibos/__init__.py to /usr/local/graminelibos
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_22.04_6.0.9/gramine/python/graminelibos/gen_jinja_env.py to /usr/local/graminelibos
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_22.04_6.0.9/gramine/python/graminelibos/manifest.py to /usr/local/graminelibos
```

**_Because graminelibos is not correctly installed, gramine-sgx-gen-private-key results in ModuleNotFoundError: No module named 'graminelibos'_**

### Steps to reproduce

Build Gramine from source 
1. meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled
2. ninja -C build/
3. sudo ninja -C build/ install
4. gramine-sgx-gen-private-key

### Expected results

Graminelibos should be installed in correct path and gramine-sgx-gen-priavte-key or gramine python libraries should be working

### Actual results

Currently, it fails with **ModuleNotFoundError: No module named 'graminelibos'**

Logs attached
[Ubuntu_22_04_ninja_install_log.txt](https://github.com/gramineproject/gramine/files/10836743/Ubuntu_22_04_ninja_install_log.txt)
[Ubuntu_20_04_ninja_install_log.txt](https://github.com/gramineproject/gramine/files/10836744/Ubuntu_20_04_ninja_install_log.txt)

### Gramine commit hash

37cd3068493ee9b064b1845d1c0bbc55080aa6fe

### PR DESCRIPTION
**Pull request by woju**
## How to test this PR? 

Install Gramine on Ubuntu 22.04 from sources, either do not specify `--prefix` or set it to `/usr/local`.

Fixes #1201 

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
This commit will be either dropped (if it is purely for debug/reviews), or merged into the second commit?

Otherwise we will have a state in our commit history that breaks our own CI.
___
*[`.ci/check-python-platlib.jenkinsfile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDcV49OrJ3Jntb1M3:-NPJDcV49OrJ3Jntb1M4:bxswdc3) ([raw file](https://github.com/gramineproject/gramine/blob/618c6f7e6de502d712e56ce132ed001161c44e68/.ci/check-python-platlib.jenkinsfile#L1)):*
> ```
> pipeline {
> ```

Are we really adding such a pipeline, or was it (the first commit here) purely for testing and reviewing?

This pipeline looks like a total overkill, for a very specific bug...
___
*[`.ci/check-python-platlib.jenkinsfile` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJE3dAENKAbiLU1xQD:-NPJE3dAENKAbiLU1xQE:b43woxh) ([raw file](https://github.com/gramineproject/gramine/blob/618c6f7e6de502d712e56ce132ed001161c44e68/.ci/check-python-platlib.jenkinsfile#L7)):*
> ```
>             agent { dockerfile { filename '.ci/check-python-platlib-debian11.dockerfile' } }
>             steps { sh '''
>                 python3 -c "import sys; sys.exit('$(python3 ./scripts/get-python-platlib.py /usr/local)' not in sys.path)"
> ```

Can't we use a Jenkins variable instead of copy-pasting the same line?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This commit will be either dropped (if it is purely for debug/reviews), or merged into the second commit?

Otherwise we will have a state in our commit history that breaks our own CI.
</blockquote></details>

Or reorder to have it after. Weren't we supposed to have separate commits for tests?
___
*[`.ci/check-python-platlib.jenkinsfile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDcV49OrJ3Jntb1M3:-NPMNZwj9jSmjOd7e-i1:bxmfrho) ([raw file](https://github.com/gramineproject/gramine/blob/618c6f7e6de502d712e56ce132ed001161c44e68/.ci/check-python-platlib.jenkinsfile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Are we really adding such a pipeline, or was it (the first commit here) purely for testing and reviewing?

This pipeline looks like a total overkill, for a very specific bug...
</blockquote></details>

I'm fed up with python installation paths, and what 3 different APIs return for a value thereof, being all over the place on various distros. And it even changes with distro release, because we're living in interesting times over which those APIs are being reworked. So I've pulled a big hammer.
___
*[`.ci/check-python-platlib.jenkinsfile` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJE3dAENKAbiLU1xQD:-NPMOT3q6DteT_fECNls:b-r60xzg) ([raw file](https://github.com/gramineproject/gramine/blob/618c6f7e6de502d712e56ce132ed001161c44e68/.ci/check-python-platlib.jenkinsfile#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can't we use a Jenkins variable instead of copy-pasting the same line?
</blockquote></details>

This is declarative pipeline, I'd have to rewrite for an imperative one. See if you like this one better.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
> Weren't we supposed to have separate commits for tests?

Yes, but this rule is purely for ease of reviewing (so that reviewers can git-clone the PR, use the first commit, verify that it fails, then add the second commit and verify that it now succeeds).

After the review, we merge the two commits to have a proper history in `master`. But we (well, I) mostly ignore this rule...

Anyway, the reorder of commits is good for me.
___
*[`.ci/check-python-platlib.jenkinsfile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDcV49OrJ3Jntb1M3:-NPMkxi_6MeV_aQ6A99M:b-xhmf50) ([raw file](https://github.com/gramineproject/gramine/blob/618c6f7e6de502d712e56ce132ed001161c44e68/.ci/check-python-platlib.jenkinsfile#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'm fed up with python installation paths, and what 3 different APIs return for a value thereof, being all over the place on various distros. And it even changes with distro release, because we're living in interesting times over which those APIs are being reworked. So I've pulled a big hammer.
</blockquote></details>

Fair enough, let's keep it.
___
*[`.ci/check-python-platlib.jenkinsfile` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJE3dAENKAbiLU1xQD:-NPMkuyYDEJo6XX6pQa4:b-8omkvo) ([raw file](https://github.com/gramineproject/gramine/blob/618c6f7e6de502d712e56ce132ed001161c44e68/.ci/check-python-platlib.jenkinsfile#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is declarative pipeline, I'd have to rewrite for an imperative one. See if you like this one better.
</blockquote></details>

This looks awesome! Thanks.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
> Yes, but this rule is purely for ease of reviewing (so that reviewers can git-clone the PR, use the first commit, verify that it fails, then add the second commit and verify that it now succeeds).

Yes exactly. Please keep it for now, but we'll merge then before merging.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Yes, but this rule is purely for ease of reviewing (so that reviewers can git-clone the PR, use the first commit, verify that it fails, then add the second commit and verify that it now succeeds).

Yes exactly. Please keep it for now, but we'll merge then before merging.
</blockquote></details>

Please don't. I'd be easier to revert the testing thing if we need to do it.

**Review by mkow — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please don't. I'd be easier to revert the testing thing if we need to do it.
</blockquote></details>

Why would we revert only one of these commits? Also, this is purely theoretical, I think we've reverted changes just a few times in the last ~5 years (and most of it weren't simple reverts, rather "logical" revert of some change, not just reverting the commit in git).
Anyways, we almost always commit tests in the same commit as the functionality and I'd keep it this way for uniformity (and I don't really see a reason for not doing this).
___
*[`scripts/get-python-platlib.py` line 78 at r2](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPcGbzf00Ppadl2LOGW:-NPcGbzf00Ppadl2LOGX:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/bf301590491816bad4fa3b9458d0dadcb7c6cfc2/scripts/get-python-platlib.py#L78)):*
> ```Python
>             return platlib1
> 
>         # 2) if system is tool old for sysconfig, then distutils shoud work
> ```





_Suggestion:_
```Python
if system is too old for sysconfig, then distutils should work
```

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: 7 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
> Why would we revert only one of these commits?

Imagine that for whatever reason we'd like to remove CI pipelines. But we obviously won't need to revert the actual change in `get-python-platlib.py`. Or the other way around: if I made an error in this script that would affect other distro (in a way that we don't yet realise), then we can revert the change while leaving the pipeline intact. IOW there are two different decisions to make here: 1) how we fix the 22.04 problem, 2) if/how we test this change (and possibly other changes).

> Also, this is purely theoretical

It's not, Dima just asked if this pipeline is really needed in another thread. This decision we might want to revisit in the future.

> I think we've reverted changes just a few times in the last ~5 years 

Yeah, it's no wonder if you intentionally make commits that can't be cleanly reverted.
___
*[`scripts/get-python-platlib.py` line 78 at r2](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPcGbzf00Ppadl2LOGW:-NPcVzRyAlyRS76ToXok:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bf301590491816bad4fa3b9458d0dadcb7c6cfc2/scripts/get-python-platlib.py#L78)):*
> ```Python
>             return platlib1
> 
>         # 2) if system is tool old for sysconfig, then distutils shoud work
> ```

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> Why would we revert only one of these commits?

Imagine that for whatever reason we'd like to remove CI pipelines. But we obviously won't need to revert the actual change in `get-python-platlib.py`. Or the other way around: if I made an error in this script that would affect other distro (in a way that we don't yet realise), then we can revert the change while leaving the pipeline intact. IOW there are two different decisions to make here: 1) how we fix the 22.04 problem, 2) if/how we test this change (and possibly other changes).

> Also, this is purely theoretical

It's not, Dima just asked if this pipeline is really needed in another thread. This decision we might want to revisit in the future.

> I think we've reverted changes just a few times in the last ~5 years 

Yeah, it's no wonder if you intentionally make commits that can't be cleanly reverted.


</blockquote></details>

I agree with @woju here: I can imagine that we would like to revert the CI change only. So making it a separate commit seems reasonable to me.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with @woju here: I can imagine that we would like to revert the CI change only. So making it a separate commit seems reasonable to me.
</blockquote></details>

I prepared a final rebase with two commits. @mkow Please ACK or NACK here, because this PR is ready for merge.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1203#-NPJDo_cBimW8HVB4ZXs):*
Ok, if I understand correctly, the argument here is that there's a real risk that we'll want to keep the change but remove the pipeline, which seems to justify the exception.

> > I think we've reverted changes just a few times in the last ~5 years
> 
> Yeah, it's no wonder if you intentionally make commits that can't be cleanly reverted.

You imply here that we wanted to revert something in the past but didn't do it because of the commit split? I don't remember any such case, we rarely merge changes which are later undone, and all such cases I remember were undone *much* later (e.g. after we deprecated a feature because of Linux or hardware changes), so `git revert` wouldn't be suitable for them anyways (because `git revert` works cleanly only on very recent commits in project which are as actively developed as Gramine).

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-EDMM please (testing the EDMM Jenkins machine)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1203)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
