### PR TITLE
[LibOS] Add `/dev/fd/` directory

### LINKED ISSUE #1267: `/dev/fd/` support
### Description of the problem

I am getting below error in gramine when trying to execute process substitution with gramine. Named pipe file /dev/fd/63 is not getting detetcted by gramine:

diff: /dev/fd/63: No such file or directory

Process substitution is a form of inter-process communication that allows the input or output of a command to appear as a file. This allows programs that normally only accept files to directly read from or write to another program.
Reference: https://en.wikipedia.org/wiki/Process_substitution 

### Steps to reproduce

gramine 1.4
1. Navigate to CI-Examples/bash
2. Create 2 dummpy text files (here file1 and file2)
3. Run the command gramine-direct bash -c 'diff file2 <(sort file1)'

(Here, result of sort file1 is stored to named pipe file /dev/fd/63. Now this run time generated (named pipe) file acts as argument for diff command
so the given command becomes diff file2 /dev/fd/63)

### Expected results

we should see the unmatched(uncommon) text out of the 2 files (as diff stands for differenciation)

### Actual results

diff: /dev/fd/63: No such file or directory
[process_substitution_failure_log.txt](https://github.com/gramineproject/gramine/files/11147469/process_substitution_failure_log.txt)

### Gramine commit hash

gramine 1.4-aefd5d0875c4fdf76edd67f5043952bdd32b0f7a

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Fixes #1267 (or at least one of the problems there, I split out the other problem to #1872).

## How to test this PR? 

Try `ls -la <(echo 123)` in Bash under Gramine.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1873)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1873)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1873)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1873#-NxGv0GwClpPCAIM33pP:-NxGv0GwClpPCAIM33pQ:byi7huw) (no related file):*
You sure you want to mention that it fixes #1267? It doesn't really (it kinda fixes the title, but it doesn't fix the actual problem of reading the pipe that is explained in the issue).

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1873)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1873#-NxGv0GwClpPCAIM33pP:-NxLtJCR7ctpWVkumTrk:b-qezkjt) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I prefer to close that one because it's a bit messy. That's why I created #1872, which is cleaner and lists exactly what's left to do.
</blockquote></details>

Ok, fair enough.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1873)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1873)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
