### PR TITLE
[LibOS] chroot fs: remove redundant arg in `chroot_temp_open()`

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

As in title. Tiny change.

Extracted from https://github.com/gramineproject/gramine/pull/1812.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1816)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1816)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1816#-NuRHmIy37rtPbaZR4hs:-NuRHmIy37rtPbaZR4ht:b-rq9y2j) (no related file):*
What about https://github.com/gramineproject/gramine/blob/0ee48eebb24c38bdad193fa9945a3b26d4a89dc6/libos/src/fs/shm/fs.c#L55?

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1816)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1816#-NuRHmIy37rtPbaZR4hs:-NuThjUPBr5Fwq5CHKOg:b-glz11o) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's different. In the `_do_open()` functions we can't remove the `type` argument.

Please note that we have a similar function here, `chroot_do_open()`, where I also do *not* remove the `type` argument.
</blockquote></details>

An additional explanation that may help understand the difference:
- `chroot_temp_open()` is used to open a definitely-existing file, just to get a handle on this file. This is needed because many PAL functions operate only on opened handles, not on filenames.
- `chroot_do_open()` is used to open or create a file, getting the handle on this file as a by-effect. Since the file may not exist (thus there is no inode to extract the info from), we *need to know* the type explicitly.

`shm_do_open()` is related to the second kind of helper functions. So not applicable to this PR.

___

**Review by kailun-qin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1816)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1816#-NuRHmIy37rtPbaZR4hs:-NuTy79N-tZLgFymafP3:b-ie0wux) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

An additional explanation that may help understand the difference:
- `chroot_temp_open()` is used to open a definitely-existing file, just to get a handle on this file. This is needed because many PAL functions operate only on opened handles, not on filenames.
- `chroot_do_open()` is used to open or create a file, getting the handle on this file as a by-effect. Since the file may not exist (thus there is no inode to extract the info from), we *need to know* the type explicitly.

`shm_do_open()` is related to the second kind of helper functions. So not applicable to this PR.
</blockquote></details>

Indeed -- I misread it. Thanks for the great explanation!

___

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1816)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1816)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest this please (unrelated Jenkins maintenance issues)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1816)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest this please (unrelated Jenkins maintenance issues)

**Pull request merged**
