### PR TITLE
[common] Refactor Protected Files, part 2

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This commit refactors PF code without changing functionality (part 2 in a series of commits). In particular, this commit simplifies function signatures of `ipf_read_node()` and `ipf_write_node()`.

Extracted from https://github.com/gramineproject/gramine/pull/1841 at the request of @mkow.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1867)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1867)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files.c` line 847 at r1](https://reviewable.io/reviews/gramineproject/gramine/1867#-Nwt8Idv1TrUAnNe5rXa:-Nwt8Idv1TrUAnNe5rXb:bb7ozr7) ([raw file](https://github.com/gramineproject/gramine/blob/3d8fca12ea47107f788ff954b3770e41c12d4dba/common/src/protected_files/protected_files.c#L847)):*
> ```C
>         // read the root node of the mht
>         if (!ipf_read_node(pf, /*node_number=*/1, &pf->root_mht.encrypted.cipher))
> 			return false;
> ```

tabs

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1867)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/src/protected_files/protected_files.c` line 847 at r1](https://reviewable.io/reviews/gramineproject/gramine/1867#-Nwt8Idv1TrUAnNe5rXa:-NwtKRwm9gJ1D5DHYWq1:b7k1ots) ([raw file](https://github.com/gramineproject/gramine/blob/3d8fca12ea47107f788ff954b3770e41c12d4dba/common/src/protected_files/protected_files.c#L847)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

tabs
</blockquote></details>

Done. I wonder how this could happen.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1867)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1867)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1867)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
