### PR TITLE
[PAL/Linux-SGX] Add diagnostics to error message about sigstruct size

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 
Inspired by #1997, maybe in the future it will save one round trip while debugging other people's computers. 

## How to test this PR? 

```
cd helloworld
make SGX=1
truncate -s 0 helloworld.sig  # or any number != 1808
gramine-sgx helloworld
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/1998#-O62R2WL7knvi422ef8k:-O62R2WL7knvi422ef8l:bwoq3gb) ([raw file](https://github.com/gramineproject/gramine/blob/1f142d5555c6a38c909a4a6513fe6e5edf45855e/pal/src/host/linux-sgx/host_framework.c#L141)):*
> ```C
>     if ((size_t)stat.st_size != sizeof(sgx_sigstruct_t)) {
>         log_error("size of sigstruct size does not match: expected %zu, found %jd",
>                   sizeof(sgx_sigstruct_t), (intmax_t)stat.st_size);
> ```

I'd use `size_t` here, the size cannot be negative anyways.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/1998#-O62R2WL7knvi422ef8k:-O62ufflEMb_xi3MEAC8:b-gu2d14) ([raw file](https://github.com/gramineproject/gramine/blob/1f142d5555c6a38c909a4a6513fe6e5edf45855e/pal/src/host/linux-sgx/host_framework.c#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd use `size_t` here, the size cannot be negative anyways.
</blockquote></details>

I couldn't find any guarantee that `off_t` isn't bigger than `size_t`, and IIRC `off_t` is configurable by a macro that I can't remember name of. So this appears to me as the correct (portable) way to printf the value?

I'm also not entirely sure if the comparison is posixly correct, but I was not brave enough to fix it. On sane distros it's likely fine.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/1998#-O62R2WL7knvi422ef8k:-O62zdlT-DXOe2ZwqoXw:bqwiew) ([raw file](https://github.com/gramineproject/gramine/blob/1f142d5555c6a38c909a4a6513fe6e5edf45855e/pal/src/host/linux-sgx/host_framework.c#L141)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I couldn't find any guarantee that `off_t` isn't bigger than `size_t`, and IIRC `off_t` is configurable by a macro that I can't remember name of. So this appears to me as the correct (portable) way to printf the value?

I'm also not entirely sure if the comparison is posixly correct, but I was not brave enough to fix it. On sane distros it's likely fine.
</blockquote></details>

I'm a bit uneasy about that `%jd`, it works only because we link untrusted PAL to glibc, so it's kinda by accident - our internal printf doesn't support `j`. `off_t` is mess, but so is `intmax_t`.

You're right though, the cast to `size_t` is wrong, but it's wrong also in the `if` above - on 32-bits it would trim the size, so `0x100000000+sizeof(sgx_sigstruct_t)` would pass this check.

I'm actually not sure how to solve this well... I really hate how C types always turn out to be useless...

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/1998#-O62R2WL7knvi422ef8k:-O639jaA8iuJsHvJ2zSX:bplzr21) ([raw file](https://github.com/gramineproject/gramine/blob/1f142d5555c6a38c909a4a6513fe6e5edf45855e/pal/src/host/linux-sgx/host_framework.c#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm a bit uneasy about that `%jd`, it works only because we link untrusted PAL to glibc, so it's kinda by accident - our internal printf doesn't support `j`. `off_t` is mess, but so is `intmax_t`.

You're right though, the cast to `size_t` is wrong, but it's wrong also in the `if` above - on 32-bits it would trim the size, so `0x100000000+sizeof(sgx_sigstruct_t)` would pass this check.

I'm actually not sure how to solve this well... I really hate how C types always turn out to be useless...
</blockquote></details>

Oh, I forgot about internal printf. Yes, that makes sense, I hope no-one will create 2**64+1808 sized files.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/1998#-O62R2WL7knvi422ef8k:-O63DLP02YVvQSaDm7cI:b-fj6ydt) ([raw file](https://github.com/gramineproject/gramine/blob/1f142d5555c6a38c909a4a6513fe6e5edf45855e/pal/src/host/linux-sgx/host_framework.c#L141)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Oh, I forgot about internal printf. Yes, that makes sense, I hope no-one will create 2**64+1808 sized files.
</blockquote></details>

The problem is that `0x100000000` is not 2**64, it's just 4 GB, so it's doable. But this is just a debugging / user help, so I won't block on this.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 140 at r2](https://reviewable.io/reviews/gramineproject/gramine/1998#-O65s-KOErfXTiv7JVhU:-O65s-KOErfXTiv7JVhV:bn50q4s) ([raw file](https://github.com/gramineproject/gramine/blob/e4f91407713376d665569054b027e1b7a9ba726c/pal/src/host/linux-sgx/host_framework.c#L140)):*
> ```C
> 
>     if ((size_t)stat.st_size != sizeof(sgx_sigstruct_t)) {
>         log_error("size of sigstruct size does not match: expected %zu, found %zu",
> ```

There are two times `size`, please remove one (or better, rephrase slightly)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 140 at r2](https://reviewable.io/reviews/gramineproject/gramine/1998#-O65s-KOErfXTiv7JVhU:-O66-jxp6a2e3nA1SnxJ:b-y65irq) ([raw file](https://github.com/gramineproject/gramine/blob/e4f91407713376d665569054b027e1b7a9ba726c/pal/src/host/linux-sgx/host_framework.c#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There are two times `size`, please remove one (or better, rephrase slightly)
</blockquote></details>

I rephrased slightly.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 135 at r3](https://reviewable.io/reviews/gramineproject/gramine/1998#-O661kyw8Y1xogByv_Qo:-O661kyw8Y1xogByv_Qp:bvwd52w) ([raw file](https://github.com/gramineproject/gramine/blob/e20c8a6b632fe20e26924bfdbe4f07dc9b75505b/pal/src/host/linux-sgx/host_framework.c#L135)):*
> ```C
>     struct stat stat;
>     int sigfile_fd = -1;
>     int ret = 0;
> ```

Please just `int ret;`
___
*[`pal/src/host/linux-sgx/host_framework.c` line 140 at r3](https://reviewable.io/reviews/gramineproject/gramine/1998#-O661xdS3H5xAsbfdjQh:-O661xdS3H5xAsbfdjQi:be34ew9) ([raw file](https://github.com/gramineproject/gramine/blob/e20c8a6b632fe20e26924bfdbe4f07dc9b75505b/pal/src/host/linux-sgx/host_framework.c#L140)):*
> ```C
>     if (sigfile_fd < 0) {
>         log_error("Cannot open sigstruct file %s", sig_path);
>         ret = -EINVAL;
> ```

Since we're changing this, just `ret = sigfile_fd;`

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 135 at r3](https://reviewable.io/reviews/gramineproject/gramine/1998#-O661kyw8Y1xogByv_Qo:-O66cZbK9FTisL0kb_uP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/382d6565f0981509ccdb9ff0650c97024d1f3e2b/pal/src/host/linux-sgx/host_framework.c#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please just `int ret;`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 140 at r3](https://reviewable.io/reviews/gramineproject/gramine/1998#-O661xdS3H5xAsbfdjQh:-O66c_zmEqL5ACr_nkRu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/382d6565f0981509ccdb9ff0650c97024d1f3e2b/pal/src/host/linux-sgx/host_framework.c#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're changing this, just `ret = sigfile_fd;`
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1998)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
