### PR TITLE
[LibOS] Set `handle->uri` on opening a protected file

### PR DESCRIPTION
**Pull request by kailun-qin**
Fixes https://github.com/gramineproject/gramine/issues/840.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/841)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, test this please

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/841)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/841#-N9Wuazn252_ENIQVHHC:-N9Wuazo9hD6C6YpnEND:b-caafxq) (no related file):*
Could you elaborate on why this is the correct fix? I'm not familiar with most of FS code and it seems that it allows for having `handle->uri == NULL` and this code is invalid: https://github.com/gramineproject/gramine/blob/d8217c8ad08fc2be289384b90100e29c0506c097/libos/src/libos_rtld.c#L1037

___
___
*[`libos/src/fs/chroot/encrypted.c` line 184 at r1](https://reviewable.io/reviews/gramineproject/gramine/841#-N9WqBN_-r_GHwJiIBV-:-N9WqBN_-r_GHwJiIBV0:b-f5rufv) ([raw file](https://github.com/gramineproject/gramine/blob/89521c7dcfdb9760ecc624e19d620d02c093c41e/libos/src/fs/chroot/encrypted.c#L184)):*
> ```C
>     if (ret < 0)
>         return ret;
> ```

Couldn't we just always set `hdl->uri` here (i.e. regardless of whether code below will succeed)?
___
*[`libos/src/fs/chroot/encrypted.c` line 209 at r1](https://reviewable.io/reviews/gramineproject/gramine/841#-N9WuZ9aCjWF7QxbC-8X:-N9WuZ9aCjWF7QxbC-8Y:baki5ok) ([raw file](https://github.com/gramineproject/gramine/blob/89521c7dcfdb9760ecc624e19d620d02c093c41e/libos/src/fs/chroot/encrypted.c#L209)):*
> ```C
> }
> 
> static int chroot_encrypted_creat(struct libos_handle* hdl, struct libos_dentry* dent, int flags,
> ```

This doesn't set `uri` either.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/841)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/841#-N9Wuazn252_ENIQVHHC:-N9WutNb1-noaTthR_7J:b-gwmmd0) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you elaborate on why this is the correct fix? I'm not familiar with most of FS code and it seems that it allows for having `handle->uri == NULL` and this code is invalid: https://github.com/gramineproject/gramine/blob/d8217c8ad08fc2be289384b90100e29c0506c097/libos/src/libos_rtld.c#L1037
</blockquote></details>

cc @dimakuv @mkow maybe you know more about this

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/841)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/841#-N9Wuazn252_ENIQVHHC:-N9aSwiw00qkoZLHc1TL:b-e1u8eg) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

cc @dimakuv @mkow maybe you know more about this
</blockquote></details>

The LibOS codebase doesn't require `handle::uri` to be set: https://github.com/gramineproject/gramine/blob/aaf34c87bfebd071cdb18a187a7b7cbe510da88a/libos/include/libos_handle.h#L180

Ideally, this `handle::uri` should be removed and instead moved to handle-specific struct. Like we do for Encrypted Files here: https://github.com/gramineproject/gramine/blob/aaf34c87bfebd071cdb18a187a7b7cbe510da88a/libos/include/libos_fs_encrypted.h#L46

Many parts of the FS code do not set the URI. For example, `tmpfs` handles do not set URI.

I agree with @boryspoplawski that this line is wrong: https://github.com/gramineproject/gramine/blob/d8217c8ad08fc2be289384b90100e29c0506c097/libos/src/libos_rtld.c#L1037

It should have an IF clause similar to this case: https://github.com/gramineproject/gramine/blob/d8217c8ad08fc2be289384b90100e29c0506c097/libos/src/libos_rtld.c#L839-L841

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/841#-N9aV1a5AKnECh52y7Ar:-N9aV1a5AKnECh52y7As:bvbd1gm) (no related file):*
@kailun-qin I think this solution is wrong. We need to make Gramine LibOS codebase resistant to cases of `handle::uri == NULL`. Maybe you could look into this? See also my other comment.

But to fix #840 quickly, we can just add an `if (hdl->uri) ...only then call append_r_debug()...`

___
___
*[`libos/src/fs/chroot/encrypted.c` line 179 at r1](https://reviewable.io/reviews/gramineproject/gramine/841#-N9aUvTN1p1xUeUdO1-u:-N9aUvTN1p1xUeUdO1-v:b-s52rym) ([raw file](https://github.com/gramineproject/gramine/blob/89521c7dcfdb9760ecc624e19d620d02c093c41e/libos/src/fs/chroot/encrypted.c#L179)):*
> ```C
> 
>     int ret;
>     char* uri = NULL;
> ```

I have a strong feeling that this code is unnecessary and wrong.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/841)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/841#-N9Wuazn252_ENIQVHHC:-N9auxhuC-97Unb40Yew:bmduywv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The LibOS codebase doesn't require `handle::uri` to be set: https://github.com/gramineproject/gramine/blob/aaf34c87bfebd071cdb18a187a7b7cbe510da88a/libos/include/libos_handle.h#L180

Ideally, this `handle::uri` should be removed and instead moved to handle-specific struct. Like we do for Encrypted Files here: https://github.com/gramineproject/gramine/blob/aaf34c87bfebd071cdb18a187a7b7cbe510da88a/libos/include/libos_fs_encrypted.h#L46

Many parts of the FS code do not set the URI. For example, `tmpfs` handles do not set URI.

I agree with @boryspoplawski that this line is wrong: https://github.com/gramineproject/gramine/blob/d8217c8ad08fc2be289384b90100e29c0506c097/libos/src/libos_rtld.c#L1037

It should have an IF clause similar to this case: https://github.com/gramineproject/gramine/blob/d8217c8ad08fc2be289384b90100e29c0506c097/libos/src/libos_rtld.c#L839-L841
</blockquote></details>

I see, make sense. Thanks!

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/841#-N9aV1a5AKnECh52y7Ar:-N9av3mQ7ytyqJmMXWhD:b-612znw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin I think this solution is wrong. We need to make Gramine LibOS codebase resistant to cases of `handle::uri == NULL`. Maybe you could look into this? See also my other comment.

But to fix #840 quickly, we can just add an `if (hdl->uri) ...only then call append_r_debug()...`
</blockquote></details>

Yes, I can look more thoroughly into this. Did a quick fix at https://github.com/gramineproject/gramine/pull/845 for https://github.com/gramineproject/gramine/issues/840.

___

**Comment by boryspoplawski** [comment]
Closing this PR as we decided not to proceed with it

**Pull request closed without merging**
