### PR TITLE
[tools/sgx] Cosmetic refactoring of RA-TLS

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

No functional changes. This is in preparation for "interoperable RA-TLS" modification of RA-TLS (with IANA-registered OIDs and CBOR tags).

## How to test this PR? 

CI. Only renames of funcs/variables and moving code around.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)

### CODE REVIEW

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1038#-NGbRAH27UhT4_LmTZXZ:-NGbRAH27UhT4_LmTZX_:bhco33z) ([raw file](https://github.com/gramineproject/gramine/blob/18e588f19caec11bdcfa08335b291f60cc168b0e/tools/sgx/ra-tls/ra_tls_verify_common.c#L157)):*
> ```C
>     *out_size   = *p++;
>     *out_size <<= 8;
>     *out_size  += *p++;
> ```

This style is correct?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1038#-NGbRAH27UhT4_LmTZXZ:-NGuPg46CMBh591A3DTK:bfu3v73) ([raw file](https://github.com/gramineproject/gramine/blob/18e588f19caec11bdcfa08335b291f60cc168b0e/tools/sgx/ra-tls/ra_tls_verify_common.c#L157)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This style is correct?
</blockquote></details>

What do you mean exactly?

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1038#-NGbRAH27UhT4_LmTZXZ:-NGua1xFD_OSgOJQGe0c:bny3dja) ([raw file](https://github.com/gramineproject/gramine/blob/18e588f19caec11bdcfa08335b291f60cc168b0e/tools/sgx/ra-tls/ra_tls_verify_common.c#L157)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean exactly?
</blockquote></details>

I mean the alignment of variables.
Shouldn't it be simple:
```
    *out_size = *p++;
    *out_size <<= 8;
    *out_size += *p++;
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1038#-NGbRAH27UhT4_LmTZXZ:-NGuicdv12ZIGyHWA7wG:brjx1g9) ([raw file](https://github.com/gramineproject/gramine/blob/18e588f19caec11bdcfa08335b291f60cc168b0e/tools/sgx/ra-tls/ra_tls_verify_common.c#L157)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I mean the alignment of variables.
Shouldn't it be simple:
```
    *out_size = *p++;
    *out_size <<= 8;
    *out_size += *p++;
```

</blockquote></details>

Done. In this particular case, I found it more readable, but I don't care.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 52 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRTuma6uTySVNt9s2e:-NHRTuma6uTySVNt9s2f:b5ec57r) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls.h#L52)):*
> ```objc
> 
> __attribute__ ((visibility("hidden")))
> int extract_quote_and_verify_claims(mbedtls_x509_crt* crt, sgx_quote_t** out_quote,
> ```

What does "verify claims" mean, exactly? Where are these "claims"? I'm confused :)
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1038#-NGbRAH27UhT4_LmTZXZ:-NHRVMsdATRLmMVX41iQ:bozuxtq) ([raw file](https://github.com/gramineproject/gramine/blob/18e588f19caec11bdcfa08335b291f60cc168b0e/tools/sgx/ra-tls/ra_tls_verify_common.c#L157)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. In this particular case, I found it more readable, but I don't care.
</blockquote></details>

I see what @dimakuv wanted to achieve, but IMO it looks weird, so +1 to the unaligned version.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 152 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRVCI5CrpxZgbBI0lD:-NHRVCI5CrpxZgbBI0lE:b-ecxaqq) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls_verify_common.c#L152)):*
> ```C
>     }
> 
>     if (p + 2 >= exts_end)
> ```

Was refusing `out_size == 0` intended here? (`>=` vs `>`)
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 214 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRWvAK58fgAD6zF2bQ:-NHRWvAK58fgAD6zF2bR:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls_verify_common.c#L214)):*
> ```C
>     if (quote_size < sizeof(*quote))
>         return MBEDTLS_ERR_X509_INVALID_EXTENSIONS;
> ```





_Suggestion:_
```C
currently only a single claim is verified
```
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRX2D_9zGqEaLZfbI8:-NHRX2D_9zGqEaLZfbI9:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls_verify_common.c#L215)):*
> ```C
>         return MBEDTLS_ERR_X509_INVALID_EXTENSIONS;
> 
>     /* currently single claim verified: must compare public key's hash from cert against SGX quote's
> ```





_Suggestion:_
```C
public key's hash from cert must match SGX
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: 4 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 52 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRTuma6uTySVNt9s2e:-NHTbWvB2exTFfIPWLOC:b-8ystai) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls.h#L52)):*
Welcome to the world of attestation...

I recommend this standard: https://trustedcomputinggroup.org/wp-content/uploads/TCG_DICE_Attestation_Architecture_r22_02dec2020.pdf

Page 14 has a nice diagram and this snippet:

> The Attester consists of an Attesting Environment and a Target Environment. The Attesting Environment collects
assertions, called Claims, about the trustworthiness properties of the Target Environment. Claims are packaged
as Evidence by the Attesting Environment, integrity protected and authenticated. The Attesting Environment may
also supply additional claims that attest the freshness and recentness of collected claims.

In our particular case, "verify claims" means only one thing currently: verify that the public key inside the SGX report's `user_report_data` field corresponds to the public key of the X.509 certificate itself. To recall why this is so, please check our RA-TLS X.509 cert diagram here: https://gramine.readthedocs.io/en/latest/attestation.html#mid-level-ra-tls-interface
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1038#-NGbRAH27UhT4_LmTZXZ:-NHTckda4EbcSNKeD1eI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/18e588f19caec11bdcfa08335b291f60cc168b0e/tools/sgx/ra-tls/ra_tls_verify_common.c#L157)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I see what @dimakuv wanted to achieve, but IMO it looks weird, so +1 to the unaligned version.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 152 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRVCI5CrpxZgbBI0lD:-NHTcGMXBupmLzw-0sgx:bnz33lz) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls_verify_common.c#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Was refusing `out_size == 0` intended here? (`>=` vs `>`)
</blockquote></details>

The size cannot be `0` because we verified above that the size of the extension ("the ASN.1 length-of-octet-string encoding") is in-between 128-65K bytes. So yes, refusing zero size is on purpose -- it's impossible (otherwise the ASN.1 encoding is broken in this certificate).

Actually, let me modify this snippet slightly so it's obvious that `out_size` should be in very specific limits.

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 214 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRWvAK58fgAD6zF2bQ:-NHTcuhn4M3pa1lZLB98:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls_verify_common.c#L214)):*
> ```C
>     if (quote_size < sizeof(*quote))
>         return MBEDTLS_ERR_X509_INVALID_EXTENSIONS;
> ```

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRX2D_9zGqEaLZfbI8:-NHTd0Fy2VHjZilvZYed:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls_verify_common.c#L215)):*
> ```C
>         return MBEDTLS_ERR_X509_INVALID_EXTENSIONS;
> 
>     /* currently single claim verified: must compare public key's hash from cert against SGX quote's
> ```

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 52 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRTuma6uTySVNt9s2e:-NHVeqzKBgYL6jhU5tx_:b-qv3ugo) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls.h#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Welcome to the world of attestation...

I recommend this standard: https://trustedcomputinggroup.org/wp-content/uploads/TCG_DICE_Attestation_Architecture_r22_02dec2020.pdf

Page 14 has a nice diagram and this snippet:

> The Attester consists of an Attesting Environment and a Target Environment. The Attesting Environment collects
assertions, called Claims, about the trustworthiness properties of the Target Environment. Claims are packaged
as Evidence by the Attesting Environment, integrity protected and authenticated. The Attesting Environment may
also supply additional claims that attest the freshness and recentness of collected claims.

In our particular case, "verify claims" means only one thing currently: verify that the public key inside the SGX report's `user_report_data` field corresponds to the public key of the X.509 certificate itself. To recall why this is so, please check our RA-TLS X.509 cert diagram here: https://gramine.readthedocs.io/en/latest/attestation.html#mid-level-ra-tls-interface
</blockquote></details>

Why not just `[...]_and__verify_pubkey`? The TCG terminology is quite confusing to me.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1038#-NGbRAH27UhT4_LmTZXZ:-NHVkLQg3c1yy-e19OK3:b-bse1od) ([raw file](https://github.com/gramineproject/gramine/blob/18e588f19caec11bdcfa08335b291f60cc168b0e/tools/sgx/ra-tls/ra_tls_verify_common.c#L157)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

? Done what?
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 152 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRVCI5CrpxZgbBI0lD:-NHVkZ3rDmUKyQU16mkW:beu6x1k) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls_verify_common.c#L152)):*
> we verified above that the size of the extension ("the ASN.1 length-of-octet-string encoding") is in-between 128-65K bytes

Hmm, where? Size parsing is below, not above. Anyways, the code looks good now.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHVlYm11L06Q0kQPPlY:-NHVlYm11L06Q0kQPPlZ:bz0zutr) ([raw file](https://github.com/gramineproject/gramine/blob/71b5330f99e7aa24bdb67cada92e970d3880c88b/tools/sgx/ra-tls/ra_tls_verify_common.c#L164)):*
> ```C
>     uint8_t* val = p;
> 
>     if (val_size < 128 || val_size > SGX_QUOTE_MAX_SIZE || val + val_size > exts_end)
> ```

otherwise overflow is theoretically possible (remember that the certificate is not trusted at this point)



_Suggestion:_
```C
val_size > exts_end - val
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: 1 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 52 at r2](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHRTuma6uTySVNt9s2e:-NHYZCOR0LiwheQGJInn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fb7dd93ecade004618f62780572f9a70e9ad783d/tools/sgx/ra-tls/ra_tls.h#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just `[...]_and__verify_pubkey`? The TCG terminology is quite confusing to me.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1038#-NGbRAH27UhT4_LmTZXZ:-NHYYdWt4tGt-FstL5nw:b-orxedi) ([raw file](https://github.com/gramineproject/gramine/blob/18e588f19caec11bdcfa08335b291f60cc168b0e/tools/sgx/ra-tls/ra_tls_verify_common.c#L157)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

? Done what?
</blockquote></details>

That was me clicking "Done" button for no reason. Sorry.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHVlYm11L06Q0kQPPlY:-NHYYyGq0aXv0OvYyvjp:b-l2tt7p) ([raw file](https://github.com/gramineproject/gramine/blob/71b5330f99e7aa24bdb67cada92e970d3880c88b/tools/sgx/ra-tls/ra_tls_verify_common.c#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

otherwise overflow is theoretically possible (remember that the certificate is not trusted at this point)
</blockquote></details>

Done, good catch.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 221 at r3](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHYZDoc0xUiwbiC1aIs:-NHYZDoc0xUiwbiC1aIt:b-3b73bv) ([raw file](https://github.com/gramineproject/gramine/blob/71b5330f99e7aa24bdb67cada92e970d3880c88b/tools/sgx/ra-tls/ra_tls_verify_common.c#L221)):*
> ```C
> 
>     /* currently only a single claim is verified: public key's hash from cert must match SGX quote's
>      * report_data */
> ```

Since Michal doesn't like the word "claim", I modified this sentence to have "check"

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 221 at r3](https://reviewable.io/reviews/gramineproject/gramine/1038#-NHYZDoc0xUiwbiC1aIs:-NHZdLpCCuKhBtXggNHa:bftmvxo) ([raw file](https://github.com/gramineproject/gramine/blob/71b5330f99e7aa24bdb67cada92e970d3880c88b/tools/sgx/ra-tls/ra_tls_verify_common.c#L221)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since Michal doesn't like the word "claim", I modified this sentence to have "check"
</blockquote></details>

Not in general, just in this context it sounds vague and confusing :)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

**Review by oshogbo — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038#-:-NHg4_fqB2jWRr9-mt5r:bb6ywmx)* status: all files reviewed, 1 unresolved discussion

**Review by dimakuv — COMMENTED** [review]
> Dismissed @oshogbo from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1038)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1038#-NGbRAH27UhT4_LmTZXZ:-NHhb4vK59OYYfNTqpK6:b-ir78jr) ([raw file](https://github.com/gramineproject/gramine/blob/18e588f19caec11bdcfa08335b291f60cc168b0e/tools/sgx/ra-tls/ra_tls_verify_common.c#L157)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That was me clicking "Done" button for no reason. Sorry.
</blockquote></details>

@oshogbo You were blocking on this particular discussion. So the idea was for you to change your disposition in this discussion (by clicking on "Satisfied" button) in the top-right corner.

Anyway, since you wrote "LGTM", I dismissed you from this discussion, to move Reviewable state to "ok to merge".

**Pull request merged**
