### PR TITLE
Revisit compiler flag usages

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
See commit messages.

## Useful links
https://man7.org/linux/man-pages/man1/gcc.1.html
https://man7.org/linux/man-pages/man1/ld.1.html
https://gcc.gnu.org/onlinedocs/gcc/Standards.html#Standards

## How to test this PR? 
No functional changes, CI should be enough.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 17 of 17 files at r2, 1 of 9 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/970#-NE8sFI47llffrRYkEiG:-NE8sFI47llffrRYkEiH:b-n9s32y) (no related file):*
clang refuses to get `SSIZE_MAX` for some reason, will debug tomorrow

___

**Review by dimakuv — APPROVED** [review]
> Reviewed 17 of 17 files at r2, 9 of 9 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: 25 of 27 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/970#-NE8sFI47llffrRYkEiG:-NEE0xQC62pQdw8Ht8Hq:b-31ykh2) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

clang refuses to get `SSIZE_MAX` for some reason, will debug tomorrow
</blockquote></details>

Not sure what was the exact problem, most likely `ffreestanding` does not define something and `SSIZE_MAX` was omitted.

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/meson.build` line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/970#-NEF6DHM2pR5vv2D8DIw:-NEF6DHM2pR5vv2D8DIx:b-gg3076) ([raw file](https://github.com/gramineproject/gramine/blob/ab3b6e4ac4c62319cfe4c60504fc429357234041/libos/meson.build#L4)):*
> ```Meson
>     '-fPIC',
>     # TODO: check whether all standard functions implemented in Gramine match their APIs and remove
>     # this
> ```

Why "remove this"? Do you mean remove `-ffreestanding`? Or do you mean remove this comment?

Removing `-ffreestanding` doesn't make sense. If you meant removing the comment, please say so: `...and remove this comment`

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/meson.build` line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/970#-NEF6DHM2pR5vv2D8DIw:-NEGFq0R7Jaddpf5iwN4:bszawv6) ([raw file](https://github.com/gramineproject/gramine/blob/ab3b6e4ac4c62319cfe4c60504fc429357234041/libos/meson.build#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why "remove this"? Do you mean remove `-ffreestanding`? Or do you mean remove this comment?

Removing `-ffreestanding` doesn't make sense. If you meant removing the comment, please say so: `...and remove this comment`
</blockquote></details>

I just reverted the old comment.
It means removing `ffreestanding`. Generally it turns out this option isn't really useful and I used it just because we had `no-builtin` anyway (and `ffreestanding` is sort of a "stronger version").
Pros:
- it tells the compiler that we run in a freestanding env - it's unclear what benefit is that

Cons:
- it disables some optimization around "known functions" (basically those from the standard); if we adhere to their standard semantics and signatures, there is no need for disabling these (and actually compiler transforming `struct A a = { 0 };` into a memset could be beneficial)

So if we fix this comment, we can remove this option

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`libos/meson.build` line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/970#-NEF6DHM2pR5vv2D8DIw:-NEGUfG5-BXrBk25DVAk:b7q9c5y) ([raw file](https://github.com/gramineproject/gramine/blob/ab3b6e4ac4c62319cfe4c60504fc429357234041/libos/meson.build#L4)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I just reverted the old comment.
It means removing `ffreestanding`. Generally it turns out this option isn't really useful and I used it just because we had `no-builtin` anyway (and `ffreestanding` is sort of a "stronger version").
Pros:
- it tells the compiler that we run in a freestanding env - it's unclear what benefit is that

Cons:
- it disables some optimization around "known functions" (basically those from the standard); if we adhere to their standard semantics and signatures, there is no need for disabling these (and actually compiler transforming `struct A a = { 0 };` into a memset could be beneficial)

So if we fix this comment, we can remove this option
</blockquote></details>

Ah, got it. Makes sense now.

**Review by mkow — APPROVED** [review]
> Reviewed 17 of 17 files at r2, 1 of 9 files at r4, 7 of 8 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/970)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
