### PR TITLE
[Docs] Mention MAA plugin for RA-TLS/SecretProv

### LINKED ISSUE #1569: [Docs] Mention MAA plugin in the core documentation
### Description of the feature

Extracted from https://github.com/gramineproject/contrib/pull/38

> Should we add somewhere in core Gramine that point to the MAA versions of RA-TLS and SecretProv libs here in the contrib repo?

(MAA stands for [Microsoft Azure Attestation](https://learn.microsoft.com/en-us/azure/attestation/overview)).

Yes. My proposal will be to add a new sub-section "Vendor-specific plugins" in the "Attestation" docs page, right-before the "Third Party solutions" sub-section (https://gramine.readthedocs.io/en/stable/attestation.html#third-party-solutions).

And in this new sub-section have a list with only one item (currently) which is Microsoft Azure Attestation and a link to the corresponding contrib subdirectory.

@mkow's comment:

> I'd rather wait a bit until more users test this, but I'm also fine with mentioning it if you want. But please add a disclaimer that this is not an official part of the project yet and wasn't thoroughly reviewed in terms of security.

**Conclusion**: First test the MAA plugin a bit, then at some point add the link to our core documentation. This GitHub issue is created not to forget about this.

### Why Gramine should implement it?

People need to learn that Gramine has a (semi-official) RA-TLS plugin for MAA.

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

There is a Microsoft Azure Attestation (MAA) plugin for RA-TLS and SecretProv libraries, kept in the `contrib` repository.

Fixes #1569.

## How to test this PR? 

I temporarily enabled the Attestation page: https://gramine.readthedocs.io/en/dimakuv-docs-mention-maa-plugin/attestation.html

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1604)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1604)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1604#-NgZDO0W81QutMhVsMVT:-NgZDO0X0Niel9ObA7pB:b-oqqk5a) (no related file):*
IIUC, we agreed to postpone merging this right-before releasing v1.6. So blocking for now.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1604)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1604)* status: all files reviewed, 1 unresolved discussion

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1604)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1604#-NgZDO0W81QutMhVsMVT:-NkEcCjR0XhmMzHRvHKT:b-hx3va1) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

IIUC, we agreed to postpone merging this right-before releasing v1.6. So blocking for now.
</blockquote></details>

We're close to releasing v1.6, so I moved this PR into the merge queue.

___

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1604)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1604)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1604)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
