### PR TITLE
[Pal/Linux] Disable host-level ASLR in PAL Linux

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Gramine fork() emulation does fork()+execve() on the host system which effectively remaps PAL executable to a new address if ASLR is on. The new location could collide with other mappings that are later on sent to the child process via checkpointing mechanism (user mapped regions).

Fixes https://github.com/gramineproject/graphene/issues/2589

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkKa4o55dSv2HTFkBK6):*
This commit is the last version working with runc 1.0.1 (used by docker on ubuntu 18.04).
___
*[Scripts/docker_seccomp.json, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkKaLI-2xy-PAVhfzxh:-MkKaLI-2xy-PAVhfzxi:b-d4wclh) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Scripts/docker_seccomp.json#L1)):*
> ```JSON
> {
> ```

I didnt know where to put this file and ended up with `Scripts`.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMEIAk62guJlorMxm7):*
Weird English. I suggest to remove it. Or maybe
```
with the only difference being the enabled `personality` syscall.
`
```

___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMI1jb1W6pWjdeWzdw):*
We should put a comment somewhere that we must periodically update this seccomp file against the new versions... But we can't put the comment in JSON. So maybe just a new para here, in the commit message?
___
*[Pal/src/host/Linux/db_main.c, line 201 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMGApr0bmcpshR8yAO:-MkMGApr0bmcpshR8yAP:b-4pe3t4) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Pal/src/host/Linux/db_main.c#L201)):*
> ```C
>     if (first_process) {
>         ret = DO_SYSCALL(personality, 0xffffffffu);
>         if (ret == -1) {
> ```

`DO_SYSCALL` calls `do_syscall` which simply returns the result of `syscall` intruction: https://github.com/gramineproject/gramine/blob/40e942db6b02555cf2414f20bbd313b63f50e400/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L22

So there is no `-1`. It should be `ret < 0`
___
*[Pal/src/host/Linux/db_main.c, line 205 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMFNkW9g3ah_SMWjcx:-MkMFNkW9g3ah_SMWjcy:beq1gyw) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Pal/src/host/Linux/db_main.c#L205)):*
> ```C
>         }
>         if (!(ret & ADDR_NO_RANDOMIZE)) {
>             /* Grapthene fork() emulation does fork()+execve() on host and then sends all necessary
> ```

`Gramine` now
___
*[Pal/src/host/Linux/db_main.c, line 209 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMGNrW0q0jMpjri_7X:-MkMGNrW0q0jMpjri_7Y:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Pal/src/host/Linux/db_main.c#L209)):*
> ```C
>              * colliding with PAL executable (as it would get a new random address in the child). */
>             ret = DO_SYSCALL(personality, (unsigned int)ret | ADDR_NO_RANDOMIZE);
>             if (ret == -1) {
> ```

ditto
___
*[Scripts/docker_seccomp.json, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkKaLI-2xy-PAVhfzxh:-MkMGbtS7BcLeISl_M5c:b-a4o6o6) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Scripts/docker_seccomp.json#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I didnt know where to put this file and ended up with `Scripts`.
</blockquote></details>

@woju Does this placement make sense? Another option would be `Tools/`. One more option would be somewhere under `.ci/`, but this file is not only about CI enablement -- other users of Gramine may also want to use this file in their own Docker usages.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMEIAk62guJlorMxm7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Weird English. I suggest to remove it. Or maybe
```
with the only difference being the enabled `personality` syscall.
`
```

</blockquote></details>

TODO at rebase.
___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMI1jb1W6pWjdeWzdw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should put a comment somewhere that we must periodically update this seccomp file against the new versions... But we can't put the comment in JSON. So maybe just a new para here, in the commit message?
</blockquote></details>

What's the point of putting such info in commit message? I don't think there is any place we can put it, that would serve the purpose of reminding us.
___
*[Pal/src/host/Linux/db_main.c, line 201 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMGApr0bmcpshR8yAO:-MkOXl7hDKOvaPyxHEUn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Pal/src/host/Linux/db_main.c#L201)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`DO_SYSCALL` calls `do_syscall` which simply returns the result of `syscall` intruction: https://github.com/gramineproject/gramine/blob/40e942db6b02555cf2414f20bbd313b63f50e400/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L22

So there is no `-1`. It should be `ret < 0`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 205 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMFNkW9g3ah_SMWjcx:-MkOXlTb7vcZDE-v8UzE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Pal/src/host/Linux/db_main.c#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Gramine` now
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 209 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMGNrW0q0jMpjri_7X:-MkOXlx08qWcjkVsMhLD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Pal/src/host/Linux/db_main.c#L209)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Scripts/docker_seccomp.json, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkKaLI-2xy-PAVhfzxh:-MkOXnEEDrCcvp7pknqU:b-56dye) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Scripts/docker_seccomp.json#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Does this placement make sense? Another option would be `Tools/`. One more option would be somewhere under `.ci/`, but this file is not only about CI enablement -- other users of Gramine may also want to use this file in their own Docker usages.
</blockquote></details>

I didn't want to put this in `.ci` because it will be used outside of CI too.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkMI1jb1W6pWjdeWzdw):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of putting such info in commit message? I don't think there is any place we can put it, that would serve the purpose of reminding us.
</blockquote></details>

OK, agreed, no good place to put this reminder. Doesn't matter much, resolving.

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/89#-Mkba-MM9BhWC-4aukG7:-Mkba-MN3wwZ-O2gLqwa:blps0jd) (no related file):*
This breaks for me. I'm running Gramine inside a Docker container (with the attached JSON policy provided):

```
~/gramine/LibOS/shim/test/regression$ gramine-direct helloworld
error: Using insecure argv source. Gramine will continue application execution, but this configuration must not be used in production!
[::] error: failed to allocate memory (-12)
[::] error: failed to allocate memory (-12)
[::] error: failed to allocate memory (-12)
[::] error: failed to allocate memory (-12)
[::] error: failed to allocate memory (-12)
[::] error: Out-of-memory in library OS
```

After some investigation, it's because PAL reports vDSO range incorrectly, and LibOS tries to map over part of it. I'm trying to fix that in #96.

---
___
*[Pal/src/host/Linux/db_main.c, line 202 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkbFrNg8KrvwXIUXYNN:-MkbFrNg8KrvwXIUXYNO:bh5vn0d) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Pal/src/host/Linux/db_main.c#L202)):*
> ```C
>         ret = DO_SYSCALL(personality, 0xffffffffu);
>         if (ret == -1) {
>             INIT_FAIL(unix_to_pal_error(-ret), "retriving personality failed");
> ```

Typo: retriving -> retrieving

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Scripts/docker_seccomp.json, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkKaLI-2xy-PAVhfzxh:-MkbmHuGDYRjbh98Kd45:bplfa1g) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Scripts/docker_seccomp.json#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I didn't want to put this in `.ci` because it will be used outside of CI too.
</blockquote></details>

You can always add new dictionary, maybe `seccomp/`. Probably not `tools/`, there's only the CLI frontend.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/89#-Mkba-MM9BhWC-4aukG7:-Mkc0uPv1dcfh5vpRxfq:biwqt6e) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This breaks for me. I'm running Gramine inside a Docker container (with the attached JSON policy provided):

```
~/gramine/LibOS/shim/test/regression$ gramine-direct helloworld
error: Using insecure argv source. Gramine will continue application execution, but this configuration must not be used in production!
[::] error: failed to allocate memory (-12)
[::] error: failed to allocate memory (-12)
[::] error: failed to allocate memory (-12)
[::] error: failed to allocate memory (-12)
[::] error: failed to allocate memory (-12)
[::] error: Out-of-memory in library OS
```

After some investigation, it's because PAL reports vDSO range incorrectly, and LibOS tries to map over part of it. I'm trying to fix that in #96.

</blockquote></details>

FYI: #96 was just merged. @pwmarcz Feel free to try again (rebased on the latest master).

---
___
*[Scripts/docker_seccomp.json, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkKaLI-2xy-PAVhfzxh:-Mkc12a72u8UliT7mxdh:bacluaf) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Scripts/docker_seccomp.json#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

You can always add new dictionary, maybe `seccomp/`. Probably not `tools/`, there's only the CLI frontend.
</blockquote></details>

I don't like adding yet another top-level dir to our repo, but Borys's call. I'm fine with the current `Scripts/` dir then.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/89#-Mkba-MM9BhWC-4aukG7:-MkcHlmm7n8LxXDVNT8Z:brpwdi) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: #96 was just merged. @pwmarcz Feel free to try again (rebased on the latest master).
</blockquote></details>

Works for me now.

---
___
*[Scripts/docker_seccomp.json, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/89#-MkKaLI-2xy-PAVhfzxh:-MkcI3Gc5ZefO012UQOC:b-t8r7ga) ([raw file](https://github.com/gramineproject/gramine/blob/5727193dbc93e210c55576b94782e1d5669466ae/Scripts/docker_seccomp.json#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like adding yet another top-level dir to our repo, but Borys's call. I'm fine with the current `Scripts/` dir then.
</blockquote></details>

`Scripts/` sounds good to me, I also wouldn't want a separate directory just for this.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/89)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
