### PR TITLE
[LibOS] Add missing unlock on error return path in `shim_do_rmdir`

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Fixes a bug introduced in #282

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/307)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/307)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/307)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/307)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/307)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
