### PR TITLE
[tests] Introduce tests for PEM file signing functions

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Add new tests.
This test was requested in the PR: https://github.com/gramineproject/gramine/pull/1613

## How to test this PR? 

CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)

### CODE REVIEW

**Review by woju — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`tests/test_sgx_sign.py` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NikfAD_1tuNTzyNCGYK:-NikfAD_1tuNTzyNCGYL:bne7xfv) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L37)):*
> ```Python
> 
> def test_sign_from_pem_path():
>     key_file = os.path.join(testdir, 'files/key.pem')
> ```

If you want to have those keys as `'''`-strings in the `test_*.py` file, not as sidecars, you could use `tmp_path` pytest fixture and just write them to temporary file and load from there. See the first snippet in this doc: https://docs.pytest.org/en/7.4.x/how-to/tmp_path.html for an example. Pytest's tests usually do that so the tests are self-contained, and this also plays well with things like click's `isolated_filesystem` (https://click.palletsprojects.com/en/8.1.x/testing/#file-system-isolation), where you always need to write the file in the test setup anyway.

I'm not blocking though. If you are certain you want those keys committed to the repo as regular files, it's perfectly fine.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinNDgM21CqppdS6Z1c:-NinNDgM21CqppdS6Z1d:b-4dzizu) (no related file):*
CI failed, please check.

___
___
*[`tests/test_sgx_sign.py` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinLiEu51bQ9yCr0Buo:-NinLiEu51bQ9yCr0Bup:bejbdc0) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L28)):*
> ```Python
>     numbers = public_key.public_numbers()
>     assert numbers.e == exponent
>     assert numbers.n == modulus
> ```

Don't you want to raise a proper Exception, with some meaningful message? This check then will be more visible in code, and the failing test will be easier to decipher (rather than looking at the Python's backtrace).
___
*[`tests/test_sgx_sign.py` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinLyOiAtWbzd1vgvGT:-NinLyOiAtWbzd1vgvGU:b47eqav) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L34)):*
> ```Python
>     # if signature verification fails.
>     public_key.verify(signature_bytes, data, padding.PKCS1v15(),
>         hashes.SHA256())
> ```

This can all surely fit in one line -- we have a 100-char limit. Please fix in the whole PR; looks like your default editor limit is 80 chars.
___
*[`tests/test_sgx_sign.py` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NikfAD_1tuNTzyNCGYK:-NinMPgk5oTK96IX0atG:b-smlu7l) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L37)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If you want to have those keys as `'''`-strings in the `test_*.py` file, not as sidecars, you could use `tmp_path` pytest fixture and just write them to temporary file and load from there. See the first snippet in this doc: https://docs.pytest.org/en/7.4.x/how-to/tmp_path.html for an example. Pytest's tests usually do that so the tests are self-contained, and this also plays well with things like click's `isolated_filesystem` (https://click.palletsprojects.com/en/8.1.x/testing/#file-system-isolation), where you always need to write the file in the test setup anyway.

I'm not blocking though. If you are certain you want those keys committed to the repo as regular files, it's perfectly fine.
</blockquote></details>

I'm a bit scared to commit to the repo private keys, without making it very explicit that these are dummy testing keys.

So please either:
1. Inline the keys in the Python script as Woju recommends, or
2. Rename keys to smth like `dummy_test_key.pem`

I've seen random people on the internet raising hell that "Look, this project just committed private keys, and they call themselves security-oriented"... Let's be sure we don't get under such fire.
___
*[`tests/test_sgx_sign.py` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinMrhL7rXlwvM6oV1s:-NinMrhL7rXlwvM6oV1t:bvtf3p) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L46)):*
> ```Python
> def test_sign_from_pem_path_with_passphrase():
>     key_file = os.path.join(testdir, 'files/key_passphrase.pem')
>     passphrase = b'oshogbo'
> ```

I would prefer `test-passphrase` or something. In the couple years, people will wonder what this word means :) Not blocking though.

**Review by kailun-qin — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @oshogbo)

___
*[`tests/test_sgx_sign.py` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NikfAD_1tuNTzyNCGYK:-NinOky1-AgnIKQkZiaQ:b-4ot2i4) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L37)):*
> I'm a bit scared to commit to the repo private keys

+1, we'd better not do this.

> please either:
>   1.  Inline the keys in the Python script as Woju recommends, or
>   2.  Rename keys to smth like `dummy_test_key.pem`

Instead of hardcoding them either in the source or a "dummy"-prefixed file, can't we just generate them?

**Review by woju — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @oshogbo)

___
*[`tests/test_sgx_sign.py` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinLiEu51bQ9yCr0Buo:-NinvEed5GupNgC_f_64:bozgrk2) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't you want to raise a proper Exception, with some meaningful message? This check then will be more visible in code, and the failing test will be easier to decipher (rather than looking at the Python's backtrace).
</blockquote></details>

No, you don't. This is being executed with pytest, and pytest treats AssertionError specially, displaying left and right hand side of the assertion test: https://docs.pytest.org/en/7.1.x/how-to/assert.html
___
*[`tests/test_sgx_sign.py` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NikfAD_1tuNTzyNCGYK:-Ninw8wZ5grtnIhnYitv:bupkqvd) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L37)):*
> without making it very explicit that these are dummy testing keys.

I'd argue that they're in `tests/` directory, that's enough of an explanation for me.

But yes, generating them sounds OK.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @oshogbo)

___
*[`tests/test_sgx_sign.py` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinLiEu51bQ9yCr0Buo:-NinwmRlAQaZj0MzXiZO:bv2ubvc) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L28)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, you don't. This is being executed with pytest, and pytest treats AssertionError specially, displaying left and right hand side of the assertion test: https://docs.pytest.org/en/7.1.x/how-to/assert.html
</blockquote></details>

I'm sorry, the `assert` statement, not the `AssertionError` exeption. The point still stands, writing `assert` is the correct thing to do.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

___
*[`tests/test_sgx_sign.py` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinLiEu51bQ9yCr0Buo:-NioAOkC76H2Q1VopPOr:bjap5kf) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L28)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'm sorry, the `assert` statement, not the `AssertionError` exeption. The point still stands, writing `assert` is the correct thing to do.
</blockquote></details>

Got it, thanks for the link.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinNDgM21CqppdS6Z1c:-NioTss66za18O49KDKi:b13kzvd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

CI failed, please check.
</blockquote></details>

Sorry I should mention this in the PR.
The CI failed as we need this fix: https://github.com/gramineproject/gramine/pull/1613

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`tests/test_sgx_sign.py` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinLyOiAtWbzd1vgvGT:-NioVGU_C_6XRmdwA73d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This can all surely fit in one line -- we have a 100-char limit. Please fix in the whole PR; looks like your default editor limit is 80 chars.
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinNDgM21CqppdS6Z1c:-NioYfjr6yG7t-eGGqUA:b82mdu5) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Sorry I should mention this in the PR.
The CI failed as we need this fix: https://github.com/gramineproject/gramine/pull/1613
</blockquote></details>

Ah, then I keep this comment as blocking.

___

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinNDgM21CqppdS6Z1c:-NjBiBGOChknG9EXsv8o:bm5rkq1) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, then I keep this comment as blocking.
</blockquote></details>

@oshogbo Can you rebase this PR as #1613 was merged recently?

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinNDgM21CqppdS6Z1c:-NjDOZpE1_GEDIEg4kRS:b-xvwxy2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo Can you rebase this PR as #1613 was merged recently?
</blockquote></details>

I have rebased this PR.

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinNDgM21CqppdS6Z1c:-NjDaQKSB4hWlHdP3Ncn:b-egc6my) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I have rebased this PR.
</blockquote></details>

The tests fail in some builds, as it turns out that we don't install sgx_sign when sgx is disabled (`-Dsgx=disabled`) I will fix that.

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinNDgM21CqppdS6Z1c:-NjDaja6BpxRvRRSTYwt:bt3tdxg) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

The tests fail in some builds, as it turns out that we don't install sgx_sign when sgx is disabled (`-Dsgx=disabled`) I will fix that.
</blockquote></details>

I mean I will fix the tests, not installation of sgx_sign :)

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: 0 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`tests/test_sgx_sign.py` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1646#-NikfAD_1tuNTzyNCGYK:-NjDnkhS1IX3f25NAwUC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/75ba026ed27e6054e3e5eab4d6984f88ce9e6fbc/tests/test_sgx_sign.py#L37)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> without making it very explicit that these are dummy testing keys.

I'd argue that they're in `tests/` directory, that's enough of an explanation for me.

But yes, generating them sounds OK.
</blockquote></details>

Done.
___
*[`tests/files/key.pem` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjDSeoc1iZqp3JuPveT:-NjDnlmxEwnTkS6z-wBB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cef060c53abb0f7bd68d004d9a9889ff8d441be5/tests/files/key.pem#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we generate these keys on the fly in the test? This will reduce noise from automatic scanners and the risk that someone uses the hardcoded key for something.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`tests/test_sgx_sign.py` line 26 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjEP2hc9unt-L9Tf_f1:-NjEP2hd8u-KfNcOLUyb:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L26)):*
> ```Python
> 
>         encryption_algorithm = serialization.NoEncryption()
>         if passphrase:
> ```





_Suggestion:_
```Python
if passphrase is not None:
```

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`tests/test_sgx_sign.py` line 14 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjEaGEl1hHRUmmk4JzU:-NjEaGEmCq5T77iII-fj:b-7nte2i) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L14)):*
> ```Python
> from cryptography.hazmat.primitives.asymmetric import padding, rsa
> 
> testdir = os.path.dirname(os.path.abspath(__file__))
> ```

Not needed anymore.
___
*[`tests/test_sgx_sign.py` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjEUEwv9VD8JDfrlnj2:-NjEUEwv9VD8JDfrlnj3:b-q94aqk) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L16)):*
> ```Python
> testdir = os.path.dirname(os.path.abspath(__file__))
> 
> class TempRSAKeyFile:
> ```

Make this a pytest fixture:

```python
@pytest.fixture
def tmp_rsa_key(tmp_path):
    def tmp_rsa_key(passphrase=None):
        key_path = tmp_path / 'key.pem'
        with open(key_path, 'wb') as file:
            file.write(passphrase or b'123')  # (write the key, not this thing)
        return key_path
    return tmp_rsa_key

def test_key(tmp_rsa_key):
    path = tmp_rsa_key()
    with open(path) as file:
        assert file.read() == '123'

def test_key(tmp_rsa_key):
    path = tmp_rsa_key(b'pass')
    with open(path) as file:
        assert file.read() == 'pass'
```

- `tmp_path` is a magic thing from pytest that makes a temporary directory and removes it after the test function is finished
- `tmp_rsa_key` argument in `test_` function receives the returned value of the function (again, evaluated by pytest magic), not the function itself, hence function in function (but this allows to have an argument)
___
*[`tests/test_sgx_sign.py` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjETyguB34yNaLnFIWv:-NjETyguB34yNaLnFIWw:b-e89vos) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L64)):*
> ```Python
> @pytest.mark.sgx
> def test_sign_from_pem_path():
>     # pylint: disable=import-outside-toplevel
> ```

This disabling comment should be file-wide, I don't expect in this file any function that would *not* have import inside...
___
*[`tests/test_sgx_sign.py` line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjE_q5U6pXt-BQ6uo1a:-NjE_q5U6pXt-BQ6uo1b:b-he44zq) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L81)):*
> ```Python
> 
>     data = b'lorem ipsum dolor sit amet consectetur adipiscing elit'
>     passphrase = b'randompassphrase'
> ```

N/b, but if we don't want to hardcode things, those two can be pulled from `os.urandom()` function. Just saying.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinNDgM21CqppdS6Z1c:-NjGrgA6EI74Uo8qHMDJ:b-2p3glb) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I mean I will fix the tests, not installation of sgx_sign :)
</blockquote></details>

It still fails.

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`tests/test_sgx_sign.py` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjEUEwv9VD8JDfrlnj2:-NjHEutz3Hx4h-rXheXB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Make this a pytest fixture:

```python
@pytest.fixture
def tmp_rsa_key(tmp_path):
    def tmp_rsa_key(passphrase=None):
        key_path = tmp_path / 'key.pem'
        with open(key_path, 'wb') as file:
            file.write(passphrase or b'123')  # (write the key, not this thing)
        return key_path
    return tmp_rsa_key

def test_key(tmp_rsa_key):
    path = tmp_rsa_key()
    with open(path) as file:
        assert file.read() == '123'

def test_key(tmp_rsa_key):
    path = tmp_rsa_key(b'pass')
    with open(path) as file:
        assert file.read() == 'pass'
```

- `tmp_path` is a magic thing from pytest that makes a temporary directory and removes it after the test function is finished
- `tmp_rsa_key` argument in `test_` function receives the returned value of the function (again, evaluated by pytest magic), not the function itself, hence function in function (but this allows to have an argument)
</blockquote></details>

Done.
___
*[`tests/test_sgx_sign.py` line 26 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjEP2hc9unt-L9Tf_f1:-NjHB6JqBrD26rDxUZvi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L26)):*
> ```Python
> 
>         encryption_algorithm = serialization.NoEncryption()
>         if passphrase:
> ```

Done.
___
*[`tests/test_sgx_sign.py` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjETyguB34yNaLnFIWv:-NjHB93uCVwvLJfMWANl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L64)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This disabling comment should be file-wide, I don't expect in this file any function that would *not* have import inside...
</blockquote></details>

Done.
___
*[`tests/test_sgx_sign.py` line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjE_q5U6pXt-BQ6uo1a:-NjHB9jGE22sObknpvLH:bxnpgyx) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L81)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

N/b, but if we don't want to hardcode things, those two can be pulled from `os.urandom()` function. Just saying.
</blockquote></details>

I don't think this passphrase really matters here.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: 3 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`tests/test_sgx_sign.py` line 14 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjEaGEl1hHRUmmk4JzU:-NjHExpZ9cBYKSbPAl4m:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not needed anymore.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @woju)

___
*[`tests/test_sgx_sign.py` line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjE_q5U6pXt-BQ6uo1a:-NjIeTaI4ND4q7YbLcG0:bg22jst) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L81)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I don't think this passphrase really matters here.
</blockquote></details>

I won't block, but generating a random one takes almost the same amount of space, so why not :)

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1646#-NinNDgM21CqppdS6Z1c:-NjJClpR-zZcJL3Br6Xg:b-amjj99) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It still fails.
</blockquote></details>

It doesn't any longer.

___

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @woju)

___
*[`tests/test_sgx_sign.py` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjEUEwv9VD8JDfrlnj2:-NjLtqWmBVKu0d9yCkSK:bo8x5q4) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L16)):*
> `tmp_rsa_key` argument in `test_` function receives the returned value of the function (again, evaluated by pytest magic), not the function itself, hence function in function (but this allows to have an argument)

I don't like this magic, as it is very hard to reason about (if you don't know that it's what PyTest does under the hood). But I guess PyTest had reasons to do it this way...

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`tests/test_sgx_sign.py` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjEUEwv9VD8JDfrlnj2:-NjMi-oQ2FxmTIcW8axH:bygo3rl) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> `tmp_rsa_key` argument in `test_` function receives the returned value of the function (again, evaluated by pytest magic), not the function itself, hence function in function (but this allows to have an argument)

I don't like this magic, as it is very hard to reason about (if you don't know that it's what PyTest does under the hood). But I guess PyTest had reasons to do it this way...
</blockquote></details>

Yea, me neither. I preferred the version with a TMP file, especially since this also annoys pylint. But what can you do if this is a standard?

**Review by woju — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`tests/test_sgx_sign.py` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1646#-NjEUEwv9VD8JDfrlnj2:-NjN4xo9-BTRnR7naWxK:b-zb3gss) ([raw file](https://github.com/gramineproject/gramine/blob/15edeb15a5dc7428b4e49dd4907dfdb24273b1ca/tests/test_sgx_sign.py#L16)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yea, me neither. I preferred the version with a TMP file, especially since this also annoys pylint. But what can you do if this is a standard?
</blockquote></details>

It's easy when you get used to it, and allows to write quite clean, very readable tests with less boilerplate. That counts when you are reading those tests to check that everything is obviously correct.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1646)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
