### PR TITLE
[LibOS] Inform user about malformed URI

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Just more logs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1068)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1068)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`libos/src/fs/libos_fs.c` line 442 at r1](https://reviewable.io/reviews/gramineproject/gramine/1068#-NI8M9ge9GbTjObFhgpi:-NI8UJCk7-LHROpj9bmT:b-s546pe) ([raw file](https://github.com/gramineproject/gramine/blob/ea1eee2096a902e3918797cf7cd61a97bd7e6fce/libos/src/fs/libos_fs.c#L442)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Do we want a function name?
In this PR (https://github.com/gramineproject/gramine/pull/1040) I'm trying to clean this up:
</blockquote></details>

Idk, might be useful, but I won't insist

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1068)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`libos/src/fs/libos_fs.c` line 442 at r1](https://reviewable.io/reviews/gramineproject/gramine/1068#-NI8M9ge9GbTjObFhgpi:-NIByYeEEDTXfYcpgNZD:b-w8bufd) ([raw file](https://github.com/gramineproject/gramine/blob/ea1eee2096a902e3918797cf7cd61a97bd7e6fce/libos/src/fs/libos_fs.c#L442)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Idk, might be useful, but I won't insist
</blockquote></details>

Yeah, I'd also prefer the approach in #1040, and not adding the func name in this PR

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1068)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1068)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`libos/src/fs/libos_fs.c` line 442 at r1](https://reviewable.io/reviews/gramineproject/gramine/1068#-NI8M9ge9GbTjObFhgpi:-NIFPLU14li8-0LJDgNE:bs2s27x) ([raw file](https://github.com/gramineproject/gramine/blob/ea1eee2096a902e3918797cf7cd61a97bd7e6fce/libos/src/fs/libos_fs.c#L442)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I'd also prefer the approach in #1040, and not adding the func name in this PR
</blockquote></details>

fwiw I don't like 1040 that much, but it's also fine without func name here

**Review by yamahata — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1068#-:-NIFxnuQDE8IwgBDNZAE:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1068)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
