### PR TITLE
Fix argument for SGX client

### PR DESCRIPTION
**Pull request by liangintel**
## Description of the changes
When compiling for running DCAP client in SGX, should make with options
as: make app dcap, previously one is not correct.

When running DCAP client in SGX, should add the arguments in cmd.

## How to test this PR?
N/A: No functional change to the code.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/225)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/225)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @liangintel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/225#-MocDFqW4BHzXxlTeZkZ:-MocDFqW4BHzXxlTeZk_:brffvy2) (no related file):*
I verified that this was indeed a bug in our README. I also verified that the proposed fix is correct and makes sense. Thanks for this PR, @liangintel!

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/225#-MocCiV_4aYQH-Ha-lOo):*
Should prepend `[CI-Examples]`. And in general, modify the commit message slightly; currently the commit message is too verbose. Basically, we just fixed the command line to execute the in-SGX-enclave DCAP client in the README.

@liangintel You don't need to do anything. I will fix the commit message myself, during the final git rebase.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by liangintel** [comment]
thanks Dmitrii

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/225)* status: all files reviewed, 1 unresolved discussion (waiting on @liangintel)

**Review by liangintel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/225)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/225#-MocCiV_4aYQH-Ha-lOo):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should prepend `[CI-Examples]`. And in general, modify the commit message slightly; currently the commit message is too verbose. Basically, we just fixed the command line to execute the in-SGX-enclave DCAP client in the README.

@liangintel You don't need to do anything. I will fix the commit message myself, during the final git rebase.
</blockquote></details>

OK.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/225)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/225#-MocCiV_4aYQH-Ha-lOo):*
<details><summary><i>Previously, liangintel wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/225)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
