### PR TITLE
[Docs] Update Gramine Docker image usage

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 
- Removed outdated information about the supported image distros
- Updated Docker run command to include provisioning device

## How to test this PR? 
CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1905)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1905)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`Documentation/installation.rst` line 114 at r1](https://reviewable.io/reviews/gramineproject/gramine/1905#-O-AMoVZ3r8HYGNXoH4h:-O-AMoVZ3r8HYGNXoH4i:bfqve17) ([raw file](https://github.com/gramineproject/gramine/blob/0b3f90b2a8bf536a44de9ed9fbded37dc6288eaa/Documentation/installation.rst#L114)):*
> ```reStructuredText
> To run the Gramine image via Docker, the recommended command is::
> 
>     docker run --device /dev/sgx_enclave --device /dev/sgx_provision -it gramineproject/gramine
> ```

Actually, why would it be needed inside the Docker container? What is the scenario where you required it?

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1905)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/installation.rst` line 114 at r1](https://reviewable.io/reviews/gramineproject/gramine/1905#-O-AMoVZ3r8HYGNXoH4h:-O-ANi_243eRi2o8w6ad:b-u7m4lm) ([raw file](https://github.com/gramineproject/gramine/blob/0b3f90b2a8bf536a44de9ed9fbded37dc6288eaa/Documentation/installation.rst#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why would it be needed inside the Docker container? What is the scenario where you required it?
</blockquote></details>

In my case, users would like to try out some attestation applications inside our provided docker image. Also, from our dockerhub -- "To be able to spawn architectural enclaves the AESM service needs access to `/dev/sgx_provision` device. You need to pass both of these devices when running `docker`, if you want to use `gramine-sgx".

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1905)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`Documentation/installation.rst` line 104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1905#-O-AT-eNDDzdmhyG2Gx6:-O-AT-eNDDzdmhyG2Gx7:b-6i8ebv) ([raw file](https://github.com/gramineproject/gramine/blob/0b3f90b2a8bf536a44de9ed9fbded37dc6288eaa/Documentation/installation.rst#L104)):*
> ```reStructuredText
> Gramine binaries and tools, as well as the pre-requisite packages to run
> applications under Gramine. The only currently available Gramine image is based
> on Ubuntu 20.04. The only requirement on the host system is a Linux kernel with
> ```

Hm, can you remove this mention of "only available image"? It's not true, and also I don't want to maintain this -- we'll forget anyway to update this snippet. So I would just remove it.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1905)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/installation.rst` line 104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1905#-O-AT-eNDDzdmhyG2Gx6:-O-AWAJg7-JJqIwoMb5J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0b3f90b2a8bf536a44de9ed9fbded37dc6288eaa/Documentation/installation.rst#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, can you remove this mention of "only available image"? It's not true, and also I don't want to maintain this -- we'll forget anyway to update this snippet. So I would just remove it.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1905)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1905)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1905)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest Docs please (network was unavailable on the node, unrelated)

**Comment by dimakuv** [comment]
Jenkins, retest Docs please (network was unavailable on the node, unrelated)

**Comment by dimakuv** [comment]
Jenkins, retest Docs please (network was unavailable on the node, now should be fixed)

**Pull request merged**
