### PR TITLE
Use `#pragma once` instead of handcrafted header guards

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Cons of `#pragma once`:
- not in C standard
- compiler-specific behavior in cases like including the same file through different {soft,hard}links, or multiple copies of the same header in the repo

Pros:
- less boilerplate
- works well in practice
- no need to update it when moving/renaming a header file
- handcrafted header guards are error prone (easy to have non-matching `#ifndef` and `#define`, easy to collide with other file header guards, and especially prone to copy-paste errors)

The cases with {soft,hard}links and using multiple copies of the same headers are rather exotic and we don't ever plan to have them in our codebase.

Overall: `#pragma once` works well in practice and it's much more likely that we'll introduce a bug with handcrafted include guards than with `#pragma once`.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 120 of 120 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`Documentation/devel/coding-style.rst` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/669#-N54y3_3-mVBIjXF06oN:-N54y3_3-mVBIjXF06oO:bp785ly) ([raw file](https://github.com/gramineproject/gramine/blob/e7508ccdae77f546f4389d5926388421698aef55/Documentation/devel/coding-style.rst#L109)):*
> ```reStructuredText
>    #. Gramine's headers.
> 
> #. Assignments may be aligned when assigning some structurized data (e.g. struct
> ```

I would move the new point before this line, because previous talks about includes too (albeit in a different context)
___
*[`LibOS/include/arch/x86_64/gramine_entry_api.h` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/669#-N54zk6OCzSMACMbDAGK:-N54zk6OCzSMACMbDAGL:b-sx5fwv) ([raw file](https://github.com/gramineproject/gramine/blob/5faa9eb4f11592e379fdc4319a043def557f2422/LibOS/include/arch/x86_64/gramine_entry_api.h#L14)):*
> ```objc
>  */
> 
> #ifndef GRAMINE_ENTRY_API_H_
> ```

I Would make this file an exception. It's included from outside, so who knows what magic with hard/soft links people will do on it.
___
*[`Pal/include/pal/pal.h` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/669#-N550vb3C65u1-bZUeBY:-N550vb3C65u1-bZUeBZ:b-qnsrep) ([raw file](https://github.com/gramineproject/gramine/blob/e7508ccdae77f546f4389d5926388421698aef55/Pal/include/pal/pal.h#L17)):*
> ```objc
> #include <stdnoreturn.h>
> 
> // TODO: fix this (but see x86_64/pal.h)
> ```

Please use full repo path, I don't even know which file this talks about (there is only one `pal.h`, this one)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: 115 of 120 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`Documentation/devel/coding-style.rst` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/669#-N54y3_3-mVBIjXF06oN:-N554bG9-wtx4Bxv35S4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e7508ccdae77f546f4389d5926388421698aef55/Documentation/devel/coding-style.rst#L109)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would move the new point before this line, because previous talks about includes too (albeit in a different context)
</blockquote></details>

Done.
___
*[`LibOS/include/arch/x86_64/gramine_entry_api.h` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/669#-N54zk6OCzSMACMbDAGK:-N555O4y1Nv9NLVYQNRf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5faa9eb4f11592e379fdc4319a043def557f2422/LibOS/include/arch/x86_64/gramine_entry_api.h#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I Would make this file an exception. It's included from outside, so who knows what magic with hard/soft links people will do on it.
</blockquote></details>

Done.
___
*[`Pal/include/pal/pal.h` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/669#-N550vb3C65u1-bZUeBY:-N555VVGE74p0_oz0pru:b4z986l) ([raw file](https://github.com/gramineproject/gramine/blob/e7508ccdae77f546f4389d5926388421698aef55/Pal/include/pal/pal.h#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use full repo path, I don't even know which file this talks about (there is only one `pal.h`, this one)
</blockquote></details>

Oh, that's actually a mistake on my side in the header name. But I can also extend the whole path in addition to fixing it.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/include/api.h` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N557cgV4qIVg3pzuZLL:-N557cgV4qIVg3pzuZLM:b-k9wzrx) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/common/include/api.h#L17)):*
> ```objc
> #endif
> 
> #define INSIDE_API_H
> ```

Don't we want to move it just after standard includes? (assert can be our own)
___
*[`LibOS/include/arch/x86_64/gramine_entry_api.h` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N557vsV9caBbSig6P_z:-N557vsV9caBbSig6Pa-:b-kymsm0) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/LibOS/include/arch/x86_64/gramine_entry_api.h#L15)):*
> ```objc
> 
> /* We don't use `#pragma once` here because this header is used by our custom glibc build, and
>  * glibc's codebase and buildsystem is a mess. */
> ```

It's also a public api - people can build their own libraries against it (it's not only our glibc).

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: 119 of 120 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/include/api.h` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N557cgV4qIVg3pzuZLL:-N558o8k90Q5BCx5v-f-:b-9ojdfp) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/common/include/api.h#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we want to move it just after standard includes? (assert can be our own)
</blockquote></details>

Ah, right, overlooked the assert.
___
*[`LibOS/include/arch/x86_64/gramine_entry_api.h` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N557vsV9caBbSig6P_z:-N558uj9Dd1zOUaQFx1R:b-yr0yze) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/LibOS/include/arch/x86_64/gramine_entry_api.h#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's also a public api - people can build their own libraries against it (it's not only our glibc).
</blockquote></details>

But this works in normal cases. We're only afraid about glibc because it's known for unholy hacks.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Pal/include/pal/pal.h` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/669#-N550vb3C65u1-bZUeBY:-N55GA0QDAlAEdMCzGu5:bong9ye) ([raw file](https://github.com/gramineproject/gramine/blob/e7508ccdae77f546f4389d5926388421698aef55/Pal/include/pal/pal.h#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Fix what? What is going on here? The referred file doesn't seem to have any explanations too.
</blockquote></details>

It says: `This header is usable only inside pal.h (due to a cyclic dependency)`. So, that's the explanation why this hack is currently needed.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/include/arch/x86_64/gramine_entry_api.h` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N557vsV9caBbSig6P_z:-N55Hg_y7vof2A8bUY2K:b-qthy4f) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/LibOS/include/arch/x86_64/gramine_entry_api.h#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd say it's their own choice to do such hacks (and you _really_ need to do crazy things to notice any problems with `#pragma once`). Anyways, this works, it's only about the explanation comment now, and IMO we wouldn't change it if not for glibc.
</blockquote></details>

But we never changed it due to glibc in the first place. It's our own header used in our own glibc patches, so there is no risk of failures there.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`LibOS/include/arch/x86_64/gramine_entry_api.h` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N557vsV9caBbSig6P_z:-N55IanD6FCt2SCxMm5H:boiesac) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/LibOS/include/arch/x86_64/gramine_entry_api.h#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But we never changed it due to glibc in the first place. It's our own header used in our own glibc patches, so there is no risk of failures there.
</blockquote></details>

Hmm, I changed it for the glibc ;)
There _is_ a risk, we are not sure what glibc does with these files during build (may copy them a few times, or something) and it also may start causing troubles in new glibcs. If not for glibc I wouldn't really change it.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/include/arch/x86_64/gramine_entry_api.h` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N557vsV9caBbSig6P_z:-N55KIIv-A9itRRoluDS:b69yl19) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/LibOS/include/arch/x86_64/gramine_entry_api.h#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I changed it for the glibc ;)
There _is_ a risk, we are not sure what glibc does with these files during build (may copy them a few times, or something) and it also may start causing troubles in new glibcs. If not for glibc I wouldn't really change it.
</blockquote></details>

I don't understand why the argument is different for glibc and for other usages (by external users, outside of our control).

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`LibOS/include/arch/x86_64/gramine_entry_api.h` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N557vsV9caBbSig6P_z:-N55Kki54pRh_QllE4aF:bhai4qc) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/LibOS/include/arch/x86_64/gramine_entry_api.h#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't understand why the argument is different for glibc and for other usages (by external users, outside of our control).
</blockquote></details>

The other users use this header in their projects intentionally, while in glibc it's us who glue it into glibc codebase and outside of glibc devs control. If someone else intentionally uses this header in their project and then does some crazy hacks then if it breaks, it's on their own request.

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: 120 of 131 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/669#-N55UcoR8copTW2lsY_J:-N55X2M4ByUrPhGA3SR4:b-kc9hny) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I found at least one header file that didn't have the guard: `enclave_ocalls.h`. We probably have a couple of other header files like this, that don't have any protection at all.

Could you please try to find them and add `#pragma once` to them?
</blockquote></details>

Good catch! Found quite a lot of them...
Anyways, fixed, hopefully all.

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: 120 of 131 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`Documentation/devel/coding-style.rst` line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N55a6mQ4Ya1iEnwbk5U:-N55bvJXCvL9pildVmw-:baxrwhn) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/Documentation/devel/coding-style.rst#L99)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This could use some explanation/rationale, like that in PR description, for people who would like to ever revisit the decision. We know it's non-standard, but it's supported by the compilers we're interested in, and we think it's less error-prone.
</blockquote></details>

I considered it, but then decided that this guide should be concise and quick to read / look up a specific rule, and explaining this choice requires at least a paragraph of text. Also, other rules here are not explained either.
I guess you can always find this commit or this PR if you want to check the arguments in the future.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: 120 of 131 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/devel/coding-style.rst` line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/669#-N55a6mQ4Ya1iEnwbk5U:-N55r8BP4n-10JWaCKmI:bs4ixp3) ([raw file](https://github.com/gramineproject/gramine/blob/243f797a82c9652d5c2371e86ab20900650b0a8a/Documentation/devel/coding-style.rst#L99)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I considered it, but then decided that this guide should be concise and quick to read / look up a specific rule, and explaining this choice requires at least a paragraph of text. Also, other rules here are not explained either.
I guess you can always find this commit or this PR if you want to check the arguments in the future.
</blockquote></details>

OK, fair enough.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/669)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
