### PR TITLE
Mock ocall in sgx_pthread.edl for in-enclave RA client

### PR DESCRIPTION
**Pull request by duanbing**
## Description of the changes 
Per as https://github.com/intel/SGXDataCenterAttestationPrimitives/pull/193,  some thread related `ocall` were added.  we here mock those APIs for graphene `ra-tls`.

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/63)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/63)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @duanbing)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/63#-Mje6kSf1TQum5YEFzb1):*
I don't think this was intended. Please verify your PRs before publishing ;)
___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/63#-Mje6lV6CYdlP-QSrGFY):*
ditto

**Comment by duanbing** [comment]
hi, @mkow  just check that, I reviewed the `contributing` instructions, I should run`git commit -s`, not `git commit --amend --no-edit --signoff`;  secondly, I should use `foo`, not the repo name,  as the branch name.  Is this right?

**Comment by mkow** [comment]
@duanbing: First, please use Reviewable for the review, otherwise discussions are not properly threaded. You'll also see my comment in context then.
Overall, did you actually verify what you pushed in this PR?

**Comment by duanbing** [comment]
@mkow,  For sure,  I ran the  Regression Tests according to contributing instructions (1xfailed, `test_pal.py::TC_20_SingleProcess::test_301_memory_nosgx XFAIL`), and the in-enclave client mode of `ra-tls-mbedtls` which was failed due to `undefined symbol pthread_create_ocall`.   Did you mean this?

**Review by dimakuv — CHANGES_REQUESTED** [review]
@duanbing Let's go through the problems in this PR.

- https://graphene.readthedocs.io/en/latest/devel/contributing.html#pull-requests says "Address a single problem." However, your PR contains 4 commits. The first of these commits is `[tests] Skip some flaky and unreliable LTP tests` by Michal, which is *not your change*. So this PR addresses two unrelated problems (one of which was already fixed in the master branch by Michal).

- The same section in the Contributing Instructions says "Be signed-off by the author of the PR in git". This means that every commit in your PR needs to have a "Signed-off-by" line. NOT the first commit (which is not your commit anyway, it is Michal's), but ALL commits. https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for

- https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle says "Merge commits are never allowed". You have not one, but TWO merge commits in this PR. I understand that this may be your first time using git, but you should educate yourself a bit about git and its flows. E.g., a good reference is: https://medium.com/singlestone/a-git-workflow-using-rebase-1b1210de83e5

- https://graphene.readthedocs.io/en/latest/devel/contributing.html#branch-names says "For example, if user jane is adding feature foo, the branch should be named: jane/foo." So you should *not* use the `master` branch in your forked repo for the PR, instead you should create a branch with the name like `duanbing/add-mock-ocalls-sgx-pthread-in-ratls`.

Actually, the root of your problems is the last bullet item -- you didn't create a new branch but instead you modified the `master` branch in your forked repo. This **always leads to problems**. Never do it, not only for Graphene/Gramine, but also for other projects.

> I should run `git commit -s`, not `git commit --amend --no-edit --signoff`, or just remove the signed-off?

When you create a new commit, just do `git commit -s`. When you need to modify the last commit, just do `git commit --amend -s`. also, you can manually add the line `Signed-off-by: duanbing <hibduan@gmail.com>` at the end of the commit message, if you so desire.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/63#-:-MjhNU2W7h8F1RW4qROO:byzj10p)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @duanbing and @mkow)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/63#-Mje6kSf1TQum5YEFzb1):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think this was intended. Please verify your PRs before publishing ;)
</blockquote></details>

@duanbing You cannot sign off on the commits that you didn't write. A "sign off" means that "you have created the patch in question" (https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for).
___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/63#-Mje6lV6CYdlP-QSrGFY):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Merge commits should not exist in the PR at all.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/63)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @duanbing and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/63#-MjhRHiO8ZFYqwex5q3R:-MjhRHiO8ZFYqwex5q3S:byvryqv) (no related file):*
By the way, the change itself in this PR is reasonable -- the Intel SGX SDK/PSW libraries added a couple new functions, and we need to mock them in our "RA-TLS verifier inside of an SGX enclave" lib.

---

**Review by duanbing — COMMENTED** [review]
Thanks for your explanation. I'll submit another PR.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/63#-:-Mjhb11R8-O37rfNRlCK:bzfnqwy)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/63#-MjhRHiO8ZFYqwex5q3R:-MjhcBeB57QhJjv-oTFg:bh0z9t5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, the change itself in this PR is reasonable -- the Intel SGX SDK/PSW libraries added a couple new functions, and we need to mock them in our "RA-TLS verifier inside of an SGX enclave" lib.
</blockquote></details>

Yes, this is the issue I met in my project.

---
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/63#-Mje6kSf1TQum5YEFzb1):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@duanbing You cannot sign off on the commits that you didn't write. A "sign off" means that "you have created the patch in question" (https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for).
</blockquote></details>

OK. 
___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/63#-Mje6lV6CYdlP-QSrGFY):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Merge commits should not exist in the PR at all.
</blockquote></details>

Will fix it in another PR.

**Pull request closed without merging**
