### PR TITLE
[Pal] Refactor `handle_serialize()`

### PR DESCRIPTION
**Pull request by yao-ji**
## Description of the changes 

Rename some variables to make the code more readable. Also checked the remaining pointers inside handle. There is no need to serialize those pointers.

## How to test this PR? 
Run pal regression test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/988)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/988)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @yao-ji)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEky7Qh8gOKgGpLgZLz):*




_Suggestion:_
```
[PAL]
```
___
*[`pal/src/host/linux/pal_streams.c` line 72 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl6paK0CVHsfO8A-cd:-NEl6paK0CVHsfO8A-ce:bkaw8t5) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux/pal_streams.c#L72)):*
> ```C
>             break;
>         case PAL_TYPE_DIR:
>             field = handle->dir.realpath;
> ```

Cannot `handle->dir.realpath` be `NULL`? (old code checked that, idk if it was needed or not)
___
*[`pal/src/host/linux/pal_streams.c` line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl7x3Z1uhsAbM9KJNk:-NEl7x3_CYpof_udbAju:b-2efwa0) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux/pal_streams.c#L74)):*
> ```C
>             field = handle->dir.realpath;
>             field_size = strlen(handle->dir.realpath) + 1;
>             /* no need to serialize buf/ptr/end */
> ```

Then please set these fields to some valid values (`NULL` maybe) in deserialize
ditto for all other types
___
*[`pal/src/host/linux/pal_streams.c` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl7Q-m7E1OPTrMV2O-:-NEl7Q-m7E1OPTrMV2O0:b-idh96) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux/pal_streams.c#L82)):*
> ```C
>             /* processes have no fields to serialize */
>             break;
>         case PAL_TYPE_THREAD:
> ```

Actually why did you add these types here? Previously `-PAL_ERROR_INVAL` was returned for them, now they will be serialized
___
*[`pal/src/host/linux/pal_streams.c` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl7XlYCpweycq4IkrI:-NEl7XlYCpweycq4IkrJ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux/pal_streams.c#L161)):*
> ```C
>         case PAL_TYPE_PROCESS:
>             break;
>         case PAL_TYPE_THREAD:
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl7bbmC-Vea8WWfp7e:-NEl7bbmC-Vea8WWfp7f:b-x915y7) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L43)):*
> ```C
> 
> static ssize_t handle_serialize(PAL_HANDLE handle, void** data) {
>     int ret = 0;
> ```

This change is not needed, please revert
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl8BFu3q2BVXK7NT8T:-NEl8BFu3q2BVXK7NT8U:b-2efwa0) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L54)):*
> ```C
>             field = handle->file.realpath;
>             field_size = strlen(handle->file.realpath) + 1;
>             /* no need to serialize chunk_hashes & umem */
> ```

Then please set these fields to some valid values (`NULL` maybe) in deserialize
ditto for all other types
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl8bUN5UIDPWJTljko:-NEl8bUN5UIDPWJTljkp:b-yocpe4) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L90)):*
> ```C
>             }
>             break;
>         case PAL_TYPE_THREAD:
> ```

ditto (why add new types)
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl8pCX1frOA3UMSXki:-NEl8pCX1frOA3UMSXkj:btsnzjy) ([raw file](https://github.com/gramineproject/gramine/blob/546c598b694d091121babc215bf6b9f9f52bbb4d/pal/src/host/linux-sgx/pal_streams.c#L107)):*
> ```C
>         memcpy(buffer + hdlsz, d, dsz);
> 
>     ret = 0;
> ```

Please just set the values here



_Suggestion:_
```C
*data = buffer;
ret = buffer_size;
```
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl93Xy09pBcS7zxcDK:-NEl93Xy09pBcS7zxcDL:b-33b6k6) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L123)):*
> ```C
> 
>     *data = buffer;
>     return buffer_size;
> ```

See comment above



_Suggestion:_
```C
    return ret;
```
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 199 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl99Zm-I97dtitEoYs:-NEl99Zm-I97dtitEoYt:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L199)):*
> ```C
>             }
>             break;
>         case PAL_TYPE_THREAD:
> ```

ditto

**Review by yao-ji — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/988)* status: 0 of 2 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEky7Qh8gOKgGpLgZLz):*
Done.
___
*[`pal/src/host/linux/pal_streams.c` line 72 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl6paK0CVHsfO8A-cd:-NEoNvjcBam6dsoxX6qV:b-pfs2ew) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux/pal_streams.c#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Cannot `handle->dir.realpath` be `NULL`? (old code checked that, idk if it was needed or not)
</blockquote></details>

It is set in `dir_open()` and never set to `NULL`, which is the same as `file.realpath`.
___
*[`pal/src/host/linux/pal_streams.c` line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl7x3Z1uhsAbM9KJNk:-NEoOeAP2WPIeDQca5TX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux/pal_streams.c#L74)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then please set these fields to some valid values (`NULL` maybe) in deserialize
ditto for all other types
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl7Q-m7E1OPTrMV2O-:-NEoOgOkCza-CPWm6ML0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux/pal_streams.c#L82)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually why did you add these types here? Previously `-PAL_ERROR_INVAL` was returned for them, now they will be serialized
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl7XlYCpweycq4IkrI:-NEoOjslDhEfLTH4xw89:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux/pal_streams.c#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl7bbmC-Vea8WWfp7e:-NEoOk_k-6BDu8fx3KvV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This change is not needed, please revert
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl8BFu3q2BVXK7NT8T:-NEoOmczDFQJI5WVTu7i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then please set these fields to some valid values (`NULL` maybe) in deserialize
ditto for all other types
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl8bUN5UIDPWJTljko:-NEoOnEFBembBfJ4lRhi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L90)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (why add new types)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl8pCX1frOA3UMSXki:-NEoOoNI6IrFZr53WhwH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/546c598b694d091121babc215bf6b9f9f52bbb4d/pal/src/host/linux-sgx/pal_streams.c#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please just set the values here
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl93Xy09pBcS7zxcDK:-NEoOqdc28tDadvauG9K:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L123)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

See comment above
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 199 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEl99Zm-I97dtitEoYs:-NEoOtbd2pGXptTPx9lV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1518f58b4405c33156dd62732c8bf02a6c0b56c2/pal/src/host/linux-sgx/pal_streams.c#L199)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/988)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @yao-ji)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/988#-NEky7Qh8gOKgGpLgZLz):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not how fixups work in git, I would recommend you reading about it :)
We will fix that on final rebase, so you don't have to change anything now

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/988)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @yao-ji)

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/988)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @yao-ji)

___
*[`pal/src/host/linux-sgx/pal_streams.c` line 61 at r2](https://reviewable.io/reviews/gramineproject/gramine/988#-NEvB-Zh7I-Vxapq3up5:-NEvB-Zi9sTFALyCgCxX:by45jpw) ([raw file](https://github.com/gramineproject/gramine/blob/cb33f711ef0d16110b14f11768ed6f879c5151e2/pal/src/host/linux-sgx/pal_streams.c#L61)):*
> ```C
>             if (handle->pipe.ssl_ctx) {
>                 free_field = true;
>                 ret = _PalStreamSecureSave(handle->pipe.ssl_ctx, (const uint8_t**)&field, &field_size);
> ```

This line is too long.
The limit is 100.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 85 at r2](https://reviewable.io/reviews/gramineproject/gramine/988#-NEvAmN37UMlEj6hKi8Z:-NEvAmN37UMlEj6hKi8_:b-rqxvo7) ([raw file](https://github.com/gramineproject/gramine/blob/cb33f711ef0d16110b14f11768ed6f879c5151e2/pal/src/host/linux-sgx/pal_streams.c#L85)):*
> ```C
>             if (handle->process.ssl_ctx) {
>                 free_field = true;
>                 ret = _PalStreamSecureSave(handle->process.ssl_ctx, (const uint8_t**)&field, &field_size);
> ```

ditto.



_Code quote:_
```C
ret = _PalStreamSecureSave(handle->process.ssl_ctx, (const uint8_t**)&field, &field_size);
```

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/988)* status: all files reviewed, 2 unresolved discussions (waiting on @oshogbo)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/988)* status: all files reviewed, 2 unresolved discussions (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_streams.c` line 226 at r3](https://reviewable.io/reviews/gramineproject/gramine/988#-NF9yDuNEc1SNI-FA24J:-NF9yDuNEc1SNI-FA24K:bcgjvre) ([raw file](https://github.com/gramineproject/gramine/blob/73e087f690b0e87dc202b191ca09b0a0841a4d6f/pal/src/host/linux-sgx/pal_streams.c#L226)):*
> ```C
>     int fd = target_process->process.stream;
> 
>     /* first send hdl_hdr so the recipient knows how many FDs were transferred + how large is cargo */
> ```

Why this change?

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/988)* status: all files reviewed, 2 unresolved discussions (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_streams.c` line 226 at r3](https://reviewable.io/reviews/gramineproject/gramine/988#-NF9yDuNEc1SNI-FA24J:-NF9z2WO8hjhc1BC3jJ_:b9wvnkj) ([raw file](https://github.com/gramineproject/gramine/blob/73e087f690b0e87dc202b191ca09b0a0841a4d6f/pal/src/host/linux-sgx/pal_streams.c#L226)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

It was more than 100 chars per line, so shortened it

**Pull request merged**
