### PR TITLE
Release 1.8

### PR DESCRIPTION
**Pull request by woju**
Release PR for v1.8

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2022)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2022)* status: 0 of 85 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "TODO" found in commit messages' one-liners (waiting on @woju)

___
*[`debian/changelog` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/2022#-O9MPhlj2Mw7bxrql-Ho:-O9MPhlj2Mw7bxrql-Hp:bvz3610) ([raw file](https://github.com/gramineproject/gramine/blob/560e7e3bbeca782732d37d960eff028c9b508c73/debian/changelog#L10)):*
> ```
> 
>   * version 1.8
>   * TBD: new and updated features (copy from release notes)
> ```

TODO: update that "TBD"?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 85 files at r1, 80 of 80 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2022)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "TODO" found in commit messages' one-liners (waiting on @woju)

**Review by kailun-qin — COMMENTED** [review]
> Reviewed 5 of 85 files at r1, 1 of 80 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2022)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "TODO" found in commit messages' one-liners (waiting on @woju)

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2022)* status: all files reviewed, 1 unresolved discussion, "TODO" found in commit messages' one-liners (waiting on @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 85 files at r1, 78 of 80 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2022)* status: all files reviewed, all discussions resolved, "TODO" found in commit messages' one-liners

**Comment by woju** [comment]
Jenkins, test Jenkins-Direct-24.04-Debug please

**Pull request merged**
