### PR TITLE
[glibc] Migrate to the newest version - 2.35

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
The patch is exactly the same as for 2.34, but I verified manually that nothing new was added.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: 0 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`subprojects/glibc-2.35-0.wrap` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N322YGZ2nOcn58--GMO:-N322YGZ2nOcn58--GMP:b-x9ve19) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L9)):*
> ```
> directory = glibc-2.35-0
> source_url = https://ftp.gnu.org/gnu/glibc/glibc-2.35.tar.gz
> source_fallback_url = https://packages.gramineproject.io/distfiles/glibc-2.35.tar.gz
> ```

@woju please upload this file

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: 0 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`subprojects/glibc-2.35-0.wrap` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N322s-1DQXsv6_0fMKQ:-N322s-1DQXsv6_0fMKR:br0czwr) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L14)):*
> ```
> patch_directory = glibc-2.35
> 
> # this unpacks the sources to `glibc-2.35-1/glibc-2.35`
> ```

TODO: `s/-1/-0/`
(not updating now to check jenkins, since it's already triggered)

**Review by mkow — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/612#-N345hMb-O1on8cz8cAm:-N345hMb-O1on8cz8cAn:b-ga1ftq) (no related file):*
Huh, `ra-tls-secret-prov` failed on Jenkins-SGX-18.04-apps, but we didn't change anything there yet: (at the time the CI ran on this PR)
```
03:21:58  Makefile:152: recipe for target 'check_epid' failed
03:21:58  make: *** [check_epid] Error 1
```

___

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`subprojects/glibc-2.35-0.wrap` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N34Eo-QBtVTy5MBsvZ9:-N34Eo-QBtVTy5MBsvZA:bft83im) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L7)):*
> ```
> 
> [wrap-file]
> directory = glibc-2.35-0
> ```

If we always include revisions, by custom the first one should be `-1`, not `-0`.
___
*[`subprojects/glibc-2.35-0.wrap` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N322YGZ2nOcn58--GMO:-N34EPa0-k5frJiRpmsc:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@woju please upload this file
</blockquote></details>

done

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/612#-N345hMb-O1on8cz8cAm:-N34Nx5416CFm0weT55k:bwl7rfh) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh, `ra-tls-secret-prov` failed on Jenkins-SGX-18.04-apps, but we didn't change anything there yet: (at the time the CI ran on this PR)
```
03:21:58  Makefile:152: recipe for target 'check_epid' failed
03:21:58  make: *** [check_epid] Error 1
```
</blockquote></details>

Yes, I've seen it yesterday, but could not reproduce locally (in docker with 18.04).
FWIW: the `OUTPUT` file (which is not printed in CI) contained something about inability to map a segment from `libm.so`

___
___
*[`subprojects/glibc-2.35-0.wrap` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N34Eo-QBtVTy5MBsvZ9:-N34OO2k84nb6NQPQE4O:b-g6a60d) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If we always include revisions, by custom the first one should be `-1`, not `-0`.
</blockquote></details>

I added it, because the comment above would look weird without it and we need it someday.
What's the difference? `0` is a very good starting number :)
___
*[`subprojects/glibc-2.35-0.wrap` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N322YGZ2nOcn58--GMO:-N34ObOfD4VP8zNxCzcW:bfwr67o) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

done
</blockquote></details>

Not done. (403)

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[`subprojects/glibc-2.35-0.wrap` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N34Eo-QBtVTy5MBsvZ9:-N34j7pt6P2mRXl3za3o:b-wtgj31) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I added it, because the comment above would look weird without it and we need it someday.
What's the difference? `0` is a very good starting number :)
</blockquote></details>

This is a custom, all packaging systems do it that way.
___
*[`subprojects/glibc-2.35-0.wrap` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N322YGZ2nOcn58--GMO:-N34jGwEDdC1VH5j6kpr:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done. (403)
</blockquote></details>

Fixed.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/612#-N345hMb-O1on8cz8cAm:-N35FiAk8lBIXKBspenQ:b-ybecyn) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, I've seen it yesterday, but could not reproduce locally (in docker with 18.04).
FWIW: the `OUTPUT` file (which is not printed in CI) contained something about inability to map a segment from `libm.so`
</blockquote></details>

#617 should fix it

___
___
*[`subprojects/glibc-2.35-0.wrap` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N34Eo-QBtVTy5MBsvZ9:-N35FoIW6ayReq0GTzw8:bf1qxri) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is a custom, all packaging systems do it that way.
</blockquote></details>

Well, this is not a real revision, just a hack to trigger meson.
Anyway, I don't care, if it's so important I can change it later (for now this is blocked on another PR).

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @woju)

___
*[`subprojects/glibc-2.35-0.wrap` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N34Eo-QBtVTy5MBsvZ9:-N3KFlb1--qWTLmgOp5D:bhvcxgk) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski I would also vote to start with `-1`, simply for uniformity -- this is how we did it before and for other subprojects (e.g., mbedTLS).

The top-level comment in this file should be fixed as well then.
</blockquote></details>

Sure, will do then. But for uniformity we should start without any suffixes - this is what we did before (i.e. no suffix -> `-1` -> `-2`). This is why I added `-0` - to have the comment and leave the old numbering.
But you all seem to want `-1` so that's what I'll do

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[`subprojects/glibc-2.35-0.wrap` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N34Eo-QBtVTy5MBsvZ9:-N3KMByw9QcHD60lnZHX:b-o8ig6c) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure, will do then. But for uniformity we should start without any suffixes - this is what we did before (i.e. no suffix -> `-1` -> `-2`). This is why I added `-0` - to have the comment and leave the old numbering.
But you all seem to want `-1` so that's what I'll do
</blockquote></details>

FWIW meson 0.60 has tooling to repack and re-unpack the wraps: https://mesonbuild.com/Release-notes-for-0-60-0.html#new-subprojects-packagefiles-subcommand, but this is relatively new development. Unless you have rolling distro, this needs Ubuntu 22.04 or Debian testing or 11 with backports (not the default repo).

**Review by dimakuv — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: 8 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[`subprojects/glibc-2.35-0.wrap` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/612#-N34Eo-QBtVTy5MBsvZ9:-N3KfgyN5C-VyuQXLn5H:b-91vuq0) ([raw file](https://github.com/gramineproject/gramine/blob/bd480b76b81cf9ce908aefcf4b447d2cbff91da4/subprojects/glibc-2.35-0.wrap#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

FWIW meson 0.60 has tooling to repack and re-unpack the wraps: https://mesonbuild.com/Release-notes-for-0-60-0.html#new-subprojects-packagefiles-subcommand, but this is relatively new development. Unless you have rolling distro, this needs Ubuntu 22.04 or Debian testing or 11 with backports (not the default repo).
</blockquote></details>

But this won't help us at all, these are just commands to manually issue. We wanted to automatically force an update if wrap files are changed.

`-1` done

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: 8 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/612#-N3IzXiRCpy607CftJkO:-N3Kh86u2N-m8XdC3g0C:beyvqy0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Did you check this PR with GDB? Just curious because I found this item in the release notes about the debugger:

> Bump r_version in the debugger interface to 2 and add a new field,   r_next, support multiple namespaces.

So looks like the interface to the debugger changed with this version? Hopefully it doesn't affect anything in our GDB hooks.
</blockquote></details>

I did not do any complex testing, but I had used GDB with this PR. Stepping, breakpoints and such work well (in SGX case).
Also we have some tests for GDB integration, hopefully they would catch any simple issue

___

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — DISMISSED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/612)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-20.04 (`fdatasync01` timed out, unrelated)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-20.04 please (fdatasync01 timed out, unrelated; forgot to be nice)

**Pull request merged**
