### PR TITLE
[CI] Ubuntu 24.04 and 22.04 part 1/?

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

This is the first PR in a series, a split of #2021 (and #1904 before). It is split into separate commits to make it easier to review, because reviewable has trouble with 17-commit PR.

There will be differences between particular commits, because we need to make sure all PRs pass necessary CI pipelines.

## How to test this PR? 

CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2026)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2026)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by woju** [comment]
Jenkins, test Jenkins-Debug-20.04 please

**Comment by woju** [comment]
Jenkins, test Jenkins-20.04 please

**Comment by woju** [comment]
Jenkins, test Jenkins-Direct-Sanitizers

**Comment by woju** [comment]
Jenkins, test Jenkins-Direct-Sanitizers please

**Comment by woju** [comment]
Jenkins, test Jenkins-SGX-20.04-apps please

**Comment by woju** [comment]
Jenkins, test Jenkins-SGX-20.04-musl please

**Comment by woju** [comment]
Jenkins, test Jenkins-SGX-EDMM please

**Review by dimakuv — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2026)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by woju** [comment]
Jenkins, test Jenkins-SGX-20.04 please

**Comment by woju** [comment]
Jenkins, test Jenkins-SGX-Sanitizers please

**Pull request merged**
