### PR TITLE
[Pal] Remove `pal_sec` and refactor topology structures

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

This is a preparation for a better topology sanitization and deduplication of PAL code.
I wish it could be smaller, but after cleaning up and deduplicating the structures a lot of code started to make no sense, so I had to refactor also it and a lot of changes cascaded.

After this probably one more refactoring and then sanitization rework will come.

## How to test this PR? 

CI.
Do we know any workload which tests sysfs topology better than our CI?

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 44 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdSQ9R0ry2aXsEPnSH:-MsdSQ9S7wAS22U0QMYo:b3ddtz9) (no related file):*
> Do we know any workload which tests sysfs topology better than our CI?

OpenVINO is known to check sysfs. Without proper sysfs configuration, OpenVINO still works (IIRC) but is very slow.

---
___
*[Pal/include/pal_internal.h, line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdTI7R8uS-pitNEAmk:-MsdTI7R8uS-pitNEAml:by7zmu2) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/pal_internal.h#L163)):*
> ```objc
> unsigned long _DkMemoryAvailableQuota(void);
> // Returns 0 on success, negative PAL code on failure
> int _DkGetCPUInfo(PAL_CPU_INFO* info);
> ```

Why not replace `PAL_CPU_INFO` with `struct pal_cpu_info`?
___
*[Pal/include/arch/x86_64/pal_topology.h, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdTibmAOxsmk-YTPmQ:-MsdTibmAOxsmk-YTPmR:bcjmnyq) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/arch/x86_64/pal_topology.h#L10)):*
> ```objc
> 
> // TODO: drop after removing PAL_NUM from here
> typedef uint64_t PAL_NUM;
> ```

Why not just drop it immediately, in this PR?
___
*[Pal/include/arch/x86_64/pal_topology.h, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdTqr23FuiHuVWaqVI:-MsdTqr23FuiHuVWaqVJ:bvuegs9) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/arch/x86_64/pal_topology.h#L26)):*
> ```objc
> 
> /* PAL_CPU_INFO holds /proc/cpuinfo data */
> typedef struct PAL_CPU_INFO_ {
> ```

Why not remove typedefs in this header and use `struct pal_cpu_info` and similar?
___
*[Pal/include/arch/x86_64/pal_topology.h, line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdUP5G8injd0vR4xn5:-MsdUP5G8injd0vR4xn6:b-cp4fc4) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/arch/x86_64/pal_topology.h#L67)):*
> ```objc
> /* This struct takes ~1.6KB. On a single socket, 4 logical core system, with 3 cache levels
>  * it would take ~8KB in memory. */
> // TODO: what does this ^ mean? the struct has constant size, much less than 1.6KB
> ```

I think this comment got stale. In the beginning, this struct had a lot of stuff hard-coded as arrays of fixed length. Now this struct is full of pointers to other structs, so the comment doesn't make much sense any more. (The second part of the comment -- about 8KB of memory -- is probably still valid though.)

Maybe just remove this comment?
___
*[Pal/include/arch/x86_64/pal_topology.h, line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdUv6y0T4T8vOd9ML4:-MsdUv6y0T4T8vOd9ML5:bcpuw9f) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/arch/x86_64/pal_topology.h#L71)):*
> ```objc
>     PAL_CPU_INFO cpu_info; // TODO: should this be moved out to `pal_public_state` or kept here?
>                            // We don't need to take this from the untrusted host as a start argument
>                            // (but the rest of this struct _is_ used this way).
> ```

Yes, I had the same proposal.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdVOOnAek5FKucv-nN:-MsdVOOnAek5FKucv-nO:b-8l8xdc) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/arch/x86_64/pal_topology.h#L89)):*
> ```objc
>                               * available on the host */
> 
>     PAL_CORE_TOPO_INFO* core_topology; /* array of logical core topology info, owned by this struct */ // TODO: what size?
> ```

The size is `online_logical_cores_cnt`. You can also move this field close to that field.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdVZPj1JaP8HPWqJtf:-MsdVZPj1JaP8HPWqJtg:b-nwrc59) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/arch/x86_64/pal_topology.h#L90)):*
> ```objc
> 
>     PAL_CORE_TOPO_INFO* core_topology; /* array of logical core topology info, owned by this struct */ // TODO: what size?
>     PAL_NUMA_TOPO_INFO* numa_topology; /* array of numa topology info, owned by this struct */ // TODO: what size?
> ```

The size is `online_nodes_cnt`. You can also move this field close to that field.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 91 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdVb9a8RTgAmeOiV4k:-MsdVb9a8RTgAmeOiV4l:b-z0pysx) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/arch/x86_64/pal_topology.h#L91)):*
> ```objc
>     PAL_CORE_TOPO_INFO* core_topology; /* array of logical core topology info, owned by this struct */ // TODO: what size?
>     PAL_NUMA_TOPO_INFO* numa_topology; /* array of numa topology info, owned by this struct */ // TODO: what size?
> };
> ```

Please add comments on a separate line for each of these fields (above the field), otherwise it's hard to read these comments.

I mean the style that Pawel likes to use: https://github.com/gramineproject/gramine/blob/84b331fe7da92675a888837eb54c2b33a3de4518/LibOS/shim/include/shim_fs.h#L29
___
*[Pal/src/host/Linux-common/topo_info.c, line 236 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdXakCDYGzws3rikGn:-MsdXakCDYGzws3rikGo:b-xulp1i) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/src/host/Linux-common/topo_info.c#L236)):*
> ```C
> 
>     /* array of "logical core -> socket" mappings */
>     int* cpu_to_socket = (int*)malloc(online_logical_cores_cnt * sizeof(int));
> ```

You don't correctly free `cpu_to_socket` in this function.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 830 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdZZ6H-Qa8IvzjxroC:-MsdZZ6H-Qa8IvzjxroD:b7968ip) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/src/host/Linux-SGX/db_misc.c#L830)):*
> ```C
> }
> 
> // TODO: Refactor and remove? Or move the parsing from db_main:pal_linux_main to here?
> ```

I'm totally confused. Where did you move this logic then? Is it now in Linux-common, in `get_numa_topo_info()`?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-Msd_QMPAKmdpqWA74ev:-Msd_QMPAKmdpqWA74ew:b-qdjgmt) (no related file):*
I would prefer to split this in several PRs... But I don't insist.

Proposed PRs:
- Replacing `EAX` with `CPUID_WORD_EAX` and `cpuid` with `DkGetCpuid`
- Replacing `mem_info.mem_total` with `mem_total` (removing `MEM_INFO`)
- Replacing `num_` with `_cnt`
- Removing duplicate code from `sgx_main.c`
- Everything else

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)* status: 42 of 44 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-Msd_QMPAKmdpqWA74ev:-MsexfcqEJuAdIE3ncvN:b-e8anuu) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The problem with this is that I noticed these _after_ doing the refactoring, and splitting some of these out would generate a lot of conflicts. But it's doable (especially some of the points you listed should be easy to split), so if you prefer it then I can do it.
</blockquote></details>

I'm definitely for spliting these as separate PRs (as much as possible, of course; if some things are too tedious, then lump them into one big PR). It was a pain to review this hodge-podge PR.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)* status: 42 of 44 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-Msd_QMPAKmdpqWA74ev:-MseyT9rCPrcUMKVBIiG:bzb90tv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm definitely for spliting these as separate PRs (as much as possible, of course; if some things are too tedious, then lump them into one big PR). It was a pain to review this hodge-podge PR.
</blockquote></details>

Ok, let me do this now.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)* status: 42 of 44 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-Msd_QMPAKmdpqWA74ev:-Msfe4wh1TWutX_0yalJ:b-cpcfl) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, let me do this now.
</blockquote></details>

First one (CPUID): https://github.com/gramineproject/gramine/pull/317

---

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)* status: 42 of 44 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdSQ9R0ry2aXsEPnSH:-MsfnU3o-LiVn1kuaQ-y:bug1q2f) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, this example doesn't build for me:
```
CMake Error at inference-engine/cmake/dependencies.cmake:240 (message):
  OpenCV is not available on current platform
Call Stack (most recent call first):
  inference-engine/CMakeLists.txt:18 (include)


-- Configuring incomplete, errors occurred!
```

Any ideas? I'm not familiar with OpenVINO.
</blockquote></details>

Haven't run this in a long time but based on the error it looks like `OpenCV` should be installed? Please see this file, https://github.com/openvinotoolkit/openvino/blob/2020.4/build-instruction.md#build-on-linux-systems

Extract from the above link,
```
If the CMake-based build script can not find and download the OpenCV package that is supported on your platform, or if you want to use a custom build of the OpenCV library, refer to the Use Custom OpenCV Builds section for details.
```

Also, I would recommend running the `install_dependencies.sh` script if you haven't done so.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-Msd_QMPAKmdpqWA74ev:-MsfkkW89j0QepsC7_m9:b-703rrr) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

First one (CPUID): https://github.com/gramineproject/gramine/pull/317
</blockquote></details>

Thanks for splitting the PR, it is easier to ingest smaller changes :)

---
___
*[Pal/include/arch/x86_64/pal_topology.h, line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdUP5G8injd0vR4xn5:-MsflHee0nc-9UQKbq2l:b-k0k68c) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/arch/x86_64/pal_topology.h#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You may be right. @vijaydhanraj, what do you think?
</blockquote></details>

Yes, pls remove this comment.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)* status: 42 of 44 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-Msd_QMPAKmdpqWA74ev:-MsgMqTp3n98oioc_Xzo:b-xwh7ps) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks for splitting the PR, it is easier to ingest smaller changes :)
</blockquote></details>

Next one (`PAL_MEM_INFO`): https://github.com/gramineproject/gramine/pull/318

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)* status: 42 of 44 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-Msd_QMPAKmdpqWA74ev:-MsgaDz0CaT2f4tnEJa-:byc9tas) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Next one (`PAL_MEM_INFO`): https://github.com/gramineproject/gramine/pull/318
</blockquote></details>

And one more (`num_` -> `_cnt`): https://github.com/gramineproject/gramine/pull/319
More will need to wait for merging these, because of conflicts.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/314)* status: 42 of 44 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdSQ9R0ry2aXsEPnSH:-MsoHmV-2Cp0Ebam628n:b-mrxmgc) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Haven't run this in a long time but based on the error it looks like `OpenCV` should be installed? Please see this file, https://github.com/openvinotoolkit/openvino/blob/2020.4/build-instruction.md#build-on-linux-systems

Extract from the above link,
```
If the CMake-based build script can not find and download the OpenCV package that is supported on your platform, or if you want to use a custom build of the OpenCV library, refer to the Use Custom OpenCV Builds section for details.
```

Also, I would recommend running the `install_dependencies.sh` script if you haven't done so.
</blockquote></details>

Thanks, will try this. Although I followed the README of that example, so, it seems that either I missed something or the steps there are incomplete.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/314#-Msd_QMPAKmdpqWA74ev:-MsoI66N7vAO1W-_U7-c:b71us0p) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

And one more (`num_` -> `_cnt`): https://github.com/gramineproject/gramine/pull/319
More will need to wait for merging these, because of conflicts.
</blockquote></details>

Ok, and the last two points: https://github.com/gramineproject/gramine/pull/325. I left them as a single PR, because it would require quite some  work to split them apart.

---
___
*[Pal/include/arch/x86_64/pal_topology.h, line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/314#-MsdUP5G8injd0vR4xn5:-MsoEU7_EtJx6sq6Rr8r:b-w9vgam) ([raw file](https://github.com/gramineproject/gramine/blob/3e63301630e00ace314200182b51f1ed5f4f0c75/Pal/include/arch/x86_64/pal_topology.h#L67)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, pls remove this comment.
</blockquote></details>

Done (in the new PR).

**Comment by mkow** [comment]
Everything was already resubmitted as smaller PRs, so I'm closing this one.

**Pull request closed without merging**
