### PR TITLE
Remove deprecated `sgx.require_*` manifest options

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

FYI: I'll submit some more cleanups to other deprecated stuff later.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1863)

### CODE REVIEW

**Review by kailun-qin — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1863)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1863)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1863#-NwsMwEi3Daxhrs-zkEm):*
Don't we want a prefix `[Docs,PAL/Linux-SGX]` ?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1863)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1863#-NwsMwEi3Daxhrs-zkEm):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want a prefix `[Docs,PAL/Linux-SGX]` ?
</blockquote></details>

Or maybe just `[PAL/Linux-SGX]`? The docs update is just a result of the change in SGX PAL. I can do that when rebasing.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1863)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1863#-NwsMwEi3Daxhrs-zkEm):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Or maybe just `[PAL/Linux-SGX]`? The docs update is just a result of the change in SGX PAL. I can do that when rebasing.
</blockquote></details>

Ok, makes sense to me. I'm approving.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1863)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1863#-NwsMwEi3Daxhrs-zkEm):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, makes sense to me. I'm approving.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1863)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1863)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
