### PR TITLE
[LibOS] Fix assertion on `dent->inode`

### PR DESCRIPTION
**Pull request by JaewonHur**
Signed-off-by: Jaewon Hur <hurjaewon@snu.ac.kr>

## Description of the changes 

Fix assertion on `dent->inode`.

## How to test this PR? 

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NLyrVPPD0Bcw9Wp5Q4m:-NLyrVPPD0Bcw9Wp5Q4n:bs6nemf) (no related file):*
I reproduced this assert failure locally:
- Busybox manifest file diff:
```diff
diff --git a/CI-Examples/busybox/busybox.manifest.template b/CI-Examples/busybox/busybox.manifest.template
@@ -15,6 +15,8 @@ fs.mounts = [
   { path = "/etc/hosts", uri = "file:helper-files/hosts" },
+
+  { type = "encrypted", path = "/bla", uri = "file:encrypted_file_mrenclave", key_name = "_sgx_mrenclave" },
 ]
```

- Failing run:
```
~/gramineproject/gramine/CI-Examples/busybox$ gramine-sgx busybox sh
echo "Hello" > bla
chmod 644 bla
[P5:T5:busybox] assert failed ../libos/src/fs/chroot/encrypted.c:341 !dent->inode
[P1:libos] error: Child process (vmid: 0x5) got disconnected
Power failure
```

So this PR is legit.

___

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NLyrVPPD0Bcw9Wp5Q4m:-NM-Udx0E-BLPx5AnoTc:b-ykcxcy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I reproduced this assert failure locally:
- Busybox manifest file diff:
```diff
diff --git a/CI-Examples/busybox/busybox.manifest.template b/CI-Examples/busybox/busybox.manifest.template
@@ -15,6 +15,8 @@ fs.mounts = [
   { path = "/etc/hosts", uri = "file:helper-files/hosts" },
+
+  { type = "encrypted", path = "/bla", uri = "file:encrypted_file_mrenclave", key_name = "_sgx_mrenclave" },
 ]
```

- Failing run:
```
~/gramineproject/gramine/CI-Examples/busybox$ gramine-sgx busybox sh
echo "Hello" > bla
chmod 644 bla
[P5:T5:busybox] assert failed ../libos/src/fs/chroot/encrypted.c:341 !dent->inode
[P1:libos] error: Child process (vmid: 0x5) got disconnected
Power failure
```

So this PR is legit.
</blockquote></details>

As we the code path depends on the `dentry->inode != NULL`:
```
[...]
    int ret = chroot_dentry_uri(dent, dent->inode->type, &uri);
```

I think this assertion was wrong, as the PR states.
The same assertion is used in `chroot/fs.c` in function `chroot_chmod`.
I wondered for a moment if we shouldn't convert this assertion to if statement.
But it seems that in the case when we are using file descriptor - we are verifying that inode is set:
```
long libos_syscall_fchmod(int fd, mode_t mode) {
     [...]

     if (!dent->inode) { 
          ret = -ENOENT;
          goto out;
     }
}
```

I would still feel better converting the assertion to check.

Besides that, it's LGTM.

___

**Review by oshogbo — COMMENTED** [review]
Ot the other hand, shouldn't we also add a test case for this, then?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127#-:-NM-dwV_7yslOX7E7UnF:b-bovji6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @JaewonHur)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NLyrVPPD0Bcw9Wp5Q4m:-NM2wNlE67l6Q6nSad2D:b7beo4n) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

As we the code path depends on the `dentry->inode != NULL`:
```
[...]
    int ret = chroot_dentry_uri(dent, dent->inode->type, &uri);
```

I think this assertion was wrong, as the PR states.
The same assertion is used in `chroot/fs.c` in function `chroot_chmod`.
I wondered for a moment if we shouldn't convert this assertion to if statement.
But it seems that in the case when we are using file descriptor - we are verifying that inode is set:
```
long libos_syscall_fchmod(int fd, mode_t mode) {
     [...]

     if (!dent->inode) { 
          ret = -ENOENT;
          goto out;
     }
}
```

I would still feel better converting the assertion to check.

Besides that, it's LGTM.

</blockquote></details>

No, I don't think we should change assertion to check.

See this comment on `chmod()` callback: https://github.com/gramineproject/gramine/blob/ff9ec79ab27fb4f95daa35656d1410c695264509/libos/include/libos_fs.h#L377-L388

Basically, this callback is assumed to get a positive `dentry` (i.e., dentry that is associated with an actual file, hence it has `inode != NULL`). So we definitely should *not* modify the callback -- instead we should modify the users of this callback to adhere to the required pre-conditions.

There are two users of `chmod()` callback:
- `libos_syscall_fchmodat`
- `libos_syscall_fchmod`

Both guarantee that `dentry` is positive (i.e. it has `dentry->inode != NULL`).

Thus, I don't see a need for any changes.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NM2xI5R4CwLYx1ZCaAP:-NM2xI5R4CwLYx1ZCaAQ:by6kjke) (no related file):*
> Ot the other hand, shouldn't we also add a test case for this, then?

I thought about this, but we need exactly this combination for a test:
- encrypted file
- performing `chmod()` on it
- checking that `chmod()` did something meaningful

Such a test felt very unnatural, and to introduce it only to test this single line of an assert sounds wrong.

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NLyrVPPD0Bcw9Wp5Q4m:-NM3oJKy5l_fiw204Q9H:b-y2ulig) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, I don't think we should change assertion to check.

See this comment on `chmod()` callback: https://github.com/gramineproject/gramine/blob/ff9ec79ab27fb4f95daa35656d1410c695264509/libos/include/libos_fs.h#L377-L388

Basically, this callback is assumed to get a positive `dentry` (i.e., dentry that is associated with an actual file, hence it has `inode != NULL`). So we definitely should *not* modify the callback -- instead we should modify the users of this callback to adhere to the required pre-conditions.

There are two users of `chmod()` callback:
- `libos_syscall_fchmodat`
- `libos_syscall_fchmod`

Both guarantee that `dentry` is positive (i.e. it has `dentry->inode != NULL`).

Thus, I don't see a need for any changes.
</blockquote></details>

Yes, I already mentioned that the `libos_syscall_fchmod` guarantees these.
It's ok.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NM2xI5R4CwLYx1ZCaAP:-NM3oQ3Z4E1EnbJThUDk:bexrv17) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Ot the other hand, shouldn't we also add a test case for this, then?

I thought about this, but we need exactly this combination for a test:
- encrypted file
- performing `chmod()` on it
- checking that `chmod()` did something meaningful

Such a test felt very unnatural, and to introduce it only to test this single line of an assert sounds wrong.
</blockquote></details>

Is it?
It sounds like a normal operation on an encrypted file, like testing if `chmod` actually does anything.
Otherwise, why do we even implement `chmod` for encrypted files?

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NM2xI5R4CwLYx1ZCaAP:-NM3uZF49AXR7ORMakiV:b-z9dytu) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Is it?
It sounds like a normal operation on an encrypted file, like testing if `chmod` actually does anything.
Otherwise, why do we even implement `chmod` for encrypted files?
</blockquote></details>

Hm, actually, you're right. We can write a generic `chmod` test under `libos/test/fs`, and it wil automatically work for normal/tmpfs/encrypted files.

@oshogbo Is this something you'd like to do?

___

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @JaewonHur)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NM2xI5R4CwLYx1ZCaAP:-NM45tLoBOpZ52rWh4-A:bzedblr) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

If the author of PR is not interested in writing it, I can do it.
</blockquote></details>

@JaewonHur Would you be interested in trying this?

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: 1 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @JaewonHur)

___
*[`libos/test/fs/chmod_stat.c` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMd1Tkg1M8gG1EgzSjH:-NMd1Tkg1M8gG1EgzSjI:btl8voo) ([raw file](https://github.com/gramineproject/gramine/blob/be737c7dd794ec3d11dc60a738fc9e55ac82e34e/libos/test/fs/chmod_stat.c#L3)):*
> ```C
> #include "common.h"
> 
> static void read_perm(struct stat* st, char* perm) {
> ```

Why going so complicated? Can't we compare numbers?
https://en.wikipedia.org/wiki/Chmod#Numerical_permissions
I think we can simplify this.
___
*[`libos/test/fs/test_fs.py` line 182 at r2](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMd2D80BvHeFcsW1QCQ:-NMd2D817AkvZi6zt-S9:b6jpgaj) ([raw file](https://github.com/gramineproject/gramine/blob/be737c7dd794ec3d11dc60a738fc9e55ac82e34e/libos/test/fs/test_fs.py#L182)):*
> ```Python
> 
>         self.assertNotIn('ERROR: ', stderr)
>         self.assertIn('open(' + file_path + ') RW OK', stdout)
> ```

Our new rules say the checking should be done in the test itself.
The binary should do all checking, and python just checks if "test ok" was returned.

**Review by JaewonHur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: 1 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/fs/chmod_stat.c` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMd1Tkg1M8gG1EgzSjH:-NMfkgHuCwAZ86NYmWNa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be737c7dd794ec3d11dc60a738fc9e55ac82e34e/libos/test/fs/chmod_stat.c#L3)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Why going so complicated? Can't we compare numbers?
https://en.wikipedia.org/wiki/Chmod#Numerical_permissions
I think we can simplify this.
</blockquote></details>

Done.
___
*[`libos/test/fs/test_fs.py` line 182 at r2](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMd2D80BvHeFcsW1QCQ:-NMfl29_39i6GlND9bEN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be737c7dd794ec3d11dc60a738fc9e55ac82e34e/libos/test/fs/test_fs.py#L182)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Our new rules say the checking should be done in the test itself.
The binary should do all checking, and python just checks if "test ok" was returned.
</blockquote></details>

Done.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: 1 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @JaewonHur)

___
*[`libos/test/fs/chmod_stat.c` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMkc7n03b_P3kCYFbYD:-NMkc7n03b_P3kCYFbYE:bqu1l93) ([raw file](https://github.com/gramineproject/gramine/blob/66d1fe247bd6d8e0f20d7633e46d92ea4fd20fe5/libos/test/fs/chmod_stat.c#L5)):*
> ```C
> static void chmod_stat(const char* file_path) {
>     struct stat st;
>     uint32_t perm, expected_perm;
> ```

I guess expect perm can be set here or just a macro. Up 2 you, not blocking.
___
*[`libos/test/fs/chmod_stat.c` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMkcp0A3coXqIAKcMGk:-NMkcp0A3coXqIAKcMGl:bq2pl8s) ([raw file](https://github.com/gramineproject/gramine/blob/66d1fe247bd6d8e0f20d7633e46d92ea4fd20fe5/libos/test/fs/chmod_stat.c#L17)):*
> ```C
>         fatal_error("File permission is different (expected: %o, actual: %o)\n", expected_perm, perm);
> 
>     if (chmod(file_path, (st.st_mode & ~S_IWUSR)))
> ```

Should we also test `fchmod(2)`?
Can't we just remove ~S_IWUSR from expected_perm and use it here in chmod?
If so maybe just call it `referenc_perm`, to not confuse users.
___
*[`libos/test/fs/meson.build` line 48 at r3](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMkdX2W5cjzYCaFtils:-NMkdX2W5cjzYCaFtilt:b-umjduk) ([raw file](https://github.com/gramineproject/gramine/blob/66d1fe247bd6d8e0f20d7633e46d92ea4fd20fe5/libos/test/fs/meson.build#L48)):*
> ```Meson
>     'seek_tell_truncate': {},
>     'stat': {},
>     'chmod_stat': {},
> ```

This should be sorted.
___
*[`libos/test/fs/tests.toml` line 19 at r3](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMkdQjiCxMZesyTD6eT:-NMkdQjiCxMZesyTD6eU:b-umjduk) ([raw file](https://github.com/gramineproject/gramine/blob/66d1fe247bd6d8e0f20d7633e46d92ea4fd20fe5/libos/test/fs/tests.toml#L19)):*
> ```TOML
>   "seek_tell_truncate",
>   "stat",
>   "chmod_stat",
> ```

This should be sorted.

**Review by JaewonHur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: 1 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/fs/chmod_stat.c` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMkcp0A3coXqIAKcMGk:-NMkuf3t2pGRPGPolwMX:b9tsi6k) ([raw file](https://github.com/gramineproject/gramine/blob/66d1fe247bd6d8e0f20d7633e46d92ea4fd20fe5/libos/test/fs/chmod_stat.c#L17)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Should we also test `fchmod(2)`?
Can't we just remove ~S_IWUSR from expected_perm and use it here in chmod?
If so maybe just call it `referenc_perm`, to not confuse users.
</blockquote></details>

Added `fchmod(2)`.
Rewrite to use only `expected_perm` in `chmod`.
`reference_perm` may also work, but I used `expected_perm` since its value changes as the test goes.
___
*[`libos/test/fs/meson.build` line 48 at r3](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMkdX2W5cjzYCaFtils:-NMkuaGj4-7u5S-rzYgE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/66d1fe247bd6d8e0f20d7633e46d92ea4fd20fe5/libos/test/fs/meson.build#L48)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This should be sorted.
</blockquote></details>

Done.
___
*[`libos/test/fs/tests.toml` line 19 at r3](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMkdQjiCxMZesyTD6eT:-NMkuavT10nNEn7mfY2h:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/66d1fe247bd6d8e0f20d7633e46d92ea4fd20fe5/libos/test/fs/tests.toml#L19)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This should be sorted.
</blockquote></details>

Done.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: 1 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @JaewonHur)

___
*[`libos/test/fs/chmod_stat.c` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMkcp0A3coXqIAKcMGk:-NMmKzuDDiO4ltsBPbFJ:b-vuj8ut) ([raw file](https://github.com/gramineproject/gramine/blob/66d1fe247bd6d8e0f20d7633e46d92ea4fd20fe5/libos/test/fs/chmod_stat.c#L17)):*
<details><summary><i>Previously, JaewonHur (jwhur) wrote…</i></summary><blockquote>

Added `fchmod(2)`.
Rewrite to use only `expected_perm` in `chmod`.
`reference_perm` may also work, but I used `expected_perm` since its value changes as the test goes.
</blockquote></details>

Thank you :)
___
*[`libos/test/fs/chmod_stat.c` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMmL40Q6wRowXJOEWfJ:-NMmL40Q6wRowXJOEWfK:b-isu0gw) ([raw file](https://github.com/gramineproject/gramine/blob/0e3eabe813af9a8a20e15dd53d44aa1c7665ee56/libos/test/fs/chmod_stat.c#L1)):*
> ```C
> #include "common.h"
> ```

You don't want to add your copy rights?
___
*[`libos/test/fs/chmod_stat.c` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMmKbvY8vYF1y1mPayA:-NMmKbvY8vYF1y1mPayB:b-nakrp0) ([raw file](https://github.com/gramineproject/gramine/blob/0e3eabe813af9a8a20e15dd53d44aa1c7665ee56/libos/test/fs/chmod_stat.c#L47)):*
> ```C
>         fatal_error("Usage: %s <file_path>\n", argv[0]);
> 
>     setup();
> ```

I guess the setup should be done before any potential print?

```
    setup();
    if (argc < 2)
        fatal_error("Usage: %s <file_path>\n", argv[0]);
```



_Code quote:_
```C
 setup
```

**Review by JaewonHur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: 1 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/fs/chmod_stat.c` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMmL40Q6wRowXJOEWfJ:-NMqxVVZ4KcHFrdkD2V-:b-bsbdqw) ([raw file](https://github.com/gramineproject/gramine/blob/0e3eabe813af9a8a20e15dd53d44aa1c7665ee56/libos/test/fs/chmod_stat.c#L1)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

You don't want to add your copy rights?
</blockquote></details>

Thank you, but it's okay.
___
*[`libos/test/fs/chmod_stat.c` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1127#-NMmKbvY8vYF1y1mPayA:-NMqxcU7BbfJokRpHgVU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0e3eabe813af9a8a20e15dd53d44aa1c7665ee56/libos/test/fs/chmod_stat.c#L47)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I guess the setup should be done before any potential print?

```
    setup();
    if (argc < 2)
        fatal_error("Usage: %s <file_path>\n", argv[0]);
```

</blockquote></details>

Done.

**Review by oshogbo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127#-:-NN10Z_ZBGHjyJ9-_GEq:bnfp4nl)* status: 1 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners

**Comment by oshogbo** [comment]
Jenkins, test this please

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @JaewonHur)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNM1I9I2Mznnz9BzSsH:-NNM1I9J4GDRrS7tSZOy:bymizkn) (no related file):*
I noticed only small typos. The rest looks good. I verified in our Jenkins that the new test works on all three types of files: normal, tmpfs, and encrypted.

@JaewonHur If you agree, we can fix the small typos ourselves during final rebase & merge.

___
___
*[`libos/test/fs/chmod_stat.c` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNM0PkSCdbAKBBkKI4O:-NNM0PkSCdbAKBBkKI4P:b-nf7bc1) ([raw file](https://github.com/gramineproject/gramine/blob/138b0431d7ca2177d5a5033d0fe37fb8cfa246da/libos/test/fs/chmod_stat.c#L7)):*
> ```C
>     uint32_t perm, expected_perm = (S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);
> 
>     int fd = open_output_fd(file_path, /*rdwr*/true);
> ```

`/*rdwr*/true` -> `/*rdwr=*/true`
___
*[`libos/test/fs/chmod_stat.c` line 44 at r6](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNM0JCdDIhF-wtAuaTa:-NNM0JCdDIhF-wtAuaTb:b-dkz2k1) ([raw file](https://github.com/gramineproject/gramine/blob/138b0431d7ca2177d5a5033d0fe37fb8cfa246da/libos/test/fs/chmod_stat.c#L44)):*
> ```C
> 
> int main(int argc, char* argv[]) {
> ```

Please remove an empty line

**Review by JaewonHur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/fs/chmod_stat.c` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNM0PkSCdbAKBBkKI4O:-NNOuEQj6T_XVHTThTvn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/138b0431d7ca2177d5a5033d0fe37fb8cfa246da/libos/test/fs/chmod_stat.c#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`/*rdwr*/true` -> `/*rdwr=*/true`
</blockquote></details>

Done.
___
*[`libos/test/fs/chmod_stat.c` line 44 at r6](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNM0JCdDIhF-wtAuaTa:-NNOuEeUCfm2v0pHsw7x:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/138b0431d7ca2177d5a5033d0fe37fb8cfa246da/libos/test/fs/chmod_stat.c#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove an empty line
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @JaewonHur)

___
*[`libos/test/fs/chmod_stat.c` line 5 at r7](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNaWNyrCpdhw0ETFiKA:-NNaWNysCUStWLtlVvOn:bmy3c92) ([raw file](https://github.com/gramineproject/gramine/blob/9499f64cd8df5e4ca259a9176f7ffac9ef0a8356/libos/test/fs/chmod_stat.c#L5)):*
> ```C
> static void chmod_stat(const char* file_path) {
>     struct stat st;
>     uint32_t perm, expected_perm = (S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);
> ```

Also, I'd prefer to move this variable creation into a separate, line for readability.



_Suggestion:_
```C
S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH
```
___
*[`libos/test/fs/chmod_stat.c` line 5 at r7](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNaWfe76-GmWN_r6HD1:-NNaWfe76-GmWN_r6HD2:b5ybrbc) ([raw file](https://github.com/gramineproject/gramine/blob/9499f64cd8df5e4ca259a9176f7ffac9ef0a8356/libos/test/fs/chmod_stat.c#L5)):*
> ```C
> static void chmod_stat(const char* file_path) {
>     struct stat st;
>     uint32_t perm, expected_perm = (S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);
> ```

Let's instead either use the octal notation or the macros from `common/include/perm.h`, these `S_I*` macros are unreadable. 



_Code quote:_
```C
S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH
```

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @JaewonHur)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNli7cKD27qm0T553ty:-NNli7cKD27qm0T553tz:b-6d2rwb) (no related file):*
@JaewonHur: Will you have time soon to fix up these nits? If not I can do it myself when rebasing the PR before merging.

___

**Review by JaewonHur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNli7cKD27qm0T553ty:-NNnb87b8XrMsPgBAw37:b-h56eld) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@JaewonHur: Will you have time soon to fix up these nits? If not I can do it myself when rebasing the PR before merging.
</blockquote></details>

Thank you, please!

___

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @JaewonHur and @mkow)

___
*[`libos/test/fs/chmod_stat.c` line 5 at r7](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNaWfe76-GmWN_r6HD1:-NNpKls_5zVoSQOnum_P:b-tj27sx) ([raw file](https://github.com/gramineproject/gramine/blob/9499f64cd8df5e4ca259a9176f7ffac9ef0a8356/libos/test/fs/chmod_stat.c#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Let's instead either use the octal notation or the macros from `common/include/perm.h`, these `S_I*` macros are unreadable. 
</blockquote></details>

But this is a standalone test, and it can't/shouldn't include the headers from Gramine?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @JaewonHur)

___
*[`libos/test/fs/chmod_stat.c` line 5 at r7](https://reviewable.io/reviews/gramineproject/gramine/1127#-NNaWfe76-GmWN_r6HD1:-NNq0rg40hEM96fCngwt:bjdwekp) ([raw file](https://github.com/gramineproject/gramine/blob/9499f64cd8df5e4ca259a9176f7ffac9ef0a8356/libos/test/fs/chmod_stat.c#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But this is a standalone test, and it can't/shouldn't include the headers from Gramine?
</blockquote></details>

Ah, right, this `common.h` included above is from the test directory. Will use octal then.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1127)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Direct-Sanitizers please (timeout on Blender download, again... :/ )

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Direct-Sanitizers please (timeout on Blender download again, but the faulty node should now be out of CI)

**Pull request merged**
