### PR TITLE
[python] Pass bytes to cryptography.io's RSAPrivateKey.sign()

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

See commit message.

Fixes: #1731

## How to test this PR? 

Check the reproducer in #1731.
Cc: @andre-w-fischer

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1732#-Np-V-pR73BDAP4GQSil):*
FYI: You can see this commit here: https://github.com/pyca/cryptography/commit/0000b402dd5edffa6a86ca560464e83a66fd91f5

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1732#-Np2LRTB74nFKaEQF-oz):*
-> `Technically`



_Code quote:_
```
Techically
```

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1732#-Np2LRTB74nFKaEQF-oz):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `Technically`
</blockquote></details>

Done
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1732#-Np-V-pR73BDAP4GQSil):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: You can see this commit here: https://github.com/pyca/cryptography/commit/0000b402dd5edffa6a86ca560464e83a66fd91f5
</blockquote></details>

FYI: I expanded this sentence a bit to make it clearer what commit is meant here.

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1732#-Np44dHpBeTF72t_S-Kf:-Np44dHpBeTF72t_S-Kg:b-m09t6q) (no related file):*
Upstream accepted bug and fixed this:
- https://github.com/pyca/cryptography/issues/10256
- https://github.com/pyca/cryptography/pull/10259
- https://github.com/pyca/cryptography/commit/08b24d87a64734ac7f5c575b309ad7d49c246353

Now I'm not sure if we want to merge this on our side. I'd argue we can, because `.to_bytes()` should return bytes, but right now there is no technical reason to merge. At least we can reword the commit message.

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1732#-Np44dHpBeTF72t_S-Kf:-Np5HPggDZERwq7o14CZ:b-e53ftg) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Upstream accepted bug and fixed this:
- https://github.com/pyca/cryptography/issues/10256
- https://github.com/pyca/cryptography/pull/10259
- https://github.com/pyca/cryptography/commit/08b24d87a64734ac7f5c575b309ad7d49c246353

Now I'm not sure if we want to merge this on our side. I'd argue we can, because `.to_bytes()` should return bytes, but right now there is no technical reason to merge. At least we can reword the commit message.
</blockquote></details>

Let me change the commit message slightly. Our fix makes sense to me, and it's better to be on the safe side (what if someone has 42.0.0 - 42.0.1 on their platform).

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1732#-Np44dHpBeTF72t_S-Kf:-Np5JfDB772bIkm5pFUH:b2de3xe) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me change the commit message slightly. Our fix makes sense to me, and it's better to be on the safe side (what if someone has 42.0.0 - 42.0.1 on their platform).
</blockquote></details>

@woju I changed the commit message. Can you check if this reads well to you?

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1732#-Np44dHpBeTF72t_S-Kf:-Np5S90I7-p8N-sgP7zn:b-h4yfe) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju I changed the commit message. Can you check if this reads well to you?
</blockquote></details>

I meant, the main thing that we're fixing is, `to_bytes()` does not return bytes, but `bytearray`, which is confusing. After next week no one will ever see the affected versions. But whatever, this is also OK, I'm +1-ing.

___

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1732#-Np44dHpBeTF72t_S-Kf:-NpHnqpx6SH9x2VFqQdB:b5gvsxe) (no related file):*
> `to_bytes()` does not return bytes, but `bytearray`, which is confusing

I'm in favor of merging this PR just because of this - the current code is just confusing, so why not fix it up.

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
