### PR TITLE
[RA-TLS] Adapt for the new encrypted files API

### PR DESCRIPTION
**Pull request by NieDzejkob**
## Description of the changes 

This adapts the secret provisioning library and the example that uses it to make use of the new encrypted files APIs.

## How to test this PR? 

The `ra-tls-secret-prov` example, which is run by CI, should almost fully suffice, though the warnings and errors printed in some conditions need to be checked manually.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NieDzejkob)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BZd_T-n7GQRqiG_HJ):*
We don't write `RA-TLS` as a separate component in our commits. I suggest:
```
[Pal/Linux-SGX] Adapt RA-TLS for the new encrypted files API
```
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2B_Tp-6Gc_a1KSYGgT:-N2B_Tp-6Gc_a1KSYGgU:b-odi61d) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/CI-Examples/ra-tls-secret-prov/README.md#L79)):*
> ```Markdown
> 
> # test encrypted-files client
> gramine-sgx ./secret_prov_pf_client
> ```

We should rename `_pf_` to `_enc_files_` I guess.

We should also rename all those files in examples that have `pf` in their names (well, maybe it's only this `secret_prov_pf_client`).
___
*[`Pal/src/host/Linux-SGX/tools/common/util.h` line 100 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2Ba0mdDEPWPw5bMLd6:-N2Ba0mdDEPWPw5bMLd7:bpjx1oa) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/Pal/src/host/Linux-SGX/tools/common/util.h#L100)):*
> ```objc
>  *  \param[in]     buffer_size Size of the buffer.
>  *  \param[in]     masked      If non-NULL, this string will be used in error messages instead
>  *                             of the input hexstring itself. Use when parsing sensitive data.
> ```

Why such weird alignment of arguments? For uniformity with other parts of the code, it should be like this:
```
 *  \param[in] buffer_size  Size of the buffer.
```

Note the double-space after the arg name.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BbmG7-IunJYeUrr5y:-N2BbmG7-IunJYeUrr5z:b-hujlb4) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L334)):*
> ```C
> 
>         if (e) {
>             char keydata[16];
> ```

Instead of `16`, you should be able to use `sgx_key_128bit_t` here (declared in `sgx_arch.h` which is included in `ra_tls.h`), and you can do `sizeof(sgx_key_128bit_t)` to get 16.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BcDbq-hs4JgqUi9hD:-N2BcDbq-hs4JgqUi9hE:b-ouxjwy) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L340)):*
> ```C
>             char path_buf[256];
>             if (snprintf(path_buf, 256, "/dev/attestation/keys/%s", e) >= 256) {
>                 ERROR("Key name '%s' too long\n", path_buf);
> ```

But in this case, `path_buf` will be truncated and not null terminated, so you'll end up printing some garbage. Maybe change the error message to mention `e` instead of `path_buf`?
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2Bcdho2glRmkKLlm-O:-N2Bcdho2glRmkKLlm-P:bezcd45) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L340)):*
> ```C
>             char path_buf[256];
>             if (snprintf(path_buf, 256, "/dev/attestation/keys/%s", e) >= 256) {
>                 ERROR("Key name '%s' too long\n", path_buf);
> ```

Also, we don't print errors in this file. But now that I'm thinking about it -- maybe we should. Otherwise debugging this file is hard (I use GDB, but with log messages it would be much better for end users).

So maybe you could add log messages to other parts in this function?

**Review by NieDzejkob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: 7 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BZd_T-n7GQRqiG_HJ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't write `RA-TLS` as a separate component in our commits. I suggest:
```
[Pal/Linux-SGX] Adapt RA-TLS for the new encrypted files API
```
</blockquote></details>

Okay, TODO for rebase time.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2B_Tp-6Gc_a1KSYGgT:-N2MmiJb5Va-mX0A--gx:b-dtlav0) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/CI-Examples/ra-tls-secret-prov/README.md#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should rename `_pf_` to `_enc_files_` I guess.

We should also rename all those files in examples that have `pf` in their names (well, maybe it's only this `secret_prov_pf_client`).
</blockquote></details>

Considering the abbreviation is still alive in the name of `gramine-sgx-pf-{crypt,tamper}`, I wouldn't fret about removing it from examples at the moment.

(also it will conflict with #588)
___
*[`Pal/src/host/Linux-SGX/tools/common/util.h` line 100 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2Ba0mdDEPWPw5bMLd6:-N2MhgjxArNd454_7jjN:b-t45xmh) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/Pal/src/host/Linux-SGX/tools/common/util.h#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why such weird alignment of arguments? For uniformity with other parts of the code, it should be like this:
```
 *  \param[in] buffer_size  Size of the buffer.
```

Note the double-space after the arg name.
</blockquote></details>

Fixed. I was looking at `read_file` above as an example, but apparently extrapolated wrong.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BbmG7-IunJYeUrr5y:-N2Mi4O8A-U6KvoGioex:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Instead of `16`, you should be able to use `sgx_key_128bit_t` here (declared in `sgx_arch.h` which is included in `ra_tls.h`), and you can do `sizeof(sgx_key_128bit_t)` to get 16.
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BcDbq-hs4JgqUi9hD:-N2Mi4wbBtRk7jQAf7jW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L340)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But in this case, `path_buf` will be truncated and not null terminated, so you'll end up printing some garbage. Maybe change the error message to mention `e` instead of `path_buf`?
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2Bcdho2glRmkKLlm-O:-N2Mm3UHAEhQyeIkO9v3:b-ghr9f0) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L340)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also, we don't print errors in this file. But now that I'm thinking about it -- maybe we should. Otherwise debugging this file is hard (I use GDB, but with log messages it would be much better for end users).

So maybe you could add log messages to other parts in this function?
</blockquote></details>

I think that's best left for another PR, especially considering that we might want this one merged for the impending release.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2B_Tp-6Gc_a1KSYGgT:-N2RBtPTDerNMLskkXx0:be7wr5u) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/CI-Examples/ra-tls-secret-prov/README.md#L79)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Considering the abbreviation is still alive in the name of `gramine-sgx-pf-{crypt,tamper}`, I wouldn't fret about removing it from examples at the moment.

(also it will conflict with #588)
</blockquote></details>

OK, you're right.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2Bcdho2glRmkKLlm-O:-N2RC6O8-bTdpo5RRXkA:b-qezkjt) ([raw file](https://github.com/gramineproject/gramine/blob/0e30eda094f7b5d9396cb65a24da17a49bd8298b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L340)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

I think that's best left for another PR, especially considering that we might want this one merged for the impending release.
</blockquote></details>

Ok, fair enough.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @NieDzejkob)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BZd_T-n7GQRqiG_HJ):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Okay, TODO for rebase time.
</blockquote></details>

Actually, maybe we should start doing it? It's technically separate from SGX PAL. Not blocking though.
___
*[`Pal/src/host/Linux-SGX/tools/common/util.h` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WKroqCinBJpCIV7bg:-N2WKroqCinBJpCIV7bh:b-5nprnr) ([raw file](https://github.com/gramineproject/gramine/blob/286d11da39c3fcd39d7bfc4c7fc389525ae1e278/Pal/src/host/Linux-SGX/tools/common/util.h#L104)):*
> ```C
> const char* masked
> ```

I think it should be rather named `mask`.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 322 at r2](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WLuR2ERgZuRWV8Wce:-N2WLuR2ERgZuRWV8Wcf:bibgc98) ([raw file](https://github.com/gramineproject/gramine/blob/286d11da39c3fcd39d7bfc4c7fc389525ae1e278/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L322)):*
> ```C
> 
>         /* successfully retrieved the secret: is it a key for encrypted files? */
>         e = getenv(SECRET_PROVISION_SET_KEY);
> ```

Please use a more descriptive name (doesn't have to me long, just not a single random letter).



_Code quote:_
```C
e
```

**Review by NieDzejkob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Pal/src/host/Linux-SGX/tools/common/util.h` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WKroqCinBJpCIV7bg:-N2WO4xL1eoU_PSz-qTE:b-wkrf6v) ([raw file](https://github.com/gramineproject/gramine/blob/286d11da39c3fcd39d7bfc4c7fc389525ae1e278/Pal/src/host/Linux-SGX/tools/common/util.h#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```C
> const char* masked
> ```

I think it should be rather named `mask`.
</blockquote></details>

If you feel like that's better, OK. Renamed.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 322 at r2](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WLuR2ERgZuRWV8Wce:-N2WOD2WCYHLqxxAUBeg:b-di7w40) ([raw file](https://github.com/gramineproject/gramine/blob/286d11da39c3fcd39d7bfc4c7fc389525ae1e278/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L322)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use a more descriptive name (doesn't have to me long, just not a single random letter).
</blockquote></details>

Not new code, but I agree, a more descriptive name would be better. Cleaned it up a bit.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @NieDzejkob)

___
*[`Pal/src/host/Linux-SGX/tools/common/util.h` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WKroqCinBJpCIV7bg:-N2WQIP7Aai9RAAWZxhr:b-523rie) ([raw file](https://github.com/gramineproject/gramine/blob/286d11da39c3fcd39d7bfc4c7fc389525ae1e278/Pal/src/host/Linux-SGX/tools/common/util.h#L104)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

If you feel like that's better, OK. Renamed.
</blockquote></details>

Yeah, I prefer it because variable names usually describe "what is this variable", and "masked" sounds weird in this role.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 322 at r2](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WLuR2ERgZuRWV8Wce:-N2WQfp253Yuo1os-VBe:b1oy43p) ([raw file](https://github.com/gramineproject/gramine/blob/286d11da39c3fcd39d7bfc4c7fc389525ae1e278/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L322)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Not new code, but I agree, a more descriptive name would be better. Cleaned it up a bit.
</blockquote></details>

Oh, right. But now the function in longer so this name is more annoying ;) 
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 292 at r3](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WQZrZ9hLFeenLHLdD:-N2WQZrZ9hLFeenLHLdE:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/742b02935ea9d0f8950430469bcbd61c26be0bf2/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L292)):*
> ```C
> }
> 
> static bool truthy(const char *s) {
> ```





_Suggestion:_
```C
const char* s
```
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 323 at r3](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WQtUyCJz_e_-1nvVA:-N2WQtUyCJz_e_-1nvVB:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/742b02935ea9d0f8950430469bcbd61c26be0bf2/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L323)):*
> ```C
> 
>         /* successfully retrieved the secret: is it a key for encrypted files? */
>         const char *key_name = getenv(SECRET_PROVISION_SET_KEY);
> ```





_Suggestion:_
```C
const char* key_name
```
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 326 at r3](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WQvgp1RfJ76DRpBpI:-N2WQvgp1RfJ76DRpBpJ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/742b02935ea9d0f8950430469bcbd61c26be0bf2/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L326)):*
> ```C
>         if (!key_name) {
>             /* no key name specified - check old PF env var for compatibility */
>             const char *pf_key = getenv(SECRET_PROVISION_SET_PF_KEY);
> ```





_Suggestion:_
```C
const char* pf_key
```

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BZd_T-n7GQRqiG_HJ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, maybe we should start doing it? It's technically separate from SGX PAL. Not blocking though.
</blockquote></details>

It well may be that we will move RA-TLS and Secret Prov out of the core Gramine repo. Until we do so, let's keep the current style.

**Review by NieDzejkob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: 8 of 9 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @NieDzejkob)

___
*[`Pal/src/host/Linux-SGX/tools/common/util.h` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WKroqCinBJpCIV7bg:-N2WRp2f7wrNPaKGziLv:bxm2ubg) ([raw file](https://github.com/gramineproject/gramine/blob/286d11da39c3fcd39d7bfc4c7fc389525ae1e278/Pal/src/host/Linux-SGX/tools/common/util.h#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I prefer it because variable names usually describe "what is this variable", and "masked" sounds weird in this role.
</blockquote></details>

I thought of it as "masked content" or something like that.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 292 at r3](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WQZrZ9hLFeenLHLdD:-N2WS-3J1Te5FqWYByXr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/742b02935ea9d0f8950430469bcbd61c26be0bf2/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L292)):*
> ```C
> }
> 
> static bool truthy(const char *s) {
> ```

Done.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 323 at r3](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WQtUyCJz_e_-1nvVA:-N2WS0jb9T_v-2dhr0Ix:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/742b02935ea9d0f8950430469bcbd61c26be0bf2/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L323)):*
> ```C
> 
>         /* successfully retrieved the secret: is it a key for encrypted files? */
>         const char *key_name = getenv(SECRET_PROVISION_SET_KEY);
> ```

Done.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c` line 326 at r3](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WQvgp1RfJ76DRpBpI:-N2WS1EA6Bfyq3oDpQQQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/742b02935ea9d0f8950430469bcbd61c26be0bf2/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L326)):*
> ```C
>         if (!key_name) {
>             /* no key name specified - check old PF env var for compatibility */
>             const char *pf_key = getenv(SECRET_PROVISION_SET_PF_KEY);
> ```

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BZd_T-n7GQRqiG_HJ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It well may be that we will move RA-TLS and Secret Prov out of the core Gramine repo. Until we do so, let's keep the current style.
</blockquote></details>

sure
___
*[`Pal/src/host/Linux-SGX/tools/common/util.h` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/587#-N2WKroqCinBJpCIV7bg:-N2WS_Pb2_2aGqkwyrAU:b-ys98ip) ([raw file](https://github.com/gramineproject/gramine/blob/286d11da39c3fcd39d7bfc4c7fc389525ae1e278/Pal/src/host/Linux-SGX/tools/common/util.h#L104)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

I thought of it as "masked content" or something like that.
</blockquote></details>

Ah. But without the noun it reads differently, at least for me ;)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/587#-N2BZd_T-n7GQRqiG_HJ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

sure
</blockquote></details>

Done.

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/587)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
