### PR TITLE
[Docs] Add Technical Charter document

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The Technical Charter, copied from a Word document into an RST format.

## How to test this PR? 

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)

### CODE REVIEW

**Review by donporter — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097#-:-NKx18pr1VRCQ2Q72gFg:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by chiache — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by donporter — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1097#-NOivMdW03kPaN0M0vFw:-NOivMdW03kPaN0M0vFx:brv9rsw) (no related file):*
Why not adding it to the main docs? I don't like freestanding documents placed as files in random places without any links to them anywhere ;)

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1097#-NOivMdW03kPaN0M0vFw:-NOizg-8AwdcDYLptgda:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not adding it to the main docs? I don't like freestanding documents placed as files in random places without any links to them anywhere ;)
</blockquote></details>

Done.

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @donporter)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXfJDaXAizloD9nzSKJ:-NXfJDaXAizloD9nzSKK:bbkjen5) (no related file):*
@dimakuv: Could you rebase this PR? We merged the docs reorg recently and can proceed with this one now.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: 0 of 2 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @donporter and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXfJDaXAizloD9nzSKJ:-NXiLy57Ee3ekXN7oSzI:blcafws) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: Could you rebase this PR? We merged the docs reorg recently and can proceed with this one now.
</blockquote></details>

Done. Also temporarily enabled the ReadTheDocs rendering: https://gramine.readthedocs.io/en/dimakuv-add-technical-charter/devel/charter.html

___
___
*[`Documentation/devel/charter.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiNvcq5Uo2drot3g4L:-NXiNvcr0TCAoPRcDLz0:bt96kif) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L1)):*
> ```reStructuredText
> Technical Charter (the "Charter") for Gramine Project
> ```

Do we want/need this `the "Charter"` part? It looks ugly in the RTD rendering.
___
*[`Documentation/devel/charter.rst` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOD-rDfDmjr4r2jzK:-NXiOD-rDfDmjr4r2jzL:b-teme88) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L31)):*
> ```reStructuredText
> 2. The TSC voting members are initially the Project’s Committers. At the
>    inception of the project, the Committers of the Project will be as set forth
>    within the "CONTRIBUTING" file within the Project’s code repository.  The TSC
> ```

Well, we don't have the Committers (Maintainers) anymore in the CONTRIBUTING file: https://github.com/gramineproject/gramine/blob/master/CONTRIBUTING.rst

To avoid duplication, we moved this list to our ReadTheDocs as a separate page: https://gramine.readthedocs.io/en/dimakuv-add-technical-charter/management-team.html

What should we do? Do we add a link in CONTRIBUTING to that page? Or maybe there's a way to include that page into CONTRIBUTING.
___
*[`Documentation/devel/charter.rst` line 34 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOZJa0txo9nARxhqV:-NXiOZJa0txo9nARxhqW:b8fjaz8) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L34)):*
> ```reStructuredText
>    may choose an alternative approach for determining the voting members of the
>    TSC, and any such alternative approach will be documented in the CONTRIBUTING
>    file. Any meetings of the Technical Steering Committee are intended to be
> ```

Do we want to add links to this document? Here for example we could add a link to the Meeting Notes Gramine discussions.
___
*[`Documentation/devel/charter.rst` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOh-H5jyEtKqZOLoe:-NXiOh-H5jyEtKqZOLof:byfkj1u) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L47)):*
> ```reStructuredText
>    ii. Committers are Contributors who have earned the ability to modify
>        ("commit") source code, documentation or other technical artifacts in a
>        project’s repository; and
> ```

Do we want to add links to this document? Here for example we could add a link to https://gramine.readthedocs.io/en/dimakuv-add-technical-charter/devel/contributing.html
___
*[`Documentation/devel/charter.rst` line 127 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOpxZDRm4AWKJcrnG:-NXiOpxZDRm4AWKJcrnH:bai7wkn) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L127)):*
> ```reStructuredText
>    https://lfprojects.org/policies/.
> 
> 2. The TSC may adopt a code of conduct ("CoC") for the Project, which is subject
> ```

Do we want to add a link to https://github.com/gramineproject/gramine/blob/master/CODE_OF_CONDUCT.rst?

Also, a bit weird that the document says "may adopt" though we already adopted it.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: 0 of 2 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @donporter and @mkow)

___
*[`Documentation/devel/charter.rst` line 199 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiPE5l96As1VrozFDb:-NXiPE5l96As1VrozFDc:bbrxsvq) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L199)):*
> ```reStructuredText
>    i. All new inbound code contributions to the Project must be made using the
>       GNU Lesser General Public License version 3, available at
>       https://www.gnu.org/licenses/lgpl-3.0.en.html (the "Project License").
> ```

Here we could add a link to https://github.com/gramineproject/gramine/blob/master/LICENSE.txt and https://github.com/gramineproject/gramine/blob/master/LICENSE.addendum.txt
___
*[`Documentation/devel/charter.rst` line 202 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiPJZ7-aqjiAAi3tjw:-NXiPJZ7-aqjiAAi3tjx:b-szjeip) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L202)):*
> ```reStructuredText
> 
>    ii. All new inbound code contributions must also be accompanied by a
>        Developer Certificate of Origin (http://developercertificate.org)
> ```

Here we could add a link to https://gramine.readthedocs.io/en/dimakuv-add-technical-charter/devel/DCO/index.html

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`Documentation/devel/charter.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiNvcq5Uo2drot3g4L:-NXiQUa00NmxqO6BMNMj:b-q05ogt) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L1)):*
> Do we want/need this `the "Charter"` part?

I'm fine w/ removing it, if it's not required to follow the template. If it's required, should the full title be `Technical Charter (the "Charter") for Gramine Project a Series of LF Projects, LLC`?
___
*[`Documentation/devel/charter.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiUspgBsNFbwvlRu_p:-NXiUspgBsNFbwvlRu_q:b-dpmp1c) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L1)):*
> ```reStructuredText
> Technical Charter (the "Charter") for Gramine Project
> ```

I'm not sure on this -- should we move this to a `CHARTER.rst` at the top-level of the project and just put a link here (similar to `CONTRIBUTING.rst`)?
___
*[`Documentation/devel/charter.rst` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiR34eB8LVpwN0NejS:-NXiR34eB8LVpwN0NejT:b-vs1ro2) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L3)):*
> ```reStructuredText
> Technical Charter (the "Charter") for Gramine Project
> =====================================================
> ```

According to the template, should we have sth. like `Adopted <date>` here?
___
*[`Documentation/devel/charter.rst` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOD-rDfDmjr4r2jzK:-NXiSi8f5V4F2-ah2s-Y:b-x3eynr) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, we don't have the Committers (Maintainers) anymore in the CONTRIBUTING file: https://github.com/gramineproject/gramine/blob/master/CONTRIBUTING.rst

To avoid duplication, we moved this list to our ReadTheDocs as a separate page: https://gramine.readthedocs.io/en/dimakuv-add-technical-charter/management-team.html

What should we do? Do we add a link in CONTRIBUTING to that page? Or maybe there's a way to include that page into CONTRIBUTING.
</blockquote></details>

This is actually a technical charter (which is kind of high-level) -- do we need/want to add any Gramine specific doc/info links into a such charter? Same question for all the below notes.
___
*[`Documentation/devel/charter.rst` line 127 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOpxZDRm4AWKJcrnG:-NXiTOxGBJor6oqJvYy6:b90ftnk) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want to add a link to https://github.com/gramineproject/gramine/blob/master/CODE_OF_CONDUCT.rst?

Also, a bit weird that the document says "may adopt" though we already adopted it.
</blockquote></details>

I think it's fine w/ the `may` here, since it's a charter and we may someday abandon the adopted CoC.
___
*[`Documentation/devel/charter.rst` line 206 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiS72r5yxYppyKq8Yw:-NXiS72r5yxYppyKq8Yx:bnabmwz) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L206)):*
> ```reStructuredText
>        TSC-approved contribution process which will bind the authorized
>        contributor and, if not self-employed, their employer to the applicable
>        license;
> ```

`;` -> `.`



_Code quote:_
```reStructuredText
;
```

**Review by donporter — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: all files reviewed, 11 unresolved discussions (waiting on @dimakuv and @mkow)

___
*[`Documentation/devel/charter.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiNvcq5Uo2drot3g4L:-N_dJUAvERLHJbEUv6yD:b-wl0n56) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Do we want/need this `the "Charter"` part?

I'm fine w/ removing it, if it's not required to follow the template. If it's required, should the full title be `Technical Charter (the "Charter") for Gramine Project a Series of LF Projects, LLC`?
</blockquote></details>

I don't know that we should do minor wording tweaks; isn't the point to just post the official/legal charter?
___
*[`Documentation/devel/charter.rst` line 34 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOZJa0txo9nARxhqV:-N_dKbBmEmE0YFbybdp3:bf5sscz) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want to add links to this document? Here for example we could add a link to the Meeting Notes Gramine discussions.
</blockquote></details>

Seems like a nice idea to me.
___
*[`Documentation/devel/charter.rst` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOh-H5jyEtKqZOLoe:-N_dKdm7-5MSSDpp0kvw:be43zhg) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want to add links to this document? Here for example we could add a link to https://gramine.readthedocs.io/en/dimakuv-add-technical-charter/devel/contributing.html
</blockquote></details>

Seems like it can't hurt.
___
*[`Documentation/devel/charter.rst` line 127 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOpxZDRm4AWKJcrnG:-N_dKi8-5enMjMRN2N1V:b-xulka7) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L127)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think it's fine w/ the `may` here, since it's a charter and we may someday abandon the adopted CoC.
</blockquote></details>

Or that this predates the code of conduct.  Perhaps one could add a footnote or pop-up/parenthetical that indicates that a CoC was adopted+link?
___
*[`Documentation/devel/charter.rst` line 199 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiPE5l96As1VrozFDb:-N_dKw6R9afbXIfECKjB:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L199)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here we could add a link to https://github.com/gramineproject/gramine/blob/master/LICENSE.txt and https://github.com/gramineproject/gramine/blob/master/LICENSE.addendum.txt
</blockquote></details>

+1
___
*[`Documentation/devel/charter.rst` line 202 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiPJZ7-aqjiAAi3tjw:-N_dKyV46mWqOOKffdY4:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L202)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here we could add a link to https://gramine.readthedocs.io/en/dimakuv-add-technical-charter/devel/DCO/index.html
</blockquote></details>

+1

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @donporter, @kailun-qin, and @mkow)

___
*[`Documentation/devel/charter.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiNvcq5Uo2drot3g4L:-NcLq_OU08IrKVaz8YLe:b-ft8408) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L1)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I don't know that we should do minor wording tweaks; isn't the point to just post the official/legal charter?
</blockquote></details>

Done. Kailun is right, looking at other examples, that's what projects write.
___
*[`Documentation/devel/charter.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiUspgBsNFbwvlRu_p:-NcLqz2u-ltF5P9agTuq:by3i8i7) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I'm not sure on this -- should we move this to a `CHARTER.rst` at the top-level of the project and just put a link here (similar to `CONTRIBUTING.rst`)?
</blockquote></details>

Done, sounds reasonable.
___
*[`Documentation/devel/charter.rst` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiR34eB8LVpwN0NejS:-NcM-uinCPPfRJoV_FXs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L3)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

According to the template, should we have sth. like `Adopted <date>` here?
</blockquote></details>

Done.
___
*[`Documentation/devel/charter.rst` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOD-rDfDmjr4r2jzK:-NcM0DSrBg72mDgOOdHn:b-xk46hl) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L31)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This is actually a technical charter (which is kind of high-level) -- do we need/want to add any Gramine specific doc/info links into a such charter? Same question for all the below notes.
</blockquote></details>

Done, Ok, I'm not doing anything about this text, I'll leave it high-level.
___
*[`Documentation/devel/charter.rst` line 34 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOZJa0txo9nARxhqV:-NcM0J2h6j8FsoMazP_r:br7i9a3) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L34)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Seems like a nice idea to me.
</blockquote></details>

As mentioned by Kailun, I would keep this Charter document high-level. I don't want to add links, which may at some point get stale.
___
*[`Documentation/devel/charter.rst` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOh-H5jyEtKqZOLoe:-NcM0QLaCirPruXmKScp:br7i9a3) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L47)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Seems like it can't hurt.
</blockquote></details>

As mentioned by Kailun, I would keep this Charter document high-level. I don't want to add links, which may at some point get stale.
___
*[`Documentation/devel/charter.rst` line 127 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiOpxZDRm4AWKJcrnG:-NcM0SDA4kDRxhf11VEI:br7i9a3) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L127)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Or that this predates the code of conduct.  Perhaps one could add a footnote or pop-up/parenthetical that indicates that a CoC was adopted+link?
</blockquote></details>

As mentioned by Kailun, I would keep this Charter document high-level. I don't want to add links, which may at some point get stale.
___
*[`Documentation/devel/charter.rst` line 199 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiPE5l96As1VrozFDb:-NcM0UPA-jEojwtOtuDN:br7i9a3) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L199)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

+1
</blockquote></details>

As mentioned by Kailun, I would keep this Charter document high-level. I don't want to add links, which may at some point get stale.
___
*[`Documentation/devel/charter.rst` line 202 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiPJZ7-aqjiAAi3tjw:-NcM0VNM-c9SQPjpk1GE:br7i9a3) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L202)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

+1
</blockquote></details>

As mentioned by Kailun, I would keep this Charter document high-level. I don't want to add links, which may at some point get stale.
___
*[`Documentation/devel/charter.rst` line 206 at r4](https://reviewable.io/reviews/gramineproject/gramine/1097#-NXiS72r5yxYppyKq8Yw:-NcM0ZneDNVV1aQCYcM_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d155c7e1edf2c9f0ef786c1f0e536ba9a0eaf7b/Documentation/devel/charter.rst#L206)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

`;` -> `.`
</blockquote></details>

Done.

**Review by donporter — DISMISSED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: all files reviewed, 3 unresolved discussions (waiting on @kailun-qin and @mkow)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: all files reviewed, 5 unresolved discussions (waiting on @dimakuv and @kailun-qin)

___
*[`CHARTER.rst` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/1097#-NcU2CQ08kHxOL4gchB6:-NcU2CQ08kHxOL4gchB7:b-e8shfn) ([raw file](https://github.com/gramineproject/gramine/blob/26b1dc06fdc231c69bbcd480f4945832cfc8e1c9/CHARTER.rst#L1)):*
> ```reStructuredText
> Technical Charter (the "Charter") for Gramine Project a Series of LF Projects, LLC
> ```

This doesn't look good in the ToC, because the whole title is printed there and it takes three lines :grimacing:
___
*[`CHARTER.rst` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/1097#-NcU2ZRg05bHZbvLgbH0:-NcU2ZRg05bHZbvLgbH1:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/26b1dc06fdc231c69bbcd480f4945832cfc8e1c9/CHARTER.rst#L1)):*
> ```reStructuredText
> Technical Charter (the "Charter") for Gramine Project a Series of LF Projects, LLC
> ```





_Suggestion:_
```reStructuredText
Project, a Series of LF Projects LLC
```
___
*[`CHARTER.rst` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/1097#-NcU9fp-6DyP6PTMKvxz:-NcU9fp-6DyP6PTMKvy-:b-yh5c6x) ([raw file](https://github.com/gramineproject/gramine/blob/26b1dc06fdc231c69bbcd480f4945832cfc8e1c9/CHARTER.rst#L4)):*
> ```reStructuredText
> ==================================================================================
> 
> Adopted August 21, 2023.
> ```

Not on 14 Sept 2020?



_Suggestion:_
```reStructuredText
Adopted on August 21, 2023.
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

___
*[`CHARTER.rst` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/1097#-NcU2CQ08kHxOL4gchB6:-NcVczzy8FgarAndHej2:b-gv5yeh) ([raw file](https://github.com/gramineproject/gramine/blob/26b1dc06fdc231c69bbcd480f4945832cfc8e1c9/CHARTER.rst#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This doesn't look good in the ToC, because the whole title is printed there and it takes three lines :grimacing:
</blockquote></details>

Done. I know, but this is how it is in the official template and in other examples on the internet.

Anyway, I think we can do cosmetic changes to this document, so I shortened the title and instead added a sentence below.
___
*[`CHARTER.rst` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/1097#-NcU2ZRg05bHZbvLgbH0:-NcVd9SvD9SczDeSLy_H:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/26b1dc06fdc231c69bbcd480f4945832cfc8e1c9/CHARTER.rst#L1)):*
> ```reStructuredText
> Technical Charter (the "Charter") for Gramine Project a Series of LF Projects, LLC
> ```

Done.
___
*[`CHARTER.rst` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/1097#-NcU9fp-6DyP6PTMKvxz:-NcVdAiM0o9pOplZL9uA:bblxouy) ([raw file](https://github.com/gramineproject/gramine/blob/26b1dc06fdc231c69bbcd480f4945832cfc8e1c9/CHARTER.rst#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not on 14 Sept 2020?
</blockquote></details>

Done. I didn't know which date to put here exactly, but you're right, it makes more sense to have the date of the actual adoption of that Word document.

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`CHARTER.rst` line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/1097#-NcVe8zf694ECv_X7tSM:-NcVe8zf694ECv_X7tSN:bkxnee2) ([raw file](https://github.com/gramineproject/gramine/blob/ebc023eb30c059dfb9f3d32a2531997e8b7861a4/CHARTER.rst#L4)):*
> ```reStructuredText
> =================
> 
> This is a Technical Charter (the "Charter") for Gramine Project, a Series of LF
> ```

-> `the`?



_Code quote:_
```reStructuredText
a
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: 2 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`CHARTER.rst` line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/1097#-NcVe8zf694ECv_X7tSM:-NcVenaI03jo2gZk6Xfm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ebc023eb30c059dfb9f3d32a2531997e8b7861a4/CHARTER.rst#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `the`?
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1097)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
