### PR TITLE
[PAL/Linux-SGX] Add missing fields in local attestation

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
See the commits.

## How to test this PR? 
You need a machine which reports `1` (or rather lowest bit set) in supported miscselect (you can use `is-sgx-available` from https://github.com/gramineproject/gramine/pull/1075 PR to check). Then try enabling `exinfo` in manifest - without this PR local attestation will fail.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)

### CODE REVIEW

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Debug-20.04 please (GH fetch failed, Jenkins or GH hiccup)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Debug-Sanitizers please (GH fetch failed, Jenkins or GH hiccup)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Direct-Sanitizers please (GH fetch failed, Jenkins or GH hiccup)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: 11 of 12 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6Gqxb-bKbxN5OprMD):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add as the first sentence that we remove a step of send/receive of `targetinfo` of the peer enclave in the local-attestation protocol in Gramine.
</blockquote></details>

How about:

```
[PAL/Linux-SGX] Clean up local attestation code

Local attestation previously ignored some fields of target info
structure, which is fixed by this commit.
Also, since in Gramine parent and child enclave have the very same
measurements and initial configuration, we can skip sending TARGETINFO
structure in local attestation.
```
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 1103 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6BKFxCP0n5YVuk9Et:-NJ6g65NBaXPi60DPUMD:b3cwdob) ([raw file](https://github.com/gramineproject/gramine/blob/43e2826cdfc5973c2662ab50817dbfc2db6343de/pal/src/host/linux-sgx/enclave_framework.c#L1103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Rather weird style of assigning fields, I guess you wanted to implicitly set reserved/all other fields to zeros? Not blocking.
</blockquote></details>

What's weird about it? I find it much more readable than memset(0) + wall of memcpy's. Plus it gives some type checking.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 1154 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6CslUEdtxBSeSI22u:-NJ6ggVe6jJam2EjW3dD:b-wta1de) ([raw file](https://github.com/gramineproject/gramine/blob/43e2826cdfc5973c2662ab50817dbfc2db6343de/pal/src/host/linux-sgx/enclave_framework.c#L1154)):*
Correct. Plus I'm not sure whether it was a security issue that we sent targetinfo via unencrypted channel (I guess no, but I didn't think much about it).

> Could we rename?

I guess, but to what? We still need asymmetry, one process does read+write, another does write+read.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 1184 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6EQc0BEuY4LoCle2A:-NJ7-0v308aj9qdGLhQm:byo7ztk) ([raw file](https://github.com/gramineproject/gramine/blob/9448770353531d498ef40b37add1284b7eff7ed0/pal/src/host/linux-sgx/enclave_framework.c#L1184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove deleting the stream (the shutdown of the UNIX socket, if I understand correctly)?

UPDATE: You close it in the caller.
</blockquote></details>

It made no sense, to close it here.
___
*[`pal/src/host/linux-sgx/pal_process.c` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6F9MTDy1jukYtxPQ5:-NJ7-X1E5Pfl8lnngaJJ:b-gn9ak8) ([raw file](https://github.com/gramineproject/gramine/blob/43e2826cdfc5973c2662ab50817dbfc2db6343de/pal/src/host/linux-sgx/pal_process.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You eliminated the step `send SGX target info ...`, so you should rewrite this paragraph.
</blockquote></details>

Removed, as it does not apply now.
___
*[`pal/src/host/linux-sgx/pal_process.c` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6FGozBkDCSMxN61ZA:-NJ7-roh6MvLP3VqZS11:biann8r) ([raw file](https://github.com/gramineproject/gramine/blob/43e2826cdfc5973c2662ab50817dbfc2db6343de/pal/src/host/linux-sgx/pal_process.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You removed `SGX targetinfo`, so you should modify this paragraph (keep only `SGX report` as "identity").
</blockquote></details>

Not really. We still have `SGX targetinfo` as identity, it's just not sent, because it's the same in parent and child. But different enclaves have different tragetinfo.
___
*[`pal/src/host/linux-sgx/pal_process.c` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6FQkr4bv9S5dAW4rR:-NJ70lRm2j-vQyvD-Vbr:b-5tejkh) ([raw file](https://github.com/gramineproject/gramine/blob/43e2826cdfc5973c2662ab50817dbfc2db6343de/pal/src/host/linux-sgx/pal_process.c#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here we say `target identity of the peer enclave`, which is still correct. But I would add in parentheses that the target identity is exactly the same as this enclave's identity (so we use this simplification in our protocol to NOT send targetinfos).
</blockquote></details>

But in this paragraph it doesn't matter. It only says that CMAC is over a structure that contains target enclave identity, it's irrelevant whether it's the same of different as current's enclave one.
___
*[`pal/src/host/linux-sgx/pal_process.c` line 118 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6Fo9Y8KTYMUx2Ubis:-NJ71Prh1-h_gO8YP6lE:b-ga5uqu) ([raw file](https://github.com/gramineproject/gramine/blob/43e2826cdfc5973c2662ab50817dbfc2db6343de/pal/src/host/linux-sgx/pal_process.c#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, shouldn't we just include `config_svn` and `config_id` in this check?

UPDATE: Looking at the `memcmp` check here, isn't it what we already do, so the comment is stale?
</blockquote></details>

Not sure what you mean. We do include them in this check, but the comment says we possibly might want **not** to do so. I would say we never want to do that, but who knows.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6Gqxb-bKbxN5OprMD):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How about:

```
[PAL/Linux-SGX] Clean up local attestation code

Local attestation previously ignored some fields of target info
structure, which is fixed by this commit.
Also, since in Gramine parent and child enclave have the very same
measurements and initial configuration, we can skip sending TARGETINFO
structure in local attestation.
```
</blockquote></details>

Sounds good to me. Please add a squash commit or just rebase with this message.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 1154 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6CslUEdtxBSeSI22u:-NJ7BQm76Rp_mesL4WFl:b58c7g7) ([raw file](https://github.com/gramineproject/gramine/blob/43e2826cdfc5973c2662ab50817dbfc2db6343de/pal/src/host/linux-sgx/enclave_framework.c#L1154)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Correct. Plus I'm not sure whether it was a security issue that we sent targetinfo via unencrypted channel (I guess no, but I didn't think much about it).

> Could we rename?

I guess, but to what? We still need asymmetry, one process does read+write, another does write+read.
</blockquote></details>

Ok, whatever, the names are not important.
___
*[`pal/src/host/linux-sgx/pal_process.c` line 118 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6Fo9Y8KTYMUx2Ubis:-NJ7BlUE3bcV4ET84FGp:bxmexw5) ([raw file](https://github.com/gramineproject/gramine/blob/43e2826cdfc5973c2662ab50817dbfc2db6343de/pal/src/host/linux-sgx/pal_process.c#L118)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not sure what you mean. We do include them in this check, but the comment says we possibly might want **not** to do so. I would say we never want to do that, but who knows.
</blockquote></details>

Right, misread (and forgot how `configid` is used).

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJ6Gqxb-bKbxN5OprMD):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sounds good to me. Please add a squash commit or just rebase with this message.
</blockquote></details>

I blocked myself, so I don't forget to do it on final rebase

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/enclave_ecalls.c` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJG8kBQDPk7U8spnvrj:-NJG8kBRDaCRWFpOO4DU:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/8decefc3631c7e88fc39cd269566e4143d9f9be5/pal/src/host/linux-sgx/enclave_ecalls.c#L15)):*
> ```C
> 
> /* This eats 1KB of a stack, so prevent inlining. */
> __attribute__ ((noinline)) static void init_xsave_size_from_report(void) {
> ```





_Suggestion:_
```C
__attribute__((noinline))
```
___
*[`pal/src/host/linux-sgx/pal_linux.h` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJGA5Cg4cNw1COl7F64:-NJGA5Cg4cNw1COl7F65:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/8decefc3631c7e88fc39cd269566e4143d9f9be5/pal/src/host/linux-sgx/pal_linux.h#L120)):*
> ```objc
>  * \brief Fill sgx_target_info_t with information from sgx_report_body_t
>  */
> void sgx_report_body_to_target_info(sgx_report_body_t* report_body, sgx_target_info_t* target_info);
> ```





_Suggestion:_
```objc
out_target_info
```
___
*[`pal/src/host/linux-sgx/pal_process.c` line 91 at r2](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJGC07GC7DBd3D6DBeB:-NJGC07GC7DBd3D6DBeC:bx3lmbb) ([raw file](https://github.com/gramineproject/gramine/blob/9448770353531d498ef40b37add1284b7eff7ed0/pal/src/host/linux-sgx/pal_process.c#L91)):*
> ```C
>  *         - Parent: Verify report(Child -> Parent)
>  *         - Parent: Extract targetinfo(Child) from report(Child -> Parent)
>  *                   and then generate report(Parent -> Child)
> ```

I had exactly this simplification on my TODOlist, but never managed to get to it :)
___
*[`pal/src/host/linux-sgx/pal_process.c` line 185 at r2](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJGCvDHEQUZhI3bEKUT:-NJGCvDHEQUZhI3bEKUU:b-12z7kf) ([raw file](https://github.com/gramineproject/gramine/blob/8decefc3631c7e88fc39cd269566e4143d9f9be5/pal/src/host/linux-sgx/pal_process.c#L185)):*
> ```C
> 
> failed:
>     _PalStreamDelete(child, PAL_DELETE_ALL);
> ```

Isn't `_PalObjectClose()` enough for process objects?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/enclave_ecalls.c` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJG8kBQDPk7U8spnvrj:-NJGfz_vDMLX3P1BtqmS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8decefc3631c7e88fc39cd269566e4143d9f9be5/pal/src/host/linux-sgx/enclave_ecalls.c#L15)):*
> ```C
> 
> /* This eats 1KB of a stack, so prevent inlining. */
> __attribute__ ((noinline)) static void init_xsave_size_from_report(void) {
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_linux.h` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJGA5Cg4cNw1COl7F64:-NJGk21e0q7rm7SqqUST:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8decefc3631c7e88fc39cd269566e4143d9f9be5/pal/src/host/linux-sgx/pal_linux.h#L120)):*
> ```objc
>  * \brief Fill sgx_target_info_t with information from sgx_report_body_t
>  */
> void sgx_report_body_to_target_info(sgx_report_body_t* report_body, sgx_target_info_t* target_info);
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_process.c` line 185 at r2](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJGCvDHEQUZhI3bEKUT:-NJGkDIo1dAht70Ubx5N:bbnjgk5) ([raw file](https://github.com/gramineproject/gramine/blob/8decefc3631c7e88fc39cd269566e4143d9f9be5/pal/src/host/linux-sgx/pal_process.c#L185)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't `_PalObjectClose()` enough for process objects?
</blockquote></details>

No idea, I just moved the delete call from within some random function call

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/pal_process.c` line 185 at r2](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJGCvDHEQUZhI3bEKUT:-NJH_s_a3bxHJhZtytuc:b9o7jja) ([raw file](https://github.com/gramineproject/gramine/blob/8decefc3631c7e88fc39cd269566e4143d9f9be5/pal/src/host/linux-sgx/pal_process.c#L185)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No idea, I just moved the delete call from within some random function call
</blockquote></details>

Ok, unblocking then. But looks strange, closing the handle should do everything which is needed.

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/pal_process.c` line 83 at r5](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJHlEGS4KZQnETw7Onp:-NJHlEGT66obS49FXKeB:b-mjymrj) ([raw file](https://github.com/gramineproject/gramine/blob/a347179de3fcd532f862699fe089c541060687c1/pal/src/host/linux-sgx/pal_process.c#L83)):*
> ```C
>  *         - Child:  Verify report(Parent -> Child)
> *
> *       Note that both Parent and Child have the same SGX target info.
> ```

Just noticed this misformatting (look at the line beginning). Want to again and fix, or whatever?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`pal/src/host/linux-sgx/pal_process.c` line 83 at r5](https://reviewable.io/reviews/gramineproject/gramine/1074#-NJHlEGS4KZQnETw7Onp:-NJHn8J6-zjx81Spz5gM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a347179de3fcd532f862699fe089c541060687c1/pal/src/host/linux-sgx/pal_process.c#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just noticed this misformatting (look at the line beginning). Want to again and fix, or whatever?
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1074)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
