### PR TITLE
[Docs] Fix `git clone <branch>` shallow copy

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

By mistake, our Quick start guide and Cloud deployment pages contained:
```
git clone https://github.com/gramineproject/gramine.git <branch>
```

This is supposed to clone a single commit of Gramine (for CI-Examples testing). But this command clones the master branch of Gramine into a directory named `<branch>`. The correct form should be:
```
git clone https://github.com/gramineproject/gramine.git --branch <branch>
```

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/624#-N3U5GqUBEplT65lkXO7):*




_Suggestion:_
```
branch
```
___
*[`Documentation/conf.py` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/624#-N3U5YN85YCudcqMdZVq:-N3U5YN85YCudcqMdZVr:b-ed8x9s) ([raw file](https://github.com/gramineproject/gramine/blob/cc766d572ac4b5c0217cb51fb96fa225dc8008fa/Documentation/conf.py#L81)):*
> ```Python
> primary_domain = 'c'
> 
> rst_stable_checkout = 'master'
> ```

@woju: How does this work? It will influence `en/stable/` or something more?

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Documentation/conf.py` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/624#-N3U5YN85YCudcqMdZVq:-N3UJYSC6IRWuhfQFDSo:b-a5zisd) ([raw file](https://github.com/gramineproject/gramine/blob/cc766d572ac4b5c0217cb51fb96fa225dc8008fa/Documentation/conf.py#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The `en/latest` page will render like this:
```
git clone --depth 1 https://github.com/gramineproject/gramine.git --branch master
```

Currently the `en/latest` page looks like this:
```
git clone --depth 1 https://github.com/gramineproject/gramine.git
```

I like the new version better -- it is more explicit. But I can change, if someone insists.
</blockquote></details>

What about `en/stable/`?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Documentation/conf.py` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/624#-N3U5YN85YCudcqMdZVq:-N3ULGFL2y5_gfSw1v3t:b87559u) ([raw file](https://github.com/gramineproject/gramine/blob/cc766d572ac4b5c0217cb51fb96fa225dc8008fa/Documentation/conf.py#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about `en/stable/`?
</blockquote></details>

The `en/stable/` page will render like this:
```
git clone --depth 1 https://github.com/gramineproject/gramine.git --branch v1.3
```

Unfortunately, this will start happenning only when we have a new release (v1.3).

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/conf.py` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/624#-N3U5YN85YCudcqMdZVq:-N3UksV66PLQgdZ9yBo3:b-9ido38) ([raw file](https://github.com/gramineproject/gramine/blob/cc766d572ac4b5c0217cb51fb96fa225dc8008fa/Documentation/conf.py#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The `en/stable/` page will render like this:
```
git clone --depth 1 https://github.com/gramineproject/gramine.git --branch v1.3
```

Unfortunately, this will start happenning only when we have a new release (v1.3).
</blockquote></details>

I'd prefer to `/en/latest` version still render without `--branch`. For simplicity. I don't think being explicit helps here.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by dimakuv — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/conf.py` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/624#-N3U5YN85YCudcqMdZVq:-N3VEUpp63mHj198wviw:bm3yqt3) ([raw file](https://github.com/gramineproject/gramine/blob/cc766d572ac4b5c0217cb51fb96fa225dc8008fa/Documentation/conf.py#L81)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'd prefer to `/en/latest` version still render without `--branch`. For simplicity. I don't think being explicit helps here.
</blockquote></details>

OK, done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/624#-N3U5GqUBEplT65lkXO7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase. Blocked myself.
</blockquote></details>

I did the rebase and fixed this.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/624)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
