### PR TITLE
[LibOS] Import simple Linux types

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

This is a part of making our LibOS independent from the host headers (we want this b/c the host may not even be Linux).

Continuation of #1275, #1301, #1426 and #1541.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)

### CODE REVIEW

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: 0 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`libos/include/linux_abi/poll.h` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDQdN_5v3R4t5PlJgI:-NeDQdNa3i1ILH-argmT:bdgu5wj) ([raw file](https://github.com/gramineproject/gramine/blob/80d0edd407ae43fec2323d9bec8cfa8a203c6eea/libos/include/linux_abi/poll.h#L14)):*
> ```objc
> #include <linux/eventpoll.h>
> 
> struct linux_fd_set {
> ```

The renaming was needed because PAL imports some of the LibOS headers and they can clash with host headers. So, I propose to prefix our Linux ABI structs with `linux_`. What do you think?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDanH6-isyqWwjV7qR):*
The name of the commit is misleading. This PR is more like a bunch of small-ish changes to the headers (untangling the "big fat" `types.h` header + types and macros here and there).

But also, I don't have a better name... Maybe simply `[LibOS] Continue replacing Linux types`
___
*[`libos/include/linux_abi/poll.h` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDQdN_5v3R4t5PlJgI:-NeDa0AzEo8RSxLy3vyO:bwfzcml) ([raw file](https://github.com/gramineproject/gramine/blob/80d0edd407ae43fec2323d9bec8cfa8a203c6eea/libos/include/linux_abi/poll.h#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The renaming was needed because PAL imports some of the LibOS headers and they can clash with host headers. So, I propose to prefix our Linux ABI structs with `linux_`. What do you think?
</blockquote></details>

I like the `linux_` prefix.
___
*[`libos/include/linux_abi/sysinfo.h` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDaSd21uwYqXk1I8Hs:-NeDaSd21uwYqXk1I8Ht:bg6v019) ([raw file](https://github.com/gramineproject/gramine/blob/80d0edd407ae43fec2323d9bec8cfa8a203c6eea/libos/include/linux_abi/sysinfo.h#L11)):*
> ```objc
> /* These need to be binary-identical with the ones used by Linux. */
> 
> #include <linux/utsname.h>
> ```

Why not expand this header in this PR? It should be just a couple of macros/types, I would assume.
___
*[`libos/src/fs/libos_fs_pseudo.c` line 204 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDa8YP-836Z9nQCyZ2:-NeDa8YP-836Z9nQCyZ3:b-uw10t5) ([raw file](https://github.com/gramineproject/gramine/blob/80d0edd407ae43fec2323d9bec8cfa8a203c6eea/libos/src/fs/libos_fs_pseudo.c#L204)):*
> ```C
> }
> 
> static uint64_t makedev(unsigned int major, unsigned int minor) {
> ```

Why is it 64-bit, whereas in `types_arch.h` it's 32-bit?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: 9 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDanH6-isyqWwjV7qR):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The name of the commit is misleading. This PR is more like a bunch of small-ish changes to the headers (untangling the "big fat" `types.h` header + types and macros here and there).

But also, I don't have a better name... Maybe simply `[LibOS] Continue replacing Linux types`
</blockquote></details>

Fine with me, except `replacing` -> `importing`.
___
*[`libos/include/linux_abi/sysinfo.h` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDaSd21uwYqXk1I8Hs:-NeGCRVS1fcl0A7p8RoE:b-1eh3wi) ([raw file](https://github.com/gramineproject/gramine/blob/80d0edd407ae43fec2323d9bec8cfa8a203c6eea/libos/include/linux_abi/sysinfo.h#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not expand this header in this PR? It should be just a couple of macros/types, I would assume.
</blockquote></details>

Sure, done.
___
*[`libos/src/fs/libos_fs_pseudo.c` line 204 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDa8YP-836Z9nQCyZ2:-NeG9dPXEMmfqtkq-9BF:byozaan) ([raw file](https://github.com/gramineproject/gramine/blob/80d0edd407ae43fec2323d9bec8cfa8a203c6eea/libos/src/fs/libos_fs_pseudo.c#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is it 64-bit, whereas in `types_arch.h` it's 32-bit?
</blockquote></details>

It's not, `types_arch.h` defines `dev_t` which is not used here. `stat` struct doesn't contain any `dev_t` fields, it was a bug in the old code.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDanH6-isyqWwjV7qR):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Fine with me, except `replacing` -> `importing`.
</blockquote></details>

Sounds good to me.
___
*[`libos/include/linux_abi/sysinfo.h` line 13 at r2](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeHimmb8v7iqG2OdlYA:-NeHimmb8v7iqG2OdlYB:b8127pb) ([raw file](https://github.com/gramineproject/gramine/blob/299fa60314446aa472819dbcf431ff2d1442c25f/libos/include/linux_abi/sysinfo.h#L13)):*
> ```objc
> #define __NEW_UTS_LEN 64
> 
> struct new_utsname {
> ```

So what's our logic -- when do we prepend `linux_` prefix to data structs? Is it only when the data struct conflicts with the one in PAL?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: 7 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/include/linux_abi/sysinfo.h` line 13 at r2](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeHimmb8v7iqG2OdlYA:-NeJA5HJ7CVVTqdRUpmZ:buvdj8w) ([raw file](https://github.com/gramineproject/gramine/blob/299fa60314446aa472819dbcf431ff2d1442c25f/libos/include/linux_abi/sysinfo.h#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would too add to all of them, except the trivial types.

So why don't you add the `linux_` prefix in this particular case?
</blockquote></details>

Ohhh, that's why you asked about it here, sorry. Yeah, I just forgot to prefix this struct, fixed.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/include/linux_abi/sysinfo.h` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeJogCw2jKe3XWEMgdw:-NeJogCx1pk86Fpg1dng:b-kdv48z) ([raw file](https://github.com/gramineproject/gramine/blob/1986dffa81cc62e280ac5dc13fb92b839789b322/libos/include/linux_abi/sysinfo.h#L23)):*
> ```objc
> 
> /* Copied and slightly adapted from linux/include/uapi/linux/sysinfo.h, ver 5.11. */
> struct sysinfo {
> ```

What about this one? Do we want to prefix with `linux_`?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/include/linux_abi/sysinfo.h` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeJogCw2jKe3XWEMgdw:-NeKIrvh2XwAz8sEOtWB:b-q1ivzy) ([raw file](https://github.com/gramineproject/gramine/blob/1986dffa81cc62e280ac5dc13fb92b839789b322/libos/include/linux_abi/sysinfo.h#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this one? Do we want to prefix with `linux_`?
</blockquote></details>

Yes, but I'll rename older structs later, in one go (there are many more structs / types requiring renaming, grep for e.g. `__kernel_`).
In this PR I just wanted to clean up the `types.h` header.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1551#-NeDanH6-isyqWwjV7qR):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sounds good to me.
</blockquote></details>

Done

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Comment by woju** [comment]
Jenkins, test Jenkins-SGX-EDMM please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-EDMM please (seems to work now)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1551)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Pull request merged**
