### PR TITLE
[CI] Remove pylint from checks

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

pylint turned out to not be suitable as a CI check due to its instability between versions and a large amount of questionable findings.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1658)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1658)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1658)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1658)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1658)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1658)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1658#-Nk5uQ4V-FcA2HumgvLq:-Nk5uQ4V-FcA2HumgvLr:b-t3n597) (no related file):*
Can't we agree on a given version of pylint and use it, for example, from docker? In this way we would have a fixed version of pylint across all machines. I think disabling it completely can cause a lot of bugs in Python code, especially since we don't have an extended number of tests of this subsystem.
We just had a bug in python that was noticeable for weeks because pylint was disabled.
I can draft a proposal how to change CI to run it.

In the meantime, I agree we can disable it if it causes to much noise.

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1658)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, @oshogbo, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1658#-Nk5uQ4V-FcA2HumgvLq:-Nk8AyOoBX46moLMqcBG:b-m9f0g4) (no related file):*
> I think disabling it completely can cause a lot of bugs in Python code, especially since we don't have an extended number of tests of this subsystem.  
> We just had a bug in python that was noticeable for weeks because pylint was disabled.

Wasn't that bug the only meaningful finding we ever got from it? The problem I have with pylint is that it is extremely PITA, forcing us to golf the code in weird ways just to fulfill its very subjective rules. Contrary to linters from other languages, it has mostly stylistic warnings (like "too many arguments to a function") which don't take any context into the account.
Just to give some measure how annoying and ineffective it is: we have ~600 lines of Python code and 37 `# pylint: ` comments to manually disable warnings. That's one pylint silencer every 16 lines of code...

> In the meantime, I agree we can disable it if it causes to much noise.

Yup, that's for sure :)

___
___
*[`.ci/run-shellcheck` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/1658#-Nk8AJaEBxdrJPlKtrMw:-Nk8AJaEBxdrJPlKtrMx:bflnxnq) ([raw file](https://github.com/gramineproject/gramine/blob/85d296c26d4a2909d8a62d1ca011044dd3725ff1/.ci/run-shellcheck#L17)):*
> ```
>     scripts/download \
>     scripts/gitignore-test \
>     scripts/run-pylint \
> ```

I'm sorry for pushing again, I just noticed a bug here right before merging - this is a shellcheck list, `run-pylint` should still stay on it.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1658)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1658)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
