### PR TITLE
[tests] Re-enable test for writing to `/dev/stdout`

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 
This was fixed after the pseudo filesystem refactoring so that we can re-enable the test now.

## How to test this PR? 
CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1282)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1282)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1282)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @kailun-qin)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1282#-NSpeVSC0XDQ1a7_8xzH):*
("so that" means "with the purpose of" I think, and it sounds weird here - "with the purpose of reenabling the test now")



_Suggestion:_
```
so we can
```

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1282)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1282)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1282#-NSpeVSC0XDQ1a7_8xzH):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

("so that" means "with the purpose of" I think, and it sounds weird here - "with the purpose of reenabling the test now")
</blockquote></details>

Yep, thanks for updating it!

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1282)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
