### PR TITLE
[CI-Examples] Add SSL cert creation for `make dcap` target

### PR DESCRIPTION
**Pull request by veenasai2**
Signed-off-by: Veena Saini <veena.saini@intel.com>

## Description of the changes 

Sometimes, we have a requirement of creating the dcap server binary along with ssl certificates on a non-sgx system. This change helps user to get the dcap server binary along with certificates using `make dcap` command only. 
## How to test this PR? 
Step 1: `make app dcap ` should work as before 
Step 2: `make distclean`
Step 3: `make dcap` should generate `secret_prov_server_dcap` binary with ssl ceritificates.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/727)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/727)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @veenasai2)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/727#-N6CxYWvDI7_oZd6kcmm):*
This should be ```[CI-Examples] Add SSL cert creation for `make dcap` target```

I can fix it during the final rebase.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/727#-N6CxRhs0z0TH3_j3kZb:-N6CxRhs0z0TH3_j3kZc:b-5f901e) ([raw file](https://github.com/gramineproject/gramine/blob/839ba4eef309350c41005e670562193a5f6d0767/CI-Examples/ra-tls-secret-prov/Makefile#L39)):*
> ```Makefile
> .PHONY: dcap
> dcap: secret_prov_server_dcap
> ```

Why did you remove this empty line? Please keep it, it is useful for separation (otherwise it is hard to read the file)

**Review by veenasai2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/727)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/727#-N6CxYWvDI7_oZd6kcmm):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be ```[CI-Examples] Add SSL cert creation for `make dcap` target```

I can fix it during the final rebase.
</blockquote></details>

ok, thanks
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/727#-N6CxRhs0z0TH3_j3kZb:-N6D-gXNCi5mpq8Ij12l:b-r18wie) ([raw file](https://github.com/gramineproject/gramine/blob/839ba4eef309350c41005e670562193a5f6d0767/CI-Examples/ra-tls-secret-prov/Makefile#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this empty line? Please keep it, it is useful for separation (otherwise it is hard to read the file)
</blockquote></details>

done, thanks.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/727)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/727)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/727)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/727#-N6CxYWvDI7_oZd6kcmm):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

ok, thanks
</blockquote></details>

Shouldn't be `to (...) target`?

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/727)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/727#-N6CxYWvDI7_oZd6kcmm):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't be `to (...) target`?
</blockquote></details>

Done

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/727)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
