### PR TITLE
[LibOS] Fix random bugs found by Klocwork

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Some bugs fixed, mostly checking return values.

## How to test this PR? 

CI should pass.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/127)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/127)* status: 0 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[LibOS/shim/include/shim_checkpoint.h, line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFeMG36kZJJwKDwyfE:-MlFeMG36kZJJwKDwyfF:bwazcay) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/include/shim_checkpoint.h#L194)):*
> ```objc
>             tmp = NEXT_CP_ENTRY();                   \
>         if (!tmp)                                    \
>             DkProcessExit(EINVAL);                   \
> ```

FYI: I'm killing the process instead of returning `NULL` because `GET_CP_ENTRY` may legitimately return 0. Ideally, it should be rewritten like `int get_cp_entry(type, uintptr_t* out_val)`
___
*[LibOS/shim/include/shim_sync.h, line 151 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFeewhBgt4Jwh2bs5d:-MlFeewhBgt4Jwh2bs5e:b-wlq3i2) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/include/shim_sync.h#L151)):*
> ```objc
>     do {                                       \
>         log_error("uthash error: %s", msg);    \
>         DkProcessExit(ENOMEM);                 \
> ```

FYI: This was a small bug that I noticed, unrelated to this PR really.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 317 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFelI42VM0I4_LGBpF:-MlFelI42VM0I4_LGBpG:b-etkkr7) ([raw file](https://github.com/gramineproject/gramine/blob/4355bdc3bf67ef2bc277a200bb8cced55bd536c3/LibOS/shim/src/bookkeep/shim_signal.c#L317)):*
> ```C
>     else
>         log_error("%s at 0x%08lx (IP = 0x%08lx, VMID = %u, TID = %u)", errstr, addr,
>                   context ? ip : 0, g_process_ipc_ids.self_vmid, tid);
> ```

FYI: This finding is funny: Klocwork reported smth like "`context` cannot be NULL, why are you checking it here?"

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-20.04-apps please (GitHub glitched and we couldn't download dependencies)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/127)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_checkpoint.h, line 187 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFfPpu23y7cG_fAYtJ:-MlFfPpu23y7cG_fAYtK:b-w44fqw) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/include/shim_checkpoint.h#L187)):*
> ```objc
>     })
> 
> /* FIXME: this macro must be rewritten as a function with out_val and that returns error code. */
> ```

FWIW: I don't think there is much point in these comments - we need to rewrite the whole checkpointing subsystem, not only these 2 macros.
___
*[LibOS/shim/include/shim_checkpoint.h, line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFeghr7YDhwa6ZQMxw:-MlFeghr7YDhwa6ZQMxx:b-i816kj) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/include/shim_checkpoint.h#L194)):*
> ```objc
>             tmp = NEXT_CP_ENTRY();                   \
>         if (!tmp)                                    \
>             DkProcessExit(EINVAL);                   \
> ```

I think similar macros we have just do `return -EINVAL`, but this is madness, so this version is better I guess. Maybe also add a `log_error()` ?
___
*[LibOS/shim/include/shim_checkpoint.h, line 280 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFfLyE4JNn1Ywf6xRY:-MlFfLyE4JNn1Ywf6xRZ:brsm6oh) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/include/shim_checkpoint.h#L280)):*
> ```objc
>         struct shim_cp_map_entry* e = get_cp_map_entry(store->cp_map, obj, true); \
>         if (!e)                                                                   \
>             DkProcessExit(ENOMEM);                                                \
> ```

ditto (log msg)
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFgJty4Wm5EDVhOLbc:-MlFgJty4Wm5EDVhOLbd:bzborgp) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/src/bookkeep/shim_handle.c#L270)):*
> ```C
> struct shim_handle* get_fd_handle(uint32_t fd, int* fd_flags, struct shim_handle_map* map) {
>     map = map ?: get_thread_handle_map(NULL);
>     if (!map)
> ```

Is this possible? Wouldn't `assert(map);` be enough?
Update: ok I see. We probably should just remove the check for `thread` in `get_thread_handle_map` - it should not be possible for it to be NULL.
___
*[LibOS/shim/src/fs/proc/thread.c, line 237 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFi3Ug1u2nPCIBX-G5:-MlFi3Ug1u2nPCIBX-G6:bdxdkr7) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/src/fs/proc/thread.c#L237)):*
> ```C
> 
>     struct shim_handle_map* handle_map = get_thread_handle_map(NULL);
>     if (!handle_map)
> ```

Can be removed if we apply the change I've described above.
___
*[LibOS/shim/src/fs/proc/thread.c, line 255 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFi6Wc1EVRaUoyUwNc:-MlFi6Wc1EVRaUoyUwNd:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/src/fs/proc/thread.c#L255)):*
> ```C
>     __UNUSED(parent);
>     struct shim_handle_map* handle_map = get_thread_handle_map(NULL);
>     if (!handle_map)
> ```

ditto
___
*[LibOS/shim/src/fs/proc/thread.c, line 300 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFi7QvBMLRUaSYtJlf:-MlFi7QwDhqDQlApi3kI:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/src/fs/proc/thread.c#L300)):*
> ```C
> 
>     struct shim_handle_map* handle_map = get_thread_handle_map(NULL);
>     if (!handle_map)
> ```

ditto

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/127)* status: 2 of 8 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_checkpoint.h, line 187 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFfPpu23y7cG_fAYtJ:-MlFj7QHB2FecE1eiH17:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/include/shim_checkpoint.h#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

FWIW: I don't think there is much point in these comments - we need to rewrite the whole checkpointing subsystem, not only these 2 macros.
</blockquote></details>

Done
___
*[LibOS/shim/include/shim_checkpoint.h, line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFeghr7YDhwa6ZQMxw:-MlFj86l5hep1eFyBCGN:b21omzm) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/include/shim_checkpoint.h#L194)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think similar macros we have just do `return -EINVAL`, but this is madness, so this version is better I guess. Maybe also add a `log_error()` ?
</blockquote></details>

Done. But not sure how to describe this error.
___
*[LibOS/shim/include/shim_checkpoint.h, line 280 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFfLyE4JNn1Ywf6xRY:-MlFjWcF1y-WOL1oqlKU:b21omzm) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/include/shim_checkpoint.h#L280)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (log msg)
</blockquote></details>

Done. But not sure how to describe this error.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFgJty4Wm5EDVhOLbc:-MlFl26v-qzYEKJQctEs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/src/bookkeep/shim_handle.c#L270)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is this possible? Wouldn't `assert(map);` be enough?
Update: ok I see. We probably should just remove the check for `thread` in `get_thread_handle_map` - it should not be possible for it to be NULL.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 237 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFi3Ug1u2nPCIBX-G5:-MlFl3GX4JYKIwP_f75Y:b-e883kl) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/src/fs/proc/thread.c#L237)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can be removed if we apply the change I've described above.
</blockquote></details>

Done. Added asserts everywhere, just in case.
___
*[LibOS/shim/src/fs/proc/thread.c, line 255 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFi6Wc1EVRaUoyUwNc:-MlFl5L66VIBWPfvOGCx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/src/fs/proc/thread.c#L255)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 300 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFi7QvBMLRUaSYtJlf:-MlFl5qn6GaxS8floxFm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/src/fs/proc/thread.c#L300)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/127)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_checkpoint.h, line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/127#-MlFeghr7YDhwa6ZQMxw:-MlFoJJSAKdIqGy4t-i9:b2yakah) ([raw file](https://github.com/gramineproject/gramine/blob/a07e60a6220153354676ed86829c413fb99d3418/LibOS/shim/include/shim_checkpoint.h#L194)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. But not sure how to describe this error.
</blockquote></details>

Whatever, just something we can grep sources for. Looks good ;)

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 2 of 5 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/127)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-20.04 please (GitHub failed)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-20.04-apps please (GitHub failed)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/127)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/127)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
