### PR TITLE
[Pal/Linux-SGX] Correctly set masks in SIGSTRUCT

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, SIGSTRUCT.ATTRIBUTEMASK (which contains the masks for enclave attributes such as DEBUG and for XFRM/XCR0 bits) and SIGSTRUCT.MISCMASK (which contains the mask for Extended SSA frame features) were incorrectly set to mirror SIGSTRUCT.ATTRIBUTES and SIGSTRUCT.MISCSELECT.

This commit replaces this incorrect logic with hard-coded values for SIGSTRUCT.ATTRIBUTEMASK and SIGSTRUCT.MISCMASK. In particular, all bits in the masks are set to one (meaning "EINIT checks each attribute"). The only exceptions currently are not-security-critical AVX and AVX512 bits -- they are not reflected in the mask, and they are set in SIGSTRUCT.ATTRIBUTES if the system supports them during generation of the `.token` file.

Useful links:
- https://github.com/openenclave/openenclave/blob/master/include/openenclave/bits/sgx/sgxtypes.h
- https://www.felixcloutier.com/x86/einit
- https://en.wikipedia.org/wiki/Control_register#XCR0_and_XSS
- "Intel SGX Explained", Sections 5.6.2 and 5.7.4, and also check Figure 77

## How to test this PR? 

All tests must pass. You can manually verify the ATTRIBUTES, MISCSELECT, and their corresponding MASKs in the outputs (e.g., when building and running the Redis example).

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjcX_8j4xqBll7LQfqU:-MjcX_8j4xqBll7LQfqV:b-z8c6ho) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L81)):*
> ```objc
>   */
> #define SGX_FLAGS_MASK_CONST_HI 0xffffffffUL
> #define SGX_FLAGS_MASK_CONST_LO 0xffffffffUL
> ```

FYI: I split these 64-bit masks into two 32-bit values because our Asm parser incorrectly works on 64-bit macros (recall that we use some Makefile and GCC magic to auto-generate `_offsets.py` from C headers)... So I had to do this slightly weird separation.
___
*[python/graphenelibos/sgx_get_token.py, line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjcYF3d7ZIH8xQaxPvB:-MjcYF3d7ZIH8xQaxPvC:b-2h416t) ([raw file](https://github.com/gramineproject/gramine/blob/3c3b522974a974e80f84bac2cd1797e151474146/python/graphenelibos/sgx_get_token.py#L45)):*
> ```Python
>         # changed in xfrm (need to stay the same as signed).
>         if xfrms & (bits & xfrmmask) == (bits & xfrmmask) and feature in cpu_features:
>             new_xfrms |= xfrms | bits
> ```

FYI: Honestly, no idea what this code meant... I think we didn't really understand ATTRIBUTES in Intel SGX at that point.
___
*[python/graphenelibos/sgx_get_token.py, line 144 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjcYRUp639M5GjC4toc:-MjcYRUp639M5GjC4tod:b-jsor27) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/python/graphenelibos/sgx_get_token.py#L144)):*
> ```Python
>     fields['isvsvnle'] = (210, '<H')
>     fields['reserved4'] = (212, '24B')
>     fields['misc_select'] = (236, '<L')
> ```

FYI: This was a bug. It did not manifest itself before because `misc_mask` was always equal to `misc_select` (see my comment on the main bug below).
___
*[python/graphenelibos/sgx_sign.py, line 593 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjcYcrQ1m1yDTRQXAaW:-MjcYcrQ1m1yDTRQXAaX:bkoyok6) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/python/graphenelibos/sgx_sign.py#L593)):*
> ```Python
>         'attribute_mask': (offs.SGX_ARCH_ENCLAVE_CSS_ATTRIBUTE_MASK, '<4L',
>                            offs.SGX_FLAGS_MASK_CONST_LO, offs.SGX_FLAGS_MASK_CONST_HI,
>                            offs.SGX_XFRM_MASK_CONST_LO, offs.SGX_XFRM_MASK_CONST_HI),
> ```

FYI: These are the main bugs. The old code simply copied `misc_select` value into the `misc_mask` value of the generated SIGSTRUCT. Same for `attribute_mask`, which was copied from `flags` + `xfrms` verbatim.

The fix for this main bug is to use hard-coded masks.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjcX_8j4xqBll7LQfqU:-MjdxV2n38Xa7iilTWfm:b8hsnjm) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I split these 64-bit masks into two 32-bit values because our Asm parser incorrectly works on 64-bit macros (recall that we use some Makefile and GCC magic to auto-generate `_offsets.py` from C headers)... So I had to do this slightly weird separation.
</blockquote></details>

Wait, why? It does work correctly with 64 constants.
___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-Mjdxl7DCnz4cnh-WItG:-Mjdxl7DCnz4cnh-WItH:b-hthyyl) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L84)):*
> ```objc
> 
> #define SGX_XFRM_LEGACY   0x03ULL
> #define SGX_XFRM_AVX      0x04ULL
> ```

Why this change? Afaiu bit 1 (value `2`) is SSE, which we do require with AVX.
___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjdyTw-7yofv4804FX4:-MjdyTw-7yofv4804FX5:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L86)):*
> ```objc
> #define SGX_XFRM_AVX      0x04ULL
> #define SGX_XFRM_MPX      0x18ULL
> #define SGX_XFRM_AVX512   0xe4ULL
> ```

ditto

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjcX_8j4xqBll7LQfqU:-Mjhq0NuByoy_6e3UtPo:bhw90md) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L81)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait, why? It does work correctly with 64 constants.
</blockquote></details>

Nope. I added a dummy `DUMMY_64BIT_VALUE` for an example:
```
$ grep -rIw DUMMY_64BIT_VALUE
Pal/src/host/Linux-SGX/sgx_arch.h:#define DUMMY_64BIT_VALUE 0xffffffffffffffffUL
Pal/src/host/Linux-SGX/generated-offsets.s:     .ascii "GENERATED_INTEGER DUMMY_64BIT_VALUE $-1 "
Pal/src/host/Linux-SGX/generated-offsets.c:    DEFINE(DUMMY_64BIT_VALUE, DUMMY_64BIT_VALUE);
```

Notice `-1` value in `generated-offsets.s` file. This is the file that is auto-generated from `generated-offsets.c`.

Some hints on how we end up with `-1`:
- https://github.com/gramineproject/gramine/blob/4321ecf82de15ecf5f091dcaccae5d8ea43758f1/common/include/generated-offsets-build.h#L5 -- this is how `DEFINE` macro is defined: it produces inline asm with the value taken via `i` GCC asm modifier
- https://github.com/gramineproject/gramine/blob/4321ecf82de15ecf5f091dcaccae5d8ea43758f1/Scripts/Makefile.rules#L38 -- this is how we transform `generated-offsets.c` to `generated-offsets.s`
- https://github.com/gramineproject/gramine/blob/4321ecf82de15ecf5f091dcaccae5d8ea43758f1/Scripts/Makefile.rules#L56 -- this is how we produce the used-in-this-PR `_offsets.py`
- https://github.com/gramineproject/gramine/blob/master/Scripts/gen-offsets.py -- this is the script to produce the final `_offsets.py`; the script itself is good but it doesn't even read `-1` garbage value because its regex expects a positive number

I tried to play with different GCC asm modifiers (other than `i`), but didn't succeed. So I decided to fall back to 32-bit values. I'll be happy to fix this if there is a simple way to make our crazy constant-generation scripts do the right thing.
___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-Mjdxl7DCnz4cnh-WItG:-MjhudgMDhmIpGw8YFTm:b-2y60rp) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L84)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this change? Afaiu bit 1 (value `2`) is SSE, which we do require with AVX.
</blockquote></details>

Explanation is a bit tricky.

In this PR, we introduce a hard-coded `SGX_XFRM_MASK_CONST_LO 0xffffff1bUL`. This is equal to `0b11111111111111111111111100011011`. You can notice that we mask bits 2 (AVX) and 5-7 (AVX512). This translates to "I am the enclave signer, and I don't care if this SGX enclave will run on a machine with AVX/AVX512 disabled or enabled".

Also notice that we do *not* mask bits 0 (x87) and 1 (SSE). This translates to "I am the enclave signer, and I force this SGX enclave to run only on a machine that has x87 and SSE enabled". We enforce this because Intel SGX can *not* run on machines that do not support the XSAVE feature (which is kinda "tangentially" decided based on set bits 0 and 1 in XFRM/XCR0).

Also in this PR, we introduce the following logic:
```
if bits & xfrmmask == 0 and feature in cpu_features:
    new_xfrms |= bits
```

This logic is to optionally enable XFRM-masked features present on this CPU. This check says "Does the enclave signer care about the feature bits? If *not*, let's enable these feature bits in the SGX enclave".

So if we would keep `SGX_XFRM_AVX      0x06ULL`, we'll have `0b110`. And because we have bit 1 set here (SSE), our Python logic would fail: not all bits in the XFRM mask are masked (because SSE bit is always unmasked). So we won't be able to enable AVX at all.

Finally, note that keeping bit 1 in `SGX_XFRM_AVX` doesn't make much sense anyway -- Intel SGX doesn't even work if this bit is unset. So having it as a pre-requisite to AVX is redundant -- it is a pre-requisite for SGX already.

(Alternatively, I could remove bit 1 from `SGX_XFRM_MASK_CONST_LO`, but this makes no sense logically -- SSE *must be set* for SGX to work, but our mask would say "enclave signer doesn't care about SSE feature"?!)
___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjdyTw-7yofv4804FX4:-MjhwXveEfrJmlOHxVU9:baook5h) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L86)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Same explanation for AVX512 as above.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjcX_8j4xqBll7LQfqU:-MjiALp70Xl6AYSRHvh0:bpcamut) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nope. I added a dummy `DUMMY_64BIT_VALUE` for an example:
```
$ grep -rIw DUMMY_64BIT_VALUE
Pal/src/host/Linux-SGX/sgx_arch.h:#define DUMMY_64BIT_VALUE 0xffffffffffffffffUL
Pal/src/host/Linux-SGX/generated-offsets.s:     .ascii "GENERATED_INTEGER DUMMY_64BIT_VALUE $-1 "
Pal/src/host/Linux-SGX/generated-offsets.c:    DEFINE(DUMMY_64BIT_VALUE, DUMMY_64BIT_VALUE);
```

Notice `-1` value in `generated-offsets.s` file. This is the file that is auto-generated from `generated-offsets.c`.

Some hints on how we end up with `-1`:
- https://github.com/gramineproject/gramine/blob/4321ecf82de15ecf5f091dcaccae5d8ea43758f1/common/include/generated-offsets-build.h#L5 -- this is how `DEFINE` macro is defined: it produces inline asm with the value taken via `i` GCC asm modifier
- https://github.com/gramineproject/gramine/blob/4321ecf82de15ecf5f091dcaccae5d8ea43758f1/Scripts/Makefile.rules#L38 -- this is how we transform `generated-offsets.c` to `generated-offsets.s`
- https://github.com/gramineproject/gramine/blob/4321ecf82de15ecf5f091dcaccae5d8ea43758f1/Scripts/Makefile.rules#L56 -- this is how we produce the used-in-this-PR `_offsets.py`
- https://github.com/gramineproject/gramine/blob/master/Scripts/gen-offsets.py -- this is the script to produce the final `_offsets.py`; the script itself is good but it doesn't even read `-1` garbage value because its regex expects a positive number

I tried to play with different GCC asm modifiers (other than `i`), but didn't succeed. So I decided to fall back to 32-bit values. I'll be happy to fix this if there is a simple way to make our crazy constant-generation scripts do the right thing.
</blockquote></details>

Oh, I've tried a positive value...
Okey, this is madness, let's leave the current version.
___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-Mjdxl7DCnz4cnh-WItG:-MjiFqJ99ltslALfn-DU:b-zczhwc) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Explanation is a bit tricky.

In this PR, we introduce a hard-coded `SGX_XFRM_MASK_CONST_LO 0xffffff1bUL`. This is equal to `0b11111111111111111111111100011011`. You can notice that we mask bits 2 (AVX) and 5-7 (AVX512). This translates to "I am the enclave signer, and I don't care if this SGX enclave will run on a machine with AVX/AVX512 disabled or enabled".

Also notice that we do *not* mask bits 0 (x87) and 1 (SSE). This translates to "I am the enclave signer, and I force this SGX enclave to run only on a machine that has x87 and SSE enabled". We enforce this because Intel SGX can *not* run on machines that do not support the XSAVE feature (which is kinda "tangentially" decided based on set bits 0 and 1 in XFRM/XCR0).

Also in this PR, we introduce the following logic:
```
if bits & xfrmmask == 0 and feature in cpu_features:
    new_xfrms |= bits
```

This logic is to optionally enable XFRM-masked features present on this CPU. This check says "Does the enclave signer care about the feature bits? If *not*, let's enable these feature bits in the SGX enclave".

So if we would keep `SGX_XFRM_AVX      0x06ULL`, we'll have `0b110`. And because we have bit 1 set here (SSE), our Python logic would fail: not all bits in the XFRM mask are masked (because SSE bit is always unmasked). So we won't be able to enable AVX at all.

Finally, note that keeping bit 1 in `SGX_XFRM_AVX` doesn't make much sense anyway -- Intel SGX doesn't even work if this bit is unset. So having it as a pre-requisite to AVX is redundant -- it is a pre-requisite for SGX already.

(Alternatively, I could remove bit 1 from `SGX_XFRM_MASK_CONST_LO`, but this makes no sense logically -- SSE *must be set* for SGX to work, but our mask would say "enclave signer doesn't care about SSE feature"?!)
</blockquote></details>

All right, then please add a quick comment somewhere around here saying that SSE is always enabled (SGX requirement).

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjcX_8j4xqBll7LQfqU:-MjnWnAw6hEIuvVn_dhj:bzamek7) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L81)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Oh, I've tried a positive value...
Okey, this is madness, let's leave the current version.
</blockquote></details>

Could you say this in a comment? This implementation is quite unexpected.
___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjnY-oc8seOVch2QQ4a:-MjnY-oc8seOVch2QQ4b:b-6kjvh3) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L96)):*
> ```
> enable security-critical 
> ```

I'd drop this, I don't think it's "critical" for security. It's just that if the author of the enclave wanted it, then we should check it.
___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 100 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjnYQAU2bckjWjFsER8:-MjnYQAU2bckjWjFsER9:b-yitveg) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L100)):*
> ```
> Two versions
> ```

`versions` -> `instances` (ditto in other places)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: 3 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-Mjdxl7DCnz4cnh-WItG:-MjioLVg26VZjay0QBXx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L84)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All right, then please add a quick comment somewhere around here saying that SSE is always enabled (SGX requirement).
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjnY-oc8seOVch2QQ4a:-Mjnj2is0FhYwpqYnGLq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L96)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> enable security-critical 
> ```

I'd drop this, I don't think it's "critical" for security. It's just that if the author of the enclave wanted it, then we should check it.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 100 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjnYQAU2bckjWjFsER8:-MjnjEMx-IEVsN-bZ0xR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L100)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Two versions
> ```

`versions` -> `instances` (ditto in other places)
</blockquote></details>

Done.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: 3 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_arch.h, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/44#-MjcX_8j4xqBll7LQfqU:-MjnmEkxAHdYvzoYbGCY:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9b996dcde7979e259d14acf461d65957439f9351/Pal/src/host/Linux-SGX/sgx_arch.h#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you say this in a comment? This implementation is quite unexpected.
</blockquote></details>

Done

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/44)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
