### PR TITLE
Bump Gramine version to 1.1

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

This commit will most likely be our v1.1 release (after checking packages).

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/373)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/373)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/373)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/373#-MuvMgFR732q60DLyUhH:-MuvMgFR732q60DLyUhI:beu4ruv) (no related file):*
Blocking until we validate packages generated from this commit.

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/373)* status: all files reviewed, 1 unresolved discussion

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/373)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/373#-MuvMgFR732q60DLyUhH:-MuzOiKp0tUGXZWq-0Nl:bk7o0pu) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Blocking until we validate packages generated from this commit.
</blockquote></details>

Testing done and it seems that we're ready to go :)

---

**Pull request merged**
