### PR TITLE
Compile SGX tools with meson

### PR DESCRIPTION
**Pull request by woju**
This is https://github.com/gramineproject/graphene/pull/2645

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 63 of 66 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — COMMENTED** [review]
> Reviewed 63 of 66 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

___
*[CI-Examples/ra-tls-mbedtls/client.manifest.template, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk26djvDNix330K-m1_:-Mk26djwAs5UgtiwISdD:b-5odpr7) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/client.manifest.template#L51)):*
> ```
>     "file:/etc/gai.conf",
>     "file:/etc/ssl/certs/ca-certificates.crt",
>     "file:/etc/sgx_default_qcnl.conf",
> ```

Why this change? All other manifests indent at two spaces (probably to save line space for long paths, which IMO makes sense).
___
*[CI-Examples/ra-tls-mbedtls/server.manifest.template, line 46 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk2ArlO1DCo71nV18gV:-Mk2ArlP0-W9kvyfIUnu:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/server.manifest.template#L46)):*
> ```
>     "file:/etc/group",
>     "file:/etc/passwd",
>     "file:/etc/gai.conf",
> ```

ditto
___
*[CI-Examples/ra-tls-secret-prov/secret_prov_client.manifest.template, line 43 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk2Dids0Q3YEUc9bke1:-Mk2Dids0Q3YEUc9bke2:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-secret-prov/secret_prov_client.manifest.template#L43)):*
> ```
>     "file:/etc/passwd",
>     "file:/etc/gai.conf",
>     "file:/etc/resolv.conf",
> ```

ditto
___
*[CI-Examples/ra-tls-secret-prov/secret_prov_min_client.manifest.template, line 47 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk2DmXdEjsorhclgHUj:-Mk2DmXdEjsorhclgHUk:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-secret-prov/secret_prov_min_client.manifest.template#L47)):*
> ```
>     "file:/etc/passwd",
>     "file:/etc/gai.conf",
>     "file:/etc/resolv.conf",
> ```

ditto
___
*[CI-Examples/ra-tls-secret-prov/secret_prov_pf_client.manifest.template, line 52 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk2Dv3H14hxMQU0NBQo:-Mk2Dv3H14hxMQU0NBQp:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-secret-prov/secret_prov_pf_client.manifest.template#L52)):*
> ```
> 
> sgx.protected_files = [
>     "file:files/input.txt",
> ```

ditto

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/client.manifest.template, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk26djvDNix330K-m1_:-Mk2Xw7-2OKayz2Q-SxF:b34du7g) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/client.manifest.template#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why this change? All other manifests indent at two spaces (probably to save line space for long paths, which IMO makes sense).
</blockquote></details>

Because we indent with 4 spaces: https://gramine.readthedocs.io/en/latest/devel/coding-style.html. I don't understand why this wasn't caught in review earlier. Do you want me to fix all the manifests in `CI-Examples/`?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

___
*[CI-Examples/ra-tls-mbedtls/client.manifest.template, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk26djvDNix330K-m1_:-Mk2bLwB6pXgTthkf86o:b-maxre3) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/client.manifest.template#L51)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because we indent with 4 spaces: https://gramine.readthedocs.io/en/latest/devel/coding-style.html. I don't understand why this wasn't caught in review earlier. Do you want me to fix all the manifests in `CI-Examples/`?
</blockquote></details>

Whatever we decide, this is completely unrelated to this PR, so please revert.

Anyways, our coding style covers only C, Meson and reST, and they have different rules (e.g. different line length limits). I think here two spaces are fine - we'll never have any deep nesting (where two-space indentation starts to be unreadable) and file paths are often long, so it's better to have more space for them.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/client.manifest.template, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk26djvDNix330K-m1_:-Mk2cMAcC3VyQwY7bYYQ:b-p146dv) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/client.manifest.template#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Whatever we decide, this is completely unrelated to this PR, so please revert.

Anyways, our coding style covers only C, Meson and reST, and they have different rules (e.g. different line length limits). I think here two spaces are fine - we'll never have any deep nesting (where two-space indentation starts to be unreadable) and file paths are often long, so it's better to have more space for them.
</blockquote></details>

No, we should have a single rule for all the files where this works (i.e. not reST), so we don't have to maintain per-filetype editor config. There's not much difference between 2 and 4 spaces in path length.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

___
*[CI-Examples/ra-tls-mbedtls/client.manifest.template, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk26djvDNix330K-m1_:-Mk2dAg723X-yPkA9xwT:b14y7q8) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/client.manifest.template#L51)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, we should have a single rule for all the files where this works (i.e. not reST), so we don't have to maintain per-filetype editor config. There's not much difference between 2 and 4 spaces in path length.
</blockquote></details>

Whatever, please revert it from this PR, it's unrelated. If you want to change this then it should be a separate PR/issue.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/client.manifest.template, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk26djvDNix330K-m1_:-Mk2g3Lo0xYQDN79RnHf:b-nstciu) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/client.manifest.template#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Whatever, please revert it from this PR, it's unrelated. If you want to change this then it should be a separate PR/issue.
</blockquote></details>

Done. #73

**Review by mkow — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

___
*[CI-Examples/ra-tls-mbedtls/client.manifest.template, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk26djvDNix330K-m1_:-Mk2ggTJBrq_HqouqDzC:bwou6kp) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/client.manifest.template#L51)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done. #73 
</blockquote></details>

But now you based this PR on #73. Please just drop this change from here and point to master, so that we can merge it. A lot of PRs are blocked on this one and there's no reason to wait for merging #73, as it's unrelated (and not obvious that it will be merged, the style in TOML is something we need to discuss there).

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: 69 of 74 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/client.manifest.template, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk26djvDNix330K-m1_:-Mk2iij_-L6Q8aEhCtuY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/client.manifest.template#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But now you based this PR on #73. Please just drop this change from here and point to master, so that we can merge it. A lot of PRs are blocked on this one and there's no reason to wait for merging #73, as it's unrelated (and not obvious that it will be merged, the style in TOML is something we need to discuss there).
</blockquote></details>

Done.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: 69 of 74 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/client.manifest.template, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk26djvDNix330K-m1_:-Mk2jUWq0wedz6_UPjU8:b5x3g37) ([raw file](https://github.com/gramineproject/gramine/blob/a324c28fa746c43dc77037dd7746e1089194bbac/CI-Examples/ra-tls-mbedtls/client.manifest.template#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But the PR is still based on `woju/qe`, not master?
</blockquote></details>

Now should be OK.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/64#-Mk2mBjd8soTCkq_VRd9:-Mk2mBjeB2es66lrJQ4J:bu2skkv) (no related file):*
The first commit doesn't build. Please either squash the fix to it (currently the last commit) or change their order so that each commit works correctly.

---

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

**Review by dimakuv — APPROVED** [review]
> Reviewed 8 of 21 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boryspoplawski)

**Pull request merged**
