### PR TITLE
[PAL] Rename files

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Rename rules:
- `db_` -> `pal_`
- `sgx_` -> `host_` (but with several exceptions)
- `-` -> `_` (only for files, not for directories)

See https://github.com/gramineproject/gramine/discussions/667 and https://github.com/gramineproject/gramine/discussions/687 for details.

## How to test this PR? 

CI is enough.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/690)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/690)* status: 101 of 103 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/690#-N5f2HAZBYCp8kuQCASi:-N5fI6Q_CRSZoR47mEF7:b25xwdd) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> sgx_ -> host_ (but with several exceptions)

What are these exceptions and why? I see for example `sgx_arch.h`
</blockquote></details>

See my other comment.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5fIks2Ajm8FOz65Md6):*
Change during final rebase to smth like this:
```
[PAL] Rename files to have `pal_`, `enclave_` and `host_` prefixes

Rename rules: ...

Additionally, this commit changes `-` in PAL C/header filenames to
`_`, for consistency with the rest of the codebase.
```
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5fHjqA9rHuVv8x21Gh):*
Rephrase to this during final rebase:
```
  - `sgx_` -> `host_` (with the exceptions of `sgx_arch.h` and
    `sgx_attest.h` which pertain to the SGX HW arch)
```
___
*[`pal/src/meson.build` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5f1ilBAnrkDd8tgm1x:-N5fIDEC6tptJsXu360_:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/662ca2d919f98e9d44ee6d2d242c45716e2fe21f/pal/src/meson.build#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please sort this list
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/db_misc.c` line 612 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5f4R9K5DKk5oqfRB0D:-N5fIZTl6GaKlzOdYXvN:bhvmbga) ([raw file](https://github.com/gramineproject/gramine/blob/ecca6b5567981626f5874a99594634754b691823/pal/src/host/linux-sgx/db_misc.c#L612)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`-` in name.
Update: actually, this comment is probably just outdated.
</blockquote></details>

Done. Just deleted this line.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/690)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5fHjqA9rHuVv8x21Gh):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Rephrase to this during final rebase:
```
  - `sgx_` -> `host_` (with the exceptions of `sgx_arch.h` and
    `sgx_attest.h` which pertain to the SGX HW arch)
```
</blockquote></details>

But why not have everything uniformly named?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/690)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5fHjqA9rHuVv8x21Gh):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But why not have everything uniformly named?
</blockquote></details>

Well, that's what @mkow suggested during the meeting. That `sgx_arch.h` and `sgx_attest.h` -- files that are truly "SGX hardware" specific -- keep their names.

I can rename to `pal_sgx_arch.h` and `pal_sgx_attest.h` (because they are used by both trusted and untrusted worlds), if both you and @mkow approve such rename.

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/690)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5fHjqA9rHuVv8x21Gh):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, that's what @mkow suggested during the meeting. That `sgx_arch.h` and `sgx_attest.h` -- files that are truly "SGX hardware" specific -- keep their names.

I can rename to `pal_sgx_arch.h` and `pal_sgx_attest.h` (because they are used by both trusted and untrusted worlds), if both you and @mkow approve such rename.
</blockquote></details>

`pal_sgx_*` makes no sense to me. I don't see much point in having them as `sgx` instead of `enclave` (I would say it's fine that they are used in both "worlds"). Or even give them custom names (e.g. `attestation.h`).
Anyway, unblocking if it was already discussed and I just missed it

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/690)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5fHjqA9rHuVv8x21Gh):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`pal_sgx_*` makes no sense to me. I don't see much point in having them as `sgx` instead of `enclave` (I would say it's fine that they are used in both "worlds"). Or even give them custom names (e.g. `attestation.h`).
Anyway, unblocking if it was already discussed and I just missed it
</blockquote></details>

I'd leave that `sgx_` prefix as these headers are usually just a bunch of SGX hardware constants. Although it's not a super strong preference.

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/690)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/690)* status: 101 of 103 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5fIks2Ajm8FOz65Md6):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Change during final rebase to smth like this:
```
[PAL] Rename files to have `pal_`, `enclave_` and `host_` prefixes

Rename rules: ...

Additionally, this commit changes `-` in PAL C/header filenames to
`_`, for consistency with the rest of the codebase.
```
</blockquote></details>

Done
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/690#-N5fHjqA9rHuVv8x21Gh):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd leave that `sgx_` prefix as these headers are usually just a bunch of SGX hardware constants. Although it's not a super strong preference.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 99 of 103 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/690)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
