### PR TITLE
[LibOS] Remove dead code from `libos_handle.h`

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Noticed these completely unused declarations. Removed them.

## How to test this PR? 

CI is enough.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1204)

### CODE REVIEW

**Review by woju — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1204)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1204)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1204)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1204)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
