### PR TITLE
[LibOS] Fail if address in `arch_prctl()` is inaccessible

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The check was missing. Reported by Scott Constable.

## How to test this PR? 

N/A. Trivial.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1543)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1543)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1543)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1543)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1543)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
