### PR TITLE
[Docs] Improve "Quick Start" and "Cloud Deployment" pages

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Two commits in this PR:

- [Docs] Improve "Run sample application" section of Quick Start

- [Docs] Rewrite "Cloud Deployment" to use Gramine install. The previous version of this document described how to build Gramine from the GitHub repo, which is not user-friendly. Now this document is similar to the Quick Start Guide.

## How to test this PR? 

N/A.

I rented a couple MS Azure CC VMs (one with Ubuntu 18.04, another with Ubuntu 20.04) and installed Gramine in a bare minimum of steps. This documentation follows my experiments.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/594)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/594)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/cloud-deployment.rst` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/594#-N2R-XHA59dUVWi1yHER:-N2R-XHA59dUVWi1yHES:bo7r72a) ([raw file](https://github.com/gramineproject/gramine/blob/d71990db878026bd037b265fe934e6ddc0ae8211/Documentation/cloud-deployment.rst#L37)):*
> ```reStructuredText
> On Ubuntu 20.04::
> 
>    sudo curl -fsSLo /usr/share/keyrings/gramine-keyring.gpg https://packages.gramineproject.io/gramine-keyring.gpg
> ```

Don't we want to join the common steps into one paragraph? Only Gramine package version/name differs, which is in last step
___
*[`Documentation/quickstart.rst` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/594#-N2R1cd_5dZk1inznZPE:-N2R1cd_5dZk1inznZPF:b-id13vg) ([raw file](https://github.com/gramineproject/gramine/blob/d71990db878026bd037b265fe934e6ddc0ae8211/Documentation/quickstart.rst#L70)):*
> ```reStructuredText
>    sudo dnf install gcc make      # for RHEL-8-like distribution
> 
> Change to the HelloWorld example directory::
> ```

This reads weirdly (change what?), maybe `Change` -> `Move` or `Go`? Idk

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/594)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`Documentation/cloud-deployment.rst` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/594#-N2R-XHA59dUVWi1yHER:-N2R2yFs8b3d9LBBfyp2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d71990db878026bd037b265fe934e6ddc0ae8211/Documentation/cloud-deployment.rst#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we want to join the common steps into one paragraph? Only Gramine package version/name differs, which is in last step
</blockquote></details>

Done.
___
*[`Documentation/quickstart.rst` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/594#-N2R1cd_5dZk1inznZPE:-N2R2M1-E30Gfqb5020P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d71990db878026bd037b265fe934e6ddc0ae8211/Documentation/quickstart.rst#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This reads weirdly (change what?), maybe `Change` -> `Move` or `Go`? Idk
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/594)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/594)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/594)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/594)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/594)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
