### PR TITLE
[LibOS] Add interrupt handling around `DkStreamWaitForClient`

### LINKED ISSUE #376: [Linux-SGX] Intermittent LTP test failures seen with create_pollable_event: DkStreamOpen failed: -13 error
## Description of the problem

For setrlimit01 and sendfile04, sendfile04_64 we are seeing intermittent failures when run with Gramine SGX. 

**Sendfile**
```
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)
  - fs.experimental__enable_sysfs_topology = true (forwarding sysfs topology from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------
sendfile04_64    1  TPASS  :  sendfile() returned 14 : Bad address
sendfile04_64    2  TBROK  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_centos_5.14/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/sendfile/sendfile04.c:233: client/server fork failed: Cannot allocate memory
[P1:T1:sendfile04_64] error: create_pollable_event: DkStreamOpen failed: -13
sendfile04_64    3  TBROK  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_centos_5.14/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/sendfile/sendfile04.c:233: Remaining cases broken
```
For sendfile it throws `cannot allocate memory` error even though the system has sufficient free memory and because of the intermittent nature of the issue, the immediate run tends to PASS.

**Setrlimit**

```
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)
  - fs.experimental__enable_sysfs_topology = true (forwarding sysfs topology from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

setrlimit01    1  TPASS  :  RLIMIT_NOFILE functionality is correct
setrlimit01    2  TFAIL  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_dcap/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/setrlimit/setrlimit01.c:185: setrlimit failed, expected 10 got 26
setrlimit01    0  TWARN  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_dcap/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/setrlimit/setrlimit01.c:226: Expected EAGAIN got 12
setrlimit01    0  TWARN  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_dcap/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/setrlimit/setrlimit01.c:226: Expected EAGAIN got 12
[P1:T1:setrlimit01] error: create_pollable_event: DkStreamOpen failed: -13
[P1:T1:setrlimit01] error: create_pollable_event: DkStreamOpen failed: -13
[P1:T1:setrlimit01] error: create_pollable_event: DkStreamWaitForClient failed: -13
```

For setrlimit the test hangs and is eventually killed by a timeout. 

Trace logs from different systems and runs are attached here.
[sendfile04_20.04_5.12_sgx.txt](https://github.com/gramineproject/gramine/files/7992258/sendfile04_20.04_5.12_sgx.txt)
[setrlimit.txt](https://github.com/gramineproject/gramine/files/7992259/setrlimit.txt)
[sendfile04_64_fail_log.txt](https://github.com/gramineproject/gramine/files/7992260/sendfile04_64_fail_log.txt)
[sendfile04_64_intermittent_fail_log.txt](https://github.com/gramineproject/gramine/files/7992261/sendfile04_64_intermittent_fail_log.txt)
[setrlimit_timeout_log.txt](https://github.com/gramineproject/gramine/files/7992263/setrlimit_timeout_log.txt)

## Steps to reproduce

`gramine-sgx sendfile04_64` --> the issue is more reproducible with this test.
`gramine-sgx setrlimit01`

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 

It also missed PAL to UNIX errno translations.

Fixes #376

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/381)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/381)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/381)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-20.04 please (`fdatasync01` and `fcntl14_64` from LTP timed out)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/381)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/381)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/381)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
