### PR TITLE
Update Github issues template to require Gramine commit hash

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Although we had a note in the comment, nobody really gave the hash.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/380)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/380)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[.github/ISSUE_TEMPLATE.md, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/380#-Mv00PXB9mqpYDusxjP2:-Mv00PXB9mqpYDusxjP3:bhvpfsp) ([raw file](https://github.com/gramineproject/gramine/blob/af99dc570f5d6930708fb09d9787324a0546b70c/.github/ISSUE_TEMPLATE.md#L15)):*
> ```Markdown
>

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/380)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[.github/ISSUE_TEMPLATE.md, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/380#-Mv0rDJK3U7GMcztELZD:-Mv0rDJLC2XHFJyjBLEJ:bl3aqom) ([raw file](https://github.com/gramineproject/gramine/blob/af99dc570f5d6930708fb09d9787324a0546b70c/.github/ISSUE_TEMPLATE.md#L28)):*
> ```Markdown
> ## Gramine commit hash
> 
> 
> ```

I bet people will just leave this empty :)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/380)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[.github/ISSUE_TEMPLATE.md, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/380#-Mv0rDJK3U7GMcztELZD:-Mv1434g9YEEu9Erj08F:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/af99dc570f5d6930708fb09d9787324a0546b70c/.github/ISSUE_TEMPLATE.md#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`uesd` -> `used`
</blockquote></details>

Done.
___
*[.github/ISSUE_TEMPLATE.md, line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/380#-Mv0rJ78EgIaHMyZiCbx:-Mv143L81pWvrEgC2dRB:bz8lhus) ([raw file](https://github.com/gramineproject/gramine/blob/af99dc570f5d6930708fb09d9787324a0546b70c/.github/ISSUE_TEMPLATE.md#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I bet people will just leave this empty :)
</blockquote></details>

Most likely, but it least the cannot pretend they didnt see it

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/380)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/380)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/380)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/380)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
