### PR TITLE
Fix broken indentation in LICENSE.txt

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

As in the title. This PR just replaces the license with the original, downloaded from https://www.gnu.org/licenses/lgpl-3.0.txt.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1307)

### CODE REVIEW

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1307)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1307)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by oshogbo — COMMENTED** [review]
Looks pretty straight forward.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1307#-:-NTwc1Br4DoDXU7dGrRt:btg6rec)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1307)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
