### PR TITLE
Add testcase for protected file

### PR DESCRIPTION
**Pull request by anjalirai-intel**
Writing to already existing protected file fails
https://github.com/gramineproject/gramine/issues/641

Signed-off-by: Anjali Rai <anjali.rai@intel.com>

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/648)

### CODE REVIEW

**Review by oshogbo — COMMENTED** [review]
There are a lot of style issues, maybe try to run `clang-format`?
https://gramine.readthedocs.io/en/latest/devel/coding-style.html

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/648#-:-N4S04Ma06tto3z6H1Xe:b9hxtfn)* status: 0 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/648)* status: 0 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

___
*[`LibOS/shim/test/fs/protect_file.c` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/648#-N4SNb5TCNV_mIlLQqJg:-N4SNb5TCNV_mIlLQqJh:b6a6j3y) ([raw file](https://github.com/gramineproject/gramine/blob/807af3ba14c956db79c1b5635ffb9df7d727d8d5/LibOS/shim/test/fs/protect_file.c#L30)):*
> ```C
>     char buffer[MAX_BUF_SIZE];
> 
>     memset(buffer,sizeof(buffer),'0');
> ```

I was wrong, you are not setting the buffer with '0', you have arguments in wrong order.



_Code quote:_
```C
    memset(buffer,sizeof(buffer),'0');
```

**Comment by anjalirai-intel** [comment]
@oshogbo I have updated the PR with the changes

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/648)* status: 0 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/648#-N5AIssg3nKQ0qN8EWsq:-N5AIssg3nKQ0qN8EWsr:b-t5yi3w) (no related file):*
@anjalirai-intel, @oshogbo: I think this PR is a subset of what https://github.com/gramineproject/gramine/pull/651 does, can we close it then?

___

**Comment by anjalirai-intel** [comment]
@mkow If you feel this is subset of #651 you can close this PR

**Comment by oshogbo** [comment]
Yes, I think we can close this for now.
@dimakuv suggested that we might want this.
But from my point of view is very similar to the `truncate` one.

**Comment by dimakuv** [comment]
Yes, we actually test the same in #651. Closing.

**Pull request closed without merging**
