### PR TITLE
[PAL/Linux-SGX] Print message on EACCES during SGX driver open

### LINKED ISSUE #1140: Gramine doesn't report EACCESS error when /dev/sgx_enclave does not have execute permissions
### Description of the problem

On a system where you have `/dev/sgx_enclave` and `/dev/sgx_provision` devices but without execute permissions, then gramine-sgx fails with `load_enclave() failed with error: No such file or directory (ENOENT)` error, it seems to go ahead to the next possible path for sgx device which is `/dev/sgx/enclave` and reports an ENOENT error for that.

This seems incorrect and ideally it should report `EACCESS` error. After changing the permissions to execute gramine-sgx works file.

Please find attached the strace for when execute permissions are not present, and after execute permissions are given to sgx devices.

Error snippet from strace :
```
open("/dev/sgx_enclave", O_RDWR|O_CLOEXEC) = -1 EACCES (Permission denied)
open("/dev/sgx/enclave", O_RDWR|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "error: Cannot open SGX driver de"..., 142error: Cannot open SGX driver device. Please make sure you're using an up-to-date kernel or the standalone Intel SGX kernel module is loaded.
) = 142
write(2, "error: load_enclave() failed wit"..., 76error: load_enclave() failed with error: No such file or directory (ENOENT)
) = 76
```

### Steps to reproduce

```
[graminevalrhel9@graminevalrhel9 helloworld]$ ls -al /dev/ | grep sgx
crw-rw----.  1 root sgx      10, 125 Jan 23 08:27 sgx_enclave
crw-------.  1 root root     10, 126 Jan 23 08:27 sgx_provision
```

```
gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Cannot open SGX driver device. Please make sure you're using an up-to-date kernel
error: load_enclave() failed with error: No such file or directory (ENOENT)
```

```
sudo chmod 777 /dev/sgx_*
ls -al /dev/ | grep sgx
crwxrwxrwx.  1 root sgx      10, 125 Jan 23 08:27 sgx_enclave
crwxrwxrwx.  1 root root     10, 126 Jan 23 08:27 sgx_provision
```

```
gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Hello, world
```

### Expected results

```
gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Hello, world
```

### Actual results

_No response_

### Gramine commit hash

ff9ec79ab27fb4f95daa35656d1410c695264509

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Fixes #1140 

## How to test this PR? 

Test manually.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1141)

### CODE REVIEW

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1141)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by oshogbo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1141#-:-NMd0JL2DpUvfPEC2LGs:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1141)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/1141#-NMd0S5p0eptD9qK85ax:-NMd0S5q4kP65MRjxFp_:b-8by8gb) ([raw file](https://github.com/gramineproject/gramine/blob/90e247bf1c154695cec26c76faa0364701729edd/pal/src/host/linux-sgx/host_framework.c#L35)):*
> ```C
>         ret = DO_SYSCALL(open, paths_to_try[i], O_RDWR | O_CLOEXEC, 0);
>         if (ret == -EACCES) {
>             log_error("Cannot open %s (permission denied). This may happen because this device "
> ```

I'm not sure about the wording here:
Doesn't the user has insufficient permissions to the device/driver?

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1141)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1141#-NMdLPu66qr-zJ09J5Ug):*




_Suggestion:_
```
when opening SGX driver
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1141)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1141#-NMdLPu66qr-zJ09J5Ug):*
Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1141)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1141)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest pkg-rpm-almalinux9 please (`Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.almalinux.org/mirrorlist/9/appstream`)

**Pull request merged**
