### PR TITLE
[Pal,LibOS] Disable sysfs topology by default

### PR DESCRIPTION
**Pull request by vijaydhanraj**
## Description of the changes 
This commit disables sysfs feature by default but exposes a new manifest option `fs.experimental__enable_sysfs_topology`
to turn on the feature for experimental purposes.

As a part of this commit, sysfs regression test is also disabled.

Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>

## How to test this PR? 
Although sysfs regression test is disabled, one can add the `fs.experimental__enable_sysfs_topology` manifest option and run the `sysfs_common` test manually.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/135)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/135)* status: 2 of 7 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNB_PE3o4SPOhJTiNg:-MlNB_PE3o4SPOhJTiNh:b-cd05lr) (no related file):*
Please add a custom `sysfs_common.manifest.template` to `LibOS/regression`, enable `experimental__enable_sysfs_topology` there and unskip `sysfs_common` test.

---
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNCrAE46r9zUMWiUBX):*
What are `experimental purposes`?
Maybe just reword to ```... `fs.experimental__enable_sysfs_topology` which enables the feature.``` or just `testing purposes`?
___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNCJAdAN2DcyddElIP):*
This can be removed, doesn't seem to be so important to put it into commit message (also hopefully that test won't be disabled).
Let's do that at rebase.
___
*[Documentation/manifest-syntax.rst, line 366 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNDu0LCGVSIPQ-eGC8:-MlNDu0LCGVSIPQ-eGC9:beslsyq) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Documentation/manifest-syntax.rst#L366)):*
> ```reStructuredText
> 
> This syntax toggles sysfs feature in Gramine. Note: The feature is still under development
> and can expose security issues when used in production environment.
> ```

I would add something that this will change in the near future (and the feature will be production ready).
___
*[LibOS/shim/src/shim_init.c, line 413 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNExGQ4mE2m7HMq7vT:-MlNExGQ4mE2m7HMq7vU:bhjeo68) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/LibOS/shim/src/shim_init.c#L413)):*
> ```C
> 
>     //TODO: Remove this manifest option once sysfs is more stable.
>     int ret = toml_bool_in(g_manifest_root, "fs.experimental__enable_sysfs_topology",
> ```

Why here? Please move this to `init_fs` and move the `g_enable...` flag to that file (make it global but static for that file).
___
*[LibOS/shim/src/fs/shim_fs.c, line 156 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNEIFX3fAqR5tVH_bo:-MlNEIFX3fAqR5tVH_bp:bo3jnqt) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/LibOS/shim/src/fs/shim_fs.c#L156)):*
> ```C
>     }
> 
>     log_debug("Mounting special sys filesystem: /sys");
> ```

This print should be inside `if (g_enable_sysfs_topology)`. Maybe just split the check from the if below?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 375 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNHl97-2TTnMxee_3m:-MlNHl97-2TTnMxee_3n:bq3zmhq) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Pal/src/host/Linux-SGX/db_main.c#L375)):*
> ```C
>         return -1;
>     }
>     g_pal_sec.online_logical_cores = online_logical_cores;
> ```

Why this is initialized? Why don't we skip this whole function if sysfs is not enabled?
Won't the rest of the code see `g_pal_sec.online_logical_cores` and use this number to access that many entries from `g_pal_sec.topo_info.online_logical_cores`?
Btw, why these 2 variables have the same name, yet one is a number and the other an array?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 737 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNJZso9W90m23tlL-K:-MlNJZso9W90m23tlL-L:bcire8g) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Pal/src/host/Linux-SGX/sgx_main.c#L737)):*
> ```C
> 
>     //TODO: Remove this manifest option once sysfs is more stable.
>     ret = toml_bool_in(manifest_root, "fs.experimental__enable_sysfs_topology",
> ```

Is it worth the effort? Untrusted part can initialize it even if it's disabled, that shouldn't be a problem and hopefully this is not performance heavy thing?

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/135)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @vijaydhanraj)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNCEYV2GFbe4NeyUk2):*
`sysfs` -> `sysfs topology` (on Linux sysfs contains much more than just CPU topology)
ditto for the whole PR
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNBfzN4l-ODn4LRcKm):*
Please also state the reason for disabling it and that it will be back after we properly sanitize and test it.
___
*[Documentation/manifest-syntax.rst, line 357 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNCn9GCktKvf99kng9:-MlNCn9GCktKvf99kngA:bd6bqlj) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Documentation/manifest-syntax.rst#L357)):*
> ```
> Sysfs experimental flag
> ```

Now this means that the flag is experimental ;) Should rather be "Experimental sysfs topology support"
___
*[Documentation/manifest-syntax.rst, line 358 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNCNs80SXVXj6OL5Q9:-MlNCNs80SXVXj6OL5QA:bdvkjb0) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Documentation/manifest-syntax.rst#L358)):*
> ```reStructuredText
> 
> Sysfs experimental flag
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

This has wrong length
___
*[Documentation/manifest-syntax.rst, line 365 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlND6Ed2iMXnu1Wx8QQ:-MlND6Ed2iMXnu1Wx8QR:b-avwzc5) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Documentation/manifest-syntax.rst#L365)):*
> ```reStructuredText
>     (Default: false)
> 
> This syntax toggles sysfs feature in Gramine. Note: The feature is still under development
> ```

`sysfs` -> `sysfs topology`
___
*[Documentation/manifest-syntax.rst, line 366 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNDBiLDiU9fieC1gt8:-MlNDBiLDiU9fieC1gt9:bfbni7e) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Documentation/manifest-syntax.rst#L366)):*
> ```
> can expose security issues when used in production environment
> ```

It can also expose them outside production :P I'd just drop the last part. Proposed rewrite of the whole sentence: "Note: The feature is still under development and may contain security vulnerabilities".
___
*[LibOS/shim/src/shim_init.c, line 394 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNGI7U6NQ8FCCVmeLg:-MlNGI7U6NQ8FCCVmeLh:b-pbiob6) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/LibOS/shim/src/shim_init.c#L394)):*
> ```C
> 
>     g_manifest_root = g_pal_control->manifest_root;
>     assert(g_manifest_root);
> ```

I wouldn't add this assert, `manifest_root` can't be NULL here and if it was then everything would explode right away. I.e. this assert doesn't give us anything useful, just takes space IMO.
___
*[LibOS/shim/src/shim_init.c, line 412 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNEP-7-qff64TZ_tDs:-MlNEP-9BykH2PJ4zrwc:b-avwzc5) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/LibOS/shim/src/shim_init.c#L412)):*
> ```C
>     RUN_INIT(init_rlimit);
> 
>     //TODO: Remove this manifest option once sysfs is more stable.
> ```

`sysfs` -> `sysfs topology`
___
*[LibOS/shim/src/shim_init.c, line 414 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNGvAV-V8korrgDoNq:-MlNGvAV-V8korrgDoNr:b73b3ex) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/LibOS/shim/src/shim_init.c#L414)):*
> ```C
>     //TODO: Remove this manifest option once sysfs is more stable.
>     int ret = toml_bool_in(g_manifest_root, "fs.experimental__enable_sysfs_topology",
>                            /*defaultval=*/false, &g_enable_sysfs_topology);
> ```

This looks more like something which belongs to `init_fs()`. Any reason for placing it here?
___
*[LibOS/shim/test/regression/test_libos.py, line 860 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNFrB_2-D4iiDrbClp:-MlNFrB_2-D4iiDrbClq:b3bdfh0) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/LibOS/shim/test/regression/test_libos.py#L860)):*
> ```Python
>         return n
> 
>     @unittest.skip('skip sysfs tests until the feature is fully stable')
> ```

`skip sysfs tests until the feature is fully stable` -> `this feature is not stable yet`

(we already see that this is a "skip", please be more concise :) )
___
*[LibOS/shim/test/regression/test_libos.py, line 861 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNG67SB3iB1igcv7Qq:-MlNG67SB3iB1igcv7Qr:bwvxf0f) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/LibOS/shim/test/regression/test_libos.py#L861)):*
> ```Python
> 
>     @unittest.skip('skip sysfs tests until the feature is fully stable')
>     def test_040_sysfs(self):
> ```

Actually, why not enable sysfs topology for this single test in its manifest? We wouldn't need to disable it.
___
*[Pal/src/db_main.c, line 569 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNEqvLA8x7G2bgsBSc:-MlNEqvLA8x7G2bgsBSd:b-avwzc5) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Pal/src/db_main.c#L569)):*
> ```C
>     g_pal_control.mem_info.mem_total = _DkMemoryQuota();
> 
>     //TODO: Remove this manifest option once sysfs is more stable.
> ```

`sysfs` -> `sysfs topology`
___
*[Pal/src/db_main.c, line 570 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNFAaWDNoOAoVBt9l0:-MlNFAaWDNoOAoVBt9l1:b-3m1e39) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Pal/src/db_main.c#L570)):*
> ```C
> 
>     //TODO: Remove this manifest option once sysfs is more stable.
>     bool enable_sysfs_topology;
> ```

Could we save this in `g_pal_control`? This way you wouldn't need to parse it again in LibOS.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 375 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNHl97-2TTnMxee_3m:-MlNK_DG0QlxGE3NvlX4:bqt08db) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Pal/src/host/Linux-SGX/db_main.c#L375)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is initialized? Why don't we skip this whole function if sysfs is not enabled?
Won't the rest of the code see `g_pal_sec.online_logical_cores` and use this number to access that many entries from `g_pal_sec.topo_info.online_logical_cores`?
Btw, why these 2 variables have the same name, yet one is a number and the other an array?
</blockquote></details>

Seems that procfs uses `online_logical_cores` for `/proc/cpuinfo`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 396 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNLEOCDraivQuCEgRd:-MlNLEOCDraivQuCEgRe:bdr1wyu) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Pal/src/host/Linux-SGX/db_main.c#L396)):*
> ```C
>     g_pal_sec.possible_logical_cores = possible_logical_cores;
> 
>     /* If sysfs_topology is disabled, skip sanitizing topology information. */
> ```

`sysfs_topology` -> `sysfs topology`
ditto for the whole PR
___
*[Pal/src/host/Linux-SGX/db_main.c, line 416 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNMOBRAjkexD5ju-6_:-MlNMOBRAjkexD5ju-6a:bcs6m81) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Pal/src/host/Linux-SGX/db_main.c#L416)):*
> ```C
> 
>     /* Sanitize logical core -> socket mappings */
>     ret = sanitize_socket_info(sec_info->cpu_socket, online_logical_cores);
> ```

Waaait, isn't this "sanitization" running on non-enclave memory? Same below, this whole function seems to be broken...
So, +1 to Borys question, can we just disable it as a whole? It looks completely insecure.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 965 at r1](https://reviewable.io/reviews/gramineproject/gramine/135#-MlNFQ5l2iKp_8e4qsTZ:-MlNFQ5l2iKp_8e4qsT_:b4noas0) ([raw file](https://github.com/gramineproject/gramine/blob/0f5afc13a5ed5b041d2e47f0eef0fa8e716e382f/Pal/src/host/Linux-SGX/sgx_main.c#L965)):*
> ```C
>     pal_sec->cpu_socket = cpu_socket;
> 
>     if (g_enable_sysfs_topology) {
> ```

We don't need this switch here (and additional manifest parsing), we are in the untrusted part.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — COMMENTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/135)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/135)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/135#-MlPBrslAqxNbA3iCl9q:-MlPeHxW8SPsqlWhbexk:byh17mw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I wouldn't call it "insecure" (well, it has the prefix "experimental"), but Ok.
</blockquote></details>

After I noticed this sanitization on untrusted memory I lost my confidence with that code ;) We'll need to check all of this really carefully.

---

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/135)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 364 at r4](https://reviewable.io/reviews/gramineproject/gramine/135#-MlPiAz1EV9r-luvy8kQ:-MlPpICs5zKhMGg6dBpD:bopqipk) ([raw file](https://github.com/gramineproject/gramine/blob/d91b68d91a8c888fbc9033a2a3344cc29af5252f/Pal/src/host/Linux-SGX/db_main.c#L364)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I wonder, what's the point of these checks if we also check whether it's in range `[1; N]`?
</blockquote></details>

This was in the old code, and Vijay actually changes everything to `uint64_t` (as it should be) in his new PRs, so let's just keep it as is.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 597 at r4](https://reviewable.io/reviews/gramineproject/gramine/135#-MlPkNMCEG0Y93mRnyUv:-MlPppUE0MfwWQWD4i9g:bfczoog) ([raw file](https://github.com/gramineproject/gramine/blob/d91b68d91a8c888fbc9033a2a3344cc29af5252f/Pal/src/host/Linux-SGX/db_main.c#L597)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we deem this as a "insecure configuration"? Shouldn't enabling this alone trigger the warning?
</blockquote></details>

Done, oops.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 843 at r4](https://reviewable.io/reviews/gramineproject/gramine/135#-MlPka5Q-EjC27Mh4ccw:-MlPqN3L8hJEQB7Nc1Wq:b5oxkgn) ([raw file](https://github.com/gramineproject/gramine/blob/d91b68d91a8c888fbc9033a2a3344cc29af5252f/Pal/src/host/Linux-SGX/db_main.c#L843)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`/*is_exitgroup=*/`
</blockquote></details>

Done. Here and in other places.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/135)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/135)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`test-direct / apps.LTP.sendfile09_64` timed out, unrelated)

**Pull request merged**
