### PR TITLE
[docker] Add support for Ubuntu Noble

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Add support for Ubuntu Noble.

## How to test this PR? 

Build image.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`packaging/docker/build.sh` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2045#-OAHflV6EvQxsoNdak32:-OAHflV6EvQxsoNdak33:b-5jwro7) ([raw file](https://github.com/gramineproject/gramine/blob/06ae6eecaa6f21bff0325e1a1fb8109ed4e5fd19/packaging/docker/build.sh#L4)):*
> ```Shell
> 
> usage() {
>     echo "Usage: build.sh [ubuntu20,ubuntu22]"
> ```

This probably needs to be adjusted as well.



_Suggestion:_
```Shell
[ubuntu20,ubuntu22,ubuntu24]
```

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

___
*[`packaging/docker/build.sh` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2045#-OAHflV6EvQxsoNdak32:-OAXMtDzAGePIGpBMCdd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/06ae6eecaa6f21bff0325e1a1fb8109ed4e5fd19/packaging/docker/build.sh#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This probably needs to be adjusted as well.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2045)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
