### PR TITLE
[Documentation] Fix a typo in the building section

### LINKED ISSUE #151: Building section in readme docs has a typo for specifying sgx_driver_path (-Dsgx_driver_path instead of -Dsgx_driver_include_path)
## Description of the problem
Refer to the building section where the meson sample command mentions `-Dsgx_driver_path` which should be `-Dsgx_driver_include_path`

```
meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled \
    -Dsgx_driver=<driver> -Dsgx_driver_path=<path-to-sgx-driver-sources>
```
https://gramine.readthedocs.io/en/latest/building.html#id1

### PR DESCRIPTION
**Pull request by aneessahib**
Fixes #151

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/154)

### CODE REVIEW

**Review by woju — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/154)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @aneessahib)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/154)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @aneessahib)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/154)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @aneessahib)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/154)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
