### PR TITLE
[LibOS] Fix an UAF on PAL event in `clone_implementation_wrapper`

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
See the commit message.

## How to test this PR? 
Try running https://github.com/gramineproject/gramine/pull/839 with and without this fix with ASAN and UBSAN enabled.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/852)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/852)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/852#-N9sA0A4EgDA7WZ9werW):*




_Suggestion:_
```
a UAF
```

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/852)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/852#-NA3NLFY-dkpvSCoEFvb:-NA3NLFY-dkpvSCoEFvc:b-em3dit) (no related file):*
Thanks, now I know what happened in PR #839. A tricky case, but I wonder why this wasn't noticed before by ASan/UBSan (in our CI)?

___
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/852#-NA3MYtM9gzlNmzxM7sJ):*
`it's` -> `the child is`
___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/852#-NA3MqqzDh0oWFgcJBs3):*
`that`

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/852)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/852#-NA3NLFY-dkpvSCoEFvb:-NA46mZMBWqFhz6KfqRy:bsz1uo0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, now I know what happened in PR #839. A tricky case, but I wonder why this wasn't noticed before by ASan/UBSan (in our CI)?
</blockquote></details>

No idea. This requires an unfortunate race, but I don't recall changing anything thread entry specific in that PR...

___

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/852)* status: all files reviewed, 3 unresolved discussions (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/852#-NA3NLFY-dkpvSCoEFvb:-NA4LSiK9D5uT3AZTFdR:bfxeltz) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No idea. This requires an unfortunate race, but I don't recall changing anything thread entry specific in that PR...
</blockquote></details>

Whatever.

___

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/852)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/852#-NA3MYtM9gzlNmzxM7sJ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`it's` -> `the child is`
</blockquote></details>

Done
___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/852#-NA3MqqzDh0oWFgcJBs3):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`that`
</blockquote></details>

Done

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/852)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
