### PR TITLE
Fix exit_group status code and include

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Fixes that were promised during #1900.

## How to test this PR? 

Ci/CD.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1960#-O3GrhlC5EsusdpyyCEb):*
```
[common] Fix include of nodiscard.h header
```

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1960#-O3GrhlC5EsusdpyyCEb):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
[common] Fix include of nodiscard.h header
```
</blockquote></details>

Can be done during final rebase

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1960#-O3GrhlC5EsusdpyyCEb):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can be done during final rebase
</blockquote></details>

Will do.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1960#-O3Th1WR7m-tKADzQ1TE):*




_Suggestion:_
```
[PAL] Set exit_group status to 1 instead of internal PAL_ERROR_NOMEM
```

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @oshogbo)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @oshogbo)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @oshogbo)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

**Review by dimakuv — APPROVED** [review]
> Dismissed @oshogbo from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1960)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
