### PR TITLE
[glibc] Fix wrong warning option in compile script

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 

This was reported by @jyizheng. Thanks to him!

See discussions in https://github.com/gramineproject/gramine/discussions/1487 for details.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1490)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1490)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by woju — APPROVED** [review]
How this ever worked? Why we didn't catch this before?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1490#-:-NcM5JKREsb7zWIITlmS:bwd4txv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
It's a meson subproject build, and there is no `Werror` in the C flags (from what I see), so I guess it was just always a warning, which was hidden somewhere deep in the `glibc-build.log` file...

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1490#-:-NcM7nrW3KE1dJL7Jh0z:bbe20s5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1490)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
Should we add `-Werror` there? Or is it impossible, or not in scope in this PR? How do we know there aren't any other such problems here?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1490#-:-NcRUh9q1JoGxIPr7qTf:bwz7i8l)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
@woju: AFAIR glibc compiles with warnings, maaany warnings :)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1490#-:-NcSulfO0b77PtxtpKJZ:b-wkcg0a)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
ACK, thanks for explanation. What can we do, we'll have to rely on drive-by contributors to fix this stuff.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1490#-:-NcT7AZnBmskXDJNfNbN:b-q8pu03)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
