### PR TITLE
[PAL/Linux-SGX] Error out on enclave_dbginfo allocation failure

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

We're modifying this structure dynamically since we introduced support for dynamic TCS. The modification code in `add_dynamic_tcs()` has no way of knowing whether the allocation failed or succeeded, thus it has no way to decide whether writing there is legal or not.

This PR guarantees that the stucture is always allocated.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1968)

### CODE REVIEW

**Review by oshogbo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1968#-:-O3rBGH287PdrwrQcb3E:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1968)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1968)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1968#-O43P7tR0MFcfod3IWOy):*
-> structure



_Code quote:_
```
stucture
```

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1968)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1968#-O43P7tR0MFcfod3IWOy):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> structure
</blockquote></details>

Can be done during final rebase

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1968)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @kailun-qin)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1968#-O43P7tR0MFcfod3IWOy):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can be done during final rebase
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1968)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
