### PR TITLE
Unify usage of arch specific meson.build

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
As discussed in https://github.com/gramineproject/gramine/pull/569 arch can use whatever files it wants.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: 0 of 15 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1dsWMn-5chgWMXwYbG:-N1dsWMn-5chgWMXwYbH:b-abdxtw) (no related file):*
@stefanberger what do you think? Since asm is arch specific it will only be used in arch specific `meson.build`, so it should be all good.

---

**Review by stefanberger — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573#-:-N1eN1Je5SafddC5nIMZ:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1eZc4d0m_dKTFh9rW1:-N1eZc4eEy7h-AwkUCjq:bthls4d) (no related file):*
nitpick: everywhere `Arch specific` -> `Arch-specific`

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1ej79o-T-sGYGIAcj9:-N1ej79o-T-sGYGIAcjA:bb5ffwj) (no related file):*
Actually, this PR should also arch-ify `nasm_gen` definition. But not sure how; I see two options:
A) add `if host_machine.cpu_family() == 'x86_64'` around it
B) create `arch/x86` directory in the root of the repo and add `meson.build` there (which will define `nasm-gen`)

---

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1ej79o-T-sGYGIAcj9:-N1eovO79G2ViZpUGYkU:b5bd4vk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, this PR should also arch-ify `nasm_gen` definition. But not sure how; I see two options:
A) add `if host_machine.cpu_family() == 'x86_64'` around it
B) create `arch/x86` directory in the root of the repo and add `meson.build` there (which will define `nasm-gen`)
</blockquote></details>

For now, I'd suggest `if host_machine.cpu_family()`, but optimally I'd rename `Scripts/` to `utils/` and did `utils/arch/...`. Having `arch/` in toplevel seems uncalled for.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1enf654O2zyt5pC5JO:-N1enf654O2zyt5pC5JP:b-2z6bmq) (no related file):*
Please add a note to meson section in `coding-style.rst` about this new convention with subdir + temporary variable, with rationale about single variable in a single file.

---
___
*[`LibOS/shim/test/abi/meson.build` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/573#-N1elJnC7cSo-q8x7Og3:-N1elJnDEyZSLgTz64sm:bqyhf4u) ([raw file](https://github.com/gramineproject/gramine/blob/9704e666e32a9646844cc0a6745c701bfd5b43b2/LibOS/shim/test/abi/meson.build#L3)):*
> ```Meson
> if host_machine.cpu_family() == 'x86_64'
>     subdir(host_machine.cpu_family())
> endif
> ```

This will pop on ppc64 unless plugged, is this intentional? This is for ABI tests, so unless @stefanberger actually writes those tests, this is counterproductive.
___
*[`Pal/src/arch/meson.build` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/573#-N1en4I38NBMMmRKWn1r:-N1emBwFC9Fbom09lSB8:b-ddqeaa) ([raw file](https://github.com/gramineproject/gramine/blob/64aae72130998cb405507bb796f7a3eb4a75f9ee/Pal/src/arch/meson.build#L1)):*
> ```Meson
> subdir(host_machine.cpu_family())
> ```

(This and other will also affect ppc, but this is OK, it's likely needed anyway).

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

___
*[`LibOS/shim/test/abi/meson.build` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/573#-N1elJnC7cSo-q8x7Og3:-N1ewiQ-DDmzFNgSgwPM:b2pkqi8) ([raw file](https://github.com/gramineproject/gramine/blob/9704e666e32a9646844cc0a6745c701bfd5b43b2/LibOS/shim/test/abi/meson.build#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This will pop on ppc64 unless plugged, is this intentional? This is for ABI tests, so unless @stefanberger actually writes those tests, this is counterproductive.
</blockquote></details>

I wasn't going those write those tests for now but would provide an empty meson.build file assuming that would work.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`LibOS/shim/test/abi/meson.build` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/573#-N1elJnC7cSo-q8x7Og3:-N1eyfNh9ltXRqQnZaXl:bmjwej7) ([raw file](https://github.com/gramineproject/gramine/blob/9704e666e32a9646844cc0a6745c701bfd5b43b2/LibOS/shim/test/abi/meson.build#L3)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I wasn't going those write those tests for now but would provide an empty meson.build file assuming that would work.
</blockquote></details>

Yes, it will. If that suits you, then I think it's fine.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1eZc4d0m_dKTFh9rW1:-N1eqzPt6dpC9vnB6wuq:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: everywhere `Arch specific` -> `Arch-specific`
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1ej79o-T-sGYGIAcj9:-N1eszFP9ood-3TFtA48:bdpowgf) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For now, I'd suggest `if host_machine.cpu_family()`, but optimally I'd rename `Scripts/` to `utils/` and did `utils/arch/...`. Having `arch/` in toplevel seems uncalled for.
</blockquote></details>

Ok, did an `if` for now.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1enf654O2zyt5pC5JO:-N1eyR7f-nxCdTRxhUBX:b-896fix) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please add a note to meson section in `coding-style.rst` about this new convention with subdir + temporary variable, with rationale about single variable in a single file.
</blockquote></details>

Done.

---
___
*[`LibOS/shim/test/abi/meson.build` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/573#-N1elJnC7cSo-q8x7Og3:-N1er5um-4VzDBoJApeb:bfnn84b) ([raw file](https://github.com/gramineproject/gramine/blob/9704e666e32a9646844cc0a6745c701bfd5b43b2/LibOS/shim/test/abi/meson.build#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This will pop on ppc64 unless plugged, is this intentional? This is for ABI tests, so unless @stefanberger actually writes those tests, this is counterproductive.
</blockquote></details>

If one doesn't want to have them, they can just plug an empty `meson.build` here. I just didn't want to make precedent/exception for patterns like this.
If this is a problem for some reason, I can restore the old version.

**Review by stefanberger — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @mkow and @woju)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 15 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1griv6D7MQ3X6XiZS2):*
Maybe we should add a hint that `Linux-SGX PAL is already arch-specific, so doesn't apply to it`?
___
*[`LibOS/shim/src/meson.build` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1gqe2B9XisqgKHeNG_:-N1gqe2C4d2Mvkttd0Y0:b45m5h1) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/LibOS/shim/src/meson.build#L104)):*
> ```Meson
> 
> # Arch-specific meson.build must define a list of arch-specific sources in `libos_sources_arch`
> # and a full path to LibOS linker script in `shim_lds`.
> ```

This is hard to read, and will get even more confusing if we e.g. add a third Meson variable.

Maybe add some structure to all these comments, like this:
```
# Arch-specific meson.build must define the following Meson variables:
#   - `libos_sources_arch` -- list of arch-specific sources
#   - `shim_lds` -- full path to LibOS linker script
```

Similarly rephrase in all other places in this PR.
___
*[`Pal/src/meson.build` line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1gr9Vi9UEl7CwCK5ux:-N1gr9Vj3pRPZiPSy7gP:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/Pal/src/meson.build#L22)):*
> ```Meson
> )
> 
> # Arch-specific meson.build must define a list of arch-specific sources in `pal_common_sources_arch`
> ```

ditto
___
*[`Pal/src/host/Linux/meson.build` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1grQE9E4DJMnJgXKH_:-N1grQEA5kRJewad9lqN:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/Pal/src/host/Linux/meson.build#L20)):*
> ```Meson
> 
> # Arch-specific meson.build must define a list of arch-specific sources in `pal_direct_sources_arch`
> # and a full path to PAL linker script in `pal_direct_lds`.
> ```

ditto
___
*[`Pal/src/host/Linux-common/meson.build` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1grZnP5id-BFoax0MQ:-N1grZnP5id-BFoax0MR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/Pal/src/host/Linux-common/meson.build#L15)):*
> ```Meson
> 
> # Arch-specific meson.build must define a list of arch-specific sources in
> # `pal_linux_common_sources_urts_arch`.
> ```

ditto
___
*[`Pal/src/host/Skeleton/meson.build` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1grodUB7lPXjqW7uWs:-N1grodUB7lPXjqW7uWt:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/Pal/src/host/Skeleton/meson.build#L1)):*
> ```Meson
> # Arch-specific meson.build must define a full path to PAL linker script in `pal_skeleton_lds`.
> ```

ditto

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1griv6D7MQ3X6XiZS2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we should add a hint that `Linux-SGX PAL is already arch-specific, so doesn't apply to it`?
</blockquote></details>

Idk, can add if you want, but I think it's obvious SGX is arch specific.
___
*[`LibOS/shim/src/meson.build` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1gqe2B9XisqgKHeNG_:-N1hnGaCDo3eYv6Z9nl_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/LibOS/shim/src/meson.build#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is hard to read, and will get even more confusing if we e.g. add a third Meson variable.

Maybe add some structure to all these comments, like this:
```
# Arch-specific meson.build must define the following Meson variables:
#   - `libos_sources_arch` -- list of arch-specific sources
#   - `shim_lds` -- full path to LibOS linker script
```

Similarly rephrase in all other places in this PR.
</blockquote></details>

Done.
___
*[`Pal/src/meson.build` line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1gr9Vi9UEl7CwCK5ux:-N1hnYSVEPrKHB6AzhDW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/Pal/src/meson.build#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux/meson.build` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1grQE9E4DJMnJgXKH_:-N1hnihe3eOvk4vZAGke:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/Pal/src/host/Linux/meson.build#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-common/meson.build` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1grZnP5id-BFoax0MQ:-N1hnozZAPVQgY3Of7tv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/Pal/src/host/Linux-common/meson.build#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Pal/src/host/Skeleton/meson.build` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1grodUB7lPXjqW7uWs:-N1hnvQ6459L9NGY5r7h:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9092ab04c8d9e43753b9ea03213cb0f19b90c72f/Pal/src/host/Skeleton/meson.build#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1eZc4d0m_dKTFh9rW1:-N1hu595-s2J0ZRh7fME:b9lwwma) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You missed the commit message.

___

**Review by dimakuv — DISMISSED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/573#-N1griv6D7MQ3X6XiZS2):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Idk, can add if you want, but I think it's obvious SGX is arch specific.
</blockquote></details>

OK, whatever, not important.

**Review by woju — DISMISSED** [review]
> Reviewed 2 of 7 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`LibOS/shim/test/abi/meson.build` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/573#-N1elJnC7cSo-q8x7Og3:-N1jntc95kr3P-VVqj3N:b-bhyi1) ([raw file](https://github.com/gramineproject/gramine/blob/9704e666e32a9646844cc0a6745c701bfd5b43b2/LibOS/shim/test/abi/meson.build#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If one doesn't want to have them, they can just plug an empty `meson.build` here. I just didn't want to make precedent/exception for patterns like this.
If this is a problem for some reason, I can restore the old version.
</blockquote></details>

No, it's OK. I was concerned about putting unreasonable burden on other archs.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/573#-N1eZc4d0m_dKTFh9rW1:-N1jpXBB79Afdvebj_kB:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You missed the commit message.
</blockquote></details>

Done.

___

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/573)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by stefanberger** [comment]
> No, it's OK. I was concerned about putting unreasonable burden on other archs.

I have now also 3 ABI tests for ppc64 derived from the x86_64 code.

**Pull request merged**
