### PR TITLE
[common,LibOS,PAL] Remove network/hton.c

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Some used functions from this removed file were moved to `socket_utils.h` and rewritten for readability.

This PR was inspired by discussions in https://github.com/gramineproject/gramine/pull/1308.

## How to test this PR? 

CI is enough.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1310)

### CODE REVIEW

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1310)* status: 0 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/include/socket_utils.h` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1310#-NTx4cyQDIwuF5cg3PTb:-NTx4cyQDIwuF5cg3PTc:bbbd353) ([raw file](https://github.com/gramineproject/gramine/blob/83d7133fa8481efc36610b03b657d3732964bcaf/common/include/socket_utils.h#L16)):*
> ```objc
> void linux_to_pal_sockaddr(const void* linux_addr, struct pal_socket_addr* pal_addr);
> 
> #if __BYTE_ORDER == __BIG_ENDIAN
> ```

Do we want to use compiler predefined macros e.g., `__BYTE_ORDER__ ` so that we won't need to pull in libc headers (`#include <endian.h>` above)?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1310)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`common/include/socket_utils.h` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1310#-NTx4cyQDIwuF5cg3PTb:-NTx8Yrp5TypfOvCEh9G:b-rcsgfn) ([raw file](https://github.com/gramineproject/gramine/blob/83d7133fa8481efc36610b03b657d3732964bcaf/common/include/socket_utils.h#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do we want to use compiler predefined macros e.g., `__BYTE_ORDER__ ` so that we won't need to pull in libc headers (`#include <endian.h>` above)?
</blockquote></details>

Done. I checked, and these macros seem supported on GCC and Clang for some time (and on different archs), so this looks like a safe option.

**Comment by dimakuv** [comment]
Jenkins, retest Docs please (one CI machine changed its RSA key)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (one CI machine changed its RSA key)

**Comment by dimakuv** [comment]
Jenkins, retest check-python-platlib please (one CI machine changed its RSA key)

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1310)* status: 0 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`common/src/network/hton.c` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/1310#-NTxvfumA7rnu_-dTYiP:-NTxvfumA7rnu_-dTYiQ:b-3zbucp) ([raw file](https://github.com/gramineproject/gramine/blob/032e35ecf32096cc3e8134f90dadad770b545fe0/common/src/network/hton.c#L1)):*
> ```C
> /* Copyright (C) 1993,97,2002 Free Software Foundation, Inc.
> ```


We may need to remove this network directory during rebase since nothing is left here.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1310)* status: 8 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1310)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1310#-NU-JEDa1319iwsv5uFc):*
Just "common", the change is there and the rest is only a result of it to adjust to the new "API".



_Suggestion:_
```
[common] Remove network/hton.c
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1310)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1310#-NU-JEDa1319iwsv5uFc):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just "common", the change is there and the rest is only a result of it to adjust to the new "API".
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1310)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
