### PR TITLE
Mention GitHub Discussions in README

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Requested by Mona. See https://github.com/gramineproject/gramine/discussions/985.

## How to test this PR? 

See https://github.com/gramineproject/gramine/tree/dimakuv/add-discussions-to-readme

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1011)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1011)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`README.rst` line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/1011#-NFKGMzOETfKt35w4Seh:-NFKGMzPARSLVX8UC4_D:b-e2m9ep) ([raw file](https://github.com/gramineproject/gramine/blob/509409d51c4eb998036454e265937bc3e4161fbe/README.rst#L85)):*
> ```reStructuredText
> <https://github.com/gramineproject/gramine/issues>`__.
> 
> If you really prefer emails, please send them to users@gramineproject.io
> ```

I don't see a reason for this word here

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1011)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`README.rst` line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/1011#-NFKGMzOETfKt35w4Seh:-NFNFpT64-75xW_H-W4e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/509409d51c4eb998036454e265937bc3e4161fbe/README.rst#L85)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't see a reason for this word here
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1011)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1011)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1011#-NFRDIiJ6HDAIDyoXTFt):*




_Suggestion:_
```
[Docs] Mention GitHub Discussions in README
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1011)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1011#-NFRDIiJ6HDAIDyoXTFt):*
Done.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1011)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1011)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
