### PR TITLE
[docker] Support multiple versions of Ubuntu

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Allow to create images on ubuntu 20.04 and 22.04. 

## How to test this PR? 

I have run libos regression test suite on Ubuntu 22.04.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1614)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1614)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1614#-Nh6H4Y0DwJEfeHqAcdp):*
Can we add smth like `Previously only Ubuntu 20.04 (bionic) was supported. This commit adds support for Ubuntu 22.04 (jammy).`

Can be done during final rebase.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1614)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1614#-Nh6H4Y0DwJEfeHqAcdp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add smth like `Previously only Ubuntu 20.04 (bionic) was supported. This commit adds support for Ubuntu 22.04 (jammy).`

Can be done during final rebase.
</blockquote></details>

Ofc :)

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1614)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1614#-Nh6H4Y0DwJEfeHqAcdp):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ofc :)
</blockquote></details>

Let me just fix this for myself, bionic was 18.04:
`Previously only Ubuntu 20.04 (focal) was supported. This commit adds support for Ubuntu 22.04 (jammy).`

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1614)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1614)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1614)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1614#-Nh6H4Y0DwJEfeHqAcdp):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Let me just fix this for myself, bionic was 18.04:
`Previously only Ubuntu 20.04 (focal) was supported. This commit adds support for Ubuntu 22.04 (jammy).`
</blockquote></details>

Oops, yes, your version is correct.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1614)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1614#-Nh6H4Y0DwJEfeHqAcdp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, yes, your version is correct.
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1614)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Pull request merged**
