### PR TITLE
[CI-Examples] Harden Busybox example

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This PR removes the `sgx.allowed_files` insecure manifest option, since the files there are not needed at all. Also, this commit removes many other superfluous manifest options.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`CI-Examples/busybox/busybox.manifest.template` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/958#-NDluY2j-WUpKtD4_IdM:-NDluY2j-WUpKtD4_IdN:b-5jkj9) ([raw file](https://github.com/gramineproject/gramine/blob/d5599d52d2076006d31493da00f096099298aaf0/CI-Examples/busybox/busybox.manifest.template#L13)):*
> ```
> loader.env.HOME = ""
> loader.env.PWD = ""
> loader.env.HOSTNAME = "test"
> ```

FYI: No idea why these were added by someone, it's too old (more than 3 years ago)
___
*[`CI-Examples/busybox/Makefile` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/958#-NDlucq997GptWxgfSmt:-NDlucq997GptWxgfSmu:b-f34ujw) ([raw file](https://github.com/gramineproject/gramine/blob/d5599d52d2076006d31493da00f096099298aaf0/CI-Examples/busybox/Makefile#L41)):*
> ```Makefile
> 	# to the Busybox binary
> 	sed -e 's/.*CONFIG_BUSYBOX_EXEC_PATH.*/CONFIG_BUSYBOX_EXEC_PATH="\/busybox"/' \
> 		-i $(SRCDIR)/.config
> ```

FYI: This was too old (more than 3 years ago), not `/proc/self/exe` works fine, I did some experiments.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: 1 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`CI-Examples/busybox/busybox.manifest.template` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/958#-NDm8iMP5Ks3LifWyyi2:-NE-uu5H2PpbM4qLzXtq:b-ddr2ev) ([raw file](https://github.com/gramineproject/gramine/blob/d5599d52d2076006d31493da00f096099298aaf0/CI-Examples/busybox/busybox.manifest.template#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Did you try running network related programs in busybox (like `ping` or `dig`)?
Also what about e.g. `id`, does it work without these?
Note this manifest is for all programs run via the shell, not only the busybox sh itself.
</blockquote></details>

Done.

- `ping` cannot be used because Gramine doesn't support raw sockets:
```
$ gramine-direct ./busybox ping 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
ping: can't create raw socket: Protocol not supported
```

- `dig` is not something found in Busybox:
```
$ ./busybox dig
dig: applet not found
```

- `hostname` is a good candidate, and you're right, my first iteration didn't work:
```
$ gramine-direct ./busybox hostname -f
hostname: localhost: Host name lookup failure
```

- with new changes to this PR, `hostname` works:
```
$ gramine-direct ./busybox hostname -f
mehlow-prequal01.jf.intel.com
```

- another good candidate for testing is `wget`, now also works:
```
$ gramine-direct ./busybox wget google.com
Connecting to proxy-us.intel.com:911 (10.7.211.16:911)
saving to 'index.html'
index.html           100% |********************************| 14012  0:00:00 ETA
'index.html' saved
```

- I'm not sure why you care about `id`. It works but unsurprisingly shows this:
```
$ gramine-direct ./busybox id
uid=0 gid=0
```

There are a bunch of other applets like `ip` (can't work in Gramine since too low level), `telnet` (seems to work, but I didn't test properly with some echo server), `tftp` (didn't test).
___
*[`CI-Examples/busybox/Makefile` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/958#-NDlucq997GptWxgfSmt:-NE-tv9Y3CJTjfsI8wjg:b-1rcs3e) ([raw file](https://github.com/gramineproject/gramine/blob/d5599d52d2076006d31493da00f096099298aaf0/CI-Examples/busybox/Makefile#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, it's not all roses either:
```
bash-5.1# exec /proc/self/exe -i
exe-5.1#
```
</blockquote></details>

@boryspoplawski I'm not sure how you achieved this effect?

Here is what I have:
```bash
gramine/CI-Examples/busybox$ ./busybox sh
~/gramineproject/gramine/CI-Examples/busybox $ exec /proc/self/exe -i
exe: applet not found

gramine/CI-Examples/busybox$ gramine-direct ./busybox sh
exec /proc/self/exe -i
exe: applet not found
```

As can be seen above, the behavior is the same.

Did you spawn Bash inside of BusyBox before doing this?
___
*[`CI-Examples/busybox/README.md` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/958#-NDmAjxKEJ8jAAyN1N2J:-NE-uV87E791vw561am2:bm7q6wr) ([raw file](https://github.com/gramineproject/gramine/blob/d5599d52d2076006d31493da00f096099298aaf0/CI-Examples/busybox/README.md#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this change? If you are reading this readme, then it means you have obtained Gramine sources and are using latest master, doesn't it?
</blockquote></details>

Done. Fair enough.
___
*[`CI-Examples/busybox/README.md` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/958#-NDmAtqm4DHv5pUb8tUP:-NE-uW3y-ZCVVO8RdnRY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5599d52d2076006d31493da00f096099298aaf0/CI-Examples/busybox/README.md#L32)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (LTP tests `fcntl14_64` and`fdatasync01` timed out, unrelated and seems because of slow hard drive)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/busybox/busybox.manifest.template` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/958#-NE1_2wJ-K-mq4MXQCuN:-NE1_2wJ-K-mq4MXQCuO:b22x5z3) ([raw file](https://github.com/gramineproject/gramine/blob/63df5c588d84c30f1422a6860e3ba0159390515e/CI-Examples/busybox/busybox.manifest.template#L10)):*
> ```
> loader.env.LD_LIBRARY_PATH = "/lib"
> 
> # required when running e.g. `wget` applet in a corporate environment with a proxy
> ```

Please add a note that this is for testing purposes and not production.
Also I assume you test often with busybox, and having these makes your life much easier. Otherwise I would remove them - this is `CI-Examples`, not `CorpoEnv-Examples`.
___
*[`CI-Examples/busybox/Makefile` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/958#-NDlucq997GptWxgfSmt:-NE1aWik7XpWlDlW4hIf:b27jv0k) ([raw file](https://github.com/gramineproject/gramine/blob/d5599d52d2076006d31493da00f096099298aaf0/CI-Examples/busybox/Makefile#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski I'm not sure how you achieved this effect?

Here is what I have:
```bash
gramine/CI-Examples/busybox$ ./busybox sh
~/gramineproject/gramine/CI-Examples/busybox $ exec /proc/self/exe -i
exe: applet not found

gramine/CI-Examples/busybox$ gramine-direct ./busybox sh
exec /proc/self/exe -i
exe: applet not found
```

As can be seen above, the behavior is the same.

Did you spawn Bash inside of BusyBox before doing this?
</blockquote></details>

Yeah, I've used `bash` by mistake.
Anyway `/proc/self/exe` still seems have a lot of issue, but it works good enough for now

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/958#-NE2nkX72so1LaalQNLd):*
this is a bit off, as `/etc/hosts` turned out to be needed in the end



_Code quote:_
```
since the files there are not needed at all
```
___
*[`CI-Examples/busybox/busybox.manifest.template` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/958#-NE1_2wJ-K-mq4MXQCuN:-NE2o20E5anKBnBA2825:bhajq2o) ([raw file](https://github.com/gramineproject/gramine/blob/63df5c588d84c30f1422a6860e3ba0159390515e/CI-Examples/busybox/busybox.manifest.template#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a note that this is for testing purposes and not production.
Also I assume you test often with busybox, and having these makes your life much easier. Otherwise I would remove them - this is `CI-Examples`, not `CorpoEnv-Examples`.
</blockquote></details>

We don't have this in other examples, why adding it here?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/958#-NE2nkX72so1LaalQNLd):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this is a bit off, as `/etc/hosts` turned out to be needed in the end
</blockquote></details>

I'll change to this:
```
  This commit removes the `sgx.allowed_files` insecure manifest option,
  since the files there are not needed at all (except for `/etc/hosts` which
  now has hardcoded contents and is added as `sgx.trusted_files`). Also, ...
```
___
*[`CI-Examples/busybox/busybox.manifest.template` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/958#-NE1_2wJ-K-mq4MXQCuN:-NE51sNh2uCt1q4GLhK2:bkrnxky) ([raw file](https://github.com/gramineproject/gramine/blob/63df5c588d84c30f1422a6860e3ba0159390515e/CI-Examples/busybox/busybox.manifest.template#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We don't have this in other examples, why adding it here?
</blockquote></details>

Well, yeah, ok, let me delete these envvars.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/958#-NE2nkX72so1LaalQNLd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll change to this:
```
  This commit removes the `sgx.allowed_files` insecure manifest option,
  since the files there are not needed at all (except for `/etc/hosts` which
  now has hardcoded contents and is added as `sgx.trusted_files`). Also, ...
```
</blockquote></details>

Done

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/958)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
