### PR TITLE
[Pal] Deduplicate `_DkGetCPUInfo()` implementations

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

And also move them to a proper, arch-specific, but not PAL-specific directory.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/meson.build, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/334#-MtE-M40EN1eZSbr5wbn:-MtE-M40EN1eZSbr5wbo:b-yemrg) ([raw file](https://github.com/gramineproject/gramine/blob/40648e165729e50b316317c5765c97cb9f5faefb/Pal/src/meson.build#L22)):*
> ```Meson
> )
> 
> pal_sources_arch = [
> ```

`pal_common_sources_arch` for uniformity?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/meson.build, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/334#-MtE-M40EN1eZSbr5wbn:-MtFJ3MG-brb72CUrzmD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40648e165729e50b316317c5765c97cb9f5faefb/Pal/src/meson.build#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`pal_common_sources_arch` for uniformity? 
</blockquote></details>

Done.

**Review by stefanberger — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334#-:-MtFNJyy2U4bwkGp4BYb:bnfp4nl)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/pal_internal.h, line 227 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHaTKo8gfKV90gg4Qe:-MtHaTKp88Vzv89zJ7ka:b-faxyje) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/include/pal_internal.h#L227)):*
> ```objc
> int _DkRandomBitsRead(void* buffer, size_t size);
> 
> double _DkGetBogomips(void);
> ```

Do we really want this instead of `int _DkGetBogomips(double* out_value)`?

I understand that this is an internal interface, and thus we can change it in the future as we see fit. Also, I understand that there is currently no possibility to return an error (on Linux at least). But could an "irrecoverable" error happen in other PALs? (Then we would need a proper return error code.)
___
*[Pal/src/meson.build, line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHYdyD6jb7OaKacE9a:-MtHYdyD6jb7OaKacE9b:bu0bz0q) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/meson.build#L23)):*
> ```Meson
> 
> pal_common_sources_arch = [
>     'pal_cpuid.c',
> ```

Why did you choose the prefix `pal_`? Wouldn't it be more consistent to have `db_cpuid.c`?

I will be also fine with `pal_cpuid.c`, I just want to understand if we decide on any conventions (like moving away from `db_` prefix).
___
*[Pal/src/arch/x86_64/pal_cpuid.c, line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHZiMi4bif1MM8KZT5:-MtHZiMi4bif1MM8KZT6:bjo6341) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/arch/x86_64/pal_cpuid.c#L124)):*
> ```C
>                 fmax *= 2;
>                 flags = new_flags;
>             }
> ```

I find this unnecessarily complicated -- we know the max possible set of flags, so we know the max possible `flags` string size. There is no need for realloc here.

We could either have a `g_flags_str[4096]` global, or `flags = malloc(4096)` -- in both cases we can remove realloc and just have an assert. I chose `4096` just as an example -- in fact, for the current set of flags it's more like `1024`.

But not blocking, since you simple copy-pasted this code.
___
*[Pal/src/arch/x86_64/pal_cpuid.c, line 146 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtH_b6z8M6M_QzwfgGv:-MtH_b6z8M6M_QzwfgGw:bqvfeac) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/arch/x86_64/pal_cpuid.c#L146)):*
> ```C
>     free(brand);
> out_vendor_id:
>     free(vendor_id);
> ```

I dislike this pattern of multiple labels. I'd prefer to have a single label `out` and define all these three vars at the top of the func as `char* flags = NULL;`.

But not blocking, since you simple copy-pasted this code.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 641 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHbH24BGnHmGRI4k_A:-MtHbH24BGnHmGRI4k_B:b-hhbkzh) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/host/Linux-SGX/db_misc.c#L641)):*
> ```C
> #define CPUID_LEAF_PROC_FREQ 0x16
> 
> ssize_t read_file_buffer(const char* filename, char* buf, size_t buf_size) {
> ```

Why is this function declared here? Maybe move to `enclave_framework.c` or `enclave_platform.c`?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334)* status: 12 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/include/pal_internal.h, line 227 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHaTKo8gfKV90gg4Qe:-MtIMhqu2kw2rvUz54hT:b-sbsgis) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/include/pal_internal.h#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we really want this instead of `int _DkGetBogomips(double* out_value)`?

I understand that this is an internal interface, and thus we can change it in the future as we see fit. Also, I understand that there is currently no possibility to return an error (on Linux at least). But could an "irrecoverable" error happen in other PALs? (Then we would need a proper return error code.)
</blockquote></details>

I'd rather do this only after we actually find a PAL where we need it. Or maybe you want me to do this already and change the logic on SGX?
___
*[Pal/src/meson.build, line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHYdyD6jb7OaKacE9a:-MtIP44q1MSjopvjOCwK:b2vy8kd) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/meson.build#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you choose the prefix `pal_`? Wouldn't it be more consistent to have `db_cpuid.c`?

I will be also fine with `pal_cpuid.c`, I just want to understand if we decide on any conventions (like moving away from `db_` prefix).
</blockquote></details>

I just won't to slowly move away from `db_`, no one knows what it stands for. I'll probably rename other files at some point.
___
*[Pal/src/arch/x86_64/pal_cpuid.c, line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHZiMi4bif1MM8KZT5:-MtIPPAk4VxBLule07cl:b4yvly8) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/arch/x86_64/pal_cpuid.c#L124)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I find this unnecessarily complicated -- we know the max possible set of flags, so we know the max possible `flags` string size. There is no need for realloc here.

We could either have a `g_flags_str[4096]` global, or `flags = malloc(4096)` -- in both cases we can remove realloc and just have an assert. I chose `4096` just as an example -- in fact, for the current set of flags it's more like `1024`.

But not blocking, since you simple copy-pasted this code.
</blockquote></details>

I'd fix this on another occasion, as we want to focus on the topology sanitization right now.
___
*[Pal/src/arch/x86_64/pal_cpuid.c, line 146 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtH_b6z8M6M_QzwfgGv:-MtIQSqdDaxAeP9zvvLO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/arch/x86_64/pal_cpuid.c#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I dislike this pattern of multiple labels. I'd prefer to have a single label `out` and define all these three vars at the top of the func as `char* flags = NULL;`.

But not blocking, since you simple copy-pasted this code.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 641 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHbH24BGnHmGRI4k_A:-MtIRQxL7yNXaSh7e78h:b-djbpit) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/host/Linux-SGX/db_misc.c#L641)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this function declared here? Maybe move to `enclave_framework.c` or `enclave_platform.c`?
</blockquote></details>

I don't know, both "db_misc" and "enclave_framework" seem like a bag of totally random things...

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Pal/include/pal_internal.h, line 227 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHaTKo8gfKV90gg4Qe:-MtIc57r24G3QyiP0LdY:b-jcml8p) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/include/pal_internal.h#L227)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rather do this only after we actually find a PAL where we need it. Or maybe you want me to do this already and change the logic on SGX?
</blockquote></details>

OK, just wanted to know your opinion.
___
*[Pal/src/meson.build, line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHYdyD6jb7OaKacE9a:-MtIcCPK530WiHo0cfEE:bzalhiu) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/meson.build#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I just won't to slowly move away from `db_`, no one knows what it stands for. I'll probably rename other files at some point.
</blockquote></details>

OK, I agree with this.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 641 at r2](https://reviewable.io/reviews/gramineproject/gramine/334#-MtHbH24BGnHmGRI4k_A:-MtIcK_a1fMR322o6j8V:bwvlthd) ([raw file](https://github.com/gramineproject/gramine/blob/67155a48bfd01dc96575a16b49b07662077298e6/Pal/src/host/Linux-SGX/db_misc.c#L641)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't know, both "db_misc" and "enclave_framework" seem like a bag of totally random things...
</blockquote></details>

OK, agreed.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/334)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
