### PR TITLE
[Tools] Compile argv_serializer with meson

### PR DESCRIPTION
**Pull request by woju**
Another thing to mesonify.

## How to test this PR? 

In Jenkins there are two tests in `test_libos.py`.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/68)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/68)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/68#-Mjn13ssBuZ465vbi2Z2):*
Shouldn't it be `[Tools]` or `[build]`? Not blocking, can be done during final rebase.

**Comment by woju** [comment]
Jenkins, test Jenkins-Debug-20.04 please (timeout on `test_libos.TC_30_Syscall.test_033_rename_unlink_chroot`)

**Review by mkow — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/68)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/68#-Mjn13ssBuZ465vbi2Z2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't it be `[Tools]` or `[build]`? Not blocking, can be done during final rebase.
</blockquote></details>

Yup, IMO "[Tools]" is better.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/68)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/68#-Mjn13ssBuZ465vbi2Z2):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, IMO "[Tools]" is better.
</blockquote></details>

Done

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/68)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
