### PR TITLE
[LibOS] Allocate temporary CPU mask on stack in `sched_setaffinity`

### LINKED ISSUE #913: Degradation seen when running certain OpenVino models for Latency after [LibOS,PAL] Emulate CPU affinity in LibOS commit
## Description of the problem
In preparation for the release we were running different workloads with Gramine master and we noticed a substantial jump in overhead for Gramine Direct when running select OpenVino workloads measuring latency.

Sample numbers for one of the workloads are copied below:

image

Observations:
1.	Gramine 1.2 without numactl had the best values for both native and with Gramine direct.
2.	Gramine 1.3 without numactl, Gramine Direct numbers degrade by almost 30%. 
3.	Gramine 1.3 with numactl the numbers improve a bit (146 vs 156) but the native numbers degrade (107 vs 133)

When we triaged the different commit that went into Gramine post v1.2 we found that this was due to the following commit:
[[LibOS,PAL] Emulate CPU affinity in LibOS](https://github.com/gramineproject/gramine/commit/5b6f6db983a9ec23cf94408f5941eaaaea9a4d41)

ov_perf_bert_large_fp32_latency, ov_perf_bert_large_int8_latency are some of the other workloads where we see similar degradations.

Other workloads like TensorFlow and Redis don't have any performance degradations when compared to Gramine 1.2

## Steps to reproduce

Please the steps in this document to setup and run OpenVino.

[benchmarking.txt](https://github.com/gramineproject/gramine/files/9577454/benchmarking.txt)

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, temporary CPU mask was always allocated on heap. However, the current LibOS memory allocator exhibits bad performance in multi-threaded environments as it has a single global lock. This becomes a performace bottleneck on some heavily multi-threaded workloads like OpenVINO.

This PR introduces a fast path for the common case of platforms with less than 1024 CPUs, where temporary CPU mask is allocated on the stack and thus avoids lock contention.

Fixes #913.

## How to test this PR? 

See #913. I checked manually on the OpenVINO workload.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC4lRFr7Wjkza9Q2fcy:buq99vl) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
> ```C
>     size_t cpu_mask_size = GET_CPU_MASK_LEN() * sizeof(*cpu_mask);
> 
>     if (cpu_mask_size <= 128) {
> ```

FYI: This is a rather random limit. I thought that allocating 128 bytes of stack doesn't hurt, and it accounts for 1024 CPUs, which is more than enough for modern CPUs. I'll be ok to change this limit in any direction (but no less than 256 CPUs). If needed, I can also introduce a macro for this.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC4yvhr02vkN9miRT1_:b-a323d3) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: This is a rather random limit. I thought that allocating 128 bytes of stack doesn't hurt, and it accounts for 1024 CPUs, which is more than enough for modern CPUs. I'll be ok to change this limit in any direction (but no less than 256 CPUs). If needed, I can also introduce a macro for this.
</blockquote></details>

I think we can even go with 1024, it's still just 1/4 of a page.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`libos/src/sys/libos_sched.c` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC51GGQ8GR7_z7ZMVVj:-NC51GGRCJVINDWXpK_F:b8y001n) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L11)):*
> ```C
>  */
> 
> #include <alloca.h>
> ```

This is a system header we probably should not include.
___
*[`libos/src/sys/libos_sched.c` line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC51MhQ1mN5OydUPcmr:-NC51MhQ1mN5OydUPcms:b-zfapeb) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L173)):*
> ```C
>         /* fast path: allocate on stack if the platform has <= 1024 CPUs */
>         cpu_mask_on_heap = false;
>         cpu_mask = alloca(cpu_mask_size);
> ```

defined in `api.h`



_Suggestion:_
```C
__alloca
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/sys/libos_sched.c` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC51GGQ8GR7_z7ZMVVj:-NC5BfjlABlWEbUcLGZ9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is a system header we probably should not include.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_sched.c` line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC51MhQ1mN5OydUPcmr:-NC5BvmE6fCLsXKFdApS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L173)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

defined in `api.h`
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC5W7NcA0RirWxKujg8:bf9ve0l) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we can even go with 1024, it's still just 1/4 of a page.
</blockquote></details>

Agree and since the default stack size is `256K` even `1K` allocation should be fine.
nit: Would it help to add a comment or a MACRO that tells what this 128 bytes represent? Something like 128 bytes to represent 1024 CPUs or even a MACRO like `CPUMASK_TO_HOLD_1024CPUS`.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC5oTd7AfycpDhF36l9:br3wp39) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Agree and since the default stack size is `256K` even `1K` allocation should be fine.
nit: Would it help to add a comment or a MACRO that tells what this 128 bytes represent? Something like 128 bytes to represent 1024 CPUs or even a MACRO like `CPUMASK_TO_HOLD_1024CPUS`.
</blockquote></details>

Nah, a macro would be an overkill here. This constant is only a performance threshold.
@dimakuv: Did you see this discussion?

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC5ybuD2MTQAMYxoM77:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nah, a macro would be an overkill here. This constant is only a performance threshold.
@dimakuv: Did you see this discussion?
</blockquote></details>

Done.

**Review by vijaydhanraj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915#-:-NC5zR4t9Kfi9JfjdFMd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC6jKxYAxsr5XZjIm6y:b-wyp1a9) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please revert this change. LibOS stack is only 8 pages (32k) and I don't see how `1024` CPUs would not be enough.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`libos/src/sys/libos_sched.c` line 184 at r4](https://reviewable.io/reviews/gramineproject/gramine/915#-NC6kfXI8oZZCLh35Gp2:-NC6kfXI8oZZCLh35Gp3:b-9ns8yy) ([raw file](https://github.com/gramineproject/gramine/blob/ec11be727632b54a339c25e630c0999645d449c7/libos/src/sys/libos_sched.c#L184)):*
> ```C
> 
>     memset(cpu_mask, 0, cpu_mask_size);
>     memcpy(cpu_mask, user_mask_ptr, MIN(user_mask_size, cpu_mask_size));
> ```

```
size_t len = MIN(user_mask_size, cpu_mask_size);
memcpy(cpu_mask, user_mask_ptr, len);
memset(&cpu_mask[len], 0, cpu_mask_size - len);

```

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @vijaydhanraj)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> Reviewed all commit messages.
> Dismissed @stefanberger from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC6zWWFD7suixog4kp0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please revert this change. LibOS stack is only 8 pages (32k) and I don't see how `1024` CPUs would not be enough.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_sched.c` line 184 at r4](https://reviewable.io/reviews/gramineproject/gramine/915#-NC6kfXI8oZZCLh35Gp2:-NC6z5yv6uIYPt948C5J:b-21xbwd) ([raw file](https://github.com/gramineproject/gramine/blob/ec11be727632b54a339c25e630c0999645d449c7/libos/src/sys/libos_sched.c#L184)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

```
size_t len = MIN(user_mask_size, cpu_mask_size);
memcpy(cpu_mask, user_mask_ptr, len);
memset(&cpu_mask[len], 0, cpu_mask_size - len);

```
</blockquote></details>

I understand the proposed change, but I don't see a need in complicating the current code for a tiny optimization (first, `cpu_mask` will be typically tens of bytes, memsetting which is a negligible number of CPU cycles, second, this feels like something that a compiler can optimize itself).

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC6zxgmC5qAhwF4yy6i:b-5qegu3) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Btw, as @boryspoplawski mentioned, the LibOS stack is indeed only 8 pages in size: https://github.com/gramineproject/gramine/blob/00e91a07ad5dd258cfbabdfdfe7e9b0c7bf2602c/libos/include/libos_defs.h#L10-L16

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC7Yde08d2lIZ8zgcDE:bcqw9l0) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, as @boryspoplawski mentioned, the LibOS stack is indeed only 8 pages in size: https://github.com/gramineproject/gramine/blob/00e91a07ad5dd258cfbabdfdfe7e9b0c7bf2602c/libos/include/libos_defs.h#L10-L16
</blockquote></details>

Thanks @boryspoplawski @dimakuv but am a little confused as `pthread_attr_getstacksize()` shows stack size as `256K` (default) as defined in https://github.com/gramineproject/gramine/blob/00e91a07ad5dd258cfbabdfdfe7e9b0c7bf2602c/libos/include/libos_defs.h#L19

PS: Not blocking but just discussing.

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NC7htUG7NWtBPJQHDXf:b8rflvt) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks @boryspoplawski @dimakuv but am a little confused as `pthread_attr_getstacksize()` shows stack size as `256K` (default) as defined in https://github.com/gramineproject/gramine/blob/00e91a07ad5dd258cfbabdfdfe7e9b0c7bf2602c/libos/include/libos_defs.h#L19

PS: Not blocking but just discussing.
</blockquote></details>

@vijaydhanraj This is a `ulimit` stack limit, it has nothing to do with the LibOS stack size

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

___
*[`libos/src/sys/libos_sched.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/915#-NC4lRFr7Wjkza9Q2fcx:-NCDWqTdATm0XHjB0dWZ:b5i9fmm) ([raw file](https://github.com/gramineproject/gramine/blob/0d1eb92d5222ec9e12735864432ddf4453f5ac94/libos/src/sys/libos_sched.c#L170)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@vijaydhanraj This is a `ulimit` stack limit, it has nothing to do with the LibOS stack size
</blockquote></details>

Got it, thanks @boryspoplawski

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: all files reviewed, 1 unresolved discussion

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/915)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
