### PR TITLE
[Docs] Add notes on running Helloworld on Alpine

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

I was asked to add these notes on Helloworld on Alpine.

## How to test this PR? 

I temporarily enabled the page: https://gramine.readthedocs.io/en/dimakuv-docs-add-alpine-helloworld/run-sample-application.html

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`Documentation/run-sample-application.rst` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZTd-2o054SPlRWrHcz:-NZTd-2o054SPlRWrHd-:b-bksd7d) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L39)):*
> ```reStructuredText
>    gramine-sgx helloworld
> 
> If you want to run this example on Alpine, then before building, modify the
> ```

Why specific to this example (i.e., what about other sample applications below)?



_Code quote:_
```reStructuredText
this example
```
___
*[`Documentation/run-sample-application.rst` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZTdLyD0kKyMLRaHvDP:-NZTdLyD0kKyMLRaHvDQ:b-mz6hj5) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L57)):*
> ```reStructuredText
> 
> Please note that these sample applications are tested on Ubuntu. Most of these
> applications are also known to run correctly on Fedora/RHEL/AlmaLinux/Rocky
> ```

Alpine?



_Code quote:_
```reStructuredText
Fedora/RHEL/AlmaLinux/Rocky
```
___
*[`Documentation/run-sample-application.rst` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZTdUFW8oNFxg-_eyM5:-NZTdUFW8oNFxg-_eyM6:bnqaflz) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L58)):*
> ```reStructuredText
> Please note that these sample applications are tested on Ubuntu. Most of these
> applications are also known to run correctly on Fedora/RHEL/AlmaLinux/Rocky
> Linux, but with caveats. One caveat is that Makefiles should be invoked with
> ```

How about mentioning it as a caveat here?



_Code quote:_
```reStructuredText
but with caveats
```

**Comment by anjalirai-intel** [comment]
*[`Documentation/run-sample-application.rst` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZU0C-f59OwEoFqk8WP:-NZU0C-f59OwEoFqk8WQ:bjeyq13) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L36)):*
> ```reStructuredText
> Build and run with SGX::
> 
>    make SGX=1
> ```

Helloworld example will work, we should also specify about ARCH_LIBDIR=/lib, incase someone wants to build other workloads

**Review by anjalirai-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`Documentation/run-sample-application.rst` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZU0C-f59OwEoFqk8WP:-NZUPs5n1u7fLS4dRfc0:b-ro89kh) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L36)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Helloworld example will work, we should also specify about ARCH_LIBDIR=/lib, incase someone wants to build other workloads
</blockquote></details>

And Do we also mention about pointing gramine.runtimedir('musl') to /usr/local/lib

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @kailun-qin, and @mkow)

___
*[`Documentation/run-sample-application.rst` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZU0C-f59OwEoFqk8WP:-NZUTX8QE-3NYiSqWbut:bnlv6y8) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L36)):*
> Helloworld example will work, we should also specify about `ARCH_LIBDIR=/lib`, incase someone wants to build other workloads

That actually doesn't work correctly today. That's because `/lib` is considered a "special Gramine runtime-only" directory by our current manifest examples, whereas on Alpine `/lib` is a system-wide generic directory.

Thus, if we just blindly recommend users to specify `ARCH_LIBDIR=/lib`, this will mount over (override) the Gramine-specific `/lib` directory, and either performance will get worse, or even the application will fail.

So basically: we have a kinda bug in Gramine manifests that they use `/lib` for Gramine-specific purposes. We need to fix this bug first, and only then we'll be able  to recommend `ARCH_LIBDIR=/lib`.

I don't want to neither explain all this buggy behavior in this documention, nor add the recommendation of `ARCH_LIBDIR=/lib` that will regress Gramine behavior.

> And Do we also mention about pointing gramine.runtimedir('musl') to /usr/local/lib

What? I'm not sure I understand this. What does it mean "pointing ..."? Is there some bug in Gramine's runtimedir?

---

UPDATE: After thinking about this, I decided to add `ARCH_LIBDIR=/lib` in this PR. This **is** the correct thing to do on Alpine, and the fact that we have a bug in Gramine (that re-uses `/lib` for its own purposes) shouldn't preclude adding the correct instructions in the documentation.
___
*[`Documentation/run-sample-application.rst` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZTd-2o054SPlRWrHcz:-NZUUuPx2eUQ8z1cPi0h:bl114wr) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L39)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Why specific to this example (i.e., what about other sample applications below)?
</blockquote></details>

Because in this current section, we show how to run Helloworld. So if a person uses Alpine, then by trying the steps in this section, they will fail. So we need to warn users in this section, rather than "users will be smart enough to read the following sections and figure out for themselves".

Or maybe you have some specific suggestion how to change the text here?

Note that ideally, we'd have three different subsections: "run Helloworld on Debian/Ubuntu", "run Helloworld on RHEL-like", "run Helloworld on Alpine".

But this is way too much changes, and I honestly don't know how to make it nice. So currently I'm going with a simple approach.
___
*[`Documentation/run-sample-application.rst` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZTdLyD0kKyMLRaHvDP:-NZUWVXU8Q_ba66oF2Kl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L57)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Alpine?
</blockquote></details>

Done.
___
*[`Documentation/run-sample-application.rst` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZTdUFW8oNFxg-_eyM5:-NZUX5TXCFjX_lB4YGFx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L58)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

How about mentioning it as a caveat here?
</blockquote></details>

Done.

**Review by anjalirai-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Documentation/run-sample-application.rst` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZU0C-f59OwEoFqk8WP:-NZUYjvo4ITB7DAS36Sa:bj4o81l) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Helloworld example will work, we should also specify about `ARCH_LIBDIR=/lib`, incase someone wants to build other workloads

That actually doesn't work correctly today. That's because `/lib` is considered a "special Gramine runtime-only" directory by our current manifest examples, whereas on Alpine `/lib` is a system-wide generic directory.

Thus, if we just blindly recommend users to specify `ARCH_LIBDIR=/lib`, this will mount over (override) the Gramine-specific `/lib` directory, and either performance will get worse, or even the application will fail.

So basically: we have a kinda bug in Gramine manifests that they use `/lib` for Gramine-specific purposes. We need to fix this bug first, and only then we'll be able  to recommend `ARCH_LIBDIR=/lib`.

I don't want to neither explain all this buggy behavior in this documention, nor add the recommendation of `ARCH_LIBDIR=/lib` that will regress Gramine behavior.

> And Do we also mention about pointing gramine.runtimedir('musl') to /usr/local/lib

What? I'm not sure I understand this. What does it mean "pointing ..."? Is there some bug in Gramine's runtimedir?

---

UPDATE: After thinking about this, I decided to add `ARCH_LIBDIR=/lib` in this PR. This **is** the correct thing to do on Alpine, and the fact that we have a bug in Gramine (that re-uses `/lib` for its own purposes) shouldn't preclude adding the correct instructions in the documentation.
</blockquote></details>

I meant this issue which you stated "That's because `/lib` is considered a "special Gramine runtime-only" directory by our current manifest examples, whereas on Alpine `/lib` is a system-wide generic directory."

The update looks good

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

___
*[`Documentation/run-sample-application.rst` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZU0C-f59OwEoFqk8WP:-NZUZfci5DGKosnzKAjD:b-h9hqzo) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L36)):*
> And Do we also mention about pointing gramine.runtimedir('musl') to /usr/local/lib

Ah, I understand now. What you mean is that "Gramine runtime" directory must be modified from `/lib` to e.g. `/usr/local/lib`.

So yes, the Gramine runtime dir must be modified to something other than `/lib`, as this dir clashes with Alpine. But we are not sure what this new dir should be; @woju said that this requires some discussions and checking (there are standards that regulate directory names, and we want to adhere to these standards, otherwise we will hit similar problems in the future).

The `/usr/local/lib` directory that was proposed as a quick fix was just a bandaid, that's not a proper solution (it will clash with system-wide `/usr/local/lib`, and we get the same problem again). In reality, the directory name would probably be smth like `/usr/local/lib-gramine-x86_64`, guaranteed to never clash with system-wide libs.

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Documentation/run-sample-application.rst` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZTd-2o054SPlRWrHcz:-NZUgfEK2RPjdTeX0HSM:b-w9pzgs) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Because in this current section, we show how to run Helloworld. So if a person uses Alpine, then by trying the steps in this section, they will fail. So we need to warn users in this section, rather than "users will be smart enough to read the following sections and figure out for themselves".

Or maybe you have some specific suggestion how to change the text here?

Note that ideally, we'd have three different subsections: "run Helloworld on Debian/Ubuntu", "run Helloworld on RHEL-like", "run Helloworld on Alpine".

But this is way too much changes, and I honestly don't know how to make it nice. So currently I'm going with a simple approach.
</blockquote></details>

OK, I'm fine w/ the current version.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @dimakuv)

___
*[`Documentation/run-sample-application.rst` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZU0C-f59OwEoFqk8WP:-NZVGpzQDACk2BViF4tt:b-4vx1sj) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> And Do we also mention about pointing gramine.runtimedir('musl') to /usr/local/lib

Ah, I understand now. What you mean is that "Gramine runtime" directory must be modified from `/lib` to e.g. `/usr/local/lib`.

So yes, the Gramine runtime dir must be modified to something other than `/lib`, as this dir clashes with Alpine. But we are not sure what this new dir should be; @woju said that this requires some discussions and checking (there are standards that regulate directory names, and we want to adhere to these standards, otherwise we will hit similar problems in the future).

The `/usr/local/lib` directory that was proposed as a quick fix was just a bandaid, that's not a proper solution (it will clash with system-wide `/usr/local/lib`, and we get the same problem again). In reality, the directory name would probably be smth like `/usr/local/lib-gramine-x86_64`, guaranteed to never clash with system-wide libs.
</blockquote></details>

Most likely `/usr/lib/x86_64-gramine-gnu` and `/usr/lib/x86_64-gramine-musl`. I would need to prototype this. Not in this PR.
___
*[`Documentation/run-sample-application.rst` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZVH6c1896eRwXW5SL5:-NZVH6c1896eRwXW5SL6:b-yi9rj5) ([raw file](https://github.com/gramineproject/gramine/blob/827e579c758a6eb1c450b975cbb5dacccc1264e5/Documentation/run-sample-application.rst#L41)):*
> ```reStructuredText
> If you want to run this example on Alpine, then before building, modify the
> :file:`helloworld.manifest.template` file: replace ``gramine.runtimedir()`` with
> ``gramine.runtimedir('musl')``. For details, see the section "glibc vs musl"
> ```

If you wanted, you could have done this in manifest: 
```jinja
{% if libc is undefined -%}
    {% set libc = 'glibc' -%}
{% endif -%}

{# ... #}

sgx.trusted_files = [
    "{{ gramine.runtimedir(libc) }}",
    {# ... #}
]
```
in manifest, then add `$GRAMINE_MANIFEST_OPTS` (normally unset and empty) to `gramine-manifest` invocation in `Makefile` and suggest that people do `make GRAMINE_MANIFEST_OPTS=-Dlibc=musl`. There would be no need to edit files, which will get overwritten on checkout and also should not be usually done in packaging. Some day we'll want to add this test as sanity check to `APKBUILD`.

I would totally understand if this is not in scope for this PR, so not blocking.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1438)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @woju)

___
*[`Documentation/run-sample-application.rst` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZU0C-f59OwEoFqk8WP:-NZVxVo27Px3hiYCPc50:bn2ylsm) ([raw file](https://github.com/gramineproject/gramine/blob/0ead6f388d3f83ede77621c000254304a0cbf0a8/Documentation/run-sample-application.rst#L36)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Most likely `/usr/lib/x86_64-gramine-gnu` and `/usr/lib/x86_64-gramine-musl`. I would need to prototype this. Not in this PR.
</blockquote></details>

Sure and thanks.
___
*[`Documentation/run-sample-application.rst` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1438#-NZVH6c1896eRwXW5SL5:-NZVxkcf81cJ9Io-pA0k:bj6qeex) ([raw file](https://github.com/gramineproject/gramine/blob/827e579c758a6eb1c450b975cbb5dacccc1264e5/Documentation/run-sample-application.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If you wanted, you could have done this in manifest: 
```jinja
{% if libc is undefined -%}
    {% set libc = 'glibc' -%}
{% endif -%}

{# ... #}

sgx.trusted_files = [
    "{{ gramine.runtimedir(libc) }}",
    {# ... #}
]
```
in manifest, then add `$GRAMINE_MANIFEST_OPTS` (normally unset and empty) to `gramine-manifest` invocation in `Makefile` and suggest that people do `make GRAMINE_MANIFEST_OPTS=-Dlibc=musl`. There would be no need to edit files, which will get overwritten on checkout and also should not be usually done in packaging. Some day we'll want to add this test as sanity check to `APKBUILD`.

I would totally understand if this is not in scope for this PR, so not blocking.
</blockquote></details>

Yep, I like the idea, but I don't think this is in scope of this PR. Moreover, this should be done uniformly in all our tests, it wouldn't make sense to update only the Helloworld app.

**Pull request merged**
