### PR TITLE
[common,PAL/Linux-SGX] Move IOCTLs from Linux-SGX to common code

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This internal change in Gramine makes flexible IOCTLs generic for all PALs. A future commit will use these new IOCTL APIs in Linux PAL.

Second part of the series of PRs. Other PRs:
- Before this one: https://github.com/gramineproject/gramine/pull/1386
- After this one: https://github.com/gramineproject/gramine/pull/1388

## How to test this PR? 

CI is enough, no functional changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1387)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1387)* status: 0 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1387#-NXjrich-z0ml7wkaMru:-NXjrich-z0ml7wkaMrv:b-n26pb3) (no related file):*
The code is extracted as-is from `pal_devices.c` into new files `ioctls.h` and `ioctls.c`. The changes are minimal -- only in the function names (to remove the `static` keyword and to have a common prefix `ioctls_`).

Unfortunately, I don't know a best way to show a nice git diff. The best I can recommend is this:
```
git diff dimakuv/rename-ioctl-apis:pal/src/host/linux-sgx/pal_devices.c common/src/ioctls/ioctls.h
git diff dimakuv/rename-ioctl-apis:pal/src/host/linux-sgx/pal_devices.c common/src/ioctls/ioctls.c
```

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1387)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1387)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1387)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
