### PR TITLE
[CI-Examples] busybox: Add note on build failure on Ubuntu 24.04

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

For details see #1909.

This doesn't fix the problem, just mentions it to users in the README.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1910)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1910)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-EDMM please (weird timeouts on `TC_04_Attestation.test_000_attestation` and `TC_04_Attestation.test_001_attestation_stdio`, unrelated to the PR)

**Pull request merged**
