### PR TITLE
Drop support for using 0/1 for bools in manifests

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

It was already long-deprecated, time to remove it.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/375)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/375)* status: 1 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[CI-Examples/ra-tls-mbedtls/server.manifest.template, line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/375#-MuxGDjaDTHRqyYGc4u1:-MuxGDjaDTHRqyYGc4u2:b-5wvukh) ([raw file](https://github.com/gramineproject/gramine/blob/6ac9829dcb56d0ddf9d066cd7f0a9657ec0155ce/CI-Examples/ra-tls-mbedtls/server.manifest.template#L35)):*
> ```
> sgx.remote_attestation = true
> sgx.ra_client_spid = "{{ ra_client_spid }}"
> sgx.ra_client_linkable = {{ 'true' if ra_client_linkable == '1' else 'false' }}
> ```

Why not make `ra_client_linkable` either true or false?
ditto for the whole PR

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/375)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/375#-Muz8Bfu23RjDVSJgd0z:-Muz8Bfu23RjDVSJgd1-:b-nlp31r) (no related file):*
I manually verified that our Documentation, GSC and Examples do not have deprecated syntax.

---
___
*[CI-Examples/ra-tls-mbedtls/server.manifest.template, line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/375#-MuxGDjaDTHRqyYGc4u1:-Muz5kVZ5FQi5_iRkYQb:b-a3b0bl) ([raw file](https://github.com/gramineproject/gramine/blob/6ac9829dcb56d0ddf9d066cd7f0a9657ec0155ce/CI-Examples/ra-tls-mbedtls/server.manifest.template#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not make `ra_client_linkable` either true or false?
ditto for the whole PR
</blockquote></details>

I guess because `ra_client_linkable` is taken from the environment variable, and having a `true`/`false` value in the environment variable is weird/non-intuitive for users?

Links for context:
- https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/CI-Examples/ra-tls-mbedtls/Makefile#L10
- https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/CI-Examples/ra-tls-mbedtls/Makefile#L88
- https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/README.md (see examples with `RA_CLIENT_LINKABLE=`)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/375)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/375#-Muz8Bfu23RjDVSJgd0z:-MuzP6zd8H6IEPLx4dmB:b-ucfknh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I manually verified that our Documentation, GSC and Examples do not have deprecated syntax.
</blockquote></details>

Thanks!

---
___
*[CI-Examples/ra-tls-mbedtls/server.manifest.template, line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/375#-MuxGDjaDTHRqyYGc4u1:-MuzP8i-1vrFyF1ZvH4i:bjvgv61) ([raw file](https://github.com/gramineproject/gramine/blob/6ac9829dcb56d0ddf9d066cd7f0a9657ec0155ce/CI-Examples/ra-tls-mbedtls/server.manifest.template#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess because `ra_client_linkable` is taken from the environment variable, and having a `true`/`false` value in the environment variable is weird/non-intuitive for users?

Links for context:
- https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/CI-Examples/ra-tls-mbedtls/Makefile#L10
- https://github.com/gramineproject/gramine/blob/97704a59456cf94e7a90ec995f7eade1cf426a82/CI-Examples/ra-tls-mbedtls/Makefile#L88
- https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/README.md (see examples with `RA_CLIENT_LINKABLE=`)
</blockquote></details>

Yup, we have to preserve 0/1 in the env for consistency, because we use 0/1 in all other envs. So, somewhere we need that `if` with a conversion, and I prefer to write it in concise and readable Python syntax than in Bash ;)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/375)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/375)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/375)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/375)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/375#-Mv-LY8X7oBh89rdPOhT:-Mv-LY8Y1PmFTlkQJXWo:bnbskac) (no related file):*
Actually, let me block till we resolve the discussion about GSC (because it will use the master branch tip in the default configuration). We have this discussion on Gitter. Maybe we'll first modify default GSC value in https://github.com/gramineproject/gsc/blob/c4d5c2ddc7376645f396f069c06f6ba02aea2ee7/config.yaml.template#L8

---

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/375)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/375#-Mv-LY8X7oBh89rdPOhT:-Mv-xoW0AE8lHzo2xzvM:b-t3v0rt) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, let me block till we resolve the discussion about GSC (because it will use the master branch tip in the default configuration). We have this discussion on Gitter. Maybe we'll first modify default GSC value in https://github.com/gramineproject/gsc/blob/c4d5c2ddc7376645f396f069c06f6ba02aea2ee7/config.yaml.template#L8
</blockquote></details>

Unblocking this. We agreed that users must update their GSC manifests or they must set `v1.1` as the commit tag in the GSC's `config.yaml` file.

---

**Pull request merged**
