### PR TITLE
[LibOS] Allow `unlink()` on corrupted encrypted files 

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

~~Previously, LibOS unconditionally set up the inode of the dentry on first lookup, for example, querying the size of the underlying file and saving it into inode fields. This setup of dentry's inode is not needed in cases like file removal (`unlink()`), since the inode will be immediately removed after it was set up. This was particularly painful for encrypted files (as they would open and decrypt the underlying file on inode setup) and tmpfs files (as they would allocate an underlying memory region for file contents on inode setup). Moreover, encrypted files were decrypted on lookup, just to get the real file size; this failed `unlink()` on corrupted or encrypted-with-old-key files.~~

~~This PR allows to skip the setup of the inode. Currently this is only used for the `unlink()` system call. This fixes the problematic case of encrypted files mentioned above and may improve tmpfs performance.~~

Currently, LibOS unconditionally sets up the inode of the dentry on first lookup, for example, querying the size of the underlying file and saving it into inode fields. This setup of dentry's inode is not needed in cases like file removal (`unlink()`), since the inode will be immediately removed after it was set up.

This pecularity made it impossible to remove (unlink) corrupted encrypted files by the app itself: already the lookup of the file would fail, disallowing to proceed to the removal operation. "Corrupted" may mean an attacker-modified file or a more benign case of encrypted-with-old-key file.

This PR allows to perform `unlink()` on such "corrupted" encrypted files (by keeping a "shallow" file object). A LibOS test was added.

## How to test this PR? 

A LibOS test was added.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: 4 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLghYfCBxOln2jjmpY):*
> Moreover, [...]

You just said exactly that in the previous sentence?
___
*[`libos/src/fs/tmpfs/fs.c` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLjj0X0pVGYyfmkeXu:-NsLjj0X0pVGYyfmkeXv:b-owo0ln) ([raw file](https://github.com/gramineproject/gramine/blob/274d0eeadeba1b381deb92d8b7f5659c2b634551/libos/src/fs/tmpfs/fs.c#L36)):*
> ```C
>         return -ENOMEM;
> 
>     if (!skip_inode_setup) {
> ```

Ehh, I'm not a fan of this, now we have some magic bool which leaves the `inode` struct in a partially-initialized state with some fields being initialized and some not. And it's not even documented which ones are which and `unlink` code actually uses that initialized subset...
___
*[`libos/test/regression/tmp_enc/mrenclaves/.dummy` line 0 at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLijrA1JoWFx_imn9W:-NsLijrA1JoWFx_imn9X:b-22wpbz) ([raw file](https://github.com/gramineproject/gramine/blob/0ca3cbd5d24eb5e0ec1fe51995e5954dbbc47061/libos/test/regression/tmp_enc/mrenclaves/.dummy#L0)):*
I think I prefer `.gitkeep`, because it says why we need such a file.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: 4 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/fs/tmpfs/fs.c` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLjj0X0pVGYyfmkeXu:-NsN4gbh2tnBzsJpaPO2:b6uh2pe) ([raw file](https://github.com/gramineproject/gramine/blob/274d0eeadeba1b381deb92d8b7f5659c2b634551/libos/src/fs/tmpfs/fs.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ehh, I'm not a fan of this, now we have some magic bool which leaves the `inode` struct in a partially-initialized state with some fields being initialized and some not. And it's not even documented which ones are which and `unlink` code actually uses that initialized subset...
</blockquote></details>

First of all, I agree that this is a bad coding practice. This was the first idea / workaround that came to my mind, but I also prefer now to change the logic.

After thinking about this, I propose the following:
1. We get rid of `xxx_setup_dentry()` functions:
   - It currently does two things: (a) creates the new inode + attaches it to the dentry, and (b) sets up the additional inode fields like size, create/modify time, etc.
   - The name is meaningless; a better name would be `xxx_create_and_attach_inode()`
   - Some FS implementations (Pseudo, Encrypted) already got rid of this helper function and just inline creation of the inode object; the rest FS implementations (Tmpfs, Chroot, Shm) have this helper function but could easily inline the logic.
2. We split what `xxx_setup_dentry()` func does into two parts:
   - The part of "create the new inode + attach it to dentry" is inlined into corresponding callers (like already done in Pseudo and Encrypted)
   - The part of "set up additional inode fields" is moved to separate helper functions, and this set up is performed **on demand** (lazily), instead of the current eager approach.
3. We clearly separate and document the fields that are immediately initialized in the inode object:
   - I'd like to note that we **must create the inode** during lookup, because inode represents the actual file (whereas dentry is more like a wrapper object that just keeps the info about path traversals)
   - But the inode only needs a small subset of fields during its creation: the FS type, the file type, the permissions, and maybe the uid/gid.
   - The rest inode fields are initialized first with "none" values (e.g. `size = -1` I guess?), and only set up on demand.

In this case, we get rid of this `skip_inode_setup` flag that we have to drag everywhere in this PR, and flip the logic to a more readable one: **instead of skipping set up of inodes in otherwise eager file lookup, we set up inode fields on demand**.

Then the problem of Encrypted and Tmpfs files -- as explained in the PR description -- will go away automatically.

@mkow @kailun-qin What do you think about this proposal?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: 4 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/src/fs/tmpfs/fs.c` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLjj0X0pVGYyfmkeXu:-NtNEZC6ALH77BghcbMs:b-si1a52) ([raw file](https://github.com/gramineproject/gramine/blob/274d0eeadeba1b381deb92d8b7f5659c2b634551/libos/src/fs/tmpfs/fs.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

First of all, I agree that this is a bad coding practice. This was the first idea / workaround that came to my mind, but I also prefer now to change the logic.

After thinking about this, I propose the following:
1. We get rid of `xxx_setup_dentry()` functions:
   - It currently does two things: (a) creates the new inode + attaches it to the dentry, and (b) sets up the additional inode fields like size, create/modify time, etc.
   - The name is meaningless; a better name would be `xxx_create_and_attach_inode()`
   - Some FS implementations (Pseudo, Encrypted) already got rid of this helper function and just inline creation of the inode object; the rest FS implementations (Tmpfs, Chroot, Shm) have this helper function but could easily inline the logic.
2. We split what `xxx_setup_dentry()` func does into two parts:
   - The part of "create the new inode + attach it to dentry" is inlined into corresponding callers (like already done in Pseudo and Encrypted)
   - The part of "set up additional inode fields" is moved to separate helper functions, and this set up is performed **on demand** (lazily), instead of the current eager approach.
3. We clearly separate and document the fields that are immediately initialized in the inode object:
   - I'd like to note that we **must create the inode** during lookup, because inode represents the actual file (whereas dentry is more like a wrapper object that just keeps the info about path traversals)
   - But the inode only needs a small subset of fields during its creation: the FS type, the file type, the permissions, and maybe the uid/gid.
   - The rest inode fields are initialized first with "none" values (e.g. `size = -1` I guess?), and only set up on demand.

In this case, we get rid of this `skip_inode_setup` flag that we have to drag everywhere in this PR, and flip the logic to a more readable one: **instead of skipping set up of inodes in otherwise eager file lookup, we set up inode fields on demand**.

Then the problem of Encrypted and Tmpfs files -- as explained in the PR description -- will go away automatically.

@mkow @kailun-qin What do you think about this proposal?
</blockquote></details>

Sounds good. One small change maybe: are the lazily-initialized fields always initialized together? I.e. do I understand correctly, that the whole inode structure can only be in 2 states: "early-initialized" and fully initialized? In this case, could we move these lazy fields into a separate structure and point to it from some inode field, which would be `NULL` in "early-initialized" state? This way we can be sure that nothing accidentally uses bogus values (like size == -1) for computations.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: 4 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/fs/tmpfs/fs.c` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLjj0X0pVGYyfmkeXu:-NuRRE4QBBYyD1vtjmOh:b133v7g) ([raw file](https://github.com/gramineproject/gramine/blob/274d0eeadeba1b381deb92d8b7f5659c2b634551/libos/src/fs/tmpfs/fs.c#L36)):*
Sounds good to me.

> are the lazily-initialized fields always initialized together?

I suspect not.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: 4 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/tmpfs/fs.c` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLjj0X0pVGYyfmkeXu:-NuUQbuQ-u6fI4zUELMc:b-6c8sex) ([raw file](https://github.com/gramineproject/gramine/blob/274d0eeadeba1b381deb92d8b7f5659c2b634551/libos/src/fs/tmpfs/fs.c#L36)):*
> One small change maybe: are the lazily-initialized fields always initialized together?

Took a look at this -- no, the lazily-initialized fields are **not** initialized together.

So I don't think we could use your idea with a special `NULL` field that is lazily allocated.

I will instead continue with my original idea -- to just write a comment for `struct libos_inode` which fields are early initialized and which are initialized later (on `open()` actually).

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: 0 of 21 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLghYfCBxOln2jjmpY):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Moreover, [...]

You just said exactly that in the previous sentence?
</blockquote></details>

I modified the commit message completely.
___
*[`libos/test/regression/sealed_file.c` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/1779#-NrKsMr1A-ncxuwQUAhh:-NuZGXy4BxwCeKYQeKLu:bgdq47u) ([raw file](https://github.com/gramineproject/gramine/blob/41e17c074ff3a8565a99b1b971e1df931e7b2c14/libos/test/regression/sealed_file.c#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not amazing. I was thinking whether I need to add this `skip_inode_setup = true` to the `access()` system call, but then decided against it. `access()` may legitimately setup the inode, and it will be used afterwards, e.g. in subsequent `open()`. So I kept this rather weird logic in the test.

This also satisfies the customer who found this bug.
</blockquote></details>

This comment is still relevant (other than `skip_inode_setup = true` part).
___
*[`libos/src/fs/tmpfs/fs.c` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLjj0X0pVGYyfmkeXu:-NuZGjng60OdsuHzSKlk:b-pkve1d) ([raw file](https://github.com/gramineproject/gramine/blob/274d0eeadeba1b381deb92d8b7f5659c2b634551/libos/src/fs/tmpfs/fs.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> One small change maybe: are the lazily-initialized fields always initialized together?

Took a look at this -- no, the lazily-initialized fields are **not** initialized together.

So I don't think we could use your idea with a special `NULL` field that is lazily allocated.

I will instead continue with my original idea -- to just write a comment for `struct libos_inode` which fields are early initialized and which are initialized later (on `open()` actually).
</blockquote></details>

Ok, this turned out to be a total mess. 

I made a failed attempt at splitting into early-init and lazy-init parts of the inode. There's too much complexity, as many parts in Gramine's FS rely on the fact that e.g. `inode->size` is initialized immediately at lookup (i.e. at first "notice" of the file).

In particular, I got fed up with `generic_inode_stat()` and decided for a much more contained and pointed approach -- modifying only the Encrypted Files code. I force-pushed since everything is changed in this PR, except for the test.
___
*[`libos/test/regression/tmp_enc/mrenclaves/.dummy` line  at r2](https://reviewable.io/reviews/gramineproject/gramine/1779#-NsLijrA1JoWFx_imn9W:-NuYRXFpDeWp0wldxqLN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ca3cbd5d24eb5e0ec1fe51995e5954dbbc47061/libos/test/regression/tmp_enc/mrenclaves/.dummy#L)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think I prefer `.gitkeep`, because it says why we need such a file.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1, 1 of 1 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaMrbP16OpAqKYxZ7B):*




_Suggestion:_
```
peculiarity
```
___
*[`libos/src/fs/chroot/encrypted.c` line 163 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaWC8c65krmJAhwDJM:-NuaWC8c65krmJAhwDJN:b-g9l6pk) ([raw file](https://github.com/gramineproject/gramine/blob/97ee80a53cdfa6fbc739521f0e1168b2c58f100d/libos/src/fs/chroot/encrypted.c#L163)):*
> \`unlink\`ing

I'd rather just write `unlinking` or `unlink()-ing`.
___
*[`libos/src/fs/chroot/encrypted.c` line 342 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaX0QAE-JOSqLPnV4K:-NuaX0QAE-JOSqLPnV4L:bp63hjh) ([raw file](https://github.com/gramineproject/gramine/blob/97ee80a53cdfa6fbc739521f0e1168b2c58f100d/libos/src/fs/chroot/encrypted.c#L342)):*
> ```C
>     struct libos_encrypted_file* enc = old->inode->data;
>     if (!enc)
>         return -EACCES;
> ```

`old->inode->lock` and `new_uri` leak here
___
*[`libos/test/regression/sealed_file.c` line 24 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaTiLPELCCK-UBKQf5:-NuaTiLPELCCK-UBKQf6:bnszmuj) ([raw file](https://github.com/gramineproject/gramine/blob/97ee80a53cdfa6fbc739521f0e1168b2c58f100d/libos/test/regression/sealed_file.c#L24)):*
> ```C
>     if (argc != 3)
>         errx(EXIT_FAILURE, "Usage: %s <protected file to create/validate> <unlink?>", argv[0]);
> ```

Please also check that `argv[2]` is either `unlink` or `nounlink` (right now anything equals to `nounlink`)
___
*[`libos/test/regression/sealed_file.c` line 56 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaTA857C2fxd2VF9jO:-NuaTA857C2fxd2VF9jP:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/97ee80a53cdfa6fbc739521f0e1168b2c58f100d/libos/test/regression/sealed_file.c#L56)):*
> ```C
>             err(EXIT_FAILURE, "unlink failed");
> 
>         printf("UNLINK OK");
> ```





_Suggestion:_
```C
puts("UNLINK OK");
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: 19 of 21 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaMrbP16OpAqKYxZ7B):*
Will do at final rebase
___
*[`libos/src/fs/chroot/encrypted.c` line 163 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaWC8c65krmJAhwDJM:-Nuc6UJ69Ml8OORBASgB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/97ee80a53cdfa6fbc739521f0e1168b2c58f100d/libos/src/fs/chroot/encrypted.c#L163)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> \`unlink\`ing

I'd rather just write `unlinking` or `unlink()-ing`.
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/encrypted.c` line 342 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaX0QAE-JOSqLPnV4K:-Nuc6gkOCvS0DJxUQPXK:b-u661y0) ([raw file](https://github.com/gramineproject/gramine/blob/97ee80a53cdfa6fbc739521f0e1168b2c58f100d/libos/src/fs/chroot/encrypted.c#L342)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`old->inode->lock` and `new_uri` leak here
</blockquote></details>

Done, copy-paste fail
___
*[`libos/test/regression/sealed_file.c` line 24 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaTiLPELCCK-UBKQf5:-Nuc7J0o9NBtX18IGQup:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/97ee80a53cdfa6fbc739521f0e1168b2c58f100d/libos/test/regression/sealed_file.c#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also check that `argv[2]` is either `unlink` or `nounlink` (right now anything equals to `nounlink`)
</blockquote></details>

Done.
___
*[`libos/test/regression/sealed_file.c` line 56 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaTA857C2fxd2VF9jO:-Nuc7SwOCQxKdwzB3UiD:b-ow196j) ([raw file](https://github.com/gramineproject/gramine/blob/97ee80a53cdfa6fbc739521f0e1168b2c58f100d/libos/test/regression/sealed_file.c#L56)):*
> ```C
>             err(EXIT_FAILURE, "unlink failed");
> 
>         printf("UNLINK OK");
> ```

Done. And in other places too.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 13 files at r1, 1 of 1 files at r2, 16 of 17 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: all files reviewed, 8 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-20.04-musl please (`tests.test_sgx_sign.test_sign_from_pem_path_with_passphrase` failed, unrelated)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/1779#-NuaMrbP16OpAqKYxZ7B):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do at final rebase
</blockquote></details>

Done.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-20.04-apps please (Jenkins didn't trigger this job)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-20.04-musl please (Jenkins didn't trigger this job)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1779)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
