### PR TITLE
Small fixups after #194

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Just some fixups for things overlooked in #194.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: 1 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/src/arch/x86_64/start.S, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/218#-MoJY9_hDY1SszyPJXo6:-MoJY9_hDY1SszyPJXo7:b-efs8aa) ([raw file](https://github.com/gramineproject/gramine/blob/54550e395cf0c63f7e77eebc68ce87ddec60e08c/LibOS/shim/src/arch/x86_64/start.S#L8)):*
> ```
>  *   16(%rsp)              argv[1]
>  *   ...
>  *   (8*(argc+0))(%rsp)    argv[argc] = NULL
> ```

It was correct, you made off by one :)
___
*[Pal/regression/crt_init/arch/x86_64/user_start.S, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/218#-MoJYIma3tZm1LrkeYzy:-MoJYIma3tZm1LrkeYzz:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/54550e395cf0c63f7e77eebc68ce87ddec60e08c/Pal/regression/crt_init/arch/x86_64/user_start.S#L8)):*
> ```
>  *   16(%rsp)              argv[1]
>  *   ...
>  *   (8*(argc+0))(%rsp)    argv[argc] = NULL
> ```

ditto
___
*[Pal/src/db_rtld.c, line 635 at r1](https://reviewable.io/reviews/gramineproject/gramine/218#-MoJYLDyDmW7EusQjslX:-MoJYLDz5Duj9975vaTC:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/54550e395cf0c63f7e77eebc68ce87ddec60e08c/Pal/src/db_rtld.c#L635)):*
> ```C
>      *   16(%rsp)              argv[1]
>      *   ...
>      *   (8*(argc+0))(%rsp)    argv[argc] = NULL
> ```

ditto

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: 1 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/arch/x86_64/start.S, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/218#-MoJY9_hDY1SszyPJXo6:-MoJ_Zsf8GkQHa5hWCY1:bzcnq6m) ([raw file](https://github.com/gramineproject/gramine/blob/54550e395cf0c63f7e77eebc68ce87ddec60e08c/LibOS/shim/src/arch/x86_64/start.S#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It was correct, you made off by one :)
</blockquote></details>

Oh noes, I got fooled by this `8(%rsp)` vs `(8*(argc+0))(%rsp)`. Can I make this uniform? I.e. `8(%rsp)`, `(8+8)(%rsp)`, ..., `(8+8*(argc+0))(%rsp)`? This way we'd count from the `argv` start.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: 1 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/src/arch/x86_64/start.S, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/218#-MoJY9_hDY1SszyPJXo6:-MoJeGhLDy5FYrNuVU9G:b-f7qnfp) ([raw file](https://github.com/gramineproject/gramine/blob/54550e395cf0c63f7e77eebc68ce87ddec60e08c/LibOS/shim/src/arch/x86_64/start.S#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh noes, I got fooled by this `8(%rsp)` vs `(8*(argc+0))(%rsp)`. Can I make this uniform? I.e. `8(%rsp)`, `(8+8)(%rsp)`, ..., `(8+8*(argc+0))(%rsp)`? This way we'd count from the `argv` start.
</blockquote></details>

Sure. Tho I would rather remove all these ascii arts and just leave the `for deatils see this file`, where we would have C code handling all of these.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: 1 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/arch/x86_64/start.S, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/218#-MoJY9_hDY1SszyPJXo6:-MoKuc4JC3M1Jicr-qEo:bub7b29) ([raw file](https://github.com/gramineproject/gramine/blob/54550e395cf0c63f7e77eebc68ce87ddec60e08c/LibOS/shim/src/arch/x86_64/start.S#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure. Tho I would rather remove all these ascii arts and just leave the `for deatils see this file`, where we would have C code handling all of these.
</blockquote></details>

Ok, check now. As a bonus, I removed AT&T obfuscation from this snippet.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/db_rtld.c, line 635 at r2](https://reviewable.io/reviews/gramineproject/gramine/218#-MoL4HnT0ErFnaqguoqK:-MoL4HnUDEEQDBRyHrKq:b-per0u9) ([raw file](https://github.com/gramineproject/gramine/blob/04db57de58184f5011d345cec42397d0d01804da/Pal/src/db_rtld.c#L635)):*
> ```C
>      *   RSP+8+8*1           argv[1]
>      *   ...
>      *   RSP+8+8*(argc+0)    argv[argc] = NULL
> ```

Now that we are so precise I would do:
```
...
RSP+8+8*(argc)    argv[argc] = NULL
RSP+16+8*(argc+0)    envp[0]
...
```
So that indices match on each line.
___
*[Pal/src/db_rtld.c, line 640 at r2](https://reviewable.io/reviews/gramineproject/gramine/218#-MoL4cYt43RN7IgCk-pQ:-MoL4cYt43RN7IgCk-pR:b-sa6o1h) ([raw file](https://github.com/gramineproject/gramine/blob/04db57de58184f5011d345cec42397d0d01804da/Pal/src/db_rtld.c#L640)):*
> ```C
>      *   ...
>      *   RSP+8+8*(argc+n+1)  envp[n] = NULL
>      *   RSP+8+8*(argc+n+2)  auxv[0] = AT_NULL
> ```

And here I would do `RSP+16+8*(argc+n+1)  auxv[0] = AT_NULL` or even `RSP+16+8*(argc+n)+8  auxv[0] = AT_NULL`

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/db_rtld.c, line 635 at r2](https://reviewable.io/reviews/gramineproject/gramine/218#-MoL4HnT0ErFnaqguoqK:-MoLP0xxAbrNsg4wUBU3:buje4ef) ([raw file](https://github.com/gramineproject/gramine/blob/04db57de58184f5011d345cec42397d0d01804da/Pal/src/db_rtld.c#L635)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now that we are so precise I would do:
```
...
RSP+8+8*(argc)    argv[argc] = NULL
RSP+16+8*(argc+0)    envp[0]
...
```
So that indices match on each line.
</blockquote></details>

But then the order of offsets is shuffled, you first would add all the offsets together and then argc and index separately...
If you want another version then I can just split it into arg and env calculations (`RSP+8+8*argc+8+8*i`), but it gets quite long this way.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/db_rtld.c, line 635 at r2](https://reviewable.io/reviews/gramineproject/gramine/218#-MoL4HnT0ErFnaqguoqK:-MoL_cx19KRWDUNirJ4m:b3gaz58) ([raw file](https://github.com/gramineproject/gramine/blob/04db57de58184f5011d345cec42397d0d01804da/Pal/src/db_rtld.c#L635)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But then the order of offsets is shuffled, you first would add all the offsets together and then argc and index separately...
If you want another version then I can just split it into arg and env calculations (`RSP+8+8*argc+8+8*i`), but it gets quite long this way.
</blockquote></details>

The current version makes no sense to me: we split initial `8` for argc, but still count argv and envp together and as result you have `RSP+8+8*(argc+2)    envp[1]` (`+2` vs `[1]`).
Also this line `RSP+8+8*(argc+0)    argv[argc] = NULL` - what is `0` suppose to be? This is last/terminating element of argv.
TBH this is more confusing to me than the original version we had.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/db_rtld.c, line 635 at r2](https://reviewable.io/reviews/gramineproject/gramine/218#-MoL4HnT0ErFnaqguoqK:-MoXtP9_8Zi7FJsHfyFR:b7f3nhe) ([raw file](https://github.com/gramineproject/gramine/blob/04db57de58184f5011d345cec42397d0d01804da/Pal/src/db_rtld.c#L635)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The current version makes no sense to me: we split initial `8` for argc, but still count argv and envp together and as result you have `RSP+8+8*(argc+2)    envp[1]` (`+2` vs `[1]`).
Also this line `RSP+8+8*(argc+0)    argv[argc] = NULL` - what is `0` suppose to be? This is last/terminating element of argv.
TBH this is more confusing to me than the original version we had.
</blockquote></details>

I agree with Borys that the current transition from argv to envp is weird. I like Michal's suggestion to be very verbose. So I would change to this:
```
     *
     *   RSP + 0                          argc
     *   RSP + 8+8*0                      argv[0]
     *   RSP + 8+8*1                      argv[1]
     *   ...
     *   RSP + 8+8*(argc)                 argv[argc] = NULL
     *   RSP + 8+8*(argc) + 8+8*0         envp[0]
     *   RSP + 8+8*(argc) + 8+8*1         envp[1]
     *   ...
     *   RSP + 8+8*(argc) + 8+8*n         envp[n] = NULL
     *   RSP + 8+8*(argc) + 8+8*n + 8     auxv[0] = AT_NULL
```

This may  be verbose but very clear.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/db_rtld.c, line 635 at r2](https://reviewable.io/reviews/gramineproject/gramine/218#-MoL4HnT0ErFnaqguoqK:-MoYcST09ej-8orj6EYg:breil3j) ([raw file](https://github.com/gramineproject/gramine/blob/04db57de58184f5011d345cec42397d0d01804da/Pal/src/db_rtld.c#L635)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Borys that the current transition from argv to envp is weird. I like Michal's suggestion to be very verbose. So I would change to this:
```
     *
     *   RSP + 0                          argc
     *   RSP + 8+8*0                      argv[0]
     *   RSP + 8+8*1                      argv[1]
     *   ...
     *   RSP + 8+8*(argc)                 argv[argc] = NULL
     *   RSP + 8+8*(argc) + 8+8*0         envp[0]
     *   RSP + 8+8*(argc) + 8+8*1         envp[1]
     *   ...
     *   RSP + 8+8*(argc) + 8+8*n         envp[n] = NULL
     *   RSP + 8+8*(argc) + 8+8*n + 8     auxv[0] = AT_NULL
```

This may  be verbose but very clear.
</blockquote></details>

+1 to @dimakuv proposal

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/db_rtld.c, line 635 at r2](https://reviewable.io/reviews/gramineproject/gramine/218#-MoL4HnT0ErFnaqguoqK:-MoZMUsv1YhqB4A7PhQ4:bwq6kp6) ([raw file](https://github.com/gramineproject/gramine/blob/04db57de58184f5011d345cec42397d0d01804da/Pal/src/db_rtld.c#L635)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1 to @dimakuv proposal
</blockquote></details>

I also like Dima's version, changed!

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/218)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`apps.LTP.fdatasync01` timed out, weird but unrelated)

**Pull request merged**
