### PR TITLE
[LibOS] Move procfs cpuinfo display code into functions

### PR DESCRIPTION
**Pull request by stefanberger**
Move the code for generating the output of /proc/cpuinfo so that it
is easier to adapt it to other architectures.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)

### CODE REVIEW

**Review by stefanberger — COMMENTED** [review]
I have left ppc64 code in there to show where that 'tail' function is coming from.
Now where should we put the architecture-specifc code? Just into an architecture-specific file like info-x86_64.c or should there be a directory as well like x86_64/info.c ?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N2vcGs1D7E7zp2lpZ9U:b1q61fz)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by mkow — COMMENTED** [review]
I'd rather keep ppc64-specific code out of our repo until we decide that we officially support ppc64 (and add proper tests to CI, etc) and instead place a short comment explaining that this output differs depending on architecture.

Ad directory vs ifdef: No strong preference from my side. @dimakuv, @boryspoplawski, @pwmarcz: What do you think?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N2xAUx67czz51E_n-oa:b-4f11my)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by stefanberger — COMMENTED** [review]
Yes, I will remove the ppc64 code from this PR.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N2xD-07COlmapdZhkCg:b-35p7re)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by boryspoplawski — COMMENTED** [review]
I definitely prefer directory, like `arch/{x86_64,ppc64}/something.c`, unless the contents are very small and it's an overkill.
Ad this PR: is content of `/proc/cpu*` similar in any ways between archs? Maybe we should have completely different versions? How does Linux do it?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N2xQw8b3DCrvYEioQ6T:b-3g3u1e)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by stefanberger — COMMENTED** [review]
Linux has per-architecture implementations: https://elixir.bootlin.com/linux/latest/C/ident/cpuinfo_op

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N2xVaCY7qBnDLJqAJBz:b-i3n62i)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by stefanberger — COMMENTED** [review]
So what do you suggest for the few archs Gramine may support? Split it up as suggested in this patch or move the whole implementation of the function into its own file?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N2xYWkI1yPseRqMxWZj:boitrnt)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by boryspoplawski — COMMENTED** [review]
I'd suggest a file for each arch, not sure tho for which function (`proc_cpuinfo_load` or per cpu + tail)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N2y0FUX0JUIZU1WKT7K:bvmch7d)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: 0 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`LibOS/shim/include/shim_proc.h` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/607#-N30aVTA9cMrp95eLTAM:-N30oHlL-8tf06l6cXu9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/73c68cb8adb0fab70b795a6e46e692adeb53f061/LibOS/shim/include/shim_proc.h#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would rename this file to something more descriptive, e.g. `shim_fs_proc.h`
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_proc.h` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/607#-N30_h5S1yqdEOmVukzX:-N30oIA18FfMhf5JQ56T:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/73c68cb8adb0fab70b795a6e46e692adeb53f061/LibOS/shim/include/shim_proc.h#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nitpick: please move `*/` to a new line
</blockquote></details>

Done.
___
*[`LibOS/shim/src/meson.build` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/607#-N30ak4jEx1bhIb2OPmi:-N30pq6ADP4Vj-jIhwvi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/73c68cb8adb0fab70b795a6e46e692adeb53f061/LibOS/shim/src/meson.build#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Let's not multiply `arch` directories. Please move it to `LibOS/shim/src/arch/`. This will require this file to be renamed though, I propose: `fs_proc/info.c` (to keep in similar to the old version)
</blockquote></details>

Done.
___
*[`LibOS/shim/src/fs/proc/arch/x86_64/info.c` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/607#-N30_zdj5owS8cnNHRa2:-N30pqdu6Meu7tYQ8uEl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/73c68cb8adb0fab70b795a6e46e692adeb53f061/LibOS/shim/src/fs/proc/arch/x86_64/info.c#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[`LibOS/shim/src/arch/x86_64/meson.build` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30qmLo7kARBAUUFC4I:-N30qmLo7kARBAUUFC4J:b-cxgwl5) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/meson.build#L8)):*
> ```Meson
>     'start.S': {},
>     'syscallas.S': {},
>     'fs_proc/info.c': {},
> ```

NP: please sort.
___
*[`LibOS/shim/src/arch/x86_64/fs_proc/info.c` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30scwmAVQNyGleAkiI:-N30scwmAVQNyGleAkiJ:bghxr81) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/fs_proc/info.c#L6)):*
> ```C
>  */
> 
> #include <stddef.h>
> ```

Why do we need this?
___
*[`LibOS/shim/src/arch/x86_64/fs_proc/info.c` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30si0Q7YQa5e99gw2_:-N30si0Q7YQa5e99gw2a:bghxr81) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/fs_proc/info.c#L8)):*
> ```C
> #include <stddef.h>
> 
> #include "pal.h"
> ```

Why do we need this?
___
*[`LibOS/shim/src/arch/x86_64/fs_proc/info.c` line 9 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30srpW8CjlmdypyhDl:-N30srpW8CjlmdypyhDm:b6ptpum) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/fs_proc/info.c#L9)):*
> ```C
> 
> #include "pal.h"
> #include "shim_fs_proc.h"
> ```

Please include `api.h` for `__UNUSED` and `free()`
___
*[`LibOS/shim/src/arch/x86_64/fs_proc/info.c` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30tCsb3Gudio7ggNE9:-N30tCsb3Gudio7ggNEA:b-ubanvw) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/fs_proc/info.c#L15)):*
> ```C
>         int ret = print_to_str(str, *size, max, fmt, ##__VA_ARGS__);  \
>         if (ret < 0) {                                                \
>             free(str);                                                \
> ```

Now it makes little sense to have this `free()` here. Please move it to the common function.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @stefanberger)

___
*[`LibOS/shim/src/arch/x86_64/fs_proc/info.c` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30scwmAVQNyGleAkiI:-N31JKOP3XAt6vagIGoI:b-3p83lh) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/fs_proc/info.c#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this?
</blockquote></details>

Had added it for `size_t`'

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/arch/x86_64/meson.build` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30qmLo7kARBAUUFC4I:-N34TAb72NMs05zj3hhA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/meson.build#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: please sort.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/arch/x86_64/fs_proc/info.c` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30si0Q7YQa5e99gw2_:-N31IwTQ7JN0WlXgP3hM:bs5c2hg) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/fs_proc/info.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this?
</blockquote></details>

```
In file included from ../LibOS/shim/src/arch/x86_64/fs_proc/info.c:7:0:
../LibOS/shim/include/shim_fs_proc.h:15:37: warning: ‘struct pal_cpu_thread_info’ declared inside parameter list will not be visible outside of this definition or declaration
                              struct pal_cpu_thread_info* thread);
                                     ^~~~~~~~~~~~~~~~~~~
```
___
*[`LibOS/shim/src/arch/x86_64/fs_proc/info.c` line 9 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30srpW8CjlmdypyhDl:-N34T_3454ZGhcB2YpVr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/fs_proc/info.c#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please include `api.h` for `__UNUSED` and `free()`
</blockquote></details>

Done.
___
*[`LibOS/shim/src/arch/x86_64/fs_proc/info.c` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/607#-N30tCsb3Gudio7ggNE9:-N34T_a_CUvS4l_8gbNE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3ff9fe15b1bd78b0ab4f9a2b123a87a367feaf47/LibOS/shim/src/arch/x86_64/fs_proc/info.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now it makes little sense to have this `free()` here. Please move it to the common function.
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by stefanberger — COMMENTED** [review]
I see that tests are failing. Can someone please let me know which ones are failing.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N3560_m1tJ6CzR0ncJX:b-udblrd)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — COMMENTED** [review]
`proc` and `cpuinfo` from LibOS/regression
Do you have any x86 machine to test these? (no need for sgx)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N357D2h0PzhuQUTMRMS:b7y4mlm)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by stefanberger — COMMENTED** [review]
Fixed it.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607#-:-N357WvY8cNMc3aB-Cb-:b-ybz948)* status: 4 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[`LibOS/shim/src/fs/proc/info.c` line 158 at r5](https://reviewable.io/reviews/gramineproject/gramine/607#-N35Gb_g5U8qa51cYE8J:-N35Gb_g5U8qa51cYE8K:bc1xrnj) ([raw file](https://github.com/gramineproject/gramine/blob/48f37f002cd909edf696b26650bf5a082345c962/LibOS/shim/src/fs/proc/info.c#L158)):*
> ```C
> 
> exit:
>     if (ret) {
> ```

Actually, could you change it (here and in all above) to `ret < 0`? We usually do it this way (some functions return `>= 0` on success, this is not the case here, but let's stick to the convention).

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/fs/proc/info.c` line 158 at r5](https://reviewable.io/reviews/gramineproject/gramine/607#-N35Gb_g5U8qa51cYE8J:-N365ft9ApwU6kWk8cjC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48f37f002cd909edf696b26650bf5a082345c962/LibOS/shim/src/fs/proc/info.c#L158)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, could you change it (here and in all above) to `ret < 0`? We usually do it this way (some functions return `>= 0` on success, this is not the case here, but let's stick to the convention).
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 5 files at r3, 2 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 5 files at r3, 2 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/607)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
