### PR TITLE
Misc removals of legacy stuff

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

See commit messages.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/743)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/743)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/743#-N6i1BHX7FGk1vxOmmnO):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I thought about it, but couldn't find a good wording which doesn't require writing a long essay explaining what I mean by "removing make stuff", so I just kept it this way.
</blockquote></details>

Yeah, I don't have a good idea either. Or maybe `[Make] Remove last remnants of building Gramine with Make`? Just to make it clear we talk about main component, not some docs, tools or whatnot.
Unblocking anyway.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/743)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/743#-N6i1BHX7FGk1vxOmmnO):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, I don't have a good idea either. Or maybe `[Make] Remove last remnants of building Gramine with Make`? Just to make it clear we talk about main component, not some docs, tools or whatnot.
Unblocking anyway.
</blockquote></details>

Ok, I can change it when rebasing.

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 8 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/743)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/743#-N6i1BHX7FGk1vxOmmnO):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, I can change it when rebasing.
</blockquote></details>

+1 to Borys's suggestion

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/743)* status: 5 of 16 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/743#-N6i1BHX7FGk1vxOmmnO):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Borys's suggestion
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 11 of 11 files at r4, 8 of 8 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/743)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 8 of 8 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/743)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
