### PR TITLE
[Docs] Describe AESM in sgx-intro

### PR DESCRIPTION
**Pull request by NieDzejkob**
Also fix the formatting of the "See also" section of "Architectural Enclaves".

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/472)

### CODE REVIEW

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/472)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[Documentation/sgx-intro.rst, line 209 at r1](https://reviewable.io/reviews/gramineproject/gramine/472#-MyxN6VU6Cymq5KdXlYK:-MyxN6VU6Cymq5KdXlYL:bzhrx9o) ([raw file](https://github.com/gramineproject/gramine/blob/bce754e212e9f399eb4d064b186e949cf5a3643e/Documentation/sgx-intro.rst#L209)):*
> ```reStructuredText
> 
>       The Architectural Enclave Service Manager is responsible for providing SGX
>       applications with access to the :term:`Architectural Enclaves`. It consists
> ```

"with access" -> can you describe that `aesmd` actually hosts the enclaves?
___
*[Documentation/sgx-intro.rst, line 212 at r1](https://reviewable.io/reviews/gramineproject/gramine/472#-MyxNELv6fIQMu4hWYRA:-MyxNELwAr8ceurwbjXN:b-js5p0d) ([raw file](https://github.com/gramineproject/gramine/blob/bce754e212e9f399eb4d064b186e949cf5a3643e/Documentation/sgx-intro.rst#L212)):*
> ```reStructuredText
>       of the Architectural Enclave Service Manager Daemon and a component of the
>       SGX SDK, which communicate over a Unix socket with the fixed path
>       ``/var/run/aesmd/aesm.sock``.
> ```

```suggestion
:file:`/var/run/aesmd/aesmd.sock`.
```

**Review by NieDzejkob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/472)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Documentation/sgx-intro.rst, line 209 at r1](https://reviewable.io/reviews/gramineproject/gramine/472#-MyxN6VU6Cymq5KdXlYK:-Mz-x8sI-4R0x3YVqQLR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bce754e212e9f399eb4d064b186e949cf5a3643e/Documentation/sgx-intro.rst#L209)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

"with access" -> can you describe that `aesmd` actually hosts the enclaves?
</blockquote></details>

Done.
___
*[Documentation/sgx-intro.rst, line 212 at r1](https://reviewable.io/reviews/gramineproject/gramine/472#-MyxNELv6fIQMu4hWYRA:-Mz-x6X417qzAwn3Us0i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bce754e212e9f399eb4d064b186e949cf5a3643e/Documentation/sgx-intro.rst#L212)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

```suggestion
:file:`/var/run/aesmd/aesmd.sock`.
```
</blockquote></details>

Done.

**Review by woju — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/472)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> I've noticed that I had forgotten to signoff on the fixup commits, force-pushed to fix that.

Thanks, it's nice to do (it makes the DCO bot happier) but not required, we'll squash the fixups anyways after merging.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/472#-:-MzLCAdg2_zn_mIV0yjj:b-k2ie1j)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/472)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by pwmarcz** [comment]
Jenkins, retest this please

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/472)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/472)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
