### PR TITLE
[Docs,LibOS] Update `Graphene` to `Gramine` in SVG and comments

### PR DESCRIPTION
**Pull request by billionairiam**
## Description of the changes 
Update documentation to reflect name change from Graphene to Gramine

Some files, such as[ marblerun.svg](https://github.com/gramineproject/gramine/blob/master/Documentation/img/marblerun.svg) and [libos_fs_util.c](https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/libos/src/fs/libos_fs_util.c#L80), still contain references to Graphene, the former name of the project. This commit replaces Graphene with Gramine in the documentation and code comments to avoid confusion and inconsistency.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)

### CODE REVIEW

**Review by llly — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1747#-NprTRDO8yq4PPuT9NiU):*
-> `[Docs,LibOS] Update "Graphene" to "Gramine" in SVG and comments`

“rename” sounds a bit misleading to me



_Code quote:_
```
[Docs & libos] Rename Graphene to Gramine in documentation and code  comments
```

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1747#-NprTRDO8yq4PPuT9NiU):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `[Docs,LibOS] Update "Graphene" to "Gramine" in SVG and comments`

“rename” sounds a bit misleading to me
</blockquote></details>

+1 to @kailun-qin's proposed text. We can do it at final rebase.

**Review by billionairiam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1747#-NprTRDO8yq4PPuT9NiU):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to @kailun-qin's proposed text. We can do it at final rebase.
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @billionairiam)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1747#-Npuh59jCtcO-xMHtWmQ):*
@billionairiam Please add the Signed-off-by line

**Review by billionairiam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1747#-Npuh59jCtcO-xMHtWmQ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@billionairiam Please add the Signed-off-by line
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @billionairiam)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1747#-Npuh59jCtcO-xMHtWmQ):*
<details><summary><i>Previously, billionairiam (Liang Ma) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@billionairiam Sorry, you used a wrong format of Lastname-Firstname. Our DCO plugin expects this:
```
Expected "Liang Ma liang3.ma@intel.com", but got "Ma, Liang liang3.ma@intel.com".
```

So please fix your line to:
```
Signed-off-by: Liang Ma <liang3.ma@intel.com>
```

**Review by billionairiam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1747#-Npuh59jCtcO-xMHtWmQ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@billionairiam Sorry, you used a wrong format of Lastname-Firstname. Our DCO plugin expects this:
```
Expected "Liang Ma liang3.ma@intel.com", but got "Ma, Liang liang3.ma@intel.com".
```

So please fix your line to:
```
Signed-off-by: Liang Ma <liang3.ma@intel.com>
```
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1747#-NqtQ3QLE6JjktEEjf4e:-NqtQ3QMC2LoY3plf4wt:bvt3lbp) (no related file):*
@billionairiam: Please create PRs from branches in `<your-nick>/<change-descr>` format and especially not from `master`, even if it's from your private repo - this makes it harder for us to pull and rebase it.
See https://gramine.readthedocs.io/en/latest/devel/contributing.html#branch-names.

___

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
