### PR TITLE
README.md: Fix performance tuning link

### PR DESCRIPTION
**Pull request by psfoley**
This PR:
- Fixes a broken link in the README

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1229)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
Thanks! Seems this document isn't that popular, as nobody reported this bug for quite some time since we moved this doc page...

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1229#-:-NQS27aQ0pxkqT95wQLk:b-3cp6xw)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @psfoley)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1229#-NQS1g847iiNdGMoMv1-):*
Please update the commit message and just force-push this commit.



_Suggestion:_
```
[Docs] Fix performance tuning link in README.rst
```

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1229)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1229)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1229)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
