### PR TITLE
[Docs,docker] Drop official support for Ubuntu 20.04

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Gramine 1.8 was the last release supporting Ubuntu 20.04.

## How to test this PR? 

No functional changes intended, except the dockerfiles (@oshogbo: plz test).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)

### CODE REVIEW

**Review by kailun-qin — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAp4BXkD5aGTWAvkF-F:-OAp4BXkD5aGTWAvkF-G:bhpgl7) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/Documentation/tutorials/pytorch/index.rst#L8)):*
> ```reStructuredText
>    This tutorial is outdated and may not work on the current Gramine version /
>    currently supported Linux distributions. Contributions to refresh it are
>    welcomed!
> ```

Not blocking but it's kind of weird that we state at the same time that: [https://github.com/gramineproject/gramine/blob/93be2c23164f89def3afdc3d049bf6dd3e872401/Documentation/tutorials/pytorch/index.rst#L85-L97)](https://github.com/gramineproject/gramine/blob/93be2c23164f89def3afdc3d049bf6dd3e872401/Documentation/tutorials/pytorch/index.rst#L88-L89. Maybe we can just remove the "should work" and "for simplicity we ..." there.

Can we create an issue so that we won't forget / contributors can easily notice?

BTW, one probably won't validate this tutorial on all currently supported Linux distros in the future (most likely only latest Gramine + latest Ubuntu distro). So we need always keep this warning?



_Code quote:_
```reStructuredText
.. warning::

   This tutorial is outdated and may not work on the current Gramine version /
   currently supported Linux distributions. Contributions to refresh it are
   welcomed!
```

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAp8WV07P-UYQ0XtjMp:-OAp8WV07P-UYQ0XtjMq:b-3swk0k) (no related file):*
What about https://github.com/gramineproject/gramine/blob/93be2c23164f89def3afdc3d049bf6dd3e872401/python/graminelibos/sgx_sign.py#L29-L31? Do we plan to remove it in a separate PR?

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAp8WV07P-UYQ0XtjMp:-OAr5XoT0xP3BR3baM_k:bqiihcd) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about https://github.com/gramineproject/gramine/blob/93be2c23164f89def3afdc3d049bf6dd3e872401/python/graminelibos/sgx_sign.py#L29-L31? Do we plan to remove it in a separate PR?
</blockquote></details>

Yes, look at the branch name :)
I didn't want to mix too many different changes in a single PR, especially that it may turn out that we can't drop all the hacks for some reason.

___
___
*[`Documentation/tutorials/pytorch/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAp4BXkD5aGTWAvkF-F:-OAr5s9wAQobDdcAzy-P:b-hge719) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/Documentation/tutorials/pytorch/index.rst#L8)):*
> Maybe we can just remove the "should work" and "for simplicity we ..." there.

You mean removing that whole paragraph?

> Can we create an issue so that we won't forget / contributors can easily notice?

Hmm, we could, but it would need to be re-created quite often, so I don't know if it makes sense, it would generate a lot of noise... And I'm not sure if anyone cares about this tutorial, the last update was a year and a half ago.

**Review by monavij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAp4BXkD5aGTWAvkF-F:-OArq2vzAnfLHSJJuotd:baeifyu) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/Documentation/tutorials/pytorch/index.rst#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Maybe we can just remove the "should work" and "for simplicity we ..." there.

You mean removing that whole paragraph?

> Can we create an issue so that we won't forget / contributors can easily notice?

Hmm, we could, but it would need to be re-created quite often, so I don't know if it makes sense, it would generate a lot of noise... And I'm not sure if anyone cares about this tutorial, the last update was a year and a half ago.
</blockquote></details>

No this is an important tutorial that showcases end to end deployment of Gramine with encrypted files and attestation. We need to fix this tutorial and add to the priority list

**Review by kailun-qin — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow and @monavij)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAp8WV07P-UYQ0XtjMp:-OAu2i4a2ZJTEDRlIXDg:bkf6n0q) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, look at the branch name :)
I didn't want to mix too many different changes in a single PR, especially that it may turn out that we can't drop all the hacks for some reason.
</blockquote></details>

Sure, thanks!

___
___
*[`Documentation/tutorials/pytorch/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAp4BXkD5aGTWAvkF-F:-OAu2s-o13Y02uZATl91:b-16grbi) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/Documentation/tutorials/pytorch/index.rst#L8)):*
> You mean removing that whole paragraph?

Yes, I would only keep "- Ubuntu 20.04." as the prerequisite when this tutorial was tested (+ this warning).

> but it would need to be re-created quite often, so I don't know if it makes sense, it would generate a lot of noise...

Yeah. I would at least test it (w/ Gramine v1.8 + Ubuntu 24.04) and fix where needed in the coming weeks anyway.

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow and @monavij)

___
*[`Documentation/devel/building.rst` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAvgkQH7fYVpoXJI_0K:-OAvgkQH7fYVpoXJI_0L:b-ml1pna) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/Documentation/devel/building.rst#L19)):*
> ```reStructuredText
> 
> Gramine currently only works on the x86_64 architecture. Gramine is currently
> tested on Ubuntu 22.04/24.04, along with Linux kernel version 5.x. We recommend
> ```

Please keep descending order, here and everywhere else. If some one lacks attention span to read two version numbers, the bigger (newer) number should be read.



_Suggestion:_
```reStructuredText
24.04/22.04
```
___
*[`packaging/docker/build.sh` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAvh5ZpEtvx0SPyy7Yi:-OAvh5ZpEtvx0SPyy7Yj:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/packaging/docker/build.sh#L4)):*
> ```Shell
> 
> usage() {
>     echo "Usage: build.sh [ubuntu20,ubuntu22,ubuntu24]"
> ```





_Suggestion:_
```Shell
ubuntu20,ubuntu22
```
___
*[`packaging/docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAvhJaH5BWszdlEUQHK:-OAvhJaH5BWszdlEUQHL:btil30e) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/packaging/docker/Dockerfile#L1)):*
> ```Dockerfile
> ARG UBUNTU_IMAGE=ubuntu:24.04
> ```

This stuff I'd like to be explicitly confirmed by @oshogbo.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: 3 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`Documentation/devel/building.rst` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAvgkQH7fYVpoXJI_0K:-OAw_HL-7uYkZk9UVzyJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/Documentation/devel/building.rst#L19)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please keep descending order, here and everywhere else. If some one lacks attention span to read two version numbers, the bigger (newer) number should be read.
</blockquote></details>

Done.
___
*[`Documentation/tutorials/pytorch/index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAp4BXkD5aGTWAvkF-F:-OAw_Tg7BnrurRIuvgeX:bdhbnew) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/Documentation/tutorials/pytorch/index.rst#L8)):*
> Yes, I would only keep "- Ubuntu 20.04." as the prerequisite when this tutorial was tested (+ this warning).

Done.
___
*[`packaging/docker/build.sh` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAvh5ZpEtvx0SPyy7Yi:-OAwkVucAtBcVaJ52wu5:b-3biko9) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/packaging/docker/build.sh#L4)):*
> ```Shell
> 
> usage() {
>     echo "Usage: build.sh [ubuntu20,ubuntu22,ubuntu24]"
> ```

good find, thanks! (except that it should be 20 to be deleted, not 24 ;) )
___
*[`packaging/docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAvhJaH5BWszdlEUQHK:-OAwkkhR9wP3BqMmQmvW:bnk2u4t) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/packaging/docker/Dockerfile#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This stuff I'd like to be explicitly confirmed by @oshogbo.
</blockquote></details>

FYI: This is just the default value for the argument (now it matches the newest one in `build.sh`).

**Review by woju — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`packaging/docker/build.sh` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2051#-OAvh5ZpEtvx0SPyy7Yi:-OAwwyGZ8cEjeYoDF3gI:b32vhw) ([raw file](https://github.com/gramineproject/gramine/blob/bf256cf3b71d371f7a625e243c4be2f1d1b9ed6c/packaging/docker/build.sh#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

good find, thanks! (except that it should be 20 to be deleted, not 24 ;) )
</blockquote></details>

:)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2051)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Direct-24.04 please (`fdatasync01` from LTP timed out, known and unrelated to the PR)

**Pull request merged**
