### PR TITLE
[LibOS] Move Linux ABI headers to a separate directory (part 1)

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

This PR starts a series of changes which aim at decoupling our LibOS from the headers of the system where it's being built. This dependency never actually made sense - we are a program emulating a specific Linux ABI, so it doesn't make sense to pull its definitions from the host where the external part of Gramine runs/is built on (because theoretically it could be even Windows).

This PR is only the first step, I plan to introduce next changes in steps to minimize conflicts with other PRs. The plan is:
- Move the rest of Linux ABI structs into `linux_abi/`.
- Stop using `__kernel_` prefix, it's a reversed name in C.
- Define all structures inside Gramine headers and remove all system includes from LibOS.

If you disagree with some parts of this plan then better to say it now, before I make more changes :)

## How to test this PR? 

No functional changes intended.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1275)

### CODE REVIEW

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1275)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`libos/include/linux_abi/types.h` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSdzqx9EndExt14EIWD:-NSdzqx9EndExt14EIWE:b-1nwdaj) ([raw file](https://github.com/gramineproject/gramine/blob/9a435bb7cd40cbe59414de77d55d0d7d72e65adb/libos/include/linux_abi/types.h#L40)):*
> ```objc
> typedef __kernel_fd_set    fd_set;
> 
> /* /arch/x86/include/asm/posix_types_64.h */
> ```

Do we still want to keep this? Besides, Linux actually switched to use generic posix_types.h: https://elixir.bootlin.com/linux/v6.2/source/include/uapi/asm-generic/posix_types.h#L37 long ago.



_Code quote:_
```objc
/arch/x86/include/asm/posix_types_64.h
```

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1275)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/include/linux_abi/types.h` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSdzqx9EndExt14EIWD:-NSfWgYn6qnuPaC0gLyM:bija6bx) ([raw file](https://github.com/gramineproject/gramine/blob/9a435bb7cd40cbe59414de77d55d0d7d72e65adb/libos/include/linux_abi/types.h#L40)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do we still want to keep this? Besides, Linux actually switched to use generic posix_types.h: https://elixir.bootlin.com/linux/v6.2/source/include/uapi/asm-generic/posix_types.h#L37 long ago.
</blockquote></details>

Fixed.
FYI: I'm planning to go over all these typedefs and defines and clean them up, in this (and next) PR I'm mostly just shuffling things around.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1275)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/include/libos_types.h` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjQ-Pe-tsBxU2OG8Hg:-NSjQ-Pe-tsBxU2OG8Hh:bu018mi) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/libos_types.h#L21)):*
> ```objc
> 
> typedef unsigned long int nfds_t;
> typedef unsigned long int nlink_t;
> ```

What is the logic by which you move the types/macros/etc in this PR? Is it like this: (a) create an analogue of e.g. `linux/time.h`, (b) check what structs/types/macros are defined in the corresponding Linux header(s), and (c) move to this new file only these structs/types/macros?
___
*[`libos/include/libos_types.h` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjQsDj2QL-WsMOe9M5:-NSjQsDj2QL-WsMOe9M6:bzag78p) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/libos_types.h#L21)):*
> ```objc
> 
> typedef unsigned long int nfds_t;
> typedef unsigned long int nlink_t;
> ```

Are these two not defined in Linux headers anywhere?
___
*[`libos/include/libos_types.h` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjQv_43bpFTQIkWDd2:-NSjQv_43bpFTQIkWDd3:b-k6yqko) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/libos_types.h#L33)):*
> ```objc
> 
> #define PID_MAX_LIMIT 4194304 /* Linux limit 2^22, this value is *one greater* than max PID */
> #define PID_MAX (PID_MAX_LIMIT - 1)
> ```

These are surely defined in some Linux headers. Why did you keep them here?
___
*[`libos/include/arch/x86_64/linux_abi/signals_arch.h` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjR2aZEfpzcwNrAQWN:-NSjR2a_9WiujdEG804m:b-ft5c0o) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/arch/x86_64/linux_abi/signals_arch.h#L7)):*
> ```objc
> #pragma once
> 
> /* Types and structure used by various Linux ABIs (e.g. syscalls). */
> ```

`structure` -> `structures` (plural)

ditto everywhere
___
*[`libos/include/linux_abi/signals.h` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjRpQGCCfM-ddv5w-l:-NSjRpQGCCfM-ddv5w-m:b-yn2rbi) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/linux_abi/signals.h#L10)):*
> ```objc
> /* These need to be binary-identical with the ones used by Linux. */
> 
> // TODO: remove all of these includes and make this header libc-independent.
> ```

Actually, what does it mean `make this header libc-independent`?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1275)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/include/libos_types.h` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjQsDj2QL-WsMOe9M5:-NSkP2qK4QNhYxdtU03a:b-qezkjt) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/libos_types.h#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd need to clean up `stat` structure first, which I'll do in upcoming PRs (right now stat-related structs and types are partially pulled from glibc headers and partially defined by us, it's a mess).
</blockquote></details>

Ok, fair enough.
___
*[`libos/include/libos_types.h` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjQv_43bpFTQIkWDd2:-NSkPO306YI_jRMK11Nh:bqipcs3) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/libos_types.h#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure if these are actually a part of kernel ABI, it's more like Gramine LibOS internal constants?
</blockquote></details>

https://elixir.bootlin.com/linux/v6.0/source/include/linux/threads.h#L34 -- though it is around 2^30 according to the comment, not 2^22 -- but maybe the comment was written from some older Linux version.

Anyway, should I block on issues like these, or we'll deal with them in next PRs?
___
*[`libos/include/linux_abi/signals.h` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjRpQGCCfM-ddv5w-l:-NSkPs8k9J3KOEB99-Bj:b-ejv4xh) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/linux_abi/signals.h#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think that these includes are partially dependent on libc and on the installed kernel on the host, but I'm not sure how this works exactly. I can reword it if you want, but not sure how exactly.
</blockquote></details>

I think I know what you mean. However, IIUC, all headers that start with `linux/` and `asm/` are libc-independent. Well, whatever, I'm not blocking on this comment anymore.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1275)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/include/libos_types.h` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjQv_43bpFTQIkWDd2:-NSlhUvB7Kmpu9_f16aB:b-r6jyav) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/libos_types.h#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it should stay here. "pid numbers may be limited" is a part of kernel ABI, but these particular defines are just LibOS configuration. This includes the specific value, I don't think it's part of the ABI that it's always 2**30?
</blockquote></details>

Ok, I agree, resolving.
___
*[`libos/include/linux_abi/signals.h` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/1275#-NSjRpQGCCfM-ddv5w-l:-NSlhZAr85HowgHp05wp:b-pbdqz3) ([raw file](https://github.com/gramineproject/gramine/blob/0e3a87cea4ecb589c3650910876663d04d5f0ec6/libos/include/linux_abi/signals.h#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, maybe, but I wouldn't care enough to spend time researching if it's actually independent, because this comment will go away anyways in the next PRs.
</blockquote></details>

Agreed.

**Review by kailun-qin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1275#-:-NSn3e_t4oLGrV1y6tW2:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1275)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
