### PR TITLE
[LibOS] Clean up locking code

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This series of commits removes useless artifacts from locking code.

Commit by commit review advised.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/661)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/661)* status: 1 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/sys/shim_alarm.c` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/661#-N4w_b9JAq2uEcP9TSL2:-N4w_b9JAq2uEcP9TSL3:b-aq01w5) ([raw file](https://github.com/gramineproject/gramine/blob/51958480f06df333300864a24c18d67a308e5c56/LibOS/shim/src/sys/shim_alarm.c#L45)):*
> ```C
> 
> /* TODO: we use `g_process.fs_lock` for concurrent accesses to `real_itimer`. Maybe introduce
>  * a custom lock and init function here? */
> ```

If anybody has strong feelings about this, I can introduce a commit here that fixes it, but I'm not sure how exactly the fix should look like

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 4 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/661)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/shim_async.c` line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/661#-N5-Be1H0h8D7cLfY9Ba:-N5-Be1H0h8D7cLfY9Bb:b52zrmo) ([raw file](https://github.com/gramineproject/gramine/blob/c1283b797a688bcd63fc7f42d8b0a0a511dda8b3/LibOS/shim/src/shim_async.c#L139)):*
> ```C
> 
>     /* enable locking mechanisms since we are going in multi-threaded mode */
>     enable_locking();
> ```

What a super-obscure thing we did here...
___
*[`LibOS/shim/src/shim_init.c` line 381 at r3](https://reviewable.io/reviews/gramineproject/gramine/661#-N5-BqH-7dYC1qupna7S:-N5-BqH-7dYC1qupna7T:b-5pq7zj) ([raw file](https://github.com/gramineproject/gramine/blob/c1283b797a688bcd63fc7f42d8b0a0a511dda8b3/LibOS/shim/src/shim_init.c#L381)):*
> ```C
>     shim_tcb_init();
> 
>     log_setprefix(shim_get_tcb());
> ```

Wait, why is this removed?
___
*[`LibOS/shim/src/shim_init.c` line 423 at r3](https://reviewable.io/reviews/gramineproject/gramine/661#-N5-B99Q6LMldWCVJA6W:-N5-B99Q6LMldWCVJA6X:botu2cf) ([raw file](https://github.com/gramineproject/gramine/blob/f67ee60901b8e024aa6825cae13dc9e40feea346/LibOS/shim/src/shim_init.c#L423)):*
> ```C
>     RUN_INIT(init_ipc);
>     RUN_INIT(init_process, argc, argv);
>     RUN_INIT(init_mount_root);
> ```

Why did you move here?
___
*[`LibOS/shim/src/fs/shim_fs.c` line 46 at r3](https://reviewable.io/reviews/gramineproject/gramine/661#-N5-BS0LDDLN52thZ4rT:-N5-BS0LDDLN52thZ4rU:bw02zoc) ([raw file](https://github.com/gramineproject/gramine/blob/f67ee60901b8e024aa6825cae13dc9e40feea346/LibOS/shim/src/fs/shim_fs.c#L46)):*
> ```C
> #include "memmgr.h"
> 
> static MEM_MGR mount_mgr = NULL;
> ```

Since we're here, can we also prepend all these global vars with `g_`?
___
*[`LibOS/shim/src/ipc/shim_ipc_worker.c` line 407 at r3](https://reviewable.io/reviews/gramineproject/gramine/661#-N5-C8Us9M8hrGcnnh96:-N5-C8Us9M8hrGcnnh97:b-g8gfqd) ([raw file](https://github.com/gramineproject/gramine/blob/c1283b797a688bcd63fc7f42d8b0a0a511dda8b3/LibOS/shim/src/ipc/shim_ipc_worker.c#L407)):*
> ```C
> 
> int init_ipc_worker(void) {
>     enable_locking();
> ```

What a super-obscure thing we did here-2...
___
*[`LibOS/shim/src/sys/shim_alarm.c` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/661#-N4w_b9JAq2uEcP9TSL2:-N5-AVrE7_uLWhtwEBn9:b56kll8) ([raw file](https://github.com/gramineproject/gramine/blob/51958480f06df333300864a24c18d67a308e5c56/LibOS/shim/src/sys/shim_alarm.c#L45)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If anybody has strong feelings about this, I can introduce a commit here that fixes it, but I'm not sure how exactly the fix should look like
</blockquote></details>

Why not introduce a file-local spinlock here? Looking at the code, there is nowhere to be blocked, so a spinlock would work fine.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 414 at r3](https://reviewable.io/reviews/gramineproject/gramine/661#-N5-CI-k87fvAPNGKvR9:-N5-CI-lCTtPnUNbR5-k:b-g8fsqu) ([raw file](https://github.com/gramineproject/gramine/blob/c1283b797a688bcd63fc7f42d8b0a0a511dda8b3/LibOS/shim/src/sys/shim_clone.c#L414)):*
> ```C
>     assert(flags & CLONE_SIGHAND);
> 
>     enable_locking();
> ```

What a super-obscure thing we did here-3...

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/661)* status: 7 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`LibOS/shim/src/shim_init.c` line 381 at r3](https://reviewable.io/reviews/gramineproject/gramine/661#-N5-BqH-7dYC1qupna7S:-N5-QnYX2wrU8rqxE0vJ:b-haf3ia) ([raw file](https://github.com/gramineproject/gramine/blob/c1283b797a688bcd63fc7f42d8b0a0a511dda8b3/LibOS/shim/src/shim_init.c#L381)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, why is this removed?
</blockquote></details>

Because it touches stuff that's not yet initialized. We call this function again after initialization anyway. The difference is that now `[::] ` is omitted in the very early log (but it contained no information, so this shouldn't be an issue).
___
*[`LibOS/shim/src/shim_init.c` line 423 at r3](https://reviewable.io/reviews/gramineproject/gramine/661#-N5-B99Q6LMldWCVJA6W:-N5-RVlk7HpoOROQCAil:b34jhdj) ([raw file](https://github.com/gramineproject/gramine/blob/f67ee60901b8e024aa6825cae13dc9e40feea346/LibOS/shim/src/shim_init.c#L423)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you move here?
</blockquote></details>

Because the two functions above (`init_ipc` and `init_process`) do not need it, but it (`init_mount_root`) does use stuff from `g_process`, which is initialized in `init_process`.
___
*[`LibOS/shim/src/fs/shim_fs.c` line 46 at r3](https://reviewable.io/reviews/gramineproject/gramine/661#-N5-BS0LDDLN52thZ4rT:-N5-RsTC-akScDknGKf6:bb74ce2) ([raw file](https://github.com/gramineproject/gramine/blob/f67ee60901b8e024aa6825cae13dc9e40feea346/LibOS/shim/src/fs/shim_fs.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're here, can we also prepend all these global vars with `g_`?
</blockquote></details>

Sure
___
*[`LibOS/shim/src/sys/shim_alarm.c` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/661#-N4w_b9JAq2uEcP9TSL2:-N5-VNgTD5ngU5XJ4eXR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/51958480f06df333300864a24c18d67a308e5c56/LibOS/shim/src/sys/shim_alarm.c#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not introduce a file-local spinlock here? Looking at the code, there is nowhere to be blocked, so a spinlock would work fine.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/661)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 12 files at r6, 4 of 10 files at r7, 6 of 6 files at r8, 10 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/661)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 4 files at r11, 5 of 6 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/661)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Debug-20.04 please (`fdatasync01` failed, unrelated)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 12 files at r6, 2 of 4 files at r11, 5 of 6 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/661)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
