### PR TITLE
[*] Fix indentation in manifest templates

### PR DESCRIPTION
**Pull request by woju**
Signed-off-by: Wojtek Porczyk <woju@invisiblethingslab.com>

## Description of the changes 

TOML should be indented to 4 spaces like everything else, so we won't have to maintain per-filetype editor config.

## How to test this PR? 

jenkins

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-Mk2kaLc5yUBb5xGi43-:b-2ifcej) (no related file):*
> TOML should be indented to 4 spaces 

Where did you get that from? TOML does not have strict requirements on that, but examples use 2 spaces (and I think it's convenient this way): https://github.com/toml-lang/toml#example

> we won't have to maintain per-filetype editor config.

My editor does not have a problem with it and correctly autoidents in our makefile.template without any specific configs.

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-Mk2nUIy03olNZ9MxMYI:b-ubgzfj) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> TOML should be indented to 4 spaces 

Where did you get that from? TOML does not have strict requirements on that, but examples use 2 spaces (and I think it's convenient this way): https://github.com/toml-lang/toml#example

> we won't have to maintain per-filetype editor config.

My editor does not have a problem with it and correctly autoidents in our makefile.template without any specific configs.
</blockquote></details>

Isn't it obvious that you should have coherent rules about indenting in the whole project?

This doesn't work for example: https://gramine.readthedocs.io/en/latest/devel/setup.html#vim-configuration, you'd need to have a separate rule for `*.manifest.template`.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-Mk2oMKa9U8QGvoRdnjI:b-451ofo) (no related file):*
> Isn't it obvious that you should have coherent rules about indenting in the whole project?

Formatting rules are either per language+project or per language (because some languages have "hardcoded" one, common formatting which should vary between projects - like Go or Rust). The style always depend on the source language, as we already do with reST, C and Meson. And we provide suggested editor configs, so we can easily fix it there.

Overall, I like the 2 space indents in TOML. I won't die on this hill, but I prefer this version.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-Mk2pPZ43xdxYlrqWAdU:bkt7wir) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Isn't it obvious that you should have coherent rules about indenting in the whole project?

Formatting rules are either per language+project or per language (because some languages have "hardcoded" one, common formatting which should vary between projects - like Go or Rust). The style always depend on the source language, as we already do with reST, C and Meson. And we provide suggested editor configs, so we can easily fix it there.

Overall, I like the 2 space indents in TOML. I won't die on this hill, but I prefer this version.
</blockquote></details>

*shouldn't

---

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-Mk2qjYd6wRnA2FtwfU5:bmlpb3u) (no related file):*
> This doesn't work for example: https://gramine.readthedocs.io/en/latest/devel/setup.html#vim-configuration, you'd need to have a separate rule for *.manifest.template.

It does work. I have the same/similar rules set in my vimrc and it does work.

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-Mk2qRa35VHM9oLjkag1:b-ym0clb) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

*shouldn't
</blockquote></details>

Well, C should have a single tab, rendered to 8 spaces, according to K&R and also Linus.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-Mk2rVyLEl75dM-B31PC:b-snl9z1) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Well, C should have a single tab, rendered to 8 spaces, according to K&R and also Linus.
</blockquote></details>

And 2 spaces according to Google. There's no formatting enforced by the standard for neither C nor C++, but there are a few leading/popular styles. Which is different from Rust/Go, where they ship the official auto-formatter with one, standarized syntax. But this is getting a bit off-topic.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-Mk6WQ9f0dg3vznUcsWw:bk724vj) (no related file):*
> Well, C should have a single tab, rendered to 8 spaces, according to K&R and also Linus.

Oh god no. I don't care much about 2-vs-4 spaces in TOML files, but definitely no 8-space tabs in C code.

Generally, I never had problems with our 2-space indentation in our TOML files, moreover, my Vim correctly indents to 2 spaces even without any specific configs.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-Mk7Y73G7ghRZ-EHolej:b45bgz3) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> but definitely no 8-space tabs in C code.

This wasn't a real proposal, it was just aimed at derailing the argument.
</blockquote></details>

:) So anyway, I don't care but for simplicity, I'd just vote for closing this PR and not doing anything.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/73)* status: 0 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/73#-Mk2kaLc5yUBb5xGi42z:-MknxcNrDAOuwxR6Gehe:b-bkhklb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

:) So anyway, I don't care but for simplicity, I'd just vote for closing this PR and not doing anything.
</blockquote></details>

Ok, seems that most of maintainers prefer the current formatting, so I'm closing this.

---

**Pull request closed without merging**
