### PR TITLE
[CI] Enable RWX verification for all binaries

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Ensure that none of the binaries we distribute contain an RWX segment.

## How to test this PR? 

CI is sufficient.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1698)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1698)* status: 0 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1698#-NnKpxHgDI9MpGYdy0Em:-NnKpxHh52FU0F2c8la2:bjkrezy) (no related file):*
Interesting PR. Why did you implement it? Any particular issue you noticed?

___

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1698)* status: 0 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1698#-NnKpxHgDI9MpGYdy0Em:-NnKyeBz973O18SrUf1A:bywm04t) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interesting PR. Why did you implement it? Any particular issue you noticed?
</blockquote></details>

Actually, it was @mkow's idea as a follow-up to the original one.
I have not seen any other issue.
It is just a seatbelt to ensure we don't ship any libs/execs with RWX.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1698)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @oshogbo)

___
*[`.ci/lib/stage-test-direct.jenkinsfile` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1698#-NnNB6ynBsAfyyI3rGVd:-NnNB6ynBsAfyyI3rGVe:b-863ifz) ([raw file](https://github.com/gramineproject/gramine/blob/1f72aaf8148a7712c5c8bad1da9839e2bcc5c633/.ci/lib/stage-test-direct.jenkinsfile#L6)):*
> ```
>             grep ELF | \
>             cut -d':' -f1 | \
>             xargs -L1 .ci/check-rwx.py
> ```

I don't really care (in CI) -- but do we want to exit on the first failure of file check?



_Code quote:_
```
xargs -L1 .ci/check-rwx.py
```

**Review by dimakuv — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1698)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

___
*[`.ci/lib/stage-test-direct.jenkinsfile` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1698#-NnNerh4-1CSHzcYeEPi:-NnNerh4-1CSHzcYeEPj:b3mfmke) ([raw file](https://github.com/gramineproject/gramine/blob/1f72aaf8148a7712c5c8bad1da9839e2bcc5c633/.ci/lib/stage-test-direct.jenkinsfile#L3)):*
> ```
> stage('test-direct') {
>     sh '''
>         find ${GRAMINE_LIBDIR} -exec file {} \\; | \
> ```

This detects also a bunch of other files, most importantly including `tests`:
```
gramine/built-debug/lib/x86_64-linux-gnu$ find . -exec file {} \; | grep ELF | cut -
d':' -f1
./libmbedx509_gramine.so.6
...
./libra_tls_attest.so
./gramine/runtime/glibc/libanl.so.1
...
./gramine/tests/pal/Bootstrap7  # DO WE WANT THIS?
./gramine/tests/libos/entrypoint/stack_auxiliary  # DO WE WANT THIS?
...
./gramine/direct/libpal.so
./gramine/skeleton/libpal.so
./gramine/sgx/loader
./gramine/sgx/libpal.so
./gramine/sgx/gdb_integration/sgx_gdb.so
./gramine/libsysdb.so
```

Do we care about them? I don't mind checking them, so not blocking.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1698)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`.ci/lib/stage-test-direct.jenkinsfile` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1698#-NnNerh4-1CSHzcYeEPi:-NnNnRffBXnaLiIMi8-K:b-epbzvs) ([raw file](https://github.com/gramineproject/gramine/blob/1f72aaf8148a7712c5c8bad1da9839e2bcc5c633/.ci/lib/stage-test-direct.jenkinsfile#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This detects also a bunch of other files, most importantly including `tests`:
```
gramine/built-debug/lib/x86_64-linux-gnu$ find . -exec file {} \; | grep ELF | cut -
d':' -f1
./libmbedx509_gramine.so.6
...
./libra_tls_attest.so
./gramine/runtime/glibc/libanl.so.1
...
./gramine/tests/pal/Bootstrap7  # DO WE WANT THIS?
./gramine/tests/libos/entrypoint/stack_auxiliary  # DO WE WANT THIS?
...
./gramine/direct/libpal.so
./gramine/skeleton/libpal.so
./gramine/sgx/loader
./gramine/sgx/libpal.so
./gramine/sgx/gdb_integration/sgx_gdb.so
./gramine/libsysdb.so
```

Do we care about them? I don't mind checking them, so not blocking.
</blockquote></details>

I was thinking about excluding tests, but on the other hand, I don't see a reason not to check them, at least at this point.
___
*[`.ci/lib/stage-test-direct.jenkinsfile` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1698#-NnNB6ynBsAfyyI3rGVd:-NnNnE8VC9NguTGRIP4B:b4w40t3) ([raw file](https://github.com/gramineproject/gramine/blob/1f72aaf8148a7712c5c8bad1da9839e2bcc5c633/.ci/lib/stage-test-direct.jenkinsfile#L6)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I don't really care (in CI) -- but do we want to exit on the first failure of file check?
</blockquote></details>

I don't think we want to.
I think the behavior is correct: report all files that fail this check in one go.
Otherwise, if there are multiple files, somebody might think there is only one invalid file, fix one file, and repeat the test on CI/CD. In this way, he gets all errors in one go.



_Code snippet:_
```
$ echo "a c b d" | tr ' ' '\n'  | xargs -L1 ls -lah
total 16K
drwxr-xr-x  2 oshogbo oshogbo 4.0K Jan  5 03:51 .
drwxrwxrwt 12 root    root     12K Jan  5 03:51 ..
ls: cannot access 'c': No such file or directory
total 16K
drwxr-xr-x  2 oshogbo oshogbo 4.0K Jan  5 03:51 .
drwxrwxrwt 12 root    root     12K Jan  5 03:51 ..
ls: cannot access 'd': No such file or directory
```

**Review by mkow — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1698)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
