### PR TITLE
[tests] Fix installation of Musl tests

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

The previous script moved the test binaries out of the build directory, instead of copying them. As a result, every "rebuild and install" cycle ended up rebuilding all the Musl binaries, even if their dependencies didn't change.

## How to test this PR? 

Rebuild and install Gramine twice. The second rebuild should only rebuild about 4 targets (because of the `vcs_tag`) instead of rebuilding 99 of them.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/300)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/300)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/300)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/300#-MruouTL3Ob7k52rGmCM:-MruouTL3Ob7k52rGmCN:blbt7yv) (no related file):*
> As a result, every "rebuild and install" cycle ended up rebuilding all the Musl binaries, even if their dependencies didn't change

Ah, that's why. I thought it was a feature, not a bug :)

---
___
*[LibOS/shim/test/regression/install_musl_tests.sh, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/300#-MrupKhf03FsUVafCCq7:-MrupKhf03FsUVafCCq8:b5t7g21) ([raw file](https://github.com/gramineproject/gramine/blob/abab6e6d09ed95262f1ffc8f61835ee697c0519d/LibOS/shim/test/regression/install_musl_tests.sh#L5)):*
> ```Shell
> # Usage:
> #
> #    rename_musl_tests destdir musl_a musl_b musl_c...
> ```

The name is different name, `rename_musl_tests` -> `install_musl_tests`

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/300)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/test/regression/install_musl_tests.sh, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/300#-MrupKhf03FsUVafCCq7:-Ms4zlzB7C1rU6TZr-mn:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/abab6e6d09ed95262f1ffc8f61835ee697c0519d/LibOS/shim/test/regression/install_musl_tests.sh#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The name is different name, `rename_musl_tests` -> `install_musl_tests`
</blockquote></details>

Fixed.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/300)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/300)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/300)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/300)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/300)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-20.04 please (`fdatasync01` from LTP timed out, which is unrelated to this PR)

**Pull request merged**
