### PR TITLE
[CI-Examples] Add Candle ML framework example

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Candle is a minimalist ML framework for Rust with a focus on performance and ease of use. This PR adds two examples with Candle: simple matrix multiplication (to quickly test functionality) and Quantized LLaMA (to test performance).

## How to test this PR? 

Follow the README.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1938)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1938)* status: 0 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1938#-O1S9D2mBjT3R_aiKBkx:-O1S9D2mBjT3R_aiKBky:bveruxy) (no related file):*
https://github.com/gramineproject/gramine/pull/1937 is a prerequisite. Blocking.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1938)* status: 0 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1938#-O1SAFlXCXlOsBoiHnfv:-O1SAFlY-tsiLJ583MpM:b9a0i5k) (no related file):*
We need to decide where to put this example (and if we want this example at all). Most probably it should go to the separate Examples repo? Don't know.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1938#-O1SJrsb-k9uiLJaxOz7:-O1SJrsb-k9uiLJaxOz8:bhgg8j) (no related file):*
I have two examples, not sure if both are needed. If we decide to leave only one, then I would prefer the Quantized LLaMA one, because it is much more complex and can be used for benchmarking.

___
___
*[`CI-Examples/candle/Makefile` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/1938#-O1SAURiBI-KitAsa5UY:-O1SAURjDBJMPk-w0RV0:bv4n69m) ([raw file](https://github.com/gramineproject/gramine/blob/18d0dbb83622001006afa1d5fbf893298f19b7cb/CI-Examples/candle/Makefile#L25)):*
> ```Makefile
> 	mkdir -p $(SRCDIR) && cd $(SRCDIR) && \
> 		cargo new candle_matmul && cd candle_matmul && \
> 		cargo add --git https://github.com/huggingface/candle.git candle-core && \
> ```

I hard-coded all URLs and SHA256 hashes for now, I'm not sure if it's worth to make them variables.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1938)* status: 0 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1938#-O1a-2S5BehRjqhYLrKs:-O1a-2S5BehRjqhYLrKt:b-m4o2d6) (no related file):*
Quick benchmark results for `candle_quantized` (LLAMA2 7B). Collected on a powerful SPR machine with 2 NUMA nodes and 72 physical cores (i.e. 36 physical cores on each node). Running the workload with 36 threads and pinned to 36 physical cores on NUMA node 0. SGX PRM (basically EPC) is configured with 32GB on each NUMA node.

- Original workload:
```
~/gramine/CI-Examples/candle$ RAYON_NUM_THREADS=36 numactl --cpunodebind=0 --membind=0 \
    ./candle_quantized --model llama-2-7b.ggmlv3.q4_0.bin --tokenizer tokenizer.json --sample-len 200
avx: true, neon: false, simd128: false, f16c: true
temp: 0.80 repeat-penalty: 1.10 repeat-last-n: 64
Running on CPU, to run on GPU, build this example with `--features cuda`
loaded 291 tensors (3.79GB) in 3.46s
params: HParams { n_vocab: 32000, n_embd: 4096, n_mult: 256, n_head: 32, n_layer: 32, n_rot: 128, ftype: 2 }
model built
...
   6 prompt tokens processed: 9.50 token/s
 199 tokens generated: 6.07 token/s

```

- `gramine-direct`:
```
~/gramine/CI-Examples/candle$ RAYON_NUM_THREADS=36 numactl --cpunodebind=0 --membind=0 \
    gramine-direct ./candle_quantized
avx: true, neon: false, simd128: false, f16c: true
temp: 0.80 repeat-penalty: 1.10 repeat-last-n: 64
Running on CPU, to run on GPU, build this example with `--features cuda`
loaded 291 tensors (3.79GB) in 3.17s
params: HParams { n_vocab: 32000, n_embd: 4096, n_mult: 256, n_head: 32, n_layer: 32, n_rot: 128, ftype: 2 }
model built
...
   6 prompt tokens processed: 3.01 token/s
 199 tokens generated: 1.56 token/s
```

- `gramine-sgx`, no EDMM:
```
~/gramine/CI-Examples/candle$ RAYON_NUM_THREADS=36 numactl --cpunodebind=0 --membind=0 \
    gramine-sgx ./candle_quantized
avx: true, neon: false, simd128: false, f16c: true
temp: 0.80 repeat-penalty: 1.10 repeat-last-n: 64
Running on CPU, to run on GPU, build this example with `--features cuda`
loaded 291 tensors (3.79GB) in 27.87s
params: HParams { n_vocab: 32000, n_embd: 4096, n_mult: 256, n_head: 32, n_layer: 32, n_rot: 128, ftype: 2 }
model built
...
   6 prompt tokens processed: 2.36 token/s
 199 tokens generated: 6.83 token/s
```

- `gramine-sgx`, with EDMM:
```
~/gramine/CI-Examples/candle$ RAYON_NUM_THREADS=36 numactl --cpunodebind=0 --membind=0 \
    gramine-sgx ./candle_quantized
avx: true, neon: false, simd128: false, f16c: true
temp: 0.80 repeat-penalty: 1.10 repeat-last-n: 64
Running on CPU, to run on GPU, build this example with `--features cuda`
loaded 291 tensors (3.79GB) in 43.01s
params: HParams { n_vocab: 32000, n_embd: 4096, n_mult: 256, n_head: 32, n_layer: 32, n_rot: 128, ftype: 2 }
model built
...
   6 prompt tokens processed: 0.07 token/s
 199 tokens generated: 5.87 token/s
```

To be honest, I don't know how to interpret these.

___
___
*[`CI-Examples/candle/candle_quantized.manifest.template` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1938#-O1Y3zdDA7wmJduJ3F1o:-O1_zJ_h8r8AsDmJu546:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/18d0dbb83622001006afa1d5fbf893298f19b7cb/CI-Examples/candle/candle_quantized.manifest.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Must add `RAYON_NUM_THREADS` as a passthrough envvar, so that users can change the number of threads to run.
</blockquote></details>

Done
___
*[`CI-Examples/candle/candle_quantized.manifest.template` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/1938#-O1_prJX4mWzz-Azy0CW:-O1_zIt881qHA2JC3Om5:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/18d0dbb83622001006afa1d5fbf893298f19b7cb/CI-Examples/candle/candle_quantized.manifest.template#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Need to bump to "32G". The original workload takes up to 5.5GB, and the enclave with 16GB (minus the ASLR adjustments, minus Gramine's internal state) may error out with ENOMEM.
</blockquote></details>

Done

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1938)* status: 0 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1938#-O1tCLbG3DOBKQn8iOud:-O1tCLbG3DOBKQn8iOue:b-eklyr0) (no related file):*
Maybe better to include it in our [examples repo](https://github.com/gramineproject/examples) (instead of CI-Examples) so that it will be tested before each release (instead of every time)?

___

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1938)* status: 0 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1938#-O1SAFlXCXlOsBoiHnfv:-O20397R9pOkY_moIiZm:b-akkzwl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We need to decide where to put this example (and if we want this example at all). Most probably it should go to the separate Examples repo? Don't know.
</blockquote></details>

I'm against it, I think it's not popular enough to justify the burden of maintaining it (but I'll be happy to change my mind if you prove that it's actually popular). Maybe Examples repo would be better, assuming someone wants to maintain it there.

___

**Comment by monavij** [comment]
> I'm against it, I think it's not popular enough to justify the burden of maintaining it (but I'll be happy to change my mind if you prove that it's actually popular). Maybe Examples repo would be better, assuming someone wants to maintain it there.

One reason is that its a good rust example and we don't have one in Examples. One way to make something popular is to use them, especially if we like them :-)

**Review by mkow — COMMENTED** [review]
We already have an example in Rust: https://github.com/gramineproject/gramine/tree/master/CI-Examples/rust.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1938#-:-O2JokX28jC_xB7zwsoj:b57xmr9)* status: 0 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

**Comment by dimakuv** [comment]
Closing this PR. The fix to Gramine LibOS was merged in this repo, and the Candle example itself was moved to another repo: https://github.com/gramineproject/examples/pull/104

**Pull request closed without merging**
