### PR TITLE
[Docs] Create a section on prefix when installing from sources

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

See @woju's comment in #1434.

Closes #1434.

## How to test this PR? 

Docs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1436)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1436)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1436#-NZBmG0D03eWDx86eKD1:-NZBmG0D03eWDx86eKD2:b-5jr36r) (no related file):*
@jinengandhi-intel: Also ping here, the previous PR wasn't merged in the end.

___

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1436)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`Documentation/devel/building.rst` line 187 at r1](https://reviewable.io/reviews/gramineproject/gramine/1436#-NZBpr8NAcDA7FbbGs57:-NZBpr8NAcDA7FbbGs58:b-qey8m9) ([raw file](https://github.com/gramineproject/gramine/blob/9f127227cc09730b6a4ffd3c8300be7ce929a5e7/Documentation/devel/building.rst#L187)):*
> ```reStructuredText
>   that :file:`/usr/local/bin` is in your path (in ``$PATH`` environment
>   variable). Alternatively, you can modify the installation prefix, e.g. to
>   :file:`/usr`.
> ```

Or `--bindir`/`-Dbindir=`. This overrides only this path. Do you want to write this? (not blocking)
___
*[`Documentation/devel/building.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine/1436#-NZBpEXvE7s5lOovjkQd:-NZBpEXvE7s5lOovjkQe:buzlr4w) ([raw file](https://github.com/gramineproject/gramine/blob/9f127227cc09730b6a4ffd3c8300be7ce929a5e7/Documentation/devel/building.rst#L190)):*
> ```reStructuredText
> 
> - When installing from sources, Gramine Python modules are placed under
>   :file:`/usr/local/lib/python3.xyz/site-packages`. Some Linux distributions
> ```

This is inaccurate, on Debian-like distros this goes to `.../python3/dist-packages`. See `scripts/get-python-platlib.py` and this: https://github.com/gramineproject/gramine/blob/475ff5c4d5785c060e1174af05ffa788dc35a9db/meson.build#L51-L52.

Also newer meson versions (newer than we use) have `-Dpython.platlibdir`, which we don't use, but might in the future.

How much into detail we would like to get here?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1436)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Documentation/devel/building.rst` line 187 at r1](https://reviewable.io/reviews/gramineproject/gramine/1436#-NZBpr8NAcDA7FbbGs57:-NZBxzT44GDjpFx9xePh:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9f127227cc09730b6a4ffd3c8300be7ce929a5e7/Documentation/devel/building.rst#L187)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Or `--bindir`/`-Dbindir=`. This overrides only this path. Do you want to write this? (not blocking)
</blockquote></details>

Done
___
*[`Documentation/devel/building.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine/1436#-NZBpEXvE7s5lOovjkQd:-NZBy-094ZvpbrAIST1E:blwtyow) ([raw file](https://github.com/gramineproject/gramine/blob/9f127227cc09730b6a4ffd3c8300be7ce929a5e7/Documentation/devel/building.rst#L190)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is inaccurate, on Debian-like distros this goes to `.../python3/dist-packages`. See `scripts/get-python-platlib.py` and this: https://github.com/gramineproject/gramine/blob/475ff5c4d5785c060e1174af05ffa788dc35a9db/meson.build#L51-L52.

Also newer meson versions (newer than we use) have `-Dpython.platlibdir`, which we don't use, but might in the future.

How much into detail we would like to get here?
</blockquote></details>

Done. Is this fine?

**Review by kailun-qin — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1436)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1436)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1436)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`Documentation/devel/building.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine/1436#-NZBpEXvE7s5lOovjkQd:-NZDHQCW6EfPIdaj07Y5:b-la18eh) ([raw file](https://github.com/gramineproject/gramine/blob/9f127227cc09730b6a4ffd3c8300be7ce929a5e7/Documentation/devel/building.rst#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Is this fine?
</blockquote></details>

Looks OK, thanks!

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1436)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1436)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
