### PR TITLE
[LibOS] Add parser for flock() syscall

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This is a preparatory commit to introduce flock (BSD locks) support.

Extracted from #1212. (The initial request from @mkow was to extract only the parser part, but the parser won't even be called if there is no syscall implementation, so I added a dummy one.)

Some references for flags in Linux:
- https://elixir.bootlin.com/linux/latest/source/fs/locks.c#L2061
- https://elixir.bootlin.com/linux/latest/source/include/uapi/asm-generic/fcntl.h#L187
- https://elixir.bootlin.com/linux/latest/source/fs/locks.c#L416

## How to test this PR? 

There is not yet any test for `flock`. But manually can check with this git diff:
```diff
diff --git a/libos/test/regression/helloworld.c b/libos/test/regression/helloworld.c
@@ -1,6 +1,15 @@
 #include <stdio.h>

+#include <sys/file.h>
+#include <sys/types.h>
+#include <sys/stat.h>
+#include <fcntl.h>
+#define LOCK_MAND   32
+
 int main(int argc, char** argv) {
     printf("Hello world!\n");
+
+    int fd = open("unknown_testfile", O_RDONLY);
+    flock(fd, LOCK_SH | LOCK_NB | LOCK_MAND | 1024);
     return 0;
 }
```

This will print:
```
(libos_parser.c:1628:buf_write_all) [P1:T1:helloworld] trace: ---- flock(3, LOCK_SH|LOCK_NB|LOCK_MAND|0x400) ...
(libos_fcntl.c:288:libos_syscall_flock) [P1:T1:helloworld] warning: flock request with LOCK_MAND is ignored
(libos_parser.c:1628:buf_write_all) [P1:T1:helloworld] trace: ---- return from flock(...) = 0x0
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1404)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1404)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYLaMOx7pgR0W0yinBk):*
This is somewhat misleading. The added dummy `flock()` succeeds (actually ignored) when the request includes `LOCK_MAND` (i.e., this is not a usually-called "dummy" implementation). And we introduced it simply because parser won't even be called if there is no syscall implementation (i.e., it's the syscall arg parser that we actually wanted to instroduce and actually introduced). I suggest to either change the title to focus on the "arg parser" part or return 0 in the dummy impl.



_Code quote:_
```
[LibOS] Add dummy `flock()` implementation
```
___
*[`libos/src/sys/libos_fcntl.c` line 310 at r1](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYLfOnt5f6dGa0h-chJ:-NYLfOnt5f6dGa0h-chK:b-xrvwuq) ([raw file](https://github.com/gramineproject/gramine/blob/d6ce159ee3b5790808c1899924abd5ae25431bd7/libos/src/sys/libos_fcntl.c#L310)):*
> ```C
> 
>     /* TODO: add implementation */
>     ret = -ENOSYS;
> ```

why not 0? (see my comment in the commit msg)



_Code quote:_
```C
ret = -ENOSYS;
```

**Review by kailun-qin — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1404)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1404)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVKcGz4bpZ8wFlvg3H):*
> except for the corner case of deprecated `LOCK_MAND`.

huh, why?

update: ok, I see, but please clarify this sentence, I got quite confused after reading it. I.e., say that `LOCK_MAND` mode is nowadays ignored on Linux and always succeeds.
___
*[`libos/include/libos_table.h` line 90 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVKq3L0qPFhb_ZuOzN:-NYVKq3L0qPFhb_ZuOzO:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/21d04f437f35659786d8e56cea698cf224932021/libos/include/libos_table.h#L90)):*
> ```objc
> long libos_syscall_uname(struct new_utsname* buf);
> long libos_syscall_fcntl(int fd, int cmd, unsigned long arg);
> long libos_syscall_flock(int fd, unsigned int cmd);
> ```





_Suggestion:_
```objc
unsigned int fd
```
___
*[`libos/src/sys/libos_fcntl.c` line 282 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVVsW52A7R4RDklpy5:-NYVVsW52A7R4RDklpy6:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/21d04f437f35659786d8e56cea698cf224932021/libos/src/sys/libos_fcntl.c#L282)):*
> ```C
> }
> 
> long libos_syscall_flock(int fd, unsigned int cmd) {
> ```





_Suggestion:_
```C
unsigned int fd
```
___
*[`libos/src/sys/libos_fcntl.c` line 288 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVMV5M6d-S6dVOMBs0:-NYVMV5M6d-S6dVOMBs1:bnrdp83) ([raw file](https://github.com/gramineproject/gramine/blob/21d04f437f35659786d8e56cea698cf224932021/libos/src/sys/libos_fcntl.c#L288)):*
> flock request with LOCK_MAND is ignored

If you want to use present simple then it should be "flock requests [...] are". Or change to past tense and thus change the meaning to "there was such a call and it just got ignored".
___
*[`libos/src/sys/libos_fcntl.c` line 295 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVRnYdC4N6q64yWuda:-NYVRnYdC4N6q64yWudb:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/21d04f437f35659786d8e56cea698cf224932021/libos/src/sys/libos_fcntl.c#L295)):*
> ```C
>     assert(handle_map);
> 
>     struct libos_handle* hdl = get_fd_handle(fd, NULL, handle_map);
> ```





_Suggestion:_
```C
struct libos_handle* hdl = get_fd_handle(fd, /*has_flock_locks=*/NULL, /*map=*/NULL);
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1404)* status: 2 of 4 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVKcGz4bpZ8wFlvg3H):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> except for the corner case of deprecated `LOCK_MAND`.

huh, why?

update: ok, I see, but please clarify this sentence, I got quite confused after reading it. I.e., say that `LOCK_MAND` mode is nowadays ignored on Linux and always succeeds.
</blockquote></details>

Done.
___
*[`libos/include/libos_table.h` line 90 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVKq3L0qPFhb_ZuOzN:-NYXVas41psfutSezfsD:b-90orrv) ([raw file](https://github.com/gramineproject/gramine/blob/21d04f437f35659786d8e56cea698cf224932021/libos/include/libos_table.h#L90)):*
> ```objc
> long libos_syscall_uname(struct new_utsname* buf);
> long libos_syscall_fcntl(int fd, int cmd, unsigned long arg);
> long libos_syscall_flock(int fd, unsigned int cmd);
> ```

Done. Indeed, https://elixir.bootlin.com/linux/v6.3/source/include/linux/syscalls.h#L421.

Though we have this incorrect `int fd` in many other syscall declarations...
___
*[`libos/src/sys/libos_fcntl.c` line 282 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVVsW52A7R4RDklpy5:-NYXVoe6AGXXDrUMuaZv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/21d04f437f35659786d8e56cea698cf224932021/libos/src/sys/libos_fcntl.c#L282)):*
> ```C
> }
> 
> long libos_syscall_flock(int fd, unsigned int cmd) {
> ```

Done.
___
*[`libos/src/sys/libos_fcntl.c` line 288 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVMV5M6d-S6dVOMBs0:-NYXVu2N44oBeSUK-mBs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/21d04f437f35659786d8e56cea698cf224932021/libos/src/sys/libos_fcntl.c#L288)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> flock request with LOCK_MAND is ignored

If you want to use present simple then it should be "flock requests [...] are". Or change to past tense and thus change the meaning to "there was such a call and it just got ignored".
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_fcntl.c` line 295 at r2](https://reviewable.io/reviews/gramineproject/gramine/1404#-NYVRnYdC4N6q64yWuda:-NYXWJnyCk3ESDSrC7RY:b4q3o2f) ([raw file](https://github.com/gramineproject/gramine/blob/21d04f437f35659786d8e56cea698cf224932021/libos/src/sys/libos_fcntl.c#L295)):*
> ```C
>     assert(handle_map);
> 
>     struct libos_handle* hdl = get_fd_handle(fd, NULL, handle_map);
> ```

Done. Not sure why you have `has_flock_locks=` in your suggestion. It's actually `fd_flags=`.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1404)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1404)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1404)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
