### PR TITLE
[Docs] Fix PyTorch tutorial

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The tutorial wasn't updated since Gramine v1.2, it got stale.

## How to test this PR? 

Manually on a DCAP machine.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1418#-NYcgHdw5eyyBBwkUMFI:-NYcgHdw5eyyBBwkUMFJ:b-smcgiw) (no related file):*
TODO(myself or find someone): test with Gramine v1.4 and with latest-master Gramine on a fresh DCAP system (e.g. MS Azure VM). And probably on Ubuntu 22.04 too.

___
___
*[`Documentation/tutorials/pytorch/index.rst` line 491 at r1](https://reviewable.io/reviews/gramineproject/gramine/1418#-NYcg_bkEcC2X0rFzX88:-NYcg_bkEcC2X0rFzX89:buzds2g) ([raw file](https://github.com/gramineproject/gramine/blob/dee44de8a73757d7845c7514099b2942a61a3f17/Documentation/tutorials/pytorch/index.rst#L491)):*
> ```reStructuredText
>    loader.env.SECRET_PROVISION_SERVERS = "localhost:4433"
> 
> We must specify the path at which `libsecret_prov_attest.so` should be found.
> ```

This whole hunk is required only if we merge https://github.com/gramineproject/gramine/pull/1417.

Otherwise this hunk is not needed. I blocked myself until we have a resolution of that other PR.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1418#-NYcjTBx6RVVJsnb2kxx:-NYcjTBx6RVVJsnb2kxy:b84s8m1) (no related file):*
I temporarily enabled ReadTheDocs on this PR: https://gramine.readthedocs.io/en/dimakuv-fix-pytorch-tutorial/tutorials/pytorch/index.html

___

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1418#-NYcgHdw5eyyBBwkUMFI:-NYpjHrI-wp0jQLiB3RY:b-75blq2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself or find someone): test with Gramine v1.4 and with latest-master Gramine on a fresh DCAP system (e.g. MS Azure VM). And probably on Ubuntu 22.04 too.
</blockquote></details>

I checked this tutorial on a Ubuntu 20.04 DCAP system w/ Gramine latest-master -- all work fine.

___
___
*[`Documentation/tutorials/pytorch/index.rst` line 474 at r2](https://reviewable.io/reviews/gramineproject/gramine/1418#-NYplHGG5GpUMxH-Jzur:-NYplHGG5GpUMxH-Jzus:bk59pk6) ([raw file](https://github.com/gramineproject/gramine/blob/5cc471b799edc649e84a18eb83bcf169b888062d/Documentation/tutorials/pytorch/index.rst#L474)):*
> ```reStructuredText
> Our PyTorch uses remote secret provisioning which requires some knowledge about
> the network configuration on the platform. Therefore, we need to enable
> networking information::
> ```

A bit off the topic -- I noticed that we did not copy the `hosts` helper file (https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov/helper-files) from the `ra-tls-secret-prov` example. I understand it's not required in this tutorial, but why it's required for the `ra-tls-secret-prov` example then?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1418#-NYcgHdw5eyyBBwkUMFI:-NYrJuUB0_0BVC3_PDR2:b-ucfknh) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I checked this tutorial on a Ubuntu 20.04 DCAP system w/ Gramine latest-master -- all work fine.
</blockquote></details>

Thanks!

___
___
*[`Documentation/tutorials/pytorch/index.rst` line 474 at r2](https://reviewable.io/reviews/gramineproject/gramine/1418#-NYplHGG5GpUMxH-Jzur:-NYrJxKX8Iez0dCOGpXw:bds1vts) ([raw file](https://github.com/gramineproject/gramine/blob/5cc471b799edc649e84a18eb83bcf169b888062d/Documentation/tutorials/pytorch/index.rst#L474)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

A bit off the topic -- I noticed that we did not copy the `hosts` helper file (https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov/helper-files) from the `ra-tls-secret-prov` example. I understand it's not required in this tutorial, but why it's required for the `ra-tls-secret-prov` example then?
</blockquote></details>

To be honest, I don't remember why this file was needed in that example.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/tutorials/pytorch/index.rst` line 161 at r2](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZa-EIz4LE7peM06nL3:-NZa-EIz4LE7peM06nL4:b-prj6be) ([raw file](https://github.com/gramineproject/gramine/blob/5cc471b799edc649e84a18eb83bcf169b888062d/Documentation/tutorials/pytorch/index.rst#L161)):*
> ```reStructuredText
> manifest file contains both general non-SGX options for Gramine and
> SGX-specific ones.  Please refer to `this
> <https://gramine.readthedocs.io/en/stable/manifest-syntax.html>`__ for further
> ```

Shouldn't this be a relative URL, not absolute? So it always points to the right version.
___
*[`Documentation/tutorials/pytorch/index.rst` line 194 at r2](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZa3EZo2FflQGkWlvuV:-NZa3EZo2FflQGkWlvuW:byinx7z) ([raw file](https://github.com/gramineproject/gramine/blob/5cc471b799edc649e84a18eb83bcf169b888062d/Documentation/tutorials/pytorch/index.rst#L194)):*
> ```reStructuredText
>    ]
> 
> We also mount other directories such as ``{{ arch_libdir }}`` required by Python
> ```

Where is it actually mounted?



_Code quote:_
```reStructuredText
We also mount other directories such as ``{{ arch_libdir }}``
```
___
*[`Documentation/tutorials/pytorch/index.rst` line 342 at r2](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZa2pg7Eot3VC0LJ-nH:-NZa2pg7Eot3VC0LJ-nI:b-dxjuj2) ([raw file](https://github.com/gramineproject/gramine/blob/5cc471b799edc649e84a18eb83bcf169b888062d/Documentation/tutorials/pytorch/index.rst#L342)):*
> ```reStructuredText
> 
> Gramine provides a feature of `Encrypted Files
> <https://gramine.readthedocs.io/en/stable/manifest-syntax.html?highlight=protected#encrypted-files>`__,
> ```

ditto - actually, could you fix all the links here?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 0 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 491 at r1](https://reviewable.io/reviews/gramineproject/gramine/1418#-NYcg_bkEcC2X0rFzX88:-NZaU3S139HFWHvJXMVS:bcbjovh) ([raw file](https://github.com/gramineproject/gramine/blob/dee44de8a73757d7845c7514099b2942a61a3f17/Documentation/tutorials/pytorch/index.rst#L491)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This whole hunk is required only if we merge https://github.com/gramineproject/gramine/pull/1417.

Otherwise this hunk is not needed. I blocked myself until we have a resolution of that other PR.
</blockquote></details>

We did it in another way, this hunk is not needed, let me remove.
___
*[`Documentation/tutorials/pytorch/index.rst` line 161 at r2](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZa-EIz4LE7peM06nL3:-NZaU0i57rYaNdFAVcPZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5cc471b799edc649e84a18eb83bcf169b888062d/Documentation/tutorials/pytorch/index.rst#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't this be a relative URL, not absolute? So it always points to the right version.
</blockquote></details>

Done.
___
*[`Documentation/tutorials/pytorch/index.rst` line 194 at r2](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZa3EZo2FflQGkWlvuV:-NZaQRg5EllLvZQSFCZv:b-2ai8va) ([raw file](https://github.com/gramineproject/gramine/blob/5cc471b799edc649e84a18eb83bcf169b888062d/Documentation/tutorials/pytorch/index.rst#L194)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Where is it actually mounted?
</blockquote></details>

I'm not sure I understand your question. In this sub-section, I'm talking about the existing `pytorch.manifest.template` file: https://github.com/gramineproject/examples/blob/badc31fe538dacb5ada00f2cbb0b51b67ed5ed39/pytorch/pytorch.manifest.template#L22

Do you want me to add an example for this, as I do with `/lib` and Python-package paths? Like this:
```
   fs.mounts = [
     ...
     { path = "{{ arch_libdir }}", uri = "file:{{ arch_libdir }}" },
     ...
   ]
```
___
*[`Documentation/tutorials/pytorch/index.rst` line 342 at r2](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZa2pg7Eot3VC0LJ-nH:-NZaU1jd8cKv0AGruAaJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5cc471b799edc649e84a18eb83bcf169b888062d/Documentation/tutorials/pytorch/index.rst#L342)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto - actually, could you fix all the links here?
</blockquote></details>

Done.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 0 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 491 at r1](https://reviewable.io/reviews/gramineproject/gramine/1418#-NYcg_bkEcC2X0rFzX88:-NZaU_K7BwHMFF0zSfJE:b-r7x8pj) ([raw file](https://github.com/gramineproject/gramine/blob/dee44de8a73757d7845c7514099b2942a61a3f17/Documentation/tutorials/pytorch/index.rst#L491)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We did it in another way, this hunk is not needed, let me remove.
</blockquote></details>

Done, removed.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 0 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZaVXbYDHm91nZ9q_3O:-NZaVXbYDHm91nZ9q_3P:b-aj7h7o) ([raw file](https://github.com/gramineproject/gramine/blob/21826528ff50999361e477eb014dac9dc398281e/Documentation/tutorials/pytorch/index.rst#L99)):*
> ```reStructuredText
>   before you proceed (don't forget to choose Linux as the target OS).
> 
> - Gramine of at least v1.4, with DCAP support. DCAP software infrastructure must
> ```

Do I change the version to `v1.5`?
___
*[`Documentation/tutorials/pytorch/index.rst` line 365 at r3](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZaVhJRC51GnUqKD7l1:-NZaVhJRC51GnUqKD7l2:b-aj7h7o) ([raw file](https://github.com/gramineproject/gramine/blob/21826528ff50999361e477eb014dac9dc398281e/Documentation/tutorials/pytorch/index.rst#L365)):*
> ```reStructuredText
> repository), so let's build the secret provisioning server::
> 
>    git clone --depth 1 --branch v1.4 https://github.com/gramineproject/gramine.git
> ```

Do I change the version to `v1.5`?

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZaVXbYDHm91nZ9q_3O:-NZaaaht8GXc6wbWuT6e:b3jlwm0) ([raw file](https://github.com/gramineproject/gramine/blob/21826528ff50999361e477eb014dac9dc398281e/Documentation/tutorials/pytorch/index.rst#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do I change the version to `v1.5`?
</blockquote></details>

Have we tested with Gramine v1.4? If so, I think it's fine that we keep it to `v1.4` since it looks like we don't have changes/updates in this tutorial that're specific to `v1.5`.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 194 at r2](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZa3EZo2FflQGkWlvuV:-NZdoNstE-wN7PbNwroR:buc5q48) ([raw file](https://github.com/gramineproject/gramine/blob/5cc471b799edc649e84a18eb83bcf169b888062d/Documentation/tutorials/pytorch/index.rst#L194)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not sure I understand your question. In this sub-section, I'm talking about the existing `pytorch.manifest.template` file: https://github.com/gramineproject/examples/blob/badc31fe538dacb5ada00f2cbb0b51b67ed5ed39/pytorch/pytorch.manifest.template#L22

Do you want me to add an example for this, as I do with `/lib` and Python-package paths? Like this:
```
   fs.mounts = [
     ...
     { path = "{{ arch_libdir }}", uri = "file:{{ arch_libdir }}" },
     ...
   ]
```
</blockquote></details>

Done. I just added this snippet, as it seems logical to have it.
___
*[`Documentation/tutorials/pytorch/index.rst` line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZaVXbYDHm91nZ9q_3O:-NZdoR4q0ApqZJIiOckB:b-r2xpwp) ([raw file](https://github.com/gramineproject/gramine/blob/21826528ff50999361e477eb014dac9dc398281e/Documentation/tutorials/pytorch/index.rst#L99)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Have we tested with Gramine v1.4? If so, I think it's fine that we keep it to `v1.4` since it looks like we don't have changes/updates in this tutorial that're specific to `v1.5`.
</blockquote></details>

Done, I changed to v1.5 everywhere, since this version will be released now, and I tested against the master branch.

I see no reason to specify an older version (v1.4) if we can safely specify the new version.

**Comment by dimakuv** [comment]
*[`Documentation/tutorials/pytorch/index.rst` line 93 at r4](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZeDOwJ3TcfyQzQ2Sm6:-NZeDOwJ3TcfyQzQ2Sm7:b-kyi5c2) ([raw file](https://github.com/gramineproject/gramine/blob/b6b47e3e98765ebdcdb0dc93ab7762a9651989f9/Documentation/tutorials/pytorch/index.rst#L93)):*
> ```reStructuredText
>   Please install the following dependencies::
> 
>       sudo apt-get install libnss-mdns libnss-myhostname
> ```

Working on this: I suspect this is not needed. I'm doing this tutorial on a fresh Azure VM, let's see if things will work without this.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 93 at r4](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZeDOwJ3TcfyQzQ2Sm6:-NZeHyva8vcqElv8NyqK:b-gop2w0) ([raw file](https://github.com/gramineproject/gramine/blob/b6b47e3e98765ebdcdb0dc93ab7762a9651989f9/Documentation/tutorials/pytorch/index.rst#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Working on this: I suspect this is not needed. I'm doing this tutorial on a fresh Azure VM, let's see if things will work without this.
</blockquote></details>

Done, I verified, this is not required.

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/tutorials/pytorch/index.rst` line 111 at r5](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZftVlDAB3mo1vAPwtB:-NZftVlDAB3mo1vAPwtC:bqn7udn) ([raw file](https://github.com/gramineproject/gramine/blob/979983cbd9361bd560b755f3d64ccb29c09a8b0e/Documentation/tutorials/pytorch/index.rst#L111)):*
> ```reStructuredText
> Go to the directory with Gramine's PyTorch example::
> 
>    git clone --depth 1 --branch v1.5 https://github.com/gramineproject/examples.git
> ```

So, this should go after the 1.5 release?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 111 at r5](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZftVlDAB3mo1vAPwtB:-NZfyHvl283KjJ_QjFEq:bb4i5fv) ([raw file](https://github.com/gramineproject/gramine/blob/979983cbd9361bd560b755f3d64ccb29c09a8b0e/Documentation/tutorials/pytorch/index.rst#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, this should go after the 1.5 release?
</blockquote></details>

Done, I'm using stable-checkout macro now. What do you think?
___
*[`Documentation/tutorials/pytorch/index.rst` line 96 at r6](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZfyLmc5bnzV8NwVd-Q:-NZfyLmc5bnzV8NwVd-R:b-lrexy5) ([raw file](https://github.com/gramineproject/gramine/blob/ba8a22e83fd4ca8510acaf9bf4ed8c103b8d0b4e/Documentation/tutorials/pytorch/index.rst#L96)):*
> ```reStructuredText
>   the compute platform).
> 
> - Latest Gramine, with DCAP support. DCAP software infrastructure must also be
> ```

FYI: I can't use stable-checkout because it is in the form `--branch <version>`, so I decided to just use "Latest". Is it fine?

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/tutorials/pytorch/index.rst` line 111 at r5](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZftVlDAB3mo1vAPwtB:-NZgftKs-8XwyUNcj9yy:b-w3s528) ([raw file](https://github.com/gramineproject/gramine/blob/979983cbd9361bd560b755f3d64ccb29c09a8b0e/Documentation/tutorials/pytorch/index.rst#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, I'm using stable-checkout macro now. What do you think?
</blockquote></details>

Hmm, that will work weirdly I think? If someone will be browsing this tutorial with Gramine X.Y, and then look at this line, they will get the newest checkout instead of the version for which the rest of the text was written?
___
*[`Documentation/tutorials/pytorch/index.rst` line 96 at r6](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZfyLmc5bnzV8NwVd-Q:-NZgfnKjBxEje-pFV1Xc:bs0jr6r) ([raw file](https://github.com/gramineproject/gramine/blob/ba8a22e83fd4ca8510acaf9bf4ed8c103b8d0b4e/Documentation/tutorials/pytorch/index.rst#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I can't use stable-checkout because it is in the form `--branch <version>`, so I decided to just use "Latest". Is it fine?
</blockquote></details>

Hmm, see the other discussion.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 111 at r5](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZftVlDAB3mo1vAPwtB:-NZgreU81bFyM4L0XQhg:b-k604vz) ([raw file](https://github.com/gramineproject/gramine/blob/979983cbd9361bd560b755f3d64ccb29c09a8b0e/Documentation/tutorials/pytorch/index.rst#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, that will work weirdly I think? If someone will be browsing this tutorial with Gramine X.Y, and then look at this line, they will get the newest checkout instead of the version for which the rest of the text was written?
</blockquote></details>

Yes, that's true. Ok, I'm unhappy with all tried approaches. I would prefer to have `v1.5` in this document explicitly (because that's what it was tested on and that's what has the exact described properties).

So if you're against having `v1.5` before the actual release, I'm fine with postponing this PR to be merged after the release.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/tutorials/pytorch/index.rst` line 111 at r5](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZftVlDAB3mo1vAPwtB:-NZgshXNChB-EPniD9Oz:b-2jvm7h) ([raw file](https://github.com/gramineproject/gramine/blob/979983cbd9361bd560b755f3d64ccb29c09a8b0e/Documentation/tutorials/pytorch/index.rst#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, that's true. Ok, I'm unhappy with all tried approaches. I would prefer to have `v1.5` in this document explicitly (because that's what it was tested on and that's what has the exact described properties).

So if you're against having `v1.5` before the actual release, I'm fine with postponing this PR to be merged after the release.
</blockquote></details>

Done, I reverted back to explicit `v1.5`
___
*[`Documentation/tutorials/pytorch/index.rst` line 96 at r6](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZfyLmc5bnzV8NwVd-Q:-NZgsf8t897BAOOtLJIg:b-2jvm7h) ([raw file](https://github.com/gramineproject/gramine/blob/ba8a22e83fd4ca8510acaf9bf4ed8c103b8d0b4e/Documentation/tutorials/pytorch/index.rst#L96)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, see the other discussion.
</blockquote></details>

Done, I reverted back to explicit `v1.5`

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Documentation/tutorials/pytorch/index.rst` line 289 at r8](https://reviewable.io/reviews/gramineproject/gramine/1418#-NZjXM3N0aOyvTOf6B5R:-NZz2RHb49vbxnecXi22:b-j0asw4) ([raw file](https://github.com/gramineproject/gramine/blob/217ec4809e3c338098214cd744e38eedc44869de/Documentation/tutorials/pytorch/index.rst#L289)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

On EPID platforms the token is not dummy, and also I think the token is created when you run `gramine-sgx`, though I haven't seen the Makefile, so it might have been explicitly created. Also the testing instructions of this PR say that this is intended for DCAP machines, and installation instruction says only "Gramine 1.5", so people can just use packages (for upstream/DCAP driver). This token point is probably moot, can we just remove it?
</blockquote></details>

Done, you're right.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — DISMISSED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by woju — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1418)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
