### PR TITLE
[PAL] Fix main() signature in regression tests for UBSan

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 
Split from #1904

## How to test this PR? 

compile with ubsan on Ubuntu 24.04 and run

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`pal/regression/AttestationReport.c` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/2002#-O7DcmmQ7RetipFBLh82:-O7DcmmQ7RetipFBLh83:b-befspd) ([raw file](https://github.com/gramineproject/gramine/blob/8cdb22fd7a5a7cf771a44afdb17fe110d4b10296/pal/regression/AttestationReport.c#L12)):*
> ```C
> int main(int argc, char** argv, char** envp) {
>     /* We don't care about unused args to main, but UBSan complains otherwise
>      * with call through pointer with incorrect function type"
> ```

Unmatched `"` at the end. ditto everywhere

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/2002#-O7Dgt2GBexFy1L0WYzU):*
I would also add the commit message body:
```
Newer Clang versions (v18 and newer) added more UBSan checks that
triggered UBSan on PAL regression tests. For more info, see previous
commit "[common] Update UBSan to be compatible with Clang 18".
```
___
*[`pal/regression/AttestationReport.c` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/2002#-O7DcmmQ7RetipFBLh82:-O7DhLFzAyZKV7KwRlH9:bkdf4yj) ([raw file](https://github.com/gramineproject/gramine/blob/8cdb22fd7a5a7cf771a44afdb17fe110d4b10296/pal/regression/AttestationReport.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Unmatched `"` at the end. ditto everywhere
</blockquote></details>

Yes, should be `with "call through pointer ..."`

Also, I personally don't like when for 1- or 2-line comments, the ending bracket is on a separate line. I would finish in the same (second) line: `...function type" */`

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: 1 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/2002#-O7Dgt2GBexFy1L0WYzU):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would also add the commit message body:
```
Newer Clang versions (v18 and newer) added more UBSan checks that
triggered UBSan on PAL regression tests. For more info, see previous
commit "[common] Update UBSan to be compatible with Clang 18".
```
</blockquote></details>

Done.
___
*[`pal/regression/AttestationReport.c` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/2002#-O7DcmmQ7RetipFBLh82:-O7EBm_ZE_FJls8--WPZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8cdb22fd7a5a7cf771a44afdb17fe110d4b10296/pal/regression/AttestationReport.c#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, should be `with "call through pointer ..."`

Also, I personally don't like when for 1- or 2-line comments, the ending bracket is on a separate line. I would finish in the same (second) line: `...function type" */`
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`pal/regression/ipv6_parser.c` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/2002#-O7ED15l5WLMAaiY6qQI:-O7ED15l5WLMAaiY6qQJ:b4wezxe) ([raw file](https://github.com/gramineproject/gramine/blob/097343f63ad8e4dacf547482d9933678ec2bf833/pal/regression/ipv6_parser.c#L1)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */ /* Copyright (C) 2022 Intel Corporation
> ```

Unintended bug?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: 16 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`pal/regression/ipv6_parser.c` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/2002#-O7ED15l5WLMAaiY6qQI:-O7EDznzC_T8Jc9nkkPr:b-dcvkdy) ([raw file](https://github.com/gramineproject/gramine/blob/097343f63ad8e4dacf547482d9933678ec2bf833/pal/regression/ipv6_parser.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Unintended bug?
</blockquote></details>

Fixed. Yes, too much joining lines

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 15 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 17 files at r1, 15 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by woju** [comment]
Jenkins, test linux-sgx-vm-gcc-release please

**Comment by woju** [comment]
Jenkins, test linux-sgx-vm-gcc-release please

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by woju** [comment]
Jenkins, test linux-sgx-vm-gcc-release please

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2002)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
