### PR TITLE
[LibOS] Add support for execv with argv = NULL

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

Add support for execv with argv = NULL.

## How to test this PR? 

Run added LibOS regression test case.

Resolves: https://github.com/gramineproject/gramine/issues/794

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIp-RX2KQwNHMg6ln8):*
`execv` is one of the libc wrappers, not a syscall



_Suggestion:_
```
execve
```
___
*[`libos/src/sys/libos_exec.c` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIqEUG5HoJbUuCE2rn:-NEIqEUH6ETZkxJCJtjH:b-5tt2bz) ([raw file](https://github.com/gramineproject/gramine/blob/d895bc2ec5b9964afade8e3e891b30ab5cfcb180/libos/src/sys/libos_exec.c#L150)):*
> ```C
>             return -EFAULT;
>     }
>     if (!argv)
> ```

I'd rather put the loop above in the `else` branch of this `if`.
___
*[`libos/test/regression/exec_null.c` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIpfGo4NMGLueranM0:-NEIpfGo4NMGLueranM1:b-m69wm2) ([raw file](https://github.com/gramineproject/gramine/blob/d895bc2ec5b9964afade8e3e891b30ab5cfcb180/libos/test/regression/exec_null.c#L4)):*
> ```C
> 
> int main(int argc, const char** argv, const char** envp) {
>     execve("./exec_victim", NULL, NULL);
> ```

Please change to inline syscall to ensure that we're testing the real syscall (because we're testing a quirk of its interface glibc is not unlikely to alter the args).
___
*[`libos/test/regression/meson.build` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIqaT42rzX4n_7RFyX:-NEIqaT539QlVQUimZEB:bsj84rm) ([raw file](https://github.com/gramineproject/gramine/blob/d895bc2ec5b9964afade8e3e891b30ab5cfcb180/libos/test/regression/meson.build#L24)):*
> ```Meson
>     'exec_invalid_args': {},
>     'exec_null': {
>         'c_args': '-Wno-nonnull',
> ```

Won't be needed when calling the syscall directly.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: 2 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIp-RX2KQwNHMg6ln8):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`execv` is one of the libc wrappers, not a syscall
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_exec.c` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIqEUG5HoJbUuCE2rn:-NEJDeVR-zrJ-r19ngZP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d895bc2ec5b9964afade8e3e891b30ab5cfcb180/libos/src/sys/libos_exec.c#L150)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rather put the loop above in the `else` branch of this `if`.
</blockquote></details>

Done.
___
*[`libos/test/regression/exec_null.c` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIpfGo4NMGLueranM0:-NEJDdj77VNWzsN-1cHs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d895bc2ec5b9964afade8e3e891b30ab5cfcb180/libos/test/regression/exec_null.c#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please change to inline syscall to ensure that we're testing the real syscall (because we're testing a quirk of its interface glibc is not unlikely to alter the args).
</blockquote></details>

Done.
___
*[`libos/test/regression/meson.build` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIqaT42rzX4n_7RFyX:-NEJE3VJEuFPIlF1IXIF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d895bc2ec5b9964afade8e3e891b30ab5cfcb180/libos/test/regression/meson.build#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Won't be needed when calling the syscall directly.
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[`libos/test/regression/exec_victim` line 0 at r2](https://reviewable.io/reviews/gramineproject/gramine/979#-NEKLiAgCJOephvpdBe2:-NEKLiAgCJOephvpdBe3:be8unq7) ([raw file](https://github.com/gramineproject/gramine/blob/cee82a915df42e1d2b8233c1e032783f3b8620f5/libos/test/regression/exec_victim#L0)):*
Accidentally added this file? Please revert this.
___
*[`libos/test/regression/tests.toml` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/979#-NEKMMR_7PNOss0KzfHh:-NEKMMR_7PNOss0KzfHi:buur1k5) ([raw file](https://github.com/gramineproject/gramine/blob/cee82a915df42e1d2b8233c1e032783f3b8620f5/libos/test/regression/tests.toml#L26)):*
> ```TOML
>   "exec_fork",
>   "exec_invalid_args",
>   "exec_null",
> ```

Please add the test to `tests_musl.toml` list as well (to test also on Musl, not only on Glibc)

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: 5 of 7 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/test/regression/exec_victim` line  at r2](https://reviewable.io/reviews/gramineproject/gramine/979#-NEKLiAgCJOephvpdBe2:-NELEaL63DSFqlNt3MuP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cee82a915df42e1d2b8233c1e032783f3b8620f5/libos/test/regression/exec_victim#L)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Accidentally added this file? Please revert this.
</blockquote></details>

Done.
___
*[`libos/test/regression/tests.toml` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/979#-NEKMMR_7PNOss0KzfHh:-NELEbOc5Oy6esPrE1jr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cee82a915df42e1d2b8233c1e032783f3b8620f5/libos/test/regression/tests.toml#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add the test to `tests_musl.toml` list as well (to test also on Musl, not only on Glibc)
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`fdatasync01` and `writev07` LTP tests timed out, unrelated)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[`libos/src/sys/libos_exec.c` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIqEUG5HoJbUuCE2rn:-NELjR6k2_N3Q-Qy2Uv8:byrthqv) ([raw file](https://github.com/gramineproject/gramine/blob/d895bc2ec5b9964afade8e3e891b30ab5cfcb180/libos/src/sys/libos_exec.c#L150)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, do we want to use such formatting? I'm not strongly against, but would prefer to put the `for` inside braces (we only drop them for `else-if` constructions).
@dimakuv: WDYT?
</blockquote></details>

+1 to @mkow. Let's put the for loop into additional `{ }`, otherwise it looks weird.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: 6 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/sys/libos_exec.c` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/979#-NEIqEUG5HoJbUuCE2rn:-NELuXrJ3Gdw4xFY8w2h:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d895bc2ec5b9964afade8e3e891b30ab5cfcb180/libos/src/sys/libos_exec.c#L150)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to @mkow. Let's put the for loop into additional `{ }`, otherwise it looks weird.
</blockquote></details>

Done.
___
*[`libos/test/regression/exec_null.c` line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/979#-NELhJkn7dqA42nl-mHU:-NELui3T1-8IsO91-CQV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a68882d2b53e44ebababa10d5de39929ff258e03/libos/test/regression/exec_null.c#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 4 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/exec_null.c` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/979#-NELvYQH7ndDISoZKCXS:-NELvYQH7ndDISoZKCXT:b-3yqyyk) ([raw file](https://github.com/gramineproject/gramine/blob/83cdb4fedbe98e145f58d49b16af630004191062/libos/test/regression/exec_null.c#L5)):*
> ```C
> #include <unistd.h>
> 
> int main(int argc, const char** argv, const char** envp) {
> ```

Didn't compiler complain about unused variables here?



_Suggestion:_
```C
int main(void)
```

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: 6 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/regression/exec_null.c` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/979#-NELvYQH7ndDISoZKCXS:-NEM1SWr8oBiA4HJOGdJ:bx7ek19) ([raw file](https://github.com/gramineproject/gramine/blob/83cdb4fedbe98e145f58d49b16af630004191062/libos/test/regression/exec_null.c#L5)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Didn't compiler complain about unused variables here?
</blockquote></details>

I did not but done now.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/979)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
