### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Miscellaneous fixes from my todo list. Stashed into one PR as they are rather small.
Review commit-by-commit

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: 10 of 15 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/sys/shim_clone.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/658#-N4nBNyy9nB8p8_xHy74:-N4nBNyy9nB8p8_xHy75:b-haoeae) ([raw file](https://github.com/gramineproject/gramine/blob/425e845086d018103034b59849f04b2798302d73/LibOS/shim/src/sys/shim_clone.c#L62)):*
> ```C
>      * do not move the below functions before shim_tcb_init/set_cur_thread()! */
>     object_wait_with_retry(arg->create_event);
>     DkObjectClose(arg->create_event);
> ```

It's unrelated, but I've moved this to the parent - it's easier to reason about the code this way and it's one step closer to parent noticing child failures.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 6 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`LibOS/shim/include/shim_pollable_event.h` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/658#-N4oCg7K0O6owDlk4BDq:-N4oCg7LD3QWR8vDYzqk:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b10745a16d0e4d023f6866c0e48a022b7fb538ce/LibOS/shim/include/shim_pollable_event.h#L13)):*
> ```objc
> /*
>  * These events have binary semaphore semantics:
>  * - `set_pollable_event(e)` sets the semaphore to 1 (regardless of it's current state),
> ```





_Suggestion:_
```objc
its
```
___
*[`LibOS/shim/include/shim_pollable_event.h` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/658#-N4oChKWA9dFJJjtlUx6:-N4oChKWA9dFJJjtlUx7:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b10745a16d0e4d023f6866c0e48a022b7fb538ce/LibOS/shim/include/shim_pollable_event.h#L14)):*
> ```objc
>  * These events have binary semaphore semantics:
>  * - `set_pollable_event(e)` sets the semaphore to 1 (regardless of it's current state),
>  * - `clear_pollable_event(e)` sets the semaphore to 0 (regardless of it's current state).
> ```





_Suggestion:_
```objc
its
```

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: 14 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/include/shim_pollable_event.h` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/658#-N4oCg7K0O6owDlk4BDq:-N4vWZS-C3eRXaJvJYer:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b10745a16d0e4d023f6866c0e48a022b7fb538ce/LibOS/shim/include/shim_pollable_event.h#L13)):*
> ```objc
> /*
>  * These events have binary semaphore semantics:
>  * - `set_pollable_event(e)` sets the semaphore to 1 (regardless of it's current state),
> ```

Done.
___
*[`LibOS/shim/include/shim_pollable_event.h` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/658#-N4oChKWA9dFJJjtlUx6:-N4vWZwb71SFmtk02kXt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b10745a16d0e4d023f6866c0e48a022b7fb538ce/LibOS/shim/include/shim_pollable_event.h#L14)):*
> ```objc
>  * These events have binary semaphore semantics:
>  * - `set_pollable_event(e)` sets the semaphore to 1 (regardless of it's current state),
>  * - `clear_pollable_event(e)` sets the semaphore to 0 (regardless of it's current state).
> ```

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 6 of 6 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/shim_async.c` line 291 at r4](https://reviewable.io/reviews/gramineproject/gramine/658#-N5-7dA4A6CX8rLl4tDs:-N5-7dA4A6CX8rLl4tDt:b-1nym5a) ([raw file](https://github.com/gramineproject/gramine/blob/7b7149bdd5aa84cd392291d1a3fc764cecfc91a8/LibOS/shim/src/shim_async.c#L291)):*
> ```C
>         /* wait on async IO events + install_new_event + next expiring alarm/timer */
>         ret = DkStreamsWaitEvents(pals_cnt + 1, pals, pal_events, ret_events,
>                                   inf_sleep ? NULL : &sleep_time);
> ```

So this was a bug? If we wanted to sleep forever, we passed `sleep_time == NO_TIMEOUT` which makes no sense for `DkStreamsWaitEvents()`... Or rather, it indeed tells to sleep for a veeeery long time, but it's not a proper "no timeout" handling.

Same question for a couple other places where `NO_TIMEOUT` was still used.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`LibOS/shim/src/shim_async.c` line 291 at r4](https://reviewable.io/reviews/gramineproject/gramine/658#-N5-7dA4A6CX8rLl4tDs:-N5-BsmD8Di_5Lq4R7tJ:bm92ig1) ([raw file](https://github.com/gramineproject/gramine/blob/7b7149bdd5aa84cd392291d1a3fc764cecfc91a8/LibOS/shim/src/shim_async.c#L291)):*
> Or rather, it indeed tells to sleep for a veeeery long time, but it's not a proper "no timeout" handling.

Yes, it was just a very finite approximation of an infinite value/timeout :)

> Same question for a couple other places where NO_TIMEOUT was still used.

Other places just set this value as intermediate and then fixed up arguments based on it.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`LibOS/shim/src/shim_async.c` line 291 at r4](https://reviewable.io/reviews/gramineproject/gramine/658#-N5-7dA4A6CX8rLl4tDs:-N5-KwoL2-tiwKWYoQq2:bsod6zg) ([raw file](https://github.com/gramineproject/gramine/blob/7b7149bdd5aa84cd392291d1a3fc764cecfc91a8/LibOS/shim/src/shim_async.c#L291)):*
> Other places just set this value as intermediate and then fixed up arguments based on it.

Most places yes, but at least the `futex` code seems to be wrong. See my other comment where I highlight it.

Anyway, this was just a question to be sure I understand the changes. Everything is good now.
___
*[`LibOS/shim/src/sys/shim_futex.c` line 771 at r4](https://reviewable.io/reviews/gramineproject/gramine/658#-N5-KrHi4i74Gn69Z9Kd:-N5-KrHi4i74Gn69Z9Ke:b-1w5bkp) ([raw file](https://github.com/gramineproject/gramine/blob/425e845086d018103034b59849f04b2798302d73/LibOS/shim/src/sys/shim_futex.c#L771)):*
> ```C
>             /* fallthrough */
>         case FUTEX_WAIT_BITSET:
>             return futex_wait(uaddr, val, timeout, val3);
> ```

FYI: This used `timeout == NO_TIMEOUT` incorrectly, if I'm not mistaken.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`LibOS/shim/src/shim_async.c` line 291 at r4](https://reviewable.io/reviews/gramineproject/gramine/658#-N5-7dA4A6CX8rLl4tDs:-N5-OnH4DDHrGAGy95e6:b-x3teec) ([raw file](https://github.com/gramineproject/gramine/blob/7b7149bdd5aa84cd392291d1a3fc764cecfc91a8/LibOS/shim/src/shim_async.c#L291)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Other places just set this value as intermediate and then fixed up arguments based on it.

Most places yes, but at least the `futex` code seems to be wrong. See my other comment where I highlight it.

Anyway, this was just a question to be sure I understand the changes. Everything is good now.
</blockquote></details>

No, it had a check in the child function for this, so `NO_TIMEOUT` was used internally only (it was never passed to PAL or outside of the futex file).
___
*[`LibOS/shim/src/sys/shim_futex.c` line 354 at r4](https://reviewable.io/reviews/gramineproject/gramine/658#-N5-OgZi9Oog4qX8moU1:-N5-OgZi9Oog4qX8moU2:b-7uyd8o) ([raw file](https://github.com/gramineproject/gramine/blob/425e845086d018103034b59849f04b2798302d73/LibOS/shim/src/sys/shim_futex.c#L354)):*
> ```C
>     futex = NULL;
> 
>     ret = thread_wait(timeout != NO_TIMEOUT ? &timeout : NULL, /*ignore_pending_signals=*/false);
> ```

@dimakuv here

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`LibOS/shim/src/shim_async.c` line 291 at r4](https://reviewable.io/reviews/gramineproject/gramine/658#-N5-7dA4A6CX8rLl4tDs:-N5-RwNuELQs9M-cjOT3:b32w0x) ([raw file](https://github.com/gramineproject/gramine/blob/7b7149bdd5aa84cd392291d1a3fc764cecfc91a8/LibOS/shim/src/shim_async.c#L291)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, it had a check in the child function for this, so `NO_TIMEOUT` was used internally only (it was never passed to PAL or outside of the futex file).
</blockquote></details>

OK

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 13 files at r5, 6 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (LTP `fcntl14_04` and `fdatasync01` failed, known unrelated issue)

**Review by mkow — APPROVED** [review]
> Reviewed 13 of 13 files at r5, 6 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/658)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
