### PR TITLE
[Docs] Stop using `|nbsp|` on pages rendered by GitHub

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

GitHub misrenders it, effectively leaving a triple-space which looks really ugly.

## How to test this PR? 

Look at the rich diff on GitHub.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)

### CODE REVIEW

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1892#-NycH3qa3JZKxX_fIxZ2:-NycH3qa3JZKxX_fIxZ3:b-qor1n4) (no related file):*
What about https://github.com/gramineproject/gramine/blob/master/CONTRIBUTING.rst?

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)* status: 1 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1892#-NycH3qa3JZKxX_fIxZ2:-Nygj5E24RGSfLGK1AV5:b6z9n06) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about https://github.com/gramineproject/gramine/blob/master/CONTRIBUTING.rst?
</blockquote></details>

Right, done. Although it has more problems, e.g. missing syntax highlighting and that "sh" rendered at the top, but I don't know any easy workaround/fix for that.

___

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)* status: 1 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1892#-NycH3qa3JZKxX_fIxZ2:-NygwZtL246Sc-AID3hg:buoe9si) (no related file):*
> but I don't know any easy workaround/fix for that.

Isn't the easy workaround be just removing it? Pls see https://github.com/gramineproject/gramine/commit/a7f46aab10364cfd18565fe803a806405043210a.

___

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)* status: 1 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1892#-NycH3qa3JZKxX_fIxZ2:-NyjrME9Ahwll7tJOWL8:b618qux) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> but I don't know any easy workaround/fix for that.

Isn't the easy workaround be just removing it? Pls see https://github.com/gramineproject/gramine/commit/a7f46aab10364cfd18565fe803a806405043210a.
</blockquote></details>

We'd lose syntax highlighting on RTD then. So, I additionally I converted the code blocks (only those which actually had something highlightable), let's see if it works now.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/howto-doc.rst` line 135 at r3](https://reviewable.io/reviews/gramineproject/gramine/1892#-NyuEpWtEwialSG0spN5:-NyuEpWtEwialSG0spN6:b-oyhtvp) ([raw file](https://github.com/gramineproject/gramine/blob/2dd925758d42316101949ced4f27f4ab5f89bef1/Documentation/devel/howto-doc.rst#L135)):*
> ```reStructuredText
>   this for files processed also by other software (like ``README.rst``, which
>   is both rendered by GitHub and included in ``index.rst``) - GitHub renders
>   those spaces incorrectly.
> ```

(nb) Since this is another such SNAFU from GitHub in about a month (see #1854), I wonder if we shouldn't rewrite README and CONTRIBUTING in markdown, because GitHub looks like optimising for markdown only, and getting bugs in other markup languages it nominally supports.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`Documentation/devel/howto-doc.rst` line 135 at r3](https://reviewable.io/reviews/gramineproject/gramine/1892#-NyuEpWtEwialSG0spN5:-Nz1-qkM2vVMnyWr8SRt:btorl9e) ([raw file](https://github.com/gramineproject/gramine/blob/2dd925758d42316101949ced4f27f4ab5f89bef1/Documentation/devel/howto-doc.rst#L135)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

(nb) Since this is another such SNAFU from GitHub in about a month (see #1854), I wonder if we shouldn't rewrite README and CONTRIBUTING in markdown, because GitHub looks like optimising for markdown only, and getting bugs in other markup languages it nominally supports.
</blockquote></details>

For the record: we briefly discussed this on the Gramine call and decided that we'll go with the Markdown rewrite if we get into such an issue again.

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1892)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
