### PR TITLE
[packaging] Add source of official Gramine docker image

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
It was used to build https://hub.docker.com/r/gramineproject/gramine

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/797)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/797)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/797)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/797#-N7yl-vjDyJLV1RBZDNQ:-N7yl-vjDyJLV1RBZDNR:bqy7pxn) (no related file):*
Is `packaging/` what we want? Maybe under already-existing `tools/`? Or at least `Packaging/` with a capital letter (as it is more of a "metadata" thing).

___
___
*[`packaging/docker/Dockerfile` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/797#-N7ykaUPBX6-A893Oatq:-N7ykaUPBX6-A893Oatr:bfbw65d) ([raw file](https://github.com/gramineproject/gramine/blob/cce16850fd580fa72528982ee5aa3ba092478f1d/packaging/docker/Dockerfile#L20)):*
> ```Dockerfile
>     libsgx-aesm-quote-ex-plugin \
>     libsgx-aesm-ecdsa-plugin \
>     libsgx-dcap-quote-verify \
> ```

FYI: We converged on this minimal set of SGX packages by reading the Intel SGX SDK/PSW/DCAP docs and with some trial-and-error.
___
*[`packaging/docker/Dockerfile` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/797#-N7ykXkD-DDYPBhmdZ5E:-N7ykXkD-DDYPBhmdZ5F:by0f03o) ([raw file](https://github.com/gramineproject/gramine/blob/cce16850fd580fa72528982ee5aa3ba092478f1d/packaging/docker/Dockerfile#L21)):*
> ```Dockerfile
>     libsgx-aesm-ecdsa-plugin \
>     libsgx-dcap-quote-verify \
>     psmisc
> ```

FYI: This package is needed for `killall` in `restart_aesm.sh`

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/797)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/797#-N7yl-vjDyJLV1RBZDNQ:-N83VCdgE6tBUmbeeyB3:baabkl2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is `packaging/` what we want? Maybe under already-existing `tools/`? Or at least `Packaging/` with a capital letter (as it is more of a "metadata" thing).
</blockquote></details>

I thought having one directory for all kinds of packages/images was a good idea. Putting this into `tools/` would also be fine with me.
As for capital letter - I don't mind either, but I would prefer small letter - it's not more metadata than `tools` are.
cc @mkow 

___

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/797)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/797#-N7yl-vjDyJLV1RBZDNQ:-N840u5e3NET20YKmKaV:b-99t0ok) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I thought having one directory for all kinds of packages/images was a good idea. Putting this into `tools/` would also be fine with me.
As for capital letter - I don't mind either, but I would prefer small letter - it's not more metadata than `tools` are.
cc @mkow 
</blockquote></details>

`tools` sounds weird for this, it's rather a way of packaging Gramine (i.e. wrapping in something).
Also, I don't think it's "metadata", whatever this term means in case of codebase. Are our build files metadata? So, I'd just go with `packaging`.

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/797)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/797#-N7yl-vjDyJLV1RBZDNQ:-N843s9o6-U2Lxf7mSyQ:b-71vnra) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`tools` sounds weird for this, it's rather a way of packaging Gramine (i.e. wrapping in something).
Also, I don't think it's "metadata", whatever this term means in case of codebase. Are our build files metadata? So, I'd just go with `packaging`.
</blockquote></details>

Ok, then I'm also fine.

___

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/797)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/797)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
