### PR TITLE
Release 1.5

### PR DESCRIPTION
**Pull request by woju**
This is release PR for 1.5. Will be rebased and updated accordingly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1437)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1437)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZDs8eo5I653-moqcOc:-NZDs8eo5I653-moqcOd:b-kczh16) (no related file):*
We also need a commit bumping the version to post-release.

___
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZDsH8v3qzTziR0ZiqP):*
Please change to the format we used in previous releases.
___
*[`debian/changelog` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZDsik62HDMNDvfY5tM:-NZDsik62HDMNDvfY5tN:b49e6xw) ([raw file](https://github.com/gramineproject/gramine/blob/d18632cef8ee6d50db9f7e7f01203c5125ddf59d/debian/changelog#L3)):*
> ```
> gramine (1.5~rc2) unstable-bookworm unstable-bullseye unstable-jammy unstable-focal; urgency=medium
> 
>   * test release
> ```

This will need to be updated.

**Review by kailun-qin — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1437)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1437)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZDs8eo5I653-moqcOc:-NZF2KPlE6pZ0TO-ouuq:by802ee) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We also need a commit bumping the version to post-release.
</blockquote></details>

+1, and the commit message we write is like this: `Bump Gramine version to 1.4post~UNRELEASED`

___
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZDsH8v3qzTziR0ZiqP):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please change to the format we used in previous releases.
</blockquote></details>

Which is like this: `Bump Gramine version to 1.4`
___
*[`debian/changelog` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZF2WMXC7TmqNQAo51f:-NZF2WMXC7TmqNQAo51g:bemkdah) ([raw file](https://github.com/gramineproject/gramine/blob/d18632cef8ee6d50db9f7e7f01203c5125ddf59d/debian/changelog#L3)):*
> ```
> gramine (1.5~rc2) unstable-bookworm unstable-bullseye unstable-jammy unstable-focal; urgency=medium
> 
>   * test release
> ```

Do you plan to add changes? I guess there were none for Debian packages?

**Comment by mgild** [comment]
Very excited!

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1437)* status: 1 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZDs8eo5I653-moqcOc:-NZjZBm64MX-YDDwBjpZ:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, and the commit message we write is like this: `Bump Gramine version to 1.4post~UNRELEASED`
</blockquote></details>

Done.

___
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZDsH8v3qzTziR0ZiqP):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Which is like this: `Bump Gramine version to 1.4`
</blockquote></details>

Done.
___
*[`debian/changelog` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZF2WMXC7TmqNQAo51f:-NZjZ0p30vtnptRs-wqA:b-lx22tm) ([raw file](https://github.com/gramineproject/gramine/blob/d18632cef8ee6d50db9f7e7f01203c5125ddf59d/debian/changelog#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you plan to add changes? I guess there were none for Debian packages?
</blockquote></details>

Added. There were some small changes in dependencies.
___
*[`debian/changelog` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1437#-NZDsik62HDMNDvfY5tM:-NZjZ6Wr6rcow-orcKIK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d18632cef8ee6d50db9f7e7f01203c5125ddf59d/debian/changelog#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This will need to be updated.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1437)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1437)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
