### PR TITLE
[Meson] Allow building with `-Dglibc=disabled`

### LINKED ISSUE #1399: [Meson] Build fails when `meson setup -Dglibc=disabled`
### Description of the problem

This is because of the following snippets:

- https://github.com/gramineproject/gramine/blob/514df189a6867c92dac83923649cd2a124866e62/subprojects/packagefiles/mbedtls/meson.build#L58-L63

- https://github.com/gramineproject/gramine/blob/514df189a6867c92dac83923649cd2a124866e62/tools/sgx/ra-tls/meson.build#L31-L34 (and several more in this file)

### Steps to reproduce

This was detected on Alpine 3.18.0, on which there is no Glibc (https://ariadne.space/2021/08/26/there-is-no-such-thing-as-a-glibc-based-alpine-image/). So we have no choice but to use `-Dglibc=disabled`.

And anyway, it would be totally misleading for Gramine to have Glibc-based RA-TLS and mbedTLS libs by default on something like Alpine OS.

### Expected results

Bla

### Actual results

Bla

### Gramine commit hash

514df189a6867c92dac83923649cd2a124866e62

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously mbedTLS and RA-TLS libs depended on Glibc being enabled (even if building on musl-only OS distro like Alpine). With this commit, if Glibc is disabled, then mbedTLS and RA-TLS installation scripts install musl-linked versions of these libs.

Fixes #1399. Closes #1417.

## How to test this PR? 

Manually on Alpine. Also, CI (glibc-based) must not break.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`subprojects/packagefiles/mbedtls/meson_options.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1400#-NY2z1LnEciNzMslB9q_:-NY2z1LnEciNzMslB9qa:b-5w6b9w) ([raw file](https://github.com/gramineproject/gramine/blob/4294634ab3978ff2e651dab77bda27e83788d9c5/subprojects/packagefiles/mbedtls/meson_options.txt#L1)):*
> ```Meson
> option('glibc', type: 'combo', choices: ['disabled', 'enabled'], value: 'enabled', yield: true)
> ```

FYI: This is to get the `glibc` variable from the super-project (which is Gramine). Taken from https://mesonbuild.com/Build-options.html#yielding-to-superproject-option

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: 1 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`subprojects/packagefiles/mbedtls/meson.build` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1400#-NY3wySh6bGNmy7Do1d9:-NYHSENY87TENi2DWEqJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4294634ab3978ff2e651dab77bda27e83788d9c5/subprojects/packagefiles/mbedtls/meson.build#L58)):*
> ```Meson
> )
> 
> # if Glibc is enabled, then make default mbedTLS libs Glibc-linked (even if musl is also enabled);
> ```

Done.
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/1400#-NY3xHMqCt7L61Jtb2kV:-NYHT0t1D0INMTVDMDbf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4294634ab3978ff2e651dab77bda27e83788d9c5/subprojects/packagefiles/mbedtls/meson.build#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rather do an if-else cascade and fail if neither `get_option('glibc')` nor `get_option('musl')` is enabled. This is to notice this place in the future if we ever add some other libcs.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/meson.build` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1400#-NY3xcYQ4w_kqPMbCJNR:-NYHTGfUERwPsjhfm4Ie:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4294634ab3978ff2e651dab77bda27e83788d9c5/tools/sgx/ra-tls/meson.build#L11)):*
> ```Meson
> libra_tls_inc = include_directories('.')
> 
> # if Glibc is enabled, then make default RA-TLS libs Glibc-linked (even if musl is also enabled);
> ```

Done.
___
*[`tools/sgx/ra-tls/meson.build` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/1400#-NY3x_Oy-s_6WanI4FVP:-NYHTGzs1SHlIXnAlrAA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4294634ab3978ff2e651dab77bda27e83788d9c5/tools/sgx/ra-tls/meson.build#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: 2 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`subprojects/packagefiles/mbedtls/meson_options.txt` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/1400#-NYHbDs165FK9xqbp5wS:-NYHhAFACLb1qo1d3H5C:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/6412dd91736aa696db0d86248df9b870d1ebe738/subprojects/packagefiles/mbedtls/meson_options.txt#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Not blocking, but maybe better to add a note here (in case that we forget about it) that we need to update once the option type from the super-project is changed to type `feature`, see https://github.com/gramineproject/gramine/blob/702ac42f81452b288b66b00308763584c3d115d3/meson_options.txt#L1.
</blockquote></details>

Done

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`subprojects/packagefiles/mbedtls/meson_options.txt` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/1400#-NYHbDs165FK9xqbp5wS:-NYLSfPE7SPuo_kumGlS:b-ucfknh) ([raw file](https://github.com/gramineproject/gramine/blob/6412dd91736aa696db0d86248df9b870d1ebe738/subprojects/packagefiles/mbedtls/meson_options.txt#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks!

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`subprojects/packagefiles/mbedtls/meson.build` line 58 at r3](https://reviewable.io/reviews/gramineproject/gramine/1400#-NYNM9fr0nZ32EIO7Frk:-NYNUMxVAs2pJgMbIhWZ:bkd9st) ([raw file](https://github.com/gramineproject/gramine/blob/88ede3230d2889b55d097be591f73988456852b8/subprojects/packagefiles/mbedtls/meson.build#L58)):*
> How symlinking those libs into runtimedir makes them "glibc-linked"?

Maybe my phrasing in the comment is wrong. What I mean is that Gramine build process will generate shared libs (in this case, mbedTLS libs) with a default compiler which will link against the default libc (which e.g. on Ubuntu is Glibc, and on Alpine is Musl).

Since we don't really know what the default compiler links against (well, maybe there's a way to learn this? I didn't find a robust way), I'm having this heuristic -- if the user is building with Glibc enabled, then this is almost certainly the default libc; if the user is building with Glibc disabled and Musl enabled, then Musl is almost certainly the default libc.

> Is there some difference in the compiled binaries?

It's very hard to tell whether shared libs built against Musl with just work with Glibc, and vice versa... From what I know, this is a no-no, and people should never assume that Musl and Glibc are interchangeable. So it's better to *assume* that there is a difference in compiled binaries.

> You should, for each of the provided libcs, check if it's enabled and then symlink the file into respective runtimedir (or not symlink, if the libc is not provided).

Symlink **which file**? We generate only one file, which maybe will be linked against Glibc and maybe against Musl (depending on the default compiler).

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`subprojects/packagefiles/mbedtls/meson.build` line 58 at r3](https://reviewable.io/reviews/gramineproject/gramine/1400#-NYNM9fr0nZ32EIO7Frk:-NYOPZehB-hDEaQHDBph:b-mtjvvi) ([raw file](https://github.com/gramineproject/gramine/blob/88ede3230d2889b55d097be591f73988456852b8/subprojects/packagefiles/mbedtls/meson.build#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> How symlinking those libs into runtimedir makes them "glibc-linked"?

Maybe my phrasing in the comment is wrong. What I mean is that Gramine build process will generate shared libs (in this case, mbedTLS libs) with a default compiler which will link against the default libc (which e.g. on Ubuntu is Glibc, and on Alpine is Musl).

Since we don't really know what the default compiler links against (well, maybe there's a way to learn this? I didn't find a robust way), I'm having this heuristic -- if the user is building with Glibc enabled, then this is almost certainly the default libc; if the user is building with Glibc disabled and Musl enabled, then Musl is almost certainly the default libc.

> Is there some difference in the compiled binaries?

It's very hard to tell whether shared libs built against Musl with just work with Glibc, and vice versa... From what I know, this is a no-no, and people should never assume that Musl and Glibc are interchangeable. So it's better to *assume* that there is a difference in compiled binaries.

> You should, for each of the provided libcs, check if it's enabled and then symlink the file into respective runtimedir (or not symlink, if the libc is not provided).

Symlink **which file**? We generate only one file, which maybe will be linked against Glibc and maybe against Musl (depending on the default compiler).
</blockquote></details>

OK. So two points: 1) if a single compilation of mbedtls is linked against specific libc (either it really is, or we don't know and assume it is, as you've written), don't we really need this compiled twice, once per each libc? Wouldn't that be the correct solution?

Also, 2) looking at meson.build and/or those `compile.sh` scripts, how do you know that if you select both, then mbedtls is compiled against glibc and not musl?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`subprojects/packagefiles/mbedtls/meson.build` line 58 at r3](https://reviewable.io/reviews/gramineproject/gramine/1400#-NYNM9fr0nZ32EIO7Frk:-NYRecheDovYGUM2CcU1:b7wfgkl) ([raw file](https://github.com/gramineproject/gramine/blob/88ede3230d2889b55d097be591f73988456852b8/subprojects/packagefiles/mbedtls/meson.build#L58)):*
> 1) if a single compilation of mbedtls is linked against specific libc (either it really is, or we don't know and assume it is, as you've written), don't we really need this compiled twice, once per each libc? Wouldn't that be the correct solution?

Yes, but how to compile twice? For Glibc-based distros (e.g. Ubuntu) we use the hack of `musl-gcc` for tests: https://github.com/gramineproject/gramine/blob/fdd3417b490ea0c287fb967432509b09161eb7f3/libos/test/regression/meson.build#L211-L221

For Musl-based distros (Alpine), iiuc, there is no way to compile against Glibc whatsoever.

> 2) looking at meson.build and/or those `compile.sh` scripts, how do you know that if you select both, then mbedtls is compiled against glibc and not musl?

Simply because of my assumption: if the user selected Glibc, then it can't be a Musl-based distro, so the default compilation is against Glibc. A corrolary: if the user disabled Glibc, then it must be a Musl-based distro, so the default compilation is against Musl.

---

I know this sounds hacky as hell... From what I gathered, everything Musl-related requires some hacks.

**Review by mkow — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`subprojects/packagefiles/mbedtls/meson.build` line 58 at r3](https://reviewable.io/reviews/gramineproject/gramine/1400#-NYNM9fr0nZ32EIO7Frk:-NYVgaQC-bNV8HwZQy6S:b9hnc19) ([raw file](https://github.com/gramineproject/gramine/blob/88ede3230d2889b55d097be591f73988456852b8/subprojects/packagefiles/mbedtls/meson.build#L58)):*
> It's very hard to tell whether shared libs built against Musl with just work with Glibc, and vice versa... From what I know, this is a no-no, and people should never assume that Musl and Glibc are interchangeable. So it's better to _assume_ that there is a difference in compiled binaries.

Yes. AFAIR officially (and surely in practice also) musl and glibc are not binary compatible.
___
*[`subprojects/packagefiles/mbedtls/meson_options.txt` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1400#-NYVhzR17GOFngPR-nHW:-NYVhzR17GOFngPR-nHX:b-5znelx) ([raw file](https://github.com/gramineproject/gramine/blob/88ede3230d2889b55d097be591f73988456852b8/subprojects/packagefiles/mbedtls/meson_options.txt#L2)):*
> ```Meson
> # TODO: after deprecating 18.04/bionic, change these to type: 'feature'
> #       see also top-level meson_options.txt
> ```

But we've already deprecated it?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`subprojects/packagefiles/mbedtls/meson_options.txt` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1400#-NYVhzR17GOFngPR-nHW:-NYaviFr77NUGmbC5Cwn:b-f49spf) ([raw file](https://github.com/gramineproject/gramine/blob/88ede3230d2889b55d097be591f73988456852b8/subprojects/packagefiles/mbedtls/meson_options.txt#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But we've already deprecated it?
</blockquote></details>

True, but I took it from here: https://github.com/gramineproject/gramine/blob/2ab91453374dc03a444e2940c295560ac9cbf178/meson_options.txt#L1

This looks like an orthogonal problem, I wouldn't want to deal with it in this PR.

But let me cook an independent PR that removes this TODO.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1400)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`subprojects/packagefiles/mbedtls/meson_options.txt` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1400#-NYVhzR17GOFngPR-nHW:-NYb9ev21IjcDsy1psEh:biuz2e) ([raw file](https://github.com/gramineproject/gramine/blob/88ede3230d2889b55d097be591f73988456852b8/subprojects/packagefiles/mbedtls/meson_options.txt#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

True, but I took it from here: https://github.com/gramineproject/gramine/blob/2ab91453374dc03a444e2940c295560ac9cbf178/meson_options.txt#L1

This looks like an orthogonal problem, I wouldn't want to deal with it in this PR.

But let me cook an independent PR that removes this TODO.
</blockquote></details>

Done, see https://github.com/gramineproject/gramine/pull/1414.

Depending on which PR will be merged first, I will change the other PR accordingly. Let me put a blocking comment here.

**Comment by dimakuv** [comment]
Superseded by #1427

**Pull request closed without merging**
