### PR TITLE
[LibOS] Refactor eventfd implementation and corresponding tests

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This PR refactors eventfd code, in preparation for a second, secure (not passthrough-to-host) implementation of eventfd. The corresponding `eventfd` test is split into two tests: a single-process test and a new multi-process (forking) test. This is because the new secure implementation of eventfd will only be applicable to single-process applications.

For context, see:
- https://github.com/gramineproject/gramine/discussions/1713
- https://github.com/gramineproject/gramine/discussions/1413

## How to test this PR? 

CI. No functional change.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: 0 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/fs/eventfd/fs.c` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-NokqullD-iTNKqKimgy:-NokqullD-iTNKqKimgz:b9jvn5d) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/src/fs/eventfd/fs.c#L24)):*
> ```C
>     int ret = PalStreamRead(hdl->pal_handle, /*offset=*/0, &count, buf);
>     ret = pal_to_unix_errno(ret);
>     maybe_epoll_et_trigger(hdl, ret, /*in=*/true, ret == 0 ? count < orig_count : false);
> ```

Working: the last arg is `is_partial` and it is never used for eventfd handles. So can just put a dummy `false` here.
___
*[`libos/src/fs/eventfd/fs.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Nokr2BoCWEGATDBM0HM:-Nokr2BoCWEGATDBM0HN:b9jvn5d) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/src/fs/eventfd/fs.c#L42)):*
> ```C
>     int ret = PalStreamWrite(hdl->pal_handle, /*offset=*/0, &count, (void*)buf);
>     ret = pal_to_unix_errno(ret);
>     maybe_epoll_et_trigger(hdl, ret, /*in=*/false, ret == 0 ? count < orig_count : false);
> ```

Working: the last arg is `is_partial` and it is never used for eventfd handles. So can just put a dummy `false` here.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/test/regression/eventfd.c` line 125 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-NolRUTZ1HMrb4u3y9tA:-NolRUTZ1HMrb4u3y9tB:b-3uoey3) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd.c#L125)):*
> ```C
>         printf("%s completed successfully\n", __func__);
>     else
>         printf("%s: nread_events: %d, MAX_EFDS: %d\n", __func__, nread_events, MAX_EFDS);
> ```

TODO: This is actually a failure, must `return 1` here.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: 0 of 10 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/sys/libos_eventfd.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-NomkIuV3lyPgpDfXvsQ:-NomkIuV3lyPgpDfXvsR:b-sfglhl) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/src/sys/libos_eventfd.c#L22)):*
> ```C
> static bool g_eventfd_passthrough_mode = false;
> 
> static int init_eventfd_mode(void) {
> ```

TODO: In a follow up PR, I ended up moving this as `RUN_INIT()`. Do the same in this PR.

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/sys/libos_eventfd.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-NomkIuV3lyPgpDfXvsQ:-Noo93hQ7N4-C2cw4u_q:byt7f9d) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/src/sys/libos_eventfd.c#L22)):*
> In a follow up PR, I ended up moving this as `RUN_INIT()`

Why not in this PR?
___
*[`libos/test/regression/eventfd.c` line 62 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Noo5EZV67nPyQG3XJgs:-Noo5EZV67nPyQG3XJgt:bi49xu6) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd.c#L62)):*
> ```C
> /* This function used to test polling on a group of eventfd descriptors.
>  * To support regression testing, positive value returned for error case. */
> static int eventfd_using_poll(void) {
> ```

hmm... I'm not blocking and I understand it might be easier for review.

But since we've already been refactoring this test and we rewrote the `eventfd_fork` part to conform w/ the latest style, should we do the same for `eventfd_using_poll` and `eventfd_using_various_flags`?
___
*[`libos/test/regression/eventfd.c` line 228 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Noo4mT-3seT6fynL4Dy:-Noo4mT-3seT6fynL4Dz:bb7mv2h) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd.c#L228)):*
> ```C
>     }
> 
>     printf("TEST OK\n");
> ```

puts



_Code quote:_
```C
printf
```
___
*[`libos/test/regression/eventfd_fork.c` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Noo4hs_-YnGIZLLKeCp:-Noo4hs_-YnGIZLLKeCq:bb7mv2h) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd_fork.c#L38)):*
> ```C
> 
>     CHECK(close(efd));
>     printf("TEST OK\n");
> ```

puts



_Code quote:_
```C
printf("TEST OK\n");
```
___
*[`libos/test/regression/eventfd_fork.manifest.template` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Noo2z9oCJarSt3E33JC:-Noo2z9oCJarSt3E33JD:b-9b5yc9) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd_fork.manifest.template#L1)):*
> ```
> loader.entrypoint = "file:{{ gramine.libos }}"
> ```

May I know why we also separate the manifest template in this PR? Is this for the 2nd/following PR?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: 6 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/fs/eventfd/fs.c` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-NokqullD-iTNKqKimgy:-NoqRH6_2kD9JZxVQoCQ:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/src/fs/eventfd/fs.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Working: the last arg is `is_partial` and it is never used for eventfd handles. So can just put a dummy `false` here.
</blockquote></details>

Done
___
*[`libos/src/fs/eventfd/fs.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Nokr2BoCWEGATDBM0HM:-NoqRHieD-kl3Yze01al:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/src/fs/eventfd/fs.c#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Working: the last arg is `is_partial` and it is never used for eventfd handles. So can just put a dummy `false` here.
</blockquote></details>

Done
___
*[`libos/src/sys/libos_eventfd.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-NomkIuV3lyPgpDfXvsQ:-NoqRJ2n3wcaz6P05hDG:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/src/sys/libos_eventfd.c#L22)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> In a follow up PR, I ended up moving this as `RUN_INIT()`

Why not in this PR?
</blockquote></details>

Done
___
*[`libos/test/regression/eventfd.c` line 62 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Noo5EZV67nPyQG3XJgs:-NoqVS_rCBVQDbpBzyTP:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd.c#L62)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

hmm... I'm not blocking and I understand it might be easier for review.

But since we've already been refactoring this test and we rewrote the `eventfd_fork` part to conform w/ the latest style, should we do the same for `eventfd_using_poll` and `eventfd_using_various_flags`?
</blockquote></details>

Done
___
*[`libos/test/regression/eventfd.c` line 125 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-NolRUTZ1HMrb4u3y9tA:-NoqVRlr8wmAGGmBQeoi:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd.c#L125)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: This is actually a failure, must `return 1` here.
</blockquote></details>

Done
___
*[`libos/test/regression/eventfd.c` line 228 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Noo4mT-3seT6fynL4Dy:-NoqVQiXCp9_5TktELyZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd.c#L228)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

puts
</blockquote></details>

Done.
___
*[`libos/test/regression/eventfd_fork.c` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Noo4hs_-YnGIZLLKeCp:-NoqSH6q8FEj-10udZjb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd_fork.c#L38)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

puts
</blockquote></details>

Done.
___
*[`libos/test/regression/eventfd_fork.manifest.template` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1727#-Noo2z9oCJarSt3E33JC:-NoqVZsW0yf-kAeOEg3Y:b3of8jt) ([raw file](https://github.com/gramineproject/gramine/blob/9e84954699e4f297970194aef567b3097f7da11f/libos/test/regression/eventfd_fork.manifest.template#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

May I know why we also separate the manifest template in this PR? Is this for the 2nd/following PR?
</blockquote></details>

Yes, it's for the second PR: https://github.com/gramineproject/gramine/pull/1728

We need to split the original `eventfd` file because it has 3 sub-tests:
- 2 sub-tests are single-process and can be implemented in a "secure eventfd" (see new PR)
- 1 sub-test is multi-process (with `fork()`) and can only be implemented in a "insecure eventfd"

So we need to separate into two.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/include/libos_internal.h` line 154 at r2](https://reviewable.io/reviews/gramineproject/gramine/1727#-NtTMCnQ1xrmomDq31QW:-NtTMCnQ1xrmomDq31QX:bd7zf23) ([raw file](https://github.com/gramineproject/gramine/blob/f96eb8b30fa5a26b889b56aa5606b4fba0060734/libos/include/libos_internal.h#L154)):*
> ```objc
> int set_hostname(const char* name, size_t len);
> 
> extern bool g_eventfd_passthrough_mode;
> ```

I assume you made it global because some future changes require that?
___
*[`libos/src/fs/eventfd/fs.c` line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/1727#-NtTGx8K3ksOsluopIPX:-NtTGx8K3ksOsluopIPY:b-3m1fbs) ([raw file](https://github.com/gramineproject/gramine/blob/f96eb8b30fa5a26b889b56aa5606b4fba0060734/libos/src/fs/eventfd/fs.c#L23)):*
> ```C
>     int ret = PalStreamRead(hdl->pal_handle, /*offset=*/0, &count, buf);
>     ret = pal_to_unix_errno(ret);
>     maybe_epoll_et_trigger(hdl, ret, /*in=*/true, /*unused was_partial=*/false);
> ```

Why is it unused? Could you explain briefly in the comment? It's not obvious to me.
Also, why removing the check for partial read? What if a partial read happens?
___
*[`libos/src/fs/eventfd/fs.c` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1727#-NtTHuFoAy3UC4egAFm-:-NtTHuFoAy3UC4egAFm0:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f96eb8b30fa5a26b889b56aa5606b4fba0060734/libos/src/fs/eventfd/fs.c#L36)):*
> ```C
>     int ret = PalStreamWrite(hdl->pal_handle, /*offset=*/0, &count, (void*)buf);
>     ret = pal_to_unix_errno(ret);
>     maybe_epoll_et_trigger(hdl, ret, /*in=*/false, /*unused was_partial=*/false);
> ```

ditto
___
*[`libos/src/sys/libos_eventfd.c` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/1727#-NtTLCUp66xJZMQinBvU:-NtTLCUp66xJZMQinBvV:bqvppds) ([raw file](https://github.com/gramineproject/gramine/blob/a933017d35a7aa3330194521389838de6be53dc4/libos/src/sys/libos_eventfd.c#L26)):*
> ```C
>     bool allow_eventfd;
>     ret = toml_bool_in(g_manifest_root, "sys.insecure__allow_eventfd", /*defaultval=*/false,
>                        &allow_eventfd);
> ```

Huh, this was called on each handle creation? :man_facepalming:
___
*[`libos/test/regression/eventfd.c` line 100 at r2](https://reviewable.io/reviews/gramineproject/gramine/1727#-NtTSbi23gyZtHTBVVaM:-NtTSbi23gyZtHTBVVaN:b-hf7sc4) ([raw file](https://github.com/gramineproject/gramine/blob/f96eb8b30fa5a26b889b56aa5606b4fba0060734/libos/test/regression/eventfd.c#L100)):*
> ```C
>         CHECK(close(efds[i]));
> 
> 	printf("%s completed successfully\n", __func__);
> ```

tab -> spaces
___
*[`libos/test/regression/eventfd_fork.manifest.template` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1727#-NtTUOtN7S6YyUi0yiGi:-NtTUOtN7S6YyUi0yiGj:bk0ocef) ([raw file](https://github.com/gramineproject/gramine/blob/f96eb8b30fa5a26b889b56aa5606b4fba0060734/libos/test/regression/eventfd_fork.manifest.template#L5)):*
> ```
> 
> loader.env.LD_LIBRARY_PATH = "/lib"
> loader.insecure__use_cmdline_argv = true
> ```

This doesn't seem to be needed?

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/include/libos_internal.h` line 154 at r2](https://reviewable.io/reviews/gramineproject/gramine/1727#-NtTMCnQ1xrmomDq31QW:-NuU0n9dAJVmNECsO60H:bpyk7qn) ([raw file](https://github.com/gramineproject/gramine/blob/f96eb8b30fa5a26b889b56aa5606b4fba0060734/libos/include/libos_internal.h#L154)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, it's for the future PR. See this in particular: https://github.com/gramineproject/gramine/pull/1728/files#diff-3ddd94d8578799cf98eaa0c49c55b2e97a42a63cd4475069772929138a8d6244

I.e., this variable will be used in `libos_clone.c` as well.

But I can remove it from here and make static, to make this PR more self-contained.
</blockquote></details>

Nah, it's fine.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
