### PR TITLE
[LibOS] Implement {,l,f}getxattr and {,l,f}listxattr

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

This PR implements getxattr, lgetxattr, fgetxattr, listxattr, llistxattr and flistxattr.

They aren't too useful because Gramine neither supports mounting files with xattrs nor setting them, but at least it makes some programs generate less warnings (e.g. `ls -l`).

## How to test this PR? 

Run `ls -l` under Bash in Gramine with and without this PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`Documentation/devel/features.md` line 738 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31rNQQCY0SVqIsiDvc:-O31rNQQCY0SVqIsiDvd:b-hohg7c) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/Documentation/devel/features.md#L738)):*
> ```Markdown
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> 
> - ☑ `getxattr()`
> ```

These are dummy... Don't we want to mark them with a dot, not with a "Ok mark"?
___
*[`Documentation/devel/features.md` line 3104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31r1QsA6G_Mng4Eqxx:-O31r1QsA6G_Mng4Eqxy:bfqn1vo) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/Documentation/devel/features.md#L3104)):*
> ```Markdown
>   `lsetxattr()`, `fsetxattr()`, `removexattr()`, `lremovexattr()`, `fremovexattr()`.
>   Reading is supported (`getxattr()`, `lgetxattr()`, `fgetxattr()`, `listxattr()`, `llistxattr()`,
>   `flistxattr()`) but always returns no attributes (which is a correct result in our case).
> ```

I don't like that these syscalls are here, under `advanced/infeasible` features. Wouldn't it be better to move them to "File system operations"?
___
*[`libos/include/libos_fs.h` line 629 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31rZ791OMPcUIEHxUg:-O31rZ7A7b7lh3jS1hKy:b-ng83f7) ([raw file](https://github.com/gramineproject/gramine/blob/4a5c4a1019a06571857e93e6b395774497cc1939/libos/include/libos_fs.h#L629)):*
> ```objc
>  *
>  * The caller should hold `g_dcache_lock`. If you do not already hold `g_dcache_lock`, use
>  * `path_lookupat` instead.
> ```

Looks like a totally bogus comment, right? This comment already belongs to the func `path_lookupat()`. Any idea why it was here?
___
*[`libos/src/sys/libos_stat.c` line 311 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31t3Ia8HzRGcODH1rf:-O31t3Ia8HzRGcODH1rg:b-8f9te5) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/libos/src/sys/libos_stat.c#L311)):*
> ```C
>                             size_t value_size) {
>     if (!is_user_string_readable(path) || !is_user_string_readable(name)
>             || !is_user_memory_writable(value, value_size))
> ```

I'm not sure this function will work as expected if `value_size == 0`. Can you add an additional check on this (and maybe put it as a separate IF statement)?
___
*[`libos/src/sys/libos_stat.c` line 326 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31tKOmC1dWRmaUkQ0Y:-O31tKOmC1dWRmaUkQ0Z:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/libos/src/sys/libos_stat.c#L326)):*
> ```C
>                              size_t value_size) {
>     if (!is_user_string_readable(path) || !is_user_string_readable(name)
>         || !is_user_memory_writable(value, value_size))
> ```

ditto
___
*[`libos/src/sys/libos_stat.c` line 339 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31tNzlEE1BYyVcZRT-:-O31tNzlEE1BYyVcZRT0:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/libos/src/sys/libos_stat.c#L339)):*
> ```C
> 
> long libos_syscall_fgetxattr(int fd, const char* name, void* value, size_t value_size) {
>     if (!is_user_string_readable(name) || !is_user_memory_writable(value, value_size))
> ```

ditto
___
*[`libos/src/sys/libos_stat.c` line 353 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31tWAw2vWGASZS53wG:-O31tWAw2vWGASZS53wH:bp0crhm) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/libos/src/sys/libos_stat.c#L353)):*
> ```C
> 
> long libos_syscall_listxattr(const char* path, char* list, size_t list_size) {
>     if (!is_user_string_readable(path) || !is_user_memory_writable(list, list_size))
> ```

ditto (`list_size == 0`)
___
*[`libos/src/sys/libos_stat.c` line 366 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31tg8d4uNi7-7AxOeH:-O31tg8d4uNi7-7AxOeI:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/libos/src/sys/libos_stat.c#L366)):*
> ```C
> 
> long libos_syscall_llistxattr(const char* path, char* list, size_t list_size) {
>     if (!is_user_string_readable(path) || !is_user_memory_writable(list, list_size))
> ```

ditto

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`Documentation/devel/features.md` line 738 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31rNQQCY0SVqIsiDvc:-O3SbmqWABhUfeh1BTp-:bwv2ai7) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/Documentation/devel/features.md#L738)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These are dummy... Don't we want to mark them with a dot, not with a "Ok mark"?
</blockquote></details>

They are _not_ dummy. They return 100% correct answer, as there are no xattrs present. What's missing is setting xattrs, but those are other functions (which are marked here as not-implemented).
___
*[`Documentation/devel/features.md` line 3104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31r1QsA6G_Mng4Eqxx:-O3Sc6AXBAgC2XpwGoDA:b-dx24fu) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/Documentation/devel/features.md#L3104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like that these syscalls are here, under `advanced/infeasible` features. Wouldn't it be better to move them to "File system operations"?
</blockquote></details>

I don't care much, they are actually a bit "advanced" and not really needed for standard apps. But if you insist then I can move it ;)
___
*[`libos/include/libos_fs.h` line 629 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31rZ791OMPcUIEHxUg:-O3SchB5BjBx_hZlLph3:b9b4akr) ([raw file](https://github.com/gramineproject/gramine/blob/4a5c4a1019a06571857e93e6b395774497cc1939/libos/include/libos_fs.h#L629)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like a totally bogus comment, right? This comment already belongs to the func `path_lookupat()`. Any idea why it was here?
</blockquote></details>

What do you mean? This is a comment for `path_lookupat()`, which does indeed require that lock when calling it.
___
*[`libos/src/sys/libos_stat.c` line 311 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31t3Ia8HzRGcODH1rf:-O3SdZodCxjOXVok15Zt:b-ta2ldw) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/libos/src/sys/libos_stat.c#L311)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not sure this function will work as expected if `value_size == 0`. Can you add an additional check on this (and maybe put it as a separate IF statement)?
</blockquote></details>

It works correctly (which is IMO logical) and we don't have special IFs for 0 in most of other places?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`Documentation/devel/features.md` line 738 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31rNQQCY0SVqIsiDvc:-O3WLlfw01CSBHXslr_m:b-lx649c) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/Documentation/devel/features.md#L738)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

They are _not_ dummy. They return 100% correct answer, as there are no xattrs present. What's missing is setting xattrs, but those are other functions (which are marked here as not-implemented).
</blockquote></details>

Hm, ok, fair enough.
___
*[`Documentation/devel/features.md` line 3104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31r1QsA6G_Mng4Eqxx:-O3WLyJ14BqMNZbe4clR:b17juru) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/Documentation/devel/features.md#L3104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't care much, they are actually a bit "advanced" and not really needed for standard apps. But if you insist then I can move it ;)
</blockquote></details>

I think it's confusing that the text under the section title says "Gramine does not implement the following classes of features", but then you say "Reading is supported ...".

So yes, I think moving these funcs is better.
___
*[`libos/include/libos_fs.h` line 629 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31rZ791OMPcUIEHxUg:-O3WMH4e-uxuHqZn_2vC:b-4ejwtb) ([raw file](https://github.com/gramineproject/gramine/blob/4a5c4a1019a06571857e93e6b395774497cc1939/libos/include/libos_fs.h#L629)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean? This is a comment for `path_lookupat()`, which does indeed require that lock when calling it.
</blockquote></details>

I meant that this comment looks like it belonged to another function, and then was accidentally copied to this function. Anyway, that's some historical bug in refactoring code I guess, doesn't matter how this comment ended up here.
___
*[`libos/src/sys/libos_stat.c` line 311 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31t3Ia8HzRGcODH1rf:-O3WND4w3v4CKm4Q4bg8:b-svo1gw) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/libos/src/sys/libos_stat.c#L311)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It works correctly (which is IMO logical) and we don't have special IFs for 0 in most of other places?
</blockquote></details>

Well, currently this func returns `-ENODATA`, instead of `-ERANGE`. See the man page:
```
    ERANGE The size of the value buffer is too small to hold the result.
```

Note that `-EFAULT` is not returned, because `is_user_memory_writable(value, 0)` returns true.

But on the other hand, that's probably normal. We should return ENODATA ("I don't know what to do with this value"), rather than ERANGE ("I know this value, but I can't copy it into the user-supplied buffer"). Ok, I'm resolving, the current order of error codes makes sense.
___
*[`libos/src/sys/libos_stat.c` line 353 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31tWAw2vWGASZS53wG:-O3WNxPe2uqdq1MJ6I0i:biyig8e) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/libos/src/sys/libos_stat.c#L353)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`list_size == 0`)
</blockquote></details>

Resolving this as well, since `list_size == 0` is "enough to hold the result" which is always an empty list (with size 0).

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: 6 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/devel/features.md` line 3104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31r1QsA6G_Mng4Eqxx:-O3XGL3-6Mx_AOZzmoly:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/Documentation/devel/features.md#L3104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think it's confusing that the text under the section title says "Gramine does not implement the following classes of features", but then you say "Reading is supported ...".

So yes, I think moving these funcs is better.
</blockquote></details>

Done.
___
*[`libos/include/libos_fs.h` line 629 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31rZ791OMPcUIEHxUg:-O3XIY2oEuWY44glCGBf:b-c4qaka) ([raw file](https://github.com/gramineproject/gramine/blob/4a5c4a1019a06571857e93e6b395774497cc1939/libos/include/libos_fs.h#L629)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I meant that this comment looks like it belonged to another function, and then was accidentally copied to this function. Anyway, that's some historical bug in refactoring code I guess, doesn't matter how this comment ended up here.
</blockquote></details>

Ah, you mean the removed part of the comment. I thought you want me to also do something with that part about the lock.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/features.md` line 730 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf5127JyiKW21QE2w:-O3Xf5127JyiKW21QE2x:b-r4n573) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L730)):*
> ```Markdown
> 
> - ☒ `setxattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

Sorry, gotta change the `sup` here too :)
___
*[`Documentation/devel/features.md` line 733 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf6ZU9CsyhtlFwJ7a:-O3Xf6ZU9CsyhtlFwJ7b:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L733)):*
> ```Markdown
> 
> - ☒ `lsetxattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 736 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf7538Xfg6w64konv:-O3Xf7538Xfg6w64konw:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L736)):*
> ```Markdown
> 
> - ☒ `fsetxattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 739 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf7d050Zp8I6eesZF:-O3Xf7d050Zp8I6eesZG:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L739)):*
> ```Markdown
> 
> - ☑ `getxattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 742 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf2nHBBp7au2cReoV:-O3Xf2nHBBp7au2cReoW:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L742)):*
> ```Markdown
> 
> - ☑ `lgetxattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 745 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf3_i2zg8t4HXPrXQ:-O3Xf3_i2zg8t4HXPrXR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L745)):*
> ```Markdown
> 
> - ☑ `fgetxattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 748 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf8b_51GN9uiyM_6P:-O3Xf8b_51GN9uiyM_6Q:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L748)):*
> ```Markdown
> 
> - ☑ `listxattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 751 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf9Jk6BW92AF-GsHY:-O3Xf9Jk6BW92AF-GsHZ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L751)):*
> ```Markdown
> 
> - ☑ `llistxattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 754 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3XfA2MBIeew62CQeY2:-O3XfA2MBIeew62CQeY3:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L754)):*
> ```Markdown
> 
> - ☑ `flistxattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 757 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3XfA_C1-xbFJTTd93N:-O3XfA_C1-xbFJTTd93O:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L757)):*
> ```Markdown
> 
> - ☒ `removexattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 760 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3XfBFSEI50YgGID0Qb:-O3XfBFSEI50YgGID0Qc:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L760)):*
> ```Markdown
> 
> - ☒ `lremovexattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto
___
*[`Documentation/devel/features.md` line 763 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3XfBp945PgE0HofD9H:-O3XfBp945PgE0HofD9I:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L763)):*
> ```Markdown
> 
> - ☒ `fremovexattr()`
>   <sup>[24](#advancedinfeasible-unimplemented-features)</sup>
> ```

ditto

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: 6 of 7 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/devel/features.md` line 730 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf5127JyiKW21QE2w:-O3Xr5uc7ZbNdJ_j7lt3:b-7cf99b) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L730)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, gotta change the `sup` here too :)
</blockquote></details>

Oops, didn't notice this :grimacing:
___
*[`Documentation/devel/features.md` line 733 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf6ZU9CsyhtlFwJ7a:-O3XtHjB9QCPrEykeD9x:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L733)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 736 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf7538Xfg6w64konv:-O3XtLGG9eOIOtq5RUqI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L736)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 739 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf7d050Zp8I6eesZF:-O3XtM6Z6K44RSd8VPiP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L739)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 742 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf2nHBBp7au2cReoV:-O3XtMXT4Q-NabNRsamH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L742)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 745 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf3_i2zg8t4HXPrXQ:-O3XtNJ86PicZpnq0NBG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L745)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 748 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf8b_51GN9uiyM_6P:-O3XtNkv-6jtej5SB5IX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L748)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 751 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3Xf9Jk6BW92AF-GsHY:-O3XtOkR9xKVRAK8TVUZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L751)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 754 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3XfA2MBIeew62CQeY2:-O3XtPQN5_eeKOjrN7ts:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L754)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 757 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3XfA_C1-xbFJTTd93N:-O3XtPtL4u16SUyp0JAf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L757)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 760 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3XfBFSEI50YgGID0Qb:-O3XtQkf2Yp4wEFgK0VO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L760)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 763 at r2](https://reviewable.io/reviews/gramineproject/gramine/1957#-O3XfBp945PgE0HofD9H:-O3XtRB87HLwJKMu_97h:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/318567b39599aa5440acc13730acb60fbaf22af2/Documentation/devel/features.md#L763)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`libos/src/sys/libos_stat.c` line 311 at r1](https://reviewable.io/reviews/gramineproject/gramine/1957#-O31t3Ia8HzRGcODH1rf:-O3_6GWh7qZIGD8HiVUp:b-xi2g7s) ([raw file](https://github.com/gramineproject/gramine/blob/33dc8372eab5fb624d743483309b59c7e2fda1fd/libos/src/sys/libos_stat.c#L311)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, currently this func returns `-ENODATA`, instead of `-ERANGE`. See the man page:
```
    ERANGE The size of the value buffer is too small to hold the result.
```

Note that `-EFAULT` is not returned, because `is_user_memory_writable(value, 0)` returns true.

But on the other hand, that's probably normal. We should return ENODATA ("I don't know what to do with this value"), rather than ERANGE ("I know this value, but I can't copy it into the user-supplied buffer"). Ok, I'm resolving, the current order of error codes makes sense.
</blockquote></details>

But why would we return `-EFAULT`? There's no data, no-data fit into a zero-sized buffer totally fine :) (and there's even a special return code for that case)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1957)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
