### PR TITLE
[LibOS,Pal] Remove some dead code

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This PR removes unused `poll` callbacks in sockets, eventfd and pipe LibOS handles + all code that become dead as a result.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/488)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/488)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/488#-MzopQrKEsGSWG-olLzy):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow changed these fields recently. Michal, are they really unneeded?
</blockquote></details>

They were used by code which was removed in previous commits in this PR

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/488)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/488#-MzopQrKEsGSWG-olLzy):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, I understand this (you removed `stat_access()` which was the only caller of these fields). But would like an explicit ack from Michal -- you didn't remove these in your previous PR because you didn't look into who uses `stat_access()` and how?
</blockquote></details>

I guess the chain was not so simple, it was like `poll() -> handle_specific_poll_callback() -> PAL API call -> PAL handle spiecific callback -> stataccess()`, so you wouldn't spot it, unless you've started from `poll`.
ping @mkow confirm (or disconfirm) :)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/488)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/488#-MzopQrKEsGSWG-olLzy):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess the chain was not so simple, it was like `poll() -> handle_specific_poll_callback() -> PAL API call -> PAL handle spiecific callback -> stataccess()`, so you wouldn't spot it, unless you've started from `poll`.
ping @mkow confirm (or disconfirm) :)
</blockquote></details>

I actually tried to remove them back then because they shouldn't be needed, but turned out that it's too much work, so I only refactored them a bit ;) Glad that @boryspoplawski finished this.
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 479 at r1](https://reviewable.io/reviews/gramineproject/gramine/488#-MzpTJn38X-o82alZePY:-MzpTJn38X-o82alZePZ:bcm91ge) ([raw file](https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/Pal/src/host/Linux-SGX/db_pipes.c#L479)):*
> ```C
> 
>     /* This pipe might use a secure session, make sure all initial work is done. */
>     while (!__atomic_load_n(&handle->pipe.handshake_done, __ATOMIC_ACQUIRE)) {
> ```

Why have you removed this? Now we can have this pipe still uninitialized when returning from this function.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/488)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 479 at r1](https://reviewable.io/reviews/gramineproject/gramine/488#-MzpTJn38X-o82alZePY:-MzpUMiLDOij0Oi8e9zN:b-xzoodd) ([raw file](https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/Pal/src/host/Linux-SGX/db_pipes.c#L479)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why have you removed this? Now we can have this pipe still uninitialized when returning from this function.
</blockquote></details>

This was only needed because we issued a poll directly on `fd`. We don't need the handshake/initialization to be finished after this function returns.

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/488)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 479 at r1](https://reviewable.io/reviews/gramineproject/gramine/488#-MzpTJn38X-o82alZePY:-MzsJ44nBoGTKLDEH3Bb:bjek1ju) ([raw file](https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/Pal/src/host/Linux-SGX/db_pipes.c#L479)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This was only needed because we issued a poll directly on `fd`. We don't need the handshake/initialization to be finished after this function returns.
</blockquote></details>

+1 to Borys's explanation.

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/488)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/488)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[-- commits, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/488#-MzopAtf1RqP5y49Gsr5):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

copy-paste failure. To fix at rebase
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/488)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest this please (CI downtime failed the builds)

**Pull request merged**
