### PR TITLE
[Docs] Change email groups addresses to use our aliases

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes

As in the title.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/241#-Mp7aWtl0Y435f-Hq3wv:-Mp7aWtm9g94R63wYKtw:b-paehjr) (no related file):*
We have the same in the GSC repo:
- https://github.com/gramineproject/gsc/search?q=googlegroups

@mkow Could you submit a similar PR there?

I checked `examples` repo, it doesn't have any mentions of googlegroups.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/241#-Mp7aWtl0Y435f-Hq3wv:-Mp7jOFo709HWXTwN2eZ:bjwf4hg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have the same in the GSC repo:
- https://github.com/gramineproject/gsc/search?q=googlegroups

@mkow Could you submit a similar PR there?

I checked `examples` repo, it doesn't have any mentions of googlegroups.
</blockquote></details>

Done in https://github.com/gramineproject/gsc/pull/32.

---

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/241#-MpA6K_43CS7az_2ZWCU:-MpA6K_5DHdtHjCxWh62:b-1p453x) ([raw file](https://github.com/gramineproject/gramine/blob/6e5ca376acfa2a6fa9b1cdd665c865536dc85771/.github/ISSUE_TEMPLATE.md#L7)):*
> ```Markdown
> 
> IMPORTANT: please do not post general questions here;
> if you have questions, please use our mailing list: devel@gramineproject.io
> ```

I'm pretty sure this should be `users@`

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/241#-MpA6K_43CS7az_2ZWCU:-MpCWRfyErFuSRTdCEl4:bki4oi3) ([raw file](https://github.com/gramineproject/gramine/blob/6e5ca376acfa2a6fa9b1cdd665c865536dc85771/.github/ISSUE_TEMPLATE.md#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm pretty sure this should be `users@`
</blockquote></details>

Hard to say, no idea.
/summon @woju

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/241#-MpA6K_43CS7az_2ZWCU:-MpCXWpc0UkF28DB5bHT:b-800itb) ([raw file](https://github.com/gramineproject/gramine/blob/6e5ca376acfa2a6fa9b1cdd665c865536dc85771/.github/ISSUE_TEMPLATE.md#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hard to say, no idea.
/summon @woju
</blockquote></details>

We literally say to email `users@` in case of general questions in other places.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/241#-MpA6K_43CS7az_2ZWCU:-MpCZDN8C4rVlI1G_6OX:biwea2x) ([raw file](https://github.com/gramineproject/gramine/blob/6e5ca376acfa2a6fa9b1cdd665c865536dc85771/.github/ISSUE_TEMPLATE.md#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We literally say to email `users@` in case of general questions in other places.
</blockquote></details>

@mkow, @woju just said it should be `users`. Please also fix in your GSC PR.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/241#-MpA6K_43CS7az_2ZWCU:-MpCl06J4G8GMSbwogQi:b-9wsght) ([raw file](https://github.com/gramineproject/gramine/blob/6e5ca376acfa2a6fa9b1cdd665c865536dc85771/.github/ISSUE_TEMPLATE.md#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow, @woju just said it should be `users`. Please also fix in your GSC PR.
</blockquote></details>

Yup, I was on the call :P I wrote my comment above before we discussed this.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Direct-Sanitizers please (`test_libos.TC_30_Syscall.test_051_mmap_sgx`, unrelated)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/241)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
