### PR TITLE
[PAL/Linux-SGX] Add "parse frequency from /proc/cpuinfo" fallback

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Some hypervisors (like Microsoft Hyper-V) currently do not expose CPUID leaves 0x15 and 0x16 (Core Crystal Clock/Process Frequency), and also do not expose  hypervisor-specific synthetic CPUID leaf 0x40000010 (Timing Information). In this case, if "Invariant TSC" feature is found in CPUID leaves, we know that TSC is stable and we need to find its frequency: we try to parse the "Processor Brand String" CPUID leaves and extract the CPU frequency from that string (assuming that TSC frequency is equal to this base CPU frequency).

For context see:
- https://github.com/gramineproject/gramine/issues/1009
- https://github.com/gramineproject/gramine/pull/1012 (prerequisite for this PR)
- https://github.com/gramineproject/gramine/pull/1154 (failed attempt)

## How to test this PR? 

Manually, e.g. on MS Azure cloud.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1180)

### CODE REVIEW

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1180)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 139 at r1](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOTjLAU9slafL0sL5Ps:-NOTjLAU9slafL0sL5Pt:b2xg8uq) ([raw file](https://github.com/gramineproject/gramine/blob/05f524aedf1910a2325fbe911cae11e416d68d9a/pal/src/host/linux-sgx/pal_misc.c#L139)):*
> ```C
>     model_name[sizeof(model_name) - 1] = '\0';
> 
>     const char* s = strchr(model_name, '@');
> ```

Is this method (using `@` pattern) always correct?

Any special reason that we don't follow the algo suggested in the SDM (specifically "Algorithm for Extracting Processor Frequency" in Section 3.2 CPUID, Volume. 2A, https://www.felixcloutier.com/x86/cpuid#extracting-the-processor-frequency-from-brand-strings)?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1180)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 139 at r1](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOTjLAU9slafL0sL5Ps:-NOUFeiA1F9wPi9Op0GL:b31jh0x) ([raw file](https://github.com/gramineproject/gramine/blob/05f524aedf1910a2325fbe911cae11e416d68d9a/pal/src/host/linux-sgx/pal_misc.c#L139)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Is this method (using `@` pattern) always correct?

Any special reason that we don't follow the algo suggested in the SDM (specifically "Algorithm for Extracting Processor Frequency" in Section 3.2 CPUID, Volume. 2A, https://www.felixcloutier.com/x86/cpuid#extracting-the-processor-frequency-from-brand-strings)?
</blockquote></details>

Done. Thanks, Kailun, I wasn't aware of that text. Now I closely follow that algorithm.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 145 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOUFjwx0xc2BbMbOAzq:-NOUFjwx0xc2BbMbOAzr:b-uiry3i) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L145)):*
> ```C
>         hz_str--;
>     if (hz_str - model_name < 3 || *hz_str-- != 'z' || *hz_str-- != 'H')
>         return 0;
> ```

FYI: I first tried to use `strstr()` but it searches from left to right and ignores the `\0` in the "needle" arg. So strings like `1.0THz 3.0GHz` were incorrectly parsed (the first number was taken).

So I ended up just doing iterations over chars.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1180)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 123 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOlgTHS6mBLj-QS5AJd:-NOlgTHT9Z7uK0mDVh0A:bq3di1f) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L123)):*
> ```C
> }
> 
> /* return TSC frequency or 0 if cannot parse CPU model name */
> ```

`brand string` (just a bit more precise), same for the below.



_Code quote:_
```C
model name
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 127 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOm6cwx-gFgTc21QfTR:-NOm6cwx-gFgTc21QfTS:bunqbcs) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L127)):*
> ```C
>     uint32_t words[CPUID_WORD_NUM];
> 
>     char model_name[48 + 1] = {0};
> ```

The returned brand string should always be NULL-terminated. Why we need an extra byte for `\0`?
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 145 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOUFjwx0xc2BbMbOAzq:-NOm6NRLAa0eUyzpzgyO:bejwarb) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L145)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I first tried to use `strstr()` but it searches from left to right and ignores the `\0` in the "needle" arg. So strings like `1.0THz 3.0GHz` were incorrectly parsed (the first number was taken).

So I ended up just doing iterations over chars.
</blockquote></details>

An alternative is to reverse the string first and then `strstr()`.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 149 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOlk1rN2r2POnRnXzBj:-NOlk1rN2r2POnRnXzBk:bky9q0c) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L149)):*
> ```C
>     uint64_t multiplier = 0;
>     if (*hz_str == 'T')
>         multiplier = 1000UL * 1000 * 1000 * 1000;
> ```

Suggest to make macros (e.g., `KHZ`, `MHZ`, `GHZ`, `THZ`) for theses and have `MHZ`, `GHZ`, `THZ` built on top of `KHZ` like `#define MHZ(x) (KHZ(x) * 1000)`.



_Code quote:_
```C
1000UL * 1000 * 1000 * 1000
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 159 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOm7VZQ9fbjyhRC1kcf:-NOm7VZQ9fbjyhRC1kcg:b-40120h) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L159)):*
> ```C
>     /* scan digits in reverse order until we hit space/tab or beginning of string */
>     const char* s = hz_str;
>     while (s > model_name && *s != ' ' && *s != '\t')
> ```

Not blocking but do we need to check `\t`?



_Code quote:_
```C
*s != '\t'
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 170 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOm-cRq4KJSdkzbrqMS:-NOm-cRq4KJSdkzbrqMT:b-wyhyq6) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L170)):*
> ```C
>         return 0;
>     }
>     if (base <= 0 || base >= 1000) {
> ```

Though w/ very low possibility, why can't `base == 0`?



_Code quote:_
```C
base <= 0
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 179 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOm1sfZCmJfAZOT9ia2:-NOm1sfZCmJfAZOT9ia3:b-qjpvni) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L179)):*
> ```C
>         s++;
>         fractional = strtol(s, &end, 10);
>         if (fractional <= 0 || end - s > 3) {
> ```

What about `fractional == 0`? It's normal to have sth like `2.0GHz` or maybe `2.00GHz` I guess? Seems the current version will return 0 frequency directly.



_Code quote:_
```C
fractional <= 0
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1180)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 123 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOlgTHS6mBLj-QS5AJd:-NOn5Nsx71d4e04yDH8m:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L123)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

`brand string` (just a bit more precise), same for the below.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 127 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOm6cwx-gFgTc21QfTR:-NOn5Q0D-KjuQku3PIuV:b8t36nn) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L127)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

The returned brand string should always be NULL-terminated. Why we need an extra byte for `\0`?
</blockquote></details>

1. To be on the safe side always (Linux also does the same, though I'm lazy to find the link again).
2. Malicious VM can intercept CPUID and provide some garbage non-NULL-terminated value. Gramine should protect against such a case, otherwise we may have buffer overrun vulnerabilities.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 145 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOUFjwx0xc2BbMbOAzq:-NOn5g_q2qBjlzesmIyL:b94puew) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L145)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

An alternative is to reverse the string first and then `strstr()`.
</blockquote></details>

Meh, I feel like reversing the string makes the parsing logic only more unreadable.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 149 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOlk1rN2r2POnRnXzBj:-NOn7WBs9XP5mNEJRDNh:b-v9hg4u) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L149)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Suggest to make macros (e.g., `KHZ`, `MHZ`, `GHZ`, `THZ`) for theses and have `MHZ`, `GHZ`, `THZ` built on top of `KHZ` like `#define MHZ(x) (KHZ(x) * 1000)`.
</blockquote></details>

Done, with slightly more readable names
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 159 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOm7VZQ9fbjyhRC1kcf:-NOn7gEV3Po-JfVAYr6L:bkmujn1) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L159)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Not blocking but do we need to check `\t`?
</blockquote></details>

Well, the Intel SDM says `scan digits until blank`, and I'm not sure what `blank` means here. So I'm defaulting to the classic "space or tab".
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 170 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOm-cRq4KJSdkzbrqMS:-NOn7rf54x-DeLqV3Ps9:b-et91oq) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L170)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Though w/ very low possibility, why can't `base == 0`?
</blockquote></details>

Done. You're right, probably smth like `0.8GHz` is possible.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 179 at r2](https://reviewable.io/reviews/gramineproject/gramine/1180#-NOm1sfZCmJfAZOT9ia2:-NOn8A4r6HzWkF5E_FjR:b-376vyb) ([raw file](https://github.com/gramineproject/gramine/blob/e6dfdee260f51bdd95365a40983fed7d5a6b7f1a/pal/src/host/linux-sgx/pal_misc.c#L179)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about `fractional == 0`? It's normal to have sth like `2.0GHz` or maybe `2.00GHz` I guess? Seems the current version will return 0 frequency directly.
</blockquote></details>

Done. Good catch.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1180)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Pull request closed without merging**
