### PR TITLE
[musl] Update musl to v1.2.5

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 

As title. No CVE fixes, but still some bug fixes. Pls see https://www.openwall.com/lists/musl/2024/03/01/2 for details.

## How to test this PR? 
CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1903)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1903)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1903#-O-4yuL20KeKp70zTGlr:-O-4yuL20KeKp70zTGls:b-oivmzd) (no related file):*
@anjalirai-intel @jinengandhi-intel You test the Alpine + Musl distribution (or maybe even Ubuntu + Musl? don't remember). I vaguely recall we had some versioning issues with Musl... Could you remind what it was and whether bumping Musl version to the latest (1.2.5) will lead to some side effects?

___
___
*[`subprojects/musl-1.2.5.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1903#-O-4ykwZDjRjasz9ppup:-O-4ykwZDjRjasz9ppuq:btakbig) ([raw file](https://github.com/gramineproject/gramine/blob/2e78fde4d382fd4fa7f8db5eabf7007ed73a1fab/subprojects/musl-1.2.5.wrap#L4)):*
> ```
> directory = musl-1.2.5
> source_url = https://musl.libc.org/releases/musl-1.2.5.tar.gz
> source_fallback_url = https://packages.gramineproject.io/distfiles/musl-1.2.5.tar.gz
> ```

@woju Can you add this file to our repo?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1903)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1903#-O-4yuL20KeKp70zTGlr:-O-5_u-v2xdwsDhgdalv:b31o5xp) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@anjalirai-intel @jinengandhi-intel You test the Alpine + Musl distribution (or maybe even Ubuntu + Musl? don't remember). I vaguely recall we had some versioning issues with Musl... Could you remind what it was and whether bumping Musl version to the latest (1.2.5) will lead to some side effects?
</blockquote></details>

Done (see comment from Anjali in another thread)

___
___
*[`subprojects/musl-1.2.5.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1903#-O-4ykwZDjRjasz9ppup:-O-5a--O3PXNRomHBHMC:bhzp4o7) ([raw file](https://github.com/gramineproject/gramine/blob/2e78fde4d382fd4fa7f8db5eabf7007ed73a1fab/subprojects/musl-1.2.5.wrap#L4)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

@dimakuv We tested two distro combination, Ubuntu 22.04 + Musl and Alpine, both of the runs were successful. No issues
</blockquote></details>

Wrong thread, but I marked your reply as resolved in another comment. Thanks for checking!

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1903)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`subprojects/musl-1.2.5.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1903#-O-4ykwZDjRjasz9ppup:-O-5zKolBJ_8Sp3xqlrq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2e78fde4d382fd4fa7f8db5eabf7007ed73a1fab/subprojects/musl-1.2.5.wrap#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wrong thread, but I marked your reply as resolved in another comment. Thanks for checking!
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1903)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`subprojects/musl-1.2.5.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1903#-O-4ykwZDjRjasz9ppup:-O-AUBXo2fT7WxY1noJF:b-63jxq4) ([raw file](https://github.com/gramineproject/gramine/blob/2e78fde4d382fd4fa7f8db5eabf7007ed73a1fab/subprojects/musl-1.2.5.wrap#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, I verified the hashes.

**Review by mkow — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1903)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1903)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1903)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
