### PR TITLE
[Pal] Let DkStreamWaitForClient set handle options

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Described in commit messages. I think it's a good change by itself, but I will also need it in another PR.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/285#-Mr1Wz1p5LpR0LQ98Mi2):*
`This option was` (remove `s`)

or `These options were`
___
*[Pal/src/host/Linux/db_pipes.c, line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/285#-Mr1XhV65GztAwqnr3Mf:-Mr1XhV65GztAwqnr3Mg:b7iv88u) ([raw file](https://github.com/gramineproject/gramine/blob/8e66218eea72eb27aa287b18669839d60980222b/Pal/src/host/Linux/db_pipes.c#L95)):*
> ```C
>  *
>  * \param[in]  handle  PAL handle of type `pipesrv` with abstract UNIX socket opened for listening.
>  * \param[out] client  PAL handle of type `pipecli` connected to the other end of the pipe (`pipe`).
> ```

Please add another param here.
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 143 at r1](https://reviewable.io/reviews/gramineproject/gramine/285#-Mr1Yotn9QPepD9otSV2:-Mr1Yoto5rSJHEwWqFS_:b-ubahvs) ([raw file](https://github.com/gramineproject/gramine/blob/8e66218eea72eb27aa287b18669839d60980222b/Pal/src/host/Linux-SGX/db_pipes.c#L143)):*
> ```C
>     clnt->pipe.fd          = ret;
>     clnt->pipe.name        = handle->pipe.name;
>     clnt->pipe.nonblocking = !!(flags & SOCK_CLOEXEC);
> ```

Oops. `SOCK_CLOEXEC` -> `SOCK_NONBLOCK`
___
*[Pal/src/host/Linux-SGX/db_sockets.c, line 322 at r1](https://reviewable.io/reviews/gramineproject/gramine/285#-Mr1ZetgDQqSXfoUQju2:-Mr1ZethDiJTOPK6quI9:b5l2bck) ([raw file](https://github.com/gramineproject/gramine/blob/8e66218eea72eb27aa287b18669839d60980222b/Pal/src/host/Linux-SGX/db_sockets.c#L322)):*
> ```C
> 
>     struct sockopt sock_options = { 0 };
>     sock_options.reuseaddr = 1; /* sockets are always set as reusable in Gramine */
> ```

Please use the same format as above (init of the struct with one field set explicitly)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/285#-Mr1Wz1p5LpR0LQ98Mi2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`This option was` (remove `s`)

or `These options were`
</blockquote></details>

Done. (in squash commit)
___
*[Pal/src/host/Linux/db_pipes.c, line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/285#-Mr1XhV65GztAwqnr3Mf:-Mr2c_y11s_whALQd6cH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e66218eea72eb27aa287b18669839d60980222b/Pal/src/host/Linux/db_pipes.c#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add another param here.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 143 at r1](https://reviewable.io/reviews/gramineproject/gramine/285#-Mr1Yotn9QPepD9otSV2:-Mr2cmN67h9gxO0SX4s2:b5326gt) ([raw file](https://github.com/gramineproject/gramine/blob/8e66218eea72eb27aa287b18669839d60980222b/Pal/src/host/Linux-SGX/db_pipes.c#L143)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops. `SOCK_CLOEXEC` -> `SOCK_NONBLOCK`
</blockquote></details>

oops indeed
___
*[Pal/src/host/Linux-SGX/db_sockets.c, line 322 at r1](https://reviewable.io/reviews/gramineproject/gramine/285#-Mr1ZetgDQqSXfoUQju2:-Mr2bc7G0VFd2DR7k9c9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e66218eea72eb27aa287b18669839d60980222b/Pal/src/host/Linux-SGX/db_sockets.c#L322)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use the same format as above (init of the struct with one field set explicitly)
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 18 of 21 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, 3 unresolved discussions, "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_socket.c, line 886 at r2](https://reviewable.io/reviews/gramineproject/gramine/285#-MrU-CQc2wWmb2x4FhFX:-MrU-CQc2wWmb2x4FhFY:b-l8uah3) ([raw file](https://github.com/gramineproject/gramine/blob/49b82a1e5405ce20691142a8c59d9dba3799479d/LibOS/shim/src/sys/shim_socket.c#L886)):*
> ```C
> 
> static int __do_accept(struct shim_handle* hdl, int flags, struct sockaddr* addr, int* addrlen) {
>     assert(!(flags & ~(O_CLOEXEC | O_NONBLOCK)));
> ```

We have `WITHIN_MASK()` for exactly this ;)
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/285#-MrUNWwT3lCpv3B5Ulim:-MrUNWwT3lCpv3B5Ulin:b7dihl1) ([raw file](https://github.com/gramineproject/gramine/blob/49b82a1e5405ce20691142a8c59d9dba3799479d/Pal/src/host/Linux-SGX/sgx_enclave.c#L405)):*
> ```C
>     int addrlen = ms->ms_addrlen;
>     int options = ms->options | SOCK_CLOEXEC;
>     assert(!(options & ~(SOCK_CLOEXEC | SOCK_NONBLOCK)));
> ```

ditto (`WITHIN_MASK()`), please grep the whole PR for these
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 423 at r2](https://reviewable.io/reviews/gramineproject/gramine/285#-MrUPhG30D7AfHvixfon:-MrUPhG30D7AfHvixfoo:b-mn04dv) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/Pal/src/host/Linux-SGX/sgx_enclave.c#L423)):*
> ```C
>         goto err;
> 
>     fd = ret;
> ```

I actually preferred the old version with explicit `fd = ret` and separate success path. Now we just have `return ret;`, while "ret" in most of our codebase means "0 or negative error".

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 886 at r2](https://reviewable.io/reviews/gramineproject/gramine/285#-MrU-CQc2wWmb2x4FhFX:-MrUZNjk9dwMs-mKIcGy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/49b82a1e5405ce20691142a8c59d9dba3799479d/LibOS/shim/src/sys/shim_socket.c#L886)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We have `WITHIN_MASK()` for exactly this ;)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/285#-MrUNWwT3lCpv3B5Ulim:-MrU_RIFAt7rs--IogHR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/49b82a1e5405ce20691142a8c59d9dba3799479d/Pal/src/host/Linux-SGX/sgx_enclave.c#L405)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`WITHIN_MASK()`), please grep the whole PR for these
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 423 at r2](https://reviewable.io/reviews/gramineproject/gramine/285#-MrUPhG30D7AfHvixfon:-MrUb2OEABGxeMnUuofE:b-b3x53j) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/Pal/src/host/Linux-SGX/sgx_enclave.c#L423)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I actually preferred the old version with explicit `fd = ret` and separate success path. Now we just have `return ret;`, while "ret" in most of our codebase means "0 or negative error".
</blockquote></details>

1) `ret` usually means return value, whatever that is
2) If you are suggesting to do:
```c
static long sgx_ocall_accept(void* pms) {
    ms_ocall_accept_t* ms = (ms_ocall_accept_t*)pms;
    long ret;
    ODEBUG(OCALL_ACCEPT, ms);

    if (ms->ms_addrlen > INT_MAX) {
        ret = -EINVAL;
        goto err;
    }
    int addrlen = ms->ms_addrlen;
    int options = ms->options | SOCK_CLOEXEC;
    assert(WITHIN_MASK(options, SOCK_CLOEXEC | SOCK_NONBLOCK));

    ret = DO_SYSCALL_INTERRUPTIBLE(accept4, ms->ms_sockfd, ms->ms_addr, &addrlen, options);
    if (ret < 0)
        goto err;

    int fd = ret;
    ms->ms_addrlen = addrlen;
    return fd

err:
    return ret;
}

```
then I disagree. Otherwise I don't really know what you are proposing, so please post the patch you would like to see added here

**Review by mkow — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 423 at r2](https://reviewable.io/reviews/gramineproject/gramine/285#-MrUPhG30D7AfHvixfon:-MrUeBX5BnXaavctPrTm:bm14s2e) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/Pal/src/host/Linux-SGX/sgx_enclave.c#L423)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1) `ret` usually means return value, whatever that is
2) If you are suggesting to do:
```c
static long sgx_ocall_accept(void* pms) {
    ms_ocall_accept_t* ms = (ms_ocall_accept_t*)pms;
    long ret;
    ODEBUG(OCALL_ACCEPT, ms);

    if (ms->ms_addrlen > INT_MAX) {
        ret = -EINVAL;
        goto err;
    }
    int addrlen = ms->ms_addrlen;
    int options = ms->options | SOCK_CLOEXEC;
    assert(WITHIN_MASK(options, SOCK_CLOEXEC | SOCK_NONBLOCK));

    ret = DO_SYSCALL_INTERRUPTIBLE(accept4, ms->ms_sockfd, ms->ms_addr, &addrlen, options);
    if (ret < 0)
        goto err;

    int fd = ret;
    ms->ms_addrlen = addrlen;
    return fd

err:
    return ret;
}

```
then I disagree. Otherwise I don't really know what you are proposing, so please post the patch you would like to see added here
</blockquote></details>

Yeah, I prefer the more redundant version, which is explicit about returning "fd or error code".
@dimakuv, @pwmarcz: Any preferences?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 423 at r2](https://reviewable.io/reviews/gramineproject/gramine/285#-MrUPhG30D7AfHvixfon:-MrW-wgv1qtImrve7IJD:bvblovo) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/Pal/src/host/Linux-SGX/sgx_enclave.c#L423)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I prefer the more redundant version, which is explicit about returning "fd or error code".
@dimakuv, @pwmarcz: Any preferences?
</blockquote></details>

Hm, I didn't have problems with Borys's version but I see the point in Michal's suggestion. Also, all other functions here also have the same construct of `int fd = ret; ... return fd;`. So I would prefer Michal's version, just for uniformity.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: 20 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 423 at r2](https://reviewable.io/reviews/gramineproject/gramine/285#-MrUPhG30D7AfHvixfon:-MrWtqI5DPBMG_reLhCe:be06yly) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/Pal/src/host/Linux-SGX/sgx_enclave.c#L423)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, I didn't have problems with Borys's version but I see the point in Michal's suggestion. Also, all other functions here also have the same construct of `int fd = ret; ... return fd;`. So I would prefer Michal's version, just for uniformity.
</blockquote></details>

Disagree, but done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: 13 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/285#-MrXPNkXBZu90W5ONPsk:-MrXPNkY0hzIOV9aTEkZ:b-jhenfq) (no related file):*
I did a squash + rebase, because I need this in another PR (and it seems it's generally accepted)

---

**Review by mkow — DISMISSED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

**Review by dimakuv — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/285)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
