### PR TITLE
[Meson] Update musl to v1.2.4

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This update is important because programs built against newer musl may crash under older musl (e.g. v1.2.2 which Gramine had previously). In particular, Gramine segfaulted on Alpine 3.18.0 on `/bin/sh` (resolves to Busybox) apps, because Busybox is built against musl v1.2.4 and therefore requires the new relocation type `RELR`.

## How to test this PR? 

CI should be enough.

Try to run some apps on Alpine 3.18.0.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: 0 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1393#-NXz1CHLBgmxp6RWTPmy:-NXz1CHLBgmxp6RWTPmz:byge3ru) (no related file):*
As I mention in the commit message, this update is required to run Gramine on Alpine 3.18.0 which uses Musl v1.2.4.

Some additional details:

https://maskray.me/blog/2021-10-31-relative-relocations-and-relr -- Musl got a patch that introduces a new RELR relocation type. This happened in between versions v1.2.2 and v1.2.4:
- https://elixir.bootlin.com/musl/v1.2.2/source/ldso/dynlink.c#L1356 (no RELR handling)
- https://elixir.bootlin.com/musl/v1.2.4/source/ldso/dynlink.c#L1421 (with RELR handling)

So `/bin/sh` -- which is actually `bin/busybox` -- is built against Musl v1.2.4 and thus contains these RELR relocations. Our Gramine's Musl v1.2.2 ignored RELR relocations, and so parts of the Busybox binary were **not** relocated, leading to a segfault later on.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: 0 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1393#-NXz1CHLBgmxp6RWTPmy:-NXz1dhR1mKlzM9b0T5p:b7dagyj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As I mention in the commit message, this update is required to run Gramine on Alpine 3.18.0 which uses Musl v1.2.4.

Some additional details:

https://maskray.me/blog/2021-10-31-relative-relocations-and-relr -- Musl got a patch that introduces a new RELR relocation type. This happened in between versions v1.2.2 and v1.2.4:
- https://elixir.bootlin.com/musl/v1.2.2/source/ldso/dynlink.c#L1356 (no RELR handling)
- https://elixir.bootlin.com/musl/v1.2.4/source/ldso/dynlink.c#L1421 (with RELR handling)

So `/bin/sh` -- which is actually `bin/busybox` -- is built against Musl v1.2.4 and thus contains these RELR relocations. Our Gramine's Musl v1.2.2 ignored RELR relocations, and so parts of the Busybox binary were **not** relocated, leading to a segfault later on.
</blockquote></details>

BTW, this is the patch that introduced it first in Musl: https://git.musl-libc.org/cgit/musl/commit/?id=d32dadd60efb9d3b255351a3b532f8e4c3dd0db1

___

**Review by mkow — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`subprojects/musl-1.2.4.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1393#-NY0cWs-EhFwxCgpNiXr:-NY0cWs-EhFwxCgpNiXs:b-bdoe6d) ([raw file](https://github.com/gramineproject/gramine/blob/81cdae927bdb2f28f56a40e4424e3bf302e2bb68/subprojects/musl-1.2.4.wrap#L4)):*
> ```
> directory = musl-1.2.4
> source_url = https://musl.libc.org/releases/musl-1.2.4.tar.gz
> source_fallback_url = https://packages.gramineproject.io/distfiles/musl-1.2.4.tar.gz
> ```

This file is not uploaded yet, right?



_Code quote:_
```
https://packages.gramineproject.io/distfiles/musl-1.2.4.tar.gz
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required)

___
*[`subprojects/musl-1.2.4.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1393#-NY0cWs-EhFwxCgpNiXr:-NY1zwXO2yITFjhjjBUN:b-4lu76f) ([raw file](https://github.com/gramineproject/gramine/blob/81cdae927bdb2f28f56a40e4424e3bf302e2bb68/subprojects/musl-1.2.4.wrap#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This file is not uploaded yet, right?
</blockquote></details>

@woju Could you add this file to our repository of packages?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`subprojects/musl-1.2.4.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1393#-NY0cWs-EhFwxCgpNiXr:-NY2Mc9M3WaKAC3Wq802:b82x7qh) ([raw file](https://github.com/gramineproject/gramine/blob/81cdae927bdb2f28f56a40e4424e3bf302e2bb68/subprojects/musl-1.2.4.wrap#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Could you add this file to our repository of packages?
</blockquote></details>

Done. Woju added it now (thanks to him!). See the list at https://packages.gramineproject.io/distfiles/

**Review by kailun-qin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

**Comment by dimakuv** [comment]
Jenkins, test this please (we had some problems with Docs pipeline, seems to be fixed now)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1393#-NXyy20u72BCooXIXpA1):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this is not 72-lines-per-char (I did this PR from another machine, and didn't bother to install proper vim there). I'll fix it during final rebase.
</blockquote></details>

Didn't you forget about this?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1393#-NXyy20u72BCooXIXpA1):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Didn't you forget about this?
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1393)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
