### PR TITLE
[python] Remove duplicates when expanding trusted files

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Not yet sure if we want it, but in case we do here it is.

Closes #977 

## How to test this PR? 
Add duplicate entries in trusted files.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1003#-NF7r1gYEaRnDh0IpKjt:-NF7r1gYEaRnDh0IpKju:b-tm64g) (no related file):*
Let me check how slow this implementation is (due to the dict search inside `append_tf()`). Looks good overall.

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1003#-NF7r1gYEaRnDh0IpKjt:-NF80xkW8dyhkU5aTEEx:bs16ao1) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me check how slow this implementation is (due to the dict search inside `append_tf()`). Looks good overall.
</blockquote></details>

Ok, the way I tested:
```
CI-Examples/python$ git diff
diff --git a/CI-Examples/python/python.manifest.template b/CI-Examples/python/python.manifest.template
@@ -45,4 +45,5 @@ sgx.trusted_files = [
   "file:helper-files/",
+  "file:/usr/",
 ]
```

- Results on master:
```
CI-Examples/python$ time make SGX=1
real    8m2.977s
user    1m43.540s
sys     0m15.164s

CI-Examples/python$ ls -lah python.manifest.sgx
-rw-rw-r-- 1 dimakuv dimakuv 88M Oct 24 00:46 python.manifest.sgx
```

- Results on this PR:
```
CI-Examples/python$ time make SGX=1
real    7m44.352s
user    1m40.896s
sys     0m16.227s

CI-Examples/python$ ls -lah python.manifest.sgx
-rw-rw-r-- 1 dimakuv dimakuv 84M Oct 24 00:56 python.manifest.sgx
```

So with the PR it is even faster. I'm not sure why -- because we use dict ops instead of list ops? Or simply because it's faster for TOML parser to dump 84MB instead of 88MB to a file?

Anyway, the PR doesn't introduce performance overhead.

___
___
*[`python/graminelibos/manifest.py` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1003#-NF81TOP7ZpOEO5DmcZ8:-NF81TOP7ZpOEO5DmcZ9:b-fleb3n) ([raw file](https://github.com/gramineproject/gramine/blob/dcc172d142a9c501304a77166a53ba1822a2de1e/python/graminelibos/manifest.py#L71)):*
> ```Python
>     else:
>         assert path.is_file()
>         append_tf(trusted_files, path, hash_file_contents(path))
> ```

Shouldn't we calculate the hash only if the file is unique (new)? Otherwise we're doing useless work.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`python/graminelibos/manifest.py` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1003#-NF81TOP7ZpOEO5DmcZ8:-NF9i1xPDcU7ke6b2e26:b-hiylx) ([raw file](https://github.com/gramineproject/gramine/blob/dcc172d142a9c501304a77166a53ba1822a2de1e/python/graminelibos/manifest.py#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we calculate the hash only if the file is unique (new)? Otherwise we're doing useless work.
</blockquote></details>

Only thing I can do is delete `append_tf` and inline the check in each callsite

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`python/graminelibos/manifest.py` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1003#-NF81TOP7ZpOEO5DmcZ8:-NF9lMEvDNuC8WAAWXk9:b-v6os06) ([raw file](https://github.com/gramineproject/gramine/blob/dcc172d142a9c501304a77166a53ba1822a2de1e/python/graminelibos/manifest.py#L71)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Only thing I can do is delete `append_tf` and inline the check in each callsite
</blockquote></details>

Yes, I think this will be reasonable.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`python/graminelibos/manifest.py` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1003#-NF81TOP7ZpOEO5DmcZ8:-NFB0f2Q27sY9CFNewQJ:b-tosagt) ([raw file](https://github.com/gramineproject/gramine/blob/dcc172d142a9c501304a77166a53ba1822a2de1e/python/graminelibos/manifest.py#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Or why not have a special case of `hash_=None`, and in this case perform `hash_file_contents(uri)`?
</blockquote></details>

I guess now that we provide `path` not `uri` it's possible

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1003)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
