### PR TITLE
[PAL] Rename `enclave_tls` to `pal_enclave_tcb` and unify names to `pal_xxx_tcb`

### PR DESCRIPTION
**Pull request by kailun-qin**
TLS stands for "Thread Local Storage" and is a memory area dedicated to storing app-specific thread-local variables. TCB stands for "Thread Control Block" and contains thread-specific internal state such as thread ID, stack pointer, and saved registers.

The Linux PAL correctly defines the struct `pal_tcb`. The Linux-SGX PAL however defines the struct `enclave_tls`. The `enclave_tls name` is misleading and breaks uniformity of code.

This patch renames:
- `struct enclave_tls` to `struct pal_enclave_tcb`
- `get_tcb_trts()` to `pal_get_enclave_tcb()`
- `SET/GET_ENCLAVE_TLS` to `SET/GET_ENCLAVE_TCB`
- `pal_tls.h` to `pal_tcb.h`

It also aligns `pal_tcb_host` to `pal_host_tcb`, `pal_tcb_linux` to `pal_linux_tcb` and related function names for unification.

Resolves https://github.com/gramineproject/graphene/issues/638.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/776#-N7V7J567_3snrGl3y92):*
```
The `enclave_tls name`
```
->
```
The `enclave_tls` name
```
___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/776#-N7V8twy1WsBeaIrf2TE:-N7V8twy1WsBeaIrf2TF:bgxkjyk) ([raw file](https://github.com/gramineproject/gramine/blob/9239d5ab17672f1c3d7ddecd240fcf250581c2a1/pal/src/host/linux-sgx/pal_tcb.h#L23)):*
> ```objc
>  * initialization. Some of them are thread specific (like tcs_offset) and some
>  * of them are identical for all threads (like enclave_size).
>  */
> ```

Could you re-wrap this comment to 100-char-limit? Since we're modifying it anyway...
___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/776#-N7V8fHFCWjwWtq2YhIe:-N7V8fHFCWjwWtq2YhIf:b4ot8tj) ([raw file](https://github.com/gramineproject/gramine/blob/9239d5ab17672f1c3d7ddecd240fcf250581c2a1/pal/src/host/linux-sgx/pal_tcb.h#L59)):*
> ```objc
> #ifdef IN_ENCLAVE
> 
> static inline struct pal_tcb_sgx* get_tcb_trts(void) {
> ```

Please also rename this function to `pal_get_tcb_sgx()`. We don't use `trts` keyword anymore.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: 13 of 15 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/776#-N7V7J567_3snrGl3y92):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
The `enclave_tls name`
```
->
```
The `enclave_tls` name
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/776#-N7V8twy1WsBeaIrf2TE:-N7VEHoeDIctjnWnOplm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9239d5ab17672f1c3d7ddecd240fcf250581c2a1/pal/src/host/linux-sgx/pal_tcb.h#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you re-wrap this comment to 100-char-limit? Since we're modifying it anyway...
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/776#-N7V8fHFCWjwWtq2YhIe:-N7VEIV59dP9EHu4_hBS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9239d5ab17672f1c3d7ddecd240fcf250581c2a1/pal/src/host/linux-sgx/pal_tcb.h#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also rename this function to `pal_get_tcb_sgx()`. We don't use `trts` keyword anymore.
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: 13 of 15 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/776#-N7VND9c4-R2XGAYAT-I:-N7VND9c4-R2XGAYAT-J:b-2cmphk) (no related file):*
> struct enclave_tls to struct pal_tcb_sgx

Don't we use `enclave` instead of `sgx` in names? (`sgx` only where something is SGX specific, like `sgx_report`)

___

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/776#-N7VND9c4-R2XGAYAT-I:-N7VcmOf23KWGoNIc2Q5:b9y7u37) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> struct enclave_tls to struct pal_tcb_sgx

Don't we use `enclave` instead of `sgx` in names? (`sgx` only where something is SGX specific, like `sgx_report`)
</blockquote></details>

Heh, too may renames recently :)

I guess we need a vote:
1. `pal_tcb_sgx` (current PR)
2. `pal_tcb_enclave` (will be uniform with already-existing `pal_tcb_host`)
3. `pal_enclave_tcb` (will NOT be uniform with already-existing `pal_tcb_host`)
4. other candidates?

Looking at these three, I am preferring `pal_enclave_tcb`, it reads easy for me. But then we also need to change `pal_tcb_host` -> `pal_host_tcb`.

@mkow @boryspoplawski @kailun-qin Let's vote.

___

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/776#-N7VND9c4-R2XGAYAT-I:-N7Ve2y36LJ_yWUjMNIr:bz96pib) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Heh, too may renames recently :)

I guess we need a vote:
1. `pal_tcb_sgx` (current PR)
2. `pal_tcb_enclave` (will be uniform with already-existing `pal_tcb_host`)
3. `pal_enclave_tcb` (will NOT be uniform with already-existing `pal_tcb_host`)
4. other candidates?

Looking at these three, I am preferring `pal_enclave_tcb`, it reads easy for me. But then we also need to change `pal_tcb_host` -> `pal_host_tcb`.

@mkow @boryspoplawski @kailun-qin Let's vote.
</blockquote></details>

I also vote for 3

___

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/776#-N7VND9c4-R2XGAYAT-I:-N7VfeDg3LQn-PBVo51k:b-6l7xsk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I also vote for 3
</blockquote></details>

I vote for 3 as it's more readable.

___

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/776#-N7VND9c4-R2XGAYAT-I:-N7W4f9zBxf3KNHSiUFg:bq641k7) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I vote for 3 as it's more readable.
</blockquote></details>

I'm fine with both 2 and 3.

___
___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/776#-N7W5Xhk5odqyFNve0ql):*
Hmm, I'm starting to dislike this. Could we only include the proposed changes in the squash commit? Or just keep the Reviewable comment open until rebase.
The problem is that I can't easily diff the old and new commit message, and this gets quite annoying with longer messages.

CC: @boryspoplawski @dimakuv @oshogbo @meithecatte



_Code quote:_
```
!TODO: use this commit message
```

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @meithecatte, and @oshogbo)

___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/776#-N7W5Xhk5odqyFNve0ql):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I'm starting to dislike this. Could we only include the proposed changes in the squash commit? Or just keep the Reviewable comment open until rebase.
The problem is that I can't easily diff the old and new commit message, and this gets quite annoying with longer messages.

CC: @boryspoplawski @dimakuv @oshogbo @meithecatte
</blockquote></details>

Hm, how is diffing Reviewable comments easier?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @meithecatte, and @oshogbo)

___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/776#-N7W5Xhk5odqyFNve0ql):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, I don't mean pasting the whole new message in the comment, but stating what to change on rebase (e.g. "`asdf_xyz` -> `xyz_asdf`"). And then after rebase I'll see the final diff and could double check if the change was applied correctly.
</blockquote></details>

Ok, so you don't mind whether we use squash commits or Reviewable comments, you just want to change what we put in there. Fine with me.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @meithecatte, and @oshogbo)

___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/776#-N7W5Xhk5odqyFNve0ql):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, so you don't mind whether we use squash commits or Reviewable comments, you just want to change what we put in there. Fine with me.
</blockquote></details>

Yup, just want to be able to easily see the diff.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: 8 of 21 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @meithecatte, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/776#-N7VND9c4-R2XGAYAT-I:-N7YTxul6qSC-Id89jny:bv1ljb5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with both 2 and 3.
</blockquote></details>

Update to 3 based on the vote.

___
___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/776#-N7W5Xhk5odqyFNve0ql):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, just want to be able to easily see the diff.
</blockquote></details>

I kept the whole new message (the usual way) for this update as it changes too much (due to the new vote).

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @meithecatte, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/776#-N7VND9c4-R2XGAYAT-I:-N7ZuGyp89Oqubl3zqTx:b9j9n3q) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Update to 3 based on the vote.
</blockquote></details>

Looks good to me!

___
___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/776#-N7W5Xhk5odqyFNve0ql):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I kept the whole new message (the usual way) for this update as it changes too much (due to the new vote).
</blockquote></details>

Regarding commit messages: I also dislike these squash commits with TODOs. I always use blocking Reviewable comments, and then always open Reviewable and check these comments before I do the final rebase. Works better for me.

Btw, @mkow, you're blocking on this discussion.
___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 82 at r3](https://reviewable.io/reviews/gramineproject/gramine/776#-N7Zu6_s4ZF74Abm8CZj:-N7Zu6_t8c466g4NTOUm:bxzh68n) ([raw file](https://github.com/gramineproject/gramine/blob/b0ecd9fc7aac045dafba30af2f56ebbb86fb8a56/pal/src/host/linux-sgx/pal_tcb.h#L82)):*
> ```objc
>                 : "ir"(value), "i"(offsetof(struct pal_enclave_tcb, member))                       \
>                 : "memory");                                                                   \
>     } while (0)
> ```

Please re-align the end-of-line `\` symbols in these two macros.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: 20 of 21 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @meithecatte, and @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 82 at r3](https://reviewable.io/reviews/gramineproject/gramine/776#-N7Zu6_s4ZF74Abm8CZj:-N7_-rRN60kZuc7_2vSL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b0ecd9fc7aac045dafba30af2f56ebbb86fb8a56/pal/src/host/linux-sgx/pal_tcb.h#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-align the end-of-line `\` symbols in these two macros.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @meithecatte, and @oshogbo)

**Review by mkow — APPROVED** [review]
> Reviewed 8 of 15 files at r1, 12 of 13 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/776#-N7_QPxQDr6qcUYdU54B:-N7_QPxQDr6qcUYdU54C:b-yxdlf1) (no related file):*
In the future, please create PRs from branches in `<your-nick>/<change-descr>` format, even if it's from you private repo - this makes it a bit easier for us to pull it and rebase before merging without polluting our local branch namespaces.

___
___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/776#-N7W5Xhk5odqyFNve0ql):*
> Btw, @mkow, you're blocking on this discussion.

Yes, because I waited for comments on it.
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 826 at r4](https://reviewable.io/reviews/gramineproject/gramine/776#-N7_R1NjAHDfHnP5-4A3:-N7_R1NjAHDfHnP5-4A4:byn8sge) ([raw file](https://github.com/gramineproject/gramine/blob/d7622f4fe1a17f8fee39307cab8c53791d62d309/pal/src/host/linux-sgx/enclave_entry.S#L826)):*
> ```
>     # (5) thread returns back to SSA=0 and handles this new exception,
>     # (6) thread is done and returns from exception handler via _restore_sgx_context() and updates
>     #     SGX_TMP_RIP (overwrites pal_enclave_tcb::tmp_rip). Now the thread returned in the middle of
> ```

please rewrap

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: 20 of 21 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/776#-N7_QPxQDr6qcUYdU54B:-N7_TwrDAF6hNfVye-Om:b95nnv4) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In the future, please create PRs from branches in `<your-nick>/<change-descr>` format, even if it's from you private repo - this makes it a bit easier for us to pull it and rebase before merging without polluting our local branch namespaces.
</blockquote></details>

Got it, just forgot it sometimes :(. Will keep in mind...

___
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 826 at r4](https://reviewable.io/reviews/gramineproject/gramine/776#-N7_R1NjAHDfHnP5-4A3:-N7_UESz1a9JrXpimNb9:b-4c5ezp) ([raw file](https://github.com/gramineproject/gramine/blob/d7622f4fe1a17f8fee39307cab8c53791d62d309/pal/src/host/linux-sgx/enclave_entry.S#L826)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please rewrap
</blockquote></details>

Good catch, done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 8 of 15 files at r1, 11 of 13 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`-- commits` line 77 at r5](https://reviewable.io/reviews/gramineproject/gramine/776#-N7bDJ_L3VrY7IBOmW3n):*
I would just add these to the list above

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`-- commits` line 77 at r5](https://reviewable.io/reviews/gramineproject/gramine/776#-N7bDJ_L3VrY7IBOmW3n):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would just add these to the list above
</blockquote></details>

Please kindly help reorganize during rebase, thanks!

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 77 at r5](https://reviewable.io/reviews/gramineproject/gramine/776#-N7bDJ_L3VrY7IBOmW3n):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Please kindly help reorganize during rebase, thanks!
</blockquote></details>

Will do, I blocked on this.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 77 at r5](https://reviewable.io/reviews/gramineproject/gramine/776#-N7bDJ_L3VrY7IBOmW3n):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do, I blocked on this.
</blockquote></details>

Done

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/776)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
