### PR TITLE
[Docs] Remove more Focal leftovers from building.rst

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

More cleanup of docs which I've stumbled upon.

## How to test this PR? 

```sh
make -C Documentation html && firefox Documentation/_build/html/devel/building.html
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2055)

### CODE REVIEW

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2055)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`Documentation/devel/building.rst` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/2055#-OBBSnMH268e4ZTVZQph:-OBBVgQn9xw-NcWNpc_7:bhqaojl) ([raw file](https://github.com/gramineproject/gramine/blob/115ffeeb72e13a2a6cab9b11160109f171832c60/Documentation/devel/building.rst#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No `ninja-build` anymore?
</blockquote></details>

No, it's in meson's dependencies. It was needed when meson was installed from `pip`.

If you'd like to keep things explicit, in case someone adds another meson backend to debian's dependencies, I can chanage `ninja build && ninja install` below to `meson compile` and `meson install`, respectively.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2055)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`Documentation/devel/building.rst` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/2055#-OBBSnMH268e4ZTVZQph:-OBBX16-1rp9PZy-SlSf:bmnlbos) ([raw file](https://github.com/gramineproject/gramine/blob/115ffeeb72e13a2a6cab9b11160109f171832c60/Documentation/devel/building.rst#L42)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, it's in meson's dependencies. It was needed when meson was installed from `pip`.

If you'd like to keep things explicit, in case someone adds another meson backend to debian's dependencies, I can chanage `ninja build && ninja install` below to `meson compile` and `meson install`, respectively.
</blockquote></details>

I think we use ninja outside of Meson? See `gramine-test`.
Anyways, won't block on this.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2055)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2055)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
