### PR TITLE
[LibOS] Add `/proc/sys/kernel/pid_max` file

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The file is read-only and returns a UINT_MAX constant.

## How to test this PR? 

This is required by some LTP tests, e.g. https://github.com/gramineproject/gramine/blob/5bba58a902d099f9068e0f04b3c2a37e591a1d27/libos/test/ltp/ltp.cfg#L869

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5JruZ6Yzy_x2JkteL:-NH5JruZ6Yzy_x2JkteM:b-jx4akx) (no related file):*
Actually, let me block myself -- I could add now-enabled LTP tests in this same PR. This is a TODO for myself and Anjali.

___

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5PmzJ6_5-WJJArs3w:-NH5PmzJ6_5-WJJArs3x:b-uv014k) (no related file):*
Jenkins failed

___
___
*[`libos/src/fs/proc/fs.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5PyBH4cjoCyQvodbP:-NH5PyBH4cjoCyQvodbQ:b-4b9vk8) ([raw file](https://github.com/gramineproject/gramine/blob/11b789fcd356dcf16e0b6f5594bcf7932fc33549/libos/src/fs/proc/fs.c#L17)):*
> ```C
>     __UNUSED(dent);
> 
>     size_t buffer_size = 64;
> ```

This could be just 16
___
*[`libos/src/fs/proc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5QCvADfzRboQWyhEI:-NH5QCvADfzRboQWyhEJ:b95fbrt) ([raw file](https://github.com/gramineproject/gramine/blob/11b789fcd356dcf16e0b6f5594bcf7932fc33549/libos/src/fs/proc/fs.c#L21)):*
> ```C
>     if (!buffer)
>         return -ENOMEM;
> ```

Please add `static_assert(IDTYPE_MAX <= UINT_MAX);` otherwise the code below is not valid.
___
*[`libos/src/fs/proc/fs.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5Q49s5H7dg4dQYCSL:-NH5Q49s5H7dg4dQYCSM:b-w4ajh9) ([raw file](https://github.com/gramineproject/gramine/blob/11b789fcd356dcf16e0b6f5594bcf7932fc33549/libos/src/fs/proc/fs.c#L26)):*
> ```C
>         free(buffer);
>         return ret;
>     }
> ```

Please add `assert(ret < buffer_size);`

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: 0 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5JruZ6Yzy_x2JkteL:-NH907sX-0AaNIIgm3WX:bh1hhe3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, let me block myself -- I could add now-enabled LTP tests in this same PR. This is a TODO for myself and Anjali.
</blockquote></details>

Done. Thanks to @anjalirai-intel for (a partial) list of LTP tests.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5PmzJ6_5-WJJArs3w:-NH8iWM3CZrSpPVZkvb9:b-poqmzs) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Jenkins failed
</blockquote></details>

This is unrelated: `Command ['gramine-direct', 'fdatasync01'] timed out after 30 s`

___
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH90WiX3cIOCJ7f5izL):*
`UINT_MAX` -> `PID_MAX_LIMIT`
___
*[`libos/src/bookkeep/libos_pid.c` line 73 at r2](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH90J2qA45fIP3TdKqt:-NH90J2qA45fIP3TdKqu:b-jikyx8) ([raw file](https://github.com/gramineproject/gramine/blob/86825543ea577dce606e9ec5c5ec907951b30959/libos/src/bookkeep/libos_pid.c#L73)):*
> ```C
>         log_debug("Limit of ids reached (limit is %u)", PID_MAX_LIMIT);
>         goto out;
>     }
> ```

@boryspoplawski Is this a correct check? I'm not sure what to do in this case.
___
*[`libos/src/fs/proc/fs.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5PyBH4cjoCyQvodbP:-NH8l79N25_M2kmovF4d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/11b789fcd356dcf16e0b6f5594bcf7932fc33549/libos/src/fs/proc/fs.c#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This could be just 16
</blockquote></details>

Done.
___
*[`libos/src/fs/proc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5QCvADfzRboQWyhEI:-NH8lI8n7PjYyLvOs-XR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/11b789fcd356dcf16e0b6f5594bcf7932fc33549/libos/src/fs/proc/fs.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add `static_assert(IDTYPE_MAX <= UINT_MAX);` otherwise the code below is not valid.
</blockquote></details>

Done.
___
*[`libos/src/fs/proc/fs.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH5Q49s5H7dg4dQYCSL:-NH8lLYOB7ON1HbeGNSs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/11b789fcd356dcf16e0b6f5594bcf7932fc33549/libos/src/fs/proc/fs.c#L26)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add `assert(ret < buffer_size);`
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/bookkeep/libos_pid.c` line 73 at r2](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH90J2qA45fIP3TdKqt:-NHB0EYrCI6NNsmaFrSP:b-z3c50x) ([raw file](https://github.com/gramineproject/gramine/blob/86825543ea577dce606e9ec5c5ec907951b30959/libos/src/bookkeep/libos_pid.c#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Is this a correct check? I'm not sure what to do in this case.
</blockquote></details>

No, you have to change `_find_free_id_range`, it assumes that IDs are unlimited (whole range of its type), you'd have to introduce this limitation. There are overflow checks there, they should hint where and what to change

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: 2 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/src/ipc/libos_ipc_pid.c` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHOM6mz6pygOuj73UWx:-NHOM6mz6pygOuj73UWy:b-5eifgy) ([raw file](https://github.com/gramineproject/gramine/blob/c42c79d8f92eb32b801d467a669c9ddbe120371c/libos/src/ipc/libos_ipc_pid.c#L64)):*
> ```C
>     assert(locked(&g_id_owners_tree_lock));
> 
>     /* note that PID_MAX_LIMIT is a value *one greater* than max PID; see man proc, `pid_max` */
> ```

Maybe I should introduce `#define PID_MAX (PID_MAX_LIMIT - 1)`, to simplify the calculations here (will make it similar to `MAX_RANGE_SIZE` that was before)?
___
*[`libos/src/bookkeep/libos_pid.c` line 73 at r2](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH90J2qA45fIP3TdKqt:-NHOKTSDCGy_SCra3v0K:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/86825543ea577dce606e9ec5c5ec907951b30959/libos/src/bookkeep/libos_pid.c#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, you have to change `_find_free_id_range`, it assumes that IDs are unlimited (whole range of its type), you'd have to introduce this limitation. There are overflow checks there, they should hint where and what to change 
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/include/libos_types.h` line 163 at r4](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHQJLEZ-L8S1hHRMaOU:-NHQJLEZ-L8S1hHRMaOV:bk6m2y5) ([raw file](https://github.com/gramineproject/gramine/blob/c42c79d8f92eb32b801d467a669c9ddbe120371c/libos/include/libos_types.h#L163)):*
> ```objc
> #define IDTYPE_MAX UINT32_MAX
> 
> #define PID_MAX_LIMIT 4194304 /* Linux limit 2^22, this value is *one greater* than max PID */
> ```

Can't we keep this as normal exact value and subtract at callsite? Or do you want to keep this in sync with kernel (which uses the same name)?
Not blocking
___
*[`libos/src/ipc/libos_ipc_pid.c` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHOM6mz6pygOuj73UWx:-NHQLlS0B9EKvberu1IX:bacvbsl) ([raw file](https://github.com/gramineproject/gramine/blob/c42c79d8f92eb32b801d467a669c9ddbe120371c/libos/src/ipc/libos_ipc_pid.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe I should introduce `#define PID_MAX (PID_MAX_LIMIT - 1)`, to simplify the calculations here (will make it similar to `MAX_RANGE_SIZE` that was before)?
</blockquote></details>

Hmm, yes, that sounds like a good idea.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: 3 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/include/libos_types.h` line 163 at r4](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHQJLEZ-L8S1hHRMaOU:-NHTpVFgAoEqgyE7MzF3:bexhozf) ([raw file](https://github.com/gramineproject/gramine/blob/c42c79d8f92eb32b801d467a669c9ddbe120371c/libos/include/libos_types.h#L163)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can't we keep this as normal exact value and subtract at callsite? Or do you want to keep this in sync with kernel (which uses the same name)?
Not blocking
</blockquote></details>

Yes, I wanted to have the same name and semantics as in Linux. Introduced `PID_MAX` helper now.
___
*[`libos/src/ipc/libos_ipc_pid.c` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHOM6mz6pygOuj73UWx:-NHTpT1-B2k5NIZPlv0u:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c42c79d8f92eb32b801d467a669c9ddbe120371c/libos/src/ipc/libos_ipc_pid.c#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, yes, that sounds like a good idea.
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/ipc/libos_ipc_pid.c` line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHTsN6IAQ8SDE-3ifm9:-NHTsN6IAQ8SDE-3ifmA:b-v8sudv) ([raw file](https://github.com/gramineproject/gramine/blob/ba002dbbe289ed526ef503403179e4b8120f5a9b/libos/src/ipc/libos_ipc_pid.c#L64)):*
> ```C
>     assert(locked(&g_id_owners_tree_lock));
> 
>     static_assert(PID_MAX < IDTYPE_MAX - MAX_RANGE_SIZE, "int overflow may happen");
> ```

If I understood the code correctly it should be this, right?



_Suggestion:_
```C
PID_MAX <= IDTYPE_MAX - (MAX_RANGE_SIZE - 1)
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/src/ipc/libos_ipc_pid.c` line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHTsN6IAQ8SDE-3ifm9:-NHTvuEV9GLtgLQGo3GP:bqrhuvp) ([raw file](https://github.com/gramineproject/gramine/blob/ba002dbbe289ed526ef503403179e4b8120f5a9b/libos/src/ipc/libos_ipc_pid.c#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If I understood the code correctly it should be this, right?
</blockquote></details>

Done. I didn't want to bother with parentheses, but now I added them.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/ipc/libos_ipc_pid.c` line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHTsN6IAQ8SDE-3ifm9:-NHU0_J58rUpIg6QT8io:b9j64i9) ([raw file](https://github.com/gramineproject/gramine/blob/ba002dbbe289ed526ef503403179e4b8120f5a9b/libos/src/ipc/libos_ipc_pid.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I didn't want to bother with parentheses, but now I added them.
</blockquote></details>

But these two were not equivalent, so it was not about parentheses.
___
*[`libos/src/ipc/libos_ipc_pid.c` line 77 at r6](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHU0muk9wolrKF3mpNZ:-NHU0muk9wolrKF3mpN_:b-pqpxkn) ([raw file](https://github.com/gramineproject/gramine/blob/ffb9cc40100427e5a24c27eca67ee5ab95f5469a/libos/src/ipc/libos_ipc_pid.c#L77)):*
> ```C
>             /* `next_id` does not overlap any existing range. */
>             *start = next_id;
>             *end   = next_id + (MAX_RANGE_SIZE - 1);
> ```

Why did you add them here?
___
*[`libos/src/ipc/libos_ipc_pid.c` line 96 at r6](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHU0oieESLHUA0wVgDj:-NHU0oieESLHUA0wVgDk:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ffb9cc40100427e5a24c27eca67ee5ab95f5469a/libos/src/ipc/libos_ipc_pid.c#L96)):*
> ```C
>     /* There are no ids greater or equal to `next_id`. */
>     *start = next_id;
>     *end   = next_id + (MAX_RANGE_SIZE - 1);
> ```

ditto

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/src/ipc/libos_ipc_pid.c` line 77 at r6](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHU0muk9wolrKF3mpNZ:-NHU6Lhg0Z55dlAkjsh8:bb72slo) ([raw file](https://github.com/gramineproject/gramine/blob/ffb9cc40100427e5a24c27eca67ee5ab95f5469a/libos/src/ipc/libos_ipc_pid.c#L77)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you add them here?
</blockquote></details>

To make it clear that this calculation never overflows.

But I guess you mean that we have unsigned ints, so even if it wraps around in the middle of calculation, we still arrive at a good value? Let me remove the parens then and reinstate the assert that highlights that we have unsigned arithmetic here.
___
*[`libos/src/ipc/libos_ipc_pid.c` line 96 at r6](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHU0oieESLHUA0wVgDj:-NHU7axfECuqQOvqUIkx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ffb9cc40100427e5a24c27eca67ee5ab95f5469a/libos/src/ipc/libos_ipc_pid.c#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`libos/src/ipc/libos_ipc_pid.c` line 77 at r6](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHU0muk9wolrKF3mpNZ:-NHU8Iiy5aFeJUkTAm_q:b-mcv9b8) ([raw file](https://github.com/gramineproject/gramine/blob/ffb9cc40100427e5a24c27eca67ee5ab95f5469a/libos/src/ipc/libos_ipc_pid.c#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To make it clear that this calculation never overflows.

But I guess you mean that we have unsigned ints, so even if it wraps around in the middle of calculation, we still arrive at a good value? Let me remove the parens then and reinstate the assert that highlights that we have unsigned arithmetic here.
</blockquote></details>

Ah, this is what you meant by the first assert.
Anyway, it's fine

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1053#-NH90WiX3cIOCJ7f5izL):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`UINT_MAX` -> `PID_MAX_LIMIT`
</blockquote></details>

Done

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, 1 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1053)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`libos/test/ltp/ltp.cfg` line 730 at r8](https://reviewable.io/reviews/gramineproject/gramine/1053#-NHVsjPz073LG6s3zN4h:-NHVsjPz073LG6s3zN4i:b-52z3pq) ([raw file](https://github.com/gramineproject/gramine/blob/96add3ce5c6f4d90e64ea04de155c1db78f37082/libos/test/ltp/ltp.cfg#L730)):*
> ```INI
>     2
> 
> # don't support getting pgid of children processes
> ```

Won't block on this, but this sentence (and others below) mean something different than you intended - the current version is in imperative mood.

**Pull request merged**
