### PR TITLE
[README,Docs] Add "Users of Gramine" section

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This section currently contains only one company (as an example of the text on Gramine usage that other companies can use as a template).

## How to test this PR? 

N/A

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)

### CODE REVIEW

**Comment by monavij** [comment]
Can we add the following two entries:
Tencent Cloud:  Tencent relies on Gramine to implement several SGX based solutions by running unmodified Linux application. A Great example is the recent launch of Tencent Cloud Shuliantong product in Tencent digital ecosystem summit.

JD Cloud: JD cloud is experimenting with Gramine for several solutions.

**Review by dimakuv — COMMENTED** [review]
@monavij Done. Slightly changed the text and added hyperlinks.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230#-:-Mom0HTX6Isl726TsbgV:b-qzvtvh)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[README.rst, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76i4U9Y300oEqhtl-:-Mp76i4V2mV-s165E7Mo:bptd06l) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/README.rst#L98)):*
> ```reStructuredText
> Gramine and would like to be highlighted on our page. We are looking forward to
> collaborating with you and continue to enhance Gramine to meet the needs of your
> confidential computing use cases.
> ```

I don't like adding even more text to our main README, no one will read it if it's that long (it should be just a quick, concise intro to our project, not a few screens of text).
I'd either remove this section from the README or replace with just "Our users: <small logos>", or something similar.
___
*[Documentation/gramine-users.rst, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp74tuY6knUgBvUjIGt:-Mp74tuY6knUgBvUjIGu:b879tya) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L1)):*
> ```
> Users of Gramine
> ```

Maybe "Our users"? Non-blocking though.
___
*[Documentation/gramine-users.rst, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76I_4El-QIKVEpRi5:-Mp76I_4El-QIKVEpRi6:bb8acnp) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L11)):*
> ```reStructuredText
> cases. We will be updating this list regularly (the list is sorted
> alphabetically).
> ```

Small formality: Could we get ACK from someone from each of these companies that they really want to appear on this list?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Documentation/gramine-users.rst, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp77l1P0wK6j_Zk2-O5:-Mp77l1P0wK6j_Zk2-O6:bx8ng9u) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L6)):*
> ```reStructuredText
> We are excited to share that several companies are experimenting with Gramine
> for their confidential computing solutions. Please reach out to us at
> gramine-maintainers@googlegroups.com if you are using Gramine and would like to
> ```

Please update to `maintainers@gramineproject.io`

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @monavij)

___
*[README.rst, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76i4U9Y300oEqhtl-:-Mp7AZ0w3BZuQuIgVF0m:b-kyoi0p) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/README.rst#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like adding even more text to our main README, no one will read it if it's that long (it should be just a quick, concise intro to our project, not a few screens of text).
I'd either remove this section from the README or replace with just "Our users: <small logos>", or something similar.
</blockquote></details>

Done, I shrinked the text. Mona (and some other people?) wanted this to be in the README (i.e., on the first page of Gramine GitHub repo).

@monavij Is this new, shrinked text fine?
___
*[Documentation/gramine-users.rst, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp74tuY6knUgBvUjIGt:-Mp7BCV35aYx-vWIqA6i:bo4uk34) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Users of Gramine
> ```

Maybe "Our users"? Non-blocking though.
</blockquote></details>

No, to me "our users" sounds weird...
___
*[Documentation/gramine-users.rst, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp77l1P0wK6j_Zk2-O5:-Mp7BFhF6kb0soOgBibk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please update to `maintainers@gramineproject.io`
</blockquote></details>

Done.
___
*[Documentation/gramine-users.rst, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76I_4El-QIKVEpRi5:-Mp7BGLg2BVSaFjdK4Os:b6eo76x) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Small formality: Could we get ACK from someone from each of these companies that they really want to appear on this list?
</blockquote></details>

Do you mean that someone from these companies should write a comment in this PR that "<Company X> is fine with this text." ? @monavij Can we arrange this?

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @monavij)

___
*[README.rst, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76i4U9Y300oEqhtl-:-Mp7H3N7Ahnu5T0_PfgQ:bitsq09) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/README.rst#L98)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, I shrinked the text. Mona (and some other people?) wanted this to be in the README (i.e., on the first page of Gramine GitHub repo).

@monavij Is this new, shrinked text fine?
</blockquote></details>

I'd even drop the second sentence, it's already included under that link and it's not really relevant here (at this point the reader didn't even see the list).
___
*[Documentation/gramine-users.rst, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76I_4El-QIKVEpRi5:-Mp7HKk82JgrqEGqNcHe:b4tjhbp) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you mean that someone from these companies should write a comment in this PR that "<Company X> is fine with this text." ? @monavij Can we arrange this?
</blockquote></details>

Yup, that would be the best. Just want to have a clear ACK from them that they are happy with using their names/logos here.

**Review by monavij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[README.rst, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76i4U9Y300oEqhtl-:-Mp8pwXM-vD6kdYS_OfJ:b9bkkp1) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/README.rst#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd even drop the second sentence, it's already included under that link and it's not really relevant here (at this point the reader didn't even see the list).
</blockquote></details>

Looks great!
___
*[Documentation/gramine-users.rst, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76I_4El-QIKVEpRi5:-Mp8q5288d2rxkvxCM7z:b-43utya) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, that would be the best. Just want to have a clear ACK from them that they are happy with using their names/logos here.
</blockquote></details>

This first set was compiled based on direct feedback from the customers. So I say its fine. In future we will ask them to send a note to `maintainers@gramineproject.io` list

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[README.rst, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76i4U9Y300oEqhtl-:-MpAhegZD5DHbRNTUpCc:b-7ldze1) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/README.rst#L98)):*
<details><summary><i>Previously, monavij (Mona Vij) wrote…</i></summary><blockquote>

Looks great!
</blockquote></details>

Done. I removed the second sentence. @monavij Is this new text still fine with you?
___
*[Documentation/gramine-users.rst, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76I_4El-QIKVEpRi5:-MpAhUOO8lDHzMyCQ4RE:bl2ucb6) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L11)):*
<details><summary><i>Previously, monavij (Mona Vij) wrote…</i></summary><blockquote>

This first set was compiled based on direct feedback from the customers. So I say its fine. In future we will ask them to send a note to `maintainers@gramineproject.io` list
</blockquote></details>

@mkow Is Mona's reply fine with you?

**Review by monavij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[README.rst, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76i4U9Y300oEqhtl-:-MpCkADY7JD9X0jAI1D7:b-v9fbz9) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/README.rst#L98)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I removed the second sentence. @monavij Is this new text still fine with you?
</blockquote></details>

Sure. Fine with me. Thanks.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/gramine-users.rst, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/230#-Mp76I_4El-QIKVEpRi5:-MpCmamGCqKTpRcTlUOz:b-4d374u) ([raw file](https://github.com/gramineproject/gramine/blob/db5a26425c561d2a321a3170e0da7ad0f6622ea3/Documentation/gramine-users.rst#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow Is Mona's reply fine with you?
</blockquote></details>

It's ok then. Mona also confirmed on the call that they are fine with being listed here, so I'm resolving the discussion.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/230)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
