### PR TITLE
Fix Coverity issues

### PR DESCRIPTION
**Pull request by jkr0103**
## Description of the changes 

PR fixes Coverity issues described below:
CID 3400413: Operands don't affect result (CONSTANT_EXPRESSION_RESULT)
result_independent_of_operands nfds > 2147483647 is always false regardless of the values of its operands. This occurs as the logical second operand of "||". Code:https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/libos/src/sys/libos_poll.c#L430

CID 3400412: Operands don't affect result (CONSTANT_EXPRESSION_RESULT)
result_independent_of_operands nfds > 2147483647 is always false regardless of the values of its operands. This occurs as the logical second operand of "||". Code: https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/libos/src/sys/libos_poll.c#L379

CID 328009: Logically dead code
The indicated dead code may have performed some action; that action will never occur. In _PalSendHandle: Code can never be reached because of a logical contradiction (CWE-561). Code: https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/pal/src/host/linux/pal_streams.c#L209-L212

CID 328084: Jinja2 autoescape disabled
Disabling Jinja2 autoescape protections allows an attacker to write untrusted data to the template which, when rendered, can result in cross-site scripting (XSS) attacks. Code: https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/gen_jinja_env.py#L94

CID 327977: (#1 of 1): Unused value (UNUSED_VALUE)
assigned_pointer Assigning value from data_node->parent to file_mht_node here, but that stored value is overwritten before it can be used. In make_env: Jinja2 autoescape protection is disabled. (CWE-79). Code: https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/common/src/protected_files/protected_files.c#L235C17-L235C30

## How to test this PR? 

Jenkins test should be fine.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`python/graminelibos/gen_jinja_env.py` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1622#-NhanO7w5n-fVxaIgUW0:-NhanO7w5n-fVxaIgUW1:blgnrem) ([raw file](https://github.com/gramineproject/gramine/blob/ea7adab5b33c476d29ac6b2153f25e0fcb4c194d/python/graminelibos/gen_jinja_env.py#L96)):*
> ```Python
> 
>     #Jinja's autoescape feature escapes HTML sequences but we're rendering TOML, hence making
>     # autoescape as false here
> ```

`making autoescape as false here` -> `hence explicitly setting autoescape to False`

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`python/graminelibos/gen_jinja_env.py` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1622#-NhanO7w5n-fVxaIgUW0:-NhayJHpE4sPOdjgkL-I:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ea7adab5b33c476d29ac6b2153f25e0fcb4c194d/python/graminelibos/gen_jinja_env.py#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`making autoescape as false here` -> `hence explicitly setting autoescape to False`
</blockquote></details>

Done.

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`common/src/protected_files/protected_files.c` line 236 at r1](https://reviewable.io/reviews/gramineproject/gramine/1622#-Nhaxtlq6Wh8w46_rS1y:-Nhb1nzX4_QtrSDnfa9T:b8smil6) ([raw file](https://github.com/gramineproject/gramine/blob/ea7adab5b33c476d29ac6b2153f25e0fcb4c194d/common/src/protected_files/protected_files.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please move the definition here.
</blockquote></details>

Cannot move definition inside `DEBUG` as it's also used outside `DEBUG` as well. This line wasn't useful in `non-DEBUG` case as it's overridden before it's used.
___
*[`python/graminelibos/gen_jinja_env.py` line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/1622#-NhazWaY02sGf3_ikjeD:-Nhb2DRI5S8f6JyDtaCi:b-hvp4mr) ([raw file](https://github.com/gramineproject/gramine/blob/ea7adab5b33c476d29ac6b2153f25e0fcb4c194d/python/graminelibos/gen_jinja_env.py#L95)):*
> ```Python
> def make_env():
> 
>     #Jinja's autoescape feature escapes HTML sequences but we're rendering TOML, hence making
> ```

Inserted space between `#` and `Jinja`. Other text kept as per Dmitrii's suggestion.
___
*[`python/graminelibos/gen_jinja_env.py` line 98 at r1](https://reviewable.io/reviews/gramineproject/gramine/1622#-NhazlLIA8DsTsqjPSiR:-Nhb2Tz-6g4Gnlfm-m2Q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ea7adab5b33c476d29ac6b2153f25e0fcb4c194d/python/graminelibos/gen_jinja_env.py#L98)):*
> ```Python
>     # autoescape as false here
>     env = jinja2.Environment(undefined=jinja2.StrictUndefined, keep_trailing_newline=True,
>                              autoescape = False)
> ```

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`common/src/protected_files/protected_files.c` line 236 at r1](https://reviewable.io/reviews/gramineproject/gramine/1622#-Nhaxtlq6Wh8w46_rS1y:-NhfM_ggC481lGmQoUAw:b-9ppyjt) ([raw file](https://github.com/gramineproject/gramine/blob/ea7adab5b33c476d29ac6b2153f25e0fcb4c194d/common/src/protected_files/protected_files.c#L236)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Cannot move definition inside `DEBUG` as it's also used outside `DEBUG` as well. This line wasn't useful in `non-DEBUG` case as it's overridden before it's used.
</blockquote></details>

Ah, this variable is reused later. Please then split the variable (just move the definition to all these places).

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`common/src/protected_files/protected_files.c` line 236 at r1](https://reviewable.io/reviews/gramineproject/gramine/1622#-Nhaxtlq6Wh8w46_rS1y:-NhgV5Fp6pOnVkWlizQW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ea7adab5b33c476d29ac6b2153f25e0fcb4c194d/common/src/protected_files/protected_files.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, this variable is reused later. Please then split the variable (just move the definition to all these places).
</blockquote></details>

Done.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`common/src/protected_files/protected_files.c` line 268 at r4](https://reviewable.io/reviews/gramineproject/gramine/1622#-Nhh4pcABLICRE4FHieE:-Nhh4pcABLICRE4FHieF:b-e5xc1b) ([raw file](https://github.com/gramineproject/gramine/blob/9aadec7ec9809901b93bf963e3b29d21f7fb38d3/common/src/protected_files/protected_files.c#L268)):*
> ```C
>     data = lruc_get_first(pf->cache);
>     uint64_t dirty_idx = 0;
>     file_node_t* file_mht_node;
> ```

This should be moved inside the loop.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`common/src/protected_files/protected_files.c` line 268 at r4](https://reviewable.io/reviews/gramineproject/gramine/1622#-Nhh4pcABLICRE4FHieE:-Nhh5xuc4fSGsrhUFUau:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/9aadec7ec9809901b93bf963e3b29d21f7fb38d3/common/src/protected_files/protected_files.c#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be moved inside the loop.
</blockquote></details>

+1

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`common/src/protected_files/protected_files.c` line 268 at r4](https://reviewable.io/reviews/gramineproject/gramine/1622#-Nhh4pcABLICRE4FHieE:-Nhh8ARw74EQys-7XCmv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9aadec7ec9809901b93bf963e3b29d21f7fb38d3/common/src/protected_files/protected_files.c#L268)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1622#-NhayODX0cnDhWs1APoI:-NhhmURm2c0PLLchSSTf:b-2cvb8f) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Disabling Jinja2 autoescape protections allows an attacker to write untrusted data to the template which, when rendered, can result in cross-site scripting (XSS) attacks.

Just for the record, because now it sounds like it's a security issue: This finding is nonsense, we aren't rendering HTML in our Jinja (`autoescape` escapes only HTML) and the input to these is trusted in our case.

And overall, a note for random readers: this PR doesn't fix any real bugs, just removes some dead code.
</blockquote></details>

I will add this note (`This commit doesn't fix any real bugs, but only removes some dead code.`) to the commit message body during final rebase.

___

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1622#-NhayODX0cnDhWs1APoI:-NhjjiPIBeYr3p31JrIc:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will add this note (`This commit doesn't fix any real bugs, but only removes some dead code.`) to the commit message body during final rebase.
</blockquote></details>

Done.

___

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1622)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
