### PR TITLE
[Pal/Linux,Linux-SGX] Make sure `g_debug_map` is complete

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

After this change, `g_debug_map` contains all loaded executables, even the ones that were loaded by the system (such as main Gramine executable or protobuf).

This is not necessary for GDB integration, but will help add features such as crash location reporting (and it already helped simplify the SGX profiling system).

(This is in preparation to add source line reporting to ASan. See discussion in #32 for context: we have a raw pointer, will probably run `addr2line` in a subprocess, this is necessary for determining the right file and offset).

## How to test this PR? 

* I checked using GDB that `g_debug_map` contains all the debug maps (including `libpal.so`, `pal-sgx`, etc.)  in both Linux and Linux-SGX modes
* SGX profiling should still work, the change influences reporting _outer_ maps (so I tested that with `sgx.profile.mode = "ocall_outer" the report still contains symbols from URTS)

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[Pal/include/host/Linux-common/linux_utils.h, line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw0f7mE-0B11qqXWxa:-Mkw0f7oEImRP6btjfoQ:b-gv99ii) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/include/host/Linux-common/linux_utils.h#L35)):*
> ```objc
> };
> 
> /* Parse `/proc/<pid>/maps`; unfortunately the function is pretty gragile w.r.t. the exact format */
> ```

Typo: `gragile`
Also `.` missing at the end
___
*[Pal/include/host/Linux-common/linux_utils.h, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw1ezA0QU3C7XRf4Pb:-Mkw1ezB3YCN6b1P4UoR:b-lhcfg6) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/include/host/Linux-common/linux_utils.h#L36)):*
> ```objc
> 
> /* Parse `/proc/<pid>/maps`; unfortunately the function is pretty gragile w.r.t. the exact format */
> int parse_proc_maps(const char* path, int (*callback)(struct proc_maps_range* r, void* arg),
> ```

I don't see the definition of this function anywhere, how does this work???
___
*[Pal/src/host/Linux/db_memory.c, line 178 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw2xu9Ee0vVJwtr5cs:-Mkw2xu9Ee0vVJwtr5ct:b9sqqml) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/src/host/Linux/db_memory.c#L178)):*
> ```C
>     }
> 
>     if (r->name && strcmp(r->name, "[vvar]") == 0) {
> ```

Hm, wouldn't:
```c
if (r->name) {
    if (!strcmp(...)) {
        ...
    } else if (!strcmp(...)) {
        ...
    } 
}
```
be a bit easier to read? Idk, maybe not, not blocking.
___
*[Pal/src/host/Linux-common/debug_map.c, line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw8ox83aZ6fTGYS8Yp:-Mkw8ox83aZ6fTGYS8Yq:b-e9iwqn) ([raw file](https://github.com/gramineproject/gramine/blob/093531f48cf73d26b9eba6e86184760cc80fb8fd/Pal/src/host/Linux-common/debug_map.c#L46)):*
> ```C
>     struct debug_map* map = g_debug_map;
>     while (map) {
>         if (map->addr == addr && strcmp(name, map->name)) {
> ```

So now we allow two maps at the same address, as long as their name is the same?
Update: judging from usage of this function, it should be `!strcmp`. Actually, wouldn't it be better to return `0` here if both `addr` and `name` match and `-EEXIST` if `addr` is the same and `name` is different? Then in the callback below we just just return this value directly.
___
*[Pal/src/host/Linux-common/debug_map.c, line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw9ESY84VgvvFsbSUa:-Mkw9ESY84VgvvFsbSUb:b-q0yb9t) ([raw file](https://github.com/gramineproject/gramine/blob/093531f48cf73d26b9eba6e86184760cc80fb8fd/Pal/src/host/Linux-common/debug_map.c#L113)):*
> ```C
> 
>     /* [vvar], [vdso] etc. */
>     if (r->name[0] == '[')
> ```

Maybe `r->name[0] != '/'` to be safe?
Since we heavily depend on the format, we may just assume that all paths are absolute (which seems to be the case).
___
*[Pal/src/host/Linux-common/file_utils.c, line 138 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw50s18Nc-EZRnuC_o:-Mkw50s20OT2jJWqMr4T:b5g6ign) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/src/host/Linux-common/file_utils.c#L138)):*
> ```C
>         char* line_end;
>         while ((line_end = strchr(buf, '\n')) != NULL) {
>             size_t line_len = line_end - buf;
> ```

Do we need this temporary variable? I think it's just making the code less readable. E.g.:
`buf[line_len] = '\0';` -> `*line_end = 0;`
```c
len -= line_end + 1 - buf;
memmove(buf, line_end + 1, len + 1);
```
___
*[Pal/src/host/Linux-common/meson.build, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw3rYJALcv_vqZnJKq:-Mkw3rYJALcv_vqZnJKr:bnd0k9n) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/src/host/Linux-common/meson.build#L7)):*
> ```Meson
>     'gramine_unix_socket_addr.c',
>     'main_exec_path.c',
>     'proc_maps.c',
> ```

There is no such file in this commit, something's seriously wrong here...
___
*[Pal/src/host/Linux-common/proc_maps.c, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/111#-MkwAKUF3NFLNrUDV1wD:-MkwAKUF3NFLNrUDV1wE:b-v0kga7) ([raw file](https://github.com/gramineproject/gramine/blob/093531f48cf73d26b9eba6e86184760cc80fb8fd/Pal/src/host/Linux-common/proc_maps.c#L1)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

Oh, here it is. You have some problems with commits split (i.e. this file should belong to the previous commit).
___
*[Pal/src/host/Linux-common/proc_maps.c, line 96 at r2](https://reviewable.io/reviews/gramineproject/gramine/111#-MkwFC-464utBG7zayo4:-MkwFC-464utBG7zayo5:bdtyxe7) ([raw file](https://github.com/gramineproject/gramine/blob/093531f48cf73d26b9eba6e86184760cc80fb8fd/Pal/src/host/Linux-common/proc_maps.c#L96)):*
> ```C
>     struct proc_maps_range r;
>     if (parse_proc_maps_line(line, &r) < 0) {
>         log_warning("%s: failed to parse /proc/maps line \"%s\"", __func__, line);
> ```

Nitpick: `/proc/self/maps` or `/proc/[pid]/maps`

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)* status: 1 of 12 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[Pal/include/host/Linux-common/linux_utils.h, line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw0f7mE-0B11qqXWxa:-MkwGpRB52sC2YBBDnRK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/include/host/Linux-common/linux_utils.h#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Typo: `gragile`
Also `.` missing at the end
</blockquote></details>

Done.
___
*[Pal/include/host/Linux-common/linux_utils.h, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw1ezA0QU3C7XRf4Pb:-MkwNHdDC3l_2XwMvsi3:bf2uptn) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/include/host/Linux-common/linux_utils.h#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't see the definition of this function anywhere, how does this work???
</blockquote></details>

Hopefully fixed now...
___
*[Pal/src/host/Linux/db_memory.c, line 178 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw2xu9Ee0vVJwtr5cs:-MkwHDVp7jXdRcDnlewc:b-aohcde) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/src/host/Linux/db_memory.c#L178)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, wouldn't:
```c
if (r->name) {
    if (!strcmp(...)) {
        ...
    } else if (!strcmp(...)) {
        ...
    } 
}
```
be a bit easier to read? Idk, maybe not, not blocking.
</blockquote></details>

Makes sense. And I can use `!strcmp`, unfortunately it looks like we use both more or less equally often :)

Done.
___
*[Pal/src/host/Linux-common/debug_map.c, line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw8ox83aZ6fTGYS8Yp:-MkwHkNr6dIv-_dgeXAQ:b-tayifd) ([raw file](https://github.com/gramineproject/gramine/blob/093531f48cf73d26b9eba6e86184760cc80fb8fd/Pal/src/host/Linux-common/debug_map.c#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

So now we allow two maps at the same address, as long as their name is the same?
Update: judging from usage of this function, it should be `!strcmp`. Actually, wouldn't it be better to return `0` here if both `addr` and `name` match and `-EEXIST` if `addr` is the same and `name` is different? Then in the callback below we just just return this value directly.
</blockquote></details>

Right, it needs to be `!strcmp`.

Sounds good, and I think it's worth it to detect situations where name doesn't match. Updated.
___
*[Pal/src/host/Linux-common/debug_map.c, line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw9ESY84VgvvFsbSUa:-MkwK92f9YcTHubuLHM6:b-xja1de) ([raw file](https://github.com/gramineproject/gramine/blob/093531f48cf73d26b9eba6e86184760cc80fb8fd/Pal/src/host/Linux-common/debug_map.c#L113)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe `r->name[0] != '/'` to be safe?
Since we heavily depend on the format, we may just assume that all paths are absolute (which seems to be the case).
</blockquote></details>

Done.

And I changed the above comment from "not a file" to "no name", vvar/vdso are not files either.
___
*[Pal/src/host/Linux-common/file_utils.c, line 138 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw50s18Nc-EZRnuC_o:-MkwKw6-6uXUfSP2j9wZ:bcjnpz) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/src/host/Linux-common/file_utils.c#L138)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we need this temporary variable? I think it's just making the code less readable. E.g.:
`buf[line_len] = '\0';` -> `*line_end = 0;`
```c
len -= line_end + 1 - buf;
memmove(buf, line_end + 1, len + 1);
```
</blockquote></details>

That looks much better. Done.
___
*[Pal/src/host/Linux-common/proc_maps.c, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/111#-MkwAKUF3NFLNrUDV1wD:-MkwLFQrAkLku0zP-5ai:b8zxik1) ([raw file](https://github.com/gramineproject/gramine/blob/093531f48cf73d26b9eba6e86184760cc80fb8fd/Pal/src/host/Linux-common/proc_maps.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Oh, here it is. You have some problems with commits split (i.e. this file should belong to the previous commit).
</blockquote></details>

Oh, right! Sorry about that. I rebased the branch to fix the commits.
___
*[Pal/src/host/Linux-common/proc_maps.c, line 96 at r2](https://reviewable.io/reviews/gramineproject/gramine/111#-MkwFC-464utBG7zayo4:-MkwMYaKBfWVGx8Rng2o:bt14npp) ([raw file](https://github.com/gramineproject/gramine/blob/093531f48cf73d26b9eba6e86184760cc80fb8fd/Pal/src/host/Linux-common/proc_maps.c#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nitpick: `/proc/self/maps` or `/proc/[pid]/maps`
</blockquote></details>

Ok, changed to `/proc/[pid]/maps`.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[Pal/src/host/Linux/db_memory.c, line 178 at r1](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw2xu9Ee0vVJwtr5cs:-MkwO5Wr-ITTaeYL9jZj:bz8pd1s) ([raw file](https://github.com/gramineproject/gramine/blob/31887291181d2712fd2bfc2ae3919a6a775916f1/Pal/src/host/Linux/db_memory.c#L178)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Makes sense. And I can use `!strcmp`, unfortunately it looks like we use both more or less equally often :)

Done.
</blockquote></details>

I personally tend to use `!strcmp`, but I don't mind `strcmp() == 0` either. I guess others do not insist on any of these versions in reviews too, so it's up to the author - which means we have both versions :)
___
*[Pal/src/host/Linux-common/debug_map.c, line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/111#-Mkw9ESY84VgvvFsbSUa:-MkwPmm64dm4Vuv5ibn_:b22r1z8) ([raw file](https://github.com/gramineproject/gramine/blob/093531f48cf73d26b9eba6e86184760cc80fb8fd/Pal/src/host/Linux-common/debug_map.c#L113)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.

And I changed the above comment from "not a file" to "no name", vvar/vdso are not files either.
</blockquote></details>

Well, `vdso` is an elf, it's just not present on the filesystem :)
___
*[Pal/src/host/Linux-common/debug_map.c, line 49 at r4](https://reviewable.io/reviews/gramineproject/gramine/111#-MkwPV4M8sy8t5BafDVN:-MkwPV4M8sy8t5BafDVO:b5aa2jd) ([raw file](https://github.com/gramineproject/gramine/blob/02bbb4ddf9d9e3ca12bacba6272dbab667bc0bb3/Pal/src/host/Linux-common/debug_map.c#L49)):*
> ```C
>             bool name_matches = !strcmp(name, map->name);
>             spinlock_unlock(&g_debug_map_lock);
>             /* If the name matches, allow adding the same map twice: this can happen e.g. because we
> ```

Nitpick: we are not adding the same map twice, we kind of skip the second add since it's valid, but not needed (as it's present already).

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)* status: 11 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-common/debug_map.c, line 49 at r4](https://reviewable.io/reviews/gramineproject/gramine/111#-MkwPV4M8sy8t5BafDVN:-MkwQ_ig5dbjX5vm6t7T:b-qj92pf) ([raw file](https://github.com/gramineproject/gramine/blob/02bbb4ddf9d9e3ca12bacba6272dbab667bc0bb3/Pal/src/host/Linux-common/debug_map.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nitpick: we are not adding the same map twice, we kind of skip the second add since it's valid, but not needed (as it's present already).
</blockquote></details>

Reworded.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 4 of 11 files at r3, 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/111#-MlATx9GADoxK4caSt8N:-MkwQ-_s4Q73aI1YyHb2:b-omsg2v) (no related file):*
`Jenkins-Debug-18.04` failed, but it was 3 days ago and with our current Jenkins usage, it's no longer in history, so couldn't check why.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 8 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 8 of 8 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/111)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
