### PR TITLE
[Docs] quickstart: Add missing `-Dtests=enabled`

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

The quickstart guide says to run `helloworld`, so we need to enable building tests.

## How to test this PR? 

Following the quickstart guide should work.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/187)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/187)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/187)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/187)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/187#-MnRIRPk9DXZH6UonQR0:-MnRIRPk9DXZH6UonQR1:b-2vd7r3) (no related file):*
Can't we instead rewrite the example to run something else? `-Dtests` shouldn't be used in production, and certainly shouldn't be taught to anyone just starting with gramine.

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/187)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/187#-MnRIRPk9DXZH6UonQR0:-MnRqKXaEDo8W6RpZj9k:bmaa6so) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can't we instead rewrite the example to run something else? `-Dtests` shouldn't be used in production, and certainly shouldn't be taught to anyone just starting with gramine.
</blockquote></details>

What do you propose? I'd use one of the projects from `CI-Examples`, but they're not as simple as helloworld. Busybox maybe?

```
cd CI-Examples/busybox
make SGX=1
gramine-sgx busybox echo "hello from Gramine"
```

---

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/187)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/187#-MnRIRPk9DXZH6UonQR0:-MnUUiJX1y20CJeBN4-1:b-foftvz) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What do you propose? I'd use one of the projects from `CI-Examples`, but they're not as simple as helloworld. Busybox maybe?

```
cd CI-Examples/busybox
make SGX=1
gramine-sgx busybox echo "hello from Gramine"
```
</blockquote></details>

Well, let's just add a proper HelloWorld example to `CI-Examples`. It makes more sense to have HelloWorld as an example rather than as a regression test anyway, so I agree here with Woju. So we'll have `CI-Examples/helloworld` with four files: `helloworld.c`, `README`, `Makefile` and `helloworld.manifest.template`.

I don't like the idea of using Busybox as an example, many people don't know what it is and this example is overly complicated. What we need is a barebones Helloworld.

I'm not blocking this PR, but if @pwmarcz can do it, then adding `CI-Examples/helloworld` sounds logical to me.

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/187)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/187#-MnRIRPk9DXZH6UonQR0:-MnVX4Ef4BBPLGxhZYvz:bij30iz) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, let's just add a proper HelloWorld example to `CI-Examples`. It makes more sense to have HelloWorld as an example rather than as a regression test anyway, so I agree here with Woju. So we'll have `CI-Examples/helloworld` with four files: `helloworld.c`, `README`, `Makefile` and `helloworld.manifest.template`.

I don't like the idea of using Busybox as an example, many people don't know what it is and this example is overly complicated. What we need is a barebones Helloworld.

I'm not blocking this PR, but if @pwmarcz can do it, then adding `CI-Examples/helloworld` sounds logical to me.
</blockquote></details>

OK. I created a new PR: https://github.com/gramineproject/gramine/pull/188

---

**Pull request closed without merging**
