### PR TITLE
[Docs] Improve wording about commandline arguments

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The wording is slightly less verbose and represented as a bullet list now. Reads easier.

One person complained about the previous paragraph with three options (it was confusingly written). Also, the `Note` kinda splits the section into two halves, and people didn't notice the second half.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/880)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`AssertionError: Command ['gramine-direct', 'fdatasync01'] timed out after 30 s`)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/880)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 140 at r1](https://reviewable.io/reviews/gramineproject/gramine/880#-NBCcQJf9Fr1ct1YHLYS:-NBCcQJf9Fr1ct1YHLYT:b-al1kb9) ([raw file](https://github.com/gramineproject/gramine/blob/d314906c8842e7ef872ad8c810967d7ba4d35ddd/Documentation/manifest-syntax.rst#L140)):*
> ```reStructuredText
> ``loader.argv_src_file`` is intended to point to either a trusted file or an
> encrypted file. The former allows to securely hardcode arguments (current
> manifest syntax doesn't allow to include them inline), the latter allows the
> ```

This is outdated (2nd option is exactly this)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/880)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`Documentation/manifest-syntax.rst` line 140 at r1](https://reviewable.io/reviews/gramineproject/gramine/880#-NBCcQJf9Fr1ct1YHLYS:-NBCnS1S4iv3NVKwefQ0:b-j5lrd1) ([raw file](https://github.com/gramineproject/gramine/blob/d314906c8842e7ef872ad8c810967d7ba4d35ddd/Documentation/manifest-syntax.rst#L140)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is outdated (2nd option is exactly this)
</blockquote></details>

Done. Just removed the sentence in brackets.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/880)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/880)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/880)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/880)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
