### PR TITLE
[PAL] Allow for bookkeeping internal memory

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
One hack less

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1061)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1061)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1061)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1061)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1061)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
