### PR TITLE
[Docs] Update sphinx to 5.3

### PR DESCRIPTION
**Pull request by woju**
## How to test this PR? 

```
make -C Documentation html man
firefox Documentation/_build/html/index.html
man ./Documentation/_build/man/gramine-manifest.1
```

Also see a version matching this PR at https://readthedocs.org/projects/gramine/builds/

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-NriVfMM2jHAY7LcCpH5:b896hjl) (no related file):*
The `Docs` CI failed, is it not updated to latest Debian stable or why?

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-Nrj8ViL4JuNqcCak44J:b-tj9pqn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The `Docs` CI failed, is it not updated to latest Debian stable or why?
</blockquote></details>

I'm thinking about abandoning docs pipeline, and instead fixing RTD integration. Jenkins pipeline takes time on our CI, and RTD integration won't.

___

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-Ns33lCq0pbwjiOx68gy:b-w0rf2v) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sounds Ok to me.
</blockquote></details>

What do you mean by "RTD integration"? Plugging RTD into GitHub status checks? I'd like to keep something in status checks which verified that the docs build (but yes, the current solution isn't great).

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-Ns3OxhrBx4eazj0i-RZ:-Ns3Oxi41VPPyuP4Rdt1:b9yfoar) (no related file):*
Something is still wrong, the function signatures aren't getting included in the docs anymore. See e.g. https://gramine--1784.org.readthedocs.build/en/1784/pal/host-abi.html#memory-allocation.

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: 3 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-NsnPXy75af5hmtbNGWu:b-tel9re) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean by "RTD integration"? Plugging RTD into GitHub status checks? I'd like to keep something in status checks which verified that the docs build (but yes, the current solution isn't great).
</blockquote></details>

RTD has two features (I think it might be relatively recent) that it 1) builds each PR and 2) reports a status on github how it went. Free CI essentially. I think it might be "check" not "status", so similar to the current DCO thing, not Jenkins.

@dimakuv tried to set it up (I can't do it, because I don't have admin rights on repo), but something was broken and we have only PR builds, not CI check.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-Ns3OxhrBx4eazj0i-RZ:-Nsn_H_c-d0mGBfvdW-r:b-iss4sk) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Something is still wrong, the function signatures aren't getting included in the docs anymore. See e.g. https://gramine--1784.org.readthedocs.build/en/1784/pal/host-abi.html#memory-allocation.
</blockquote></details>

It was missing python module for doxygen support (`breathe`).

After the fix, it will fail in such a way, if we forget it in the future: https://readthedocs.org/projects/gramine/builds/23726615/.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: 3 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-Nsw6GuS8m5oJ1KOu7u5:bednyxi) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

RTD has two features (I think it might be relatively recent) that it 1) builds each PR and 2) reports a status on github how it went. Free CI essentially. I think it might be "check" not "status", so similar to the current DCO thing, not Jenkins.

@dimakuv tried to set it up (I can't do it, because I don't have admin rights on repo), but something was broken and we have only PR builds, not CI check.
</blockquote></details>

@woju @mkow So what are we doing now? Our old `Docs` pipeline still fails, and the new RTD check is not connected to the Gramine repo.

Should we try to connect the RTD check ("free CI") again?

___

**Review by mkow — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-NtNFvQQ7ovwAZweEH7l:bccm2fo) (no related file):*
> might be "check" not "status"

Is there any difference between these two? Both DCO and Jenkins status checks look the same on GitHub PR page, at least to me.

> Should we try to connect the RTD check ("free CI") again?

Sounds good, let's try that.

___
___
*[`Documentation/conf.py` line 207 at r2](https://reviewable.io/reviews/gramineproject/gramine/1784#-NtNHoYn5r7s0ExEIEMb:-NtNHoYn5r7s0ExEIEMc:b-20t34m) ([raw file](https://github.com/gramineproject/gramine/blob/e71df826fdd582476eac7d7920222c8afb632b36/Documentation/conf.py#L207)):*
> ```Python
>     def generate_doxygen(app):
>         pass
> ```

Please no empty line here, it reads at first like both code blocks were unrelated.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: 6 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`Documentation/conf.py` line 207 at r2](https://reviewable.io/reviews/gramineproject/gramine/1784#-NtNHoYn5r7s0ExEIEMb:-NtqSGVh2f787ALEPQHB:bdur732) ([raw file](https://github.com/gramineproject/gramine/blob/e71df826fdd582476eac7d7920222c8afb632b36/Documentation/conf.py#L207)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please no empty line here, it reads at first like both code blocks were unrelated.
</blockquote></details>

I think this is the best way to do it, because the contents of the `else:` block needs empty lines. Removing empty line here would cause an illusion that only `extensions.extend()` is part of `else:`, but `def generate_doxygen()` and further code is not. Someone could even be tempted to "fix indentation error" and dedent `def` to toplevel, because `def`s are only on toplevel or inside `class:`, right?

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-Ntqc8cG7Q6QIw0mHHad:b-su31lh) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> might be "check" not "status"

Is there any difference between these two? Both DCO and Jenkins status checks look the same on GitHub PR page, at least to me.

> Should we try to connect the RTD check ("free CI") again?

Sounds good, let's try that.
</blockquote></details>

We had some discussions with woju and it seems that we should try to fix `Docs` pipeline instead. The app integration is a bit fishy, it requires some poorly documented permissions to all the repos of an account which will be used for linking, and also will have access to status checks from other sources (e.g. could overwrite Reviewable checks).

___
___
*[`.ci/debian12.dockerfile` line 27 at r3](https://reviewable.io/reviews/gramineproject/gramine/1784#-NtqaQIA2qkwa0t4rBD-:-NtqaQIA2qkwa0t4rBD0:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/e03fe7affdfa35015e0e7f331319a8ae29df8089/.ci/debian12.dockerfile#L27)):*
> ```Dockerfile
> RUN apt-get update && apt-get -y build-dep --no-install-recommends --no-install-suggests /
> 
> # for HTML docs build, which is not done in packages, so not in Build-Depends:
> ```





_Suggestion:_
```Dockerfile
so it's not in Build-Depends:
```
___
*[`Documentation/conf.py` line 207 at r2](https://reviewable.io/reviews/gramineproject/gramine/1784#-NtNHoYn5r7s0ExEIEMb:-Ntqah8_BsTxU6Ga3DUh:b-d29j7w) ([raw file](https://github.com/gramineproject/gramine/blob/e71df826fdd582476eac7d7920222c8afb632b36/Documentation/conf.py#L207)):*
Yes, but IMO the current version is much more confusing to read. We often have empty lines _inside_ if-else blocks, so we're used to reading such code. But not between `if` and `else`. Out of 39 `else:` occurrences in Gramine none of them have an empty line before.

> Someone could even be tempted to "fix indentation error" and dedent `def` to toplevel, because `def`s are only on toplevel or inside `class:`, right?

Nah, we wouldn't do that, we don't merge random changes like that without justification why it was a bug previously. Also, how is this related to the newline before `else:`? This part seem to be a problem even with the empty line, it's just something which doesn't have a good solution.

**Review by kailun-qin — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`Documentation/conf.py` line 207 at r2](https://reviewable.io/reviews/gramineproject/gramine/1784#-NtNHoYn5r7s0ExEIEMb:-Ntseu69ERgYq2asm5N0:b-xp91oq) ([raw file](https://github.com/gramineproject/gramine/blob/e71df826fdd582476eac7d7920222c8afb632b36/Documentation/conf.py#L207)):*
> which version do you prefer? Let's just vote.

I slightly prefer the version without the empty line.

P.S. maybe make e.g. `extensions.extend()`, `source_suffix.update()` in one line and remove the gaps in `else:`?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: 7 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-NuSvdWQ7V0K5BGrs3i0:b-jaowgx) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This is because Reviewable itself is an OAuth app, not "GitHub App", so we can't require that the status comes from Reviewable app

I blame GitHub ;) GitHub Apps should be allowed to write only their own statuses (or maybe require a separate permission for apps which intentionally want to override other statuses).

> I disagree that RTD is fishy

But I didn't mean that RTD is fishy. The integration with GitHub is, for which I blame GitHub and their permission model.
</blockquote></details>

Right. Yeah, the situation with GitHub, two different apps and the whole host of issues around that is 

___
___
*[`Documentation/conf.py` line 207 at r2](https://reviewable.io/reviews/gramineproject/gramine/1784#-NtNHoYn5r7s0ExEIEMb:-NuTZXjgDp9IvmAe9oWY:b7quv52) ([raw file](https://github.com/gramineproject/gramine/blob/e71df826fdd582476eac7d7920222c8afb632b36/Documentation/conf.py#L207)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> which version do you prefer? Let's just vote.

I slightly prefer the version without the empty line.

P.S. maybe make e.g. `extensions.extend()`, `source_suffix.update()` in one line and remove the gaps in `else:`?
</blockquote></details>

Done. I've rearranged some stuff to remove all whitespace (loosely based on @kailun-qin 's suggestion), maybe this is OK?

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-NuTZygj6MZJ79NVHpMB:b-rv1zu0) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Right. Yeah, the situation with GitHub, two different apps and the whole host of issues around that is
</blockquote></details>

Ok, so the final conclusion is that we are fixing the Docs pipeline in our CI, and **not** adding the RTD integration check.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

**Comment by woju** [comment]
Jenkins, test Jenkins-SGX-Sanitizers please (timeout)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: 5 of 12 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1784#-NriVfMM2jHAY7LcCpH4:-NuZDjJI9nYgNI9Zj04B:b-6g977k) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, so the final conclusion is that we are fixing the Docs pipeline in our CI, and **not** adding the RTD integration check.
</blockquote></details>

I think it doesn't matter at this point, some people have authorized that app anyway (it's authorized against users, not repos), so I'd be surprised if RTD did not already have capability to overwrite reviewable status. It's probably just posturing.

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: 11 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`Documentation/conf.py` line 132 at r6](https://reviewable.io/reviews/gramineproject/gramine/1784#-NuZrjaSCsaxBjt9IMEo:-Nu_FTc60JoYhsjEcCzo:b-vcycw1) ([raw file](https://github.com/gramineproject/gramine/blob/042095e644f4f8b695b4bf2ded73e87f9d979675/Documentation/conf.py#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO?
</blockquote></details>

Yes. For some reason doxygen won't find the last entry in CPUID_WORD enum and it says it's missing. I don't feel like debugging this right now, maybe someone who knows C better than me will fix it someday. I don't even know where this is referenced.
___
*[`Documentation/devel/features.md` line 1540 at r6](https://reviewable.io/reviews/gramineproject/gramine/1784#-NuZtlxL0KhDThojKMQk:-Nu_JKNoEGusxwXJL3W2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/042095e644f4f8b695b4bf2ded73e87f9d979675/Documentation/devel/features.md#L1540)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This doesn't render properly. Please check all the changes in this PR if they actually render.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`Documentation/conf.py` line 132 at r6](https://reviewable.io/reviews/gramineproject/gramine/1784#-NuZrjaSCsaxBjt9IMEo:-Nu_Yf1KAeEq5-lPO9co:b-44a1l7) ([raw file](https://github.com/gramineproject/gramine/blob/042095e644f4f8b695b4bf2ded73e87f9d979675/Documentation/conf.py#L132)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes. For some reason doxygen won't find the last entry in CPUID_WORD enum and it says it's missing. I don't feel like debugging this right now, maybe someone who knows C better than me will fix it someday. I don't even know where this is referenced.
</blockquote></details>

Then please explain what's that TODO about, if I was reading the code without this PR I'd have no idea what you mean (i.e. what is to be done here).

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)

___
*[`Documentation/conf.py` line 132 at r6](https://reviewable.io/reviews/gramineproject/gramine/1784#-NuZrjaSCsaxBjt9IMEo:-Nuc5Azl7yzwVfwd0--Q:beus5st) ([raw file](https://github.com/gramineproject/gramine/blob/042095e644f4f8b695b4bf2ded73e87f9d979675/Documentation/conf.py#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then please explain what's that TODO about, if I was reading the code without this PR I'd have no idea what you mean (i.e. what is to be done here).
</blockquote></details>

Alternatively, why not move this under the last group, with `parsing of these seems to be broken`

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: 11 of 12 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`Documentation/conf.py` line 132 at r6](https://reviewable.io/reviews/gramineproject/gramine/1784#-NuZrjaSCsaxBjt9IMEo:-Nudp_itAG2Qi8Pb54LG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/042095e644f4f8b695b4bf2ded73e87f9d979675/Documentation/conf.py#L132)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Alternatively, why not move this under the last group, with `parsing of these seems to be broken`
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 5 of 7 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 7 files at r6, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-20.04 please (`tests.test_sgx_sign.test_sign_from_pem_path_with_passphrase` unrelated test failed)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1784)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
