### PR TITLE
[CI] Ubuntu 24.04 and 22.04 part 3/?

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

See #2026 for rationale

## How to test this PR? 

CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2028)

### CODE REVIEW

**Comment by woju** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2028)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`-- commits` line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/2028#-O9E4lR8-xY6M8n-8ROB):*
Not blocking, but this commit message contains a ton of unnecessary info. Why not simply:
```
[LibOS/tests] Fix openmp manifest to add shm tmpfs

There is a known issue in some versions of `libomp` (the
LLVM implementation of OpenMP), and probably also in `libiomp` (Intel
implementation of OpenMP). Those versions require /dev/shm to
exist. This commit modifies the openmp manifest to add this dir as a
tmpfs mount. With this fix, the files under /dev/shm/ are not visible on
the host, so security of the application remains intact.

Based on the suggestion by Dmitrii Kuvaiskii. See 
https://github.com/gramineproject/gramine/discussions/1780#discussioncomment-8589083
```

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2028)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/2028#-O9E4lR8-xY6M8n-8ROB):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not blocking, but this commit message contains a ton of unnecessary info. Why not simply:
```
[LibOS/tests] Fix openmp manifest to add shm tmpfs

There is a known issue in some versions of `libomp` (the
LLVM implementation of OpenMP), and probably also in `libiomp` (Intel
implementation of OpenMP). Those versions require /dev/shm to
exist. This commit modifies the openmp manifest to add this dir as a
tmpfs mount. With this fix, the files under /dev/shm/ are not visible on
the host, so security of the application remains intact.

Based on the suggestion by Dmitrii Kuvaiskii. See 
https://github.com/gramineproject/gramine/discussions/1780#discussioncomment-8589083
```
</blockquote></details>

+1 (for not leaving my wrong suggestion in the commit msg) :)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2028)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/2028#-O9E4lR8-xY6M8n-8ROB):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1 (for not leaving my wrong suggestion in the commit msg) :)
</blockquote></details>

Done.

:)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2028)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2028)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2028)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 7 files at r6, 4 of 4 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2028)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 7 of 7 files at r6, 4 of 4 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2028)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
