### PR TITLE
[Pal] Un-tag topology structures

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Just a simple change, as it was discussed in #325's review.

## How to test this PR? 

CI, no functional changes intended.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/351)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/351)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/351)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/351#-MtqdiSe1r_VUQkBwuSd):*
I do not understand `Un-tag` here. What has tagging to do with hiding actual types with `typedef`? I would prefer to reword this oneliner

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/351)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/351#-MtqdiSe1r_VUQkBwuSd):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I do not understand `Un-tag` here. What has tagging to do with hiding actual types with `typedef`? I would prefer to reword this oneliner
</blockquote></details>

Isn't "tagged structure" the name used for such typedefing in C?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/351)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/351#-MtqdiSe1r_VUQkBwuSd):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't "tagged structure" the name used for such typedefing in C?
</blockquote></details>

Never heard of it and quick google doesn't show much - only results I've found used it as the structure identifier, i.e. `struct this_is_a_tag {};`

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/351)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/351#-MtqdiSe1r_VUQkBwuSd):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Never heard of it and quick google doesn't show much - only results I've found used it as the structure identifier, i.e. `struct this_is_a_tag {};`
</blockquote></details>

Better now?

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/351)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/351#-MtqdiSe1r_VUQkBwuSd):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Better now?
</blockquote></details>

Yes

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/351)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
