### PR TITLE
[Pal/Linux-SGX] Support musl version of ptrace

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

Some operating systems (like Alpine Linux) use `sys/ptrace.h` header from musl, which define ptrace requests as macros instead of enum.

glibc version - https://codebrowser.dev/glibc/glibc/sysdeps/unix/sysv/linux/x86/sys/ptrace.h.html#__ptrace_request
musl version - https://git.musl-libc.org/cgit/musl/tree/include/sys/ptrace.h#n12

## How to test this PR? 

Build with glibc and musl.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 245 at r1](https://reviewable.io/reviews/gramineproject/gramine/1311#-NTxczfA1cvFiAqAAYAO:-NTxczfA1cvFiAqAAYAP:b-n8zlgt) ([raw file](https://github.com/gramineproject/gramine/blob/2f1bec7578149659e7db05c371812cebcbc16601/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L245)):*
> ```C
> 
>     DEBUG_LOG("[enclave thread %d] TCS at 0x%lx: TCS.ossa = 0x%lx TCS.cssa = %d\n", tid,
>           (long)tcs_addr, tcs_part.ossa, tcs_part.cssa);
> ```

This should be wrapped to `(`.
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 527 at r1](https://reviewable.io/reviews/gramineproject/gramine/1311#-NTxd1A2BGnNghUGsnEZ:-NTxd1A2BGnNghUGsnE_:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2f1bec7578149659e7db05c371812cebcbc16601/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L527)):*
> ```C
> 
>     DEBUG_LOG("[GDB %d] Intercepted ptrace(%s, %d, %p, %p)\n", getpid(),
>           str_ptrace_request(request), tid, addr, data);
> ```

ditto

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @oshogbo)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1311#-NTxsrA-6dRabF8kc9ln:-NTxsrA-6dRabF8kc9lo:b9viffj) (no related file):*
Interesting. So this blocked debugging of Alpine-based applications? How did you encounter this?

___

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 706 at r2](https://reviewable.io/reviews/gramineproject/gramine/1311#-NU0rYS87uQ5lYAE05ht:-NU0rYS87uQ5lYAE05hu:b-st9sam) ([raw file](https://github.com/gramineproject/gramine/blob/a171431282137fc84a65535e2b4a2b6f7b7af0b0/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L706)):*
> ```C
>             ret = host_ptrace(PTRACE_SETREGS, tid, NULL, &regs);
>             if (ret < 0) {
>                 DEBUG_LOG("Cannot set RIP to ERESUME to continue single-step in enclave thread %d\n",
> ```

This is 1 char above 100-char limit :) Please fix

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 706 at r2](https://reviewable.io/reviews/gramineproject/gramine/1311#-NU0rYS87uQ5lYAE05ht:-NU1Jxpk3_CaYoFv_Wvf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a171431282137fc84a65535e2b4a2b6f7b7af0b0/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L706)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is 1 char above 100-char limit :) Please fix
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1311)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
