### PR TITLE
[Docs] Add enclaive.io to "Users of Gramine" section

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Adding https://enclaive.io/ text.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/494)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/494)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Documentation/gramine-users.rst, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/494#-MzuXhb44iufS2m28uTG:-MzuXhb44iufS2m28uTH:b-7ilvfz) ([raw file](https://github.com/gramineproject/gramine/blob/5acd38b90b3232bb2b11336d98d1e0898036e900/Documentation/gramine-users.rst#L26)):*
> ```reStructuredText
>   generically enclavize applications. Enclaive builds and deploys confidential
>   containers for the zero-trust Web. Use cases are in the area of GDPR-compliant
>   Web analytics and AI. Spefically, Gramine Shielded Containers (GSC) ease the
> ```

typo:



_Suggestion:_
```reStructuredText
Specifically
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/494)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/gramine-users.rst, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/494#-MzuXhb44iufS2m28uTG:-MzunhdA4WnUuh_25Mmf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5acd38b90b3232bb2b11336d98d1e0898036e900/Documentation/gramine-users.rst#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

typo:
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/494)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/494)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-20.04 please (`LibOS.shim.test.ltp.test_ltp.test_ltp[fdatasync01]` timed out, unrelated)

**Pull request merged**
