### PR TITLE
Various trivial fixes

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Just cleaning up my private TODOlist :)

## How to test this PR? 

CI, no functional changes intended.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/372)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/372)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/372)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/372)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/372)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
