### PR TITLE
[LibOS] Fix wrong return of `chroot_encrypted_write()` on failure

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 

Instead, a negative error code should be returned in case of failure.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd0kmpACvekLT-8btCf:-Nd0kmpACvekLT-8btCg:b-g39rl9) (no related file):*
How did you find this problem? Is it fixing some known GitHub issue or workload/app?

Or maybe by just manual review?

___
___
*[`libos/src/fs/chroot/encrypted.c` line 454 at r1](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd0l86a4IunsVlPG_WS:-Nd0l86a4IunsVlPG_WT:b-opj2bl) ([raw file](https://github.com/gramineproject/gramine/blob/74d68865f1d5efe1f696fbbb9250a1e88685d38e/libos/src/fs/chroot/encrypted.c#L454)):*
> ```C
> 
>     unlock(&hdl->inode->lock);
>     return actual_count;
> ```

Maybe a different way? Keep the `goto out` in place, but do this:
```
    ret = 0;
out:
    unlock(&hdl->inode->lock);
    return ret < 0 ? ret : actual_count;
```

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`libos/src/fs/chroot/encrypted.c` line 454 at r1](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd0l86a4IunsVlPG_WS:-Nd1pG0fACyHkf0iaLTM:b-kr1lsp) ([raw file](https://github.com/gramineproject/gramine/blob/74d68865f1d5efe1f696fbbb9250a1e88685d38e/libos/src/fs/chroot/encrypted.c#L454)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe a different way? Keep the `goto out` in place, but do this:
```
    ret = 0;
out:
    unlock(&hdl->inode->lock);
    return ret < 0 ? ret : actual_count;
```
</blockquote></details>

I slightly prefer Dima's version, because it's more "expected" by the readers of our codebase. But this function is short, so I won't block on this.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd0kmpACvekLT-8btCf:-Nd2ppG8CpofvfyZ3JQM:b-mlcrdf) (no related file):*
> How did you find this problem?

This was found when I was looking into the potential fix for https://github.com/gramineproject/gramine/issues/1432 (so basically by manual review).

___
___
*[`libos/src/fs/chroot/encrypted.c` line 454 at r1](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd0l86a4IunsVlPG_WS:-Nd2poiFASaU4DOp2-M1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/74d68865f1d5efe1f696fbbb9250a1e88685d38e/libos/src/fs/chroot/encrypted.c#L454)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I slightly prefer Dima's version, because it's more "expected" by the readers of our codebase. But this function is short, so I won't block on this.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/fs/chroot/encrypted.c` line 454 at r2](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd7U5Jh0teG-vo_k0t8:-Nd7U5Jh0teG-vo_k0t9:b-s20zrt) ([raw file](https://github.com/gramineproject/gramine/blob/a93fabddd41f6b8d241aca0dfa29e4a8142c3a97/libos/src/fs/chroot/encrypted.c#L454)):*
> ```C
> out:
>     unlock(&hdl->inode->lock);
>     return ret < 0 ? ret : (ssize_t)actual_count;
> ```

Actually, shouldn't we error out if this cast overflows? (it's an unrelated bug, but we can fix it while we're here)



_Code quote:_
```C
(ssize_t)actual_count
```

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/chroot/encrypted.c` line 454 at r2](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd7U5Jh0teG-vo_k0t8:-Nd8JLop3kn8kxWK8iHW:b6jrf4s) ([raw file](https://github.com/gramineproject/gramine/blob/a93fabddd41f6b8d241aca0dfa29e4a8142c3a97/libos/src/fs/chroot/encrypted.c#L454)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, shouldn't we error out if this cast overflows? (it's an unrelated bug, but we can fix it while we're here)
</blockquote></details>

Yeah, but we have such problem in various places. Do we want to fix it here?

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/chroot/encrypted.c` line 454 at r2](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd7U5Jh0teG-vo_k0t8:-Nd8bjhYApAOMI0wQeO_:b-qdiu2y) ([raw file](https://github.com/gramineproject/gramine/blob/a93fabddd41f6b8d241aca0dfa29e4a8142c3a97/libos/src/fs/chroot/encrypted.c#L454)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yeah, but we have such problem in various places. Do we want to fix it here?
</blockquote></details>

Indeed, I would prefer to have a separate PR for this.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`libos/src/fs/chroot/encrypted.c` line 454 at r2](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd7U5Jh0teG-vo_k0t8:-NdCx4N55u00TyaptFSz:b-euqa2c) ([raw file](https://github.com/gramineproject/gramine/blob/a93fabddd41f6b8d241aca0dfa29e4a8142c3a97/libos/src/fs/chroot/encrypted.c#L454)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indeed, I would prefer to have a separate PR for this.
</blockquote></details>

Ok, unblocking then. @kailun-qin: Would you have time to fix this in a separate PR?

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`libos/src/fs/chroot/encrypted.c` line 454 at r2](https://reviewable.io/reviews/gramineproject/gramine/1522#-Nd7U5Jh0teG-vo_k0t8:-NdCycK9CXRcsVm9tCz0:b7au73b) ([raw file](https://github.com/gramineproject/gramine/blob/a93fabddd41f6b8d241aca0dfa29e4a8142c3a97/libos/src/fs/chroot/encrypted.c#L454)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, unblocking then. @kailun-qin: Would you have time to fix this in a separate PR?
</blockquote></details>

Sure, let me make a follow-up PR.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1522)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
