### PR TITLE
[common,Pal/Linux] Compile with Meson

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 
Compile gramine-direct with mesonified `common/`. `gramine-lib.a` is still built because the building code is common with Linux-SGX.
 
## How to test this PR? 

As usual.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)

### CODE REVIEW

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

___
*[common/src/meson.build, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklXB2t51OgVI2muIZA:-MklXB2t51OgVI2muIZB:b-i34tuy) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/common/src/meson.build#L1)):*
> ```Meson
> if sgx
> ```

Apparently this is unused, can you remove for now? 

Not blocking on this, though.
___
*[common/src/meson.build, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklVWE57iDUqQN-1kV_:-MklVWE57iDUqQN-1kVa:bags0qc) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/common/src/meson.build#L38)):*
> ```Meson
>         'string/strstr.c',
>         'string/toml_utils.c',
>         'string/utils.c',
> ```

There are also `asan.c` and `ubsan.c`, compiled depending on whether the respective sanitizers are enabled.

(Jenkins-Sanitizers should fail on this)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[common/include/meson.build, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklXIWr3wvA1unucrqz:-MklXIWs3c-QlnDtawlT:b-4n5s01) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/common/include/meson.build#L6)):*
> ```Meson
>         join_paths('arch', host_machine.cpu_family()),
>     ),
>     tomlc99_inc, # TODO this is because there's #include "toml.h" in api.h
> ```

Is this a problem? I think our `api.h` has to depend on TOML headers.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[meson.build, line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklnSu16gaUiQaf7vnP:-MklnSu16gaUiQaf7vnQ:bgptrza) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/meson.build#L130)):*
> ```Meson
> 
> tomlc99_proj = subproject('tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5')
> tomlc99_dep = tomlc99_proj.get_variable('tomlc99_files_dep')
> ```

Why so weird? Why do you need two names for the same thing (`tomlc99_dep` and `tomlc99_files_dep`)?

E.g., for uthash you simply have `uthash_dep`. I would prefer to have the same single name for TOML (`tomlc99_dep`), unless there is a specific reason to have two names.
___
*[common/include/meson.build, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklXIWr3wvA1unucrqz:-MklkjU2B4JxjOSFVIo5:b-dnzq4j) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/common/include/meson.build#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this a problem? I think our `api.h` has to depend on TOML headers.
</blockquote></details>

Michal is right. Why is there a TODO? You think that ideally we should delete this dependency?
___
*[subprojects/packagefiles/tomlc99/meson.build, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-Mkllzef0D1ejWslquck:-Mkllzef0D1ejWslqucl:b-46j8of) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/subprojects/packagefiles/tomlc99/meson.build#L24)):*
> ```Meson
> 
> tomlc99_inc = include_directories('.')
> tomlc99_incpath = meson.current_build_dir()
> ```

What's the point of this variable? It doesn't seem to be used anywhere. Not blocking though, may be useful in the future.
___
*[subprojects/packagefiles/uthash/src/meson.build, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-Mklm_QTA-tuU05I-hVz:-Mklm_QTA-tuU05I-hW-:bsd7sgd) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/subprojects/packagefiles/uthash/src/meson.build#L1)):*
> ```Meson
> uthash_h = custom_target('uthash.h',
> ```

Why did you introduce an additional `src/` subdir for `uthash`, though you don't have it for TOML library? In fact, you don't have anything similar for all other subprojects...

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: 11 of 14 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[meson.build, line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklnSu16gaUiQaf7vnP:-Mkm0ICnD7LfeU9We-nl:bfx5rtk) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/meson.build#L130)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why so weird? Why do you need two names for the same thing (`tomlc99_dep` and `tomlc99_files_dep`)?

E.g., for uthash you simply have `uthash_dep`. I would prefer to have the same single name for TOML (`tomlc99_dep`), unless there is a specific reason to have two names.
</blockquote></details>

Done. This was an artifact from previous version, which had two dependencies imported from subproject and was subsequently simplified.
___
*[common/include/meson.build, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklXIWr3wvA1unucrqz:-MklyQtsA9P7OE40G9VO:b-31c0mi) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/common/include/meson.build#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Michal is right. Why is there a TODO? You think that ideally we should delete this dependency?
</blockquote></details>

Well, *something* needs to be decoupled. The problem is, `common_inc` (which is just includes) != `common_dep` (which is includes + `.o` files, which previously were in `gra{phene,mine}-lib.a`), and `common_inc` is used also in places which don't pull common `.o` files. Example: `pf_tamper` which pulls `COPY_ARRAY()` from `api.h`, but has no need for neither toml nor any `.o` file from `common/src/`.

So optimally I'd like to get rid on `tomlc99_inc` and `tomlc99_incpath` (see other thread) meson variables altogether and having only `tomlc99_dep` in `dependencies: []` to `common_dep` in `common/src/meson.build`, but this would require that we reorganise includes so that we don't accidentally include toml if we don't also pull the whole common lib. I don't have a specific proposal for now, hence TODO.
___
*[common/src/meson.build, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklXB2t51OgVI2muIZA:-Mkq3rM2Dxkb7zIydmQa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/common/src/meson.build#L1)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Apparently this is unused, can you remove for now? 

Not blocking on this, though.
</blockquote></details>

Done.
___
*[common/src/meson.build, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklVWE57iDUqQN-1kV_:-Mkq3qT63ZKDDDSPrzOP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/common/src/meson.build#L38)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

There are also `asan.c` and `ubsan.c`, compiled depending on whether the respective sanitizers are enabled.

(Jenkins-Sanitizers should fail on this)
</blockquote></details>

Done.
___
*[subprojects/packagefiles/tomlc99/meson.build, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-Mkllzef0D1ejWslquck:-Mkm-JWbDSwMEWVc3bwO:bkoemcg) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/subprojects/packagefiles/tomlc99/meson.build#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of this variable? It doesn't seem to be used anywhere. Not blocking though, may be useful in the future.
</blockquote></details>

It will be, when generating offsets, because that thing needs manually provided `'-I@0@'.format(...)`, because it can't rely on `include_directories()` magic in meson. This is another consequence of `#include <toml.h>` in `api.h` (see other thread).
___
*[subprojects/packagefiles/uthash/src/meson.build, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-Mklm_QTA-tuU05I-hVz:-Mkm-dZg0LBqvcWVY5ig:b35uc4n) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/subprojects/packagefiles/uthash/src/meson.build#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you introduce an additional `src/` subdir for `uthash`, though you don't have it for TOML library? In fact, you don't have anything similar for all other subprojects...
</blockquote></details>

This mirrors the directory structure of the original project. In tomlc99, `toml.c` and `toml.h` are in the root directory of the repo, and in mbedtls `Makefile` is also in the root directory. I don't remember the details, but in each case it was easier to keep patch/make executed in the current directory.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 9 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @pwmarcz, and @woju)

___
*[subprojects/packagefiles/tomlc99/toml.c.patch, line 149 at r2](https://reviewable.io/reviews/gramineproject/gramine/102#-MkqBoe670WAR3S9o9LA:-MkqBoe670WAR3S9o9LB:b-lqpa7j) ([raw file](https://github.com/gramineproject/gramine/blob/04f5b08e4677445736caf97fb174f74d00e7c4d7/subprojects/packagefiles/tomlc99/toml.c.patch#L149)):*
> ```Diff
> -	*ret = strtod(buf, &endp);
> -	return (errno || *endp) ? -1 : 0;
> +    /* FIXME: strtod() is not supported by Graphene */
> ```

`Graphene` -> `Gramine`

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: 13 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[subprojects/packagefiles/tomlc99/toml.c.patch, line 149 at r2](https://reviewable.io/reviews/gramineproject/gramine/102#-MkqBoe670WAR3S9o9LA:-MkqD11p6m_cCr-xmc7a:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/04f5b08e4677445736caf97fb174f74d00e7c4d7/subprojects/packagefiles/tomlc99/toml.c.patch#L149)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Graphene` -> `Gramine`
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[common/include/meson.build, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/102#-MklXIWr3wvA1unucrqz:-MkqTyL98TlS4oLRTi6n:b-eaw9j2) ([raw file](https://github.com/gramineproject/gramine/blob/3c16772c50745d77f30f8e8dfa08944732a6fa6c/common/include/meson.build#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Well, *something* needs to be decoupled. The problem is, `common_inc` (which is just includes) != `common_dep` (which is includes + `.o` files, which previously were in `gra{phene,mine}-lib.a`), and `common_inc` is used also in places which don't pull common `.o` files. Example: `pf_tamper` which pulls `COPY_ARRAY()` from `api.h`, but has no need for neither toml nor any `.o` file from `common/src/`.

So optimally I'd like to get rid on `tomlc99_inc` and `tomlc99_incpath` (see other thread) meson variables altogether and having only `tomlc99_dep` in `dependencies: []` to `common_dep` in `common/src/meson.build`, but this would require that we reorganise includes so that we don't accidentally include toml if we don't also pull the whole common lib. I don't have a specific proposal for now, hence TODO.
</blockquote></details>

OK. Understood. Yes, that's the consequence of our `api.h` being a kitchen sink for everything. We'll need to sort out our header includes sooner than later, we constantly bump into this.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/102)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
