### PR TITLE
[tools] Move Linux-SGX tools under `tools/sgx/`

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

As the name suggests.

See https://github.com/gramineproject/gramine/discussions/667 and https://github.com/gramineproject/gramine/discussions/687 for details.

## How to test this PR? 

CI is enough.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/717)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/717)* status: 0 of 40 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`libos/test/fs/README.md` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/717#-N5tbOYd82wos7gTODWG:-N5tbOYd82wos7gTODWH:b-8y9hyi) ([raw file](https://github.com/gramineproject/gramine/blob/f0419a8652820bca664b575a9b6b93ccf2d878c0/libos/test/fs/README.md#L27)):*
> ```Markdown
> cd $gramine/pal/src/host/linux-sgx/tools
> make install PREFIX=$gramine/libos/test/fs
> ```
> ```

FYI: This was just stale. We build Protected Files tools together with the rest of Gramine since we switched to Meson.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 36 of 41 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/717)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/717#-N6IZBFn5Yh4iXkf5f6f:-N6IZBFo4SFOLMh5GacC:bsyc1w1) (no related file):*
Some missed uses:
https://github.com/gramineproject/gramine/blame/c16cbd91f85f3f54cf2d929d0a9a30d0f3e9e5e2/Documentation/tutorials/pytorch/index.rst#L378
https://github.com/gramineproject/gramine/blame/c16cbd91f85f3f54cf2d929d0a9a30d0f3e9e5e2/Documentation/tutorials/pytorch/index.rst#L496

___

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/717)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — DISMISSED** [review]
> Reviewed 36 of 41 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/717)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/717)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/717)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
