### PR TITLE
[CI] Update Intel's SGX PGP RSA key signing Intel repos

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The previous key expired on 2023-05-24 (which is today).

The new key was copied from https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`.ci/ubuntu20.04.dockerfile` line 76 at r1](https://reviewable.io/reviews/gramineproject/gramine/1369#-NWBTQge1vOnBt6tvU_w:-NWBTQge1vOnBt6tvU_x:b6jn5yr) ([raw file](https://github.com/gramineproject/gramine/blob/4fe2801b3ec59e60b6a2d1c0d7c4db5c7f452b1d/.ci/ubuntu20.04.dockerfile#L76)):*
> ```Dockerfile
> # Intel's RSA-2048 key signing the intel-sgx/sgx_repo repository. Expires 2027-03-20.
> # https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
> COPY .ci/intel-sgx-deb.key /etc/apt/trusted.gpg.d/intel-sgx-deb.asc
> ```

@woju I noticed that in this Dockerfile, we downloaded the key instead of copying it from our repo. So I modified similarly to how it is done for Debian11 Dockerfile. Does this look legit?

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`.ci/ubuntu20.04.dockerfile` line 76 at r1](https://reviewable.io/reviews/gramineproject/gramine/1369#-NWBTQge1vOnBt6tvU_w:-NWCx_lw1iPvtDJBd2cD:bbs93x3) ([raw file](https://github.com/gramineproject/gramine/blob/4fe2801b3ec59e60b6a2d1c0d7c4db5c7f452b1d/.ci/ubuntu20.04.dockerfile#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju I noticed that in this Dockerfile, we downloaded the key instead of copying it from our repo. So I modified similarly to how it is done for Debian11 Dockerfile. Does this look legit?
</blockquote></details>

Looks good to me, but this is missing from the commit message.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by woju — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`.ci/ubuntu20.04.dockerfile` line 76 at r1](https://reviewable.io/reviews/gramineproject/gramine/1369#-NWBTQge1vOnBt6tvU_w:-NWDCp9nDnSU6Vdt9Xzz:bb6ywmx) ([raw file](https://github.com/gramineproject/gramine/blob/4fe2801b3ec59e60b6a2d1c0d7c4db5c7f452b1d/.ci/ubuntu20.04.dockerfile#L76)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Looks good to me, but this is missing from the commit message.
</blockquote></details>

LGTM

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`.ci/ubuntu20.04.dockerfile` line 76 at r1](https://reviewable.io/reviews/gramineproject/gramine/1369#-NWBTQge1vOnBt6tvU_w:-NWDEPua1fRpaJNbRub-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4fe2801b3ec59e60b6a2d1c0d7c4db5c7f452b1d/.ci/ubuntu20.04.dockerfile#L76)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

Done.

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1369#-NWDH58Z7g_lBJlPZ9ta):*
But it's 20.04 which is updated?



_Code quote:_
```
22.04
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1369#-NWDH58Z7g_lBJlPZ9ta):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But it's 20.04 which is updated?
</blockquote></details>

Done , oops

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: all files reviewed, 1 unresolved discussion

**Review by kailun-qin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1369)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
