### PR TITLE
[CI-Examples] Add Busybox check to Jenkins CI

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

See discussion in #602.

To prevent issues like #602, this PR adds a very simple check that Busybox builds and runs.

## How to test this PR? 

Busybox added to CI.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/603)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/603)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-20.04 please (Busybox website failed)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/603)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`CI-Examples/busybox/Makefile` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/603#-N2qmu5KD7G0xa8w0DcU:-N2qmu5KD7G0xa8w0DcV:b-m9psfx) ([raw file](https://github.com/gramineproject/gramine/blob/b2a8a2c32d45d024b2631fc430efdd1b80951195/CI-Examples/busybox/Makefile#L4)):*
> ```Makefile
> 
> SRCDIR = src
> BUSYBOX_URL ?= https://busybox.net/downloads/busybox-1.32.0.tar.bz2
> ```

Blocking myself: we need to add this Busybox archive to https://packages.gramineproject.io/distfiles/ (I pinged @woju for this)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/603)* status: 3 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`CI-Examples/busybox/Makefile` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/603#-N2qmu5KD7G0xa8w0DcU:-N2qx3GL0d6VBg1pYMUE:br6d5zx) ([raw file](https://github.com/gramineproject/gramine/blob/b2a8a2c32d45d024b2631fc430efdd1b80951195/CI-Examples/busybox/Makefile#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself: we need to add this Busybox archive to https://packages.gramineproject.io/distfiles/ (I pinged @woju for this)
</blockquote></details>

Done. Thanks to @woju !

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/603)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/603)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/603)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/603)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
