### PR TITLE
[Docs] Add OpenSSF Best Practices Badge

### PR DESCRIPTION
**Pull request by kailun-qin**
## Description of the changes 
We have completed the self-certification for the basic ("passing") level in the [OpenSSF Best Practices Badge Program](https://www.bestpractices.dev/en). See https://www.bestpractices.dev/en/projects/8380 for details.

According to the previous community meeting discussions https://github.com/gramineproject/gramine/discussions/1740, we planned to achieve the silver level (and we are currently 96% done). But there still seems to be several blockers, in particular:
* The project MUST be able to repeat the process of generating information from source files and get exactly the same bit-for-bit result. Related to https://github.com/gramineproject/gramine/issues/153.
* The project MUST cryptographically sign releases of the project results intended for widespread use, and there MUST be a documented process explaining to users how they can obtain the public signing keys and verify the signature(s). It is SUGGESTED that in the version control system, each important version tag (a tag that is part of a major release, minor release, or fixes publicly noted vulnerabilities) be cryptographically signed and verifiable. Related to https://github.com/gramineproject/gramine/issues/235.
* The project SHOULD support multiple cryptographic algorithms, so users can quickly switch if one is broken.

See https://www.bestpractices.dev/en/projects/8380?criteria_level=1 for details.

~~Since most of the above requirements are in our plan, I think it's fine to add this badge in our README now while we continue working on them.~~

Note that most of the not-yet-met requirements for the silver badge above are in our plan. Since we're already meeting the criteria for the "passing" badge, this PR adds it and the badge status should automatically be updated (from "passing") to silver once we meet the required silver requirements.

## How to test this PR? 
CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1773)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1773)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1773#-Nr4Yl4wExUPP-_ogkpq:-Nr4Yl4wExUPP-_ogkpr:b-9xqg2x) (no related file):*
I reviewed the https://www.bestpractices.dev/en/projects/8380#all answers. Reported to Kailun privately. Blocking here until Kailun fixes them.

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1773)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1773#-Nr4Yl4wExUPP-_ogkpq:-Nr5-ZJdATNVJ7j9x2ky:bo8mhql) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I reviewed the https://www.bestpractices.dev/en/projects/8380#all answers. Reported to Kailun privately. Blocking here until Kailun fixes them.
</blockquote></details>

All my issues were resolved.

___

**Review by mkow — APPROVED** [review]
> Since most of the above requirements are in our plan, I think it's fine to add this badge in our README now while we continue working on them.

Just to be clear, because it sounds like we're adding a badge despite not passing its criteria: if I understand correctly, Kailun mentions here the requirements for the silver badge which we didn't meet yet, but we're already meeting the criteria for the "passing" badge which this PR adds.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1773#-:-Nr5uWt-9U271WldXf3q:be1pwcs)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — COMMENTED** [review]
> the requirements for the silver badge which we didn't meet yet, but we're already meeting the criteria for the "passing" badge which this PR adds

Yes, actually the badge status would be automatically updated (from passing) to silver once we meet it. (I may update the wording a bit)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1773#-:-Nr6-LzN-IQ_0FES9V98:b-nkmeen)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1773)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
