### PR TITLE
Refactor sysfs to improve sanitization - Part 3

### PR DESCRIPTION
**Pull request by vijaydhanraj**
## Description of the changes 
This PR cleans up a few of the TODOs as part of refactoring sysfs.

## How to test this PR? 
Please run `sysfs_common` and `proc_common` regression tests.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/360)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/360)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @vijaydhanraj)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/360#-MuHhKjX3IePETsYTf2e):*
`and unify` (you forgot `and`)
___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/360#-MuHhOnhESHYcCH2UKND):*
`PAL` -> `PALs`

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/360)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/360#-MuHoq0iBPrP7S9v_9Xe):*
Also, fixed `Linux_SGX->Linux-SGX`
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/360#-MuHhKjX3IePETsYTf2e):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`and unify` (you forgot `and`)
</blockquote></details>

yes, done.
___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/360#-MuHhOnhESHYcCH2UKND):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`PAL` -> `PALs`
</blockquote></details>

Done.
___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/360#-MuHowd-BI_FN2zZ5Sz0):*
Fixed typo, `direcly -> directly`

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/360)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this pleae

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/360)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/360)* status: all files reviewed, 2 unresolved discussions

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/360)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/360)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/360)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
