### PR TITLE
[Pal] Remove superfluous PAL_MEM_INFO struct

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Split out from #314 (removing superfluous `PAL_MEM_INFO` struct).

## How to test this PR? 

CI, no functional changes intended.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/318)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/318)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/318)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/include/pal/pal.h, line 128 at r1](https://reviewable.io/reviews/gramineproject/gramine/318#-MsgZgQJ2Dns_UNeKqGu:-MsgZgQKBG9OHFWdugzr:bel48qy) ([raw file](https://github.com/gramineproject/gramine/blob/49b4929719496c6bb8cabcb28e4d3ef18cc896f4/Pal/include/pal/pal.h#L128)):*
> ```objc
>     PAL_NUM alloc_align;
> 
>     size_t mem_total;
> ```

It would be nice to have a comment describing the variable, but not blocking.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/318)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 128 at r1](https://reviewable.io/reviews/gramineproject/gramine/318#-MsgZgQJ2Dns_UNeKqGu:-MsgazMm5ZAQ56Fh0BRy:b4czihp) ([raw file](https://github.com/gramineproject/gramine/blob/49b4929719496c6bb8cabcb28e4d3ef18cc896f4/Pal/include/pal/pal.h#L128)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

It would be nice to have a comment describing the variable, but not blocking.
</blockquote></details>

Not sure what's this value exactly. And it may depend on PAL... It's used only for statistics in procfs, so it's not very important. But if you have an idea for a good comment then please suggest ;)

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/318)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/include/pal/pal.h, line 128 at r1](https://reviewable.io/reviews/gramineproject/gramine/318#-MsgZgQJ2Dns_UNeKqGu:-MsgxRj7BlXOVy94ot0t:b-nwkvb2) ([raw file](https://github.com/gramineproject/gramine/blob/49b4929719496c6bb8cabcb28e4d3ef18cc896f4/Pal/include/pal/pal.h#L128)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not sure what's this value exactly. And it may depend on PAL... It's used only for statistics in procfs, so it's not very important. But if you have an idea for a good comment then please suggest ;)
</blockquote></details>

Yes, since it can change based on the PAL, felt that a clear comment would help.

What do you think of this?
```
/*Total available memory. For example, in case of SGX, this is the remaining enclave memory after accounting for PAL, LibOS code/data as well as application's code, stack, heap, libraries and in non-sgx case, this is the total usable RAM */
```

**Review by dimakuv — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/318)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/318)* status: all files reviewed, 1 unresolved discussion (waiting on @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 128 at r1](https://reviewable.io/reviews/gramineproject/gramine/318#-MsgZgQJ2Dns_UNeKqGu:-Msj5_s080bx19YfKJvH:b-8a4r5t) ([raw file](https://github.com/gramineproject/gramine/blob/49b4929719496c6bb8cabcb28e4d3ef18cc896f4/Pal/include/pal/pal.h#L128)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, since it can change based on the PAL, felt that a clear comment would help.

What do you think of this?
```
/*Total available memory. For example, in case of SGX, this is the remaining enclave memory after accounting for PAL, LibOS code/data as well as application's code, stack, heap, libraries and in non-sgx case, this is the total usable RAM */
```
</blockquote></details>

But now you say both: "total available memory" and "remaining enclave memory", which is contradictory. I think this variable just have different meaning on both PALs, which sounds like a bug...

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/318)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow and @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 128 at r1](https://reviewable.io/reviews/gramineproject/gramine/318#-MsgZgQJ2Dns_UNeKqGu:-MsjH2O-34_JVdJPhNbG:bsr82tn) ([raw file](https://github.com/gramineproject/gramine/blob/49b4929719496c6bb8cabcb28e4d3ef18cc896f4/Pal/include/pal/pal.h#L128)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But now you say both: "total available memory" and "remaining enclave memory", which is contradictory. I think this variable just have different meaning on both PALs, which sounds like a bug...
</blockquote></details>

Maybe just keep it without a comment now? We can get back to this when we figure out if we indeed have a discrepancy in our PAL semantics.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/318)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
