### PR TITLE
[Docs] Update sphinx to 3.4

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

See commit message.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpQm86YA1uB2fhy5aWU:-NpQm86YA1uB2fhy5aWV:brf3x9u) (no related file):*
Almalinux pipelines failed.

___
___
*[`Documentation/requirements.txt` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpQltED-9f4hrkRrikH:-NpQltED-9f4hrkRrikI:b-n3hqfe) ([raw file](https://github.com/gramineproject/gramine/blob/739e24d6138758c325bf6d391acf98324f8ef262/Documentation/requirements.txt#L18)):*
> ```help
> # those require sphinx >= 5.0
> # https://github.com/sphinx-doc/sphinxcontrib-applehelp/commit/604e2cb89264b6e2669ac8c15a70d93c1e06d9d3
> sphinxcontrib-applehelp<1.0.5
> ```

I don't understand. These plugins require Sphinx 5.0, but we install 3.4... How does it work?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpQm86YA1uB2fhy5aWU:-NpZjWW8-U5znyihX3rl:b-29j49b) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Almalinux pipelines failed.
</blockquote></details>

Hopefully fixed.

___
___
*[`Documentation/requirements.txt` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpQltED-9f4hrkRrikH:-NpUGFrlCkYq6i5s2GMa:b-e97ls2) ([raw file](https://github.com/gramineproject/gramine/blob/739e24d6138758c325bf6d391acf98324f8ef262/Documentation/requirements.txt#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand. These plugins require Sphinx 5.0, but we install 3.4... How does it work?
</blockquote></details>

`>=1.0.5` et al. requires `Sphinx>=5.0`. Therefore we pin last versions that do not need 5.0.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "WIP" found in commit messages' one-liners

___
*[`Documentation/requirements.txt` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpQltED-9f4hrkRrikH:-NpdiTni5p59LLQZfPR6:bl5r42h) ([raw file](https://github.com/gramineproject/gramine/blob/739e24d6138758c325bf6d391acf98324f8ef262/Documentation/requirements.txt#L18)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`>=1.0.5` et al. requires `Sphinx>=5.0`. Therefore we pin last versions that do not need 5.0.
</blockquote></details>

Ah, ok, the comment is a bit dense then, but at least now I understand the logic

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "WIP" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpnL7KVDA-hh-atGAdQ:-NpnL7KVDA-hh-atGAdR:b-tssjny) (no related file):*
What about: https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/Documentation/devel/howto-doc.rst?plain=1#L45?

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpnJ93S48DrMmBNJpPy):*
I think we could move `WIP` now?



_Code quote:_
```
WIP
```

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: all files reviewed, 3 unresolved discussions, "WIP" found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/requirements.txt` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpqqYDDDycwyoBLJWQj:-NpqqYDDDycwyoBLJWQk:b-ru1h3x) ([raw file](https://github.com/gramineproject/gramine/blob/56d4a5d5a843ecc86e948397f44c6dc0da8cfb56/Documentation/requirements.txt#L9)):*
> ```help
> # TODO: This shouldn't be necessary once we upgrade to newer Sphinx (Sphinx 4.2.0 is not yet
> # compatible with new docutils, but pins the docutils version by itself).
> #docutils<0.18
> ```

Why not just delete this whole TODO? As I understand it, it's completely fixed after the update?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpnL7KVDA-hh-atGAdQ:-NptdIGY0KNSdFWX5x8K:b-9wyi3u) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about: https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/Documentation/devel/howto-doc.rst?plain=1#L45?
</blockquote></details>

Fixed, thank for noticing. I've also removed whole sentence about python 2.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpnJ93S48DrMmBNJpPy):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think we could move `WIP` now?
</blockquote></details>

Done.
___
*[`Documentation/requirements.txt` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1739#-NpqqYDDDycwyoBLJWQj:-Nptc9490iwfD4h_y3na:b-t36hx1) ([raw file](https://github.com/gramineproject/gramine/blob/56d4a5d5a843ecc86e948397f44c6dc0da8cfb56/Documentation/requirements.txt#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just delete this whole TODO? As I understand it, it's completely fixed after the update?
</blockquote></details>

This one is. Jinja below isn't however, I've added a TODO there and reworded to make it clear what exactly we need to do.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: all files reviewed, 3 unresolved discussions (waiting on @kailun-qin and @mkow)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1739)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
