### PR TITLE
[CI-Examples,tests] Remove/shorten `sleep` invocations

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Replace sleeps with more appropriate wait-for tools, or at least shorten the sleep interval.

## How to test this PR? 

CI is enough.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1565)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1565)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/1565#-Ner7LSg1rlPRKn_2grT:-Ner7LSg1rlPRKn_2grU:b-t4mx4f) ([raw file](https://github.com/gramineproject/gramine/blob/4eec2144c50c8392d648ae328c5f0d43b5fd6e00/CI-Examples/common_tools/benchmark-http.sh#L78)):*
> ```Shell
>         wrk -c "$CONNECTIONS" -d "$DURATION" -t "$CONCURRENCY" -R "$REQUESTS" "$DOWNLOAD_HOST/$DOWNLOAD_FILE" > OUTPUT || exit $?
> 
>         sleep 1
> ```

I actually don't know what this sleep is for exactly. It just sits there in-between app invocations. Probably to let the previous invocation to "cool down"?

I think we could also remove this sleep completely, but I decided to keep it, just make smaller.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1565)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/1565#-Ner7LSg1rlPRKn_2grT:-Neru4L6-XgLnPx0N_Jm:b-rxg0wp) ([raw file](https://github.com/gramineproject/gramine/blob/4eec2144c50c8392d648ae328c5f0d43b5fd6e00/CI-Examples/common_tools/benchmark-http.sh#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I actually don't know what this sleep is for exactly. It just sits there in-between app invocations. Probably to let the previous invocation to "cool down"?

I think we could also remove this sleep completely, but I decided to keep it, just make smaller.
</blockquote></details>

I'd remove it and see what happens :d
___
*[`libos/test/regression/eventfd.c` line 93 at r1](https://reviewable.io/reviews/gramineproject/gramine/1565#-NeruxL4-q1rspp1SV3j:-NeruxL4-q1rspp1SV3k:b-8xgb30) ([raw file](https://github.com/gramineproject/gramine/blob/4eec2144c50c8392d648ae328c5f0d43b5fd6e00/libos/test/regression/eventfd.c#L93)):*
> ```C
> 
>     while (1) {
>         poll_ret = poll(pollfds, MAX_EFDS, 100);
> ```

Isn't that too small? I'd give it at least 1s to prevent random failures.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1565)* status: 2 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1565#-NerxE_w658enr97YbL0:-NerxE_w658enr97YbL1:buruh69) (no related file):*
Let's run it 5 times, blocking until then.

___
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/1565#-Ner7LSg1rlPRKn_2grT:-NerwaTWEj-43_78oX0X:b-mteifg) ([raw file](https://github.com/gramineproject/gramine/blob/4eec2144c50c8392d648ae328c5f0d43b5fd6e00/CI-Examples/common_tools/benchmark-http.sh#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd remove it and see what happens :d
</blockquote></details>

I don't think anything will happen, but maybe the tput/latency numbers of different runs will change a bit. Whatever, removed.
___
*[`libos/test/regression/eventfd.c` line 93 at r1](https://reviewable.io/reviews/gramineproject/gramine/1565#-NeruxL4-q1rspp1SV3j:-NerwvSbE7ukGO3AOZLO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4eec2144c50c8392d648ae328c5f0d43b5fd6e00/libos/test/regression/eventfd.c#L93)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't that too small? I'd give it at least 1s to prevent random failures.
</blockquote></details>

Done.

**Comment by dimakuv** [comment]
Jenkins, retest this please (run 1/5 successful)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1565)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1565#-NerxE_w658enr97YbL0:-NesRN9K71HQmeW6jMIm:b5wsszy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's run it 5 times, blocking until then.
</blockquote></details>

Sure, sounds like a good idea.

___

**Comment by mkow** [comment]
Jenkins, retest this please (run 2/5 successful)

**Comment by dimakuv** [comment]
Jenkins, retest this please (run 3/5 successful)

**Comment by dimakuv** [comment]
Jenkins, retest this please (run 4/5 successful)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1565)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1565)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1565)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Pull request merged**
