### PR TITLE
[Docs] Add Super Protocol to "Users of Gramine" section

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Yes.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/gramine-users.rst` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1030#-NGOGm1l6BtK20mLmp3s:-NGOGm1l6BtK20mLmp3t:bpcsnku) ([raw file](https://github.com/gramineproject/gramine/blob/94f1f0f2ad3b3483d7de4706bfcab57a37382994/Documentation/gramine-users.rst#L34)):*
> ```reStructuredText
> - `Super Protocol <https://www.superprotocol.com/>`__ combines the benefits of
>   both Trusted Execution Environment (TEE) technology and blockchain to offer a
>   global, decentralized, unstoppable "super cloud". It enables easy deployment
> ```

That's too much marketing, it's a page in our docs and should briefly describe what they do with Gramine, not be an ad.



_Code quote:_
```reStructuredText
unstoppable "super cloud"
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/gramine-users.rst` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1030#-NGOGm1l6BtK20mLmp3s:-NGVkKRS6lEiWwoF06CD:brfiugz) ([raw file](https://github.com/gramineproject/gramine/blob/94f1f0f2ad3b3483d7de4706bfcab57a37382994/Documentation/gramine-users.rst#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's too much marketing, it's a page in our docs and should briefly describe what they do with Gramine, not be an ad.
</blockquote></details>

Done. This particular part was modified.

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/gramine-users.rst` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1030#-NGOGm1l6BtK20mLmp3s:-NGWWWIh2t46aEXI_cqd:b-o64z1n) ([raw file](https://github.com/gramineproject/gramine/blob/94f1f0f2ad3b3483d7de4706bfcab57a37382994/Documentation/gramine-users.rst#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. This particular part was modified.
</blockquote></details>

I re-read through this and I still don't know what this "Super Protocol" thingy is. Especially second paragraph is 100% bollocks, 0% content. This seriously needs to be rewritten for technical people, who actually want to do something with the piece, and not just regurgitate buzzwords to another powerpoint.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Documentation/gramine-users.rst` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1030#-NGOGm1l6BtK20mLmp3s:-NGWYxSH1awCQ80K_o0K:blp3f85) ([raw file](https://github.com/gramineproject/gramine/blob/94f1f0f2ad3b3483d7de4706bfcab57a37382994/Documentation/gramine-users.rst#L34)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I re-read through this and I still don't know what this "Super Protocol" thingy is. Especially second paragraph is 100% bollocks, 0% content. This seriously needs to be rewritten for technical people, who actually want to do something with the piece, and not just regurgitate buzzwords to another powerpoint.
</blockquote></details>

I agreed to remove the second paragraph (with the Super Protocol folks). I think the text is in decent shape now. Please check again -- if any specific questions/suggestions, please tell me.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/gramine-users.rst` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1030#-NGOGm1l6BtK20mLmp3s:-NGYwDBs9qIUlRh24HEm:b-xarp5q) ([raw file](https://github.com/gramineproject/gramine/blob/94f1f0f2ad3b3483d7de4706bfcab57a37382994/Documentation/gramine-users.rst#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agreed to remove the second paragraph (with the Super Protocol folks). I think the text is in decent shape now. Please check again -- if any specific questions/suggestions, please tell me.
</blockquote></details>

Won't block it, but looking at what companies post here I'm starting to regret we have this section in the first place. Looks like an ad board.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/gramine-users.rst` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1030#-NGOGm1l6BtK20mLmp3s:-NGuFWJPCjnAwwqxmZ4U:b-87iv90) ([raw file](https://github.com/gramineproject/gramine/blob/94f1f0f2ad3b3483d7de4706bfcab57a37382994/Documentation/gramine-users.rst#L34)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Maybe we should just remove all the descriptions and for each project list just the name and URL?
</blockquote></details>

This feels like an orthogonal issue which needs to be discussed.

I agree that this may not belong to the ReadTheDocs page, but more to a more "marketing" page on a Gramine website. But we currently have only this place here, and I don't see problems with having little descriptions of what companies do with Gramine (even when it sounds too non-technical).

If there is any *specific* feedback you have on this text, I can bring it to the SuperProtocol folks and they will amend the text.

**Review by kailun-qin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`Documentation/gramine-users.rst` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/1030#-NPM7q7y43AE6-HTAVHo:-NPM7q7y43AE6-HTAVHp:b-v8o4at) ([raw file](https://github.com/gramineproject/gramine/blob/e58366108e32866ab80c8e799d1e30bb6bd2d506/Documentation/gramine-users.rst#L32)):*
> ```reStructuredText
>   several solutions.
> 
> - `Super Protocol <https://www.superprotocol.com/>`__ combines the benefits of
> ```

This makes me think of `phala-blockchain`: https://github.com/Phala-Network/phala-blockchain/blob/55479c380fe499e5e2cb1aed698616a7a9196d98/gramine.Dockerfile.



_Code quote:_
```reStructuredText
- `Super Protocol <https://www.superprotocol.com/>`__ combines the benefits of
  both Trusted Execution Environment (TEE) technology and blockchain to offer a
```
___
*[`Documentation/gramine-users.rst` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/1030#-NPM7V391ZSSOovYPv3V:-NPM7V391ZSSOovYPv3W:b5xokix) ([raw file](https://github.com/gramineproject/gramine/blob/e58366108e32866ab80c8e799d1e30bb6bd2d506/Documentation/gramine-users.rst#L37)):*
> ```reStructuredText
>   easy deployment of a wide range of workloads - a rich ecosystem of
>   interoperable solutions and services, including databases, web services,
>   ready-to-use applications, confidential data sources, and much more. Super
> ```

It sounds a bit weird to have this `ready-to-use applications` amongst the other different types of workloads.



_Code quote:_
```reStructuredText
ready-to-use applications
```

**Review by monavij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`Documentation/gramine-users.rst` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/1030#-NPM7V391ZSSOovYPv3V:-NPQtTUY5hzCp_KKZ_QV:bhatmm8) ([raw file](https://github.com/gramineproject/gramine/blob/e58366108e32866ab80c8e799d1e30bb6bd2d506/Documentation/gramine-users.rst#L37)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It sounds a bit weird to have this `ready-to-use applications` amongst the other different types of workloads.
</blockquote></details>

We can drop 
"ready-to-use", but really we should close this. We got this text from them and this is how they describe their work. Let's finalize this soon.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Documentation/gramine-users.rst` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/1030#-NPM7V391ZSSOovYPv3V:-NPRa9X54tlkLuDEW_Ou:ba7zm6x) ([raw file](https://github.com/gramineproject/gramine/blob/e58366108e32866ab80c8e799d1e30bb6bd2d506/Documentation/gramine-users.rst#L37)):*
<details><summary><i>Previously, monavij (Mona Vij) wrote…</i></summary><blockquote>

We can drop 
"ready-to-use", but really we should close this. We got this text from them and this is how they describe their work. Let's finalize this soon. 
</blockquote></details>

Done, dropped.

I agree with @monavij, I would just finish this PR, merge it, and then we'll discuss about moving this whole page to the website and away from ReadTheDocs technical documentation.

@woju @mkow What do you think?

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/gramine-users.rst` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/1030#-NPM7V391ZSSOovYPv3V:-NPSgN5r7FIZBcHZdcsp:b-lc31ho) ([raw file](https://github.com/gramineproject/gramine/blob/e58366108e32866ab80c8e799d1e30bb6bd2d506/Documentation/gramine-users.rst#L37)):*
> We got this text from them and this is how they describe their work

I don't agree with this argument, the problem we have with this description is that it looks more like an ad from marketing department than a technical description of what they do.

I won't be blocking, but that's probably the last time I agree to add something like that here.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`Documentation/gramine-users.rst` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1030#-NGOGm1l6BtK20mLmp3s:-NPawkzG5KDuNrbcj6AZ:b4pw5zz) ([raw file](https://github.com/gramineproject/gramine/blob/94f1f0f2ad3b3483d7de4706bfcab57a37382994/Documentation/gramine-users.rst#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This feels like an orthogonal issue which needs to be discussed.

I agree that this may not belong to the ReadTheDocs page, but more to a more "marketing" page on a Gramine website. But we currently have only this place here, and I don't see problems with having little descriptions of what companies do with Gramine (even when it sounds too non-technical).

If there is any *specific* feedback you have on this text, I can bring it to the SuperProtocol folks and they will amend the text.
</blockquote></details>

Merged with the other thread, resolving here.
___
*[`Documentation/gramine-users.rst` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/1030#-NPM7V391ZSSOovYPv3V:-NPaskCs0ZPcL0Q6lC6I:b6sj4ac) ([raw file](https://github.com/gramineproject/gramine/blob/e58366108e32866ab80c8e799d1e30bb6bd2d506/Documentation/gramine-users.rst#L37)):*
> this is how they describe their work

@mkow is right, because while they're free to describe their work as they wish, including deferring to marketroids, in this repo it's we who describe things.

@dimakuv If you'd like specific feedback what is still wrong with this piece, I'll start with the list of weasel words that were used here to provide no content whatsoever:
- "benefits"
- "rich ecosystem"
- "solutions and services"
- "and much more"

It would be better if they just described their "solutions and services", and what they exactly do. It'd be even better if they say what market they serve, like Gematik which talks about electronic health records. Otherwise, if they can't articulate what they exactly do, then maybe they're really doing nothing and we should just copy the JD Cloud description and say that they're just experimenting.

Also, I think the list would benefit from reversing the order. Because I don't understand why similar low SNR description is the first entry, while Gematik and Tencent, both of which have good SNR in their descriptions, are demoted to the bottom of the list.

As a side note, I feel like this thing is taking too much engineering time, which for me is another argument for moving this elsewhere, outside of blast zone of technical reviewers. One intermediate solution would be to invite someone from the project in question to take part in the discussion directly (not least because that would require someone technical enough to use github and reviewable).

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Documentation/gramine-users.rst` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/1030#-NPM7V391ZSSOovYPv3V:-NPcRucD9we5d-ml9hPJ:b4xfmts) ([raw file](https://github.com/gramineproject/gramine/blob/e58366108e32866ab80c8e799d1e30bb6bd2d506/Documentation/gramine-users.rst#L37)):*
I agree with all points.

So let's agree to stop adding new "users of Gramine" in here. This will be the last PR. We should work on the webpage (well, someone...) and move this page from RTD to the webpage.

> Also, I think the list would benefit from reversing the order.

The order is alphabetical (literally by the first word, even if it is `the`). No hidden agenda here :)

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1030)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
