### PR TITLE
Fix typo in run-tests.sh

### PR DESCRIPTION
**Pull request by gutjuri**
Fixed a funny typo.

## How to test this PR? 

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1123)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1123)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @gutjuri)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1123#-NLujjz03Fa48NBeI2BT):*
This should be:
```
[CI-Examples] Fix a typo in `python/run-tests.sh`

Signed-off-by: <your name and your email>
```

Feel free to force-push to modify the commit message.

Please see examples in our Gramine commit history: https://github.com/gramineproject/gramine/commits

By the way, your name is `Juri` (without the surname), I would suggest you to add your surname to the GitHub info.
___
*[`CI-Examples/python/run-tests.sh` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1123#-NLujiZJE_MSAt7mLYge:-NLujiZJE_MSAt7mLYgf:b-nvh0et) ([raw file](https://github.com/gramineproject/gramine/blob/cfa89af5cc07ecc4dfe1ef19e12e9c31a2995b13/CI-Examples/python/run-tests.sh#L12)):*
> ```Shell
> fi
> 
> # === helloworld ===
> ```

lol :)

**Comment by gutjuri** [comment]
> By the way, your name is `Juri` (without the surname), I would suggest you to add your surname to the GitHub info.

True, thanks!

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1123)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @gutjuri)

___
*[`CI-Examples/python/run-tests.sh` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1123#-NLujiZJE_MSAt7mLYge:-NLwWg_GD39J5HU7E-09:bbq4d8r) ([raw file](https://github.com/gramineproject/gramine/blob/cfa89af5cc07ecc4dfe1ef19e12e9c31a2995b13/CI-Examples/python/run-tests.sh#L12)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I don't see a joke here.
It's a hell world.
</blockquote></details>

Heh, I also wonder if this wasn't actually intentional :)

**Review by oshogbo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1123#-:-NM0s0wq1cWIpmf8RRkf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @gutjuri)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1123)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1123#-NLujjz03Fa48NBeI2BT):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll modify the commit title + remove the commit message body (it's useless) on final rebase. No need for you to do anything additional.
</blockquote></details>

Done

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1123)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1123)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1123)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
