### PR TITLE
[python] Fix `{{ ldd }}` and add test

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

Fix `ldd()` function in `gramine-manifest`, which probably never worked and had no tests.

See also: #1410.

## How to test this PR? 

Write some manifest using this function, see if it works.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1411)

### CODE REVIEW

**Comment by Jonas-Eppard** [comment]
Thanks for the quick fix for #1410 but there is still the error with multiple executables as mentioned at the bottom of [comment@#1410](https://github.com/gramineproject/gramine/discussions/1410#discussioncomment-6250900).

**Comment by woju** [comment]
@Jonas-Eppard Yeah, thanks for the analysis. I probably need to iterate a bit on this.

**Comment by dimakuv** [comment]
@Jonas-Eppard Could you check the new version of the patch?

**Comment by Jonas-Eppard** [comment]
> I am currently unable to test the patch, but it should work for one executable but not for multiple executables.
I went ahead and tested it. The comments were correct. It fails when `ldd()` is used with multiple arguments.

**Review by woju — COMMENTED** [review]
Hopefully fixed this now. I'm sorry it took so long.

Also, rebased on top of current master.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1411#-:-Ni03O6OBZ_kb09dZuPN:b-bws7aq)* status: 1 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @Jonas-Eppard)

___
*[`python/graminelibos/gen_jinja_env.py` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/1411#-NYYqFrl4n81DDlxeiUI:-Ni03WkE2MF9GA4-2C2i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a74bdcb7a8567574cbbe4df4afc269c4eace72bf/python/graminelibos/gen_jinja_env.py#L22)):*
<details><summary><i>Previously, Jonas-Eppard (Jonas Eppard) wrote…</i></summary><blockquote>

This is still out of bounds if `ldd` is called with multiple executables.
See [comment#1410](https://github.com/gramineproject/gramine/discussions/1410):
> Since the output of ldd contains seperator lines if called with multiple executables
> [...]
> This would cause the lines t: or main: to also be evaluated in the loop body, but these lines only have 1 element so line[1] is out of bounds.
</blockquote></details>

Done.
___
*[`tests/test_ldd.py` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1411#-NYYqd-52OLKLdFHIyrR:-Ni03Vd7EJ3oO7kBsREQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a74bdcb7a8567574cbbe4df4afc269c4eace72bf/tests/test_ldd.py#L11)):*
<details><summary><i>Previously, Jonas-Eppard (Jonas Eppard) wrote…</i></summary><blockquote>

You should add a test with multiple executables to ensure that this is working as described in the [docs](https://gramine.readthedocs.io/en/stable/manpages/gramine-manifest.html#ldd):

> ldd(*executables)
> List of libraries which are linked from executables. Each library is provided at most once.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> Dismissed @Jonas-Eppard from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1411)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
