### PR TITLE
[Pal] Fix size and alignment of ancillary data buffers

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
These buffers could have been misaligned before and their size could have been too small.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/306)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/306)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/306)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_streams.c, line 242 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZkzW3EznfG9xsGvxX:-MsZkzW3EznfG9xsGvxY:b-jowvzg) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux/db_streams.c#L242)):*
> ```C
>     /* construct ancillary data with FD-to-transfer in a control message */
>     char control_buf[CMSG_SPACE(sizeof(int))]
>         __attribute__((aligned(alignof(struct cmsghdr)))) = { 0 };
> ```

why not just `alignas(struct cmsghdr)`?
___
*[Pal/src/host/Linux/db_streams.c, line 312 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZlUFj-r8dPR8lOpik:-MsZlUFj-r8dPR8lOpil:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux/db_streams.c#L312)):*
> ```C
> 
>     char control_buf[CMSG_SPACE(sizeof(int))]
>         __attribute__((aligned(alignof(struct cmsghdr)))) = { 0 };
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 281 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZlYxs0t9Z7lN389EW:-MsZlYxs0t9Z7lN389EX:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux-SGX/db_streams.c#L281)):*
> ```C
>     /* construct ancillary data with FD-to-transfer in a control message */
>     char control_buf[CMSG_SPACE(sizeof(int))]
>         __attribute__((aligned(alignof(struct cmsghdr)))) = { 0 };
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 348 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZl_G89op7N4Yi2HdK:-MsZl_G89op7N4Yi2HdL:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux-SGX/db_streams.c#L348)):*
> ```C
> 
>     char control_buf[CMSG_SPACE(sizeof(int))]
>         __attribute__((aligned(alignof(struct cmsghdr)))) = { 0 };
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 357 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZlqZf4JrEUfkSpWh6:-MsZlqZf4JrEUfkSpWh7:bku34wr) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux-SGX/db_streams.c#L357)):*
> ```C
>     if (ret < 0)
>         return unix_to_pal_error(ret);
>     if (control_buf_size < sizeof(struct cmsghdr)) {
> ```

Why adding this check? Doesn't `CMSG_SPACE()` already account for `struct cmsghdr`?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/306)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/db_streams.c, line 242 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZkzW3EznfG9xsGvxX:-MsZuBTK6pdTnyMoCLAf:b83kep0) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux/db_streams.c#L242)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why not just `alignas(struct cmsghdr)`?
</blockquote></details>

Because I forgot that we use c11 which has it.
___
*[Pal/src/host/Linux/db_streams.c, line 312 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZlUFj-r8dPR8lOpik:-MsZunSk8D2uBwy6UBHI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux/db_streams.c#L312)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 281 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZlYxs0t9Z7lN389EW:-MsZuv_cEjDGDH3GxSNP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux-SGX/db_streams.c#L281)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 348 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZl_G89op7N4Yi2HdK:-MsZv0PDCsfVNL0StM9S:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux-SGX/db_streams.c#L348)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 357 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZlqZf4JrEUfkSpWh6:-MsZvnu21SPzhuZxHXln:b-x49fuv) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux-SGX/db_streams.c#L357)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why adding this check? Doesn't `CMSG_SPACE()` already account for `struct cmsghdr`?
</blockquote></details>

This checks the return value from the `ocall_recv`.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/306)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/db_streams.c, line 357 at r1](https://reviewable.io/reviews/gramineproject/gramine/306#-MsZlqZf4JrEUfkSpWh6:-Ms_-O8NBy5-Uj5QXc98:b-8b30ou) ([raw file](https://github.com/gramineproject/gramine/blob/5ca8b1fa53a5cf9528cebc15aba582b6381999ab/Pal/src/host/Linux-SGX/db_streams.c#L357)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This checks the return value from the `ocall_recv`.
</blockquote></details>

Aaah.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/306)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/306#-Ms_2AyN-DGGQs9rEMix:-Ms_2AyN-DGGQs9rEMiy:b-enq3y4) (no related file):*
One pipeline failed, please check why.

---

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-18.04 please (LTP `fdatasync01` timed out, existing issue)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/306)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/306)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/306)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
