### PR TITLE
[CI-Examples] Harden Python example

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This PR removes the manifest option `sgx.allowed_files` with its unneeded `/etc/` files. Also the PR cleans up the paths.

## How to test this PR? 

CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/962#-NDmRQ3J3w6JHlV6mIrM):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What paths? 
</blockquote></details>

I meant `{ path = "/usr", uri = "file:/usr" }` and the removed first item in `LD_LIBRARY_PATH`. Do I need to write it explicitly?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/962#-NDmRQ3J3w6JHlV6mIrM):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I meant `{ path = "/usr", uri = "file:/usr" }` and the removed first item in `LD_LIBRARY_PATH`. Do I need to write it explicitly?
</blockquote></details>

or at least specify that you are talking about cleaning paths in manifest template

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/python/python.manifest.template` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/962#-NDmzFhA7lavYmjoYqIB:-NDmzFhA7lavYmjoYqIC:bbsqemi) ([raw file](https://github.com/gramineproject/gramine/blob/b562b9089e9b09f6475cd77de344f9e7ce988ce6/CI-Examples/python/python.manifest.template#L21)):*
> ```
>   { path = "{{ python.distlib }}", uri = "file:{{ python.distlib }}" },
>   { path = "{{ entrypoint }}", uri = "file:{{ entrypoint }}" },
>   { path = "/etc/hosts", uri = "file:helper-files/hosts" },
> ```

FYI: Looks like glibc's `getaddrinfo()` requires this file, otherwise it fails. The only thing that Python needs it for is to figure out the hostname for the `127.0.0.1` address. I'm surprised this mapping (`12.0.0.1` -> `localhost`) is not hard-coded in Glibc, but whatever.

I'm also unclear why without this file, it worked on my local machine but failed on CI?..

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`CI-Examples/python/python.manifest.template` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/962#-NDmzFhA7lavYmjoYqIB:-NDnEesqC5OjSHODR_m8:b-31mlwp) ([raw file](https://github.com/gramineproject/gramine/blob/b562b9089e9b09f6475cd77de344f9e7ce988ce6/CI-Examples/python/python.manifest.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Looks like glibc's `getaddrinfo()` requires this file, otherwise it fails. The only thing that Python needs it for is to figure out the hostname for the `127.0.0.1` address. I'm surprised this mapping (`12.0.0.1` -> `localhost`) is not hard-coded in Glibc, but whatever.

I'm also unclear why without this file, it worked on my local machine but failed on CI?..
</blockquote></details>

different python version maybe?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/962#-NDmRQ3J3w6JHlV6mIrM):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

or at least specify that you are talking about cleaning paths in manifest template
</blockquote></details>

Ok, I'll rephrase the commit message to this:
```
This commit removes the manifest option `sgx.allowed_files` with its
unneeded `/etc/` files. Also the commit cleans up the paths in the 
manifest template.
```

Will do it during final rebase.
___
*[`CI-Examples/python/python.manifest.template` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/962#-NDmzFhA7lavYmjoYqIB:-NE-ojLV7He1tk5lHfTD:b55zts6) ([raw file](https://github.com/gramineproject/gramine/blob/b562b9089e9b09f6475cd77de344f9e7ce988ce6/CI-Examples/python/python.manifest.template#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

different python version maybe?
</blockquote></details>

Yes, maybe a different Python version.

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/962#-NDmRQ3J3w6JHlV6mIrM):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I'll rephrase the commit message to this:
```
This commit removes the manifest option `sgx.allowed_files` with its
unneeded `/etc/` files. Also the commit cleans up the paths in the 
manifest template.
```

Will do it during final rebase.

</blockquote></details>

I'll also add the paragraph similar to https://github.com/gramineproject/gramine/pull/963/commits about `/etc/hosts`.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/962)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
