### PR TITLE
[Docs] Add notes on `_sgx_mrsigner` and `_sgx_mrenclave` encryption keys

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This commit is in response to customers' confusion on how to decrypt files encrypted with these keys.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1725)

### CODE REVIEW

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1725)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1725)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 1011 at r1](https://reviewable.io/reviews/gramineproject/gramine/1725#-Nx82PmZ-pCLqCfjJN3s:-Nx82PmZ-pCLqCfjJN3t:b632zqc) ([raw file](https://github.com/gramineproject/gramine/blob/45d66e339a0476b5e754353c884d7219e30bf898/Documentation/manifest-syntax.rst#L1011)):*
> ```reStructuredText
>   same platform) to unseal files. This key is not accessible outside of the
>   (same) enclave and thus cannot be used to decrypt files encrypted in this
>   enclave.
> ```

This is weirdly written IMO, not sure if I'd understand this sentence without the context of this PR:
- It seems to say mostly the same information as the previous sentence. What's the additional information here which is missing?
- "This key [...] cannot be used to decrypt" - it can, if you extract it somehow. The _key_ can be used, but it's just not accessible outside of the enclave.
- And it's actually not true, this key _is_ used to decrypt the files, by the enclave itself.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1725)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 1011 at r1](https://reviewable.io/reviews/gramineproject/gramine/1725#-Nx82PmZ-pCLqCfjJN3s:-NxBkNgT4yOo1GtBLv99:bjntfvj) ([raw file](https://github.com/gramineproject/gramine/blob/45d66e339a0476b5e754353c884d7219e30bf898/Documentation/manifest-syntax.rst#L1011)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is weirdly written IMO, not sure if I'd understand this sentence without the context of this PR:
- It seems to say mostly the same information as the previous sentence. What's the additional information here which is missing?
- "This key [...] cannot be used to decrypt" - it can, if you extract it somehow. The _key_ can be used, but it's just not accessible outside of the enclave.
- And it's actually not true, this key _is_ used to decrypt the files, by the enclave itself.
</blockquote></details>

Done, I rephrased. The previous text contained only the "recommendation" (`...useful to allow...`). I wanted to add the text that has the "mandatory limitation" flavor to it.

Well, maybe I should be even more specific and change the verb `cannot be used` to something like `can only be derived by the specific enclave on the specific platform, and thus stays secret to the enclave+platform (unless the enclave software explicitly makes this key public)`. I don't know, feels like too much text.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1725)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 1009 at r2](https://reviewable.io/reviews/gramineproject/gramine/1725#-NxCYY5b30OIXAmwmFtB:-NxCYY5b30OIXAmwmFtC:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9a2253ea052776181b16b380bacd1012f098d44a/Documentation/manifest-syntax.rst#L1009)):*
> ```reStructuredText
> * ``"_sgx_mrenclave"`` (SGX only) is the SGX sealing key based on the MRENCLAVE
>   identity of the enclave. This is useful to allow only the same enclave (on the
>   same platform) to unseal files, i.e., this key cannot be used by any other
> ```





_Suggestion:_
```reStructuredText
this key is not accessible to any other
```
___
*[`Documentation/manifest-syntax.rst` line 1014 at r2](https://reviewable.io/reviews/gramineproject/gramine/1725#-NxCY_I9-_mI8h9F9b9g:-NxCY_I9-_mI8h9F9b9h:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9a2253ea052776181b16b380bacd1012f098d44a/Documentation/manifest-syntax.rst#L1014)):*
> ```reStructuredText
> * ``"_sgx_mrsigner"`` (SGX only) is the SGX sealing key based on the MRSIGNER
>   identity of the enclave. This is useful to allow all enclaves signed with the
>   same key (and on the same platform) to unseal files, i.e., this key cannot be
> ```

ditto

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1725)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/manifest-syntax.rst` line 1009 at r2](https://reviewable.io/reviews/gramineproject/gramine/1725#-NxCYY5b30OIXAmwmFtB:-NxCbhtw6UPL1O3HpaRz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9a2253ea052776181b16b380bacd1012f098d44a/Documentation/manifest-syntax.rst#L1009)):*
> ```reStructuredText
> * ``"_sgx_mrenclave"`` (SGX only) is the SGX sealing key based on the MRENCLAVE
>   identity of the enclave. This is useful to allow only the same enclave (on the
>   same platform) to unseal files, i.e., this key cannot be used by any other
> ```

Done.
___
*[`Documentation/manifest-syntax.rst` line 1014 at r2](https://reviewable.io/reviews/gramineproject/gramine/1725#-NxCY_I9-_mI8h9F9b9g:-NxCbi9jAkrIPNJwBlql:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9a2253ea052776181b16b380bacd1012f098d44a/Documentation/manifest-syntax.rst#L1014)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1725)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1725)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1725)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
