### PR TITLE
[Pal/Linux-SGX] Generate `gsgx.h` using Meson

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

This PR is on top of #107.

Compared to @woju's original approach, I don't introduce a separate `include/gramine-config.h`, but generate `gsgx.h` directly. This might be less future-proof if we end needing a global config header in the future, but for now it's probably enough?

## How to test this PR? 

Jenkins tests the out-of-tree and DCAP 1.6 drivers, it would be nice to verify compilation on in-tree and DCAP 1.10.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[meson.build, line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/112#-MkyFZPs3yseB7xxen20:-MkyFZPs3yseB7xxen21:b-xk1j2g) ([raw file](https://github.com/gramineproject/gramine/blob/9d9d8896ec9617bfe12df88c153d19b259f97cc8/meson.build#L71)):*
> ```Meson
>     conf_sgx = configuration_data()
> 
>     # SGX driver options (in make, this was ISGX_DRIVER_PATH and link-intel-driver.py)
> ```

`make` -> `Make`
___
*[meson.build, line 108 at r1](https://reviewable.io/reviews/gramineproject/gramine/112#-MkyR3m07DrJ0x6Tbd0i:-MkyR3m12V4zAenmg4mT:b-uz8hlw) ([raw file](https://github.com/gramineproject/gramine/blob/9d9d8896ec9617bfe12df88c153d19b259f97cc8/meson.build#L108)):*
> ```Meson
>             sgx_driver_device = '/dev/isgx'
>         endif
> ```

I'd prefer to drop these empty lines, so that this whole `if-elif-else` looks like one construct/"cascade" visually. And you will still see the conditional blocks clearly, because they are indented.
Not blocking though.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: 10 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[meson.build, line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/112#-MkyFZPs3yseB7xxen20:-Mkzo5X_8KgAtx540QoH:b2nhktp) ([raw file](https://github.com/gramineproject/gramine/blob/9d9d8896ec9617bfe12df88c153d19b259f97cc8/meson.build#L71)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`make` -> `Make`
</blockquote></details>

OK.
___
*[meson.build, line 108 at r1](https://reviewable.io/reviews/gramineproject/gramine/112#-MkyR3m07DrJ0x6Tbd0i:-MkzpZT000_28ZlQqQOO:b-eub1af) ([raw file](https://github.com/gramineproject/gramine/blob/9d9d8896ec9617bfe12df88c153d19b259f97cc8/meson.build#L108)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to drop these empty lines, so that this whole `if-elif-else` looks like one construct/"cascade" visually. And you will still see the conditional blocks clearly, because they are indented.
Not blocking though.
</blockquote></details>

Actually I think there's too much logic here, all these `if`s add noise. I'll refactor it so that we compute the defaults first, and assign them later.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[meson.build, line 108 at r1](https://reviewable.io/reviews/gramineproject/gramine/112#-MkyR3m07DrJ0x6Tbd0i:-Ml-c44C-rxERPnGQKqB:b-26bsm0) ([raw file](https://github.com/gramineproject/gramine/blob/9d9d8896ec9617bfe12df88c153d19b259f97cc8/meson.build#L108)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually I think there's too much logic here, all these `if`s add noise. I'll refactor it so that we compute the defaults first, and assign them later.
</blockquote></details>

:thumbsup:
reads much better now!

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[meson.build, line 86 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-uG6rD0V5XVacb1eP:-Ml-uG6rD0V5XVacb1eQ:b-6t937e) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/meson.build#L86)):*
> ```Meson
>     #     (https://lore.kernel.org/linux-sgx/20200716135303.276442-1-jarkko.sakkinen@linux.intel.com)
>     #   - default sgx_in_kernel.h for upstreamed in-kernel driver from mainline Linux kernel 5.11+
>     #     (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git)
> ```

Two last points are obsolete I think? We don't make a difference between the patchset in the middle of review and the final version, and after this PR we don't use `sgx_in_kernel.h` which should also be removed.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-sbty55h_YJTw7PUm:-Ml-sbty55h_YJTw7PUn:b-n5wacg) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/.ci/lib/stage-build-sgx.jenkinsfile#L32)):*
> ```
>                 -Ddirect=disabled \
>                 -Dsgx=enabled \
>                 -Dsgx_driver=dcap1.6
> ```

Don't you want `$MESON_OPTIONS` from below also here?
___
*[Pal/src/host/Linux-SGX/meson.build, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-tI-23ulL1dGK9vTy:-Ml-tI-23ulL1dGK9vTz:bbksfsf) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/Pal/src/host/Linux-SGX/meson.build#L7)):*
> ```Meson
> # - sgx_integration/sgx_gdb.so
> 
> configure_file(
> ```

`gsgx_h = configure_file(...)`, and this needs to be added as source to targets that use it. 
___
*[Pal/src/host/Linux-SGX/meson.build, line 75 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-tq-HETOAj3IndjCR:-Ml-tq-HETOAj3IndjCS:bcgjvre) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/Pal/src/host/Linux-SGX/meson.build#L75)):*
> ```Meson
>     depends: [
>         tomlc99_src,
>     ]
> ```

Why this change?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: 8 of 11 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[meson.build, line 86 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-uG6rD0V5XVacb1eP:-Ml0JgZeBiUzSG2Ye-a9:b7y4vph) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/meson.build#L86)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Two last points are obsolete I think? We don't make a difference between the patchset in the middle of review and the final version, and after this PR we don't use `sgx_in_kernel.h` which should also be removed.
</blockquote></details>

Oh, I copied this from `link-sgx-driver.py`, but I didn't look too closely, my bad.

I removed this and added a short comment to each branch.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-sbty55h_YJTw7PUm:-Ml0K1GYCSM6r74I4ARM:b-qvpryc) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/.ci/lib/stage-build-sgx.jenkinsfile#L32)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Don't you want `$MESON_OPTIONS` from below also here?
</blockquote></details>

Yes, that makes sense. Fixed.
___
*[Pal/src/host/Linux-SGX/meson.build, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-tI-23ulL1dGK9vTy:-Ml0KR3SAO9zXxqeA3BK:b-df8jjj) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/Pal/src/host/Linux-SGX/meson.build#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`gsgx_h = configure_file(...)`, and this needs to be added as source to targets that use it. 
</blockquote></details>

Weird, Meson documentation ([Configuration](https://mesonbuild.com/Configuration.html)) doesn't say that, only says to put the directory in the other target's `include_directories`.

I added it, and it seems to work, but it feels strange to add `.h` to sources. I'm guessing Meson treats `.h` "sources" as something you don't pass to a compiler, but only use when calculating dependencies?
___
*[Pal/src/host/Linux-SGX/meson.build, line 75 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-tq-HETOAj3IndjCR:-Ml0M3Xt4tJTr5jdSXd1:b-9d1dm5) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/Pal/src/host/Linux-SGX/meson.build#L75)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

I added something to `depends` and removed it later, but didn't clean up properly. Fixed, thanks.

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by dimakuv — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by mkow — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

**Comment by pwmarcz** [comment]
Jenkins, retest Jenkins-Direct-Sanitizers please (known issue: timeout on LTP test `sendfile09` because the ASan build is slower)

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[meson.build, line 86 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-uG6rD0V5XVacb1eP:-Ml1rFCc3ekEuOkaA4aD:bnn3tfq) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/meson.build#L86)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oh, I copied this from `link-sgx-driver.py`, but I didn't look too closely, my bad.

I removed this and added a short comment to each branch.
</blockquote></details>

Oh, this is nice. I like it.
___
*[Pal/src/host/Linux-SGX/meson.build, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-tI-23ulL1dGK9vTy:-Ml1qQbT5dTLlFNnto7V:b-vdoixk) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/Pal/src/host/Linux-SGX/meson.build#L7)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Weird, Meson documentation ([Configuration](https://mesonbuild.com/Configuration.html)) doesn't say that, only says to put the directory in the other target's `include_directories`.

I added it, and it seems to work, but it feels strange to add `.h` to sources. I'm guessing Meson treats `.h` "sources" as something you don't pass to a compiler, but only use when calculating dependencies?
</blockquote></details>

Yes, this is barely documented. Adding `.h` to sources doesn't add it anywhere in the CC's command line at any stage, but generates a dependency on this file for the first build. On subsequent rebuilds the autogenerated `.d` is used. https://mesonbuild.com/Reference-manual.html#executable (which is also applicable to `shared_library()`).

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux-SGX/meson.build, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/112#-Ml-tI-23ulL1dGK9vTy:-Ml3zQM86aPeJvy7McT7:bgzdlde) ([raw file](https://github.com/gramineproject/gramine/blob/8d51301b06fc0bb1a9dadf4547873cda9fd6c314/Pal/src/host/Linux-SGX/meson.build#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, this is barely documented. Adding `.h` to sources doesn't add it anywhere in the CC's command line at any stage, but generates a dependency on this file for the first build. On subsequent rebuilds the autogenerated `.d` is used. https://mesonbuild.com/Reference-manual.html#executable (which is also applicable to `shared_library()`).
</blockquote></details>

Good to know, thanks!

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/112)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
