### PR TITLE
[tests] Remove duplicated read/write function

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

There is a slight difference between `write_all` and `posix_fd_rw` functions. Because the test doesn't use any signal handler, the write_all function treat EINTR as an error. However, I don't think this is a good reason to introduce a separate write function, and we can reuse existing one.

## How to test this PR? 

Run the test suite should be enough.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`libos/test/regression/rename_unlink.c` line 91 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND47XR7DfZ7bF0vUXN7:-ND47XR7DfZ7bF0vUXN8:bn62f7v) ([raw file](https://github.com/gramineproject/gramine/blob/5ef3eb6de18dc99f19967c138ea550f89c0f7eb7/libos/test/regression/rename_unlink.c#L91)):*
> ```C
>     if (posix_fd_write(fd, str, len) == -1)
>         errx(1, "posix_fd_write %s", path);
> ```

Shouldn't we check for `ret != len`?
___
*[`libos/test/regression/rename_unlink.c` line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND47_yPBiWUuWVMATex:-ND47_yPBiWUuWVMATey:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5ef3eb6de18dc99f19967c138ea550f89c0f7eb7/libos/test/regression/rename_unlink.c#L213)):*
> ```C
>     if (posix_fd_write(fd, message1, message1_len) == -1)
>         errx(1, "posix_fd_write %s", path);
> ```

ditto

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`libos/test/regression/rename_unlink.c` line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND5s-fc0BWTMpu8bHwa:-ND5s-fc0BWTMpu8bHwb:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/5ef3eb6de18dc99f19967c138ea550f89c0f7eb7/libos/test/regression/rename_unlink.c#L74)):*
> ```C
>     ssize_t n = posix_fd_read(fd, buffer, len);
>     if (n < 0)
>         errx(1, "%s: read_fd failed", desc);
> ```





_Suggestion:_
```C
posix_fd_read failed
```

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND7-ymx2fhm4DxrRbA6):*
`write_all` -> `write_all/read_all`
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND702_T2idZhHxmcRdN):*
`the write_all` function -> `the write_all/read_all functions`
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND707RTA9p-1FfYhtHC):*
`to introduce separate read/write functions`
___
*[`libos/test/regression/rename_unlink.c` line 91 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND47XR7DfZ7bF0vUXN7:-ND70QYREOZVkh0HfCbt:bale442) ([raw file](https://github.com/gramineproject/gramine/blob/5ef3eb6de18dc99f19967c138ea550f89c0f7eb7/libos/test/regression/rename_unlink.c#L91)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we check for `ret != len`?
</blockquote></details>

+1. And also `< 0` instead of `== -1`, for uniformity with the read change.
___
*[`libos/test/regression/rename_unlink.c` line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND47_yPBiWUuWVMATex:-ND70jIx7VUWcFkQ6FHf:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5ef3eb6de18dc99f19967c138ea550f89c0f7eb7/libos/test/regression/rename_unlink.c#L213)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND7-ymx2fhm4DxrRbA6):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`write_all` -> `write_all/read_all`
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND702_T2idZhHxmcRdN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the write_all` function -> `the write_all/read_all functions`
</blockquote></details>

Done.
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND707RTA9p-1FfYhtHC):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to introduce separate read/write functions`
</blockquote></details>

Done.
___
*[`libos/test/regression/rename_unlink.c` line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND5s-fc0BWTMpu8bHwa:-ND7raLCEFIBv9psqT9o:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5ef3eb6de18dc99f19967c138ea550f89c0f7eb7/libos/test/regression/rename_unlink.c#L74)):*
> ```C
>     ssize_t n = posix_fd_read(fd, buffer, len);
>     if (n < 0)
>         errx(1, "%s: read_fd failed", desc);
> ```

Done.
___
*[`libos/test/regression/rename_unlink.c` line 91 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND47XR7DfZ7bF0vUXN7:-ND47v3Q8h66QOLPmOWz:b-ihi77p) ([raw file](https://github.com/gramineproject/gramine/blob/5ef3eb6de18dc99f19967c138ea550f89c0f7eb7/libos/test/regression/rename_unlink.c#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. And also `< 0` instead of `== -1`, for uniformity with the read change.
</blockquote></details>

Hym, yea know when I think in *theory* might return 0, in which case `posix_fd_write` will behave in different manner then `write_all`
Let's check this value.
Done.
___
*[`libos/test/regression/rename_unlink.c` line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/940#-ND47_yPBiWUuWVMATex:-ND7qxK64MLUlWsV7DUL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5ef3eb6de18dc99f19967c138ea550f89c0f7eb7/libos/test/regression/rename_unlink.c#L213)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/940#-ND84qip4xQ4-Z2b5v1G):*
`functions`
___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/940#-ND84vQYEo5vfd8WR8VH):*
`...reuse an existing one.`
___
*[`libos/test/regression/rename_unlink.c` line 93 at r2](https://reviewable.io/reviews/gramineproject/gramine/940#-ND84kJW5zTP7pj-t2qJ:-ND84kJW5zTP7pj-t2qK:b-2eg6vw) ([raw file](https://github.com/gramineproject/gramine/blob/d508a3ebb0fb99686780fe2a1f514f107bb0a310/libos/test/regression/rename_unlink.c#L93)):*
> ```C
>         errx(1, "posix_fd_write %s", path);
>     if ((size_t)n != len)
>         warnx("write less bytes than expected into %s", path);
> ```

`written`
___
*[`libos/test/regression/rename_unlink.c` line 218 at r2](https://reviewable.io/reviews/gramineproject/gramine/940#-ND84lVv20MPL2pS5_Sr:-ND84lVv20MPL2pS5_Ss:b-2eg6vw) ([raw file](https://github.com/gramineproject/gramine/blob/d508a3ebb0fb99686780fe2a1f514f107bb0a310/libos/test/regression/rename_unlink.c#L218)):*
> ```C
>         errx(1, "posix_fd_write %s", path);
>     if ((size_t)n != message1_len)
>         warnx("write less bytes than expected into %s", path);
> ```

`written`

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/940#-ND84qip4xQ4-Z2b5v1G):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`functions`
</blockquote></details>

Done.
___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/940#-ND84vQYEo5vfd8WR8VH):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...reuse an existing one.`
</blockquote></details>

Done.
___
*[`libos/test/regression/rename_unlink.c` line 93 at r2](https://reviewable.io/reviews/gramineproject/gramine/940#-ND84kJW5zTP7pj-t2qJ:-ND8MmeIAANrePsSQVWs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d508a3ebb0fb99686780fe2a1f514f107bb0a310/libos/test/regression/rename_unlink.c#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`written`
</blockquote></details>

Done.
___
*[`libos/test/regression/rename_unlink.c` line 218 at r2](https://reviewable.io/reviews/gramineproject/gramine/940#-ND84lVv20MPL2pS5_Sr:-ND8Mn4n0sslm09Gsi33:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d508a3ebb0fb99686780fe2a1f514f107bb0a310/libos/test/regression/rename_unlink.c#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`written`
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`-- commits` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/940#-ND8OIxf6fIjbJk-a8hk):*
Lol, you changed it in the wrong place :)

Whatever, we'll fix it during the final rebase.
___
*[`-- commits` line 38 at r3](https://reviewable.io/reviews/gramineproject/gramine/940#-ND8OR1lAlOedJ2jWApo):*
`ones` -> `one`

My logic was "we replace two functions with an existing one".

We'll fix it during the final rebase.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/regression/rename_unlink.c` line 93 at r3](https://reviewable.io/reviews/gramineproject/gramine/940#-ND8xiyy3zyDB2XLzD9z:-ND8xiyy3zyDB2XLzDA-:b-yk2io6) ([raw file](https://github.com/gramineproject/gramine/blob/88cea1b7ddd048aae6beba85a0714c01ffd585ac/libos/test/regression/rename_unlink.c#L93)):*
> ```C
>         errx(1, "posix_fd_write %s", path);
>     if ((size_t)n != len)
>         warnx("written less bytes than expected into %s", path);
> ```

Shouldn't this be `errx`?



_Code quote:_
```C
warnx
```
___
*[`libos/test/regression/rename_unlink.c` line 218 at r3](https://reviewable.io/reviews/gramineproject/gramine/940#-ND8y47I-yfDUYA6XVH1:-ND8y47I-yfDUYA6XVH2:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/88cea1b7ddd048aae6beba85a0714c01ffd585ac/libos/test/regression/rename_unlink.c#L218)):*
> ```C
>         errx(1, "posix_fd_write %s", path);
>     if ((size_t)n != message1_len)
>         warnx("written less bytes than expected into %s", path);
> ```

ditto



_Code quote:_
```C
warnx
```

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/940#-ND8OIxf6fIjbJk-a8hk):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Lol, you changed it in the wrong place :)

Whatever, we'll fix it during the final rebase.
</blockquote></details>

You mean the comment below or something else?
___
*[`-- commits` line 38 at r3](https://reviewable.io/reviews/gramineproject/gramine/940#-ND8OR1lAlOedJ2jWApo):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`ones` -> `one`

My logic was "we replace two functions with an existing one".

We'll fix it during the final rebase.
</blockquote></details>

Done.
___
*[`libos/test/regression/rename_unlink.c` line 93 at r3](https://reviewable.io/reviews/gramineproject/gramine/940#-ND8xiyy3zyDB2XLzD9z:-NDEUVU57ZLEL3xo0ySq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88cea1b7ddd048aae6beba85a0714c01ffd585ac/libos/test/regression/rename_unlink.c#L93)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be `errx`?
</blockquote></details>

Done.
___
*[`libos/test/regression/rename_unlink.c` line 218 at r3](https://reviewable.io/reviews/gramineproject/gramine/940#-ND8y47I-yfDUYA6XVH1:-NDEUVuPAte2hAUcZhf5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88cea1b7ddd048aae6beba85a0714c01ffd585ac/libos/test/regression/rename_unlink.c#L218)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 1 unresolved discussion, "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/940#-ND8OIxf6fIjbJk-a8hk):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

You mean the comment below or something else?
</blockquote></details>

I meant that you changed `function` -> `functions` in the "squash!" section but kept it in the "[tests]" title. Anyway, you already fixed it.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/940)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
