### PR TITLE
[LibOS] Use `-1` for special signal value instead of `0xff`

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Gramine allows to inject only one SIGTERM (signal number 15). To distinguish a case when SIGTERM was already injected, LibOS atomically updates a global variable to a special value meaning "SIGTERM was injected". Previously, this special value was chosen as `0xff` for no obvious reason. This leads to an artificial requirement that valid signals cannot have numbers great than or equal to 255 (`0xff`).

This commit removes this artifical requirement by replacing `0xff` with `-1`. This is possible because signals are always of type `int`.

Suggested by @mkow . See discussions in #1703 

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1766)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1766)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1766)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1766#-NqBeTAMAcwddW606ygT):*
`greater than` (typo)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1766)* status: all files reviewed, 1 unresolved discussion

**Review by kailun-qin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1766)* status: all files reviewed, 1 unresolved discussion

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1766#-NqNbFjbAOzv2QmGAxgd):*
-> `artificial` (sorry for noticing this late)



_Code quote:_
```
artifical
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1766)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1766#-NqBeTAMAcwddW606ygT):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`greater than` (typo)
</blockquote></details>

Done
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1766#-NqNbFjbAOzv2QmGAxgd):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `artificial` (sorry for noticing this late)
</blockquote></details>

Done

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1766)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Pull request merged**
