### PR TITLE
[Pal/Linux-SGX] Fix header conflict in `sgx_main.c`

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

The problem with headers was because we imported <sys/auxv.h>, which in turns imports <elf.h>, which clashes with our own "elf.h". That was because we used the `getauxval` function from glibc. Instead, we manually parse the ELF aux vector.

## How to test this PR? 

I used a temporary log line to check if we retrieve the same value of `AT_HWCAP2`.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/416#-MwDSCykAXSn_rwxU3t3:-MwDSCyl35mq3cagecrW:b-t76nm0) (no related file):*
Why can't we just declare `getauxval` as extern symbol?
Or even better, fix the original problem, which is importing Gramine elf.h in untrusted PAL?

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/416#-MwDSCykAXSn_rwxU3t3:-MwQn4fa9iHuXc9HAb0f:b-2f0qgc) (no related file):*
>Why can't we just declare `getauxval` as extern symbol?

I assumed that even though we link against glibc, we want to rely on it as little as possible (so that e.g. we might stop linking against it in the future).

We have no written policy for such cases, though. Any opinions, @mkow @dimakuv?

> Or even better, fix the original problem, which is importing Gramine elf.h in untrusted PAL?

This file processes an ELF binary (libsysdb) to prepare the enclave, so it needs ELF struct definitions.

I'd say the "original problem" is including a `<sys/*>` header, which we almost never do because they tend to conflict with Gramine's own.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/416#-MwDSCykAXSn_rwxU3t3:-MwQqvId8bkZVo8t9mTl:b-qlddo7) (no related file):*
> I assumed that even though we link against glibc, we want to rely on it as little as possible (so that e.g. we might stop linking against it in the future).

Yes, we definitely should avoid linking against Glibc as little as possible. This way we'll have more shared code between different PALs, and just in general *not* using Glibc is a cleaner approach in my opinion.

I prefer Pawel's solution to the problem (i.e., I prefer this PR).

---

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/416#-MwDSCykAXSn_rwxU3t3:-MwRBWaM69mBead5CUHz:bk0lqnc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I assumed that even though we link against glibc, we want to rely on it as little as possible (so that e.g. we might stop linking against it in the future).

Yes, we definitely should avoid linking against Glibc as little as possible. This way we'll have more shared code between different PALs, and just in general *not* using Glibc is a cleaner approach in my opinion.

I prefer Pawel's solution to the problem (i.e., I prefer this PR).
</blockquote></details>

I'm fine with the current PR, mostly because I don't like any of the solutions, so whatever. The problem is that we use these Gramine-internal common headers in a context with system headers included, while it's designed for the env without them. I'm not sure how to solve it better :/

---

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/416#-MwDSCykAXSn_rwxU3t3:-MwSbujS4zdbjWIRTnLH:b7wgatm) (no related file):*
> I assumed that even though we link against glibc, we want to rely on it as little as possible (so that e.g. we might stop linking against it in the future).

I've never heard that we want to stop linking against glibc (actually, why would we) and I don't think it's possible - we link against protobuf (which itself links against glibc).

> This file processes an ELF binary (libsysdb) to prepare the enclave, so it needs ELF struct definitions.

So it should be fine to include system headers.

> I'd say the "original problem" is including a <sys/*> header, which we almost never do because they tend to conflict with Gramine's own.

I disagree. This is untrusted PAL, which is separate from LibOS and trusted PAL, where we want to use just Gramine headers.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/416#-MwDSCykAXSn_rwxU3t3:-MwSdjhs2072ynMa_djE:blmqc76) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> I assumed that even though we link against glibc, we want to rely on it as little as possible (so that e.g. we might stop linking against it in the future).

I've never heard that we want to stop linking against glibc (actually, why would we) and I don't think it's possible - we link against protobuf (which itself links against glibc).

> This file processes an ELF binary (libsysdb) to prepare the enclave, so it needs ELF struct definitions.

So it should be fine to include system headers.

> I'd say the "original problem" is including a <sys/*> header, which we almost never do because they tend to conflict with Gramine's own.

I disagree. This is untrusted PAL, which is separate from LibOS and trusted PAL, where we want to use just Gramine headers.
</blockquote></details>

Since you all seem to be fine with this PR I'm unblocking, but I disagree with reasoning in the commit message

---

**Review by boryspoplawski — APPROVED** [review]

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/416#-MwDSCykAXSn_rwxU3t3:-MwVSjwo25JsgfRI78Gy:bq9tl95) (no related file):*
> I've never heard that we want to stop linking against glibc (actually, why would we) and I don't think it's possible - we link against protobuf (which itself links against glibc).

I would prefer to link against a static version of protobuf which in turn links against a static musl. I think we discussed this at some point -- that we could move to static musl and have a completely self-contained untrusted-SGX PAL binary.

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/416#-MwDSCykAXSn_rwxU3t3:-MwVtfsp-NcYSd0ctFgR:b-mfhwrr) (no related file):*
>I disagree. This is untrusted PAL, which is separate from LibOS and trusted PAL, where we want to use just Gramine headers.

It's a separate executable, but it's very much *not* separate in terms of code. Untrusted PAL includes a lot of Gramine's headers, is linked against the "common" library, and so on. If we wanted to enable the use of glibc headers, there would be a lot of work to do in terms of untangling that mess.

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/416)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by pwmarcz** [comment]
Jenkins, retest Jenkins-18.04 please (`fdatasync01` LTP test failed)

**Pull request merged**
