### PR TITLE
[Pal/{Linux,Linux-SGX}] Clean up `_DkStreamsWaitEvents`

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Mostly remove unnecessary `offset` arrays.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/386)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/386)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_object.c, line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/386#-MvNsVvK-CrMn2B2sPz9:-MvNsVvK-CrMn2B2sPzA:b-rfyq00) ([raw file](https://github.com/gramineproject/gramine/blob/f4b6a7418aa7ad54debd10b0e81739b053343054/Pal/src/host/Linux/db_object.c#L74)):*
> ```C
>         ret = unix_to_pal_error(ret);
>         goto out;
>     } else if (!ret) {
> ```

Not blocking, but I liked the previous version better.
___
*[Pal/src/host/Linux-SGX/db_object.c, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/386#-MvNtRYw7IFnQZz99sFf:-MvNtRYw7IFnQZz99sFg:b-rfyq00) ([raw file](https://github.com/gramineproject/gramine/blob/f4b6a7418aa7ad54debd10b0e81739b053343054/Pal/src/host/Linux-SGX/db_object.c#L59)):*
> ```C
>         ret = unix_to_pal_error(ret);
>         goto out;
>     } else if (ret == 0) {
> ```

Not blocking, but I liked the previous version better.
___
*[Pal/src/host/Linux-SGX/db_object.c, line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/386#-MvNt9u14V3YyEFIbdsx:-MvNt9u14V3YyEFIbdsy:b-abwc9q) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/Pal/src/host/Linux-SGX/db_object.c#L77)):*
> ```C
>         ret = -PAL_ERROR_INVAL;
>         goto out;
>     }
> ```

Maybe we could still have this shortcut, to skip the expensive OCALL? Otoh, I guess if the LibOS layer is sending us an array of un-pollable handles, then it is not our fault.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/386)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/386#-MvNtcGgBHRK2zYxVXEv:-MvP_Rg7-96jryn3bMJT:b-yy4ygb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Putting a blocking comment because this PR depends on https://github.com/gramineproject/gramine/pull/385.

I'm unsure how it would actually work, but both Reviewable and GitHub tell me that this PR can be merged, when apparently it can't be merged until #385 is approved. I wonder what would happen if I would try to merge? The PR would be merged into Borys's other branch? Is this how it's supposed to work, and is this how we want to use this merge-into-other-branch feature?
</blockquote></details>

Yes, it would be merge to the other branch, because that's the base branch of this PR, it's written below PR topic.
I would say we just don't merge PRs not targeted against master (we do not have any other branches, so it's fine).

---
___
*[Pal/src/host/Linux/db_object.c, line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/386#-MvNsVvK-CrMn2B2sPz9:-MvP_yh_1OAVlSYjq5sj:bxu7w0o) ([raw file](https://github.com/gramineproject/gramine/blob/f4b6a7418aa7ad54debd10b0e81739b053343054/Pal/src/host/Linux/db_object.c#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not blocking, but I liked the previous version better.
</blockquote></details>

I prefer this version as these 2 cases are exclusive (so it's only natural for me to use `else if`). Changed to `== 0` so it's more clear.
___
*[Pal/src/host/Linux-SGX/db_object.c, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/386#-MvNtRYw7IFnQZz99sFf:-MvPaTLGB6UZ3xrSPvSb:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f4b6a7418aa7ad54debd10b0e81739b053343054/Pal/src/host/Linux-SGX/db_object.c#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not blocking, but I liked the previous version better.
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/db_object.c, line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/386#-MvNt9u14V3YyEFIbdsx:-MvPabrOAVVHMp-Kl2Ol:b-t0u3ru) ([raw file](https://github.com/gramineproject/gramine/blob/bc90e314b3ae9bef1f6ded431b886fb3421f1b7b/Pal/src/host/Linux-SGX/db_object.c#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we could still have this shortcut, to skip the expensive OCALL? Otoh, I guess if the LibOS layer is sending us an array of un-pollable handles, then it is not our fault.
</blockquote></details>

I even wanted to remove the support for passing invalid handles at all, but didn't know if we really do not do so. For example I wasn't sure in which cases `fd` can be missing from handle.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/386)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/386#-MvNtcGgBHRK2zYxVXEv:-MvPh6Hr6oNkkPmQ0AJs:bthaye1) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, it would be merge to the other branch, because that's the base branch of this PR, it's written below PR topic.
I would say we just don't merge PRs not targeted against master (we do not have any other branches, so it's fine).
</blockquote></details>

True. I noticed only now that the message says "base branch", not "master branch".

---

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/386)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_object.c, line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/386#-MvfrtRt-vOjp5L61_mR:-MvfrtRt-vOjp5L61_mS:b-c9f4a5) ([raw file](https://github.com/gramineproject/gramine/blob/25d0d06bbac5680c0c2317e4a1c879c63d54529b/Pal/src/host/Linux/db_object.c#L83)):*
> ```C
>         if (fds[i].fd == -1) {
>             /* We skipped this fd. */
>             continue;
> ```

It was like this before, but why are we leaving `ret_events` uninitialized for skipped FDs? Sounds quite unintuitive from the caller's perspective.
___
*[Pal/src/host/Linux-SGX/db_object.c, line 48 at r2](https://reviewable.io/reviews/gramineproject/gramine/386#-MvfrN0eEnNPT8X-PYii:-MvfrN0fBMWX6ygTeAyo:bozuzs3) ([raw file](https://github.com/gramineproject/gramine/blob/25d0d06bbac5680c0c2317e4a1c879c63d54529b/Pal/src/host/Linux-SGX/db_object.c#L48)):*
> ```C
> 
>         if (HANDLE_HDR(handle)->type == PAL_TYPE_PIPE) {
>             while (!__atomic_load_n(&handle->pipe.handshake_done, __ATOMIC_ACQUIRE)) {
> ```

This looks like a bugfix, please mention it in the commit message.
___
*[Pal/src/host/Linux-SGX/db_object.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/386#-MvfrqNr9rlMFhv0WlDJ:-MvfrqNr9rlMFhv0WlDK:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/25d0d06bbac5680c0c2317e4a1c879c63d54529b/Pal/src/host/Linux-SGX/db_object.c#L68)):*
> ```C
>         if (fds[i].fd == -1) {
>             /* We skipped this fd. */
>             continue;
> ```

ditto

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/386)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux/db_object.c, line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/386#-MvfrtRt-vOjp5L61_mR:-MvjL1NL9Zg_gEKQMAJg:b-xnep5) ([raw file](https://github.com/gramineproject/gramine/blob/25d0d06bbac5680c0c2317e4a1c879c63d54529b/Pal/src/host/Linux/db_object.c#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It was like this before, but why are we leaving `ret_events` uninitialized for skipped FDs? Sounds quite unintuitive from the caller's perspective.
</blockquote></details>

We are not, look at the initial loop, which prepares poll arguments, it also clears the out args.
___
*[Pal/src/host/Linux-SGX/db_object.c, line 48 at r2](https://reviewable.io/reviews/gramineproject/gramine/386#-MvfrN0eEnNPT8X-PYii:-MvjNtG-D6YcXnkfZmoe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/25d0d06bbac5680c0c2317e4a1c879c63d54529b/Pal/src/host/Linux-SGX/db_object.c#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This looks like a bugfix, please mention it in the commit message.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_object.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/386#-MvfrqNr9rlMFhv0WlDJ:-MvjM5Jk7BlIY-8-h1us:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/25d0d06bbac5680c0c2317e4a1c879c63d54529b/Pal/src/host/Linux-SGX/db_object.c#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto

**Review by mkow — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/386)* status: all files reviewed, all discussions resolved, "squash! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/386)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
