### PR TITLE
[Docs] Unify and document copyright notices

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

As discussed in https://github.com/gramineproject/gramine/pull/374 review.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/403)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 43 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/403)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/403#-MvwJvhGCGPNKPIu1raq:-MvwJvhGCGPNKPIu1rar:byf184x) (no related file):*
FYI: I manually checked LibOS files, looks like indeed you didn't miss anything.

---
___
*[CONTRIBUTING.rst, line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/403#-MvwIrIJ1084_eo-lzWu:-MvwIrIJ1084_eo-lzWv:bqq2fox) ([raw file](https://github.com/gramineproject/gramine/blob/20aab4dcdf429c613fcb996027bbe39ef2900dfd/CONTRIBUTING.rst#L173)):*
> ```reStructuredText
> readers with a rough summary of the copyrights. Because it's just a summary, we
> inlude only the year of the most recent copyrighted modification to the file
> (to know when all the copyright claims from a specific owner vanish).
> ```

`vanish` -> `expire`? Not blocking.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/403)* status: 42 of 43 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/403#-MvwJvhGCGPNKPIu1raq:-MvxmT1r5Xq8u_2aCJ68:b-ucfknh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I manually checked LibOS files, looks like indeed you didn't miss anything.
</blockquote></details>

Thanks!

---
___
*[CONTRIBUTING.rst, line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/403#-MvwIrIJ1084_eo-lzWu:-MvxmUWEDV78TLpwg1gT:bic1h37) ([raw file](https://github.com/gramineproject/gramine/blob/20aab4dcdf429c613fcb996027bbe39ef2900dfd/CONTRIBUTING.rst#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`vanish` -> `expire`? Not blocking.
</blockquote></details>

Ah, this was the word I was missing and couldn't recall :) Fixed.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/403)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 42 of 43 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/403)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/403#-Mw6imPjEQVcKBFt0h5H:-Mw6imPjEQVcKBFt0h5I:b-pqkjzq) (no related file):*
I see we used to be afraid of unicode :) (`Rafal Wojdyla`)

(not blocking)

---

**Review by dimakuv — DISMISSED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/403)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/403)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/403#-Mw6imPjEQVcKBFt0h5H:-Mw70EE6BtypVT467wxB:b-x3ezb3) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I see we used to be afraid of unicode :) (`Rafal Wojdyla`)

(not blocking)
</blockquote></details>

Hmm, I think it was just Rafał doing it this way ;)

---

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/403)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/403)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
