### PR TITLE
[LibOS] Emulate size field for fstat

### PR DESCRIPTION
**Pull request by vijaydhanraj**
## Description of the changes 

This is useful when users want to encrypt and decrypt files within the enclave. Without this commit, functions like
`pf_encrypt_files()` and `pf_decrypt_files()` that are part of `libsgx_util.so` will fail when running inside the enclave.

## How to test this PR? 
Please run `LibOS`, `PAL`, `fs` and LTP tests.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_-xj10amdYy0sbafI):*
We should just call it `libsgx_util`, without the `.so` suffix. This is because we're modifying it to be a static lib, see https://github.com/gramineproject/gramine/pull/773

We'll fix the commit message during final rebase.
___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7_2Kdv4QowyGz8perK:b-iqh7gd) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
> ```C
>             buf->st_nlink = 1;
>             if (handle) {
>                 int ret = pseudo_seek(handle, 0, SEEK_END);
> ```

Usage of `pseudo_seek()` here is wrong for many reasons.

First of all, you could replace all this with a simple:
```
if (handle)
    buf->st_size = hdl->info.str.mem.size;
```

Second, there is still a problem that this only works for cases `handle != NULL`, in other words, it works only for *opened* pseudo-files. If a file was opened, written to, and then closed, then this won't work at all and return `st_size = 0`. Which makes no sense.

The root problem seems to be that pseudo-files do *not* save the file size into `inode->size`, as other file systems do (like chroot, encrypted, tmpfs...). For example, here's how tmpfs updates `inode->size`:
- https://github.com/gramineproject/gramine/blob/d0f64b5417cc86267a320e4b72646e48c4fedfa0/libos/src/fs/tmpfs/fs.c#L260
- https://github.com/gramineproject/gramine/blob/d0f64b5417cc86267a320e4b72646e48c4fedfa0/libos/src/fs/tmpfs/fs.c#L286

We need to do something similar in this file. @vijaydhanraj Could you try my suggestion?

@pwmarcz Hopefully you could help us here, since you implemented this functionality. Is my analysis correct?

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @pwmarcz)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_-xj10amdYy0sbafI):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should just call it `libsgx_util`, without the `.so` suffix. This is because we're modifying it to be a static lib, see https://github.com/gramineproject/gramine/pull/773

We'll fix the commit message during final rebase.
</blockquote></details>

Yes, thanks.
___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7aWMvJ6LGXFBciLSoy:b-fkz920) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Usage of `pseudo_seek()` here is wrong for many reasons.

First of all, you could replace all this with a simple:
```
if (handle)
    buf->st_size = hdl->info.str.mem.size;
```

Second, there is still a problem that this only works for cases `handle != NULL`, in other words, it works only for *opened* pseudo-files. If a file was opened, written to, and then closed, then this won't work at all and return `st_size = 0`. Which makes no sense.

The root problem seems to be that pseudo-files do *not* save the file size into `inode->size`, as other file systems do (like chroot, encrypted, tmpfs...). For example, here's how tmpfs updates `inode->size`:
- https://github.com/gramineproject/gramine/blob/d0f64b5417cc86267a320e4b72646e48c4fedfa0/libos/src/fs/tmpfs/fs.c#L260
- https://github.com/gramineproject/gramine/blob/d0f64b5417cc86267a320e4b72646e48c4fedfa0/libos/src/fs/tmpfs/fs.c#L286

We need to do something similar in this file. @vijaydhanraj Could you try my suggestion?

@pwmarcz Hopefully you could help us here, since you implemented this functionality. Is my analysis correct?
</blockquote></details>

Thanks @dimakuv, will try the suggestions.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7bGuSN3jU_RUdav-5a:b5ew9lj) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
First of all, I don't understand the the justification:

>pf_encrypt_files() and pf_decrypt_files() that are part of libsgx_util.so will fail when running inside the enclave.

Does that mean you want to encrypt and decrypt files that are in a `pseudo` type FS? And if so, why not fix these functions? They are part of Gramine.

Also, this change will cause `/proc` in Gramine to behave differently from real Linux `/proc` (which, AFAIK, returns size 0 in both `stat` and `fstat`). Do you want that?

As for setting `inode->size` - we cannot do that, because the content of a pseudo-file is only generated when you open it (and each time you open it, it might generate a different content with different size). This is also the reason why `/proc/` returns 0.

Finally, if you do want to return size from `fstat()`, then @dimakuv's suggestion seems right, and you could ultimately look at `hdl->info.str.mem.size` (but make sure you use the right lock!)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7bNb1b9YIpilUkp0Zz):*
This explanation makes no sense to me. Why do we need this PR exactly?

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7bNb1b9YIpilUkp0Zz):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This explanation makes no sense to me. Why do we need this PR exactly?
</blockquote></details>

@boryspoplawski can you please see my other comment and see if it makes things a little clear?
___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7bW7wp62et-DRh8BN1:b-tw76gc) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
> Does that mean you want to encrypt and decrypt files that are in a pseudo type FS? 

The idea is an application running inside the enclave may want to encrpt/decrypt files using `libsgx_util` library. But the issue is when trying to load the wrap key, it fails as the size is 0. Please see this,
1. https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/pf_util.c#L243
2. https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L66
3. https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L57

Since the size returned is 0, `fread` here, https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L100 fails and we stop.

> Also, this change will cause /proc in Gramine to behave differently from real Linux /proc (which, AFAIK, returns size 0 in both stat and fstat). Do you want that?

No, but thanks for pointing this out. I'm not sure how we want to tackle this.

> (and each time you open it, it might generate a different content with different size)

Is this true even for `/dev/attesation/keys/default`? I thought this is a pseudo file but the size would be constant.

> Finally, if you do want to return size from fstat(), then @dimakuv's suggestion seems right, and you could ultimately look at hdl->info.str.mem.size (but make sure you use the right lock!)

Got it, thanks.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7be58z2O7w4iyHDOOL:bt1s7cd) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> Does that mean you want to encrypt and decrypt files that are in a pseudo type FS? 

The idea is an application running inside the enclave may want to encrpt/decrypt files using `libsgx_util` library. But the issue is when trying to load the wrap key, it fails as the size is 0. Please see this,
1. https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/pf_util.c#L243
2. https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L66
3. https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L57

Since the size returned is 0, `fread` here, https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L100 fails and we stop.

> Also, this change will cause /proc in Gramine to behave differently from real Linux /proc (which, AFAIK, returns size 0 in both stat and fstat). Do you want that?

No, but thanks for pointing this out. I'm not sure how we want to tackle this.

> (and each time you open it, it might generate a different content with different size)

Is this true even for `/dev/attesation/keys/default`? I thought this is a pseudo file but the size would be constant.

> Finally, if you do want to return size from fstat(), then @dimakuv's suggestion seems right, and you could ultimately look at hdl->info.str.mem.size (but make sure you use the right lock!)

Got it, thanks.
</blockquote></details>

We should probably change `tools/sgx/pf_util.c` not to use fstat, but hardcode the key length (assuming it's really constant length). This PR definitely does things we don't want to do

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7hOAHd13wOw557t2wY:bkqor9u) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We should probably change `tools/sgx/pf_util.c` not to use fstat, but hardcode the key length (assuming it's really constant length). This PR definitely does things we don't want to do
</blockquote></details>

Yes, for the case mentioned above if we modify the tool, it should be good enough. And for the case when a directory with many files and other subdirectories is passed, `readdir` and `seek` set of APIs be enough in Gramine? Is my understanding correct?

Do we want to close this PR and open another PR fixing the `pf_util` or change this PR itself?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7jpvopEGKRRkvQ0FtZ:b-v53zse) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
>  And for the case when a directory with many files and other subdirectories is passed, readdir and seek set of APIs be enough in Gramine?

I did not understand this. What are you talking about?

> Do we want to close this PR and open another PR fixing the pf_util or change this PR itself?

New PR

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7oBRLODMGJdvzMXEPV:be0cf9n) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

>  And for the case when a directory with many files and other subdirectories is passed, readdir and seek set of APIs be enough in Gramine?

I did not understand this. What are you talking about?

> Do we want to close this PR and open another PR fixing the pf_util or change this PR itself?

New PR
</blockquote></details>

Wow, looks like the situation is much more complicated, and this PR is incorrect then...

I suggest to close this PR and open a new one -- there, as Borys suggests, you should modify `tools/sgx/pf_util.c` and just hard-code the size of the key (and drop the `fstat()` calling).

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7pbsfx1fBuOq-xh7D_:b-4k65vu) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
> I did not understand this. What are you talking about?

The above discussion was about loading the wrap key. But once this is done, the application could try to encrypt/decrypt more files, directories, and subdirectories that were passed as input. So, wanted to see if there would be some gaps in getting `stat` information for these.

But it looks like there shouldn't be any issues using `readdir` and `seek` APIs to get this info.

Yes, I will close this one and create a new PR to fix the tool.

> just hard-code the size of the key (and drop the fstat() calling).

@dimakuv why hard code, can't we use `fseek`, yes this would need some more modification but would be more flexible.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7pejjS6eCRhB3ZZ7_U:b5t1apv) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> I did not understand this. What are you talking about?

The above discussion was about loading the wrap key. But once this is done, the application could try to encrypt/decrypt more files, directories, and subdirectories that were passed as input. So, wanted to see if there would be some gaps in getting `stat` information for these.

But it looks like there shouldn't be any issues using `readdir` and `seek` APIs to get this info.

Yes, I will close this one and create a new PR to fix the tool.

> just hard-code the size of the key (and drop the fstat() calling).

@dimakuv why hard code, can't we use `fseek`, yes this would need some more modification but would be more flexible. 
</blockquote></details>

Yes, Vijay, you're right -- no need to hard-code, you can use `fseek`.

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7ranrX0dC5cGKSwHsG:bnr155c) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, Vijay, you're right -- no need to hard-code, you can use `fseek`.
</blockquote></details>

It looks like we can't use `fseek` as the `glibc` library implements this using `fstat`. Please see here, https://code.woboq.org/userspace/glibc/libio/fileops.c.html#970.

So, is hardcoding the only option? Any thoughts?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7rf9z3DN-n5vfMVHQD:b5w0muv) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

It looks like we can't use `fseek` as the `glibc` library implements this using `fstat`. Please see here, https://code.woboq.org/userspace/glibc/libio/fileops.c.html#970.

So, is hardcoding the only option? Any thoughts?
</blockquote></details>

`lseek`

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/778)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/778#-N7rx4JQ9QJBffMu-TwK:-N7rx4JQ9QJBffMu-TwL:bux5dfy) (no related file):*
Closing this PR as discussed.
Created https://github.com/gramineproject/gramine/pull/787 to address this issue.

___
___
*[`libos/src/fs/libos_fs_pseudo.c` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/778#-N7_2Kdv4QowyGz8perJ:-N7rwsxQ3MbTOtrZaKnV:bwh3jm0) ([raw file](https://github.com/gramineproject/gramine/blob/6c9d7b30e21acf99afb5a41cabde7709a653bd02/libos/src/fs/libos_fs_pseudo.c#L275)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`lseek`
</blockquote></details>

Thanks `lseek` worked.

**Pull request closed without merging**
